### DISCUSSION TITLE
How to make 1% brightness in HA work with a bulb that has min dps value of 25

### DISCUSSION THREAD

**Discussion by ErikT80** [make-all/tuya-local#1026] [General]
I am currently implementing a lightbulb which has min brightness level of 25. Max is 255. I notice that with the min: 25 and max:255 config I cannot set the brightness in the HA UI to anything lower then 10%. (Getting the error: brightness should be between 25 and 255)

Is there a way to alter the config so 1% (in the UI) will be 26 and 100% --> 255?

Example config:

```
primary_entity:
  entity: light
  dps:
    - id: 1
      name: switch
      type: boolean
      optional: true
      mapping:
        - dps_val: null
          value: false
    - id: 2
      name: brightness
      type: integer
      range:
        min: 25
        max: 255
    - id: 3
      name: color_temp
      type: integer
      optional: true
      range:
        min: 0
        max: 255
      mapping:
        - invert: true
```
