### DISCUSSION TITLE
Request help for writing configs for custom devices

### DISCUSSION THREAD

**Discussion by Artjosh** [make-all/tuya-local#1131] [Q&A] [answered]
Hello, i need to make tuya-local work with more than 20 custom devices made by a company that im working with, all devices powered by tuya....
So im trying all by my self to soon pull request them to this integration.
Lets talk about the first one:

    "active_time": 1695069031,
    "biz_type": 0,
    "category": "gykzq",
    "create_time": 1694436899,
    "icon": "smart/icon/bay1631708374715LSoc/1f2c8e46535aa3d5675c71ebc0bd12bb.png",
    "id": "xxxxxxxxxxxxxxx",
    "ip": "",
    "lat": "xxxxxx",
    "local_key": "xxxxxxxxxxxxxx",
    "lon": "xxxxxxx",
    "model": "LSST6000",
    "name": "Smart Sensor FT",
    "node_id": "0198",
    "online": false,
    "owner_id": "xxxxxxxxxx",
    "product_id": "youtmdgg",
    "product_name": "Smart Sensor FT",
    "status": [
        {
            "code": "on_off",
            "value": false
        },
        {
            "code": "mode",
            "value": false
        },
        {
            "code": "initial_state",
            "value": "desligado"
        },
        {
            "code": "photo_level",
            "value": 0
        },
        {
            "code": "pir_level",
            "value": 1
        },
        {
            "code": "load_timer",
            "value": 1
        }
    ],
    "sub": true,
    "time_zone": "+08:00",
    "uid": "xxxxxxxxxxxxxxx",
    "update_time": 1695674784,
    "uuid": "xxxxxxxxx",
    "mapping": {
        "102": {
            "code": "on_off",
            "type": "Boolean",
            "values": {}
        },
        "103": {
            "code": "mode",
            "type": "Boolean",
            "values": {}
        },
        "104": {
            "code": "initial_state",
            "type": "Enum",
            "values": {
                "range": [
                    "desligado",
                    "ligado",
                    "ultimo_estado"
                ]
            }
        },
        "107": {
            "code": "photo_level",
            "type": "Integer",
            "values": {
                "unit": "",
                "min": 0,
                "max": 30,
                "scale": 0,
                "step": 1
            }
        },
        "109": {
            "code": "pir_level",
            "type": "Integer",
            "values": {
                "unit": "",
                "min": 1,
                "max": 8,
                "scale": 0,
                "step": 1
            }
        },
        "110": {
            "code": "load_timer",
            "type": "Integer",
            "values": {
                "unit": "s",
                "min": 1,
                "max": 3600,
                "scale": 0,
                "step": 1
            }
        }
    }

im able to use tinytuya to change all thoses DP though code, and im already able to use the first and second DP though the HA UI, but not yet both at same time... idk why or what im missing 
first i tried creating a yaml file with this(and it actually works fine/perfect)
```
name: Smart Sensor FT
products:
  - id: youtmdgg
    name: Smart Sensor FT
primary_entity:
  entity: switch
  dps:
    - id: 102
      type: boolean
      name: switch
```
then i tried adding the rest of the DPS, this way, and it just recognized 1 entity....
ofc i were already thinking this first secondary entity isnt right, because as the first one it is boolean and it had already worked as switch in the primary entity, but i was trying a different entity just to see if i put the second diferent it would recognize it, idk, and to see if i could see other type of card available for that entity... but ofc it wasnt working too 
```
name: Smart Sensor FT
products:
  - id: youtmdgg
    name: Smart Sensor FT
primary_entity:
  entity: switch
  dps:
    - id: 102
      type: boolean
      name: switch
secondary_entities:
  - entity: binary_sensor
    name: Mode Sensor
    dps:
      - id: 103
        type: boolean
        name: mode
  - entity: sensor
    name: Initial State
    dps:
      - id: 104
        type: enum
        name: initial_state
        mapping:
          - dps_val: "desligado"
            value: "Off"
          - dps_val: "ligado"
            value: "On"
          - dps_val: "ultimo_estado"
            value: "Last State"
  - entity: sensor
    name: Photo Level
    dps:
      - id: 107
        type: integer
        name: photo_level
  - entity: sensor
    name: PIR Level
    dps:
      - id: 109
        type: integer
        name: pir_level
  - entity: sensor
    name: Load Timer
    dps:
      - id: 110
        type: integer
        name: load_timer
```
then i tried to change the one with binary sensor to switch, it didnt recognized too, 

but then i moved this second DPS to be together with the primary entity(inside), and it worked, ofc that not in the right manner, but for test purposes....(i tried to choosing only one DP only at time( 1 per time) as a primary entity, and it works well too) )
  
 so what im missing is how to use them all in the same .yaml file being them as 1 entity each or something like that
 to me be able to use them as a card/button at the dashboard
  
after that i tried several yaml file configurations, looked into others devices configs and nothing... wasted more than 4 hours on this yesterday, made more than 30 yaml file and nothing works....
if you could point me into the right way on doing this i would be glad.. 
even a whole .yaml file to work with thoses DPS as different entities to me be able to use diferent cards/buttons etc,i would love, to me uses as guide to write the next ones...  if you need more info or something please let me know
