### DISCUSSION TITLE
Help with assigning values in a Bitfield

### DISCUSSION THREAD

**Discussion by mihsu81** [make-all/tuya-local#1199] [Q&A] [answered]
Hi @make-all,

I have an AlecoAir D12 ECO 2.0 dehumidifier for which I'm unable to identify the bitfield's value correctly.
When I use _Query properties_, I get a value of 0 when all is working usually and a value of 1 when the Water Tank is full or removed.
When I use _Get the specifications and properties of the device_, I can see two labels E1 and E2, which activate when the value of dp_id19 becomes 1.
When I use _Query Things Data Model_ I get _"label": ["FULL","E2"],_

Any suggestions?
Thanks in advance.

```json
Query Properties
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 19,
        "time": 1697755687909,
        "value": 1
      }
```
```json
Get the specifications and properties of the device
{
        "code": "fault",
        "name": "故障告警",
        "type": "Bitmap",
        "values": "{\"label\":[\"E1\",\"E2\"]}"
      }
```
```
Query Things Data Model
{
  \"abilityId\":19,
  \"accessMode\":\"ro\",
  \"code\":\"fault\",
  \"description\":\"\",
  \"extensions\":{\"scope\":\"fault\"},
  \"name\":\"故障告警\",
  \"typeSpec\":{
		\"label\":[\"FULL\",\"E2\"],
		\"maxlen\":2,
		\"type\":\"bitmap\",
		\"typeDefaultValue\":0
		}
}
```

**Comment by make-all** [comment, marked as answer]
So it is likely that bit 0 (value 1) is the Tank full indicator, and bit 1 (value 2) is whatever error E2 is.
 What I would do with this info is create two binary_sensor entities - one for "Tank full", and the other for "Fault", which I would still make a catch all, rather than just detecting error 2, to be safe in case undocumented faults exist, or E2 is actually a different bit.  The full fault code should be left as an attribute on the main entity in case anyone wants to check that a fault is really E2 or something else.
```
  - entity: binary_sensor
    class: problem
    name: Tank full
    icon: "mdi:cup-water"
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 1
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    name: Fault
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: 1
            value: false
          - value: true
 ```

**Reply by make-all** [reply]
Also, some devices will sometimes not send the fault dp when there is no fault - if this device is one of those, you will need to make dp id 19 optional in both entities, and in the second one add a mapping for `dps_val: null` to map that to false instead of being picked up by the default mapping to true.

**Comment by mihsu81** [comment]
Thanks a lot for the suggestion.
I ended up with the following sensors:
```yaml
  - entity: binary_sensor
    class: problem
    name: Tank full
    icon: "mdi:cup-water"
    optional: true
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 1
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    name: Fault
    optional: true
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: 1
            value: false
          - dps_val: null
            value: false
          - value: true
```

I've added the same binary sensors to another dehumidifier, AlecoAir D16 HOME, which has different labels.

```
Query Things Data Model
{
\"abilityId\":19,
\"accessMode\":\"ro\",
\"code\":\"fault\",
\"description\":\"\",
\"extensions\":{\"scope\":\"fault\"},
\"name\":\"故障告警\",
\"typeSpec\":{
        \"label\":[\"tankfull\",\"defrost\",\"E1\",\"E2\",\"L3\",\"L4\"],
		\"maxlen\":6,
		\"type\":\"bitmap\",
		\"typeDefaultValue\":0
		}
}
```

Will you create a PR or should I, for these 2 device configs?
