### DISCUSSION TITLE
Brightness control appears to be part of Light Color for a device

### DISCUSSION THREAD

**Discussion by bdf0506** [make-all/tuya-local#1226] [Q&A] [answered]
Might be related to #481 but not sure.

I have a currently unsupported light that I'm trying to build a YAML file to support. While I can change the color of the light without issue using a hex schema, I can't control the brightness using an integer like nearly every other light that is supported with this integration today.

Looking at the debug logs on the Tuya Cloud side, it looks like anytime that the brightness is changed, instead of it changing the DPS for brightness (which is available for this device, but apparently not used for a r/w perspective), it changes the DPS for the Light Color.

In the example here, at 20:58:55 I set the color to a value, and the brightness percentage to 52%. Then at 20:59:05, I kept the color identical and simply changed the brightness to 82%, and you can see that instead of a brightness DPS changing, the Light Color DPS changes.

![image](https://github.com/make-all/tuya-local/assets/5414343/9574c24d-6e2f-458a-87b0-1dcbc04e3a6f)

I tried using the following based on other working examples, but the DPS ID of 6 clearly won't work properly here.
This is the DPS for the light color:
````
    - id: 5
      name: rgbhsv
      type: hex
      force: true
      format:
        - name: h
          bytes: 2
          range:
            min: 0
            max: 360
        - name: s
          bytes: 2
          range:
            min: 0
            max: 1000
        - name: v
          bytes: 2
          range:
            min: 0
            max: 1000
````

and this is the DPS for the brightness:

````
    - id: 6
      name: brightness
      type: integer
      optional: true
      range:
        min: 10
        max: 1000
      mapping:
        - scale: 3.92
````

While it is delayed by 30 min or so, it does look like every now and then it will report the brightness from the device itself in a report event.

![image](https://github.com/make-all/tuya-local/assets/5414343/3adb674a-2669-427f-b04a-f84e45447803)

DPS mappings for reference:
`
{"1":"Switch","2":"Work Mode","3":"Light Switch","4":"Light Mode","5":"Light Color","6":"Brightness","8":"Music Switch","9":"Volume","10":"Music","11":"Music","13":"Scene","14":"Customize Scene Set","15":"Wake Up Set","16":"Sleep Aid Set","18":"Alarm Stop","19":"Status","20":"Timer","101":"Child Lock","102":"行程启动","103":"预览模式","104":"倒计时时间上报","105":"启用预设"}
`

**Comment by bdf0506** [comment]
This is interesting. It appears that the id of 6 isn't useful on this device at all.

If you go into the native light bulb controls in home assistant, you can set a color no problem, but then when you go to the brightness slider it will not work.

Way around this? Call it in a service, and this seems to work. I'd still like to see if there's a way that I can get the normal HA Light controls to work without needing to call it from a service, but I'm not sure how that would be possible.

This works to change color AND set brightness in the same service call:
````
service: light.turn_on
data:
  brightness_pct: 70
  color_name: red
target:
  entity_id: light.white_noise_machine
````

This works to change color ONLY:
````
service: light.turn_on
data:
  color_name: green
target:
  entity_id: light.white_noise_machine
````

This does **NOT** work to change only the brightness:
````
service: light.turn_on
data:
  brightness_pct: 70
target:
  entity_id: light.white_noise_machine
````

**Reply by make-all** [reply]
It seems your device doesn't really support white mode.  maybe renaming the color_mode dp to work_mode, and brightness to something else so those aren't taken into account will help.

**Comment by bdf0506** [comment]
With this code, I get the color mode to work very reliably. In the above post I had dps 5 set to force: true which caused problems. Now it's no longer an issue.

````
primary_entity:
  entity: light
  dps:
    - id: 1
      type: boolean
      name: power
      optional: true
    - id: 3
      type: boolean
      name: switch
    - id: 4
      type: string
      name: effect
      mapping:
        - dps_val: change
          value: Rainbow
        - dps_val: breath
          value: Breath
        - dps_val: light_off
          value: Color
        - dps_val: light_on
          value: White
    - id: 6
      name: brightness
      type: integer
      optional: true
      range:
        min: 10
        max: 1000
      mapping:
        - scale: 3.92
    - id: 5
      name: rgbhsv
      type: hex
      optional: true
      format:
        - name: h
          bytes: 2
          range:
            min: 0
            max: 360
        - name: s
          bytes: 2
          range:
            min: 0
            max: 1000
        - name: v
          bytes: 2
          range:
            min: 0
            max: 1000
````

But there's a problem - I don't have a white mode available to me for a color mode, only an effect. If I set dps 4 to color_mode, the device won't properly set the brightness. 
To further convolute it, on this device, when the mode is set to white, we now want to send brightness via dps 6 and not through the v value of dps 5. If I change dps 4 from effect to color_mode, i'll then see the White option in the HA UI, but brightness doesn't work reliably as mentioned above. And if I am in white, and then change the brightness, rather than it sending the brightness to dps 6, it sends the brightness as part of dps 5 and will then change the light back to the last RGB color instead of keeping it white. Any tips on other things to try to get this to work properly?
