### DISCUSSION TITLE
help to define entity Base64

### DISCUSSION THREAD

**Discussion by Bellavista** [make-all/tuya-local#1257] [Q&A]
Hi everyone, I need help configuring a base64 sensor.
I pulled this sensor information, but I am unable to configure it.
```
  {"abilityId":1,
  "accessMode":"rw",
  "code":"meal_plan",
  "description":"同步到设备端本地，即使设备离线，仍能正常喂食出粮，喂食计划支持6组，共30字节，不足位补零。
  # \nraw格式约定：按照“周期+时间+喂食份数+开关”来实现本地定时，具体如下\\n1，前7个比特位代表周一到周日，二进制转十六进制，占用一个字节，0代表未设置，1代表设置，如0000001，表示周日生效，转换为16进制就是01\
  \n1，前7个比特位代表周一到周日，二进制转十六进制，占用一个字节，0代表未设置，1代表设置，如0000001，表示周日生效，转换为16进制就是01\
  \n2，时间按照小时分钟格式，占用2个字节，分钟和小时，十进制转16进制，如18：50，转为16进制为1232\
  \n3，喂食份数，范围1-48.占用1个字节，十进制转16进制，如12，转为16进制为0c\
  \n4，开关，占用1个字节，00表示关闭，01表示开启\
  \n上述举例，对于APP端时间下发的结果为0112320c01，表示周日，18：50，喂食12份，开启。",
  "extensions":{"iconName":"icon-dp_time3","attribute":"96","trigger":"direct"},
  "name":"喂食计划",
  "typeSpec":{"maxlen":128,"type":"raw"}}**
```
I translated the information written in Chinese but it doesn't really match the exposed value. 
I analyzed the value and obtained the following...
The sensor represents the food distribution planning of my cat food dispenser.
An exsample value exposed is ``` "value": "DAABAQweAgENAAQBDR4DAQ4ABAEOHgYB" ```
I converted the string from base64 to binary and then in decimal i obtain these result
```
 # exsample "value": "DAABAQweAgENAAQBDR4DAQ4ABAEOHgYB"
 # exsample :        hour    minute  portion planned
 # exsample Plan 1: 00001100 00000000 00000001 00000001 --> 12:00 1 meal portion yes planned
 # exsample Plan 2: 00001100 00011110 00000010 00000001 --> 12:30 2 meal portion yes planned
 # exsample Plan 3: 00001101 00000000 00000011 00000000 --> 13:00 3 meal portion no planned
 # exsample Plan 4: 00001101 00011110 00000100 00000001 --> 13:30 4 meal portion yes planned
 # exsample Plan 5: 00001110 00000000 00000101 00000001 --> 14:00 5 meal portion yes planned
 # exsample Plan 6: 00001110 00011110 00000110 00000001 --> 14:30 6 meal portion yes planned
```
Now for me the sensor creation is a mistery, can someone help me!
The "hour" range is 0-23 "minute" range 0-59 "portion" range1-24 and "planned" is only e switch. 
I started whith these ma does not work
by

```
  - entity: sensor
    name: Planning
    icon: "mdi:calendar-multiselect"
    category: config
    dps:
      - id: 1
        type: base64
        name: plan
        optional: true
        format:
          - name: HH Timer 1
            bytes: 1
            range:
              min: 0
              max: 23
          - name: MM Timer 1
            bytes: 1
            range:
              min: 0
              max: 59
          - name: PORTION Timer 1
            bytes: 1
            range:
              min: 1
              max: 24
          - name: PLANNED Timer 1
            bytes: 1
            range:
              min: 0
              max: 1
```

**Comment by make-all** [comment]
`format` is only used to internally decode known multi-value attributes, specifically RGB and HSV options for lightbulbs.
For arbitrary values, you need to use a separate sensor (or at least attribute) for each value to want to extract, and use `mask` to define the bit mapping.

**Reply by Bellavista** [reply]
Hi make-all thank yuo
So for my case if i want the first hour and etc etc  i need someting like these
```
  - entity: sensor
    dps:
      - id: 1
        type: base64
        name: HH Timer 1
        mapping:
          - mask: "FFFFFFFF00000000000000000000000000000000......00000"
      - id: 1
        type: base64
        name: MM Timer 1
        mapping:
          - mask: "00000000FFFFFFFF000000000000000000000000......00000"
       - id: 1
        type: base64
        name: Portion Timer 1
        mapping:
          - mask: "0000000000000000FFFFFFFF0000000000000000......00000"
       - id: 1
        type: base64
        name: Planned Timer 1
        mapping:
          - mask: "000000000000000000000000FFFFFFFF00000000......00000" 
```

**Reply by make-all** [reply]
Yes

**Reply by Bellavista** [reply]
I insered
```
secondary_entities:
  - entity: sensor
    name: Planning
    icon: "mdi:calendar-multiselect"
    category: config
    dps:
      - id: 1
        type: base64
        name: HH Timer 1
        mapping:
          - mask: "FFFFFFFF000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      - id: 1
        type: base64
        name: MM Timer 1
        mapping:
          - mask: "00000000FFFFFFFF0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      - id: 1
        type: base64
        name: Portion Timer 1
        mapping:
          - mask: "0000000000000000FFFFFFFF00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
      - id: 1
        type: base64
        name: Planned Timer 1
        mapping:
          - mask: "000000000000000000000000FFFFFFFF000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```
i restarted homeassistant
but i recive these error
```
2023-11-06 00:42:15.270 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tuya_local platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/sensor.py", line 22, in async_setup_entry
    await async_tuya_setup_platform(
  File "/config/custom_components/tuya_local/helpers/config.py", line 34, in async_tuya_setup_platform
    data[ecfg.config_id] = entity_class(device, ecfg)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/sensor.py", line 45, in __init__
    raise AttributeError(f"{config.config_id} is missing a sensor dps")
AttributeError: sensor_planning is missing a sensor dps
```
Any idea? ....Sure!
