### DISCUSSION TITLE
how to exstract a simple string from DP type raw

### DISCUSSION THREAD

**Discussion by Bellavista** [make-all/tuya-local#1263] [Q&A]
Hi all,
i'm not able to exstract a string from , can someone help me
i have this dpi
```
      {
        "code": "meal_plan",
        "dp_id": 1,
        "type": "Raw",
        "values": "{}"
      },
```
whith this value
```
    {
      "code": "meal_plan",
      "value": "DAABAAweAgANAAMADR4EAA4ABQAOHgYA"
    },
```
I'm trying in different ways the more logigal is
```
secondary_entities:
  - entity: sensor
    name: Planning
    icon: "mdi:calendar-multiselect"
    category: config
    dps:
      - id: 1
        type: string
        name: sensor
```
but i recive always unknow
