### DISCUSSION TITLE
Secondary entities not appearing

### DISCUSSION THREAD

**Discussion by JackJackattack4** [make-all/tuya-local#1308] [Q&A] [answered]
Hello Tuya-local people,

I have created my own yaml code to add a device that is currently unsupported and used to add the device to HA. It worked but not fully.

I can see all primary entities but not the secondary entities in HA. See below the extract showing the entities which I can see.

![Screenshot 2023-11-15 215744](https://github.com/make-all/tuya-local/assets/150105206/7c7ea0b1-4213-4362-a21b-ec58907a5929)

I was expecting to see primary and secondary entities in the attributes of the device. I was expecting to see "Inquire_ID", ID 104 to appear in the attributes. There must be something I missed somewhere. Does anyone know what this could be?

This is the yaml code I made on my own to add the device 
```
name: EVI DC Inverter Heat Pump
products:
  - id: eb9a44bd30916d3150ftup
    name: A2 Pro
  - id: eb313fb004c523375cxgzw
    name: A2 Pro 2
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: ON-OFF
      type: boolean
      mapping:
        - dps_val: false
          value: "Off"
        - dps_val: true
          value: "On"
    - id: 2
      name: Target Temp.
      type: integer
      range:
        min: 5
        max: 60
    - id: 3
      name: Current Temp.
      type: integer
    - id: 4
      name: Working Mode
      type: string
      mapping:
        - dps_val: hot
          value: Heating
        - dps_val: cold
          value: Cooling
        - dps_val: hotwater
          value: Hot Water
        - dps_val: hot_hotwater
          value: Heating + Hot Water
        - dps_val: cold_hotwater
          value: Cooling + Hot Water
    - id: 5
      name: Setting Temp. Type
      type: string
      mapping:
        - dps_val: HotWater
          value: Hot Water
        - dps_val: Hot
          value: Heating
        - dps_val: Cold
          value: Cooling
    - id: 103
      name: Working Status
      type: string
      mapping:
        - dps_val: on
          value: On
        - dps_val: off
          value: Off
        - dps_val: defrost
          value: Defrost
        - dps_val: antifrozen
          value: Antifrozen
secondary_entities:
  - entity: select
    name: Inquire_ID
    category: config
    dps:
      - id: 104
        # mappings based on dev portal info, observed values and manufacturer's manual. DPID 104 (para. Inquiry) specifies which parameter is inquired and the value is returned using DPID 105 (Inquiry Value).
        type: string
        name: Para. Inquiry
        mapping:
          - dps_val: 1
            value: version no.
          - dps_val: 2
            value: ambient temp.
          - dps_val: 3
            value: water tank temp.
          - dps_val: 4
            value: outlet water temp.
          - dps_val: 5
            value: inlet water temp.
          - dps_val: 6
            value: evaporator coil temp.
          - dps_val: 7
            value: exhaust gas temp.
          - dps_val: 8
            value: condenser coil temp. (after throttling)
          - dps_val: 9
            value: suction temp.
          - dps_val: 10
            value: module temp.
          - dps_val: 11
            value: main valve opening degrees
          - dps_val: 12
            value: auxiliary valve opening degrees
          - dps_val: 13
            value: exhaust gas valve opening degrees
          - dps_val: 14
            value: Fan speed
          - dps_val: 15
            value: running frequency
          - dps_val: 16
            value: AC voltage
          - dps_val: 17
            value: DC voltage
          - dps_val: 18
            value: current of whole unit
          - dps_val: 19
            value: compressor current
          - dps_val: 20
            value: output power
          - dps_val: 21
            value: EVI plate heat exchanger inlet sensor
          - dps_val: 22
            value: EVI plate heat exchanger outlet sensor
          - dps_val: 23
            value: low pressure
          - dps_val: 24
            value: high pressure
          - dps_val: 25
            value: error code
          - dps_val: 26
            value: limited frequency code
          - dps_val: 27
            value: LCD Controller version
          - dps_val: 28
            value: MCU1 version
          - dps_val: 29
            value: MCU2 version
          - dps_val: 30
            value: MCU3 version
          - dps_val: 31
            value: Error History
  - entity: select
    name: Inquire_Value
    category: config
    dps:
      - id: 105
        # DPID 104 (para. Inquiry) specifies which parameter is inquired and the value is returned using DPID 105 (Inquiry Value).
        type: integer
        name: Inquiry Value
  - entity: select
    name: Set_ID
    category: config
    dps:
      - id: 106
        # mappings based on dev portal info, observed values and manufacturer's manual. DPID 106 (Para. Setting) specifies which parameter is set using the value in DPID 107 (Set Value).
        type: string
        name: Para. Setting
        mapping:
          - dps_val: d01
            value: Heating Temp Setting
          - dps_val: d02
            value: Heating Water Tank Temp Setting
          - dps_val: d03
            value: Cooling Temp Setting
          - dps_val: d04
            value: Restart Temp Difference 
          - dps_val: d05
            value: Selection on Control basis
          - dps_val: d06
            value: Setting Temp Of Electric Heater
          - dps_val: d07
            value: Deviation Time of Electric Heater Start
          - dps_val: d08
            value: Evaporator coil Temp to enter into defrosting
          - dps_val: d09
            value: Evaporator coil Temp to exit defrosting 
          - dps_val: d10
            value: Defrosting Cycle Period
          - dps_val: d11
            value: Defrosting Time
          - dps_val: d12
            value: Selection on Control after temp is reached
          - dps_val: d13
            value: Ambient temp for Stopping and Starting machine
          - dps_val: d14
            value: Temp Difference of Inlet and Outlet water for heat pump's
          - dps_val: d15
            value: Working Way of Water Pump
  - entity: select
    name: Set_Value
    category: config
    dps:
      - id: 107
        # DPID 106 (Para. Setting) specifies which parameter is set using the value in DPID 107 (Set Value).
        type: integer
        name: Set Value
```
