### DISCUSSION TITLE
Can't get select entity to work or show up

### DISCUSSION THREAD

**Discussion by dkvk** [make-all/tuya-local#1412] [Q&A] [answered]
I've created this yaml
```
name: Dual dimmer module
products:
  - id: isstlkzmlurfcc6e
    name: WiFi/BLE  Dimmer module two ways
primary_entity:
  entity: light
  name: Light 1
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: integer
      name: brightness
      range:
        min: 10
        max: 1000
  secondary_entities:
  - entity: select
    name: "Power-on status memory"
    category: config
    dps:
      - id: 14
        type: string
        name: option
        mapping:
          - dps_val: "on"
            value: "Power On"
          - dps_val: "off"
            value: "Power Off"
          - dps_val: memory
            value: "Last known state"
```
The Things Data Model have given me:
```
…
          {
            "abilityId": 14,
            "accessMode": "rw",
            "code": "relay_status",
            "description": "",
            "extensions": {
              "iconName": "setting icon-setting",
              "attribute": "128"
            },
            "name": "Power-on status memory",
            "typeSpec": {
              "range": [
                "off",
                "on",
                "memory"
              ],
              "type": "enum",
              "typeDefaultValue": "off"
            }
          }
```
The select entity is not showing up at all, I don't either get any error message.

Anyone seeing any error or has any tips on what to do?
