### DISCUSSION TITLE
Device Type not available for selection after adding device yml

### DISCUSSION THREAD

**Discussion by njoye** [make-all/tuya-local#1453] [Q&A] [answered]
I added a device yml file to my devices/ directory, restarted HA and wanted to integrate my Revolt thermostat with HA. I tested the values and connection with TinyTuya before creating the yml. Here is the yml

```yml
name: Thermostatic Radiator Valve
products:
  - id: tfbhw0mg
    name: Revolt ZX-5442
primary_entity:
  entity: climate
  dps:
    - id: 3
      name: current_temperature
      type: integer
      readonly: true
      mapping:
        - scale: 10
    - id: 107
      type: integer
      name: target_temperature
      mapping:
        - scale: 2
 ```
 It is very basic. However, when I connect to my device (through it's hub), it only shows the following device types for selection

<img width="452" alt="Bildschirmfoto 2023-12-26 um 09 16 46" src="https://github.com/make-all/tuya-local/assets/14947522/48cfa1cd-5a1d-4772-b6c1-b2996576b12b">

Is there any way I can fix this issue? Is this a known problem that I couldn't find yet?
