### DISCUSSION TITLE
Thermostat not reacting & not updating values in HA

### DISCUSSION THREAD

**Discussion by njoye** [make-all/tuya-local#1459] [Q&A]
I have Revolt ZX-5442 thermostats that are connected through a WiFi/BLE gateway. I have two issues with these:

1. When I don't interact with them through TuyaLocal for a while, it seems that they become unresponsive and I can't set the temperature anymore. Only when I open the Tuya App, then TuyaLocal again does it work. I worked with TinyTuya before and had this bug fixed through calling `updatedps()` on my thermostat before setting the temperature. This adds additional call time, but fixed the unresponsiveness issue.
2. Generally: The thermostat doesn't seem to push values by itself - only when the temperature is changed (if that works) does the current temperature value change in HA. I am using Poll mode already but it seems that that isn't helping. Again, calling `updatedps()` in TinyTuya had fixed that issue when I was testing the thermostats.

Did anyone already have similar situations? Looking forward to any help I can get.
@markpaxton - FYI

@make-all Would using TinyTuya to call `updatedps()` from the outside help? Is there any way I can enforce the DP update through TuyaLocal ?

**Comment by make-all** [comment]
Generally Tuya devices only accept one local connection, so calling updatedps from tinytuya is likely to cause more problems than it solves.

The `force: true` attribute was designed to fix such problems, it should result in updatedps being called once a minute for the dps with that tag.

**Reply by njoye** [reply]
Thanks for the info regarding TinyTuya - I was just interested because it seemed that after opening the thermostat through the app, the values in HA were also updated. Will try the force attribute and report back.

**Reply by njoye** [reply]
Is it enough to simply change the configuration file for the device & restart HA or do I need to remove and add the device again for the force attribute to be active ?

**Reply by make-all** [reply]
Restarting HA should be enough to pick up config file changes

**Reply by njoye** [reply]
Okay, in that case - I changed the config file before I went to sleep yesterday, restarted HA, and the values from my thermostats are 9 hours old (the time of the restart) this morning. Would enabling debugging for TuyaLocal help in identifying my issue? FYI - below is my current configuration file for the thermostats - I know it is not 100% up to the standard for a PR yet, but I wanted to make sure basic functionality is given before that. I also run them in Poll Only mode since I have six thermostats on one gateway and wanted to avoid the connection issue.

```yml
name: Thermostatic Radiator Valve
products:
  - id: tfbhw0mg
    name: Revolt ZX-5442
primary_entity:
  entity: climate
  dps:
    - id: 2
      name: set_temperature
      type: integer
    - id: 3
      name: current_temperature
      type: integer
      readonly: true
      force: true
      mapping:
        - scale: 10
    - id: 107
      type: integer
      name: temperature
      min: 1
      max: 59
      mapping:
        - scale: 2
    - id: 4
      type: string
      name: mode
secondary_entities:
    - entity: lock
      name: child_lock
      dps:
        - id: 7
          type: boolean
          name: child_lock
          mapping:
            - dps_val: true
              icon: "mdi:lock"
            - dps_val: false
              icon: "mdi:lock-open"
    - entity: sensor
      name: battery
      dps:
        - id: 21
          name: sensor
          type: integer
          unit: V
          mapping:
            - scale: 42
    - entity: binary_sensor
      name: window
      dps:
        - id: 110
          name: sensor
          type: boolean
          mapping:
            - dps_val: true
              icon: "mdi:window-open-variant"
            - dps_val: false
              icon: "mdi:window-closed-variant"
```

After opening the app, the values started changing again.
