### DISCUSSION TITLE
3 phase metering circuit breaker sends data too rarely

### DISCUSSION THREAD

**Discussion by aver-ua** [make-all/tuya-local#1483] [Q&A] [answered]
i have Tuya 3 phase metering circuit breaker that is not yet supported by tuya-local. 
but i've created config for it and placed requset for support #1429. 
all works fine, but  there is a slight problem with sensors values updates. they are updated only every 10 minutes. for sensors of the `total_increasing` class this does not matter, but for voltage and current I would like a little more often (1-3 minutes). setting `force: true` has no effect.
if I change one of the MCB's configuration parameters in HA (for example, current or voltage threshold), all values of sensors also immediately change. if I open MCB in the Tuya application, the sensor values begin to update once per 1-5 second.
so, is there any suggestion how it may be changed? or it is not possible?

**Comment by aver-ua** [comment]
I will answer to myself..
there is an ugly workaround: create an automation that starts every N minutes 
```yaml
trigger:
  - platform: time_pattern
    minutes: /2 # every 2 minutes
```
and sets MCB's entity "Overvoltage Threshold" to any value (260V, for example)
after that all entities (sensors) get updated

**Reply by make-all** [reply]
Some devices have a specific dp for this type of polling, so you don't affect any config values. The dp is typically write-only so does not show in HA logs, but you may be able to see the app using it in the Tuya cloud logs.

**Reply by aver-ua** [reply]
@make-all , can You explain more detailed how to view this logs? thanks.

**Reply by make-all** [reply]
I think the section is called device debugger on the iot.tuya.com site. I haven't been there since they changed the authentication, so it may have changed

**Reply by aver-ua** [reply, marked as answer]
this is what I found out after looking at the device log at iot.tuya.com.
there is dp number 109 called "online_state":
```json
{
          "abilityId": 109,
          "accessMode": "rw",
          "code": "online_state",
          "description": "",
          "name": "Online Status",
          "typeSpec": {
            "range": [
              "online",
              "offline"
            ],
            "type": "enum",
            "typeDefaultValue": "online"
          }
        }
```
after setting it to value "online" device starts reporting all dp's values immediately if any of them are changed.
I saw in the logs that this is done by the Tuya mobile application.
and this goes on for 30 minutes. after this time has elapsed, the device returns to the dps transfer every 10 minutes.

**Reply by aver-ua** [reply]
@make-all , so there is a question.
this dp 109 in config looks like:
```yaml
  - entity: binary_sensor
    class: connectivity
    category: diagnostic
    dps:
      - id: 109
        type: string
        name: sensor
        mapping:
          - dps_val: online
            value: true
          - dps_val: offline
            value: false
```
since the actual purpose of this dp is completely different, how config should be changed?
