### DISCUSSION TITLE
Strange HEX Format : how to decode it ? (ev charger)

### DISCUSSION THREAD

**Discussion by feeling001** [make-all/tuya-local#1561] [Q&A] [answered]
I'm currently writing the device yaml file to enable support of ECOPOINT EV Charger. 
( https://github.com/make-all/tuya-local/issues/1549 )

Almost everything is OK except the decoding of the phase information.

In my case this is the dps id "6".

The data model is : 
> {\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"phase_a\",\"description\":\"1、相电压，电流及功率\\n2，大端模式，HEX格式，共8个字节\\n3，单位精度：电压，2字节，单位0.1V。电流，3字节，单位 0.001A 。A相有功功率，3字节，单位0.001kW\\n4，报文格式\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"A相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},

The translation of the Chinese part is : 
> 1. Phase voltage, current and power
> 2, big-endian mode, HEX format, 8 bytes in total
> 3, unit accuracy: voltage, 2 bytes, unit 0.1V. Current, 3 bytes, unit 0.001A. Phase A active power, 3 bytes, unit 0.001kW
> 4, message format

I get the following data in my log : 
> EV Charger received {"6": "CU0ABbIAAVI=", "full_poll": false}
> EV Charger received {"6": "CUQABbQAAT4=", "full_poll": false}

I tried a b64 decoder -> not correct. Any idea how to decode it (and using it in tuya-local) ?
HELP :-)

**Comment by feeling001** [comment, marked as answer]
**SOLVED !**

CU0ABbIAAVI to hexadecimal is 094d0005b2000152

first two bytes of 094d0005b2000152 is  094d and it is 2381 in decimal, so 238.1 volt ... 

Okey, but how to convert this with mappings ;-)  ...

eazy :
```
  - entity: sensor
    name: Phase_1_A
    dps:
      - id: 6 # phase_1
        type: base64
        name: sensor
        optional: true
        unit: A
        mapping:
          - mask: "0000FFFFFF000000"
            scale: 1000
```

Nice Job make-all !

L.
