### DISCUSSION TITLE
Cannot get Cecotec BigDry connected

### DISCUSSION THREAD

**Discussion by osigida** [make-all/tuya-local#1567] [Q&A] [answered]
I'm testing a new device: dehumidifier `BigDry 9000 Professional` by Cecotec

ID and name by Tuya platform: 
```
    "product_id": "zt87jwdngs1hsaqd",
    "product_name": "BigDry 9000 Professional",
```

The data model looks like that:
```
{
  "result": {
    "model": {
      "modelId": "0000031fns",
      "services": [
        {
          "actions": [],
          "code": "",
          "description": "",
          "events": [],
          "name": "默认服务",
          "properties": [
            {
              "abilityId": 1,
              "accessMode": "rw",
              "code": "switch",
              "description": "",
              "name": "开关",
              "typeSpec": {
                "type": "bool",
                "typeDefaultValue": false
              }
            },
            {
              "abilityId": 3,
              "accessMode": "rw",
              "code": "dehumidify_set_enum",
              "description": "枚举值数值顺序，需要从小到大排序，否则使用公版APP面板显示会有问题",
              "name": "除湿值",
              "typeSpec": {
                "range": [
                  "40",
                  "45",
                  "50",
                  "55",
                  "60",
                  "65",
                  "70",
                  "75",
                  "80"
                ],
                "type": "enum",
                "typeDefaultValue": "40"
              }
            },
            {
              "abilityId": 4,
              "accessMode": "rw",
              "code": "fan_speed_enum",
              "description": "",
              "name": "Speed",
              "typeSpec": {
                "range": [
                  "low",
                  "high"
                ],
                "type": "enum",
                "typeDefaultValue": "low"
              }
            },
            {
              "abilityId": 5,
              "accessMode": "rw",
              "code": "mode",
              "description": "",
              "name": "工作模式",
              "typeSpec": {
                "range": [
                  "dehumidify",
                  "drying"
                ],
                "type": "enum",
                "typeDefaultValue": "dehumidify"
              }
            },
            {
              "abilityId": 6,
              "accessMode": "ro",
              "code": "humidity_indoor",
              "description": "",
              "name": "室内湿度",
              "typeSpec": {
                "max": 100,
                "min": 0,
                "scale": 0,
                "step": 1,
                "type": "value",
                "typeDefaultValue": 0,
                "unit": "%"
              }
            },
            {
              "abilityId": 7,
              "accessMode": "ro",
              "code": "temp_indoor",
              "description": "",
              "name": "室内温度",
              "typeSpec": {
                "max": 100,
                "min": 0,
                "scale": 0,
                "step": 1,
                "type": "value",
                "typeDefaultValue": 0,
                "unit": "℃"
              }
            },
            {
              "abilityId": 10,
              "accessMode": "rw",
              "code": "anion",
              "description": "",
              "name": "负离子",
              "typeSpec": {
                "type": "bool",
                "typeDefaultValue": false
              }
            },
            {
              "abilityId": 14,
              "accessMode": "rw",
              "code": "sleep",
              "description": "",
              "name": "睡眠模式",
              "typeSpec": {
                "type": "bool",
                "typeDefaultValue": false
              }
            },
            {
              "abilityId": 16,
              "accessMode": "rw",
              "code": "child_lock",
              "description": "",
              "name": "童锁",
              "typeSpec": {
                "type": "bool",
                "typeDefaultValue": false
              }
            },
            {
              "abilityId": 19,
              "accessMode": "ro",
              "code": "fault",
              "description": "",
              "name": "故障告警",
              "typeSpec": {
                "label": [
                  "E1",
                  "E2"
                ],
                "maxlen": 2,
                "type": "bitmap",
                "typeDefaultValue": 0
              }
            }
          ]
        }
      ]
    }
  },
  "success": true,
  "t": 1706177086498,
  "tid": "2b08d1abbb6911eeb846e2ba4cc47aff"
}
```

I've created following config: 

```
name: Dehumidifier
products:
  - id: zt87jwdngs1hsaqd
    name: BigDry 9000 Professional
primary_entity:
  entity: humidifier
  class: dehumidifier
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: false
          icon: "mdi:air-humidifier-off"
          icon_priority: 2
        - dps_val: true
          icon: "mdi:air-humidifier"
          icon_priority: 4
    - id: 2
      name: Humidity
      class: humidity
      type: string
      mapping:
        - dps_val: 40
          value: 40
        - dps_val: 45
          value: 45
        - dps_val: 50
          value: 50
        - dps_val: 55
          value: 55
        - dps_val: 60
          value: 60
        - dps_val: 65
          value: 65
        - dps_val: 70
          value: 70
        - dps_val: 75
          value: 75
        - dps_val: 80
          value: 80
    - id: 5
      name: mode
      type: string
      mapping:
        - dps_val: dehumidify
          value: Dehumidify
        - dps_val: drying
          value: Drying
secondary_entities:
  - entity: fan
    dps:
      - id: 4
        name: Speed
        type: string
        icon: "mdi:fan"
        mapping:
          - dps_val: low
            value: Low
          - dps_val: high
            value: High
  - entity: sensor
    name: Indoor Humidity
    category: diagnostic
    class: current_humidity
    readonly: true
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: sensor
    name: Indoor Temperature
    category: diagnostic
    class: current_temperature
    readonly: true
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: C
        class: measurement

  - entity: switch
    name: Anion
    category: config
    dps:
      - id: 10
        type: boolean
        name: switch
        mapping:
          - dps_val: false
            icon: "mdi:minus-circle-off-outline"
          - dps_val: true
            icon: "mdi:minus-circle-multiple-outline"

  - entity: switch
    name: Sleep
    category: config
    dps:
      - id: 14
        type: boolean
        name: switch
        mapping:
          - dps_val: false
            icon: "mdi:sleep-off"
          - dps_val: true
            icon: "mdi:sleep"

  - entity: lock
    name: Child lock
    icon: "mdi:hand-back-right-off"
    category: config
    dps:
      - id: 16
        type: boolean
        name: lock

  - entity:
    name: Status
    class: enum
    category: diagnostic
    dps:
      - id: 19
        type: bitfield
        name: sensor
        readonly: true
        # Docs mention E1 and E2, it isn't clear which is tank full, so for now
        # treat both as that.
        mapping:
          - dps_val: 0
            value: Normal
            icon: "mdi:check-circle-outline"
            icon_priority: 2
          - dps_val: 1
            value: E1
            icon: "mdi:alert-circle-outline"
            icon_priority: 2
          - dps_val: 2
            value: E2
            icon: "mdi:alert-circle-outline"
            icon_priority: 2
          - dps_val: 4
            value: Tank full
            icon: "mdi:cup-water"
            icon_priority: 2
          - dps_val: 8
            value: Defrosting
            icon: "mdi:snowflake-melt"
            icon_priority: 2
```

but whatever I do HomeAssistant does not recognise the device properly and suggests some random options as device type: 
<img width="382" alt="Screenshot 2024-01-25 at 17 08 05" src="https://github.com/make-all/tuya-local/assets/6461608/4154e1d5-dffb-4ab6-85da-50c0b6c63542">

Any hists, please? What did I do wrong?
