### DISCUSSION TITLE
Fan Control

### DISCUSSION THREAD

**Discussion by Smash5454** [make-all/tuya-local#1607] [Ideas]
Just switching over does anyone know a way to control a Fan  the App let's you control the speed. In HA I don't see a way to control anything other than the On Off Function.

**Comment by make-all** [comment]
A fan entity will normally present the speed as primary control.  What device did you select when you added it?

**Reply by Smash5454** [reply]
Set it with fan it shows the slider but it doesn't control anything.

**Comment by tschiex** [comment]
I have a similar problem, so I will continue here. 

I have a Casafan Eco Genuino fan and I extracted its information from the Tuya Cloud using the suitable API Query request:

```
{
  "result": {
    "model": "{\"modelId\":\"000001nbqb\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"name\":\"运行模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"normal\",\"sleep\",\"nature\"]}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"name\":\"风速\",\"typeSpec\":{\"type\":\"value\",\"max\":6,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"档\"}},{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"fan_direction\",\"description\":\"\",\"name\":\"运行方向\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"forward\",\"reverse\"]}},{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"name\":\"定时\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"off\",\"1hour\",\"2hour\",\"4hour\",\"8hour\"]}}]}]}"
  },
  "success": true,
  "t": 1736708507251,
  "tid": "abf472b0d11711efbbc9c2b21b10ca93"
}
```

I initially set it up using the "local tuya" extension and it works fine. 
I have control of everything: on/off, speed, timer, mode, direction.
So far, so good.

I wanted to try "tuya-local" which directly supports other Tuya devices I have. 
It works brillantly with these devices but my casafan fan is not supported. 

So, I wrote a yaml file and copied it into the devices folder on my "Supervised" installation (in `custom_components/tuya_local/devices/casafan_ceiling_fan.yaml`):

```
name: Ceiling fan
products:
  - id: 000001nbqb
    name: Casafan Eco Genuino
primary_entity:
  entity: fan
  translation_only_key: fan_with_presets
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: normal
          value: normal
        - dps_val: sleep
          value: silence
        - dps_val: nature
          value: nature
    - id: 3
      type: integer
      name: speed
      range:
        min: 1
        max: 6
    - id: 8
      type: string
      name: direction
secondary_entities:
  - entity: select
    translation_key: timer
    category: config
    dps:
      - id: 22
        type: string
        name: option
        mapping:
          - dps_val: "off"
            value: "off"
          - dps_val: "1hour"
            value: "1h"
          - dps_val: "2hour"
            value: "2h"
          - dps_val: "4hour"
            value: "4h"
          - dps_val: "8hour"
            value: "8h"
```

When I add the device in tuya-local, tuya-local offers me the correct "casafan_ceiling_fan" choice directly but then I only have 2 controls (2 entities): the on off switch and the "timer" enum. No entity for speed control,  mode control, or direction control:

![Capture d’écran du 2025-01-12 21-40-08](https://github.com/user-attachments/assets/4b9fd2bb-66e8-4a52-aeea-065f0d180a3e)


Would the co-existing "local tuya" extension be the issue here? 
Is this expected or did I make stupid error somehow?
