### DISCUSSION TITLE
Please help with Integrating TDS Readings from Water Quality Monitor

### DISCUSSION THREAD

**Discussion by jahm2u** [make-all/tuya-local#1811] [Q&A] [answered]
Hey guys, I've integrated a water quality monitor with Home Assistant using Tuya Local. Everything's working except for the TDS (Total Dissolved Solids) readings. The TDS data is visible in the Tuya API and I see we also have some TDS alarms found in devices/phw218_waterquality_monitor.yaml in Tuya Local, but it's not showing up as an entity in Home Assistant.

This is the high warning that I can find in your config for devices from this monitor.
```
- entity: number
    name: High TDS warning
    category: config
    icon: "mdi:water-opacity"
    dps:
      - id: 112
        type: integer
        name: value
        unit: ppm
        range:
          min: 0
          max: 199999
```

However, I can also see that the TDS data is being returned by the API
```"mapping": {
            "1": {
                "code": "tds_in",
                "type": "Integer",
                "values": {
                    "unit": "ppm",
                    "min": 0,
                    "max": 9999,
                    "scale": 0,
                    "step": 1
                }
            },
            "2": {
                "code": "temp_current",
                "type": "Integer",
                "values": {
                    "unit": "\u00b0C",
                    "min": 0,
                    "max": 800,
                    "scale": 1,
                    "step": 1
                }
            },
            "7": {
                "code": "battery_percentage",
                "type": "Integer",
                "values": {
                    "unit": "%",
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            }
        },
 ```
 
 Can someone point me in the right direction in terms of how to move forward to collect his data on tuya-local
