### DISCUSSION TITLE
Inkbird 4BW extension

### DISCUSSION THREAD

**Discussion by JustEndo** [make-all/tuya-local#1847] [Q&A]
Hello there!

I´m looking to extend the [Inkbird 4BW integration](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/inkbird_ibbq4bw_thermometer.yaml) to support some extra functionality and could use some pointers on how to best structure the data and how to work with constraints on bitfields.

Issue 1:

By default a unplugged probe reports a high value (~327660) on the temperature channel. I wanted to add a constraint to map the value to null when the probe is unplugged (The physical display switches to ---,- and I wanted to mimic that behaviour)
The value "plugged in" value is provided in the bitfield over on DP13 (labels below). But no matter what I do or check on the temperature value stays like it is. 

I might just be misreading the documentation, hopefully you can point me in the right direction

Example from probe 1:
```
primary_entity:
    entity: sensor
    name: Temperature probe 1
    class: temperature
    dps:
      - id: 13
        type: bitfield
        name: plugged_in
        mapping:
          - dps_val: 16
            value: false
          - value: true
      - id: 107
        type: integer
        name: sensor
        class: measurement
        mapping:
          - constraint: plugged_in
            conditions:
              - dps_val: 16
                value: null
            scale: 100
        unit: F

```

Issue 2:

What would be the best way to model the extra fields like 
DP 13: 
```
"label": [
              "P1_Target_Alert",
              "P2_Target_Alert",
              "P3_Target_Alert",
              "P4_Target_Alert",
              "P1_Remove",
              "P2_Remove",
              "P3_Remove",
              "P4_Remove",
              "P1_Below_Mini",
              "P2_Below_Mini",
              "P3_Below_Mini",
              "P4_Below_Mini",
              "P1_Above_Max",
              "P2_Above_Max",
              "P3_Above_Max",
              "P4_Above_Max",
              "Device_Temp_H",
              "Device_Temp_L",
              "Device_Charge",
              "Recording_Date",
              "WiFi_Turn_On",
              "WiFi_Smart_Con",
              "WiFi_AP",
              "WiFi_Not_Con",
              "WiFi_Con",
              "WiFi_Con_Cloud",
              "WiFi_Unknow",
              "BLE_Connected",
              "BLE_Disconnect",
              "BLE_Req_Pairing"
            ],
```
			
Should the flags be attached as attributes to the main sensors 1-4 (e.g. Temperature probe 1 above) or kept seperate? 

Issue 3:

The Below and Above flags are related to the currently unimplemented DPs 120-123, which seems to be the target thems that were mentioned in  [issue 874](https://github.com/make-all/tuya-local/issues/874)

According to the link provided there the structure of the DPs is as follows:

Datapoints 120-123 format: XX.YY.YY.ZZ.ZZ

XX: Temp Alarm Mode
  00 = Alarm Disabled
  10 = Max Temp Alarm
  11 = Temp Range Alarm
YY.YY: High/Max Temp (bytes flipped)
ZZ.ZZ: Low Temp (bytes flipped)		  

I´m assuming the best would be to model these as hex fields and mask the values appropriately?	

Thanks in advance!
