### DISCUSSION TITLE
Adding few more sensors for Fairland pool heat pump

### DISCUSSION THREAD

**Discussion by LukeStrc** [make-all/tuya-local#1897] [Ideas]
Hi.

Please could anybody create pull request / add following lines of code at the end of the `tuya-local/custom_components/tuya_local/devices/fairland_iphcr15_heatpump.yaml` file? It adds several new sensors. Maybe the Min and Max are not so important (added just because of "why not" :-) ), but current temperature and required temperature are very usefull in my perspective. I plan to write automation to turn on pool filtration when I'm returning power to grid & the required temperature differs more than 1 C from the current one (I know that when there is no water flow the current temperature is highly influenced by weather, but I plan to add some another thermometer which will be directly in the pool...).

BTW if somebody know how to improve it and take into account `temperature_unit`, it would be awesome!

Thank you!

The code:
```
  - entity: sensor
    category: diagnostic
    name: Water temperature
    icon: "mdi:thermometer"
    class: temperature
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: "°C"
        class: measurement
  - entity: sensor
    category: diagnostic
    name: Required temperature
    icon: "mdi:thermometer"
    class: temperature
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: "°C"
        class: measurement
  - entity: sensor
    category: diagnostic
    name: Minimum temperature
    icon: "mdi:thermometer"
    class: temperature
    dps:
      - id: 107
        type: integer
        name: sensor
        unit: "°C"
        class: measurement
  - entity: sensor
    category: diagnostic
    name: Maximum temperature
    icon: "mdi:thermometer"
    class: temperature
    dps:
      - id: 108
        type: integer
        name: sensor
        unit: "°C"
        class: measurement
```
