### DISCUSSION TITLE
Support for vacuum cleaners to clean a specified room

### DISCUSSION THREAD

**Discussion by almirus** [make-all/tuya-local#1924] [Ideas]
Good day! Is it possible for vacuum cleaners to designate cleaning of an individual room, or can this only be accomplished through the cloud?

**Comment by make-all** [comment]
This is probably a cloud feature, unless you can find the correct number of direction commands and delays to send it there.

**Comment by almirus** [comment]
In the log, I see the following messages, which means there is support (room cleaning). 😊
```
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] command values: ['Auto clean', 'Zone cleaning', 'pose', 'clean_spot', 'return_to_base', 'Select room cleaning']
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] fan_speed values: ['Off', 'Gentle', 'Normal', 'Strong', 'Max']
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 5 value from charge_done to charged
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 5 value from charge_done to charged
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] command values: ['Auto clean', 'Zone cleaning', 'pose', 'clean_spot', 'return_to_base', 'Select room cleaning']
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 9 value from normal to Normal
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 9 value from normal to Normal
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 4 value from chargego to return_to_base
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 4 value from chargego to return_to_base
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 5 value from charge_done to charged
2024-05-17 21:46:36.517 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] Robot vacuum: Mapped dps 5 value from charge_done to charged
2024-05-17 21:46:36.518 DEBUG (MainThread) [custom_components.tuya_local.helpers.device_config] command values: ['Auto clean', 'Zone cleaning', 'pose', 'clean_spot', 'return_to_base', 'Select room cleaning']
```

**Comment by almirus** [comment]
```
{
                    "abilityId": 4,
                    "accessMode": "rw",
                    "code": "mode",
                    "description": "smart - 自动清扫模式/全屋清扫模式 \\nchargego - 自动回充模式\\nzone - 划区清扫模式/矩形清扫模式\\npose - 指哪扫哪模式/定点清扫模式\\npart - 局部清扫模式\\nselectroom - 选区清扫",
                    "extensions": {
                        "attribute": "704"
                    },
                    "name": "工作模式",
                    "typeSpec": {
                        "type": "enum",
                        "range": [
                            "smart",
                            "chargego",
                            "zone",
                            "pose",
                            "part",
                            "selectroom"
                        ]
                    }
                },
```

```
{
                    "abilityId": 5,
                    "accessMode": "ro",
                    "code": "status",
                    "description": "默认值（不可修改删除，否则影响控制面板逻辑）：\\nstandby - 待机中\\nsmart - 自动清扫中 \\nzone_clean - 划区清扫中\\npart_clean - 局部清扫中\\ncleaning - 清扫中(备选) \\npaused - 已暂停\\ngoto_pos - 前往目标点中\\npos_arrived - 目标点已到达 \\npos_unarrive - 目标点不可达 \\ngoto_charge - 寻找充电座中 \\ncharging - 充电中\\ncharge_done - 充电完成 \\nsleep - 休眠\\nselect_room - 选区清扫\\nmop_clean - 湿拖模式\\nmanual_control - 手动控制中\\n\\n可在后面增加其他状态值，状态值尽量是状态的英文小写单词，如需要增加故障中状态，则为in_trouble",
                    "extensions": {
                        "attribute": "706"
                    },
                    "name": "当前状态",
                    "typeSpec": {
                        "type": "enum",
                        "range": [
                            "standby",
                            "smart",
                            "zone_clean",
                            "part_clean",
                            "cleaning",
                            "paused",
                            "goto_pos",
                            "pos_arrived",
                            "pos_unarrive",
                            "goto_charge",
                            "charging",
                            "charge_done",
                            "sleep",
                            "select_room",
                            "mop_clean",
                            "manual_control"
                        ]
                    }
                },
```

**Comment by make-all** [comment]
Sure, there is a command, but how do you use it to tell a "specified room" to go to?

**Reply by almirus** [reply]
```
"extensions": {
                        "attribute": "706"
                    },
```
?

**Reply by make-all** [reply]
This is the bit that is cloud-only, I think.  There is no "extensions" in the local protocol.

**Reply by pdurys** [reply]
I would like to refresh this question. (and another similar one https://github.com/make-all/tuya-local/discussions/2796)

This repo https://github.com/bennesp/robottino-rs claim that specific commands like cleaning particular room should also work locally. I have the same vacuum cleaner and it works as advertised.

Now I am trying to get this work in tuya-local in HA without success. 
In HA I can only see that robot is cleaning rooms as scheduled and when send to do something from the app, but so far was not able to send command to DP15 which would start the same as from this Repo above.

Any suggestions what to check or how to issues commands? I have tried various syntax but without any sign of life from robot.
As said I can control it locally from HA but just to do smart sweep not send it to particular room(s)
This repo describes how command should be constructed and encoded, but how to send it from tuya-local?

**Reply by make-all** [reply]
DP 15 is exposed as a text entity ("Command"), so you should be able to send the encoded command to it.

According to the repo linked, "Complex commands are sent as base64-encoded binary frames via DP 15, using a custom protocol: 0xAA + length (2 bytes BE) + command + data + checksum."

There is no clue as to what the commands are, what data needs to be sent, and how the checksum is calculated, but it is a start.
Probably that is specific to this particular model though, so it is not a general solution that can be used in this integration to make HA's new Room targeting usable.

**Reply by pdurys** [reply]
I have experimented with that and eventually I got working solution (at least for my Reventa / Tefal) 
Below is complete tutorial how I did that.
I hope if other users will test it and find it works for them too, you could implement this into integration.

I use native Tuya mobile app, but that solution should work locally.
For the moment this solution is enough for me and I am not planning to go further with other options, but I guess those could be implemented. Like go to clean spot. But that would require room map which at this moment I am struggling to pull from cloud with https://github.com/bennesp/robottino-rs

# Home Assistant: Multi-Room Selection Card for Tuya Vacuums

This guide explains how to build a custom dashboard card in Home Assistant to select multiple rooms and set the number of cleaning passes for a Tuya-based robot vacuum. 

It uses a pure-Python script to calculate and Base64-encode the Tuya DP 15 command (bypassing Home Assistant's `RestrictedPython` import limits) and a script that verifies the vacuum has started before resetting your dashboard toggles.

## Prerequisites
* A Home Assistant entity that accepts text payloads for your vacuum (e.g., `text.vacuum_command_entity` via Tuya Local integration.
* A vacuum entity to track state (e.g., `vacuum.my_robot_vacuum`).
* Tuya Local has to "see" and control vacuum cleaner

---

## Step 1: Enable Python Scripts

1. Open your Home Assistant `configuration.yaml` and add the following line if you haven't already:
   ```yaml
   python_script:
   ```
2. In the same directory as your `configuration.yaml`, create a new folder named `python_scripts`.
3. Restart Home Assistant to load the integration.

---

## Step 2: Create the Python Script

Inside the `python_scripts` folder, create a file named `generate_vacuum_rooms.py` and paste the following code. This script manually encodes the payload to Base64 without requiring the blocked `import base64` module.

```python
# python_scripts/generate_vacuum_rooms.py

def encode_b64(byte_list):
    """Pure Python Base64 encoder to bypass RestrictedPython import limits."""
    chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    out = []
    i = 0
    n = len(byte_list)
    while i < n:
        b1 = byte_list[i]
        b2 = byte_list[i + 1] if (i + 1) < n else 0
        b3 = byte_list[i + 2] if (i + 2) < n else 0

        val = (b1 << 16) | (b2 << 8) | b3

        c1 = (val >> 18) & 63
        c2 = (val >> 12) & 63
        c3 = (val >> 6) & 63
        c4 = val & 63

        out.append(chars[c1])
        out.append(chars[c2])

        if (i + 1) < n:
            out.append(chars[c3])
        else:
            out.append("=")

        if (i + 2) < n:
            out.append(chars[c4])
        else:
            out.append("=")

        i += 3
    return "".join(out)

# Fetch data passed from Home Assistant
room_ids = data.get("room_ids", [])
clean_times = int(data.get("clean_times", 1))
target_entity = data.get("entity_id", None)

if isinstance(room_ids, int):
    room_ids = [room_ids]

if room_ids:
    payload_length = 3 + len(room_ids)

    # Frame: [Header 0xAA, Length High, Length Low, Cmd 0x14, Clean Times, Room Count, Room IDs...]
    body_bytes = [0x14, clean_times, len(room_ids)] + room_ids
    raw_bytes = [0xAA, 0x00, payload_length] + body_bytes

    # Checksum: Sum of body bytes modulo 256
    checksum = sum(body_bytes) % 256
    raw_bytes.append(checksum)

    # Convert to Base64
    b64_payload = encode_b64(raw_bytes)

    logger.info("Vacuum Script -> Rooms: " + str(room_ids) + " | Payload: " + b64_payload)

    # Send command to Home Assistant entity
    if target_entity:
        domain = target_entity.split(".")[0]
        service_name = "set_dp" if domain == "localtuya" else "set_value"
        service_data = {"entity_id": target_entity, "value": b64_payload}
        if domain == "localtuya":
            service_data["dp"] = 15
            
        hass.services.call(domain, service_name, service_data, False)
```

---

## Step 3: Create Helpers (configuration.yaml)

Add the room toggles and the cleaning passes dropdown to your configuration. This example uses 4 rooms.

```yaml
input_boolean:
  vacuum_room_1:
    name: Living Room (ID 1)
    icon: mdi:sofa
  vacuum_room_2:
    name: Kitchen (ID 2)
    icon: mdi:stove
  vacuum_room_3:
    name: Bedroom (ID 3)
    icon: mdi:bed
  vacuum_room_4:
    name: Hallway (ID 4)
    icon: mdi:door-open

input_select:
  vacuum_clean_passes:
    name: Cleaning Passes
    icon: mdi:repeat
    options:
      - "1"
      - "2"
      - "3"
```
*(Reload your Input Booleans and Input Selects via Developer Tools -> YAML after adding these).*

---

## Step 4: Create the Automation Script (scripts.yaml)

This script collects the enabled rooms, triggers the python payload generation, and then waits for the vacuum to officially start cleaning before resetting the dashboard selectors.

```yaml
clean_selected_vacuum_rooms:
  alias: "Vacuum: Clean Selected Rooms"
  icon: mdi:robot-vacuum
  sequence:
    # 1. Send the command
    - action: python_script.generate_vacuum_rooms
      data:
        room_ids: >-
          {% set ns = namespace(rooms=[]) %}
          {% if is_state('input_boolean.vacuum_room_1', 'on') %}{% set ns.rooms = ns.rooms + [1] %}{% endif %}
          {% if is_state('input_boolean.vacuum_room_2', 'on') %}{% set ns.rooms = ns.rooms + [2] %}{% endif %}
          {% if is_state('input_boolean.vacuum_room_3', 'on') %}{% set ns.rooms = ns.rooms + [3] %}{% endif %}
          {% if is_state('input_boolean.vacuum_room_4', 'on') %}{% set ns.rooms = ns.rooms + [4] %}{% endif %}
          {{ ns.rooms }}
        clean_times: "{{ states('input_select.vacuum_clean_passes') | int(1) }}"
        entity_id: text.vacuum_command_entity

    # 2. Wait for the vacuum state to confirm it is actually cleaning
    - wait_for_trigger:
        - platform: state
          entity_id: vacuum.my_robot_vacuum
          to: "cleaning"
      timeout: "00:00:15"
      continue_on_timeout: false

    # 3. Reset room toggles (only runs if state changed to cleaning)
    - action: input_boolean.turn_off
      target:
        entity_id:
          - input_boolean.vacuum_room_1
          - input_boolean.vacuum_room_2
          - input_boolean.vacuum_room_3
          - input_boolean.vacuum_room_4

    # 4. Reset clean passes back to "1"
    - action: input_select.select_option
      target:
        entity_id: input_select.vacuum_clean_passes
      data:
        option: "1"
```
*(Reload your Scripts via Developer Tools -> YAML).*

---

## Step 5: Create the Dashboard Card

Add an **Entities Card** to your dashboard (Edit Dashboard → Add Card → Manual/YAML) to bring it all together:

```yaml
type: entities
title: Select Rooms to Clean
show_header_toggle: false
entities:
  - entity: input_boolean.vacuum_room_1
  - entity: input_boolean.vacuum_room_2
  - entity: input_boolean.vacuum_room_3
  - entity: input_boolean.vacuum_room_4
  - type: divider
  - entity: input_select.vacuum_clean_passes
  - type: button
    name: Start Cleaning
    icon: mdi:play-circle
    action_name: START
    tap_action:
      action: perform-action
      perform_action: script.clean_selected_vacuum_rooms
```
