### DISCUSSION TITLE
How to test new devices via yaml ?

### DISCUSSION THREAD

**Discussion by malosaa** [make-all/tuya-local#2003] [Q&A] [answered]
Hi all,

i would like to contribute new devices, as you already seen before.

There is an issue i really don't understand.
When i add a new device its asking me what type of device it is, well i can choose from 3 and all 3 do not match.
however i did create the accoring the documentation and put it in the directory with all the needed data, but it does not detect it.

For now i did do a work around, for example, i want to add my pet water fountain, it detects device type heater, so what i did was when selecting and before pressing submit, i went to that yaml of that specific heater device and past my code and save it, and then press submit, and it added my device normally and working, but i know this is not the way to test.

can someone say what i'm doing wrong ?
I have 4 more configs pending to be added, and even more devices.

regards

**Comment by make-all** [comment]
The local protocol data is normally not 100% according to the documentation.  That is why the first thing requested in the new device template is local logs, to see what the actual data received from the device is.  Frequently there will only be partial data returned on initial connection, and you will need to make all the other dps optional in order for your config to match.

**Reply by malosaa** [reply]
yes i did that, look here 



i did some research and here  i will post the issue again, my dps are correct 
when i use this config its not detected.

```
name: Hydrate Ultra
products:
  - id: cuw2k3ho3e25fade  

primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch

secondary_entities:
  - entity: light
    name: Led light
    icon: "mdi:brightness-6"
    category: config
    dps:
      - id: 102
        type: boolean
        name: switch
        icon: "mdi:brightness-6"
      - id: 103
        name: Led brightness
        type: integer
        range:
          min: 1
          max: 10
  - entity: button
    name: Filter replaced
    icon: "mdi:air-filter"
    category: config
    dps:
      - id: 104
        type: boolean
        name: button
  - entity: sensor
    name: Filter life
    icon: "mdi:air-filter"
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        precision: 0
        range:
          min: 0
          max: 43200
        mapping:
          - scale: 1440  # minutes => days
            invert: true
        unit: d
  - entity: button
    name: Pump cleaned
    icon: "mdi:pump"
    category: config
    dps:
      - id: 105
        type: boolean
        name: button
  - entity: sensor
    name: Pump maintenance
    icon: "mdi:pump"
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        precision: 0
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 1440
            invert: true
        unit: d
  - entity: sensor
    name: Water quality
    icon: "mdi:water"
    category: diagnostic
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: TDS
  - entity: switch
    name: UV sterilization
    icon: "mdi:flash"
    category: config
    dps:
      - id: 107
        type: boolean
        name: switch
  - entity: sensor
    name: Water level
    icon: "mdi:water"
    category: diagnostic
    dps:
      - id: 108
        type: integer
        name: sensor
        mapping:
          - dps_val: "1"
            value: 1
          - dps_val: "2"
            value: 2
          - dps_val: "3"
            value: 3
          - dps_val: "4"
            value: 4
  - entity: sensor
    name: UV runtime
    icon: "mdi:timer-outline"
    category: diagnostic
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: s
``` 

![image](https://github.com/make-all/tuya-local/assets/13116501/6a1a8f78-d81b-4ee7-b366-5cf316169eed)


the one it almost matches is the sprinkler, when exmam the code its almost identical with the dps so it should match. but it doesnt.

```
name: QOTO 03 sprinkler controller
primary_entity:
  entity: valve
  class: water
  dps:
    - id: 102
      type: integer
      name: valve
      mapping:
        - step: 5
secondary_entities:
  - entity: number
    icon: "mdi:pipe-valve"
    category: config
    deprecated: valve
    dps:
      - id: 102
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
        mapping:
          - step: 5
  - entity: sensor
    category: diagnostic
    icon: "mdi:valve"
    name: Open
    dps:
      - id: 103
        name: sensor
        type: integer
        unit: "%"
  - entity: sensor
    category: diagnostic
    translation_key: time_remaining
    class: duration
    dps:
      - id: 104
        name: sensor
        type: integer
        unit: s
  - entity: number
    category: config
    translation_key: timer
    dps:
      - id: 105
        type: integer
        name: value
        unit: s
        range:
          min: 0
          max: 86399
  - entity: binary_sensor
    category: diagnostic
    class: problem
    dps:
      - id: 108
        name: sensor
        type: integer
        mapping:
          - dps_val: 0
            value: false
          - value: true
```

My dps



```
{
  "result": {
    "properties": [
      {
        "code": "power",
        "custom_name": "",
        "dp_id": 101,
        "time": 1718172165137,
        "value": true
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 102,
        "time": 1718172158974,
        "value": 1
      },
      {
        "code": "water_alarm",
        "custom_name": "",
        "dp_id": 103,
        "time": 1718176476518,
        "value": 71
      },
      {
        "code": "filter_alarm",
        "custom_name": "",
        "dp_id": 104,
        "time": 1718176482526,
        "value": 2595
      },
      {
        "code": "pump_alarm",
        "custom_name": "",
        "dp_id": 105,
        "time": 1718176422661,
        "value": 2594
      },
      {
        "code": "tds",
        "custom_name": "",
        "dp_id": 106,
        "time": 1718176464555,
        "value": 137
      },
      {
        "code": "uv",
        "custom_name": "",
        "dp_id": 107,
        "time": 1718175055572,
        "value": true
      },
      {
        "code": "water_level",
        "custom_name": "",
        "dp_id": 108,
        "time": 1718172158974,
        "value": 4
      },
      {
        "code": "uvruntime",
        "custom_name": "",
        "dp_id": 109,
        "time": 1718175237297,
        "value": 0
      },
      {
        "code": "uvsection",
        "custom_name": "",
        "dp_id": 110,
        "time": 1680879964898,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1718176488525,
  "tid": "74115154288b11ef9e3b1acebe103cd3"
}
```


log:
```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:483
integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 2:02:05 AM (1 occurrences)
Last logged: 2:02:05 AM

Device matches qoto_03_sprinkler with quality of 56%. DPS: {"updated_at": 1718182896.2750244, "101": true, "102": 1, "103": 176, "104": 2700, "105": 2700, "106": 137, "107": true, "108": 4, "109": 0}
```

besides the loop warning in the log

**Comment by malosaa** [comment]
i did some more debugging and this one is weird:

so when adding this it detects during adding:

```
name: Hydrate Ultra
products:
  - id: cuw2k3ho3e25fade  

primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch
```

when adding this it does not detect...

```
name: Hydrate Ultra
products:
  - id: cuw2k3ho3e25fade  

primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch
secondary_entities:
  - entity: light
    name: Led light
    icon: "mdi:brightness-6"
    category: config
    dps:
      - id: 102
        type: boolean
        name: switch
        icon: "mdi:brightness-6"
      - id: 103
        name: Led brightness
        type: integer
        range:
          min: 1
          max: 10
```

when changing that secondary_entities: to the one from the sprinkler it get detected:

```
name: Hydrate Ultra
products:
  - id: cuw2k3ho3e25fade  

primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch
secondary_entities:
  - entity: number
    icon: "mdi:pipe-valve"
    category: config
    deprecated: valve
    dps:
      - id: 102
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
        mapping:
          - step: 5
```

whats going on here ? i'm confused...
