### DISCUSSION TITLE
Any Possibility to Support Modena water Heater ES-15-SKY

### DISCUSSION THREAD

**Discussion by tazkirap** [make-all/tuya-local#2007] [Q&A]
Hello guys, I'm really sorry if it isn't a suit place to request.
I'm really noob in github, so I Decide to write in Discussion topic

I've water heater from Modena ES 15 SKY with tuya based platform.
This is the query of data things mode

```
{
  "result": {
    "model": "{\"modelId\":\"000002fmb9\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"add_electricity\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"trigger\":\"direct\"},\"name\":\"耗电量\",\"typeSpec\":{\"type\":\"value\",\"max\":10000,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"度\"}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"FUNCTION_MODE\",\"description\":\"\",\"name\":\"模式\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"SetTemp3kw\",\"description\":\"\",\"name\":\"3KW设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"SetTemp2kw\",\"description\":\"\",\"name\":\"2KW模式设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"SetTemp1kw\",\"description\":\"\",\"name\":\"1KW模式设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"unit\":\"C\"}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"SetTempOrderI\",\"description\":\"\",\"name\":\"预约I设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"SetTempOrderII\",\"description\":\"\",\"name\":\"预约II设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":75,\"min\":30,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"default\",\"description\":\"1:E1 2:E3  3:FR \",\"name\":\"故障\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"CuntTemp\",\"description\":\"当前NTC温度\",\"name\":\"当前设备NTC实时水温度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"Cubage\",\"description\":\"1：15L  2;25L\",\"name\":\"容量设置\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"TimerMinOrderI\",\"description\":\"预约I分钟设置\",\"name\":\"预约I分钟设置\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"TimerHourOrderI\",\"description\":\"预约I小时设置\",\"name\":\"预约I小时设置\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"TimerHourOrderII\",\"description\":\"预约ii小时设置\",\"name\":\"预约II小时设置\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":113,\"accessMode\":\"rw\",\"code\":\"TimerMinOrderII\",\"description\":\"预约II小时设置\",\"name\":\"预约II分钟设置\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":114,\"accessMode\":\"ro\",\"code\":\"HeatFlag\",\"description\":\"加热标志  0;不加热  1：加热\",\"name\":\"加热标志\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":115,\"accessMode\":\"rw\",\"code\":\"reserve1\",\"description\":\"\",\"name\":\"预留字节1\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"reserve2\",\"description\":\"\",\"name\":\"预留字节2\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":117,\"accessMode\":\"rw\",\"code\":\"reserve3\",\"description\":\"\",\"name\":\"预留字节3\",\"typeSpec\":{\"type\":\"value\",\"max\":255,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},{\"abilityId\":118,\"accessMode\":\"rw\",\"code\":\"morning\",\"description\":\"\",\"name\":\"晨约\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":119,\"accessMode\":\"rw\",\"code\":\"afternoon\",\"description\":\"\",\"name\":\"午后\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1718201641907,
  "tid": "049bac0628c611efb9130e1a774ae1f3"
}
```

Is it possible to get support in tuya local?
Once again, I'm really sorry if it isn't suit to post in this topic. Thank you

**Comment by malosaa** [comment]
Try this one, not sue if it works as i don't have the device.
but it should point you in the right direction


```
name: New Device
products:
  - id: 000002fmb9  
    name: New Smart Device

primary_entity:
  entity: switch
  dps:
    - id: 1
      type: boolean
      name: switch

secondary_entities:
  - entity: sensor
    name: Electricity Consumption
    icon: "mdi:flash"
    category: diagnostic
    dps:
      - id: 10
        type: integer
        name: add_electricity
        range:
          min: 0
          max: 10000
        unit: "kWh"

  - entity: select
    name: Mode
    icon: "mdi:settings"
    category: config
    dps:
      - id: 101
        type: integer
        name: mode
        range:
          min: 0
          max: 10

  - entity: number
    name: 3KW Temperature Setting
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 102
        type: integer
        name: set_temp_3kw
        range:
          min: 30
          max: 75
        unit: "°C"

  - entity: number
    name: 2KW Temperature Setting
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 103
        type: integer
        name: set_temp_2kw
        range:
          min: 30
          max: 75
        unit: "°C"

  - entity: number
    name: 1KW Temperature Setting
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 104
        type: integer
        name: set_temp_1kw
        range:
          min: 30
          max: 75
        unit: "°C"

  - entity: number
    name: Order I Temperature Setting
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 105
        type: integer
        name: set_temp_order_i
        range:
          min: 30
          max: 75

  - entity: number
    name: Order II Temperature Setting
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 106
        type: integer
        name: set_temp_order_ii
        range:
          min: 30
          max: 75

  - entity: sensor
    name: Fault
    icon: "mdi:alert-circle"
    category: diagnostic
    dps:
      - id: 107
        type: integer
        name: fault
        range:
          min: 0
          max: 10

  - entity: sensor
    name: Current NTC Temperature
    icon: "mdi:thermometer"
    category: diagnostic
    dps:
      - id: 108
        type: integer
        name: current_ntc_temp
        range:
          min: 0
          max: 100
        unit: "°C"

  - entity: select
    name: Capacity Setting
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 109
        type: integer
        name: capacity
        range:
          min: 0
          max: 10

  - entity: number
    name: Order I Minute Setting
    icon: "mdi:timer"
    category: config
    dps:
      - id: 110
        type: integer
        name: order_i_min
        range:
          min: 0
          max: 255

  - entity: number
    name: Order I Hour Setting
    icon: "mdi:timer"
    category: config
    dps:
      - id: 111
        type: integer
        name: order_i_hour
        range:
          min: 0
          max: 255

  - entity: number
    name: Order II Hour Setting
    icon: "mdi:timer"
    category: config
    dps:
      - id: 112
        type: integer
        name: order_ii_hour
        range:
          min: 0
          max: 255

  - entity: number
    name: Order II Minute Setting
    icon: "mdi:timer"
    category: config
    dps:
      - id: 113
        type: integer
        name: order_ii_min
        range:
          min: 0
          max: 255

  - entity: sensor
    name: Heating Flag
    icon: "mdi:flash"
    category: diagnostic
    dps:
      - id: 114
        type: boolean
        name: heating_flag

  - entity: number
    name: Reserve Byte 1
    icon: "mdi:memory"
    category: config
    dps:
      - id: 115
        type: integer
        name: reserve1
        range:
          min: 0
          max: 255

  - entity: number
    name: Reserve Byte 2
    icon: "mdi:memory"
    category: config
    dps:
      - id: 116
        type: integer
        name: reserve2
        range:
          min: 0
          max: 255

  - entity: number
    name: Reserve Byte 3
    icon: "mdi:memory"
    category: config
    dps:
      - id: 117
        type: integer
        name: reserve3
        range:
          min: 0
          max: 255

  - entity: switch
    name: Morning Setting
    icon: "mdi:weather-sunset"
    category: config
    dps:
      - id: 118
        type: boolean
        name: morning

  - entity: switch
    name: Afternoon Setting
    icon: "mdi:weather-sunset"
    category: config
    dps:
      - id: 119
        type: boolean
        name: afternoon
```
