### DISCUSSION TITLE
Cannot make "select" entity work as expected

### DISCUSSION THREAD

**Discussion by jmcollin78** [make-all/tuya-local#2103] [Q&A] [answered]
Hello, I'm building a device file for AFYEEV 32A EV charger.
My device have one of this ability:

{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"trigger\":\"direct\"},\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"charge_now\",\"charge_pct\",\"charge_energy\",\"charge_schedule\",\"charge_delay\"]}},

I try to exploit it as a select entity to be able to change the work_mode.

```
...
secondary_entities:
  - entity: select
    name: Working mode
    category: config
    icon: "mdi:list-box-outline"
    dps:
      - id: 14
        type: string
        name: option
        mapping:
          - dps_val: charge_now
            value: Charge now
          - dps_val: charge_pct
            value: Charge PCT
          - dps_val: charge_energy
            value: Charge energy
          - dps_val: charge_schedule
            value: Charge schedule
          - dps_val: charge_delay
            value: Charge delay
...
```
But the entity is not created.

In the log I see some errors:
```
2024-07-11 21:14:05.318 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Chargeur garage for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 103, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_setup_entry
    raise ValueError(
ValueError: Config entry Chargeur garage (01J2EV17RM16H0MR45DZK4AV8K) for tuya_local.select has already been setup!
2024-07-11 21:14:05.324 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Chargeur garage for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 128, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 184, in async_setup_entry
    raise ValueError(
ValueError: Config entry Chargeur garage (01J2EV17RM16H0MR45DZK4AV8K) for tuya_local.number has already been setup!
```

Note: with sensor instead of select, I see the value but I cannot change it.

The complete device file is:
```
name: EV charger
products:
  - id: aaaealnecwgwerjl
    name: AFYEEV 32A EV charger
primary_entity:
  entity: sensor
  class: enum
  name: Status
  icon: "mdi:ev-station"
  dps:
    - id: 3
      type: string
      name: sensor
      mapping:
        - dps_val: charger_free
          value: Disconnected
        - dps_val: charger_insert
          value: Connected
        - dps_val: charger_free_fault
          value: Fault (disconnected)
        - dps_val: charger_charging
          value: Charging
        - dps_val: charger_wait
          value: Waiting
        - dps_val: charger_end
          value: Charged
        - dps_val: charger_fault
          value: Fault
        - dps_val: charger_pause
          value: Pause

secondary_entities:
  - entity: number
    name: Set current
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 4
        type: integer
        name: value
        unit: A
        range:
          min: 6
          max: 16
  - entity: sensor
    icon: "mdi:flash"
    name: Single phase power
    class: power
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: W
        class: measurement
        precision: 1
        mapping:
          - scale: 3
  - entity: sensor
    icon: "mdi:flash"
    name: Total power
    class: power
    dps:
      - id: 9
        type: integer
        name: sensor
        unit: W
        class: measurement
        precision: 1
        mapping:
          - scale: 1
  - entity: sensor
    name: Fault reason
    icon: 'mdi:alert-outline'
    class: enum
    dps:
      - id: 10
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: "Ready"
          - dps_val: 1
            value: "Ov2 Cr Fault"
          - dps_val: 2
            value: "OV Vol"
          - dps_val: 4
            value: "Undervoltage alarm"
          - dps_val: 8
            value: "Contactor adhesion"
          - dps_val: 16
            value: "Contactor fault"
          - dps_val: 32
            value: "Earth fault"
          - dps_val: 64
            value: "Meter Hardware alarm"
          - dps_val: 128
            value: "Scram fault"
          - dps_val: 256
            value: "CP fault"
          - dps_val: 512
            value: "Meter Commu fault"
          - dps_val: 1024
            value: "Card reader fault"
          - dps_val: 2048
            value: "Cir short fault"
          - dps_val: 4096
            value: "Adhesion fault"
          - dps_val: 8192
            value: "Self test alarm"
          - dps_val: 16384
            value: "Leakage current fault"
  - entity: select
    # class: enum
    name: Working mode
    category: config
    icon: "mdi:list-box-outline"
    dps:
      - id: 14
        type: string
        name: option
        mapping:
          - dps_val: charge_now
            value: Charge now
          - dps_val: charge_pct
            value: Charge PCT
          - dps_val: charge_energy
            value: Charge energy
          - dps_val: charge_schedule
            value: Charge schedule
          - dps_val: charge_delay
            value: Charge delay
  - entity: switch
    name: Power switch
    icon: "mdi:power"
    dps:
      - id: 18
        type: boolean
        optional: true
        force: true
        name: switch
  - entity: sensor
    class: temperature
    name: Temperature
    # category: diagnostic
    dps:
      - id: 24
        type: integer
        name: sensor
        unit: °C
        class: measurement
        mapping:
          - scale: 1
  - entity: sensor
    name: Charge energy once
    class: energy
    dps:
      - id: 25
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        optional: true
        mapping:
          - scale: 2
  - entity: sensor
    class: enum
    name: Online state
    icon: "mdi:wifi"
    dps:
      - id: 27
        type: string
        name: string
        mapping:
          - dps_val: offline
            value: Offline
          - dps_val: online
            value: Online
  - entity: number
    name: Timer
    # category: config
    icon: "mdi:car-clock"
    dps:
      - id: 28
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 15

```
