### DISCUSSION TITLE
Neo Coolcam siren

### DISCUSSION THREAD

**Discussion by Trzinka** [make-all/tuya-local#2316] [Q&A]
Hi.

`I don't have any programming experience, or it's the first time I've encountered such a yaml file, so I'd like to ask for help if possible.`

I have: **NEO Coolcam Smart Tuya Wifi Siren Alarm With Temperature Humidity Sensor**

**What I know or was able to find:**
```
Product Name  : Siren Sensor BK N 02
Device ID          : bf936cdd3891c0c4969lkq
```
and
```yaml
battery level			  = code: 101
Alarm Sound Type		  = code: 102
Alarm Period			  = code: 103
Alarm Switch			  = code: 104
Temperature			  = code: 105
Humidity			          = code: 106
Min Tem				  = code: 107
Max Tem				  = code: 108
Min Humidity			  = code: 109
Max Humidity			  = code: 110
Temp Scale			  = code: 112
Temperature alarm switch = code: 113
Humidity alarm switch	  = code: 114
Alarm type			  = code: 115
Alarm dB			          = code: 116
```

_I currently have this condition:_
![Tuya-Neo Coolcam siren](https://github.com/user-attachments/assets/60836cee-57dd-43dc-bb32-6b47829c1c02)

Examining custom_components/tuya_local/devices/neo_coolcam_siren.yaml I noticed the entry:
```yaml
    - id: 102
      type: string
      name: tone
      mapping:
        - dps_val: "1"
          value: Doorbell
        - dps_val: "2"
          value: Für Elise
        - dps_val: "3"
          value: Big Ben
        - dps_val: "4"
          value: Ring ring
        - dps_val: "5"
          value: Lone Ranger
        - dps_val: "6"
          value: Turkish march
        - dps_val: "7"
          value: High pitched
        - dps_val: "8"
          value: Red alert
        - dps_val: "9"
          value: Crickets
        - dps_val: "10"
          value: Beep
        - dps_val: "11"
          value: Dog bark
        - dps_val: "12"
          value: Police siren
        - dps_val: "13"
          value: Grandfather clock
        - dps_val: "14"
          value: Phone ring
        - dps_val: "15"
          value: Fire truck
        - dps_val: "16"
          value: Clock chime
        - dps_val: "17"
          value: Alarm clock
        - dps_val: "18"
          value: School bell
```
which cannot be found in the settings (picture above)!?

### Is there a way to add this as well?

Thanks for your help

**Comment by Trzinka** [comment]
Later, I noticed these two items, which I would like to ask if they can be added.

```yaml
    - id: 103
      type: integer
      name: duration
      unit: s
      range:
        min: 0
        max: 1800

    - id: 116
      type: string
      name: volume_level
      mapping:
        - dps_val: "0"
          value: 1.0
        - dps_val: "1"
          value: 0.7
        - dps_val: "2"
          value: 0.3
```
