### DISCUSSION TITLE
Is it possible to configure via config file instead of via the GUI?

### DISCUSSION THREAD

**Discussion by erwin** [make-all/tuya-local#2325] [General]
There are a few discussions about https://github.com/make-all/tuya-local/discussions/2024 "File configuration" however project developer Jason replied:

> The configuration file is not intended to be edited by hand, any parameters that are safe to edit are available for editing in the device Options

I have a `25` Tuya devices, many of those 25 devices are 2 and 3 way switches, so it's actually around 100 entities to setup... I've manually re-added them via various GUIs so many times, it's just a nightmare to think about doing again and again. Of course my Tuya config has crapped out again...

Back when I started with HA, I used a `localtuya.yaml` config file to set everything up. That was so awesome -- one place that I COULD SAVE, backup, and easily use to re-add all my devices. Unfortunately, local-tuya went with it's API/cloud based GUI...

I was hoping `tuya-local` might have a way to load all my devices directly via a YAML file (even if I had to edit it and do some conversions...)

The good old `localtuya.yaml` had a format like:

```
  - host: $MY_IP
    device_id: '$MY_ID'
    local_key: '$MY_KEY'
    friendly_name: Living Room TV
    protocol_version: "3.3"
    scan_interval: 30
    entities:
      - platform: binary_sensor
        friendly_name: TV Plug
        id: 1
        device_class: power
        state_on: "true"
        state_off: "false"
      - platform: switch
        friendly_name: TV Switch
        id: 1
      - platform: sensor
        friendly_name: TV Current
        unit_of_measurement: "mA"
        id: 18
      - platform: sensor
        friendly_name: TV Power
        unit_of_measurement: "W"
        scaling: 0.1
        id: 19
      - platform: sensor
        friendly_name: TV Voltage
        unit_of_measurement: "V"
        scaling: 0.1
        id: 20
      - platform: sensor
        friendly_name: TV Total
        unit_of_measurement: "kWh"
        scaling: 0.001

        id: 21
```

Is there any possibility of building an "importer" for a YAML based config that we can maintain ourselves, rather than being dependent on the GUI each time for [re]configuration?

Any guidance on where to start to implement that?
