### DISCUSSION TITLE
Device attributes control not working through Tuya-Local

### DISCUSSION THREAD

**Discussion by JackJackattack4** [make-all/tuya-local#2338] [Q&A]
Deakon heatpump device was created and integrated in Tuya-Local (deakon_evi_waterheatpump.yaml). Actual live code for that device is pasted at the end of the post.

When connecting that device to Home Assistant, changing the value of the attributes "inquire_id" in HA (via developper tools set states for example), the value of the attribute is changed in HA for a couple a seconds but the actual "inquire_id" in the actual tuya device is not changed. It seems that the device rejects the change. I observe the same behavior for the attribute "set_id".

Previously, I was able to change the value in the actual tuya device using HA when using this yaml code for the device in tuya local. But, when I use this legacy yaml code for deakon heatpump, the attributes "inquire_id" and "set_id" do not appear in HA, but they did in the past.

I am wondering what would be the best approach to allow HA to "pass" both "inquire_id" and "set_id" attributes values to the actual tuya device in order to control these parameters via HA, as I used to be able to do in the past.

Live deakon heatpump device code :
```
name: Radiator heatpump
products:
  - id: 02ek8thasvo40fmd
    name: Deakon EVI A2pro
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
          hidden: true
        - dps_val: true
          constraint: mode
          conditions:
            - dps_val: hot
              value: heat
              hidden: true
            - dps_val: cold
              value: cool
              hidden: true
            - dps_val: hotwater
              value: "off"
            - dps_val: hot_hotwater
              value: heat
            - dps_val: cold_hotwater
              value: cool
    - id: 2
      type: integer
      name: temperature
      unit: C
      range:
        min: 5
        max: 60
    - id: 3
      type: integer
      name: current_temperature
    - id: 4
      type: string
      name: mode
      hidden: true
    - id: 103
      type: string
      name: hvac_action
      mapping:
        - dps_val: "off"
          value: idle
        - dps_val: "on"
          value: heating
          constraint: mode
          conditions:
            - dps_val: cold
              value: cooling
        - dps_val: defrost
          value: heating
        - dps_val: antifrozen
          value: heating
    - id: 104
      type: string
      name: inquire_id
    - id: 105
      type: integer
      name: inquire_value
    - id: 106
      type: string
      name: set_id
    - id: 107
      type: integer
      name: set_value
      range:
        min: -100
        max: 999
    - id: 109
      type: string
      name: error_code_table
    - id: 110
      type: string
      name: error_code_table2
    - id: 111
      type: string
      name: driver_error_code1
    - id: 112
      type: string
      name: driver_error_code2
    - id: 113
      type: string
      name: sen_sys_error_code1
    - id: 114
      type: string
      name: sen_sys_error_code2
secondary_entities:
  - entity: select
    name: Combined mode
    icon: "mdi:heat-pump"
    category: config
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: hot
            value: Heating only
          - dps_val: cold
            value: Cooling only
          - dps_val: hotwater
            value: Hot water only
          - dps_val: hot_hotwater
            value: Hot water + heating
          - dps_val: cold_hotwater
            value: Hot water + cooling
  - entity: select
    name: Temperature target
    category: config
    dps:
      - id: 5
        type: string
        name: option
        mapping:
          - dps_val: HotWater
            value: Hot water
            icon: "mdi:water-thermometer"
          - dps_val: Hot
            value: Heating
            icon: "mdi:home-thermometer"
          - dps_val: Cooling
            icon: "mdi:snowflake-thermometer"
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 13
        type: bitfield
        name: fault_code
  - entity: binary_sensor
    translation_key: defrost
    category: diagnostic
    dps:
      - id: 103
        type: string
        name: sensor
        mapping:
          - dps_val: defrost
            value: true
          - value: false
  - entity: binary_sensor
    name: Anti-freeze
    class: cold
    category: diagnostic
    dps:
      - id: 103
        type: string
        name: sensor
        mapping:
          - dps_val: antifrozen
            value: true
          - value: false
```

Legacy code that I used in the past:
```
name: Radiator heatpump
products:
  - id: 02ek8thasvo40fmd
    name: Deakon EVI A2pro
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: ON-OFF
      type: boolean
      mapping:
        - dps_val: false
          value: "Off"
        - dps_val: true
          value: "On"
    - id: 2
      name: temperature
      type: integer
      range:
        min: 7
        max: 60
    - id: 3
      name: current_temperature
      type: integer
    - id: 4
      name: Working Mode
      type: string
      mapping:
        - dps_val: hot
          value: Heating
          icon: "mdi:fire"
        - dps_val: cold
          value: Cooling
          icon: "mdi:snowflake"
        - dps_val: hotwater
          value: Hot Water
        - dps_val: hot_hotwater
          value: Heating + Hot Water
        - dps_val: cold_hotwater
          value: Cooling + Hot Water
    - id: 5
      name: Setting Temp. Type
      type: string
      mapping:
        - dps_val: HotWater
          value: Hot Water
        - dps_val: Hot
          value: Heating
        - dps_val: Cold
          value: Cooling
    - id: 103
      name: Working Status
      type: string
      mapping:
        - dps_val: on
          value: On
        - dps_val: off
          value: Off
          icon: "mdi:hvac-off"
          icon_priority: 1
        - dps_val: defrost
          value: Defrost
          icon: "mdi:snowflake-melt"
          icon_priority: 3
        - dps_val: antifrozen
          value: Antifrozen
    - id: 105
      # DPID 104 (para. Inquiry) specifies which parameter is inquired and the value is returned using DPID 105 (Inquiry Value).
      name: Inquire_Value
      type: integer
    - id: 107
      # DPID 106 (Para. Setting) specifies which parameter is set using the value in DPID 107 (Set Value).
      #real parameter name should be "set_value" but climate entity standard parameter available is humidity. Other attribute cannot be used to feed a value in the set value parameter on the heat pump
      name: humidity
      type: integer

secondary_entities:
  - entity: select
    name: Inquire_ID
    category: config
    dps:
      - id: 104
        # mappings based on dev portal info, observed values and manufacturer's manual. DPID 104 (para. Inquiry) specifies which parameter is inquired and the value is returned using DPID 105 (Inquiry Value).
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: version no.
          - dps_val: "2"
            value: ambient temp.
          - dps_val: "3"
            value: water tank temp.
          - dps_val: "4"
            value: outlet water temp.
          - dps_val: "5"
            value: inlet water temp.
          - dps_val: "6"
            value: evaporator coil temp.
          - dps_val: "7"
            value: exhaust gas temp.
          - dps_val: "8"
            value: condenser coil temp. (after throttling)
          - dps_val: "9"
            value: suction temp.
          - dps_val: "10"
            value: module temp.
          - dps_val: "11"
            value: main valve opening degrees
          - dps_val: "12"
            value: auxiliary valve opening degrees
          - dps_val: "13"
            value: exhaust gas valve opening degrees
          - dps_val: "14"
            value: Fan speed
          - dps_val: "15"
            value: running frequency
          - dps_val: "16"
            value: AC voltage
          - dps_val: "17"
            value: DC voltage
          - dps_val: "18"
            value: current of whole unit
          - dps_val: "19"
            value: compressor current
          - dps_val: "20"
            value: output power
          - dps_val: "21"
            value: EVI plate heat exchanger inlet sensor
          - dps_val: "22"
            value: EVI plate heat exchanger outlet sensor
          - dps_val: "23"
            value: low pressure
          - dps_val: "24"
            value: high pressure
          - dps_val: "25"
            value: error code
          - dps_val: "26"
            value: limited frequency code
          - dps_val: "27"
            value: LCD Controller version
          - dps_val: "28"
            value: MCU1 version
          - dps_val: "29"
            value: MCU2 version
          - dps_val: "30"
            value: MCU3 version
          - dps_val: "31"
            value: Error History
  - entity: select
    name: Set_ID
    category: config
    dps:
      - id: 106
        # mappings based on dev portal info, observed values and manufacturer's manual. DPID 106 (Para. Setting) specifies which parameter is set using the value in DPID 107 (Set Value).
        type: string
        name: option
        mapping:
          - dps_val: "d01"
            value: Heating Temp Setting
          - dps_val: "d02"
            value: Heating Water Tank Temp Setting
          - dps_val: "d03"
            value: Cooling Temp Setting
          - dps_val: "d04"
            value: Restart Temp Difference 
          - dps_val: "d05"
            value: Selection on Control basis
          - dps_val: "d06"
            value: Setting Temp Of Electric Heater
          - dps_val: "d07"
            value: Deviation Time of Electric Heater Start
          - dps_val: "d08"
            value: Evaporator coil Temp to enter into defrosting
          - dps_val: "d09"
            value: Evaporator coil Temp to exit defrosting 
          - dps_val: "d10"
            value: Defrosting Cycle Period
          - dps_val: "d11"
            value: Defrosting Time
          - dps_val: "d12"
            value: Selection on Control after temp is reached
          - dps_val: "d13"
            value: Ambient temp for Stopping and Starting machine
          - dps_val: "d14"
            value: Temp Difference of Inlet and Outlet water for heat pump's
          - dps_val: "d15"
            value: Working Way of Water Pump
```

**Comment by make-all** [comment]
The Developer Tools is only changing HA internal state, and it is only passed on to entities if that attribute is a part of the entity API that is writable. It does not work for extra attributes, as there is no API that allows changing them.

**Reply by JackJackattack4** [reply]
Thanks for the reply, highly appreciated.

I was able for 8 months to use HA to automatically change the values of the 2 secondary attributes "inquire_id" and "set_id" which then via Tuya-Local was changing the parameters value on the actual device itself.

To continue to operate like this, I would just need to have both secondary attributes to continue to show up in HA. Somehow, my code does not work to have these two secondary attributes in the HA entity once loaded using Tuya-Local anymore. With the code below, I was able to see and write the two secondary attributes in HA. What could explain that the  secondary attribute does not load and appear in HA?

Extract of the relevant code to bring the secondary attribute in HA:
```
secondary_entities:
  - entity: select
    name: Inquire_ID
    category: config
    dps:
      - id: 104
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: version no.
          - dps_val: "2"
            value: ambient temp.
....
```

**Reply by make-all** [reply]
Select entities should work if the dp is rw on the device side, and with limited set of possible values. The above looks correct.

**Reply by JackJackattack4** [reply]
Select entities for both secondary entities listed before in this conversation were indicated "unavailable", probably because they were not successfully mapped and they were before.

I went back to a previous backup I had in which both secondary entities were available and working (and actually passing parameters from HA to the device itself without problems). I noticed that the select entities were available up to HA core version 2024.4.4 but then started to show "unavailable" from HA core version 2024.5.0 on.

My question then becomes: what happened on the HA core version 2024.5.0 that made some of my Tuya-local created secondary entities to become "unavailable"?

**Reply by make-all** [reply]
What does your log say? I can't imagine HA would disable those without logging the reason.

**Reply by JackJackattack4** [reply]
I have a log of the start-up with both HA core version. I was unable to find any difference pointing at the issue.

The log named 2024.4.4 has both secondary entities up and running and the log 2024.5.0 has the same setup but with a different HA core version only, both secondary entities are unavailable.

[home-assistant_2024.5.0.log](https://github.com/user-attachments/files/17237343/home-assistant_2024.5.0.log)
[home-assistant_2024.4.4.log](https://github.com/user-attachments/files/17237344/home-assistant_2024.4.4.log)

**Reply by make-all** [reply]
The issue appears to be that you are using an old tuya-local version which newer versions of HA fail to setup due to some "issues with sleep" during startup, which at first were warnings, but earlier this year became fatal errors. Tuya-local only explicitly sleeps if the IP address is set to Auto, but around HA 2024.7 they also started doing the same for I/O operations.

**Reply by JackJackattack4** [reply]
I just updated to latest HA core (2024.10.0) and updated to latest tuya-local and both entities are still unavailable, see log attached.

[home-assistant_2024.10.0.log](https://github.com/user-attachments/files/17237825/home-assistant_2024.10.0.log)

Should I change some settings in Tuya-local and just stick to the HA version 2024.4.4?

**Reply by JackJackattack4** [reply]
I realized that HACS was not also updated to the latest version, so I did update it. Some result but a different log. I also reload the devices in Tuya-Local with the change to the configuration to have the IP address set to "auto". Same result, both entities are still unavailable.

In the log, nothing seems to go to sleep anymore.

See latest log below:

[home-assistant_2024.10.0_with_latest Tuya-Local_update.log](https://github.com/user-attachments/files/17244940/home-assistant_2024.10.0_with_latest.Tuya-Local_update.log)

**Reply by JackJackattack4** [reply]
After updating to latest HA core, latest Tuya-local version and latest HACS version, I decided to delete and recreate the device in Tuya-local, and it worked!

Now, the only trouble I have is that I have to remember to override the code in the Tuya-Local for the device deakon_evi_waterheatpump.yaml after each Tuya-Local update because my code is different than the one that comes with the Tuya-Local update.

The code I am using is the following. It would be ideal to have it right off the bat with every update.

```
name: Radiator heatpump
products:
  - id: 02ek8thasvo40fmd
    name: Deakon EVI A2pro
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
          hidden: true
        - dps_val: true
          constraint: mode
          conditions:
            - dps_val: hot
              value: heat
              hidden: true
            - dps_val: cold
              value: cool
              hidden: true
            - dps_val: hotwater
              value: "off"
            - dps_val: hot_hotwater
              value: heat
            - dps_val: cold_hotwater
              value: cool
    - id: 2
      type: integer
      name: temperature
      unit: C
      range:
        min: 7
        max: 60
    - id: 3
      type: integer
      name: current_temperature
    - id: 4
      type: string
      name: mode
      hidden: true
    - id: 103
      type: string
      name: hvac_action
      mapping:
        - dps_val: "off"
          value: idle
        - dps_val: "on"
          value: heating
          constraint: mode
          conditions:
            - dps_val: cold
              value: cooling
        - dps_val: defrost
          value: heating
        - dps_val: antifrozen
          value: heating
    - id: 105
      type: integer
      name: inquire_value
    - id: 107
      type: integer
      name: set_value
      range:
        min: -100
        max: 999
    - id: 109
      type: string
      name: error_code_table
    - id: 110
      type: string
      name: error_code_table2
    - id: 111
      type: string
      name: driver_error_code1
    - id: 112
      type: string
      name: driver_error_code2
    - id: 113
      type: string
      name: sen_sys_error_code1
    - id: 114
      type: string
      name: sen_sys_error_code2
secondary_entities:
  - entity: select
    name: Combined mode
    icon: "mdi:heat-pump"
    category: config
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: hot
            value: Heating only
          - dps_val: cold
            value: Cooling only
          - dps_val: hotwater
            value: Hot water only
          - dps_val: hot_hotwater
            value: Hot water + heating
          - dps_val: cold_hotwater
            value: Hot water + cooling
  - entity: select
    name: Temperature target
    category: config
    dps:
      - id: 5
        type: string
        name: option
        mapping:
          - dps_val: HotWater
            value: Hot water
            icon: "mdi:water-thermometer"
          - dps_val: Hot
            value: Heating
            icon: "mdi:home-thermometer"
          - dps_val: Cooling
            icon: "mdi:snowflake-thermometer"
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 13
        type: bitfield
        name: fault_code
  - entity: binary_sensor
    translation_key: defrost
    category: diagnostic
    dps:
      - id: 103
        type: string
        name: sensor
        mapping:
          - dps_val: defrost
            value: true
          - value: false
  - entity: binary_sensor
    name: Anti-freeze
    class: cold
    category: diagnostic
    dps:
      - id: 103
        type: string
        name: sensor
        mapping:
          - dps_val: antifrozen
            value: true
          - value: false
  - entity: select
    name: Inquire_ID
    category: config
    dps:
      - id: 104
        # mappings based on dev portal info, observed values and manufacturer's manual. DPID 104 (para. Inquiry) specifies which parameter is inquired and the value is returned using DPID 105 (Inquiry Value).
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: version no.
          - dps_val: "2"
            value: ambient temp.
          - dps_val: "3"
            value: water tank temp.
          - dps_val: "4"
            value: outlet water temp.
          - dps_val: "5"
            value: inlet water temp.
          - dps_val: "6"
            value: evaporator coil temp.
          - dps_val: "7"
            value: exhaust gas temp.
          - dps_val: "8"
            value: condenser coil temp. (after throttling)
          - dps_val: "9"
            value: suction temp.
          - dps_val: "10"
            value: module temp.
          - dps_val: "11"
            value: main valve opening degrees
          - dps_val: "12"
            value: auxiliary valve opening degrees
          - dps_val: "13"
            value: exhaust gas valve opening degrees
          - dps_val: "14"
            value: Fan speed
          - dps_val: "15"
            value: running frequency
          - dps_val: "16"
            value: AC voltage
          - dps_val: "17"
            value: DC voltage
          - dps_val: "18"
            value: current of whole unit
          - dps_val: "19"
            value: compressor current
          - dps_val: "20"
            value: output power
          - dps_val: "21"
            value: EVI plate heat exchanger inlet sensor
          - dps_val: "22"
            value: EVI plate heat exchanger outlet sensor
          - dps_val: "23"
            value: low pressure
          - dps_val: "24"
            value: high pressure
          - dps_val: "25"
            value: error code
          - dps_val: "26"
            value: limited frequency code
          - dps_val: "27"
            value: LCD Controller version
          - dps_val: "28"
            value: MCU1 version
          - dps_val: "29"
            value: MCU2 version
          - dps_val: "30"
            value: MCU3 version
          - dps_val: "31"
            value: Error History
  - entity: select
    name: Set_ID
    category: config
    dps:
      - id: 106
        # mappings based on dev portal info, observed values and manufacturer's manual. DPID 106 (Para. Setting) specifies which parameter is set using the value in DPID 107 (Set Value).
        type: string
        name: option
        mapping:
          - dps_val: "d01"
            value: Heating Temp Setting
          - dps_val: "d02"
            value: Heating Water Tank Temp Setting
          - dps_val: "d03"
            value: Cooling Temp Setting
          - dps_val: "d04"
            value: Restart Temp Difference 
          - dps_val: "d05"
            value: Selection on Control basis
          - dps_val: "d06"
            value: Setting Temp Of Electric Heater
          - dps_val: "d07"
            value: Deviation Time of Electric Heater Start
          - dps_val: "d08"
            value: Evaporator coil Temp to enter into defrosting
          - dps_val: "d09"
            value: Evaporator coil Temp to exit defrosting 
          - dps_val: "d10"
            value: Defrosting Cycle Period
          - dps_val: "d11"
            value: Defrosting Time
          - dps_val: "d12"
            value: Selection on Control after temp is reached
          - dps_val: "d13"
            value: Ambient temp for Stopping and Starting machine
          - dps_val: "d14"
            value: Temp Difference of Inlet and Outlet water for heat pump's
          - dps_val: "d15"
            value: Working Way of Water Pump
```
