### DISCUSSION TITLE
kesser_infrared_heater.yaml

### DISCUSSION THREAD

**Discussion by eldi0s** [make-all/tuya-local#2366] [Ideas]
Hi,

there is a version of this ir heater with integrated lights. I have it working like this by editing the existing file:
```

name: Infrared heater
products:
  - id: trsas9jlfgcbxhq9
    name: Kesser 3000W
primary_entity:
  entity: switch
  name: Power
  icon: "mdi:radiator"
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: select
    name: Mode
    icon: "mdi:radiator"
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: "P0"
            value: "Off"
          - dps_val: "P1"
            value: "1000W"
          - dps_val: "P2"
            value: "2000W"
          - dps_val: "P3"
            value: "3000W"
  - entity: light
    name: floodlight
    icon: "mdi:lightbulb"
    dps:
      - id: 10
        type: boolean
        name: switch
```

Can you please officially add it?

THX
