### DISCUSSION TITLE
How use entity "event.video_doorbell" as trigger in automation?

### DISCUSSION THREAD

**Discussion by labaland** [make-all/tuya-local#2392] [Q&A]
Hi!
I dont know how to set the button on my doorbell as trigger in ha.. i guess i have to use event as trigger? But i dont know what to listen for in ha so i can see it! Someone know how to make it as trigger? :)  

sry bad english 

![image](https://github.com/user-attachments/assets/fe0556d3-ca88-4019-8a79-bd4b55a36da3)

**Comment by make-all** [comment]
You should trigger on event_type: ring. If you have multiple buttons, and you want to only trigger on a specific button, I think you can use the raw_event to match the id of the button.

**Reply by labaland** [reply]
> You should trigger on event_type: ring. If you have multiple buttons, and you want to only trigger on a specific button, I think you can use the raw_event to match the id of the button.

hmm i have tried theese 3 but no trigger :/
ty for answer :)  

```
  - trigger: event
    event_type: ring
    event_data:
      event_type: ring
      device_class: doorbell
      friendly_name: Video Doorbell - Ring
    enabled: true
    id: "1"

  - trigger: state
    entity_id:
      - event.video_doorbell_ring
    attribute: event_type
    to: ring
    id: "2"

  - trigger: event
    event_type: ring
    event_data:
      raw_event: "1728920217"
    id: "3"
```
