### DISCUSSION TITLE
When setting hidden: true on a sensor with a single DP, I still see the sensor in Home Assistant - is this expected?

### DISCUSSION THREAD

**Discussion by ncd7** [make-all/tuya-local#2517] [Q&A]
I want to hide the sensor completely and but it doesn't seem to work as expected.
Does anyone know if it's possible?

eg

```
secondary_entities:
  - entity: switch
    name: "In Fahrenheit?"
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 102
        type: boolean
        name: switch
        # for now marking as read-only and hidden as it seems to create some issues or I don't know how to set it up correctly
        hidden: true
```

I would like to have that sensor and DP but to hide the sensor in Home Assistant by default.
Is that possible?
Thanks.
