### DISCUSSION TITLE
Cecotec BigDry 4000 Expert yaml file

### DISCUSSION THREAD

**Discussion by darth-hp** [make-all/tuya-local#2571] [General]
Hey guys,

I created this `cecotec_bigdry_4000_dehumidifier.yaml` from snippets of other devices. It looks like it's mostly working, yet switching between Celsius and Fahrenheit does not work as expected and the UV part is kinda strange.

At the beginning it looks like this:
<img width="302" alt="image" src="https://github.com/user-attachments/assets/75b0d166-043c-426a-8617-f97330928286">
When selecting either Celsius or Fahrenheit it has an effect on Temperatur but it disappears after few seconds.
Similar to UV - selecting either flash off/on a switch button appears either off/on depending on the selection and disappears after also a few seconds.

Ideas welcome.

<details>
  <summary>YAML</summary>

```yaml
name: BigDry 4000 Expert
products:
  - id: d44nan1uokr1hlwf
    name: Cecotec BigDry 4000 Expert
    # {"dps": {"1": true, "3": "60", "4": "low", "6": 54, "7": 23, "19": 0}}
primary_entity:
  entity: humidifier
  class: dehumidifier
  name: Dehumidifier
  dps:
    - id: 1
      name: switch
      type: boolean
    - id: 3
      type: integer
      name: humidity
      range:
        min: 40
        max: 80
      mapping:
        - step: 5
    - id: 6
      name: current_humidity
      type: integer

secondary_entities:
  - entity: switch
    name: Power
    dps:
      - id: 1
        name: switch
        type: boolean
  - entity: select
    name: Fan Speed
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: low
            value: Low
          - dps_val: high
            value: High
  - entity: sensor
    class: temperature
    dps:
      - id: 7
        type: integer
        name: sensor
        class: measurement
      - id: 24
        type: string
        name: unit
        optional: true
        mapping:
          - dps_val: c
            value: C
          - dps_val: f
            value: F
  - entity: switch
    translation_key: uv_sterilization
    category: config
    dps:
      - id: 13
        type: boolean
        name: switch
        optional: true
  - entity: binary_sensor
    translation_key: tank_full
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 1
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    dps:
      - id: 19
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: 1
            value: false
          - dps_val: null
            value: false
          - value: true
      - id: 19
        type: bitfield
        name: fault_code
      - id: 19
        name: description
        type: bitfield
        mapping:
          - dps_val: 0
            value: OK
          - dps_val: 1
            value: "Water Tank Full or Removed"
          - dps_val: 2
            value: "E2 Compressor Fault"
  - entity: select
    translation_key: temperature_unit
    category: config
    dps:
      - id: 24
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: c
            value: celsius
          - dps_val: f
            value: fahrenheit
```
</details>

I pulled this DPs from the tuya cloud for the device

<details>
  <summary>JSON</summary>

```json
[
  {
    "abilityId": 1,
    "accessMode": "rw",
    "code": "switch",
    "description": "",
    "extensions": { "iconName": "icon-dp_power2" },
    "name": "开关",
    "typeSpec": { "type": "bool" }
  },
  {
    "abilityId": 3,
    "accessMode": "rw",
    "code": "dehumidify_set_enum",
    "description": "枚举值数值顺序，需要从小到大排序，否则使用公版APP面板显示会有问题",
    "extensions": { "iconName": "icon-setting" },
    "name": "Dehumidify",
    "typeSpec": {
      "type": "enum",
      "range": ["40", "45", "50", "55", "60", "65", "70", "75", "80"]
    }
  },
  {
    "abilityId": 4,
    "accessMode": "rw",
    "code": "fan_speed_enum",
    "description": "",
    "extensions": { "iconName": "icon-dp_wind" },
    "name": "Speed",
    "typeSpec": { "type": "enum", "range": ["low", "high"] }
  },
  {
    "abilityId": 6,
    "accessMode": "ro",
    "code": "humidity_indoor",
    "description": "",
    "extensions": { "iconName": "icon-shidu" },
    "name": "室内湿度",
    "typeSpec": {
      "type": "value",
      "max": 100,
      "min": 0,
      "scale": 0,
      "step": 1,
      "unit": "%"
    }
  },
  {
    "abilityId": 7,
    "accessMode": "ro",
    "code": "temp_indoor",
    "description": "",
    "extensions": { "iconName": "icon-wendu2" },
    "name": "室内温度",
    "typeSpec": {
      "type": "value",
      "max": 100,
      "min": 0,
      "scale": 0,
      "step": 1,
      "unit": "℃"
    }
  },
  {
    "abilityId": 13,
    "accessMode": "rw",
    "code": "uv",
    "description": "",
    "extensions": { "iconName": "icon-dp_power2" },
    "name": "UV杀菌",
    "typeSpec": { "type": "bool" }
  },
  {
    "abilityId": 19,
    "accessMode": "ro",
    "code": "fault",
    "description": "",
    "extensions": { "iconName": "icon-baojing" },
    "name": "故障告警",
    "typeSpec": { "type": "bitmap", "label": ["E1", "E2"], "maxlen": 2 }
  },
  {
    "abilityId": 24,
    "accessMode": "rw",
    "code": "temp_unit_convert",
    "description": "",
    "extensions": { "iconName": "icon-dp_mode", "attribute": "128" },
    "name": "温标切换",
    "typeSpec": { "type": "enum", "range": ["c", "f"] }
  }
]
```
</details>
