### DISCUSSION TITLE
Use an entity state in device yaml

### DISCUSSION THREAD

**Discussion by Bo-Duke** [make-all/tuya-local#2607] [Q&A]
Is there a way to use the state from a random entity as a value in the device yaml?

My usecase is this : 

I have a led strip, I managed to define a list of activable effects by using Tuya's IOT platform, I have all of them in a custom device yaml based on [dreamlight_led_strip.yaml](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/dreamlight_led_strip.yaml) and it works like a charm.

Example of my effect selector :

```
secondary_entities:
  - entity: select
    name: Scene
    category: config
    icon: "mdi:palette"
    dps:
      - id: 51
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "AQAFZGSQAAAyAAIAAAJk"
            value: "My DIY"
          - dps_val: "ATcKWlpgAABkADNYABhkAQBFA0NeAKww"
            value: "Neon"
```

The problem is that I have a list of pre-defined effects but if I want to add a new one I have to edit the yaml and re-add the device.

Is there a way to have one of the values of my mapping to be equal to an entity state? 

Something like 
```
- dps_val: States("text_input.my_custom_effect")
  value: "Custom"
```

This way if I want to add a custom effect I can just select "Custom" and it'll use the value of the entity state which is populated with a value via a custom card or whatever.

Or maybe via a service call I didn't find?

Thanks!
