### DISCUSSION TITLE
Scale mapping on Base64 DPs

### DISCUSSION THREAD

**Discussion by imurch01** [make-all/tuya-local#2751] [Q&A] [answered]
Hi,

I'm working on a config for a thermostat and starting to have some good success - configuring my devices works, the info shown on the dashboard is mostly correct, and operations like changing HVAC modes and display brightness work beautifully.

I say the info shown on the dashboard is mostly correct, because I'm having a little trouble with current temperature & humidity.
These are coded in a complex base64 DP as a 2-byte big endian array of Indoor sensor temp, Outdoor sensor temp, "weather" (I'm guessing this is a cloud-derived outdoor temperature estimate), humidity and error bit-codes.

So currently when I query via Tuya Cloud, the DP is returning APX//wEYAC8AIA== which decodes as 245, 65535, 280, 47, 32.
Temperatures (in C) are scaled by 10 throughout the device implementation, which corresponds with the fact the device is displaying 24.5 C as the current temperature, and 47% humidity. I have no outdoor sensor.

In my device config yaml, I've modelled these under a climate entity with:
```
    - id: 131
      name: current_temperature
      optional: true
      type: base64
      mask: FF00000000
      mapping:
        - scale: 10
    - id: 131
      name: current_humidity
      optional: true
      type: base64
      mask: 000000FF00
    - id: 131
      name: weather
      optional: true
      type: base64
      mask: 0000FF0000
      mapping:
        - scale: 10
    - id: 131
      name: alarm_bits
      optional: true
      type: base64
      mask: 00000000FF
```

But my climate entity is currently showing 2.4 C for current temperature, 4.8 C for weather, and 0% humidity.
I'm guessing scaling via the mapping doesn't work the way I'm trying to use it here? Or should I keep hunting for some other issue?
And if scaling that way won't work for a complex base64 DP, do you have any pointers/suggestions about other approaches?
