### DISCUSSION TITLE
How to add new sub/gateway devices?

### DISCUSSION THREAD

**Discussion by privatecoder** [make-all/tuya-local#2765] [Q&A] [answered]
I have some roller blinds I want to add, which are subdevices of a gateway. However I only find find four devices to select from, namely

<img width="254" alt="image" src="https://github.com/user-attachments/assets/054803b4-3585-4741-9ef3-797d30eb8017" />

However I cannot find this selection in the code to add another device. The question is: What is controlling the visibility of a device added via a yaml-config as gateway sub-device?

**Comment by make-all** [comment]
1. product id (in latest version only, and only when using the cloud config flow).
2. the dps available from the device compared with what is expected by the config.

**Reply by privatecoder** [reply, marked as answer]
@make-all thank you! Here is what I came up with:
```
name: Roller blind
products:
  - id: slrxhmozdm3qq9cl
    manufacturer: GW Motor
    model: Roller blind
    name: Sub-device roller blind (gateway)
entities:
  - entity: cover
    class: blind
    dps:
      - id: 1
        name: control
        type: string
        mapping:
          - conditions:
              - dps_val: ["0", "1", "2"]
                mapping:
                  - dps_val: "0"
                    value: open
                  - dps_val: "1"
                    value: close
                  - dps_val: "2"
                    value: stop
              # set options when there are non during startup
              - dps_val: null
                mapping:
                  - dps_val: open
                    value: open
                  - dps_val: close
                    value: close
                  - dps_val: stop
                    value: stop
      - id: 2
        # this is percent_control in the API Explorer but we'll use it to get the
        # last position set, as the device cannot report its current_position.
        # will be incorrect when manually opening / closing.
        name: percent_control
        type: integer
        unit: "%"
        optional: true
        range:
          min: 0
          max: 100
      - id: 101
        name: position
        type: integer
        unit: "%"
        range:
          min: 0
          max: 100
```

This lets me control up/down and set a percentage value.
