### DISCUSSION TITLE
ME80 smart thermostat

### DISCUSSION THREAD

**Discussion by cdesp** [make-all/tuya-local#2792] [General]
I bought this Tuya Wifi Smart Thermostat Temperature Controller Electric Floor Heating Water Heating LCD Display for Alice Alexa Google Home from aliexpress and it is probably an ME80 compatible device. Everything works ok except the two settings for activating the device Auto and heat. I changed the code on me80_thermostat.yaml from:

   
```
 - id: 1
  type: boolean
  name: hvac_mode
  mapping:
    - dps_val: true
      constraint: preset_mode
      conditions:
        - dps_val: auto
          value: "auto"
        - dps_val: manual
          value: "heat"
```

to this:
```      - id: 1
        type: boolean
        name: hvac_mode
        mapping:
          - dps_val: true
            value: heat
          - dps_val: false
            value: "off"
```
and at least now i can open it to manual setting.

The problem is that every time there is a new version this file gets overwritten. I even copied this file to a new one but still the new file gets deleted. Is there any way to have this change be permanenet in the device list?
