### DISCUSSION TITLE
DTS238-7 Energy Meter Configuration

### DISCUSSION THREAD

**Discussion by andyrisko** [make-all/tuya-local#2861] [Q&A]
I purchased the [DTS238-7 energy meter](https://www.aliexpress.com/item/1005004987892397.html) and encountered issues with the official Tuya integration in Home Assistant, as it incorrectly handles the device. The Tuya Local integration has a similarly named file: [dts238_7_energy_meter.yaml](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/dts238_7_energy_meter.yaml), but it recognizes the device as [earu_smart_wifi_circuit_breaker_with_energy_monitor.yaml](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/earu_smart_wifi_circuit_breaker_with_energy_monitor.yaml).

I managed to obtain some original documentation (attached) and modified the original configuration file so that the device is now recognized and displays correct values:

```
name: Energy meter
products:
  - id: i55reuttymjocx0j
    name: DTS238-7 Smart meter IVAP
entities:
  - entity: sensor
    name: Total energy
    class: energy
    dps:
      - id: 1
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 100
  - entity: sensor
    name: Total Active Power
    class: power
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: W
  - entity: sensor
    name: Total Reactive Power
    class: reactive_power
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        unit: var
  - entity: sensor
    name: Grid Frequency
    class: frequency
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        unit: Hz
  - entity: sensor
    name: Total Power Factor
    class: power_factor
    category: diagnostic
    dps:
      - id: 111
        type: integer
        name: sensor
        unit: "%"
        mapping:
          - scale: 1000
```

However, I got stuck with per-phase handling, like this:

```
- entity: sensor
  name: Active Power A
  class: power
  category: diagnostic
  dps:
    - id: 6
      type: base64
      name: sensor
      unit: kW
      mapping:
        - mask: "FFFFFFFF0000000000000000000000"
          scale: 1000
```

I need help with the following:

Should I modify the original configuration file, knowing that an update might overwrite my changes? The issue is that not even the IDs match – the original file uses 1rlikmowi2erb6qw, while mine uses i55reuttymjocx0j. Should I create a new file in a more protected location where the integration will still recognize it?
Should I try forking the repository? Maybe I will eventually figure it out.
I’m not an expert, but I would like to track reactive power on a graph. Any guidance would be much appreciated!
[protocol_i55reuttymjocx0j_20230807.pdf](https://github.com/user-attachments/files/18565724/protocol_i55reuttymjocx0j_20230807.pdf)
