### DISCUSSION TITLE
Problem defining new device Klarstein Bornholm Smart

### DISCUSSION THREAD

**Discussion by istenik** [make-all/tuya-local#2863] [General]
Hi.
I have problem adding this device.

```
name:  Klarstein Bornholm Smart Heater
products:
  - id: movachsonarakbut
    name: Klarstein Bornholm Smart 2023
entities:
  - entity: climate
    translation_only_key: heater
    dps:
      - id: 1
        type: boolean
        name: hvac_mode
        mapping:
          - dps_val: false
            value: "off"
          - dps_val: true
            value: heat
      - id: 2
        type: integer
        name: temperature
        range:
          min: 5
          max: 45
        unit: C
      - id: 3
        type: integer
        name: current_temperature
        unit: C
      - id: 4
        type: string
        name: preset_mode
        mapping:
          - dps_val: high
            value: high
          - dps_val: low
            value: low
          - dps_val: empty
            value: idle
  - entity: binary_sensor
    name: ECO
    translation_key: eco_mode
    category: config
    dps:
      - id: 5
        type: boolean
        name: switch
  - entity: lock
    translation_key: child_lock
    category: config
    dps:
      - id: 6
        type: boolean
        name: lock
  - entity: light
    translation_key: display
    category: config
    dps:
      - id: 104
        type: boolean
        name: switch
        mapping:
          - dps_val: true
            value: false
          - dps_val: false
            value: true
  - entity: select
    translation_key: timer
    category: config
    dps:
      - id: 10
        type: string
        name: option
        mapping:
          - dps_val: 0
            value: cancel
          - dps_val: 1h
            value: 1h
          - dps_val: 2h
            value: 2h
          - dps_val: 3h
            value: 3h
          - dps_val: 4h
            value: 4h
          - dps_val: 5h
            value: 5h
          - dps_val: 6h
            value: 6h
          - dps_val: 7h
            value: 7h
          - dps_val: 8h
            value: 8h
          - dps_val: 9h
            value: 9h
          - dps_val: 10h
            value: 10h
          - dps_val: 11h
            value: 11h
          - dps_val: 12h
            value: 12h
          - dps_val: 13h
            value: 13h
          - dps_val: 14h
            value: 14h
          - dps_val: 15h
            value: 15h
          - dps_val: 16h
            value: 16h
          - dps_val: 17h
            value: 17h
          - dps_val: 18h
            value: 18h
          - dps_val: 19h
            value: 19h
          - dps_val: 20h
            value: 20h
          - dps_val: 21h
            value: 21h
          - dps_val: 22h
            value: 22h
          - dps_val: 23h
            value: 23h
          - dps_val: 24h
            value: 24h

```

Error:

```
2025-01-28 11:18:50.260 ERROR (MainThread) [custom_components.tuya_local.helpers.config] Error adding binary_sensor_eco for klarstein_bornholm_smart.yaml: 'sensor'
2025-01-28 11:18:50.278 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tuya_local platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/tuya_local/binary_sensor.py", line 22, in async_setup_entry
    await async_tuya_setup_platform(
    ...<5 lines>...
    )
  File "/config/custom_components/tuya_local/helpers/config.py", line 45, in async_tuya_setup_platform
    raise ValueError(f"{device.name} does not support use as a {platform} device.")
ValueError: Klarstein Bornholm Smart Heater does not support use as a binary_sensor device.

```
