### DISCUSSION TITLE
Nested mapping

### DISCUSSION THREAD

**Discussion by Kevin-0u** [make-all/tuya-local#2894] [Q&A] [answered]
Is there a good example that showcases how nested mapping is implemented in a device configuration file?

I’m working on a device configuration file for a floor heater thermostat, where the temperature's `max`, `min`, and `step` values are influenced by two other DPs - `temperature_unit` and `hvac_mode`. I read the documentation but couldn’t fully grasp how to do it correctly. Here is the data model for the specific DP I retrieved via the Tuya IoT API, with comments translating the Chinese descriptions into English:

```
  - abilityId: 102
    accessMode: rw
    code: SetTemp
    # The temperature range is 5-40°C with a step of 5 (0.5°C) in Celsius and 41-104°F with a step of 10 (1°F) in Fahrenheit.
    # In ANTI_FROZEN mode, the temperature range is 5-15°C with a step of 5 in Celsius and 41-59°F with a step of 10 in Fahrenheit.
    description: "摄氏度,间距为5,  5----40℃\\n华氏度,间距为10, 41--104℉\\nANTI_FROZEN模式时 :摄氏度,间距为5,  5----15℃\\n           华氏度,间距为10, 41---59℉"
    name: 设置温度 # Set temperature
    typeSpec:
      type: value
      max: 1040
      min: 41 # The minimum temperature should be 50
      scale: 1 # The scale should be 10
      step: 1 # The step should be 5 for Celsius and 10 for Fahrenheit
      unit: ""
```
