### DISCUSSION TITLE
Only a small number of devices to pick from

### DISCUSSION THREAD

**Discussion by alanrothenbush** [make-all/tuya-local#2993] [Q&A] [answered]
Just installed Tuya Local, chose "Smart Life" and it found my device!  (Jafanda Air Purifier)  Yay!

Then it asked me to pick my device from a list (of YAML config files, I assume).  My plan was to pick one I felt was close, and then manually tweak the file.

Unfortunately, the device I wanted wasn't there to be picked.  In fact, just a very very small number of devices were in the list .. a dozen or so.

Huh?  Am I doing something wrong?

Thanks for any thoughts.

**Comment by make-all** [comment]
Only devices where dps are not mismatching are displayed.

At the first step, it is just finding your device from the cloud, it does not mean there is a matching config file for this device already.

**Reply by alanrothenbush** [reply]
Thanks for this!  I wiped everything and restarted, beginning by creating a really basic device file that included the ID of my fan.  This time, it all worked as hoped!  Now to figure out how to write a better YAML file.  Thanks again.

**Reply by alanrothenbush** [reply]
This is weird, and becoming annoying.  

I was methodically adding entities to my YAML file .. light, temperature sensor, humidity sensor, etc.  

I had to delete the Device, then add it again .. no other way that I could see to get the integration to read the changed YAML file.

Got as far as 7 entities!  Pretty happy.  One to go .. fan speed.  Should be easy, I thought, a number from 1 to 5.  Looked at a few other device files, found one close, did a copy and paste.  Didn't work; still seven entities.  

Tried a different way to do it .. via a "Select".  Got an error ; guess you can't select integers.

OK, forget fan speed for now .. other things to do.  Usually want Auto anyway and that was working.  Roll back to the last working YAML and add the Device yet again.  

Now got "Unknown Error" .. when doing precisely the same thing as I'd been doing for a couple of hours, with the YAML that had worked 5 minutes earlier!  Tried a few times, same result.

DARN.  OK, start from scratch.  Delete the integration, restart HA.  Re-add the integration, restart HA.  Drop the last working version of my YAML back into the Devices directory, restart HA.  

Add a device .. easy right .. done this LOTS and LOTS of times in the past couple of hours.

Doesn't find the YAML for my device!  Finds the same list of a dozen or so devices as found previously, as if my YAML wasn't there at all!

SSH in. 

```
[core-ssh devices]$ ls -al jafa*
-rw-r--r--    1 root     root           196 Feb 21 16:12 jafanda_jt999_air_purifier.yaml
[core-ssh devices]$
```

Yup, there is is.  Permissions look correct (644).  

cat the file.  It's the right file.

Hmm, OK, replace the file (with seven entities defined) with a VERY stripped down version of my YAML, nothing but a power switch.

```
name: Air Purifier
products:
  - id: eb13faf8ff5164878evydk
    manufacturer: Jafanda
    model: JT999a
entities:
  - entity: fan
    dps:
      - id: 1
        name: switch
        type: boolean
```

Try again, SAME steps as I've taken SO MANY TIMES already.  Different behaviour .. now it finds but a single device to choose from, a curtain closer.  The list of 12, all of them wrong, is down to 1, also wrong.

Kinda confused now.  Was working perfectly ...

**Reply by alanrothenbush** [reply]
BTW, here's the YAML that WAS working .. except for the fan speed.

```
name: Air Purifier
products:
  - id: eb13faf8ff5164878evydk
    manufacturer: Jafanda
    model: JT999a
entities:
  - entity: fan
    dps:
      - id: 1
        name: switch
        type: boolean
      - id: 4
        type: integer
        name: fan_speed_enum
        range:
          min: 1
          max: 5
  - entity: sensor
    class: pm25
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: µg/m³
   - entity: select
    name: Mode
    dps:
      - id: 3
        name: option
        type: string
        mapping:
          - dps_val: auto
            value: Auto
          - dps_val: manual
            value: Manual
          - dps_val: sleep
            value: Sleep
  - entity: select
    name: Light
    dps:
      - id: 101
        name: option
        type: string
        mapping:
          - dps_val: twenty_five_percent
            value: 25%
          - dps_val: fifty_percent
            value: 50%
          - dps_val: a_hundred_percent
            value: 100%
          - dps_val: displayoff
            value: Display Off
  - entity: sensor
    name: Active filter life
    icon: "mdi:air-filter"
    category: diagnostic
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: "%"
  - entity: sensor
    class: temperature
    dps:
      - id: 12
        name: sensor
        type: integer
        unit: C
        class: measurement
  - entity: sensor
    class: humidity
    dps:
      - id: 13
        type: integer
        name: sensor
        unit: "%"
        class: measurement

```
