### DISCUSSION TITLE
Help getting a better fan speed display.

### DISCUSSION THREAD

**Discussion by alanrothenbush** [make-all/tuya-local#2999] [Q&A]
Well, I've had some problems getting my Jafanda Air Purifier working under Tuya Local, but I'm finally there, with one annoying little niggle.  Let's start with a bit of the Yaml.
```
entities:
  - entity: switch
    dps:
      - id: 1
        name: switch
        type: boolean
  - entity: fan
    dps:
      - id: 4
        name: speed
        type: integer
        mode: auto   
        range:
          min: 1
          max: 5
```
This results in two entities, a Fan and a Switch.
![Capture](https://github.com/user-attachments/assets/05e18fd8-1508-4a43-9977-5747545cda8a)
However, the Speed entity **_doesn't_** show the speed, but **_does_** shows a switch, even though the YAML does not define one!  
Clicking on the switch just generates an error.
![Capture1](https://github.com/user-attachments/assets/4dff8220-1929-4b02-813f-207099619763)
Note there's no way to set the fan speed from here, all I can do is make myself mad.  If I open the entity, I get
![Capture2](https://github.com/user-attachments/assets/3f53a29d-6637-465c-bb6f-f403d131910d)
which includes the undefined switch (that still generates an error) and a slider, that also generates an error if you slide it all the way to the bottom.
![Capture3](https://github.com/user-attachments/assets/b4e2c671-9bed-4c32-83b7-b1a5de1e80d1)
Is there some way to create an entity that actually (usefully) shows the current fan speed right from the "root" card, and also allows a fan speed to be set from there?  Some sort of drop down maybe?  And one that does not include a nonexistent switch?

Thanks for any thoughts.
