### DISCUSSION TITLE
Need help crafting YAML config for fireplace with 2-stage heat modes

### DISCUSSION THREAD

**Discussion by Kevin-0u** [make-all/tuya-local#3030] [Q&A] [answered]
I'm working on a device configuration YAML for a smart fireplace. The fireplace has 3 heat modes (plus an "off" state), and I’m struggling to map them effectively to a `climate` entity. Here’s the relevant Tuya DP (data point) info:

        abilityId: 108
        accessMode: rw
        code: Heat
        description: ''
        name: Heat
        typeSpec:
            type: enum
            range:
                - 'OFF'
                - H1
                - H2
                - Auto

In the Tuya app, these modes are labeled as "Off," "Low," "High," and "Auto." However, the `hvac_mode` attribute in a `climate` entity doesn’t directly support "Low Heat" or "High Heat" options. My current YAML attempt looks like this:

```
  - entity: climate
    icon: "mdi:fireplace"
    dps:
      - id: 108
        name: hvac_mode
        type: string
        mapping:
          - dps_val: "OFF"
            value: "off"
          - dps_val: H1
            value: heat_cool
          - dps_val: H2
            value: heat
          - dps_val: Auto
            value: auto
```

The issue is that heat_cool and heat don’t accurately reflect "Low" and "High" heat modes, making the mapping feel imprecise. Is there a better way to handle this in the YAML config? Perhaps a different entity type or a custom approach to represent these heat levels more intuitively? Any suggestions or examples would be greatly appreciated!
