### DISCUSSION TITLE
Can't create cilmate entity with temperature in fahrenheit

### DISCUSSION THREAD

**Discussion by vvv2542** [make-all/tuya-local#3145] [Q&A]
I'm trying  to create cilmate entity with temperature in fahrenheit, but thermostat card always shows °C. Simple configuration:
```yaml
name: Temperature controller with display
products:
  - id: rj84vmyhm0dh0jwy
    manufacturer: Atorch
    model: S1TW
entities:
  - entity: climate
    name: Thermostat Test
    unit: F
    dps:
      - id: 113
        type: integer
        name: temperature
        unit: F
        mapping:
          - scale: 10
      - id: 113
        type: integer
        name: current_temperature
        unit: F
        mapping:
          - scale: 10
```
The card looks like this:
![изображение](https://github.com/user-attachments/assets/0e9f45ca-c796-4baa-b02c-b07c3ceb301d)
What am I doing wrong?
