### DISCUSSION TITLE
How to use Remote send and learn

### DISCUSSION THREAD

**Discussion by JabeBRD** [make-all/tuya-local#3154] [Q&A]
I have Avatto WHS20S and i have configured it, it has `id` `201` and `202`.
I can see it as remote in HA.
When i try to learn code from my TV remote, HA shows it as success, but i cant find any code in HA.
If i open Tuya developer tools, i can see that my device gets `learn` command and it sends that IR code.
Also if i try to copy that code from Tuya developer tools to HA as `send` code, it does not work, it is not accepted.
Where this learned code should go? Or are these unsupported features in Tuya Local?

This is code in my device config
```
  - entity: remote
    dps:
      - id: 201
        name: send
        type: string
        optional: true
      - id: 202
        name: receive
        type: string
        optional: true
        persist: false
```
