### DISCUSSION TITLE
Add a new 3 phase Tuya charger

### DISCUSSION THREAD

**Discussion by sigxcpu76** [make-all/tuya-local#3266] [Show and tell]
Hi,
I have a charger very similar to `goodcell_ev_charger`. I've tried to add the product ID to that YAML, restarted Home Assistant but I still don't get it in suggestions. Tried to create a separate file, copy of goodcell and put only that product id in there, still not shown in the matching list.

Is there anything else that needs to match besides (some) DPS and the product ID?

tinytuya wizard shows
```
{
  "name": "AC charging pile",
  "id": "bf218747a70cff7a6ax3iu",
  "key": "}=eF'Uyyz[Uxe{?!",
  "mac": "38:2c:e5:f1:83:9f",
  "uuid": "c03f0968e2f340fb",
  "sn": "10016519120E6D",
  "category": "qccdz",
  "product_name": "AC charging pile",
  "product_id": "ppvclgmzvwgdyjxv",
  "biz_type": 18,
  "model": "",
  "sub": false,
  "icon": "https://images.tuyaeu.com/smart/icon/bay16226250696545rLI/4e52c4c01d82ce20cebbb863b198c6f4.png",
  "mapping": {
    "3": {
      "code": "work_state",
      "type": "Enum",
      "values": {
        "range": [
          "charger_free",
          "charger_insert",
          "charger_free_fault",
          "charger_wait",
          "charger_charging",
          "charger_pause",
          "charger_end",
          "charger_fault"
        ]
      }
    },
    "14": {
      "code": "work_mode",
      "type": "Enum",
      "values": {
        "range": [
          "charge_now",
          "charge_pct",
          "charge_energy",
          "charge_schedule"
        ]
      }
    },
    "15": {
      "code": "balance_energy",
      "type": "Integer",
      "values": {
        "unit": "kW·h",
        "min": 0,
        "max": 99999999,
        "scale": 3,
        "step": 1
      }
    },
    "16": {
      "code": "clear_energy",
      "type": "Boolean",
      "values": {}
    },
    "18": {
      "code": "switch",
      "type": "Boolean",
      "values": {}
    },
    "25": {
      "code": "charge_energy_once",
      "type": "Integer",
      "values": {
        "unit": "kW·h",
        "min": 1,
        "max": 999999,
        "scale": 2,
        "step": 1
      }
    }
  }
}
```

and

```
DPS: {'10': 0, '101': 'no_connet', '102': 415, '103': 0, '104': 0, '105': 0, '106': 0, '107': 0, '109': 0, '110': 368, '112': 0, '113': 'Max32A', '115': 8, '116': 32, '117': 32, '118': 0, '119': 0, '120': '00:00:00', '121': 0, '123': True, '124': 'WaitOperation', '125': 32, '126': 32}
```

**Comment by make-all** [comment]
If the cloud method is used to add the device, it should be able to be added if the product id is matched and none of the dp types conflict.

If the manual method is used, or there is no product id match using the cloud match, then all the non-optional dps need to be present, none of the dp types conflict.

When matching, no decoding of values is done, so base64 and hex will match as strings.

**Reply by sigxcpu76** [reply]
Is there anything logged regarding to the matching so I can get a pointer on what to adjust? I don't know how to enable debug logging when there are no devices set yet. I could add a dummy device, enable debug logging and then add the EV charger to collect information.

**Reply by make-all** [reply]
There are messages logged at Warning level when first adding a device, that show the dps that are received.

**Reply by sigxcpu76** [reply]
I have deleted the manually configured device with 4 entities (assuming that it may be an issue) and then I've started all over again. Now I don't get the device type selection screen at all, it jumps to entity adding where I can choose between button/switch/... . I've enabled debug logging at the integration level and at the device level but I don't see the match quality message at all.

**Reply by sigxcpu76** [reply]
~I did even more. I've put all the DPs in optional mode, so it should match on the product ID, right? Unfortunately, I still cannot make it to display the matched devices selection screen anymore.~ I was using LocalTuya, got confused.
OK, so now all the DPSes are `optional: true`, the Product ID is correct, but it is still not displayed as a matching option.

**Comment by sigxcpu76** [comment]
![Screenshot_20250521_160348](https://github.com/user-attachments/assets/f57f01ce-4c64-479b-b619-f6331a14342f)
 These are the only options I get. The new configuration is like this:

```
name: EV charger
legacy_type: feyree_3phase_ev_charger
products:
  - id: ppvclgmzvwgdyjxv
    manufacturer: eMAG
    model: 22kW 3-phase
entities:
  - entity: sensor
    class: enum
    translation_key: status
    icon: "mdi:ev-station"
    dps:
      - id: 101
        type: string
        optional: true
        name: sensor
        mapping:
          - dps_val: no_connet
            value: available
          - dps_val: connect
            value: plugged_in
          - dps_val: charing
            value: charging
          - dps_val: wait_rfid
            value: waiting_for_authorization
          - dps_val: finish
            value: charged
          - dps_val: wait_charing
            value: waiting
          - dps_val: error
            value: fault
          - dps_val: null
            value: unknown
      - id: 3
        type: string
        optional: true
        name: charger_status
        mapping:
          - dps_val: charger_free
            value: Standby
          - dps_val: charger_insert
            value: Cable connected
          - dps_val: charger_free_fault
            value: Charger fault
          - dps_val: charger_wait
            value: Charger ready
          - dps_val: charger_charging
            value: Charging
          - dps_val: charger_pause
            value: Charging paused
          - dps_val: charger_end
            value: Charging ended
          - dps_val: charger_fault
            value: Charger fault
      - id: 11
        type: string
        optional: true
        name: alarm_set_1
      - id: 12
        type: string
        optional: true
        name: alarm_set_2
      - id: 14
        type: string
        optional: true
        name: mode
        mapping:
          - dps_val: charge_now
          - dps_val: charge_pct
          - dps_val: charge_energy
          - dps_val: charge_schedule
      - id: 15
        type: integer
        optional: true
        name: balance_energy
        unit: kWh
      - id: 18
        type: boolean
        optional: true
        name: switch
      - id: 23
        type: string
        optional: true
        name: system_version
      - id: 25
        type: integer
        optional: true
        name: charge_energy_once
        unit: kWh
      - id: 27
        type: string
        optional: true
        name: online_state
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 10
        type: bitfield
        optional: true
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: null
            value: false
          - value: true
      - id: 10
        type: bitfield
        optional: true
        name: fault_code
  - entity: button
    name: Clear energy
    class: restart
    category: config
    dps:
      - id: 16
        type: boolean
        name: button
        optional: true
  - entity: number
    name: Set charge current
    category: config
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 115
        type: integer
        name: value
        optional: true
        unit: A
        range:
          min: 6
          max: 32
        mapping:
          - constraint: max_current
            conditions:
              - dps_val: Max16A
                value_redirect: value_alt
                range:
                  min: 6
                  max: 16
      - id: 114
        type: integer
        optional: true
        name: value_alt
        unit: A
        range:
          min: 6
          max: 16
      - id: 113
        type: string
        name: max_current
        optional: true
        mapping:
          - dps_val: Max16A
            value: Max16A
          - dps_val: Max32A
            value: Max32A
      - id: 125
        type: integer
        optional: true
        name: display
  - entity: number
    name: Charge delay
    category: config
    icon: "mdi:car-clock"
    dps:
      - id: 118
        type: integer
        name: value
        optional: true
        unit: h
        range:
          min: 0
          max: 15
      - id: 121
        type: string
        optional: true
        name: display
  - entity: sensor
    class: energy
    dps:
      - id: 112
        type: integer
        name: sensor
        unit: kWh
        optional: true
        class: total_increasing
        mapping:
          - scale: 10
  - entity: sensor
    translation_key: voltage_x
    translation_placeholders:
      x: L1
    class: voltage
    category: diagnostic
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: V
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    translation_key: voltage_x
    translation_placeholders:
      x: L2
    class: voltage
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: V
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    translation_key: voltage_x
    translation_placeholders:
      x: L3
    class: voltage
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        unit: V
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    translation_key: current_x
    translation_placeholders:
      x: L1
    class: current
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        unit: A
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    translation_key: current_x
    translation_placeholders:
      x: L2
    class: current
    category: diagnostic
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: A
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    translation_key: current_x
    translation_placeholders:
      x: L3
    class: current
    category: diagnostic
    dps:
      - id: 107
        type: integer
        name: sensor
        unit: A
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    class: power
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: kW
        optional: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    class: temperature
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        optional: true
        unit: C
        class: measurement
        mapping:
          - scale: 10
  - entity: number
    name: Charging duration
    category: config
    icon: "mdi:car-clock"
    dps:
      - id: 119
        type: integer
        name: value
        optional: true
        unit: h
        range:
          min: 0
          max: 15
      - id: 120
        type: string
        optional: true
        name: session_duration
      - id: 122
        type: string
        optional: true
        name: display
  - entity: select
    name: Toggle charging
    icon: "mdi:ev-plug-type2"
    category: config
    dps:
      - id: 124
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "OpenCharging"
            value: Start charging
          - dps_val: "CloseCharging"
            value: Stop charging
          - dps_val: "WaitOperation"
            value: Waiting for command
  - entity: switch
    name: RFID
    icon: "mdi:credit-card-wireless"
    category: config
    dps:
      - id: 123
        type: boolean
        name: switch
        optional: true
```
