### DISCUSSION TITLE
Add GenioDesk Product Type:Lifting Table

### DISCUSSION THREAD

**Discussion by luizgfpf** [make-all/tuya-local#3406] [Ideas]
I attempted to create a device type manually, but it does not show up in the list of pre-configured devices.

This is from the tuya developer platform:

![image](https://github.com/user-attachments/assets/e76721f1-8e40-4d34-a280-bdb31ff65451)

**Comment by luizgfpf** [comment]
Nevermind, I got it working by editing the core.config_entries file after selecting a random device type, for future reference if anyone wants to add the same device as mine, here's the yaml file:

```
# /config/custom_components/localtuya/devices/geniodesk_liftingtable.yaml
name: Geniodesk Height Adjustable Desk
products:
  - id: ebc2b9e20a7f1db2a26eyq
    manufacturer: Geniodesk
    model: LiftingTable

entities:
  - entity: cover
    class: shutter
    dps:
      - id: 2
        type: string
        name: command
        mapping:
          - dps_val: up
            value: open
          - dps_val: down
            value: close
          - dps_val: stop
            value: stop
      - id: 8
        type: integer
        name: current_position
      - id: 8
        type: integer
        name: position
        range:
          min: 66
          max: 131

  - entity: sensor
    name: Height
    dps:
      - id: 8
        type: integer
        name: sensor
        unit: cm

  - entity: switch
    name: Child Lock
    category: config
    dps:
      - id: 102
        type: boolean
        name: switch

  - entity: select
    name: Memory Level
    category: config
    dps:
      - id: 3
        type: string
        name: option
        mapping:
          - dps_val: level_1
            value: Level 1
          - dps_val: level_2
            value: Level 2
          - dps_val: level_3
            value: Level 3
          - dps_val: level_4
            value: Level 4

  - entity: sensor
    name: Work State
    category: diagnostic
    dps:
      - id: 1
        type: string
        name: sensor

  - entity: sensor
    name: Fault
    category: diagnostic
    dps:
      - id: 5
        type: bitfield
        name: sensor
```
