### DISCUSSION TITLE
Pioneer Mini Split

### DISCUSSION THREAD

**Discussion by mudojo** [make-all/tuya-local#539] [General]
Hi, I was successfully able to add my Pioneer Mini Split (heat pump) using the Daizuki heat pump profile. Everything works correctly, however the current temp does not show in the main climate card. I was able to add it by modifying daizuki_heatpump.yaml however I need to convert it from Celsius to Fahrenheit. I tried to figure it out but couldn't. Can you add a device for Pioneer with this change or can you help me modify daizuki_heatpump.yaml to make it show correctly?

**Comment by make-all** [comment]
The current temperature does not show in the climate card for the Daizuki heatpump, because the device uses inconsistent units. It uses Fahrenheit for the set temperature, and Celsius for the current temperature, but the climate entity only has one unit specifier so isn't able to represent this correctly.

It does sound like your Pioneer branded heatpump has the same design flaw.

**Comment by Cows2Computers** [comment]
I'm commenting (for future people searching, since it took me 3 hours to find this thread) to say I bought a Rovsun brand mini split off of Amazon and also got it working with the Daizuki heatpump with the same issue of inconsistent units.

**Reply by make-all** [reply]
The issue with inconsistent units on this family of air conditioners is exactly why the current temperature is a separate sensor instead of being integrated into the climate entity for this config.  Separating them like this is the only solution short of fixing the broken device's firmware.

**Comment by Cows2Computers** [comment]
Is it possible to apply a template to do the conversion math like in a automation yaml?

**Reply by make-all** [reply]
There appears to be no climate support in the template integration
https://www.home-assistant.io/integrations/template/

**Reply by Cows2Computers** [reply]
I grow up on a farm. Home Assistant always fills my "agricultural engineering/use duct tape and baling wire" fix.

https://github.com/jcwillox/hass-template-climate 

```yaml
climate:
  - platform: climate_template
    name: Garage - Mini Split Current
    unique_id: garage_mini_split_current
    modes:
      - "off"
      - cool
      - heat
      - dry
      - fan_only
      - heat_cool
    min_temp: 61
    max_temp: 88
    fan_modes:
      - auto
      - quiet
      - low
      - medlow
      - medium
      - medhigh
      - high
      - strong
    swing_modes:
      - "off"
      - horizontal
      - vertical
      - both

    # get current states 
    current_temperature_template: "{{ states('sensor.garage_mini_split_local_2_temperature')}}"
    current_humidity_template: "{{ states('sensor.garage_4_in_1_sensor_humidity') }}"
    target_temperature_template: "{{ state_attr('climate.garage_mini_split_local_2', 'temperature') }}"
    hvac_mode_template: "{{ states('climate.garage_mini_split_local_2') }}"
    fan_mode_template: "{{ state_attr('climate.garage_mini_split_local_2', 'fan_mode') }}"
    swing_mode_template: "{{ state_attr('climate.garage_mini_split_local_2', 'swing_mode') }}"

    # allows you to control an existing Home Assistant HVAC device
    set_temperature:
      - service: climate.set_temperature
        data:
          entity_id: climate.garage_mini_split_local_2
          temperature: "{{ temperature }}"

    set_hvac_mode:
      - service: climate.set_hvac_mode
        data:
          entity_id: climate.garage_mini_split_local_2
          hvac_mode: "{{ hvac_mode }}"

    set_fan_mode:
      - service: climate.set_fan_mode
        data:
          entity_id: climate.garage_mini_split_local_2
          fan_mode: "{{ fan_mode }}"

    set_swing_mode:
      - service: climate.set_swing_mode
        data:
          entity_id: climate.garage_mini_split_local_2
          swing_mode: "{{ swing_mode }}"
```
