### DISCUSSION TITLE
Problem defining new device Inkbird IBBQ-4T

### DISCUSSION THREAD

**Discussion by ShayGus** [make-all/tuya-local#568] [General]
Trying to define a new device this device should be almost identical to IBBQ-4BW.
But for some reason it won't be recognized by the integration. 
This is the device yaml file:
```
name: Inkbird BBQ Thermometer IBBQ-4T
products:
  - id: x6oarivkdgru1upf
    name: IBBQ-4T
primary_entity:
  entity: sensor
  name: Temperature probe 1
  class: temperature
  dps:
    - id: 107
      type: integer
      name: sensor
      class: measurement
      mapping:
        - scale: 100
      unit: F
    - id: 13
      type: bitfield
      name: fault_code
    # - id: 19
    #   type: string
    #   name: unit
secondary_entities:
  - entity: sensor
    name: Temperature probe 2
    class: temperature
    dps:
      - id: 108
        type: integer
        name: sensor
        class: measurement
        mapping:
          - scale: 100
        unit: F
      # - id: 19
      #   type: string
      #   name: unit
  - entity: sensor
    name: Temperature probe 3
    class: temperature
    dps:
      - id: 109
        type: integer
        name: sensor
        class: measurement
        mapping:
          - scale: 100
        unit: F
      # - id: 19
      #   type: string
      #   name: unit
  - entity: sensor
    name: Temperature probe 4
    class: temperature
    dps:
      - id: 110
        type: integer
        name: sensor
        class: measurement
        mapping:
          - scale: 100
        unit: F
      # - id: 19
      #   type: string
      #   name: unit
  - entity: switch
    dps:
      - id: 1
        type: boolean
        name: switch
  - entity: binary_sensor
    name: Fault
    class: problem
    category: diagnostic
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: select
    name: Temperature unit
    icon: "mdi:temperature-celsius"
    category: config
    dps:
      - id: 19
        type: string
        name: option
        mapping:
          - dps_val: F
            value: Fahrenheit
          - dps_val: C
            value: Celsius
  - entity: sensor
    name: Battery
    class: battery
    category: diagnostic
    dps:
      - id: 101
        type: integer
        name: sensor
        unit: "%"
  - entity: number
    name: Screen timeout
    category: config
    icon: "mdi:camera-timer"
    dps:
      - id: 102
        type: integer
        name: value
        unit: s
        range:
          min: 0
          max: 3600
  - entity: switch
    name: Alarm
    category: config
    dps:
      - id: 104
        type: boolean
        name: switch
  - entity: light
    name: Backlight
    category: config
    dps:
      - id: 111
        type: boolean
        name: switch
  - entity: number
    name: Calibration probe 1
    category: config
    icon: "mdi:format-vertical-align-center"
    dps:
      - id: 112
        type: integer
        name: value
        range:
          min: -126
          max: 126
        mapping:
          - scale: 10
            # constraint: temp_unit
            # conditions:
            #   - dps_val: C
            #     range:
            #       min: -70
            #       max: 70
      - id: 19
        type: string
        name: temp_unit
  - entity: number
    name: Calibration probe 2
    category: config
    icon: "mdi:format-vertical-align-center"
    dps:
      - id: 113
        type: integer
        name: value
        range:
          min: -126
          max: 126
        mapping:
          - scale: 10
            # constraint: temp_unit
            # conditions:
            #   - dps_val: C
            #     range:
            #       min: -70
            #       max: 70
      - id: 19
        type: string
        name: temp_unit
  - entity: number
    name: Calibration probe 3
    category: config
    icon: "mdi:format-vertical-align-center"
    dps:
      - id: 114
        type: integer
        name: value
        range:
          min: -126
          max: 126
        mapping:
          - scale: 10
            # constraint: temp_unit
            # conditions:
            #   - dps_val: C
            #     range:
            #       min: -70
            #       max: 70
      - id: 19
        type: string
        name: temp_unit
  - entity: number
    name: Calibration probe 4
    category: config
    icon: "mdi:format-vertical-align-center"
    dps:
      - id: 115
        type: integer
        name: value
        range:
          min: -126
          max: 126
        mapping:
          - scale: 10
            # constraint: temp_unit
            # conditions:
            #   - dps_val: C
            #     range:
            #       min: -70
            #       max: 70
      - id: 19
        type: string
        name: temp_unit
```

I believe that the problem is that the pinouts reported from tuya platform are very different when using the api:

```
{
    "category": "wk",
    "functions": [
        {
            "code": "switch",
            "dp_id": 1,
            "type": "Boolean",
            "values": "{}"
        },
        {
            "code": "temp_unit_convert",
            "dp_id": 19,
            "type": "Enum",
            "values": "{\"range\":[\"c\",\"f\"]}"
        }
    ],
    "status": [
        {
            "code": "switch",
            "dp_id": 1,
            "type": "Boolean",
            "values": "{}"
        },
        {
            "code": "temp_unit_convert",
            "dp_id": 19,
            "type": "Enum",
            "values": "{\"range\":[\"c\",\"f\"]}"
        }
    ]
}
```

Would be happy to submit a pull request but unable to make it work, any help will be appreciated.
