### DISCUSSION TITLE
Breville AirRounder Plus - Climate Mappings

### DISCUSSION THREAD

**Discussion by beanaroo** [make-all/tuya-local#740] [Q&A] [answered]
I'm having a go at establishing a new device config for a [Breville AirRounder Plus](https://www.breville.com/nz/en/products/air-multifunction/bph708.html) air purifier.

The device data points have some quirks. There are two separate data points for heat and fan-only, each with three levels of intensity and an inactive state for when the other is active. These persist while the device is off.

Essentially, I would like to map three data points to two climate values:

![image](https://github.com/make-all/tuya-local/assets/1748909/7f864822-af55-4980-9c17-e93494fba58a)

Below is my progress so far, but unfortunately I get into a state of `unknown` when turning on the device, as well as an error:

### Logs:

```
WARNING (MainThread) [custom_components.tuya_local.climate] Unrecognised HVAC Mode of True ignored
```

### Browser Console:

```
code: "invalid_format"
​
message: "expected HVACMode or one of 'off', 'heat', 'cool', 'heat_cool', 'auto', 'dry', 'fan_only' for dictionary value @ data['hvac_mode']"
```

### Device Config

<details>

<summary><code>breville_airrounder_plus.yaml</code></summary>

```yaml
name: Breville AirRounder Plus
product:
  - id: h8fjsjf8tbhdm6aw
    name: "the Breville AirRounder Plus™"
primary_entity:
  entity: climate
  icon: "mdi:air-purifier"
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
        - dps_val: true
          constraint: _heat_mode
          conditions:
            - dps_val: "FanLow"
              icon: "mdi:fan"
              value: fan_only
            - dps_val: "FanMedium"
              icon: "mdi:fan"
              value: fan_only
            - dps_val: "FanHigh"
              icon: "mdi:fan"
              value: fan_only
            - dps_val: "HeatLow"
              icon: "mdi:fire"
              value: "heat"
            - dps_val: "HeatMedium"
              icon: "mdi:fire"
              value: heat
            - dps_val: "HeatHigh"
              icon: "mdi:fire"
              value: heat
    - id: 1
      name: fan_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
        - dps_val: true
          constraint: _heat_mode
          conditions:
            - dps_val: "FanLow"
              icon: "mdi:fan"
              value: low
            - dps_val: "FanMedium"
              icon: "mdi:fan"
              value: medium
            - dps_val: "FanHigh"
              icon: "mdi:fan"
              value: high
            - dps_val: "HeatLow"
              icon: "mdi:fire"
              value: low
            - dps_val: "HeatMedium"
              icon: "mdi:fire"
              value: medium
            - dps_val: "HeatHigh"
              icon: "mdi:fire"
              value: high
    - id: 2
      name: temperature
      type: integer
      range:
        min: 5
        max: 35
    - id: 3
      name: current_temperature
      type: integer
      readonly: true
    - id: 4
      name: _heat_mode
      type: string
      force: true
      hidden: true
      mapping:
        - dps_val: "heat_low"
          constraint: _cool_mode
          conditions:
            - dps_val: "NatureWind_Low"
              value: "FanLow"
            - dps_val: "NatureWind_High"
              value: "FanMedium"
            - dps_val: "CoolWind_0"
              value: "FanHigh"
        - dps_val: "heat_mid"
          value: "HeatLow"
        - dps_val: "heat_high"
          value: "HeatMedium"
        - dps_val: "heat_0"
          value: "HeatHigh"
    - id: 5
      name: _cool_mode
      type: string
      force: true
      hidden: true
```

</details>

**Comment by make-all** [comment, marked as answer]
Are those mappings correct?  It looks like they have been planned out to be _low. _mid, _high with _0 for off, but your table shows them all mixed up.

I think you can achieve this:
```yaml
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          constraint: heat_mode
          conditions:
            - dps_val: heat_low
              value: fan_only
            - dps_val: heat_mid
              value: heat
            - value: heat
    - id: 4
      name: heat_mode
      type: string
      mapping:
        - dps_val: heat_mid
          value: low
        - dps_val: heat_high
          value: medium
        - dps_val: heat_0
          value: high
    - id: 5
      name: fan_mode
      type: string
      mapping:
        - dps_val: NatureWind_Low
          value: low
        - dps_val: NatureWind_High
          value: medium
        - dps_val: CoolWind_0
          value: high
        - dps_val: SleepWind
          value_redirect: heat_mode
```

There is a limitation though - when switching into Heat mode, it will always switch to low.  That is because you need a value to set when switching modes.  If you prefer, you can switch the handling of fan and heat, to have this limitation for switching to fan_only instead.
