### DISCUSSION TITLE
Turning fan off when speed control set to off

### DISCUSSION THREAD

**Discussion by horse-pants** [make-all/tuya-local#822] [Q&A] [answered]
Hi team, 
I've been setting up my fans (a new device) in my HA and have got it mostly there, copying from the anko fan.

My last issue is that when I press the off button in the screenshot, it just sets the speed to the lowest setting but keeps going, and I can't find any obvious way to make that work in the yaml, does anyone know how to do this please?

![image](https://github.com/make-all/tuya-local/assets/79118862/d4f384ed-1198-44e5-8ea5-d19bc4affc8f)

Here's the yaml:
```yaml
name: Goldair Platinum Tower Fan with Wifi
products:
  - id: hgsp7xfajllkqujw
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: 1
          value: Normal
        - dps_val: 2
          value: Nature
        - dps_val: 3
          value: Sleep
        - dps_val: 4
          value: Child
    - id: 3
      type: integer
      name: speed
      range:
        min: 0
        max: 3
      mapping:
        - scale: 0.03
    - id: 4
      type: string
      name: oscillate
      mapping:
        - dps_val: "on"
          value: true
        - dps_val: "off"
          value: false
    - id: 6
      type: integer
      name: timer
secondary_entities:
  - entity: number
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 6
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 9
```
