### DISCUSSION TITLE
Issues with integrating power to get energy

### DISCUSSION THREAD

**Discussion by bilogic** [make-all/tuya-local#862] [Q&A]
Kind of a continuation from #833 

I did this and it looks correct to me, I could add it as a consumption entity and the numbers look correct
```
sensor:
  - platform: integration
    source: sensor.pj_1103_clamp_power_meter_power
    name: energy_spent
    unit_prefix: k
    round: 2
```

I managed to add another of those power monitoring switches (BSD29) into via Tuya Local and added the code below, but the numbers don't look right, it is a diagonal line going up all the way, what am I missing?
```
  - platform: integration
    source: sensor.energy_monitoring_smartplug_power
    name: energy_spent_pc
    unit_prefix: k
    round: 2
```
![image](https://github.com/make-all/tuya-local/assets/946010/2f1fbdc8-d27a-4ff1-8125-e5b5e3433d39)

![image](https://github.com/make-all/tuya-local/assets/946010/b267eb58-2405-4076-bf88-2915057222ec)
