### DISCUSSION TITLE
How does `direction_control` for vacuums work in HA?

### DISCUSSION THREAD

**Discussion by blakadder** [make-all/tuya-local#917] [Q&A] [answered]
> direction_control (optional, mapping of strings): a dp that is used for directional commands These are additional commands that are not part of status. They can be sent as general commands from HA.

How does this work in context of HA? I assume it's with the service vacuum.send_command but it's not clear how exactly

**Comment by make-all** [comment]
They are used through the `vacuum.send_command` service call with the mapped value given as `command`.

**Comment by blakadder** [comment, marked as answer]
For reference:

```yaml
service: vacuum.send_command
data: 
  entity_id: vacuum.m9_robot_vacuum
  command: forward
```
UI example:
![image](https://github.com/make-all/tuya-local/assets/5904370/77225e78-1e96-45e9-a927-71c3b47dc253)
