### DISCUSSION TITLE
Scales & steps - how to control?

### DISCUSSION THREAD

**Discussion by lageorgem** [make-all/tuya-local#949] [Q&A] [answered]
Hello,

I am encountering some issues while using the step and scale options for a config I am working on.

The brighness level in home assistant returns a value between 0 and 255, but I need these scaled to 0-100.
I have used the following config, taken from examples from the codebase, and it still seems not to work.
```yaml
    - id: 104
      name: brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 2
          scale: 0.392
        - constraint: 101
```

This is met with an error:
```
2023-07-30 18:33:46.169 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547099641616] brightness (171) must be between 0 and 100
```

**Comment by make-all** [comment]
~~The scale of 0.392 is for 0-1000.  You need 3.92.~~ 0.392 should be the correct scale. 100 / 0.392 = 255.  However you have an additional default mapping `- constraint: 101` which may be shadowing the mapping of scale and step.  I'm not sure what the intention is with that, but it is incorrect as-is, so should be removed.

**Reply by lageorgem** [reply]
No scale value seems to change the behaviour. The 100% reported by the device is translated into 39% (100/255), and setting the brightness to the max gives the same error always.

```
2023-07-31 10:49:15.489 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547238845136] brightness (255) must be between 0 and 100
```

**Reply by lageorgem** [reply]
My device has 3 brightness controls, and the relevant one should be chosen according to the video mode

```yaml
primary_entity:
  entity: light
  name: Backlight
  dps:
    - id: 102
      type: boolean
      name: switch
    - id: 104
      name: brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392156862745
        - constraint: 101
          conditions:
            - dps_val: ambi_mode
              value_redirect: scene_brightness
            - dps_val: color_mode
              value_redirect: color_brightness
    - id: 114
      hidden: true
      name: scene_brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392156862745
    - id: 112
      hidden: true
      name: color_brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392156862745
    - id: 111
      name: rgbhsv
      type: hex
      format:
        - name: r
          bytes: 1
        - name: g
          bytes: 1
        - name: b
          bytes: 1
secondary_entities:
  - entity: select
    name: Video Mode select
    dps:
      - id: 101
        name: option
        type: string
        mapping:
          - dps_val: video_mode
            value: Video
          - dps_val: music_mode
            value: Music
          - dps_val: film_mode
            value: Wide film
          - dps_val: color_mode
            value: Static color
          - dps_val: ambi_mode
            value: Ambient scene
```

It behaves correctly, except the scaling.

**Comment by make-all** [comment]
Try changing the `- id: 104` block to the following:

```
    - id: 104
      name: brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392156862745
          constraint: video_mode
          conditions:
            - dps_val: ambi_mode
              value_redirect: scene_brightness
            - dps_val: color_mode
              value_redirect: color_brightness
    - id: 101
      name: video_mode
      type: string
      hidden: true
```

**Reply by make-all** [reply]
And you really don't need so many decimal places on the scale, it will be rounded in the end.

**Reply by lageorgem** [reply]
Great, it kinda works. I understand that I need a named dps in the same entity for it to work?
What doesn't work is the default case. there are 3 more modes in the video_mode that I want to go to 104, and while that does seem to be the case, it seems that the scaling didn't apply to that one as well.

```yaml
entity: light
  name: Backlight
  dps:
    - id: 102
      type: boolean
      name: switch
    - id: 104
      name: brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392
        - constraint: video_mode
          conditions:
            - dps_val: ambi_mode
              value_redirect: scene_brightness
            - dps_val: color_mode
              value_redirect: color_brightness
    - id: 114
      hidden: true
      name: scene_brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392
    - id: 112
      hidden: true
      name: color_brightness
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - step: 1
          scale: 0.392
    - id: 111
      name: rgbhsv
      type: hex
      format:
        - name: r
          bytes: 1
        - name: g
          bytes: 1
        - name: b
          bytes: 1
    - id: 101
      name: video_mode
      type: string
      hidden: true
```
