### DISCUSSION TITLE
Cant turn on AC, but everything else works

### DISCUSSION THREAD

**Discussion by jonpetersathan** [make-all/tuya-local#955] [Q&A]
Hi there,

I trying to get by AC working using tuya-local. I created a new device configuration and after some trial and error, I got everything working, except turning the AC on.

Config file is here: https://github.com/jonpetersathan/tuya-local/blob/main/custom_components/tuya_local/devices/woods_cortina_airconditioner.yaml

When changing the mode in HA it doesn't turn on the AC, despite having "dps_val: true" (line 15) in the mapping. When creating an additional switch like so:
```
 - entity: switch
    name: Test
    icon: "mdi:power-sleep"
    dps:
      - id: 1
        type: boolean
        name: switch
```
I can turn on the AC by toggling this switch, but this seems like a workaround and I couldn't find any other AC config that would do this. Am I missing something?

Thanks!
