### ISSUE TITLE
Request to support another thermostat

### ISSUE THREAD

**Issue by Uaeguy** [make-all/tuya-local#100]
Hello, Thanks again for supporting these devices, I came with new Thermostat (I am looking for the perfect one for my home).

While trying to add the thermostat it shows as switch only.

The thermostat is from a company called owon [here is a link of the product](https://www.owon-smart.com/wi-fi-touchscreen-thermostat-pct513-2-product/)

The thermostat is very nice and it looks like it is a good quality. It have touch screen and not only temp sensor but also humidity sensor.

The below is what I can read from the device

```
{
  "result": {
    "active_time": 1640294954,
    "category": "wk",
    "category_name": "Thermostat",
    "create_time": 1640294954,
    "gateway_id": "",
    "icon": "smart/icon/ay1515026431018saCFs/0653ce64488da6986d1572a86924d30f.png",
    "id": "xxxxxxx",
    "ip": "xxxx",
    "lat": "xxx",
    "local_key": "xxxxxxx",
    "lon": "xxxx",
    "model": "513-TY",
    "name": "New Thermostat",
    "online": true,
    "owner_id": "xxxx",
    "product_id": "rsujjtinksnzcezy",
    "product_name": "Thermostat",
    "sub": false,
    "time_zone": "+04:00",
    "update_time": 1640295006,
    "uuid": "xxxxx"
  },
  "success": true,
  "t": 1640297197338
}
```

as for the DPS

{'dps': 
{
'2': 'cool', # working mode range: 'cool' or 'off' or 'heat' or 'emergencyheat' or 'auto' (my use case only cool)
'16': 2150, # set temp in C (21.50)
'17': 71,  # set temp in F
'23': 'c',  # the temp unit c or f
'24': 2950,  # current temp of the senor in C (29.50)
'29': 85,  # current temp of the senor in F
'34': 52, # humidity
'45': 0, 
'107': '0',  # mode of connected device ( 0 cool only system either 1 stage or 2 stage no heating here my use case is only cooling)
'108': 2150,  # set temp in C (I guess for display)
'109': 1650, # something to do with vacation mode (I didn't understand it) probably it is the heat limit 
'110': 71, # sensor temp in F
'111': 62,  
'115': 'auto',  # fan mode (auto / on / cycle)
'116': '1', # something to do with vacation mode (I didn't understand it)
'119': True, # true = enable schedule / false = disable schedule 
'120': 'permhold', # type of operation "only possible when schedule is enabled dps 119 is true" (permhold=Permanent hold, temphold = temporary hold, followschedule= follow schedule) 
'123': 25, # minimum Fan run time (min/h)
'129': 'coolfanon' #coolfanon = Cool and Fan is on / alloff = cooling is off and fan is off / fanon = cooling is off and fan is on ( this dps is for status cannot be changed via thermostat)
}}

Thanks for the support as always cheers!

**Comment by make-all** [comment]
I think something like below should work

```yaml
name: PCT513 Themostat
products:
  - id: rsujjtinksnzcezy
primary_entity:
  entity: climate
  dps:
    - id: 2
      type: string
      name: hvac_mode
      mapping:
        - dps_val: "off"
          value: "off"
        - dps_val: cool
          value: cool
        - dps_val: heat
          value: heat
        - dps_val: auto
          value: heat_cool
        - dps_val: emergencyheat
          value: heat
    - id: 16
      type: integer
      name: temperature
      range:
        min: 0
        max: 500
      mapping:
        - scale: 100
          step: 50
          constraint: temperature_unit
          conditions:
            - dps_val: f
              value_redirect: temp_f
              scale: 1
              step: 1
              range:
                min: 32
                max: 122
    - id: 17
      type: integer
      name: temp_f
      hidden: true
      range:
        min: 32
        max: 122
    - id: 23
      type: string
      name: temperature_unit
      mapping:
        - dps_val: c
          value: C
        - dps_val: f
          value: F
    - id: 24
      type: integer
      name: current_temperature
      mapping:
        - scale: 100
          constraint: temperature_unit
          conditions:
            - dps_val: f
              scale: 1
              value_redirect: curtemp_f
    - id: 29
      type: integer
      name: curtemp_f
    - id: 34
      type: integer
      name: current_humidity
    - id: 45
      type: integer
      name: unknown_45
    - id: 107
      type: string
      name: installation
    - id: 108
      type: integer
      name: temp_c
      mapping:
        - scale: 100
    - id: 109
      type: integer
      name: unknown_109
    - id: 110
      type: integer
      name: temp_f2
    - id: 111
      type: integer
      name: unknown_111
    - id: 115
      type: string
      name: fan_mode
      mapping:
        - dps_val: auto
          value: auto
        - dps_val: on
          value: on
        - dps_val: cycle
          value: cycle
    - id: 116
      type: string
      name: unknown_116
    - id: 119
      type: boolean
      name: scheduling
      hidden: true
      mapping:
        - dps_val: false
          value: Manual
    - id: 120
      type: string
      name: preset_mode
      mapping:
        - dps_val: followschedule
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
              value: Manual
            - dps_val: true
              value: Follow Schedule
        - dps_val: temphold
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
            - dps_val: true
              value: Temporary Hold
        - dps_val: permhold
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
            - dps_val: true
              value: Permanent Hold
        - dps_val: followvacation
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
            - dps_val: true
              value: Vacation
    - id: 129
      type: string
      name: hvac_action
      mapping:
        - dps_val: coolfanon
          value: cooling
        - dps_val: alloff
          value: idle
        - dps_val: fanon
          value: fan
        - dps_val: heatfanon
          value: heating
secondary_entities:
  - entity: number
    name: Fan Runtime
    unit: min
    dps:
      - id: 123
        type: integer
        name: value
        range:
          min: 0
          max: 60
```

**Comment by Uaeguy** [comment]
I will try it, do I need to update something in the integration?

**Comment by Uaeguy** [comment]
I have modified the yaml now it is operating correctly. 

I have removed vacation mode since it have different dps value (116) and when activating the vacation mode it sends data which I tired to understand but failed. 

When activating vacation mode `dps 116` changes from 1 to 2 and `dps 121 `sends data looks like this `ARYBARI1FgECEjUGQAu4` this data is translated to the following photo 
![IMG_8451](https://user-images.githubusercontent.com/36298972/147853499-b487b084-86f7-443e-99c7-f44b2a444d25.jpg)

And when I delete the schedule it sends to `dps 121` the following data `AA==` and also it changes the` dps 116 `to 1

I'm happy that the thermostat is now functional through home assistant and I don't really need the vacation mode, I have added the information just if you want to have a look.

Thanks

modified yaml: 

```yaml
name: PCT513 WiFi Touchscreen Thermostat
products:
  - id: rsujjtinksnzcezy
primary_entity:
  entity: climate
  dps:
    - id: 2
      type: string
      name: hvac_mode
      mapping:
        - dps_val: "off"
          value: "off"
        - dps_val: cool
          value: cool
        - dps_val: heat
          value: heat
        - dps_val: auto
          value: heat_cool
        - dps_val: emergencyheat
          value: heat
    - id: 16
      type: integer
      name: temperature
      range:
        min: 1500
        max: 4500
      mapping:
        - scale: 100
          step: 50
          constraint: temperature_unit
          conditions:
            - dps_val: f
              value_redirect: temp_f
              scale: 1
              step: 1
              range:
                min: 32
                max: 122
    - id: 17
      type: integer
      name: temp_f
      hidden: true
      range:
        min: 32
        max: 122
    - id: 23
      type: string
      name: temperature_unit
      mapping:
        - dps_val: c
          value: C
        - dps_val: f
          value: F
    - id: 24
      type: integer
      name: current_temperature
      mapping:
        - scale: 100
          constraint: temperature_unit
          conditions:
            - dps_val: f
              scale: 1
              value_redirect: curtemp_f
    - id: 29
      type: integer
      name: curtemp_f
    - id: 34
      type: integer
      name: current_humidity
    - id: 45
      type: integer
      name: unknown_45
    - id: 107
      type: string
      name: installation
    - id: 108
      type: integer
      name: temp_c
      mapping:
        - scale: 100
    - id: 109
      type: integer
      name: unknown_109
    - id: 110
      type: integer
      name: temp_f2
    - id: 111
      type: integer
      name: unknown_111
    - id: 115
      type: string
      name: fan_mode
      mapping:
        - dps_val: "auto"
          value: "auto"
        - dps_val: "on"
          value: "on"
        - dps_val: "cycle"
          value: "cycle"
    - id: 116
      type: string
      name: unknown_116
    - id: 119
      type: boolean
      name: scheduling
      hidden: true
      mapping:
        - dps_val: false
          value: Manual Permanent Hold
    - id: 120
      type: string
      name: preset_mode
      mapping:
        - dps_val: followschedule
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
              value: Manual Permanent Hold
            - dps_val: true
              value: Follow Schedule
        - dps_val: temphold
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
              value: Manual Permanent Hold
            - dps_val: true
              value: Temporary Hold
        - dps_val: permhold
          value: Permanent Hold
    - id: 129
      type: string
      name: hvac_action
      mapping:
        - dps_val: coolfanon
          value: cooling
        - dps_val: alloff
          value: idle
        - dps_val: fanon
          value: fan
        - dps_val: heatfanon
          value: heating
secondary_entities:
  - entity: number
    name: Fan Runtime
    unit: min
    dps:
      - id: 123
        type: integer
        name: value
        range:
          min: 0
          max: 55
        mapping:
        - step: 5
```
