### ISSUE TITLE
Request support for Kogan Smarterhome White Noise Machine (Sleep Aid) KAWHTNOSLPA

### ISSUE THREAD

**Issue by muneeb1990** [make-all/tuya-local#1003]
I've created the following YAML config for Kogan Smarterhome White Noise Machine (Model KAWHTNOSLPA). [Link](https://help.kogan.com/hc/en-us/articles/360054131214-Kogan-SmarterHome-White-Noise-Sleep-Aid-Device-KAWHTNOSLPA-Manuals-and-Support) to the device. 

```
name: Sleep Aid
products:
 - id: d9tnlvjvlgwqr9ov
 - name: Sleep Aid
primary_entity:
  entity: switch
  dps:
    - id: 105
      name: switch
      type: boolean
secondary_entities:
    - entity: light
      name: LED Light
      dps:
      - id: 104
        name: brightness
        type: integer
        range:
          min: 0
          max: 255
    - entity: select
      name: Sound Level
      category: config
      dps:
       - id: 101
         name: option
         type: string
         mapping:
           - dps_val: "low"
             value: "Low"
           - dps_val: "high"
             value: "High"
```

```
        "name": "Sleep Aid",
        "category": "bzyd",
        "product_name": "Sleep Aid",
        "product_id": "d9tnlvjvlgwqr9ov",
        "biz_type": 0,
        "model": "KAWHTNOSLPA",
        "sub": false,
        "icon": "https://images.tuyaus.com/smart/icon/ay15253387844269Sg99/a1ca49b8c0ea8bec5622e7b355169716.png",
        "version": "3.3"
```
