### ISSUE TITLE
Support for YP Pet feeder ALIEXPRESS

### ISSUE THREAD

**Issue by mhackdo18** [make-all/tuya-local#1011]
https://www.aliexpress.com/item/1005005626574888.html?spm=a2g0o.productlist.main.37.43537fd8WiM4Qx&algo_pvid=8db99145-5bc8-4816-a271-53427ae681df&algo_exp_id=8db99145-5bc8-4816-a271-53427ae681df-18&pdp_npi=4%40dis%21QAR%21261.09%21182.76%21%21%21520.00%21%21%40210323f716925357419398536e30d0%2112000033796219984%21sea%21QA%210%21A&curPageLogUid=ZoQYaDlfm0Zk

# Here is MY YAML

```
name: YP feeder
products:
  - id: wfnmgiqqch80sg1w
    name: PAF-40PCS-WBR3
primary_entity:
  entity: number
  icon: "mdi:paw"
  name: Manual feed
  dps:
    - id: 3
      name: value
      type: integer
      range:
        min: 1
        max: 40
    - id: 1
      name: meal_plan
      type: string
    - id: 14
      name: fault
      type: boolean
secondary_entities:
  - entity: sensor
    icon: "mdi:paw"
    name: Feed report
    category: diagnostic
    dps:
      - id: 15
        name: sensor
        type: integer
    type: integer
  - entity: button
    class: restart
    name: Factory reset
    category: config
    dps:
      - id: 9
        type: boolean
        name: button

```

# Information about DPS mappings

```

  "result": {
    "model": "{\"modelId\":\"000002cvm6\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"meal_plan\",\"description\":\"同步到设备端本地，即使设备离线，仍能正常喂食出粮，喂食计划最多支持10个\\nraw格式约定：按照“周期+时间+喂食份数+开关”来实现本地定时，具体如下\\n1，前7个比特位代表周一到周日，二进制转十六进制，占用一个字节，0代表未设置，1代表设置，如0000001，表示周日生效，转换为16进制就是01\\n2，时间按照小时分钟格式，占用2个字节，分钟和小时，十进制转16进制，如18：50，转为16进制为1232\\n3，喂食份数，占用1个字节，十进制转16进制，如12，转为16进制为0c\\n4，开关，占用1个字节，00表示关闭，01表示开启\\n上述举例，对于APP端时间下发的结果为0112320c01，表示周日，18：50，喂食12份，开启。\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"96\"},\"name\":\"喂食计划\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"manual_feed\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-icon-test13\"},\"name\":\"手动喂食\",\"typeSpec\":{\"max\":40,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":4,\"accessMode\":\"ro\",\"code\":\"feed_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\"},\"name\":\"喂食状态\",\"typeSpec\":{\"range\":[\"standby\",\"feeding\",\"done\"],\"type\":\"enum\",\"typeDefaultValue\":\"standby\"}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"factory_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_nav_mode\",\"attribute\":\"96\"},\"name\":\"恢复出厂\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_notice\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"pet_food_jam\",\"pet_food_shortages\",\"pet_food_run_out\",\"desiccant_exhausted\",\"battery_low\"],\"maxlen\":5,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"feed_report\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\",\"id\":15,\"trigger\":\"direct\"},\"name\":\"喂食结果上报\",\"typeSpec\":{\"max\":40,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}}]}]}"
  },
```

# Product ID

```
 "active_time": 1691949504,
      "category": "cwwsq",
      "create_time": 1691949504,
      "custom_name": "",
      "icon": "smart/icon/bay1600498541726iZPc/a2a3405a8c44fc170c9003ed553349a1.png",
      "id": "bfef13ae7486fd689fskvv",
      "ip": "",
      "is_online": true,
      "lat": "",
      "local_key": "",
      "lon": "51.5395",
      "model": "YP-1904WIFI-40",
      "name": "YP feeder",
      "product_id": "wfnmgiqqch80sg1w",
      "product_name": "PAF-40PCS-WBR3",
      "sub": false,
      "time_zone": "",
      "update_time": 1692501217,
      "uuid": ""
```

# Information about how the device functions

```
{
  "result": {
    "properties": [
      {
        "code": "meal_plan",
        "custom_name": "",
        "dp_id": 1,
        "time": 1692501241689,
        "value": "fwcUDAF/DQACAH8THgwB"
      },
      {
        "code": "manual_feed",
        "custom_name": "",
        "dp_id": 3,
        "time": 1692210273928,
        "value": 1
      },
      {
        "code": "feed_state",
        "custom_name": "",
        "dp_id": 4,
        "time": 1692439210666,
        "value": "standby"
      },
      {
        "code": "factory_reset",
        "custom_name": "",
        "dp_id": 9,
        "time": 1691949504616,
        "value": false
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 14,
        "time": 1692439210647,
        "value": 0
      },
      {
        "code": "feed_report",
        "custom_name": "",
        "dp_id": 15,
        "time": 1692505210972,
        "value": 12
      }
    ]
  },

}
```
