### ISSUE TITLE
Request support for Maxcio W-DE004

### ISSUE THREAD

**Issue by antonio1475** [make-all/tuya-local#1036]
# Proposed configuration
It's working with this below. Based on the other switches like the Mirabella. The only difference is that Maxcio's Timer DP is 2 instead of 7 for the Mirabella.

```
name: Switch with timer
products:
  - id: PGEkBctAbtzKOZng
    name: Maxcio W-DE004
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 2
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"00000008iu\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_on\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"7\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"\",\"extensions\":{\"passive\":true},\"name\":\"倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"秒\"}}]}]}"
  },
  "success": true,
  "t": 1693168856319,
  "tid": "05b80b69451a11eeb3f09e6a0abc163a"
}
```

# Product ID

```
{
  "result": [
    {
      "active_time": 1670671006,
      "category": "cz",
      "create_time": 1519470195,
      "custom_name": "Calefactor Habitación",
      "icon": "smart/icon/socket_new2.png",
      "id": "03200296dc4f22296d95",
      "ip": "xxxxx",
      "is_online": true,
      "lat": "41.4700",
      "local_key": "xxxxx",
      "lon": "2.0900",
      "model": "X3 模组",
      "name": "Smart Plug 6",
      "product_id": "PGEkBctAbtzKOZng",
      "product_name": "普通单灯智能插座-欧规",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1690668233,
      "uuid": "03200296dc4f22296d95"
    }
  ],
  "success": true,
  "t": 1693169586970,
  "tid": "b9346440451b11ee8298eeefa7b3467e"
}
```
