### ISSUE TITLE
Request to support thermostat Hysen HY08WE-2 WIFI- black

### ISSUE THREAD

**Issue by mpetcuRO** [make-all/tuya-local#104]
Hello, I have the following thermostat for Floor heating - [link](http://www.cn-hysen.com/productinfo/465729.html)
I have followed the info on how to configure it with this integration and is accepting it as an "anderson_gsh_heater" no other similar device in the list.
![image](https://user-images.githubusercontent.com/73108927/147945288-ab149f0d-7aa5-4ab0-8aae-debef0b784b8.png)
After that it shows in HA but the update is slow and the temperatures is adding one "0"
Actual temp, current temp is 19, set temp is 9
![image](https://user-images.githubusercontent.com/73108927/147945506-f9e13b21-6ad1-4c83-b83a-917811c48ad8.png)
in Lovelace the thermostat entity is slow to react and showing like this.
![image](https://user-images.githubusercontent.com/73108927/147945847-bdd2b903-3f1d-45fd-9914-c3f732548f57.png)
What do I need to get from the Tuya developer account to continue troubleshooting.

**Comment by mpetcuRO** [comment]
I have found the following in the Tuya platform under "Get the specifications and properties of the device"
`{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"℃\",\"min\":5,\"max\":1220,\"scale\":1,\"step\":1}",
        "name": "温度设置",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":1220,\"scale\":1,\"step\":1}"
      },
      {
        "code": "child_lock",
        "desc": "{}",
        "name": "童锁",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "name": "温度设置",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":5,\"max\":1220,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_current",
        "name": "当前温度",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":1580,\"scale\":1,\"step\":1}"
      },
      {
        "code": "child_lock",
        "name": "童锁",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1641226734040
}`

**Comment by make-all** [comment]
Also required will be the full output from the device. It is printed in the HA log as a warning message when you add the device if it is not an exact match.  Otherwise, you need to set the log level to debug to see it every time the device is polled, or use some other method like tuyaapi/cli or tinytuya to query the device.

**Comment by mpetcuRO** [comment]
All I can find in the log after reading the Thermostat
Warning 1
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:73
Integration: Tuya Local (documentation, issues)
First occurred: 8:55:27 AM (1 occurrences)
Last logged: 8:55:27 AM

Device matches andersson_gsh_heater with quality of 21%. DPS: {'1': True, '2': 50, '3': 170, '4': 'Manual', '6': False, '12': 0, '101': False, '102': False, '103': 170, '104': 4, '105': 15, '106': True, '107': True, '108': True, '109': -10, '110': 10, '111': 2, '112': 35, '113': 5, '114': 30, '115': 5, '116': 'all', '117': 'keep', '118': '2days', 'updated_at': 1641279321.0747674}

Warning 2
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:76
Integration: Tuya Local (documentation, issues)
First occurred: 8:55:27 AM (1 occurrences)
Last logged: 8:55:27 AM

Report this to https://github.com/make-all/tuya-local/issues/

**Comment by make-all** [comment]
There isn't a lot of datapoints defined in the Tuya developer site, most of the settings may not be available via cloud.  But that limits what I can decipher from the info the device is returning.  I assume the external temperature is the other one reading 17 (same as the internal temperature reading), as nothing else seems close.
If you save the following as `hysen_hy08we2_thermostat.yaml` in `custom_components/tuya_local/devices/`, it may help move things forward.  But I'd be interested in figuring out more of these settings before commiting this.

```
name: Hysen HY08WE-2 Thermostat
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: integer
      name: temperature
      range:
        min: 5
        max: 1220
      mapping:
        - scale: 10
    - id: 3
      type: integer
      name: current_temperature
      mapping:
        - scale: 10
    - id: 4
      type: string
      name: unknown_4
    - id: 12
      type: integer
      name: unknown_12
    - id: 101
      type: boolean
      name: unknown_101
    - id: 102
      type: boolean
      name: unknown_102
    - id: 104
      type: integer
      name: unknown_104
    - id: 105
      type: integer
      name: unknown_105
    - id: 106
      type: boolean
      name: unknown_106
    - id: 107
      type: boolean
      name: unknown_107
    - id: 108
      type: boolean
      name: unknown_108
    - id: 109
      type: integer
      name: unknown_109
    - id: 110
      type: integer
      name: unknown_110
    - id: 111
      type: integer
      name: unknown_111
    - id: 112
      type: integer
      name: unknown_112
    - id: 113
      type: integer
      name: unknown_113
    - id: 114
      type: integer
      name: unknown_114
    - id: 115
      type: integer
      name: unknown_115
    - id: 116
      type: string
      name: unknown_116
    - id: 117
      type: string
      name: unknown_117
    - id: 118
      type: string
      name: unknown_118
secondary_entities:
  - entity: lock
    name: Child Lock
    category: config
    dps:
      - id: 6
        type: boolean
        name: lock
        mapping:
          - dps_val: True
            icon: "mdi:hand-back-right-off"
          - dps_val: False
            icon: "mdi:hand-back-right"
  - entity: sensor
    name: External Temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: unknown_103
```
