### ISSUE TITLE
Tuya Alarm PG103 PG107 - gautone_pg103_alarm - Alarm Trigger is not detected

### ISSUE THREAD

**Issue by sityware** [make-all/tuya-local#1051]
Hi,

I've been setting up my alarm PG107, it seems to work like PG103. I can arm and disarm no problem.

I'm having trouble getting Home Assistant to detect the Alarm when triggered.

I think it is related to the dps id 32 - Master State.
In the Tuya IOT Device Logs, when the alarm triggers it seems to set Master state to Alarm.
Is there anyway to receive this event? There does appear to be a master_state entry in the yaml.

From the Tuya IOT master_state is either normal or alarm ( details on all instructions at the bottom )
```
      {
        "code": "master_state",
        "desc": "{\"range\":[\"normal\",\"alarm\"]}",
        "name": "主机状态",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
```

Tuya IOT Log when alarm triggered.

2023-09-01 15:46:59 | Report | Master state | Alarm
2023-09-01 15:47:00 | Report | Device Mode | Disarmed

The gautone_pg103_alarm.yaml does have master_state specified.

```
  dps:
    - id: 1
      type: string
      name: alarm_state
      mapping:
        - dps_val: disarmed
          value: disarmed
        - dps_val: arm
          value: armed_away
        - dps_val: home
          value: armed_home
        - dps_val: sos
          value: triggered
    - id: 32
      type: string
      name: master_state
      optional: true

```

**To Reproduce**
Add PG103 / PG107 Alarm to Tuya-local.
Trigger an alarm and no notifications will trigger.

&nbsp;&nbsp;
This is the instruction set of the device from Tuya IOT
&nbsp;&nbsp;

```
{
  "result": {
    "category": "mal",
    "functions": [
      {
        "code": "master_mode",
        "desc": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}",
        "name": "主机模式",
        "type": "Enum",
        "values": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}"
      },
      {
        "code": "delay_set",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "延时设置",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_time",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "报警时长",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_alarm_sound",
        "desc": "{}",
        "name": "报警声开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_light",
        "desc": "{}",
        "name": "报警灯开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_mode_sound",
        "desc": "{}",
        "name": "工作模式提示音开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_sound",
        "desc": "{}",
        "name": "键盘按键音开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_light",
        "desc": "{}",
        "name": "键盘背景灯开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "muffling",
        "desc": "{}",
        "name": "消音",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_propel",
        "desc": "{}",
        "name": "告警推送",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_delay_time",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}",
        "name": "告警后延时报警",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "master_state",
        "desc": "{\"range\":[\"normal\",\"alarm\"]}",
        "name": "主机状态",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "desc": "{}",
        "name": "恢复出厂设置",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sub_class",
        "desc": "{\"range\":[\"remote_controller\",\"detector\"]}",
        "name": "子设备品类",
        "type": "Enum",
        "values": "{\"range\":[\"remote_controller\",\"detector\"]}"
      },
      {
        "code": "sub_admin",
        "desc": "{}",
        "name": "子设备管理",
        "type": "Raw",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "master_mode",
        "name": "主机模式",
        "type": "Enum",
        "values": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}"
      },
      {
        "code": "delay_set",
        "name": "延时设置",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_time",
        "name": "报警时长",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_alarm_sound",
        "name": "报警声开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_light",
        "name": "报警灯开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_mode_sound",
        "name": "工作模式提示音开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_sound",
        "name": "键盘按键音开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_light",
        "name": "键盘背景灯开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "muffling",
        "name": "消音",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_msg",
        "name": "告警信息",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "switch_alarm_propel",
        "name": "告警推送",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_delay_time",
        "name": "告警后延时报警",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "master_state",
        "name": "主机状态",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "name": "恢复出厂设置",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sub_class",
        "name": "子设备品类",
        "type": "Enum",
        "values": "{\"range\":[\"remote_controller\",\"detector\"]}"
      },
      {
        "code": "sub_admin",
        "name": "子设备管理",
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "sub_state",
        "name": "子设备状态",
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\",\"fault\",\"others\"]}"
      }
    ]
  },
```

**Comment by sityware** [comment]
I seem to have got it working on my setup, Not sure if this is the best way?
Now I get Alarm Notifications from Home Assistant without any Tuya cloud relation.

SSH into Home Assistant
I've added a new device yaml - Should work on all the PG devices. I tested on PG107
nano /root/config/custom_components/tuya_local/devices/gautone_pg107_alarm.yaml
copy the below, paste and save the file.

Difference is the dps id 1 - master_state now has mappings

```
name: Alarm security system
products:
  - id: bf63dd13b9763f85de4csla
    name: GauTone PG-107
  - id: e778grhre1935435
    name: "PG103/PG105/PG106/PG107/PG109"
primary_entity:
  entity: alarm_control_panel
  dps:
    - id: 1
      type: string
      name: alarm_state
      mapping:
        - dps_val: disarmed
          value: disarmed
        - dps_val: arm
          value: armed_away
        - dps_val: home
          value: armed_home
        - dps_val: sos
          value: triggered
    - id: 32
      type: string
      name: master_state
      mapping:
        - dps_val: normal
          value: disarmed
        - dps_val: alarm
          value: triggered
    - id: 36
      type: string
      name: sub_class
      optional: true
    - id: 101
      type: string
      name: power_state
secondary_entities:
  - entity: number
    name: Exit delay
    category: config
    icon: "mdi:timer"
    dps:
      - id: 2
        type: integer
        name: value
        unit: s
        range:
          min: 0
          max: 1000
  - entity: number
    name: Entry delay
    category: config
    icon: "mdi:timer"
    dps:
      - id: 28
        type: integer
        name: value
        unit: s
        range:
          min: 0
          max: 1000
  - entity: number
    name: Siren duration
    category: config
    icon: "mdi:timer"
    dps:
      - id: 3
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 1000
  - entity: switch
    name: Alarm sound
    category: config
    dps:
      - id: 6
        type: boolean
        name: switch
  - entity: switch
    name: Backlight
    category: config
    dps:
      - id: 13
        type: boolean
        name: switch
  - entity: switch
    name: Arm beep
    category: config
    dps:
      - id: 4
        type: boolean
        name: switch
  - entity: switch
    name: Mode notification
    category: config
    dps:
      - id: 10
        type: boolean
        name: switch
  - entity: switch
    name: Alarm notification
    category: config
    dps:
      - id: 27
        type: boolean
        name: switch
```
&nbsp;&nbsp;
Add your Alarm device name as **myalarm** . Important for the configs below to match, rename myalarm if it is different.
Select the newly created **gautone_pg107_alarm** device when prompted.

in **/config/automations.yaml** add the below with a unique ID

```
- id: '1693562259306'
  alias: PG103_PG107_Sensor
  description: ''
  trigger:
  - platform: state
    entity_id:
    - alarm_control_panel.myalarm
    attribute: master_state
    to: triggered
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.notify
    data:
      message: Alarm Triggered
      title: Alarm Triggered
  mode: restart

```

Then add this in  **/config/configuration.yaml**

```
template:
  - sensor:
      - name: "Alarm Status"
        state: "{{ state_attr('alarm_control_panel.myalarm', 'master_state') }}"
```
&nbsp;&nbsp;
You should now have a Sensor for the Alarm. Which changes to triggered and sends a notification out to Mobile devices when signed in with the Home Assistance application.

![image](https://github.com/make-all/tuya-local/assets/31103915/92800621-942e-4aae-a348-a21d7988489d)
