### ISSUE TITLE
New Device Request - ecostrad Heater Panel

### ISSUE THREAD

**Issue by Paul-C-S** [make-all/tuya-local#108]
Hi,

Firstly - great work with this.  Thanks!

Are you able to help me add support for an Accent IQ ecostrad heater panel? --> https://www.electricradiatorsdirect.co.uk/ecostrad-accent-iq-wifi-controlled-infrared-ceiling-panels/

tuya-cli get --id ???????????? --key ??????? --ip ?.?.?.? --protocol-version 3.3 --full
{
  devId: '040005122462ab3e1dd7',
  dps: { '1': true, '2': 190, '3': 100, '10': '0', '101': true }
}

Which seems easy!
1 = on / off
2 = desired temperature (1 decimal point)
3 = current temperature (1 decimal point)

Attempt at simple YAML file (ecostrad_heater.yaml) - nothing complicated like nice icons or scaling to start with:

name: Ecostrad Heater Panel
legacy_type: ecostrad_heater
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: integer
      name: temp_set
      range:
        min: 0
        max: 450
    - id: 3
      type: integer
      name: temp_current
      readonly: true
      range:
        min: -50
        max: 500

Result:

ecostrad_heater is the top option when I try to add the Tuya Local object, but it only adds a single entity (climate) and none of the IDs identified.

There must be something very simple I'm doing wrong!

Any help would be appreciated :)

**Comment by make-all** [comment]
None of the ids are identified, because they need specific names to match the climate entity functions.

````
name: Ecostrad Heater Panel
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: true
          value: heat
        - dps_val: false
           value: "off"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 0
        max: 450
      mapping:
        - scale: 10
    - id: 3
      type: integer
      name: current_temperature
      readonly: true
      mapping:
        - scale: 10
````
You may also need a `step: 5` in the mapping for temperature, as usually temperatures can only be adjusted by 0.5 degree steps in heaters that show 0.1 degree precision.
