### ISSUE TITLE
New Device (fully working): Electriq CD12PW-V2 Dehumidifier

### ISSUE THREAD

**Issue by Gekko47** [make-all/tuya-local#109]
Hi,

Thank you very much for the work you have done creating this repository.

I have amended the previous code you had for the CD12PW-V1; changed the id's where required, added the sleep mode switch and full water tank sensor.

This works fully for me, only glitch I find is that the device takes a while to allow a second input once you have already sent a change, is there a way to delay the next sent change so that the device actually receives it?

```
name: "Electriq CD12PW-V2 Dehumidifier"
primary_entity:
  entity: humidifier
  class: dehumidifier
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: false
          icon: "mdi:air-humidifier-off"
          icon_priority: 1
        - dps_val: true
          icon: "mdi:air-humidifier"
          icon_priority: 3
    - id: 2
      type: integer
      name: humidity
      range:
        min: 35
        max: 80
      mapping:
        - step: 5
    - id: 5
      name: mode
      type: string
      mapping:
        - dps_val: "Smart"
          value: "Smart"
        - dps_val: "Air_purifier"
          value: "Air Purifier"
          icon: "mdi:air-purifier"
    - id: 6
      type: integer
      name: current_humidity
      readonly: true
secondary_entities:
  - entity: sensor
    class: humidity
    name: Current Humidity
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: "%"
        class: measurement
        readonly: true
  - entity: light
    name: Display
    category: config
    dps:
      - id: 101
        type: boolean
        name: switch
        mapping:
          - dps_val: true
            icon: "mdi:led-on"
          - dps_val: false
            icon: "mdi:led-off"
  - entity: switch
    name: Sleep
    category: config
    dps:
      - id: 104
        type: boolean
        name: switch
        mapping:
          - dps_val: true
            icon: "mdi:sleep"
          - dps_val: false
            icon: "mdi:sleep-off"
  - entity: binary_sensor
    name: Tank
    category: diagnostic
    dps:
      - id: 19
        name: sensor
        type: integer
        mapping:
          - dps_val: 1
            value: true
            icon: "mdi:flask-empty"
          - dps_val: 0
            value: false
            icon: "mdi:flask-empty-outline"
```
