### ISSUE TITLE
Request support for MoistenLand Water Timer

### ISSUE THREAD

**Issue by afallows** [make-all/tuya-local#1092]
MoistenLand Bluetooth Water Timer VIA Tuya Gateway GWB-03
Seems to work well when persist is set to false in the Device Specific Yaml file.
Had several timeouts in TinyTuya, not sure if there are some other settings I should try. Most errors were due to response from an unexpected CID.

-->

# Log Message from HomeAssistant
```
2023-09-13 13:37:10.491 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] Front Lawn (Local) refreshed device state: {"dps": {"1": true, "4": 0, "7": 100, "8": "high", "10": "cancel", "11": 300, "12": "manual"}, "cid": "**RETRACTED**", "device": "Non-JSON: (Device( '**RETRACTED**', address=None, local_key='', dev_type='default', connection_timeout=5, version=3.4, persist=False, cid='**RETRACTED**', parent='**RETRACTED**', children={} ))"}
2023-09-13 13:37:10.491 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] new state (incl pending): {"updated_at": 1694637430.4895597, "1": true, "4": 0, "7": 100, "8": "high", "10": "cancel", "11": 300, "12": "manual"}
2023-09-13 14:49:03.430 DEBUG (SyncWorker_1) [custom_components.tuya_local.device] Back Lawn (Local) refreshed device state: {"dps": {"1": true, "4": 0, "7": 100, "8": "high", "10": "cancel", "11": 600, "12": "manual", "15": 18}, "cid": "RETRACTED", "device": "Non-JSON: (Device( 'RETRACTED', address=None, local_key='', dev_type='default', connection_timeout=5, version=3.4, persist=False, cid='RETRACTED', parent='RETRACTED', children={} ))"}
```

MoistenLand.yaml via Bluetooth Gateway GWB-03 - Edited September 14, to remove persist per comment, as it is not applied correctly. Applied persist: False to DP:15 as it will only report if the watering timer has a "Watering Time last cycle" value.
```
name: Moistenland Irrigation
products:
  - id: 8t5hebn0
    name: MoistenLand Timer
primary_entity:
  entity: switch
  icon: mdi:sprinkler-variant
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: sensor
    name: Fault reporting
    category: diagnostic
    icon: mdi:alert-circle
    dps:
      - id: 4
        type: integer
        name: sensor
  - entity: sensor
    name: Battery
    class: battery
    category: diagnostic
    icon: mdi:battery
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: "%"
  - entity: sensor
    name: Battery Status
    class: enum
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        mapping:
          - dps_val: "low"
            value: "Replace Battery"
          - dps_val: "middle"
            value: "Battery Ok"
          - dps_val: "high"
            value: "Fully Charged"
  - entity: select
    name: Weather delay
    icon: "mdi:weather-cloudy-clock"
    category: config
    dps:
      - id: 10
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "Off"
          - dps_val: "24h"
            value: "1 day"
          - dps_val: "48h"
            value: "2 days"
          - dps_val: "72h"
            value: "3 days"
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 11
        name: value
        type: integer
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: sensor
    name: Work Mode
    class: enum
    category: diagnostic
    icon: mdi:auto-mode
    dps:
      - id: 12
        type: string
        name: sensor
        mapping:
          - dps_val: "manual"
            value: "Manual"
          - dps_val: "auto"
            value: "Auto"
          - dps_val: "idle"
            value: "Idle"
  - entity: sensor
    name: Use_Time_s
    category: diagnostic
    icon: mdi:water-circle
persist: False
    dps:
      - id: 15
        type: integer
        name: sensor
        range:
          min: 0
          max: 86400
        unit: min
        mapping:
          - scale: 60
            step:  60           
```

TinyTuya Test Script.

```
import tinytuya
import time
tinytuya.set_debug(True)

# Connect to Device
gw_id='REDACTED'
dev_id='REDACTED'
address='REDACTED'      # Or set to 'Auto' to auto-discover IP address
local_key="REDACTED"
did='REDACTED'
did2='REDACTED'
version="3.4"
loopcount = 0
# Get Status
gw = tinytuya.Device(gw_id,address,local_key,'device22',persist=False)
gw.set_version(3.4)
api = tinytuya.Device(gw_id,cid=did,parent=gw)
api2 = tinytuya.Device(gw_id,cid=did2,parent=gw)

while loopcount <= 10:
    api.set_value(1, True)
    time.sleep(5)
    api2.set_value(1, True)
    time.sleep(30)
    api.set_value(1, False)
    time.sleep(5)
    api2.set_value(1, False)
    time.sleep(5)
    print('Status from device 1')
    print(api.status())
    time.sleep(5)
    print('Status from device 2')
    print(api2.status())
    loopcount = loopcount + 1
```
TinyTuya Log File

```
[https://drive.google.com/file/d/17VKOZ7PuwQ4lgyeu-mAkl1vqwv52F17e/view?usp=sharing](url)
```
