### ISSUE TITLE
Request support for ASC (Wi-Fi) ver 2    (CBI Astute WiFi circuit breaker)

### ISSUE THREAD

**Issue by bbs2web** [make-all/tuya-local#1150]
I have a 'CBI Astute WiFi circuit breaker' which appears to be a newer version that what the 'asc_wifi_circuit_breaker' is for, it is very similar to the 'cbi_astute_outdoor_smartswitch' device. I subsequently created a 'ascv2_wifi_circuit_breaker' device type and it appears to work as expected.

# Information about DPS mappings
```
{
  "result": {
    "model": "{\"modelId\":\"000002k39n\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"Countdown\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_circle\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}},{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"add_ele\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dianliang\"},\"name\":\"增加电量\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":3,\"step\":100,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kwh\"}},{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-Ele\"},\"name\":\"Current current\",\"typeSpec\":{\"max\":30000,\"min\":0,\"scale\":3,\"step\":100,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"A\"}},{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dianliang\"},\"name\":\"当前电压\",\"typeSpec\":{\"max\":5000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}},{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gaodiyin\"},\"name\":\"当前功率\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}}]}]}"
  },
  "success": true,
  "t": 1696685149609,
  "tid": "07c488c7651511eeab9046acc027565a"
}
```

# Product ID
```
{
  "result": [
    {
      "active_time": 1696674771,
      "category": "kg",
      "create_time": 1690314384,
      "custom_name": "ASCv2 - Spare",
      "icon": "smart/icon/ay1568393722790s1w0j/9d1d19ccc3f44201c5ae13cc1e3a543b.png",
      "id": "bfdf3e4d1e964b2d67eqdb",
      "ip": "96.42.98.35",
      "is_online": false,
      "lat": "-25.9907",
      "local_key": "****************",
      "lon": "28.0643",
      "model": "ASC-W-002",
      "name": "ASC (Wi-Fi) ver 2",
      "product_id": "xzgtyrqbab8lm2zo",
      "product_name": "ASC (Wi-Fi) ver 2",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1696674771,
      "uuid": "98a704ad20361a06"
    }
  ],
  "success": true,
  "t": 1696685629591,
  "tid": "25eb87ed651611ee8665fe445e07f2df"
}
```

# My proposed device definition file

```
name: CBI Astute smart controller
products:
  - id: xzgtyrqbab8lm2zo
    name: ASC (Wi-Fi) ver 2
primary_entity:
  entity: switch
  class: switch
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 7
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: select
    category: config
    name: Initial state
    icon: "mdi:toggle-switch"
    dps:
      - id: 14
        type: string
        name: option
        mapping:
          - dps_val: "off"
            value: "Off"
          - dps_val: "on"
            value: "On"
          - dps_val: "memory"
            value: "Last State"
  - entity: sensor
    category: diagnostic
    class: energy
    dps:
      - id: 20
        type: integer
        name: sensor
        unit: Wh
        class: total_increasing
        force: true
        optional: true
  - entity: sensor
    category: diagnostic
    class: current
    dps:
      - id: 21
        type: integer
        name: sensor
        class: measurement
        force: true
        unit: A
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    class: voltage
    dps:
      - id: 22
        type: integer
        name: sensor
        class: measurement
        force: true
        unit: V
        range:
          min: 0
          max: 5000
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: power
    dps:
      - id: 23
        type: integer
        name: sensor
        class: measurement
        force: true
        unit: W
        range:
          min: 0
          max: 50000
        mapping:
          - scale: 10
```

Device functionality:

Everything works as expected, except that I have to have the Tuya app open on my mobile with it connected to the same SSID as what the device is connected to. I've blocked all internet access for the devices and local functionality works perfectly (automations are able to switch the circuit breaker on and off without internet access) but the sensor readings only come through whilst the app is running. The moment I close the app the current, voltage, current and power readings stop.

I was initially using local-tuya but much prefer tuya-local, I believe the above limitation to be something with this model and not specifically a problem with the device definition or DPs...
