### ISSUE TITLE
Request support for Calex Aroma Diffuser

### ISSUE THREAD

**Issue by larronni** [make-all/tuya-local#1164]
This is working for this device. Sorry, I do not know how to create a pull request...

---

##Calex aroma diffuser ##
```
name: Calex-Aroma Diffuser
products:
  - id: orw9vhekocfzx78l
    model: new-2.0 version
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: true
          icon: "mdi:toggle-switch-variant"
        - dps_val: false
          icon: "mdi:toggle-switch-variant-off"
secondary_entities:
  - entity: switch
    name: Diffuser spray
    dps:
      - id: 2
        name: switch
        type: boolean
        mapping:
          - dps_val: true
            icon: "mdi:scent"
          - dps_val: false
            icon: mdi:scent-off"
  - entity: light
    name: Diffuser light
    icon: "mdi:light-recessed"
    dps:
      - id: 7
        name: switch
        type: boolean
      - id: 9
        name: color_mode
        type: string
        mapping:
          - dps_val: colour
            value: hs
          - dps_val: colourful1
            value: Colorful
      - id: 10
        name: rgbhsv
        type: hex
        format:
          - name: r
            bytes: 1
          - name: g
            bytes: 1
          - name: b
            bytes: 1
          - name: h
            bytes: 2
            range:
              min: 0
              max: 360
          - name: s
            bytes: 1
            range:
              min: 0
              max: 255
          - name: v
            bytes: 1
            range:
              min: 0
              max: 255
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 4
        name: option
        type: string
        mapping:
          - dps_val: "cancel"
            value: "Off"
          - dps_val: "1"
            value: "1 hour"
          - dps_val: "3"
            value: "3 hours"
          - dps_val: "6"
            value: "6 hours"

```
