### ISSUE TITLE
Request support for Petrust TK-WF002 (GN_PW01)

### ISSUE THREAD

**Issue by pot-noble** [make-all/tuya-local#1173]
# YAML
```
name: Petrust Smart Fountain
products:
  - id: 5jdws4vgfzhkq7vs
primary_entity:
  entity: switch
  icon: "mdi:power"
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: select
    name: Mode
    class: enum
    icon: "mdi:auto-mode"
    dps:
      - id: 2
        type: string
        name: option
        mapping:
          - dps_val: "normal"
            value: "Normal"
          - dps_val: "smart"
            value: "Smart"
  - entity: select
    name: Water Control
    class: enum
    icon: "mdi:water-circle"
    dps:
      - id: 11
        type: string
        name: option
        mapping:
          - dps_val: "close"
            icon: "mdi:water-off"
            value: "Close"
          - dps_val: "low"
            value: "Low"
          - dps_val: "middle"
            value: "Middle"
          - dps_val: "high"
            value: "High"
  - entity: number
    name: Status Brightness
    icon: "mdi:brightness-6"
    category: config
    dps:
      - id: 12
        type: integer
        name: value
        range:
          min: 0
          max: 4
  - entity: number
    name: Filter lifetime
    icon: "mdi:air-filter"
    category: config
    dps:
      - id: 7
        type: integer
        name: value
        range:
          min: 0
          max: 30
  - entity: sensor
    name: Replace filter in
    icon: "mdi:air-filter"
    category: diagnostic
    dps:
      - id: 3
        type: integer
        name: sensor
        unit: days
  - entity: button
    name: Replace filter
    icon: "mdi:air-filter"
    category: config
    dps:
      - id: 5
        type: boolean
        name: button
  - entity: number
    name: Clean life
    icon: "mdi:pump"
    category: config
    dps:
      - id: 8
        type: integer
        name: value
        range:
          min: 0
          max: 20
  - entity: sensor
    name: Clean in
    icon: "mdi:pump"
    category: diagnostic
    dps:
      - id: 4
        type: integer
        name: sensor
        unit: days
  - entity: button
    name: Pump cleaned
    icon: "mdi:pump"
    category: config
    dps:
      - id: 6
        type: boolean
        name: button
  - entity: sensor
    name: Water level
    class: enum
    category: diagnostic
    dps:
      - id: 9
        name: sensor
        type: string
        mapping:
          - dps_val: "low"
            icon: "mdi:cup-outline"
            value: "Low"
          - dps_val: "middle"
            icon: "mdi:cup-water"
            value: "Middle"
          - dps_val: "high"
            icon: "mdi:cup"
            value: "High"
  - entity: sensor
    name: Water time (days)
    class: enum
    icon: "mdi:water-opacity"
    category: diagnostic
    dps:
      - id: 24
        type: integer
        name: sensor
  - entity: button
    name: Change water
    icon: "mdi:water-sync"
    category: config
    dps:
      - id: 25
        type: boolean
        name: button
  - entity: switch
    name: UV Cleaner
    icon: "mdi:bacteria"
    category: config
    dps:
      - id: 14
        type: boolean
        name: switch
  - entity: number
    name: UV runtime
    icon: "mdi:timer-outline"
    category: config
    dps:
      - id: 15
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 90
```
# Log Message

```
Device matches petrust_fountain_custom with quality of 94%. DPS: {"updated_at": 1697396589.492513, "1": true, "2": "normal", "3": 12, "4": 3, "5": false, "6": false, "7": 14, "8": 5, "9": "high", "11": "close", "12": 4, "14": true, "15": 10, "23": 0, "24": 6, "25": false}
```
As far as i understand there should be no logs if device matches with quality of 100%. I think those 6% is missing because of DP 9 (Water level), according to things data model it should have "middle" value but my device is reporting "high" when there is more than 20% of the water and then it will switch to "low" (i think it happens when water level is getting below the pump).
However, I didn’t removed that "middle" value cause maybe someone else’s device would report that value. 

There is also DP 23 (Fault). I'm not sure about values of that DP, what they mean and how to set it properly, i guess it should be bitfield but I don't know bits meaning yet and didn't saw any changes through device debugging in Tuya IoT platform. Maybe there is something in the things data model, I will take a closer look and add a comment if I found something.

I've also set max values for some of DPs to a lower value than device actually allows but that's just my preference.

# Information about DPS mappings

**Query Device Details**
```
"result": {
    "active_time": 111,
    "category": "cwysj",
    "create_time": 111,
    "custom_name": "",
    "icon": "smart/icon/ay1537266087379ueEwg/612fb4d2bfcd1ef853c55416ec725a7a.png",
    "id": "",
    "ip": "",
    "is_online": true,
    "lat": "111",
    "local_key": "",
    "lon": "111",
    "model": "GN_PW01",
    "name": "Pet Water Fountain",
    "product_id": "5jdws4vgfzhkq7vs",
    "product_name": "公版宠物喂水器",
    "sub": false,
    "time_zone": "",
    "update_time": 111,
    "uuid": "111"
  }
```
**Query Things Data Model**
```
  "result": {
    "model": "{\"modelId\":\"0000037g2o\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"总开关\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1664\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"normal：普通模式\\nsmart：智能模式\\nnight：夜晚模式\\npir：感应模式\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1664\"},\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"normal\",\"smart\"],\"type\":\"enum\",\"typeDefaultValue\":\"normal\"}},{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"filter_days\",\"description\":\"设备本地上报\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1664\"},\"name\":\"滤芯剩余天数\",\"typeSpec\":{\"max\":90,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"day\"}},{\"abilityId\":4,\"accessMode\":\"ro\",\"code\":\"pump_time\",\"description\":\"设备上报剩余清洗天数\",\"extensions\":{\"iconName\":\"icon-dp_time\",\"attribute\":\"1664\"},\"name\":\"清洗剩余天数\",\"typeSpec\":{\"max\":31,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"day\"}},{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"filter_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1664\"},\"name\":\"滤芯重置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"pump_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1664\"},\"name\":\"清洗重置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"filter_life\",\"description\":\"0表示关闭，不进行滤芯更换提醒，首页也不显示滤芯剩余天数\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1760\"},\"name\":\"滤芯更换提醒时间设置\",\"typeSpec\":{\"max\":90,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"day\"}},{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"time_clean\",\"description\":\"0表示关闭，不进行清洗提醒，首页也不显示清洗剩余天数\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"1760\"},\"name\":\"清洗提醒时间设置\",\"typeSpec\":{\"max\":31,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"day\"}},{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"water_level\",\"description\":\"适用于无精确计算功能的饮水机\\nlow：水量不足；\\nmiddle：水量中等；\\nhigh：水量充足；\",\"extensions\":{\"iconName\":\"icon-dp_water\",\"attribute\":\"1152\"},\"name\":\"剩余水量档位\",\"typeSpec\":{\"range\":[\"low\",\"middle\",\"high\"],\"type\":\"enum\",\"typeDefaultValue\":\"low\"}},{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"water_control\",\"description\":\"close：关闭，停止出水\\nlow：出水量小\\nmiddle：出水量中\\nhigh：出水量大\",\"extensions\":{\"iconName\":\"icon-dp_water\",\"attribute\":\"1152\"},\"name\":\"出水量调节\",\"typeSpec\":{\"range\":[\"close\",\"low\",\"middle\",\"high\"],\"type\":\"enum\",\"typeDefaultValue\":\"close\"}},{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"bright_value\",\"description\":\"0表示关闭指示灯\",\"extensions\":{\"iconName\":\"icon-liangdu\",\"attribute\":\"1152\"},\"name\":\"指示灯亮度\",\"typeSpec\":{\"max\":4,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"uv\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1152\"},\"name\":\"UV杀菌\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"uv_runtime\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"1152\"},\"name\":\"UV运行时间\",\"typeSpec\":{\"max\":180,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"lack_water：缺水提醒；\\nfilter_replace：滤芯更换提醒；\\nclean_reminder：清洗提醒；\\nbattery_power：电池供电提醒；\\npump_blocked：水泵堵塞提醒；\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"lack_water\",\"filter_replace\",\"clean_reminder\",\"battery_power\",\"pump_blocked\"],\"maxlen\":5,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"water_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time\",\"attribute\":\"1152\"},\"name\":\"用水时长\",\"typeSpec\":{\"max\":3000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"day\"}},{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"water_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1152\"},\"name\":\"用水重置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  }
```
**Query Properties **
```
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 111,
        "value": true
      },
      {
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 111,
        "value": "normal"
      },
      {
        "code": "filter_days",
        "custom_name": "",
        "dp_id": 3,
        "time": 111,
        "value": 14
      },
      {
        "code": "pump_time",
        "custom_name": "",
        "dp_id": 4,
        "time": 111,
        "value": 5
      },
      {
        "code": "filter_reset",
        "custom_name": "",
        "dp_id": 5,
        "time": 111,
        "value": false
      },
      {
        "code": "pump_reset",
        "custom_name": "",
        "dp_id": 6,
        "time": 111,
        "value": false
      },
      {
        "code": "filter_life",
        "custom_name": "",
        "dp_id": 7,
        "time": 111,
        "value": 14
      },
      {
        "code": "time_clean",
        "custom_name": "",
        "dp_id": 8,
        "time": 111,
        "value": 5
      },
      {
        "code": "water_level",
        "custom_name": "",
        "dp_id": 9,
        "time": 111,
        "value": "high"
      },
      {
        "code": "water_control",
        "custom_name": "",
        "dp_id": 11,
        "time": 111,
        "value": "close"
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 12,
        "time": 111,
        "value": 4
      },
      {
        "code": "uv",
        "custom_name": "",
        "dp_id": 14,
        "time": 111,
        "value": false
      },
      {
        "code": "uv_runtime",
        "custom_name": "",
        "dp_id": 15,
        "time": 111,
        "value": 10
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 23,
        "time": 111,
        "value": 0
      },
      {
        "code": "water_time",
        "custom_name": "",
        "dp_id": 24,
        "time": 111,
        "value": 4
      },
      {
        "code": "water_reset",
        "custom_name": "",
        "dp_id": 25,
        "time": 111,
        "value": false
      }
    ]
  }
```
**Get the specifications and properties of the device**
```
  "result": {
    "category": "cwysj",
    "functions": [
      {
        "code": "switch",
        "desc": "{}",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_reset",
        "desc": "{}",
        "name": "滤芯复位",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump_reset",
        "desc": "{}",
        "name": "水泵重置",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "desc": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1}",
        "name": "指示灯亮度",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1}"
      },
      {
        "code": "uv",
        "desc": "{}",
        "name": "UV杀菌",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "uv_runtime",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":180,\"scale\":0,\"step\":1}",
        "name": "UV运行时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":180,\"scale\":0,\"step\":1}"
      },
      {
        "code": "water_reset",
        "desc": "{}",
        "name": "用水重置",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "name": "开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump_time",
        "name": "水泵时长",
        "type": "Integer",
        "values": "{\"unit\":\"day\",\"min\":0,\"max\":31,\"scale\":0,\"step\":1}"
      },
      {
        "code": "filter_reset",
        "name": "滤芯复位",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump_reset",
        "name": "水泵重置",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_life",
        "name": "滤芯时长",
        "type": "Integer",
        "values": "{\"unit\":\"day\",\"min\":0,\"max\":90,\"scale\":0,\"step\":1}"
      },
      {
        "code": "bright_value",
        "name": "指示灯亮度",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1}"
      },
      {
        "code": "uv",
        "name": "UV杀菌",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "uv_runtime",
        "name": "UV运行时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":180,\"scale\":0,\"step\":1}"
      },
      {
        "code": "water_time",
        "name": "用水时长",
        "type": "Integer",
        "values": "{\"unit\":\"day\",\"min\":0,\"max\":3000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "water_reset",
        "name": "用水重置",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  }
```
**Get the instruction set of the device**
```
  "result": {
    "category": "cwysj",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "filter_reset",
        "desc": "filter reset",
        "name": "filter reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "pump_reset",
        "desc": "pump reset",
        "name": "pump reset",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "desc": "bright value",
        "name": "bright value",
        "type": "Integer",
        "values": "{\"min\":0,\"max\":4,\"scale\":0,\"step\":1}"
      },
      {
        "code": "uv",
        "desc": "uv",
        "name": "uv",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "uv_runtime",
        "desc": "uv runtime",
        "name": "uv runtime",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":180,\"scale\":0,\"step\":1}"
      },
      {
        "code": "water_reset",
        "desc": "water reset",
        "name": "water reset",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  }
```

# Product ID

`5jdws4vgfzhkq7vs`

# Information about how the device functions

This is a pretty much standard Tyua pet water fountain. Although it has a lot of DPs and not all of them are pretty obvious when trying to match DPs to app settings.
I couldn’t find any manuals or product descriptions in English but i have few links to product page with screenshots and functionally description. I guess it should be fine with auto translator.
https://rozetka.com.ua/ua/372842376/p372842376/
https://rozetka.com.ua/ua/363758238/p363758238/
