### ISSUE TITLE
Request support for Tadiran Apollo Inverter Air Conditioner

### ISSUE THREAD

**Issue by tidharmor** [make-all/tuya-local#1183]
Hi,

I connected my AC and created this yaml file after getting the initial DPS list from the log and the the Tuya IOT portal.
Some of the reported DPS have no effect on my model even though they are reported.
Most functions from the remote control work using this configuration.

tadiran_apollo_inverter_air_conditioner.yaml:

```
name: Tadiran Apollo Inverter air conditioner
products:
  - id: 9xvzf8c0bg33eenj
    name: Tadiran Apollo Inverter
primary_entity:
  entity: climate
  translation_key: aircon_extra
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
        - dps_val: true
          constraint: mode
          conditions:
            - dps_val: auto
              icon: "mdi:hvac"
              value: heat_cool
            - dps_val: cold
              icon: "mdi:snowflake"
              value: cool
            - dps_val: hot
              icon: "mdi:fire"
              value: heat
            - dps_val: wet
              icon: "mdi:water-off"
              value: dry
            - dps_val: wind
              icon: "mdi:fan"
              value: fan_only
    - id: 2
      name: temperature
      type: integer
      range:
        min: 16
        max: 30
      mapping:
        - step: 1
          constraint: mode
          conditions:
            - dps_val: wind
              invalid: true
    - id: 3
      name: current_temperature
      type: integer
      mapping:
        - scale: 2
    - id: 4
      name: mode
      type: string
      hidden: true
    - id: 5
      name: fan_mode
      type: string
      mapping:
        - dps_val: high
          value: high
        - dps_val: low
          value: low
        - dps_val: auto
          value: auto
        - dps_val: strong
          value: strong
    - id: 8
      name: mode_eco
      type: boolean
    - id: 12
      name: heat
      type: boolean
    - id: 13
      name: light
      type: boolean
    - id: 18
      name: humidity_current
      type: integer
      unit: "%"
      class: measurement
      mapping:
        - scale: 10
    - id: 19
      name: temperature_unit
      type: string
      mapping:
        - dps_val: f
          value: F
        - dps_val: c
          value: C
    - id: 101
      name: mood_lighting
      type: boolean
    - id: 102
      name: PM2.5
      type: integer
    - id: 103
      name: CO2
      type: integer
    - id: 104
      name: VOC
      type: integer
    - id: 105
      name: air_quality
      type: integer
    - id: 106
      name: health
      type: boolean
    - id: 107
      name: strong
      type: boolean
    - id: 108
      name: mute
      type: boolean
    - id: 109
      name: sleep
      type: boolean
    - id: 110
      name: 10c_heating
      type: boolean
    - id: 111
      name: new_style
      type: boolean
    - id: 112
      name: Power
      type: integer
    - id: 113
      name: sense
      type: string
    - id: 114
      name: self_cleaning
      type: boolean
    - id: 116
      name: Fault_code
      type: integer
    - id: 117
      name: swing_mode
      type: string
      mapping:
        - dps_val: ud_00
          value: off
        - dps_val: ud_01
          value: 1
        - dps_val: ud_02
          value: 2
        - dps_val: ud_03
          value: 3
        - dps_val: ud_04
          value: 4
        - dps_val: ud_0c
          value: vertical
    - id: 118
      name: horizontal_swing
      type: string
    - id: 119
      name: 56C_Cleaning
      type: boolean
secondary_entities:
  - entity: switch
    name: Power
    category: config
    icon: "mdi:power"
    dps:
      - id: 1
        name: switch
        type: boolean
  - entity: switch
    name: Eco
    category: config
    icon: "mdi:flower"
    dps:
      - id: 8
        name: switch
        type: boolean
  - entity: light
    name: Display
    category: config
    icon: "mdi:television-ambient-light"
    dps:
      - id: 13
        name: switch
        type: boolean
  - entity: switch
    name: Sleep
    category: config
    icon: "mdi:power-sleep"
    dps:
      - id: 109
        name: switch
        type: boolean
        optional: true
  - entity: switch
    name: Health
    category: config
    icon: "mdi:shield-bug"
    dps:
      - id: 106
        name: switch
        type: boolean
        optional: true
  - entity: switch
    name: Horizontal Swing
    category: config
    icon: "mdi:arrow-left-right-bold"
    dps:
      - id: 118
        name: switch
        type: string
        mapping:
          - dps_val: "on"
            value: true
          - dps_val: "off"
            value: false
  - entity: switch
    name: Vertical Swing
    category: config
    icon: "mdi:arrow-left-right-bold"
    dps:
      - id: 117
        name: switch
        type: string
        mapping:
          - dps_val: "on"
            value: true
          - dps_val: "off"
            value: false

```

And here is the diagnostics data from the device:

```

"data": {
    "name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df",
    "type": "tadiran_apollo_inverter_air_conditioner",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.12.11",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1697537319.0284274,
      "1": true,
      "2": 25,
      "3": 52,
      "4": "wet",
      "5": "low",
      "8": false,
      "12": false,
      "13": true,
      "18": 0,
      "19": "c",
      "101": false,
      "102": 0,
      "103": 0,
      "104": 0,
      "105": "0",
      "106": true,
      "107": false,
      "108": false,
      "109": false,
      "110": false,
      "111": false,
      "112": 0,
      "113": "cancel",
      "114": false,
      "116": 0,
      "117": "ud_03",
      "118": "lr_00",
      "119": false
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_power",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:power",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Power"
            },
            "last_changed": "2023-10-17T09:19:53.715568+00:00",
            "last_updated": "2023-10-17T09:19:53.715568+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_eco",
            "state": "off",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:flower",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Eco"
            },
            "last_changed": "2023-10-17T09:19:53.716150+00:00",
            "last_updated": "2023-10-17T09:19:53.716150+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_beep",
            "state": "unavailable",
            "attributes": {
              "restored": true,
              "device_class": "switch",
              "icon": "mdi:bell",
              "friendly_name": "Beep",
              "supported_features": 0
            },
            "last_changed": "2023-10-17T09:20:08.441466+00:00",
            "last_updated": "2023-10-17T09:20:08.441466+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_sleep",
            "state": "off",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:power-sleep",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Sleep"
            },
            "last_changed": "2023-10-17T09:19:53.716564+00:00",
            "last_updated": "2023-10-17T09:19:53.716564+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_health",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:shield-bug",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Health"
            },
            "last_changed": "2023-10-17T09:19:53.717149+00:00",
            "last_updated": "2023-10-17T09:19:53.717149+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_horizontal_swing",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:arrow-left-right-bold",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Horizontal Swing"
            },
            "last_changed": "2023-10-17T09:19:53.717599+00:00",
            "last_updated": "2023-10-17T09:19:53.717599+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "switch",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.mzgn_lvn_vertical_swing",
            "state": "on",
            "attributes": {
              "device_class": "switch",
              "icon": "mdi:arrow-left-right-bold",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Vertical Swing"
            },
            "last_changed": "2023-10-17T09:19:53.718275+00:00",
            "last_updated": "2023-10-17T09:19:53.718275+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.mzgn_lvn_display",
            "state": "on",
            "attributes": {
              "supported_color_modes": [
                "onoff"
              ],
              "color_mode": "onoff",
              "icon": "mdi:television-ambient-light",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df Display",
              "supported_features": 0
            },
            "last_changed": "2023-10-17T09:19:53.472716+00:00",
            "last_updated": "2023-10-17T09:19:53.472716+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.alon_ac_tuya_tadiran",
            "state": "dry",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat_cool",
                "cool",
                "heat",
                "dry",
                "fan_only"
              ],
              "min_temp": 16,
              "max_temp": 30,
              "target_temp_step": 1.0,
              "fan_modes": [
                "high",
                "low",
                "auto",
                "strong"
              ],
              "current_temperature": 26.0,
              "temperature": 25,
              "fan_mode": "low",
              "mode_eco": false,
              "heat": false,
              "light": true,
              "humidity_current": 0.0,
              "mood_lighting": false,
              "PM2.5": 0,
              "CO2": 0,
              "VOC": 0,
              "air_quality": 0,
              "health": true,
              "strong": false,
              "mute": false,
              "sleep": false,
              "10c_heating": false,
              "new_style": false,
              "Power": 0,
              "sense": "cancel",
              "self_cleaning": false,
              "Fault_code": 0,
              "vertical_swing": "ud_03",
              "horizontal_swing": "lr_00",
              "56C_Cleaning": false,
              "icon": "mdi:water-off",
              "friendly_name": "\u05de\u05d6\u05d2\u05df \u05d0\u05dc\u05d5\u05df",
              "supported_features": 9
            },
            "last_changed": "2023-10-17T09:19:53.474840+00:00",
            "last_updated": "2023-10-17T10:04:58.462928+00:00"
          }
        }
      ]
    }
  }

```
