### ISSUE TITLE
Request support for Water Leak Detector

### ISSUE THREAD

**Issue by tidharmor** [make-all/tuya-local#1184]
WaterLeakDetector.yaml
```
name: Water Leak Detector
primary_entity:
  entity: sensor
  class: enum
  dps:
    - id: 1
      name: sensor
      type: string
    - id: 4
      name: battery
      type: integer
      unit: "%"
      class: measurement
      optional: true
secondary_entities:
  - entity: sensor
    name: Battery
    dps:
      - id: 4
        name: battery
        type: integer
        unit: "%"
        class: measurement
        optional: true

```
