### ISSUE TITLE
Request support for Greenmigo ALPHA-Q25 Pro WIFI dehumidifier

### ISSUE THREAD

**Issue by Privatecoder** [make-all/tuya-local#1202]
@make-all 

I have a Greenmigo ALPHA-Q25 Pro WIFI, which seems to be a re-brand of the same device-family which has been added here: #306 / Eeese Otto-series.

For the start: Everything works, i.e the implemented features for Eeesee, however the Greenmigo also features setting the target "fan-speed" (dp: 4), (more) working-"mode"s (dp: 5) and "uv"-function (dp: 13)  so if this could be integrated as well, that would be great!

```
{
  "1": "Power",
  "2": "Dehumidify",
  "4": "Speed",
  "5": "Working Mode",
  "6": "Indoor Humidity",
  "8": "Swing",
  "10": "Anion",
  "13": "UV",
  "16": "Child Lock",
  "17": "Timer Off",
  "19": "Error Code"
}
```
dp: `4`
name: `fan_speed_enum`
type: `Enum`
values: `["low", "high"]`

dp: `5`
name: `mode `
type: `enum `
values: `["Manual", "Auto", "Laundrydrying", "Sleeping", "Purifying"]`

dp: `13`
name: `uv `
type: `Boolean`

error-codes are probably also of interest:

dp: `19`
name: `fault`
type: `bitmap`
values: `["E1", "E2", "tankfull", "defrost"]`

from API-Explorer:

```
"model": {
	"modelId": "000003el32",
	"services": [{
		"actions": [],
		"code": "",
		"description": "",
		"events": [],
		"name": "默认服务",
		"properties": [{
			"abilityId": 1,
			"accessMode": "rw",
			"code": "switch",
			"description": "",
			"extensions": {
				"attribute": "1"
			},
			"name": "开关",
			"typeSpec": {
				"type": "bool",
				"typeDefaultValue": false
			}
		}, {
			"abilityId": 2,
			"accessMode": "rw",
			"code": "dehumidify_set_value",
			"description": "",
			"name": "除湿值",
			"typeSpec": {
				"max": 80,
				"min": 25,
				"scale": 0,
				"step": 5,
				"type": "value",
				"typeDefaultValue": 25,
				"unit": "%"
			}
		}, {
			"abilityId": 4,
			"accessMode": "rw",
			"code": "fan_speed_enum",
			"description": "",
			"extensions": {
				"iconName": "icon-dp_wind",
				"attribute": "1024"
			},
			"name": "风速",
			"typeSpec": {
				"range": ["low", "high"],
				"type": "enum",
				"typeDefaultValue": "low"
			}
		}, {
			"abilityId": 5,
			"accessMode": "rw",
			"code": "mode",
			"description": "",
			"name": "工作模式",
			"typeSpec": {
				"range": ["Manual", "Auto", "Laundrydrying", "Sleeping", "Purifying"],
				"type": "enum",
				"typeDefaultValue": "Manual"
			}
		}, {
			"abilityId": 6,
			"accessMode": "ro",
			"code": "humidity_indoor",
			"description": "",
			"name": "室内湿度",
			"typeSpec": {
				"max": 100,
				"min": 0,
				"scale": 0,
				"step": 1,
				"type": "value",
				"typeDefaultValue": 0,
				"unit": "%"
			}
		}, {
			"abilityId": 8,
			"accessMode": "rw",
			"code": "swing",
			"description": "",
			"name": "摆风",
			"typeSpec": {
				"type": "bool",
				"typeDefaultValue": false
			}
		}, {
			"abilityId": 10,
			"accessMode": "rw",
			"code": "anion",
			"description": "",
			"name": "负离子",
			"typeSpec": {
				"type": "bool",
				"typeDefaultValue": false
			}
		}, {
			"abilityId": 13,
			"accessMode": "rw",
			"code": "uv",
			"description": "",
			"extensions": {
				"iconName": "icon-dp_power2",
				"attribute": "1024"
			},
			"name": "UV杀菌",
			"typeSpec": {
				"type": "bool",
				"typeDefaultValue": false
			}
		}, {
			"abilityId": 16,
			"accessMode": "rw",
			"code": "child_lock",
			"description": "",
			"name": "童锁",
			"typeSpec": {
				"type": "bool",
				"typeDefaultValue": false
			}
		}, {
			"abilityId": 17,
			"accessMode": "rw",
			"code": "countdown_set",
			"description": "",
			"name": "定时关机",
			"typeSpec": {
				"range": ["cancel", "1h", "2h", "3h", "4h", "5h", "6h", "7h", "8h", "9h", "10h", "11h", "12h", "13h", "14h", "15h", "16h", "17h", "18h", "19h", "20h", "21h", "22h", "23h", "24h"],
				"type": "enum",
				"typeDefaultValue": "cancel"
			}
		}, {
			"abilityId": 19,
			"accessMode": "ro",
			"code": "fault",
			"description": "",
			"extensions": {
				"scope": "fault"
			},
			"name": "故障告警",
			"typeSpec": {
				"label": ["E1", "E2", "tankfull", "defrost"],
				"maxlen": 4,
				"type": "bitmap",
				"typeDefaultValue": 0
			}
		}]
	}]
}
```

**Comment by Privatecoder** [comment]
@make-all I added the purifier myself (#1207) and I am able to control all settings. However I have two questions:

1) I was under the impression that the mode-icons could be added like this:

```
    - id: 5
      name: mode
      type: string
      mapping:
        - dps_val: Manual
          value: Manual
          icon: "mdi:hand-back-right-outline"
        - dps_val: Auto
          value: Auto
          icon: "mdi:auto-mode"
        - dps_val: Laundrydrying
          value: Laundrydrying
          icon: "mdi:t-shirt-crew-outline"
        - dps_val: Sleeping
          value: Sleeping
          icon: "mdi:sleep"
        - dps_val: Purifying
          value: Purifying
          icon: "mdi:air-purifier"
```

but it does not show them and I guess it is due to the missing `icon_priority` however I did not quite understand how that works, i.e. which value I need.

2) I extended the `diagnostic` section like so:

```
  - entity: binary_sensor
    name: Status
    class: problem
    category: diagnostic
    dps:
      - id: 19
        type: bitfield
        name: sensor
        optional: true
        mapping:
          - dps_val: 0
            value: false
            icon: "mdi:check-circle-outline"
          - dps_val: null
            value: false
            icon: "mdi:check-circle-outline"
          - dps_val: 4
            value: Tank removed
            icon: "mdi:cup-off"
          - dps_val: tankfull
            value: Tank full
            icon: "mdi:cup-water"
          - dps_val: defrost
            value: Defrost
            icon: "mdi:snowflake-melt"
          - dps_val: null
            value: false
          - dps_val: E1
            value: E1
            icon: "mdi:alert-circle-outline"
          - dps_val: E2
            value: E2
            icon: "mdi:alert-circle-outline"
```

This does show the right icon – according to the error – however I thought the `value` would be passed as well but isn't. It only shows `problem` in lovelace.

Can you help?
