### ISSUE TITLE
Request support for Smart plug 16A

### ISSUE THREAD

**Issue by guffy1234** [make-all/tuya-local#1211]
Hi

I have Smart Plug device which operates almost as smartplugv2_energyv3, but without light control.
so I prepared smartplugv2_energyv4 with corresponding product id
```yaml
name: Energy monitoring smartplug
products:
  - id: dxzf5c5vayy0nlk6
    name: Smart plug 16A
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 21
      type: integer
      name: test_bit
    - id: 26
      type: bitfield
      name: fault_code
    - id: 42
      type: base64
      name: cycle_timer
      optional: true
    - id: 43
      type: base64
      name: random_timer
      optional: true
    - id: 44
      type: base64
      name: inching
      optional: true
secondary_entities:
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: sensor
    category: diagnostic
    name: Energy
    dps:
      - id: 17
        name: sensor
        type: integer
        unit: Wh
        optional: true
      - id: 25
        type: integer
        name: calibration
        # seems to be present even when 17 is missing, but for consistency
        optional: true
  - entity: sensor
    category: diagnostic
    class: current
    dps:
      - id: 18
        name: sensor
        type: integer
        class: measurement
        force: true
        unit: mA
      - id: 23
        type: integer
        name: calibration
  - entity: sensor
    category: diagnostic
    class: power
    dps:
      - id: 19
        name: sensor
        type: integer
        class: measurement
        force: true
        unit: W
        mapping:
          - scale: 10
      - id: 24
        type: integer
        name: calibration
  - entity: sensor
    category: diagnostic
    class: voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        class: measurement
        force: true
        unit: V
        mapping:
          - scale: 10
      - id: 22
        type: integer
        name: calibration
  - entity: binary_sensor
    class: problem
    category: diagnostic
    name: Error
    dps:
      - id: 26
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: select
    category: config
    name: Initial state
    icon: "mdi:toggle-switch"
    dps:
      - id: 38
        type: string
        name: option
        mapping:
          - dps_val: "on"
            value: "On"
          - dps_val: "off"
            value: "Off"
          - dps_val: memory
            value: "Last State"
  - entity: lock
    name: Child Lock
    category: config
    icon: "mdi:hand-back-right-off"
    dps:
      - id: 41
        type: boolean
        name: lock
  - entity: switch
    name: Overcharge protection
    category: config
    dps:
      - id: 39
        type: boolean
        name: switch
        optional: true


```

PS. I also created config for Atorch AT4PW . See #1038
