### ISSUE TITLE
New Device: MoesHouse WiFi Smart Plug Wireless RGB Power Socket (EU)

### ISSUE THREAD

**Issue by vampywiz17** [make-all/tuya-local#126]
Hi! I try to add this device to use the new RGB feature (https://github.com/make-all/tuya-local/issues/89), but it think it is too different...

Link: https://www.moeshouse.com/products/wifi-smart-plug-outlet-wireless-power-socket-smart-life-tuya-app-remote-control-work-with-alexa-google-home-no-hub-required-us

```
    "status": [
      {
        "code": "switch_led",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 2,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      },
      {
        "code": "colour_data",
        "dp_id": 5,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "scene_data",
        "dp_id": 6,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_1",
        "dp_id": 7,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_2",
        "dp_id": 8,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_3",
        "dp_id": 9,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "flash_scene_4",
        "dp_id": 10,
        "type": "Json",
        "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}"
      },
      {
        "code": "switch",
        "dp_id": 101,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "cur_current",
        "dp_id": 104,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 105,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 106,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":2500,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "dp_id": 102,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1643552499183
}
```

My config (the Energy part is not important now)

```
name: MoesHouse WiFi Smart Plug Wireless RGB Power Socket
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 101
      type: boolean
      name: switch
secondary_entities:
  - entity: light
    name: Night Light
    dps:
      - id: 1
        name: switch
        type: boolean
      - id: 2
        name: color_mode
        type: string
        mapping:
          - dps_val: white
            value: white
          - dps_val: colour
            value: rgbw
          - dps_val: scene
            value: colorloop
          - dps_val: scene_1
            value: Scene 1
          - dps_val: scene_2
            value: Scene 2
          - dps_val: scene_3
            value: Scene 3
          - dps_val: scene_4
            value: Scene 4
      - id: 3
        name: brightness
        type: integer
        range:
          min: 25
          max: 255
      - id: 5
        name: rgbhsv
        type: hex
      - id: 6
        name: unknown_6
        type: hex
      - id: 7
        name: unknown_7
        type: hex
      - id: 8
        name: unknown_8
        type: hex
      - id: 9
        name: unknown_9
        type: hex
      - id: 10
        name: unknown_10
        type: hex
```

Local data (tuya-cli)

```
{ devId: '528******************',
  dps:
   { '1': false,
     '2': 'colour',
     '3': 255,
     '4': 14,
     '5': 'ff99000024ffff',
     '6': 'bd76000168ffff',
     '7': 'ffff320100ff00',
     '8': 'ffff3203ff000000ff000000ff',
     '9': 'ffff3201ff0000',
     '10': 'ffff3205ff000000ff00ffff00ff00ff0000ff',
     '101': false,
     '102': 0,
     '104': 0,
     '105': 0,
     '106': 2332 } }
```

Unfortunately not work...
