### ISSUE TITLE
Request support for Automat-ON AUT000014 7 channel underfloor heating controller

### ISSUE THREAD

**Issue by convicte** [make-all/tuya-local#1348]
# Log Message

```log
Device matches logicom_powerstrip with quality of 67%. DPS: {"updated_at": 1701085639.925399, "1": false, "2": false, "3": true, "4": false, "5": false, "6": false, "7": false, "9": 0, "10": 0, "11": 0, "12": 0, "13": 0, "14": 0, "15": 0, "38": "off"}
```

There was a very long list of 'matched' devices, since this is a rather simple ON/OFF controller with 7 channels.
I chose a random smart powerstrip, but please let me know if you'd like a different log for a more matching device.

# Information about DPS mappings

```json
  "result": {
    "model": 
"{\"modelId\":\"000002zkxl\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"149\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"switch_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"149\"},\"name\":\"开关2\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"switch_3\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"149\"},\"name\":\"开关3\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"switch_4\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"149\"},\"name\":\"开关4\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"switch_5\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"145\"},\"name\":\"开关5\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"switch_6\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"145\"},\"name\":\"开关6\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"switch_usb1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"145\"},\"name\":\"USB1开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"开关1倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"countdown_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"开关2倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"countdown_3\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"开关3倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"countdown_4\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"128\"},\"name\":\"开关4倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"countdown_5\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"开关5倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"countdown_6\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"开关6倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"countdown_usb1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"128\"},\"name\":\"USB1倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"640\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"range\":[\"off\",\"on\",\"memory\"],\"type\":\"enum\",\"typeDefaultValue\":\"off\"}}]}]}"
  },
  "success": true,
  "t": 1701085980631,
  "tid": "837fe9358d1b11eea1f1a2b59ef48e62"
  
```

# Product ID

```json
      "category": "pc",
      "model": "SC-7CH",
      "name": "Smart Controller 2",
      "product_id": "7w1gnppunpyev9tj",
      "product_name": "Smart controller",
      "sub": false,
      "icon": "smart/icon/ay1575900695654gihsz/16398522125b09390c605.jpg",
 ```

# Information about how the device functions

WiFi underfloor heating controller - 7 zones
The intelligent Wi-Fi floor heating controller allows you to control the operation of the floor heating system. Thanks to wireless cooperation with temperature sensors located in individual rooms, the Wi-Fi controller allows for separate regulation of each of the heating loops. 

https://a.allegroimg.com/s720/11c5ed/d1c35f5f4e1790f8298f4e3083ec/Underfloor-heating-controller-WiFi-7-zones-Heating-Surface-1000-m2

https://allegro.pl/oferta/sterownik-ogrzewania-podlogowego-wifi-7-stref-11011325594 (in ENG)
https://sklep.automat-on.pl/Sterownik_ogrzewania_podlogowego_WiFi_7_stref.html (in POL)
https://sklep.automat-on.pl/userdata/public/assets/Instrukcje/Instrukcja_montazu_sterownika_ogrzewania_podlogowego_WiFi-min.pdf (in POL)
https://sklep.automat-on.pl/userdata/public/assets/Instrukcje/Instrukcja_aplikacji_sterownika_ogrzewania_podlogowego_WiFi-min.pdf (in POL)

**Comment by convicte** [comment]
In principle, it's a rather simple 7 channel ON/OFF controller, with some mostly irrelevant timer integrations via SmartLife App.

My biggest problem is that using the cloud integration, I am getting idiosyncratic issues where the given channel is not getting switched OFF when HA tells it to. Since my HA instance receives an OFF report somehow, it thinks it's OFF while the room is getting blasted with excess heat because the device did not get an OFF signal from the cloud or maybe even the cloud didn't recognize the OFF from HA.

I am hoping the local integration will resolve this concern.

![image](https://github.com/make-all/tuya-local/assets/78666770/1122587b-0d5c-4bc5-a403-d4be4c8006e6)
![image](https://github.com/make-all/tuya-local/assets/78666770/c2a94cac-5f3c-4e04-822f-f5db9473859a)
![image](https://github.com/make-all/tuya-local/assets/78666770/2ecc8c30-a972-4b33-8f32-fc18fdcfcc65)

**Comment by convicte** [comment]
Thank you for a quick review of the information, @make-all !!

What is even more annoying is that there seem to be ghost cloud2cloud 'turn_ON' published messages which didn't come from HA and I have no clue where they came from:
![image](https://github.com/make-all/tuya-local/assets/78666770/05c49d9e-4145-4b5b-8ff9-0f97f100451e)

![image](https://github.com/make-all/tuya-local/assets/78666770/eb88205d-16ea-45bc-ad1a-fc53ca1b3658)
There is nothing that should have switched it on at 14:42....

**Comment by convicte** [comment]
@make-all ,
If I am not mistaken, it seems that this device is following a very similar scheme as all these devices:
https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/qnect_usb_powerstrip.yaml
https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/smart_powerstrip.yaml
wish just 7 'switches' for each circuit and a timer.

If I am not mistaken, using the collected logs, I could modify these configs to follow my devices' schema.
Would that speed up the implementation and if yes, would you like me to drop the '.yaml' here?

**Comment by convicte** [comment]
I took a stab at it and arrived at a working configuration below.

The timer integration is a bit clunky, since the values in minutes are a selector, that counts down in minute increments - so it's sometimes 0.6666(...) or 0.3333(...) in perpetuity. 

![image](https://github.com/make-all/tuya-local/assets/78666770/6d662f23-0523-479f-b315-771b56bb0fd6)

This is however because there isn't a separate DPS for a time sensor, so I guess that is the best we can expect.

I'd appreciate pointers if this can be edited to include a timer selector and then when to start it and a timer clear option.
Though for the moment it works just fine.

```yaml
name: Automat-ON AUT000014 underfloor heating controller
products:
  - id: 7w1gnppunpyev9tj
    name: Smart controller
primary_entity:
  entity: switch
  name: Switch 1
  class: switch
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: switch
    name: Switch 2
    class: switch
    dps:
      - id: 2
        type: boolean
        name: switch
  - entity: switch
    name: Switch 3
    class: switch
    dps:
      - id: 3
        type: boolean
        name: switch
  - entity: switch
    name: Switch 4
    class: switch
    dps:
      - id: 4
        type: boolean
        name: switch
  - entity: switch
    name: Switch 5
    class: switch
    dps:
      - id: 5
        type: boolean
        name: switch
  - entity: switch
    name: Switch 6
    class: switch
    dps:
      - id: 6
        type: boolean
        name: switch
  - entity: switch
    name: Switch 7
    class: switch
    dps:
      - id: 7
        type: boolean
        name: switch
  - entity: number
    name: Timer 1
    category: config
    icon: "mdi:timer"
    dps:
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: Timer 2
    category: config
    icon: "mdi:timer"
    dps:
      - id: 10
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: Timer 3
    category: config
    icon: "mdi:timer"
    dps:
      - id: 11
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: Timer 4
    category: config
    icon: "mdi:timer"
    dps:
      - id: 12
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: Timer 5
    category: config
    icon: "mdi:timer"
    dps:
      - id: 13
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: Timer 6
    category: config
    icon: "mdi:timer"
    dps:
      - id: 14
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: Timer 7
    category: config
    icon: "mdi:timer"
    dps:
      - id: 15
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: select
    name: Power on state
    icon: "mdi:toggle-switch"
    category: config
    dps:
      - id: 38
        type: string
        name: option
        mapping:
          - dps_val: "off"
            value: "Off"
          - dps_val: "on"
            value: "On"
          - dps_val: "memory"
            value: Last state
            
```
