### ISSUE TITLE
Request support for PA 210VW gas monitor

### ISSUE THREAD

**Issue by DominikWrobel** [make-all/tuya-local#1353]
Information about DPS mappings:

```
{
  "result": {
    "properties": [
      {
        "code": "gas_sensor_state",
        "custom_name": "",
        "dp_id": 1,
        "time": 1695822792312,
        "value": "normal"
      },
      {
        "code": "gas_sensor_value",
        "custom_name": "",
        "dp_id": 2,
        "time": 1695823286019,
        "value": 0
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 11,
        "time": 1695822792312,
        "value": 0
      },
      {
        "code": "muffling",
        "custom_name": "",
        "dp_id": 16,
        "time": 1695822792312,
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1701188775612,
  "tid": "da231ef88e0a11eeb675fa6037e836b7"
}
```

Product ID:

```
products:
  - id: sclatjo1jqscmwwe
    name: PA-210WV
```

My yaml proposal:

```
name: Gas leak detector
products:
  - id: sclatjo1jqscmwwe
    name: PA-210WV
primary_entity:
  entity: sensor
  name: Gas leak
  category: diagnostic
  dps:
    - id: 2
      type: integer
      name: sensor
      unit:  "%LEL"
      class: measurement
    - id: 1
      type: string
      name: gas_state
secondary_entities:
  - entity: switch
    name: Silent
    category: config
    dps:
      - id: 16
        type: boolean
        name: switch
  - entity: binary_sensor
    name: Gas sensor fault
    class: gas
    category: diagnostic
    dps:
      - id: 11
        type: string
        name: sensor
        mapping:
          - dps_val: alarm
            value: true
          - value: false
```
Info about the device: [https://pl.aliexpress.com/i/4001159493955.html?gatewayAdapt=glo2pol](url)
