### ISSUE TITLE
Request support for Heater888 / QH-GD Elegant Serie verplaatsbaar infraroodpaneel 450Watt

### ISSUE THREAD

**Issue by mrtn1988** [make-all/tuya-local#1354]
# Log Message

```
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local (documentation, issues)
First occurred: 20:25:49 (1 occurrences)
Last logged: 20:25:49

Device matches feit_dimmer with quality of 38%. DPS: {"updated_at": 1701199543.908843, "1": true, "2": 25, "3": 21, "7": false, "11": "standby", "19": "cancel", "20": 0, "21": 0}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004rcx2\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":
[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"name\":\"目标温度\",\"typeSpec\":{\"max\":45,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"℃\"}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"name\":\"当前温度\",\"typeSpec\":{\"max\":50,\"min\":-20,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-20,\"unit\":\"℃\"}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"eco\",\"description\":\"\",\"name\":\"ECO模式\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"name\":\"童锁\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"\",\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"heating\",\"standby\"],\"type\":\"enum\",\"typeDefaultValue\":\"heating\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\",\"7h\",\"8h\",\"9h\",\"10h\",\"11h\",\"12h\",\"13h\",\"14h\",\"15h\",\"16h\",\"17h\",\"18h\",\"19h\",\"20h\",\"21h\",\"22h\",\"23h\",\"24h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"\",\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"max\":1440,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"min\"}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"motor_fault\",\"sensor_fault\",\"ov_cr\"],\"maxlen\":2,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  },
  "success": true,
  "t": 1701198976397,
  "tid": "9a3b2a918e2211ee805782e0b6121b90"
}
```

# Product ID
```
{
  "result": [
    {
      "active_time": 1701032420,
      "category": "qn",
      "create_time": 1700914915,
      "custom_name": "Infrarood",
      "icon": "smart/icon/ay1562052728792FvCry/b099a62badb82fa269d0de7f009164ad.jpg",
      "id": "**REDACTED**",
      "ip": "**REDACTED**",
      "is_online": true,
      "lat": "**REDACTED**",
      "local_key": "**REDACTED**",
      "lon": "**REDACTED**",
      "model": "Heater888",
      "name": "Heater888",
      "product_id": "4iuq3mlns7b2zi7q",
      "product_name": "Heater888",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1701152270,
      "uuid": "**REDACTED**"
    }
  ],
  "success": true,
  "t": 1701199040263,
  "tid": "c057bd928e2211eea1f1a2b59ef48e62"
}
```

# Information about how the device functions
https://www.infraroodverwarmingstore.nl/wifi-remote-control-elegant-verplaatsbaar-infraroo.html

```
{
  "result": {
    "category": "qn",
    "functions": [
      {
        "code": "switch",
        "desc": "switch",
        "name": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "temp set",
        "name": "temp set",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":10,\"max\":45,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mode_eco",
        "desc": "mode eco",
        "name": "mode eco",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "lock",
        "desc": "lock",
        "name": "lock",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_set",
        "desc": "countdown set",
        "name": "countdown set",
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\"]}"
      }
    ]
  },
  "success": true,
  "t": 1701199663411,
  "tid": "33c8e70b8e2411ee805782e0b6121b90"
}
```
# Device control - Query Properties
```
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1701198515770,
        "value": true
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 2,
        "time": 1701194545658,
        "value": 25
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 3,
        "time": 1701199397303,
        "value": 21
      },
      {
        "code": "eco",
        "custom_name": "",
        "dp_id": 6,
        "time": 1701111888434,
        "value": false
      },
      {
        "code": "child_lock",
        "custom_name": "",
        "dp_id": 7,
        "time": 1701194545741,
        "value": false
      },
      {
        "code": "work_state",
        "custom_name": "",
        "dp_id": 11,
        "time": 1701194545700,
        "value": "standby"
      },
      {
        "code": "countdown_set",
        "custom_name": "",
        "dp_id": 19,
        "time": 1701194545723,
        "value": "cancel"
      },
      {
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 20,
        "time": 1701194545754,
        "value": 0
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 21,
        "time": 1701194545782,
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1701199753867,
  "tid": "69b21f668e2411ee82d73e55532a4cc5"
}
```

# My own attempt:

```
name: QHGD Elegant Serie
products:
  - id: 4iuq3mlns7b2zi7q
    name: Heater888
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: true
          value: heat
          icon: "mdi:radiator"
        - dps_val: false
          value: "off"
          icon: "mdi:radiator-disabled"
    - id: 2
      name: temperature
      type: integer
      range:
        min: 10
        max: 45
    - id: 3
      name: current_temperature
      type: integer
    - id: 6
      name: preset_mode
      type: boolean
      mapping:
        - dps_val: false
          value: comfort
        - dps_val: true
          value: eco   
          
secondary_entities:
  - entity: lock
    name: Child lock
    icon: "mdi:hand-back-right-off"
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
  - entity: binary_sensor
    name: Fault
    class: problem
    category: diagnostic
    dps:
      - id: 21
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
```
