### ISSUE TITLE
Request support for (See Attached YML) - Geeni GN-BW233 / GN-BW230

### ISSUE THREAD

**Issue by fireheadman** [make-all/tuya-local#1360]
Please see attached YML file, Took advice of Beared Tinker and created the configuration and tested it.

# Log Message

```
No Logs

```

# Information about DPS mappings

```
3 DPs, listed in YML
```

# Product ID

3 Product IDs that all behave the same way.
hvfqgkigk9nj0p6p
41xqxqiflb6lqaqv
gbi4ljmlyrxx23mz

</div>

</body>

</html>

# Information about how the device functions

**Comment by fireheadman** [comment]
```
homeassistant:/config/custom_components/tuya_local/devices# cat geeni_edison_globe_wifi.yaml
name: Geeni LUX Edison lightbulb
products:
  - id: hvfqgkigk9nj0p6p
    name: GN-BW223-999
    manufacturer: Geeni
  - id: 41xqxqiflb6lqaqv
    name: GN-BW223-999
    manufacturer: Geeni
  - id: gbi4ljmlyrxx23mz
    name: GN-BW230-999
    manufacturer: Geeni
primary_entity:
  entity: light
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      name: brightness
      type: integer
      range:
        min: 25
        max: 255
    - id: 3
      name: color_temp
      type: integer
      range:
        min: 0
        max: 255
      mapping:
        - target_range:
            min: 2700
            max: 6500
```



![image](https://github.com/make-all/tuya-local/assets/19847195/0c8097ad-f521-479c-989d-3f2cc23f5d63)
