### ISSUE TITLE
Yealink smart fan not found

### ISSUE THREAD

**Issue by sudo-nitz** [make-all/tuya-local#1389]
This form is for reporting bugs.  If you have encountered a bug, you should
generally have some log messages or device diagnostics to show something is
going wrong.  If your problem is more of a question or a request for help,
then [Discussions](https://github.com/make-all/tuya-local/discussions) is
probably a more suitable venue.

**Describe the bug**
I made a YAML configuration for new device - Yealink Smart Fan (KH-SY2626):

```
name: Yealink fan
products:
  - id: t5nfkruajk3rl4fq
    name: Yealink Smart KH-SY2626
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: "fresh"
          value: "Świeży"
        - dps_val: "nature"
          value: "Naturalny"
        - dps_val: "smart"
          value: "Inteligentny"
        - dps_val: "sleep"
          value: "Uśpienie"
    - id: 3
      type: integer
      name: speed
      range:
        min: 1
        max: 15
      mapping:
        - scale: 0.15
    - id: 5
      type: boolean
      name: oscillate
secondary_entities:
  - entity: switch
    name: Light
    icon: "mdi:lightbulb"
    category: config
    dps:
      - id: 15
        type: boolean
        name: switch
  - entity: switch
    name: Beep
    icon: "mdi:volume-high"
    category: config
    dps:
      - id: 13
        type: boolean
        name: switch
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 22
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "wyłączony"
            icon: "mdi:timer-cancel"
          - dps_val: "1h"
            value: "1 godzina"
            icon: "mdi:timer-play"
          - dps_val: "2h"
            value: "2 godziny"
            icon: "mdi:timer-play"
          - dps_val: "3h"
            value: "3 godziny"
            icon: "mdi:timer-play"
          - dps_val: "4h"
            value: "4 godziny"
            icon: "mdi:timer-play"
          - dps_val: "5h"
            value: "5 godzin"
            icon: "mdi:timer-play"
          - dps_val: "6h"
            value: "6 godzin"
            icon: "mdi:timer-play"
  - entity: sensor
    category: diagnostic
    class: temperature
    dps:
      - id: 21
        type: integer
        name: sensor
        unit: "°C"
        class: measurement
```

Based on output from Tuya IoT:

`{ "result": { "model": "{\"modelId\":\"000002fm9b\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"风扇开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"fresh nature smart sleep\",\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"fresh\",\"nature\",\"smart\",\"sleep\"],\"type\":\"enum\",\"typeDefaultValue\":\"fresh\"}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"name\":\"风速\",\"typeSpec\":{\"max\":18,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"switch_horizontal\",\"description\":\"\",\"name\":\"左右摆风开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"fan_beep\",\"description\":\"\",\"name\":\"声音\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"light\",\"description\":\"\",\"extensions\":{\"attribute\":\"16\"},\"name\":\"灯光\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"name\":\"当前温度\",\"typeSpec\":{\"max\":50,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}}]}]}" }, "success": true, "t": 1701887243436, "tid": "193f4d48946511ee82d73e55532a4cc5" }`

Before version 2023.12.1 of Tuya Local I was able to assign a new device (Yealink Smart fan) as Yealink Smart fan, because it was listed as yealink_smart_fan.yaml (Tuya Local successfully compated device's mapping with prepared YAML configuration).

After update Tuya Local to version 2023.12.1 during adding a new device  (Yealink Smart fan) Tuya Local is no longer able to assign proper YAML configuration (yealink_smart_fan.yaml is not on the list)

Off course I've moved a configuration yealink_smart_fan.yaml to "devices" folder.

**To Reproduce**
Yealink Smart fan device.
Yealink Smart fan YAML configuration file.

**Expected behavior**
Successful assigning a Yealink Smart fan YAML configuration file to Yealink Smart fan device (to be listed during adding a new [device).

![yealink](https://github.com/make-all/tuya-local/assets/149267467/59253d8f-fb1a-410e-b887-98dd41db437f)

**Additional context**
I think it's related with new interpretation of "switch" entity in latests version of Home Assistant.

If the bug involves a device, then please include device diagnostics from
Settings / Devices & Services / Tuya Local (your device) / "1 device"

Please check if there are messages from Tuya Local in the Home
Assistant log (Settings / System / Logs), and include those too.
