### ISSUE TITLE
Request support for Smartlock K7 

### ISSUE THREAD

**Issue by phid78** [make-all/tuya-local#1391]
# Log Message

```
Device matches None with quality of 0%. DPS: {"updated_at": 1701193180.4004343, "9": 26}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004eppn\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"unlock_fingerprint\",\"description\":\"【可选】指纹在门锁上录入，录入完成后由硬件分配id，发生指纹解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1344\"},\"name\":\"指纹解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"unlock_password\",\"description\":\"【可选】普通密码（非临时密码）在门锁上录入，录入完成后由硬件分配id，发生普通密码解锁后，门锁将上报该dp点。普通密码指在门锁硬件上创建的密码，不包含通过app创建的临时密码。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1344\"},\"name\":\"普通密码解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"unlock_temporary\",\"description\":\"【可选】临时密码与普通密码进行区分，临时密码指由app创建的密码，临时密码可以具备准确的效期。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-shoushimima\",\"attribute\":\"1344\"},\"name\":\"临时密码解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"unlock_card\",\"description\":\"【可选】卡片在门锁上录入，录入完成后由硬件分配id，发生卡片解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1344\"},\"name\":\"卡片解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"unlock_face\",\"description\":\"【可选】人脸在门锁上录入，录入完成后由硬件分配id，发生人脸解锁后，门锁将上报该dp点。请用记录型上报\",\"extensions\":{\"iconName\":\"icon-dp_smile\",\"attribute\":\"1344\"},\"name\":\"人脸识别解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"unlock_key\",\"description\":\"【可选】如硬件能检测出机械钥匙开门，则固定上报 dp值为1，表示发生了机械钥匙开门。该开门记录请有记录型数据上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1344\"},\"name\":\"钥匙解锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"alarm_lock\",\"description\":\"【必选】0=试错告警、1=试错告警、2=试错报告警、3=试错告警、4=假锁（锁舌卡住）、5=高温告警、6=超时未关门、7=电子锁舌未弹出、8=防撬告警 、9=钥匙插入、10=低电告警、11=电量耗尽告警、12=震动告警、13=布防告警、14=逗留抓拍、15=门铃呼叫\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"attribute\":\"1344\"},\"name\":\"告警\",\"typeSpec\":{\"range\":[\"wrong_finger\",\"wrong_password\",\"wrong_card\",\"wrong_face\",\"tongue_bad\",\"too_hot\",\"unclosed_time\",\"tongue_not_out\",\"pry\",\"key_in\",\"low_battery\",\"power_off\",\"shock\",\"defense\",\"stay_alarm\",\"doorbell\"],\"type\":\"enum\",\"typeDefaultValue\":\"wrong_finger\"}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"unlock_request\",\"description\":\"【可选】如要使用远处开门功能，该dp点必选。门锁上报远程开门请求，需要硬件主动触发。\\n门锁本地上报远程开门请求时，携带x秒倒计时，只有在x秒内才能做出响应，点击允许，门锁将会解锁。可以x小于等于90。；当门锁被远程开门同意，或者拒绝了，将该字段的值改为0，面板将不会闪烁\",\"extensions\":{\"attribute\":\"1344\"},\"name\":\"远程开门请求倒计时\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"arming_switch\",\"description\":\"【注意】该功能暂未开发\",\"extensions\":{\"attribute\":\"1344\"},\"name\":\"布防开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"residual_electricity\",\"description\":\"【可选，但必须二选一】电量值和电量状态，二选一。上报电量数值\",\"extensions\":{\"attribute\":\"1344\"},\"name\":\"剩余电量\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"unlock_app\",\"description\":\"【可选】当发生app远程开门的事件后，门锁上报远程开门的记录。使用记录型数据上报\",\"extensions\":{\"iconName\":\"icon-shouji\",\"attribute\":\"1344\"},\"name\":\"App远程解锁\\twifi门锁\",\"typeSpec\":{\"max\":999,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":16,\"accessMode\":\"ro\",\"code\":\"hijack\",\"description\":\"【可选】该功能默认不需要硬件实现，门锁不用做劫持判断，只要在app上标记解锁id即可\",\"extensions\":{\"iconName\":\"icon-baojing\",\"attribute\":\"1344\"},\"name\":\"劫持告警\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"doorbell\",\"description\":\"【可选】门锁硬件上如带有门铃功能，点击后，将会触发一次门铃呼叫通知到云端。建议，连续的门铃呼叫，只触发一次门铃呼叫上报。上报后，将在app保留记录，并可以触发push\",\"extensions\":{\"iconName\":\"icon-a_power\",\"attribute\":\"1344\"},\"name\":\"门铃呼叫\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":25,\"accessMode\":\"ro\",\"code\":\"update_all_finger\",\"description\":\"【可选】满足以下所有条件时，选择dp点。\\n1、门锁具备指指纹解锁的方式\\n2、门锁能够通过网络，将本地添加的解锁方式同步到服务器\\n使用方式：当门锁本地的指纹解锁方式发生变化，新增/删除，则触发同步所有指纹的dp，将门锁本地所有的指纹解锁id同步到云端注意：每次向上同步的时候，需要使用全量同步，把更新后本地所具备的所有的id都同步到云端\",\"extensions\":{\"iconName\":\"icon-dp_fly\",\"attribute\":\"1376\"},\"name\":\"同步所有指纹编号\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":26,\"accessMode\":\"ro\",\"code\":\"update_all_password\",\"description\":\"【可选】满足以下所有条件时，选择dp点。\\n1、门锁具备密码解锁的方式\\n2、门锁能够通过网络，将本地添加的解锁方式同步到服务器\\n3、此处所指的密码是在门锁上创建的普通的密码，不包括通过app创建的临时密码\\n使用方式：当门锁本地的密码解锁方式发生变化，新增/删除，则触发同步所有密码的dp，将门锁本地所有的密码解锁id同步到云端注意：每次向上同步的时候，需要使用全量同步，把更新后本地所具备的所有的id都同步到云端\",\"extensions\":{\"iconName\":\"icon-dp_fly\",\"attribute\":\"1376\"},\"name\":\"同步所有密码编号\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":27,\"accessMode\":\"ro\",\"code\":\"update_all_card\",\"description\":\"【可选】满足以下所有条件时，选择dp点。\\n1、门锁具备指卡片解锁的方式\\n2、门锁能够通过网络，将本地添加的解锁方式同步到服务器\\n使用方式：当门锁本地的卡片解锁方式发生变化，新增/删除，则触发同步所有卡片的dp，将门锁本地所有的卡片解锁id同步到云端注意：每次向上同步的时候，需要使用全量同步，把更新后本地所具备的所有的id都同步到云端\",\"extensions\":{\"iconName\":\"icon-dp_fly\",\"attribute\":\"1376\"},\"name\":\"同步所有卡编号\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":28,\"accessMode\":\"ro\",\"code\":\"update_all_face\",\"description\":\"【可选】满足以下所有条件时，选择dp点。\\n1、门锁具备指人脸解锁的方式\\n2、门锁能够通过网络，将本地添加的解锁方式同步到服务器\\n使用方式：当门锁本地的人脸解锁方式发生变化，新增/删除，则触发同步所有人脸的dp，将门锁本地所有的人脸解锁id同步到云端注意：每次向上同步的时候，需要使用全量同步，把更新后本地所具备的所有的id都同步到云端\",\"extensions\":{\"iconName\":\"icon-dp_fly\",\"attribute\":\"1376\"},\"name\":\"同步所有人脸编号\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":31,\"accessMode\":\"ro\",\"code\":\"update_all_fin_vein\",\"description\":\"【可选】满足以下所有条件时，选择dp点。\\n1、门锁具备指静脉解锁的方式\\n2、门锁能够通过网络，将本地添加的解锁方式同步到服务器\\n使用方式：当门锁本地的指静脉解锁方式发生变化，新增/删除，则触发同步所有指静脉的dp，将门锁本地所有的指静脉解锁id同步到云端\",\"extensions\":{\"iconName\":\"icon-dp_fly\",\"attribute\":\"1376\"},\"name\":\"同步所有指静脉编号\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":32,\"accessMode\":\"ro\",\"code\":\"unlock_offline_pd\",\"description\":\"【可选】该算法由涂鸦实现，使用离线密码开门成功后，进行上报，开门记录显示密码和解锁时间\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1344\"},\"name\":\"离线密码解锁上报\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":33,\"accessMode\":\"ro\",\"code\":\"unlock_offline_clear\",\"description\":\"【可选】该算法由涂鸦实现。在门锁上输入离线清空码后，对应密码被清空，清空记录上报。\",\"extensions\":{\"iconName\":\"icon-dp_upload\",\"attribute\":\"1344\"},\"name\":\"离线密码清空上报\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":49,\"accessMode\":\"rw\",\"code\":\"remote_no_pd_setkey\",\"description\":\"【可选】远程开门的新加密机制，该DP需要在配网的时候下发\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1376\"},\"name\":\"设置免密远程开门密钥\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":50,\"accessMode\":\"rw\",\"code\":\"remote_no_dp_key\",\"description\":\"【可选】远程开门的新加密机制，该DP需要在远程开门回复时同时发送\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1376\"},\"name\":\"新免密远程开门-带密钥\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":57,\"accessMode\":\"rw\",\"code\":\"lock_record\",\"description\":\"【可选】选择该DP后，设备关锁后，可上报关锁记录\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1344\"},\"name\":\"关锁记录\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":60,\"accessMode\":\"rw\",\"code\":\"local_capacity_link\",\"description\":\"【可选】当硬件本地存在能力需要和开门方式进行关联时，勾选该功能。如拍照或拍视频需要和开门方式进行关联，将通过该DP下发：关联功能+开门方式类型+开门方式ID\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1344\"},\"name\":\"关联本地能力\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":70,\"accessMode\":\"rw\",\"code\":\"lock_local_record\",\"description\":\"【可选】门锁本地的任何操作记录上报至云端，云端记录显示，用于374认证等场景\",\"extensions\":{\"iconName\":\"icon-dp_book\",\"attribute\":\"96\"},\"name\":\"门锁本地记录\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}}]}]}"
  },
  "success": true,
  "t": 1702143624656,
  "tid": "087f9e2f96ba11eeb675fa6037e836b7"
}
```

{
  "result": {
    "properties": [
      {
        "code": "unlock_fingerprint",
        "custom_name": "",
        "dp_id": 1,
        "time": 1702126373000,
        "value": 1
      },
      {
        "code": "unlock_password",
        "custom_name": "",
        "dp_id": 2,
        "time": 1695739562021,
        "value": 0
      },
      {
        "code": "unlock_temporary",
        "custom_name": "",
        "dp_id": 3,
        "time": 1696013459000,
        "value": 909
      },
      {
        "code": "unlock_card",
        "custom_name": "",
        "dp_id": 5,
        "time": 1700726125000,
        "value": 2
      },
      {
        "code": "unlock_face",
        "custom_name": "",
        "dp_id": 6,
        "time": 1695739562021,
        "value": 0
      },
      {
        "code": "unlock_key",
        "custom_name": "",
        "dp_id": 7,
        "time": 1695739562021,
        "value": 0
      },
      {
        "code": "alarm_lock",
        "custom_name": "",
        "dp_id": 8,
        "time": 1699288279000,
        "value": "wrong_password"
      },
      {
        "code": "unlock_request",
        "custom_name": "",
        "dp_id": 9,
        "time": 1702058182685,
        "value": 0
      },
      {
        "code": "arming_switch",
        "custom_name": "",
        "dp_id": 10,
        "time": 1695739562021,
        "value": false
      },
      {
        "code": "residual_electricity",
        "custom_name": "",
        "dp_id": 12,
        "time": 1702126396263,
        "value": 40
      },
      {
        "code": "unlock_app",
        "custom_name": "",
        "dp_id": 15,
        "time": 1697990746000,
        "value": 0
      },
      {
        "code": "hijack",
        "custom_name": "",
        "dp_id": 16,
        "time": 1695739562021,
        "value": false
      },
      {
        "code": "doorbell",
        "custom_name": "",
        "dp_id": 19,
        "time": 1695739562021,
        "value": false
      },
      {
        "code": "update_all_finger",
        "custom_name": "",
        "dp_id": 25,
        "time": 1695739568948,
        "value": "AQI="
      },
      {
        "code": "update_all_password",
        "custom_name": "",
        "dp_id": 26,
        "time": 1699288411235,
        "value": "AQg="
      },
      {
        "code": "update_all_card",
        "custom_name": "",
        "dp_id": 27,
        "time": 1696236884885,
        "value": "AQQ="
      },
      {
        "code": "update_all_face",
        "custom_name": "",
        "dp_id": 28,
        "time": 1695739562021
      },
      {
        "code": "update_all_fin_vein",
        "custom_name": "",
        "dp_id": 31,
        "time": 1695739562021
      },
      {
        "code": "unlock_offline_pd",
        "custom_name": "",
        "dp_id": 32,
        "time": 1695739562021
      },
      {
        "code": "unlock_offline_clear",
        "custom_name": "",
        "dp_id": 33,
        "time": 1695739562021
      },
      {
        "code": "remote_no_pd_setkey",
        "custom_name": "",
        "dp_id": 49,
        "time": 1695739568840,
        "value": "AAAB"
      },
      {
        "code": "remote_no_dp_key",
        "custom_name": "",
        "dp_id": 50,
        "time": 1695739562021
      },
      {
        "code": "lock_record",
        "custom_name": "",
        "dp_id": 57,
        "time": 1695739562021
      },
      {
        "code": "local_capacity_link",
        "custom_name": "",
        "dp_id": 60,
        "time": 1695739562021
      },
      {
        "code": "lock_local_record",
        "custom_name": "",
        "dp_id": 70,
        "time": 1695739562021
      }
    ]
  },
  "success": true,
  "t": 1702144579568,
  "tid": "41afb2b896bc11ee80beca3999a2877e"
}

# Product ID

{
  "result": [
    {
      "active_time": 1695739562,
      "category": "jtmspro",
      "create_time": 1695739562,
      "custom_name": "",
      "icon": "smart/program_category_icon/jtmspro.png",
      "id": "bf34ed5d83a03ab9a8bk8z",
      "ip": 
      "is_online": true,
      "lat": ,
      "local_key": ,
      "lon": ,
      "model": "",
      "name": "WifiSmartLock",
      "product_id": "umca8uiv2203ua3k",
      "product_name": "WBR3(TX全)智能门锁",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1696698853,
      "uuid": "36f1cb08193088e2"
    }
  ],
  "success": true,
  "t": 1702143731340,
  "tid": "4815f2fb96ba11ee937d6aa996d0d9e7"
}

# Information about how the device functions

https://www.alibaba.com/product-detail/Tediton-Tuya-WIFI-APP-Fingerprint-Smart_10000013113540.html

```
name: WifiSmartLock
icon: mdi:lock-smart
products:
  - id: umca8uiv2203ua3k
    name: WBR3 
    category : jtmspro
primary_entity:
  entity: lock
  dps:
    - id: 1
      name: unlock_fingerprint
      icon: mdi:fingerprint
      type: integer
      optional: true
      persist: false
    - id: 2
      name: unlock_password
      icon: mdi:keyboard
      type: integer
      optional: true
      persist: false
    - id: 3
      name: unlock_temp_pwd
      icon: mdi:keyboard-off
      type: integer
      optional: true
      persist: false
    - id: 5
      name: unlock_card
      icon: mdi:SmartCard
      type: integer
      optional: true
      persist: false
    - #id: 6
      #name: unlock_face
      #icon: mdi:FaceRecognition 
      #type: integer
      #optional: true
      #persist: false
    - id: 7 
      name: unlock_key
      icon: mdi:key_chain
      type: integer
      optional: true
      persist: false
    - id: 15 
      name: unlock_app
      icon: mdi:application
      type: integer
      optional: true
      persist: false
    - id: 9 
      name: request_unlock
      icon: mdi:LockQuestion
      type: integer
      optional: true
      persist: false
    - id: 32 
      name: unlock_offline_pd
      icon: mdi:LockOpenOutline
      type: integer
      optional: true
      persist: false
#   - id: 33 
  #   name: unlock_offline_clear
  #   icon: mdi:LockOffOutline
   #  type: integer
   #  optional: true
   #  persist: false
    - id: 57
      name: lock_record
      icon: mdi:clipboard-list
      type: string
      optional: true
    #- id: 70
      # name: lock_local_record
      # type: string
      # optional: true
secondary_entities:
  - entity: sensor
    class: battery
    category: diagnostic
    icon: mdi:BatteryHigh
    dps:
      - id: 12
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: wrong_finger
            icon: mdi:FingerprintOff
            value: true
          - dps_val: "0"
            value: true
          - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: wrong_password
          icon: mdi:NumericOff  
          value: true
        - dps_val: "1"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: wrong_card
          icon: mdi:CardBulletedOff          
          value: true
        - dps_val: "2"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: wrong_face
          icon: mdi:EmoticonPoopOutline
          value: true
        - dps_val: "3"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: tongue_bad
          icon: mdi:EmoticonTongue
          value: true
        - dps_val: "4"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: too_hot
          icon: mdi:FireCircle
          value: true
        - dps_val: "5"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: unclosed_time
          icon: mdi:TimerLockOpenOutline
          value: true
        - dps_val: "6"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: tongue_not_out
          icon: mdi:EmoticonTongueOutline
          value: true
        - dps_val: "7"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: pry
          icon: mdi:HammerScrewdriver
          value: true
        - dps_val: "8"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: key_in
          icon: mdi:ShieldKey
          value: true
        - dps_val: "9"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: low_battery
          icon: mdi:BatteryLow
          value: true
        - dps_val: "10"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: power_off
          icon: mdi:BatteryAlertVariantOutline
          value: true
        - dps_val: "11"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: shock
          icon: mdi:Hammer
          value: true
        - dps_val: "12"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: defense
          icon: mdi:ShieldAlert
          value: true
        - dps_val: "13"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: stay_alarm
          icon: mdi:MotionSensor
          value: true
        - dps_val: "14"
          value: true
        - value: false
  - entity: binary_sensor
    name: alarm_lock
    class: problem
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
        - dps_val: doorbell
          icon: mdi:Bell-alert
          value: true
        - dps_val: "15"
          value: true
        - value: false
  - entity: binary_sensor
    name: Duress
    class: safety
    category: diagnostic
    dps:
      - id: 16 
        type: boolean
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
  - entity: binary_sensor
    name: Doorbell
    class: sound
    icon: mdi:Bell
    category: diagnostic
    dps:
      - id: 19
        type: boolean
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false

```
