### ISSUE TITLE
Request support for [abir_x6_vacuum.yaml]

### ISSUE THREAD

**Issue by 10der** [make-all/tuya-local#1445]
Hi!
I am trying to add support to new device ABIR XS-X6
but i think what something miss :( 

got error what device is not support.

can you help me, please.

```
        "product_name": "XS-X6(\u516c\u7248)",
        "product_id": "g62fnprnafitqmqt",
```

```
    {
        "name": "[censored]",
        "id": "AAAAAAAAAA",
        "key": "XXXXXXXXXXXXX",
        "mac": "QQQQQQQQQQQ",
        "uuid": "EEEEEEEE",
        "sn": "TTTTTTTTTT",
        "category": "sd",
        "product_name": "XS-X6(\u516c\u7248)",
        "product_id": "g62fnprnafitqmqt",
        "biz_type": 18,
        "model": "",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1577167957623L2rTa/ca3fc7f4dcf880e99031dc8749f361e5.jpg",
        "mapping": {
            "2": {
                "code": "power_go",
                "type": "Boolean",
                "values": {}
            },
            "3": {
                "code": "mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "smart",
                        "wall_follow",
                        "spiral",
                        "chargego"
                    ]
                }
            },
            "4": {
                "code": "direction_control",
                "type": "Enum",
                "values": {
                    "range": [
                        "forward",
                        "backward",
                        "turn_left",
                        "turn_right",
                        "stop"
                    ]
                }
            },
            "5": {
                "code": "status",
                "type": "Enum",
                "values": {
                    "range": [
                        "standby",
                        "smart_clean",
                        "wall_clean",
                        "spot_clean",
                        "mop_clean",
                        "goto_charge",
                        "charging",
                        "charge_done",
                        "paused",
                        "cleaning",
                        "sleep"
                    ]
                }
            },
            "6": {
                "code": "electricity_left",
                "type": "Integer",
                "values": {
                    "unit": "%",
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "13": {
                "code": "seek",
                "type": "Boolean",
                "values": {}
            },
            "14": {
                "code": "suction",
                "type": "Enum",
                "values": {
                    "range": [
                        "quiet",
                        "normal",
                        "strong"
                    ]
                }
            },
            "15": {
                "code": "clean_record",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "16": {
                "code": "clean_area",
                "type": "Integer",
                "values": {
                    "unit": "\u33a1",
                    "min": 0,
                    "max": 9999,
                    "scale": 0,
                    "step": 1
                }
            },
            "17": {
                "code": "clean_time",
                "type": "Integer",
                "values": {
                    "unit": "\u5206",
                    "min": 0,
                    "max": 9999,
                    "scale": 0,
                    "step": 1
                }
            },
            "18": {
                "code": "fault",
                "type": "Bitmap",
                "values": {
                    "label": [
                        "edge_sweep",
                        "middle_sweep",
                        "left_wheel",
                        "right_wheel",
                        "garbage_box",
                        "land_check",
                        "collision"
                    ]
                }
            },
            "108": {
                "code": "cistern",
                "type": "Enum",
                "values": {
                    "range": [
                        "low",
                        "middle",
                        "high"
                    ]
                }
            },
            "105": {
                "code": "wake_up",
                "type": "Boolean",
                "values": {}
            }
        }
    }

```

```
name: Robot vacuum
products:
  - id: g62fnprnafitqmqt
    name: Abir X6
primary_entity:
  entity: vacuum
  dps:
    - id: 2
      type: boolean
      name: power
    - id: 3
      type: string
      name: mode
      mapping:
        - dps_val: smart
          value: smart
        - dps_val: wall_follow
          value: wall_follow
        - dps_val: spiral
          value: spiral
        - dps_val: chargego
          value: return_to_base
    - id: 4
      type: string
      name: direction_control
      optional: true
      mapping:
        - dps_val: foward
          value: forward
        - dps_val: backward
          value: reverse
        - dps_val: turn_left
          value: left
        - dps_val: turn_right
          value: right
        - dps_val: stop
          value: stop
    - id: 5
      type: string
      name: status
      mapping:
        - dps_val: standby
          value: standby
        - dps_val: smart_clean
          value: cleaning
        - dps_val: wall_clean
          value: cleaning
        - dps_val: spot_clean
          value: cleaning
        - dps_val: mop_clean
          value: cleaning
        - dps_val: goto_charge
          value: returning
        - dps_val: charging
          value: charging
        - dps_val: charge_done
          value: charged
        - dps_val: paused
          value: pause
        - dps_val: cleaning
          value: cleaning
        - dps_val: sleep
          value: sleep

    - id: 18
      type: bitfield
      name: fault
      mapping:
        - dps_val: 2
          value: edge_sweep
        - dps_val: 4
          value: middle_sweep
        - dps_val: 8
          value: left_wheel
        - dps_val: 16
          value: right_wheel
        - dps_val: 32
          value: garbage_box
        - dps_val: 64
          value: land_check
        - dps_val: 128
          value: collision

    - id: 108
      type: string
      name: cistern
      mapping:
        - dps_val: low
          value: low
        - dps_val: middle
          value: middle
        - dps_val: high
          value: high

    - id: 105
      type: boolean
      name: wake_up

secondary_entities:
  - entity: sensor
    class: battery
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: "%"
        class: measurement
```
