### ISSUE TITLE
Lefant M210P Vacuum - Mostly done

### ISSUE THREAD

**Issue by mrplow** [make-all/tuya-local#1467]
# Log Message
See attached
[home-assistant_tuya_local_2023-12-29T23-39-03.988Z.log](https://github.com/make-all/tuya-local/files/13796618/home-assistant_tuya_local_2023-12-29T23-39-03.988Z.log)

# Information about DPS mappings

I believe I've mapped everything that can be mapped, I got most of these values pocking around on the tuya api explorer and using tinytuya monitoring while pressing all the options in the tuya app.

Some DPSs don't seem to be able to be mapped into something useful:

- DPS 15 is the date a cleaning started that was completed with some extra into added to the end
  - 20231229153100300100006 is returned after running for 3 min and ending at Fri 29 Dec 2023 03:34:21 PM PST
  - I'm guessing it's YYYYMMDDHHMM<3 digits of minutes ran><3 digits of an unknown value><5 digits of total completed cleanings>
- DPS 19 this seems to only output once a cleaning cycle is started, not sure what it is
  - 'AQD/'
- DPS 106 seems to relate to the charging voltage and something else
  - idle and fully charged, right before starting a test vacuum:
    - 'charge VOL:13664'
  - start the smart clean, let it run for a few min
    - 'charge CUL:0211'
    - 'AdapterVol:15616_4'
    - 'charge CUL:0248'
    - 'AdapterVol:00372_3'
    - 'charge CUL:0258'
    - 'AdapterVol:00155_2'
    - 'charge CUL:0267'
    - 'AdapterVol:00146_1'
  - hit return to dock and it didn't update 106 unit it reached the dock
    - 'charge CUL:0144'
    - 'AdapterVol:18274_4'
    - 'charge CUL:0075'
    - 'AdapterVol:19236_3'
    - 'charge CUL:0071'
    - 'AdapterVol:19241_2'
    - 'charge CUL:0011'
    - 'AdapterVol:19257_1'
    - 'charge VOL:13225'
- DPS 107 seems to be some extra information about being charged? and wifi down (the wifi down is odd as the wifi is quite stable but I see that message whenever I start the cleaning)
  - idle and fully charged, right before starting a test vacuum:
    - 'Switch way:CHAR INTO0'
  - start the smart clean, let it run for a few min
    - 'Switch way:WIFI DOWN1'
  - hit return to dock and it immediately returned a 107
    - 'Switch way:AUTO DONE1'
  -  once docked
     - 'Switch way:CHAR INTO0'
- DPS 108 battery voltage as well as some collision detections?, the tuya app displays a map of generated cleaned areas and walls/objects - I thought this might build this map but it doesn't return enough information to rebuild anything useful
  - idle and fully charged, right before starting a test vacuum:
    - 'BatVol:13519'
  - start the smart clean, let it run for a few min
    - 'BatVol:13503'
    - 'BatVol:12933'
  - hit return to dock and it immediately returned a 108
    - 'BatVol:13139'
  - found the dock but not yet docked?
    - '108': 'OBS:3008_3129_3087 Cliff:3955_3841_0214 WALL:000_070'
  - another random sample of 108 from other tests but I didn't document it as well
    - 'sideB:276_067'

# Product ID

cgrfjjwmstsaemw8

# yaml

```yaml
name: Lefant vacuum
products:
  - id: cgrfjjwmstsaemw8
    name: Lefant M210P
primary_entity:
  entity: vacuum
  dps:
    - id: 1
      name: power
      type: boolean
    - id: 2
      name: activate
      type: boolean
    - id: 3
      name: status
      type: string
      mapping:
        - dps_val: standby
          value: standby
        - dps_val: smart
          value: smart
        - dps_val: wall_follow
          value: wall_follow
        - dps_val: spiral
          value: clean_spot
        - dps_val: chargego
          value: return_to_base
        - dps_val: random
          value: random
    - id: 4
      type: string
      name: direction_control
      optional: true
      mapping:
        - dps_val: forward
          value: forward
        - dps_val: backward
          value: backward
        - dps_val: turn_left
          value: left
        - dps_val: turn_right
          value: right
        - dps_val: stop
          value: stop
    - id: 5
      type: string
      name: status_message
      mapping:
        - dps_val: 0
          value: standby
        - dps_val: 1
          value: auto_cleaning
        - dps_val: 2
          value: wall_follow_cleaning
        - dps_val: 3
          value: spiral_cleaning
        - dps_val: 4
          value: finding_charger
        - dps_val: 5
          value: charging
        - dps_val: 6
          value: random_cleaning
        - dps_val: 7
          value: fully_charged
    - id: 13
      type: boolean
      name: locate
      optional: true
    - id: 15
      type: string
      name: cleaning_history
      readonly: true
    - id: 18
      type: integer
      name: current_error
      mapping:
        - dps_val: 0
          value: Normal
        - dps_val: 1
          value: Please check whether wheels tangled
        - dps_val: 2
          value: Please check if sides brushes are jammed
        - dps_val: 3
          value: Motor cooling error
        - dps_val: 4
          value: Please check if roller brush is jammed
        - dps_val: 5
          value: Please check if dust bin is installed correctly
        - dps_val: 6
          value: Undefined error
        - dps_val: 7
          value: Undefined error
        - dps_val: 8
          value: Front bumper error
        - dps_val: 9
          value: Please check if wheels are on the floor
        - dps_val: 10
          value: Please help me. I am stuck
        - dps_val: 11
          value: Battery low, Please recharge me
        - dps_val: 12
          value: Please use 19V, 0.6A adapter to charge
        - dps_val: 13
          value: Please check if wheels are on the floor
        - dps_val: 14
          value: Navigation failure. Please restart me
        - dps_val: 15
          value: Fail to upgrade in battery low status, please charge for a while and try again.
        - dps_val: 16
          value: MEMS Time Out
        - dps_val: 17
          value: Battery low, Please recharge me
        - dps_val: 18
          value: Please turn on the power switch for charging
        - dps_val: 19
          value: Undefined error
        - dps_val: 20
          value: Please put me back into the charging stand
        - dps_val: 21
          value: Please help me.I am stuck
        - dps_val: 22
          value: Please clean the dust on the shrapnel of this charging base, then go back to charge
    - id: 106
      type: string
      name: debug_dps_106
      readonly: true
    - id: 107
      type: string
      name: debug_dps_107
      readonly: true
    - id: 108
      type: string
      name: debug_dps_108
      readonly: true
secondary_entities:
  - entity: sensor
    name: Battery
    class: battery
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: sensor
    name: Clean area
    category: diagnostic
    icon: "mdi:floor-plan"
    dps:
      - id: 16
        type: integer
        name: sensor
        unit: m2
  - entity: sensor
    name: Clean time
    category: diagnostic
    class: duration
    icon: "mdi:clock-outline"
    dps:
      - id: 17
        type: integer
        name: sensor
        unit: min
  - entity: select
    name: Suction
    category: config
    dps:
      - id: 101
        type: string
        name: option
        mapping:
          - dps_val: low
            value: low
          - dps_val: nar
            value: middle
          - dps_val: high
            value: high
  - entity: select
    name: Sensitivity
    category: config
    dps:
      - id: 111
        type: string
        name: option
        mapping:
          - dps_val: low
            value: low
          - dps_val: mid
            value: normal
          - dps_val: high
            value: high
  - entity: switch
    name: Power boost
    category: config
    dps:
      - id: 112
        type: boolean
        name: switch
```
