### ISSUE TITLE
Star-Light Air Conditioner

### ISSUE THREAD

**Issue by tavicu** [make-all/tuya-local#147]
Hi,

I have an Air Conditioner made by Star-Light which works on WiFi with Tuya/SmartLife and it's sold in my country.

First I have checked and there is a 90% match with "TroniTechnik Hellnar Klimagerät". The most important differences are the min/max temperature (16/31) and that the step should be 0.5.

I also tried to find what other ids represent and I was able to find some.

I would like to create a PR and add the new device but first let me know if it's ok and if you consider I should change something.

I have created a new device with the file name `star_light_heatpump.yaml`. I would have called it `star_light_ac` but I don't see any file with `ac` in it.

And this content:
```
name: StarLight Heatpump
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: power
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
          icon_priority: 1
      hidden: true
    - id: 2
      name: temperature
      type: integer
      mapping:
        - scale: 10
          step: 5
          constraint: hvac_mode
          conditions:
            - dps_val: cold
              range:
                min: 160
                max: 310
            - dps_val: auto
              range:
                min: 160
                max: 310
            - dps_val: hot
              range:
                min: 160
                max: 310
            - dps_val: wet
              invalid: true
            - dps_val: wind
              invalid: true
    - id: 3
      name: current_temperature
      type: integer
    - id: 4
      name: hvac_mode
      type: string
      mapping:
        - dps_val: auto
          icon: "mdi:hvac"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: heat_cool
        - dps_val: cold
          icon: "mdi:snowflake"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: cool
        - dps_val: hot
          icon: "mdi:fire"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: heat
        - dps_val: wind
          icon: "mdi:fan"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
              value: "off"
            - dps_val: true
              value: fan_only
        - dps_val: wet
          icon: "mdi:water"
          icon_priority: 2
          constraint: power
          conditions:
            - dps_val: false
              value_redirect: power
            - dps_val: true
              value: dry
    - id: 5
      name: fan_mode
      type: string
    - id: 18
      name: unknown_18
      type: integer
    - id: 20
      name: unknown_20
      type: integer
    - id: 101
      name: unknown_101
      type: integer
    - id: 105
      name: sleep_mode
      type: string
    - id: 110
      name: unknown_110
      type: integer
    - id: 113
      name: up_down_flow_swing
      type: string
    - id: 114
      name: left_right_flow_swing
      type: string
    - id: 119
      name: unknown_119
      type: string
    - id: 120
      name: unknown_120
      type: string
    - id: 123
      name: unknown_123
      type: string
    - id: 125
      name: unknown_125
      type: string
    - id: 126
      name: up_down_flow_fixed
      type: string
    - id: 127
      name: left_right_flow_fixed
      type: string
    - id: 128
      name: unknown_128
      type: string
    - id: 129
      name: unknown_129
      type: string
    - id: 130
      name: maybe_eco_temp
      type: integer
    - id: 131
      name: unknown_131
      type: boolean
    - id: 132
      name: unknown_132
      type: boolean
    - id: 133
      name: unknown_133
      type: string
    - id: 134
      name: unknown_134
      type: string
```
