### ISSUE TITLE
[New device] Yealink Smart Fan KH-SY2626

### ISSUE THREAD

**Issue by sudo-nitz** [make-all/tuya-local#1474]
id: t5nfkruajk3rl4fq
 name: Yealink Smart KH-SY2626

Below configuration file:

```
name: Yealink fan
products:
  - id: t5nfkruajk3rl4fq
    name: Yealink Smart KH-SY2626
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: "fresh"
          value: "Fresh"
        - dps_val: "nature"
          value: "Nature"
        - dps_val: "smart"
          value: "Smart"
        - dps_val: "sleep"
          value: "Sleep"
    - id: 3
      type: integer
      name: speed
      range:
        min: 1
        max: 15
      mapping:
        - scale: 0.15
    - id: 5
      type: boolean
      name: oscillate
secondary_entities:
  - entity: switch
    name: Light
    icon: "mdi:lightbulb"
    category: config
    dps:
      - id: 15
        type: boolean
        name: switch
  - entity: switch
    name: Beep
    icon: "mdi:volume-high"
    category: config
    dps:
      - id: 13
        type: boolean
        name: switch
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 22
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "off"
            icon: "mdi:timer-cancel"
          - dps_val: "1h"
            value: "1 hour"
            icon: "mdi:timer-play"
          - dps_val: "2h"
            value: "2  hours"
            icon: "mdi:timer-play"
          - dps_val: "3h"
            value: "3 hours"
            icon: "mdi:timer-play"
          - dps_val: "4h"
            value: "4 hours"
            icon: "mdi:timer-play"
          - dps_val: "5h"
            value: "5 hours"
            icon: "mdi:timer-play"
          - dps_val: "6h"
            value: "6 hours"
            icon: "mdi:timer-play"
  - entity: sensor
    category: diagnostic
    class: temperature
    dps:
      - id: 21
        type: integer
        name: sensor
        unit: "°C"
        class: measurement
```

Configuration tested and fully working.
