### ISSUE TITLE
Request support for Taurus Agadir Connect

### ISSUE THREAD

**Issue by jedubois** [make-all/tuya-local#1478]
# Log Message

```
[custom_components.tuya_local.config_flow] Device matches wetair_wch750_heater with quality of 80%. DPS: {"updated_at": 1704221495.4797206, "1": true, "2": 23, "4": "CF", "7": false, "11": "standby", "19": "cancel", "20": 0, "21": 0, "101": "H2", "103": false}
```

# Information about DPS mappings

```
{
  "modelId": "000003g5ex",
  "services": [
    {
      "actions": [],
      "code": "",
      "description": "",
      "events": [],
      "name": "默认服务",
      "properties": [
        {
          "abilityId": 1,
          "accessMode": "rw",
          "code": "switch",
          "description": "",
          "extensions": {
            "iconName": "icon-dp_power2",
            "attribute": "1"
          },
          "name": "开关",
          "typeSpec": {
            "type": "bool",
            "typeDefaultValue": false
          }
        },
        {
          "abilityId": 2,
          "accessMode": "rw",
          "code": "temp_set",
          "description": "",
          "extensions": {
            "iconName": "icon-set",
            "attribute": "4"
          },
          "name": "目标温度",
          "typeSpec": {
            "max": 35,
            "min": 5,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 5,
            "unit": "℃"
          }
        },
        {
          "abilityId": 4,
          "accessMode": "rw",
          "code": "mode",
          "description": "",
          "extensions": {
            "iconName": "icon-dp_mode"
          },
          "name": "工作模式",
          "typeSpec": {
            "range": [
              "CF",
              "AF"
            ],
            "type": "enum",
            "typeDefaultValue": "CF"
          }
        },
        {
          "abilityId": 7,
          "accessMode": "rw",
          "code": "child_lock",
          "description": "",
          "extensions": {
            "iconName": "icon-dp_lock",
            "attribute": "4"
          },
          "name": "童锁",
          "typeSpec": {
            "type": "bool",
            "typeDefaultValue": false
          }
        },
        {
          "abilityId": 11,
          "accessMode": "ro",
          "code": "work_state",
          "description": "",
          "extensions": {
            "iconName": "icon-zhuangtai",
            "attribute": "128"
          },
          "name": "工作状态",
          "typeSpec": {
            "range": [
              "working",
              "standby"
            ],
            "type": "enum",
            "typeDefaultValue": "working"
          }
        },
        {
          "abilityId": 19,
          "accessMode": "rw",
          "code": "countdown_set",
          "description": "",
          "extensions": {
            "iconName": "icon-dp_time2",
            "attribute": "4"
          },
          "name": "倒计时",
          "typeSpec": {
            "range": [
              "cancel",
              "1h",
              "2h",
              "3h",
              "4h",
              "5h",
              "6h",
              "7h",
              "8h",
              "9h",
              "10h",
              "11h",
              "12h",
              "13h",
              "14h",
              "15h",
              "16h",
              "17h",
              "18h",
              "19h",
              "20h",
              "21h",
              "22h",
              "23h",
              "24h"
            ],
            "type": "enum",
            "typeDefaultValue": "cancel"
          }
        },
        {
          "abilityId": 20,
          "accessMode": "ro",
          "code": "countdown_left",
          "description": "",
          "extensions": {
            "iconName": "icon-dp_time2"
          },
          "name": "倒计时剩余时间",
          "typeSpec": {
            "max": 1440,
            "min": 0,
            "scale": 0,
            "step": 1,
            "type": "value",
            "typeDefaultValue": 0,
            "unit": "min"
          }
        },
        {
          "abilityId": 21,
          "accessMode": "ro",
          "code": "fault",
          "description": "",
          "extensions": {
            "iconName": "icon-baojing",
            "attribute": "128"
          },
          "name": "故障告警",
          "typeSpec": {
            "label": [
              "motor_fault"
            ],
            "maxlen": 1,
            "type": "bitmap",
            "typeDefaultValue": 0
          }
        },
        {
          "abilityId": 101,
          "accessMode": "rw",
          "code": "fan_mode",
          "description": "",
          "name": "风速模式",
          "typeSpec": {
            "range": [
              "H1",
              "H2",
              "H3"
            ],
            "type": "enum",
            "typeDefaultValue": "H1"
          }
        },
        {
          "abilityId": 103,
          "accessMode": "rw",
          "code": "night_mode",
          "description": "",
          "name": "夜间模式",
          "typeSpec": {
            "type": "bool",
            "typeDefaultValue": false
          }
        }
      ]
    }
  ]
}
```

# Product ID

        product_name: "Agadir Connect",
        product_id: "rs1azmhtak4bo0o5",

# Information about how the device functions

Product information and manual available at 
https://taurus-home.com/es-pt/products/agadir-connect-2000

# Working configuration

Below my (mostly) working configuration with the only caveat being I cannot get a new YAML file loaded by tuya-local/HA and the device appropriately detected / shown in the device options list. I worked around that for testing purposes by modifying an existing device file (wetair_wch750_heater.yml):

```
name: Taurus Agadir Connect
products:
  - id: rs1azmhtak4bo0o5
    name: "Agadir Connect"
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:radiator-disabled"
        - dps_val: true
          value: heat
          icon: "mdi:radiator"
      name: hvac_mode
    - id: 2
      type: integer
      range:
        min: 10
        max: 35
      mapping:
        - constraint: preset_mode
          conditions:
            - dps_val: AF
              invalid: true
      name: temperature
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: CF
          value: home
        - dps_val: AF
          value: away
    - id: 11
      type: string
      name: hvac_action
      mapping:
        - dps_val: working
          constraint: hvac_mode
          conditions:
            - dps_val: false
              value: "off"
            - dps_val: true
              value: heating
        - dps_val: standby
          constraint: hvac_mode
          conditions:
            - dps_val: false
              value: "off"
            - dps_val: true
              value: idle
    - id: 21
      type: bitfield
      name: fault_alarm
      readonly: true
secondary_entities:
  - entity: select
    name: "Power level"
    category: config
    icon: "mdi:thermometer"
    dps:
      - id: 101
        type: string
        name: option
        mapping:
          - dps_val: H1
            value: Low
          - dps_val: H2
            value: Medium
          - dps_val: H3
            value: High
  - entity: lock
    name: Child lock
    icon: "mdi:hand-back-right-off"
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
        optional: true
  - entity: select
    name: Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 19
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "Off"
          - dps_val: "1h"
            value: "1 hour"
          - dps_val: "2h"
            value: "2 hours"
          - dps_val: "3h"
            value: "3 hours"
          - dps_val: "4h"
            value: "4 hours"
          - dps_val: "5h"
            value: "5 hours"
          - dps_val: "6h"
            value: "6 hours"
          - dps_val: "7h"
            value: "7 hours"
          - dps_val: "8h"
            value: "8 hours"
          - dps_val: "9h"
            value: "9 hours"
          - dps_val: "10h"
            value: "10 hours"
          - dps_val: "11h"
            value: "11 hours"
          - dps_val: "12h"
            value: "12 hours"
          - dps_val: "13h"
            value: "13 hours"
          - dps_val: "14h"
            value: "14 hours"
          - dps_val: "15h"
            value: "15 hours"
          - dps_val: "16h"
            value: "16 hours"
          - dps_val: "17h"
            value: "17 hours"
          - dps_val: "18h"
            value: "18 hours"
          - dps_val: "19h"
            value: "19 hours"
          - dps_val: "20h"
            value: "20 hours"
          - dps_val: "21h"
            value: "21 hours"
          - dps_val: "22h"
            value: "22 hours"
          - dps_val: "23h"
            value: "23 hours"
          - dps_val: "24h"
            value: "24 hours"
  - entity: sensor
    category: diagnostic
    name: "Remaining time"
    class: duration
    icon: "mdi:timer-sand"
    dps:
      - id: 20
        type: integer
        name: sensor
        unit: min
  - entity: light
    name: "Display"
    category: config
    dps:
      - id: 103
        type: boolean
        name: switch
        default:
        mapping:
          - dps_val: false
            value: on
            icon: "mdi:led-variant-on"
          - dps_val: true
            value: off
            icon: "mdi:led-variant-off"
  - entity: binary_sensor
    name: Fault
    category: diagnostic
    class: problem
    dps:
      - id: 21
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: null
            value: false
          - value: true
```
