### ISSUE TITLE
Invert option for cover

### ISSUE THREAD

**Issue by tavicu** [make-all/tuya-local#148]
Hi.

I have some blind motors from Tuya and I have created a new device to integrate them.

The problem is that HA see the position of cover different than Tuya.

In HA position `0` means `closed` and `100` means `open`
In Tuya position `0` means `open` and `100` means `closed` (same behaviour as HomeKit)

To fix the display for the cover i've made an option to `invert` the position.

Here is the commit on the forked repo. https://github.com/tavicu/tuya-local/commit/4a24e8254268fc4f2f1be834d212ecc461597d76

Please let me know if you would like to integrate it into your plugin so I can make a pull request :)

The only downside of this is that the position slider will be also inverted. It will show 0% when it's closed and 100% when the blind is open. But setting the value with the slider will work correctly.
For me it was more important to have the arrows working and be displayed correctly!

**Comment by make-all** [comment]
I think the invert option can be made generic, and implemented in helpers/device_config.py rather than in generic/cover.py where it only applies to covers.  Making it apply directly at the value mapping stage will also fix the slider behaviour I think.

**Comment by make-all** [comment]
Sorry, it seems I hit the Close with Comment button by mistake.

**Comment by make-all** [comment]
A more general version of this support is released in 0.16.0

**Comment by tavicu** [comment]
Hei Jason,

Thank you for the reply and implementation.

The invert implementation in 0.16.0 looks good but there is one thing which i think it doesn't work at it should with the inverse.

And that think is the `is_closed` function (https://github.com/make-all/tuya-local/blob/454f960b0c97e79bff23b095c39160400ebdd0eb/custom_components/tuya_local/generic/cover.py#L108).

In the default state value == 0 means closed, in the invert it should be != 0 (https://github.com/tavicu/tuya-local/blob/master/custom_components/tuya_local/generic/cover.py#L163-L165)

Value 0 (from tuya) means the cover is open. Anything different than 0 should means it's closed.

**Comment by make-all** [comment]
I'm not sure I get what you are saying.  Is the range incorrect?  The implementation reverses the range so that in a range of 0 - 100, 100 is closed, and 0 is fully open.  In between those values, the cover will be partially open, so not closed.

**Comment by tavicu** [comment]
Hei.
I guess i've set a thinking ideea like "50% closed" so it should be "closed".
But as long as the Up (open) and Down (close) arrows from Home Assistant works as it should, the status it's not so important :D  

It is possible to also add a yaml for a new device?
Here is the config I have created and it's working:

Api response: (also, it doesn't matter the state of the shade, only the DPS 2 is changing.

`{'devId': '84076817a4e57c109892', 'dps': {'1': 'stop', '2': 0, '5': False, '7': 'opening'}}`

Also, it doesn't matter the state ot he shade, only the DPS 2 (position) is changing. DPS 7 (action) it always stay on `opening`. That's why I didn't map the DPS with the name `action`

```
name: Tuya Cover Blind
primary_entity:
  entity: cover
  class: blind
  dps:
    - id: 1
      name: control
      type: string
      mapping:
        - dps_val: open
          value: open
        - dps_val: close
          value: close
        - dps_val: stop
          value: stop
    - id: 2
      name: position
      type: integer
      range:
        min: 0
        max: 100
      mapping:
        - invert: true
    - id: 5
      name: control_back_mode
      type: boolean
    - id: 7
      name: work_state
      type: string
```
