### ISSUE TITLE
[New device] Support for iHunt Air Purifier 400

### ISSUE THREAD

**Issue by robex2005** [make-all/tuya-local#1485]
Hello, 

I customized a config file for supporting iHunt Air Purifier 400 (all controls are working!)

Below the yaml file (ihunt_air_purifier_400.yaml):

```
name: iHunt Air Purifier 400
products:
  - id: lf1ikizwmvevldbp
primary_entity:
  entity: switch
  icon: "mdi:air-purifier"
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: sensor
    class: pm25
    dps:
      - id: 2
        type: integer
        name: sensor
        class: measurement
        unit: ugm3       
  - entity: sensor
    name: Filter
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: "%"
  - entity: switch
    name: Ionizer
    icon: "mdi:atom-variant"
    category: config
    dps:
      - id: 6
        type: boolean
        name: switch
        mapping:
          - dps_val: true
          - dps_val: false
  - entity: lock
    name: Child lock
    category: config
    icon: "mdi:hand-back-right-off"
    dps:
      - id: 7
        type: boolean
        name: lock
  - entity: switch
    name: UV sterilization
    category: config
    icon: "mdi:sun-wireless"
    dps:
      - id: 9
        name: switch
        type: boolean
  - entity: sensor
    name: Filter hour left
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 16
        name: sensor
        type: integer
        unit: h
  - entity: button
    name: Filter reset
    category: diagnostic
    class: restart
    dps:
      - id: 11
        type: boolean
        name: button
  - entity: select
    name: Timer
    icon: "mdi:fan-clock"
    category: config
    dps:
      - id: 18
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "Cancel"
          - dps_val: "1h"
            value: "1 Hour"
          - dps_val: "2h"
            value: "2 Hour" 
          - dps_val: "3h"
            value: "3 Hour" 
          - dps_val: "4h"
            value: "4 Hour" 
          - dps_val: "5h"
            value: "5 Hour"
  - entity: select
    name: Mode
    icon: "mdi:fan-auto"
    category: config
    dps:
      - id: 3
        type: string
        name: option
        mapping:
          - dps_val: manual
            value: Manual
          - dps_val: auto
            value: Auto
          - dps_val: sleep
            value: Sleep
  - entity: select
    name: Fan Speed
    icon: "mdi:fan"
    category: config
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: speed_1
            value: Speed 25%
          - dps_val: speed_2
            value: Speed 50%
          - dps_val: speed_3
            value: Speed 75%
          - dps_val: speed_4
            value: Speed 100%
```

Entity in Home Assistant:
![image](https://github.com/make-all/tuya-local/assets/101632973/8f8717c4-fa06-46b7-876e-45d17e567ee8)

The only issue that is have, is the order of controls (probably a home assitant problem, not localtuya)
![image](https://github.com/make-all/tuya-local/assets/101632973/5e2ecd1c-9d1f-4af1-9484-e12ab7c61716)

How can i force the order of controls?

Thanks, and i hope that this configuration file makes it in the official device repository! :)
