### ISSUE TITLE
[New Device] Inventor new Air Conditioners 

### ISSUE THREAD

**Issue by PanosssD** [make-all/tuya-local#1486]
Hello i found that on new inventor ACs with new wifi module (Intentor Control APP) that their app is like a white label of tuya app.
I remove my AC from Inentor Control APP and set up from tuya smart. And i works.
So i install tuya local and fixed all the issues i found. The only open issue is fan only mode (wind as called in tuya) that i can`t manage to fix.

Bellow are the modified yaml file and the results of fix.
The device is the same Product ID as vivax_heatpump.yaml

```
name: Air Condition
products:
  - id: 9xvzf8c0bg33eenj
    name: Inventor AC
  - id: keycnvksyhjcrg8t
    name: Inventor Comfort MFV
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          constraint: mode
          conditions:
            - dps_val: auto
              value: heat_cool
            - dps_val: cold
              value: cool
            - dps_val: wet
              value: dry
            - dps_val: hot
              value: heat
            - dps_val: wind
              value: fan_only
    - id: 2
      type: integer
      name: temperature
      range:
        min: 16
        max: 30
      mapping:
        - constraint: temperature_unit
          conditions:
            - dps_val: f
              range:
                min: 64
                max: 86
              value_redirect: temp_set_f
    - id: 3
      type: integer
      name: current_temperature
      mapping:
        - scale: 2
          constraint: temperature_unit
          conditions:
            - dps_val: f
              scale: 1
              value_redirect: temp_current_f
    - id: 4
      type: string
      name: mode
      hidden: true
    - id: 5
      type: string
      name: fan_mode
      mapping:
        - dps_val: auto
          value: auto
        - dps_val: low
          value: low
        - dps_val: mid
          value: medium
        - dps_val: high
          value: high
#    - id: 8
#      type: boolean
#      name: preset_mode
#      mapping:
#        - dps_val: true
#          value: eco
#        - dps_val: false
#          value: comfort
    - id: 12
      type: boolean
      name: aux_heat
    - id: 18
      type: integer
      name: current_humidity
    - id: 19
      type: string
      name: temperature_unit
      mapping:
        - dps_val: c
          value: C
        - dps_val: f
          value: F
    - id: 23
      type: integer
      name: temp_current_f
      optional: true
      hidden: true
    - id: 24
      type: integer
      name: temp_set_f
      range:
        min: 64
        max: 86
      optional: true
      hidden: true
      # Undocumented but in log
    - id: 102
      type: integer
      name: pm25
    - id: 105
      type: string
      name: air_quality
    - id: 107
      type: boolean
      name: strong
    - id: 111
      type: boolean
      name: new_style
    - id: 116
      type: integer
      name: fault_code
    - id: 117
      type: string
      name: swing_mode
      mapping:
        - dps_val: ud_0c
          constraint: horizontal_swing
          conditions:
            - dps_val: lr_07
              value: both
            - dps_val: lr_00
              value: vertical
        - dps_val: ud_00
          constraint: horizontal_swing
          conditions:
            - dps_val: lr_07
              value: horizontal
            - dps_val: lr_00
              value: "off"
    - id: 118
      type: string
      name: horizontal_swing
    - id: 101
      type: boolean
      name: mood_lighting
      optional: true
    - id: 103
      type: integer
      name: co2
      optional: true
    - id: 104
      type: integer
      name: volatile_organic_compounds
      optional: true
    - id: 112
      type: integer
      name: power
      optional: true
secondary_entities:
  - entity: switch
    name: Emergency heat
    icon: "mdi:fire"
    dps:
      - id: 12
        type: boolean
        name: switch
  - entity: light
    name: Display
    icon: "mdi:numeric"
    category: config
    dps:
      - id: 13
        type: boolean
        name: switch
#  - entity: switch
#    name: Beep
#    icon: "mdi:bell"
#    dps:
#      - id: 16
#        type: boolean
#        name: switch
  - entity: select
    name: Temperature unit
    icon: "mdi:temperature-celsius"
    category: config
    dps:
      - id: 19
        type: string
        name: option
        mapping:
          - dps_val: c
            value: Celsius
          - dps_val: f
            value: Fahrenheit
  - entity: switch
    name: Quiet
    category: config
    icon: "mdi:music-off"
    dps:
      - id: 108
        type: boolean
        name: switch
  - entity: switch
    name: Sleep
    category: config
    icon: "mdi:power-sleep"
    dps:
      - id: 109
        type: boolean
        name: switch
        optional: true
  - entity: switch
    name: Health
    category: config
    icon: "mdi:shield-bug"
    dps:
      - id: 106
        type: boolean
        name: switch
        optional: true
  - entity: switch
    name: Turbo
    category: config
    icon: "mdi:car-turbocharger"
    dps:
      - id: 107
        type: boolean
        name: switch
        optional: true
  - entity: switch
    name: Heating 10C
    icon: "mdi:snowflake-alert"
    dps:
      - id: 110
        type: boolean
        name: switch
  - entity: select
    name: Sence
    category: config
    icon: "mdi:motion-sensor"
    dps:
      - id: 113
        type: string
        name: option
        mapping:
          - dps_val: cancel
            value: Cancel
          - dps_val: avoid
            value: Avoid
          - dps_val: follow
            value: Follow
  - entity: switch
    name: self cleaning
    icon: "mdi:spray-bottle"
    dps:
      - id: 114
        type: boolean
        name: switch
  - entity: select
    name: Vertical swing
    category: config
    icon: "mdi:arrow-up-down-bold"
    dps:
      - id: 117
        type: string
        name: option
        mapping:
          - dps_val: ud_02
            value: Top
          - dps_val: ud_04
            value: Upper
          - dps_val: ud_06
            value: Middle
          - dps_val: ud_08
            value: Lower
          - dps_val: ud_0a
            value: Bottom
          - dps_val: ud_0c
            value: Swing
          - dps_val: ud_00
            value: Stop Swing
          - dps_val: ud_01
            value: Health Air Flow (Cool)
          - dps_val: ud_03
            value: Health Air Flow (Heat)
  - entity: select
    name: Horizontal swing
    category: config
    icon: "mdi:arrow-left-right-bold"
    dps:
      - id: 118
        type: string
        name: option
        mapping:
          - dps_val: lr_03
            value: Leftmost
          - dps_val: lr_04
            value: Left
          - dps_val: lr_00
            value: Middle
          - dps_val: lr_05
            value: Right
          - dps_val: lr_06
            value: Rightmost
          - dps_val: lr_07
            value: Swing
          - dps_val: lr_00
            value: Stop Swing
  - entity: binary_sensor
    name: Fault
    class: problem
    category: diagnostic
    dps:
      - id: 116
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: switch
    name: Cleaning 56C
    icon: "mdi:pot-steam"
    dps:
      - id: 119
        type: boolean
        name: switch
```

### Device Details
![image](https://github.com/make-all/tuya-local/assets/49375908/d1c4494c-9bc7-45f2-8346-7de337e443d3)
