### ISSUE TITLE
[New device] Temperature and humidity sensor AS90

### ISSUE THREAD

**Issue by Jabber-se** [make-all/tuya-local#1497]
### Temperature and humidity sensor AS90

Temperature and humidity sensor AS90 with hight/low value alarms function.

Configuration tested on hassio core-2024.1.2, Tuya Local 2024.1.0
Please add this at devices.

Code:

```
name: Temperature and humidity sensor AS90
products:
  - id: rocfghml4gy1vvr8
primary_entity:
  entity: sensor
  class: temperature
  name: Temperature
  dps:
    - id: 1
      type: integer
      name: sensor
      unit: C
      class: measurement
      mapping:
        - scale: 10
secondary_entities:
  - entity: sensor
    class: humidity
    name: Humidity
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: "%"
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    class: battery
    name: Battery
    category: diagnostic
    dps:
      - id: 4
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: switch
    name: Charger state
    category: config
    dps:
      - id: 8
        type: boolean
        name: switch
  - entity: select
    name: Temperature unit
    category: config
    dps:
      - id: 9
        type: string
        name: option
        mapping:
          - dps_val: c
            value: C
          - dps_val: f
            value: F
  - entity: number
    name: Max temperature set
    category: config
    icon: "mdi:thermometer"
    dps:
      - id: 10
        type: integer
        name: value
        unit: C
        range:
          min: -190
          max: 1500
        mapping:
          - scale: 10
  - entity: number
    name: Min temperature set
    category: config
    icon: "mdi:thermometer"
    dps:
      - id: 11
        type: integer
        name: value
        unit: C
        range:
          min: -190
          max: 1500
        mapping:
          - scale: 10
  - entity: number
    name: Max humidity set
    category: config
    icon: "mdi:water-percent"
    dps:
      - id: 12
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 1000
        mapping:
          - scale: 10
  - entity: number
    name: Min humidity set
    category: config
    icon: "mdi:water-percent"
    dps:
      - id: 13
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 1000
        mapping:
          - scale: 10
  - entity: sensor
    name: Temperature alarm
    class: enum
    category: diagnostic
    dps:
      - id: 14
        type: string
        name: sensor
        mapping:
          - dps_val: upperalarm
            value: "Hight temperature"
          - dps_val: loweralarm
            value: "Low temperature"
          - dps_val: cancel
            value: "No alarm"
  - entity: sensor
    name: Humidity alarm
    class: enum
    category: diagnostic
    dps:
      - id: 15
        type: string
        name: sensor
        mapping:
          - dps_val: upperalarm
            value: "Hight humidity"
          - dps_val: loweralarm
            value: "Low humidity"
          - dps_val: cancel
            value: "No alarm"
  - entity: sensor
    name: Illumination value
    icon: "mdi:sun-wireless"
    dps:
      - id: 16
        type: integer
        name: sensor
        unit: "%"
        class: measurement      
  - entity: number
    name: Temperature report interval
    category: config
    icon: "mdi:clock"
    dps:
      - id: 17
        type: integer
        name: value
        unit: s
        range:
          min: 1
          max: 3600
  - entity: number
    name: Humidity report interval
    category: config
    icon: "mdi:clock"
    dps:
      - id: 18
        type: integer
        name: value
        unit: s
        range:
          min: 1
          max: 3600
  - entity: switch
    name: LCD backlight
    category: config
    dps:
      - id: 21
        type: boolean
        name: switch
  - entity: number
    name: Temperature calibration
    category: config
    icon: "mdi:thermometer"
    dps:
      - id: 23
        type: integer
        name: value
        unit: C
        range:
          min: -80
          max: 80
        mapping:
          - scale: 10
  - entity: number
    name: Humidity calibration
    category: config
    icon: "mdi:water-percent"
    dps:
      - id: 24
        type: integer
        name: value
        unit: "%"
        range:
          min: -500
          max: 500
        mapping:  
          - scale: 10
```
Device picture:
![AS90](https://github.com/make-all/tuya-local/assets/81160361/94943e98-7ad9-4200-af52-e5fee560b543)

Device in Home Assistant:
![ha1](https://github.com/make-all/tuya-local/assets/81160361/ddecff76-8340-4f29-8499-d7d814bea905)

![ha2](https://github.com/make-all/tuya-local/assets/81160361/b7e13d03-b381-4f3d-b9d3-a1b942d5bc6f)
