### ISSUE TITLE
Request support for BlissLights Sky Lite Evolve [SKY-EVOLVE-B-RCW8] --> Config Attached

### ISSUE THREAD

**Issue by fireheadman** [make-all/tuya-local#1507]
Working YAML File is here as well as mentioned in next post
REF:   https://github.com/fireheadman/tuya-local-yamls/blob/main/sky_lite_evolve_projector_light.yaml

# Log Message

```
No logs, but working config in next post

```

# Information about DPS mappings

```

**DPS INFO (Name: ID)**
Work mode: 51
Switch: 20 
Color switch: 52
Laser switch: 53 
Bright value: 101 
Laser brightness:   54
Color: 24 
Timer: 26 
Scene: 58 
Motor Switch: 60 
Motor Speed: 62




```

# Product ID

# Information about how the device functions
id: jteg9ktrhbxtiicz

REF:  https://blisslights.com/products/sky-lite-evolve
A really nice night light that shows a cloud nebula with stars

![image](https://github.com/make-all/tuya-local/assets/19847195/43342c8e-bbe8-4889-b8ad-c38e84e702df)
![image](https://github.com/make-all/tuya-local/assets/19847195/eb4bbe3d-6f8c-4e31-9336-c88515c641b1)

**Comment by fireheadman** [comment]
YAML File created and Test
![image](https://github.com/make-all/tuya-local/assets/19847195/20e9ac56-1274-4f98-905d-89659ccc538f)
![image](https://github.com/make-all/tuya-local/assets/19847195/7a67d04b-60d1-4719-9f51-fcfedd86b0ed)
![image](https://github.com/make-all/tuya-local/assets/19847195/742c73f3-763e-449d-b87c-66e34f15ab12)


homeassistant:/config/custom_components/tuya_local/devices# cat sky_lite_evolve_projector_light.yaml
```
name: Sky Lite Evolve
products:
  - id: jteg9ktrhbxtiicz
    model: SKY-EVOLVE-B-RCW8
    name: BlissLights Sky Lite Evolve
primary_entity:
  entity: light
  name: Globe Light
  icon: "mdi:globe-model"
  dps:
    - id: 20
      type: boolean
      name: switch
    - id: 52
      type: boolean
      name: color_mode
      mapping:
        - dps_val: false
          value: white
        - dps_val: true
          value: hs
    - id: 24
      name: rgbhsv
      type: hex
      format:
        - name: h
          bytes: 2
          range:
            min: 0
            max: 360
        - name: s
          bytes: 2
          range:
            min: 0
            max: 1000
        - name: v
          bytes: 2
          range:
            min: 10
            max: 1000
    - id: 51
      name: effect
      type: string
      mapping:
        - dps_val: scene
          value: Scene
        - dps_val: laser
          value: Laser
        - dps_val: colour
          value: Color
secondary_entities:
  - entity: number
    icon: "mdi:timer"
    name: Timer
    category: config
    dps:
      - id: 26
        type: integer
        name: value
        range:
          min: 0
          max: 86400
        unit: min
        mapping:
          - scale: 60
            step: 60
  - entity: light
    icon: "mdi:laser-pointer"
    name: Laser
    dps:
      - id: 53
        type: boolean
        name: switch
      - id: 54
        name: brightness
        type: integer
        range:
          min: 10
          max: 1000
        mapping:
          - scale: 3.92
  - entity: select
    icon: "mdi:movie-open-play"
    name: Theme
    category: config
    dps:
      - id: 58
        name: option
        type: string
        optional: true
        mapping:
          - dps_val: "AAA="
            value: Cosmos
          - dps_val: "AAE="
            value: Sky
          - dps_val: "AAI="
            value: Space
          - dps_val: "AAM="
            value: Ocean
  - entity: fan
    icon: "mdi:rotate-3d-variant"
    name: Nebula Movement
    dps:
      - id: 60
        type: boolean
        name: switch
      - id: 62
        type: integer
        name: speed
        range:
          min: 0
          max: 100
```
