### ISSUE TITLE
Request support for Hunter Pacific 9 Speed WiFi Remote

### ISSUE THREAD

**Issue by blackice013** [make-all/tuya-local#1529]
This is a Wi-Fi module that can be inserted into various Hunter Pacific fans.

https://www.hunterpacificinternational.com/smart-wifi-module

```yml 
name: Ceiling fan and light
products:
  - id: agjbamgmrbcbazp7
    name: Hunter Pacific 9 Speed WiFi Remote
primary_entity:
  entity: fan
  dps:
    - id: 60
      type: boolean
      name: switch
    - id: 62
      type: integer 
      name: speed
      range:
        min: 1
        max: 9
      mapping:
        - scale: 0.09
    - id: 63
      type: string
      name: direction
secondary_entities:
  - entity: light
    dps:
      - id: 20
        type: boolean
        name: switch
      - id: 22
        name: brightness
        type: integer
        range:
          min: 1
          max: 9
        mapping:
          - scale: 0.0353
```
I've tested locally with all functions working.

### Logs ### 
```2024-09-03 11:24:47.316 DEBUG (MainThread) [custom_components.tuya_local.config_flow] Found device: {'category': 'fsd', 'id': '', 'ip': '', 'local_key': '', 'name': 'Master Fan', 'node_id': '', 'online': True, 'product_id': 'agjbamgmrbcbazp7', 'product_name': '9 Speed WiFi Remote', 'uid': 'eu1704938118101pzmzo', 'uuid': '', 'support_local': True, 'device_cid': None, 'version': None}
2024-09-03 11:24:47.316 DEBUG (MainThread) [custom_components.tuya_local.config_flow] Device is already registered.
2024-09-03 11:24:47.316 DEBUG (MainThread) [custom_components.tuya_local.config_flow] Device count: 0
2024-09-03 11:25:13.431 DEBUG (MainThread) [custom_components.tuya_local.device] Master Bedroom Fan received {"20": false, "22": 1, "60": false, "62": 2, "63": "forward", "full_poll": true}

{"20":"Light ON/OFF","22":"Brightness","60":"Fan ON/OFF","62":"Fan Speed","63":"Summer/Winter"}
```
### DPS ###
```{
  "result": {
    "category": "fsd",
    "functions": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      }
    ],
    "status": [
      {
        "code": "switch_led",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":9,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_direction",
        "type": "Enum",
        "values": "{\"range\":[\"forward\",\"reverse\"]}"
      }
    ]
  },
  "success": true,
  "t": 1725328540670,
  "tid": "9f5900c8699711efbc016e7818a0f8a2"
}


{
  "result": {
    "devices": [
      {
        "active_time": 1705017674,
        "biz_type": 18,
        "category": "fsd",
        "create_time": 1705017674,
        "icon": "smart/icon/bay1597798793056Xaw4/99877e37606ef7e70fd1fe27ecc74b77.png",
        "id": "",
        "ip": "",
        "lat": "",
        "local_key": "",
        "lon": "",
        "model": "9 Speed WiFi Remote",
        "name": "Master Fan",
        "online": true,
        "owner_id": "",
        "product_id": "agjbamgmrbcbazp7",
        "product_name": "9 Speed WiFi Remote",
        "status": [
          {
            "code": "switch_led",
            "value": false
          },
          {
            "code": "bright_value",
            "value": 1
          },
          {
            "code": "fan_switch",
            "value": false
          },
          {
            "code": "fan_speed",
            "value": 2
          },
          {
            "code": "fan_direction",
            "value": "forward"
          }
        ],
        "sub": false,
        "time_zone": "+11:00",
        "uid": "eu1704938118101pzmzo",
        "update_time": 1725319653,
        "uuid": ""
      }
    ],
    "last_id": "1725319653",
    "total": 1
  },
  "success": true,
  "t": 1725328640001,
  "tid": "da8031e6699711efb77736033862a1ba"
}
```
