### ISSUE TITLE
Request support for thermostat ERGERT® FLOOR CONTROL 340 Wi-Fi

### ISSUE THREAD

**Issue by corax-team** [make-all/tuya-local#1547]
# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local ([documentation](https://github.com/make-all/tuya-local), [issues](https://github.com/make-all/tuya-local/issues))
First occurred: 16:31:21 (1 occurrences)
Last logged: 16:31:21

Device matches simple_contact_sensor with quality of 5%. DPS: {"updated_at": 1705843880.7620106, "1": true, "2": "hold", "3": "warming", "16": 190, "17": 410, "24": 190, "29": 656, "104": 0, "107": false, "108": false, "109": 0, "110": 1, "111": "1", "112": 0, "113": -50, "114": "1", "116": 500, "117": 428, "121": 450}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000039nrw\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power3\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"0-Holiday Mode\\n1-Smart Mode\\n2-Hold Mode\",\"extensions\":{\"iconName\":\"icon-a_mode_feel\",\"attribute\":\"132\"},\"name\":\"模式\",\"typeSpec\":{\"range\":[\"holiday\",\"smart\",\"hold\"],\"type\":\"enum\",\"typeDefaultValue\":\"holiday\"}},{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_sun\",\"attribute\":\"128\"},\"name\":\"工作状态\",\"typeSpec\":{\"range\":[\"warming\",\"heating\"],\"type\":\"enum\",\"typeDefaultValue\":\"warming\"}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"摄氏度,间距为5,  5----40℃\\n华氏度,间距为10, 41--104℉\\nholiday模式时 :摄氏度,间距为5,  5----15℃\\n               华氏度,间距为10, 41---59℉\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"attribute\":\"6\"},\"name\":\"目标温度\",\"typeSpec\":{\"max\":400,\"min\":50,\"scale\":1,\"step\":5,\"type\":\"value\",\"typeDefaultValue\":50,\"unit\":\"℃\"}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"temp_set_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\"},\"name\":\"目标温度_F\",\"typeSpec\":{\"max\":1040,\"min\":410,\"scale\":1,\"step\":10,\"type\":\"value\",\"typeDefaultValue\":410,\"unit\":\"℉\"}},{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"摄氏度,间距为5,  0----45℃\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"attribute\":\"2\"},\"name\":\"当前温度\",\"typeSpec\":{\"max\":450,\"min\":0,\"scale\":1,\"step\":5,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"℃\"}},{\"abilityId\":29,\"accessMode\":\"ro\",\"code\":\"temp_current_f\",\"description\":\" 华氏度,间距为1, 32--113℉\",\"extensions\":{\"iconName\":\"icon-dp_temp\"},\"name\":\"当前温度_F\",\"typeSpec\":{\"max\":1130,\"min\":320,\"scale\":1,\"step\":10,\"type\":\"value\",\"typeDefaultValue\":320,\"unit\":\"℉\"}},{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"SensorError\",\"description\":\"0表示无错误,1表示room 传感器错误,2表示floor传感器错误\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"传感器故障\",\"typeSpec\":{\"label\":[\"room\",\"floor\"],\"maxlen\":2,\"type\":\"bitmap\",\"typeDefaultValue\":0}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"TemperUnitChange\",\"description\":\"0摄氏度 \\n1华氏度\",\"name\":\"温标切换\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"Lock\",\"description\":\"0 解除童锁\\n1 触发童锁\",\"name\":\"童锁\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"TimeHoliday\",\"description\":\"\",\"name\":\"假日模式时间设置\",\"typeSpec\":{\"max\":99,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"Event_Adaptive_Set\",\"description\":\"bit0位 为0表示七天独立编程模式;为1表示5+1+1编程模式;\\nbit1位 为1表示自适应开;为0表示自适应关.\\n例如0x02 表示为七天独立编程模式,自适应=开\",\"name\":\"周程序编程模式选择/自适应开关设置\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"SemChange\",\"description\":\"0 - room  sensor\\n1 - floor sensor\\n2 - both sensors\",\"name\":\"传感器切换\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},{\"abilityId\":112,\"accessMode\":\"rw\",\"code\":\"RoomTemperComp\",\"description\":\"摄氏度,间距为5,  -5----5℃\\n华氏度,间距为10, -9----9℉\",\"name\":\"Room当前温度补偿\",\"typeSpec\":{\"max\":90,\"min\":-90,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-90,\"unit\":\"\"}},{\"abilityId\":113,\"accessMode\":\"rw\",\"code\":\"FloorTemperComp\",\"description\":\"摄氏度,间距为5,  -5----5℃\\n华氏度,间距为10, -9----9℉\",\"name\":\"Floor当前温度补偿\",\"typeSpec\":{\"max\":90,\"min\":-90,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-90,\"unit\":\"\"}},{\"abilityId\":114,\"accessMode\":\"rw\",\"code\":\"TemperDiff\",\"description\":\"0_5代表0.5\\n摄氏度时设备上报的值  5  ,10 ,20,30;\\n华氏度时设备上报的值  10  ,20  , 40, 60;  这些值为乘以10后的值\",\"name\":\"温度回差\",\"typeSpec\":{\"range\":[\"0_5\",\"1\",\"2\",\"3\"],\"type\":\"enum\",\"typeDefaultValue\":\"0_5\"}},{\"abilityId\":115,\"accessMode\":\"wr\",\"code\":\"Reset\",\"description\":\"\",\"name\":\"恢复出厂设置\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":116,\"accessMode\":\"rw\",\"code\":\"PowerSet\",\"description\":\"\",\"name\":\"功率设置\",\"typeSpec\":{\"max\":4500,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},{\"abilityId\":117,\"accessMode\":\"ro\",\"code\":\"HeaterTime\",\"description\":\"\",\"name\":\"加热时间\",\"typeSpec\":{\"max\":1470279295,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},{\"abilityId\":119,\"accessMode\":\"rw\",\"code\":\"week_program\",\"description\":\"周一到周日，分别是 0x01,0x02,0x04,0x08,0x10,0x20，0x40表示；\\nWAKE、LEAVE、RETURN、SLEEP分别是 0x00 0x01 0x02 0x03表示。\\n例如：时间07:30， 0x07  0x1e\\n例如：温度39.5，  0x01  0x8b\\n例如app下发 周一周三  wake阶段  7:30  39.5℃\\n数据格式如下:0x55 0xaa 0x00 0x06 0x00 0x0a 0x1a 0x00 0x00 0x06 05 00 07 1e 01 8b crc\\n例如设备端上报 周一周三  wake阶段  7:30  39.5℃\\n数据格式如下:0x55 0xaa 0x00 0x07 0x00 0x0a 0x1a 0x00 0x00 0x06 05 00 07 1e 01 8b crc\\n初上电上报数据时,一次上报一天的数据\\n\",\"name\":\"周程序\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},{\"abilityId\":121,\"accessMode\":\"rw\",\"code\":\"FloorLimit\",\"description\":\"摄氏20--50℃\\n华氏68--122℉\",\"name\":\"地板温度限制\",\"typeSpec\":{\"max\":1220,\"min\":200,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":200,\"unit\":\"\"}},{\"abilityId\":122,\"accessMode\":\"wr\",\"code\":\"inquire\",\"description\":\"这里上报所有周程序数据,按天上报,例如上报周一wake 7:00  23.5℃    leave 9:30  25℃   return 11:30  22℃  sleep   16:00  19℃\\n数据格式如下:55 AA 00 07 00 19 1A 00 00 15   01   00  07 00 00 EB  01  09 1E 00 FA  02  11 1E 00 DC  03  16 00 00 BE 47\",\"name\":\"查询\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}}]}]}"
  },
  "success": true,
  "t": 1705844179581,
  "tid": "0f1a8183b86211eea050fecb253acbfb"
}
```

# Product ID

qupiuahtb0dlyhvg

# Information about how the device functions

**Displaying the thermostat in the app**
![photo1705844526](https://github.com/make-all/tuya-local/assets/48172461/a6de3ee0-ab5e-4021-a327-10d42edfeb42)
![image](https://github.com/make-all/tuya-local/assets/48172461/792d81ec-f650-44f6-a83d-7613a938f72d)

**If you click on the button at the bottom left, you can select the operating mode**
![image](https://github.com/make-all/tuya-local/assets/48172461/3bb890a6-7946-4922-a539-ceb024bdd349)

**Thermostat settings**
![image](https://github.com/make-all/tuya-local/assets/48172461/cc980754-1790-44ee-a2aa-06cc71cccac4)

**You can calibrate the temperature sensor. 
Available range from 5 to -5 degrees in 0.5 degree increments**
![image](https://github.com/make-all/tuya-local/assets/48172461/d850856d-18be-41de-9f2c-253b54f9621f)

**You can specify the trigger delta. 
Available values ​​in the screenshot**
![image](https://github.com/make-all/tuya-local/assets/48172461/84f3bb37-b54f-421b-b057-770549b0d9ab)

**Choice of Celsius or Fahrenheit**
![image](https://github.com/make-all/tuya-local/assets/48172461/8f54c170-aaa9-49b3-b175-93f0606ec547)

**Enable adaptive mode.**
![image](https://github.com/make-all/tuya-local/assets/48172461/d0756f81-3102-40f1-8f76-76e7640737a0)

**Selecting a programmable mode**
![image](https://github.com/make-all/tuya-local/assets/48172461/9f6bceb4-413b-45cd-bb08-fd3f9392e517)

**When clicking "edit setting"**
![image](https://github.com/make-all/tuya-local/assets/48172461/093c8ffb-273b-4239-9439-2b9a526d5757)

**When clicking "Energy use".
Power set can be set**
![image](https://github.com/make-all/tuya-local/assets/48172461/e3f275d1-2110-4fbc-ac7c-666d1205bed3)

**When clicking "Factory reset"**
![image](https://github.com/make-all/tuya-local/assets/48172461/218c086b-35df-458a-84dc-2337e2dd1c6c)

**Link to documentation**
https://ergert.com/ru/wp-content/uploads/2022/10/ETR-340W-manual_compressed.pdf

**Comment by eksvu** [comment]
Hi! Is there any news on this thermostat?

**Comment by eksvu** [comment]
Hi. I partially managed to implement the support. These functions are enough, but now I'm faced with another problem. Two of the three thermostats are added, and the third is defined as a switch or sensor. Tell me what could be the problem?

```
name: Thermostat
products:
  - id: 0000039nrw
    name: ERGERT® FLOOR CONTROL 340 Wi-Fi  
primary_entity:
  entity: climate
  translation_key: thermostat
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          value: heat_cool
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: smart
          value: program
        - dps_val: hold
          value: manual
        - dps_val: holiday
          value: holiday
          constraint: holiday_duration
          conditions:
            - dps_val: 0
              value: "Set holiday length!"
              hidden: true
    - id: 3
      type: string
      name: hvac_action
      mapping:
        - dps_val: heating
          value: heating
        - dps_val: warming
          value: warming
        - dps_val: "off"
          constraint: hvac_mode
          conditions:
            - dps_val: true
              value: idle
            - dps_val: false
              value: "off"
    - id: 16
      type: integer
      name: temperature
      unit: C
      range:
        min: 50
        max: 400
      mapping:
        - scale: 10
          constraint: preset_mode
          conditions:
            - dps_val: holiday
              value_redirect: holiday_temp_set
    - id: 24
      type: integer
      name: current_temperature
      mapping:
        - scale: 10
secondary_entities:
  - entity: number
    name: Temperature calibration
    category: config
    icon: "mdi:thermometer-check"
    dps:
      - id: 113
        type: integer
        name: value
        unit: °
        range:
          min: -90
          max: 90
        mapping:
          - scale: 10
            step: 5
  - entity: lock
    translation_key: child_lock
    category: config
    dps:
      - id: 108
        type: boolean
        name: lock
        optional: true
        mapping:
          - dps_val: null
            value: false
```
