### ISSUE TITLE
Request support for ECOPOINT EV charger

### ISSUE THREAD

**Issue by feeling001** [make-all/tuya-local#1549]
Hi, first of all, thanks for your wonderfull tool !
I can help to add the integration if you tell me the way.

Here for an EV Car charger - ECOPOINT 
Manual : https://m.media-amazon.com/images/I/91G215Hz0lL.pdf

Regards.

# Log Message

```
2024-01-21 17:01:22.154 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1705852880.3249083, "1": 690, "3": "charger_charging", "4": 6, "10": 0, "13": "controlpi_6v_pwm", "14": "charge_energy", "18": true, "22": "EV Charger 0001", "23": "2.0.0-512.220.01", "24": 15, "25": 152}
```

# Product ID
<details>
<summary>jui3mys5c9rfdju2</summary>

```
        {
            "active_time": 1705771424,
            "biz_type": 0,
            "category": "qccdz",
            "create_time": 1705745225,
            "icon": "smart/icon/bay1611120714513bC7N/d93c5f10b049818e507b7936101dfb17.png",
            "id": "bfeb221c33cd081e4dgn3c",
            "ip": "HIDDEN",
            "lat": "HIDDEN",
            "local_key": "HIDDEN",
            "lon": "HIDDEN",
            "model": "",
            "name": "HomerEVCharger",
            "online": true,
            "owner_id": "HIDDEN",
            "product_id": "jui3mys5c9rfdju2",
            "product_name": "EV_Charger_14",
            "status": [
                {
                    "code": "forward_energy_total",
                    "value": 669
                },
                {
                    "code": "battery_percentage",
                    "value": 0
                },
                {
                    "code": "work_state",
                    "value": "charger_charging"
                },
                {
                    "code": "charge_cur_set",
                    "value": 6
                },
                {
                    "code": "power_total",
                    "value": 0
                },
                {
                    "code": "connection_state",
                    "value": "controlpi_6v_pwm"
                },
                {
                    "code": "work_mode",
                    "value": "charge_energy"
                },
                {
                    "code": "energy_charge",
                    "value": 10
                },
                {
                    "code": "switch",
                    "value": true
                },
                {
                    "code": "charge_time",
                    "value": 1
                },
                {
                    "code": "temp_current",
                    "value": 15
                },
                {
                    "code": "charge_energy_once",
                    "value": 131
                }
            ],
            "sub": false,
            "time_zone": "+01:00",
            "uid": "eu1687106509237oSJXR",
            "update_time": 1705842427,
            "uuid": "ce4eef43a499484d"
        }
    ],
    "success": true,
    "t": 1705852320293,
    "tid": "HIDDEN",
    "file": {
        "name": "tuya-raw.json",
        "description": "Full raw list of Tuya devices.",
        "account": "HIDDEN",
        "date": "2024-01-21T16:52:00.311234",
        "tinytuya": "1.13.1"
    }

```

</details>

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"0000049dk2\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"forward_energy_total\",\"description\":\"1，正向总有功电量 \\n2，大端模式，HEX格式，4个字节，6位整数+2位小数\\n3，单位精度0.01KWH\\n4，报文格式\\n例如，上报0X00 00 27 11,表示上报电量100.01 KWH（是32位，4个字节）\\n5，通信逻辑：\\nA情形：配网成功时，MCU上报总用电量。\\nB情形：MCU周期定时上报总用电量。建议：在WIFI模式时，30秒上报一次或电量增加0.1KWH时上报一次。NB模式时，1个小时上报一次电量。\\nC情形: 电表按键时上报电量。\\nD情形:面板下发00(2月日与娟娟商量，发0可行），MCU收到后回复当前的正向总有功电量给云平台。\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"正向总有功电量\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"1，电池电量%\\n2，HEX格式，共1个字节\\n3，单位精度：剩余电量%,只有整数位\\n4，报文格式\\n   百分比,1个字节表示，无小数位。\\n举例：HEX  33，表示51%\\n5，通信逻辑：\\nA情形：APP与设备通信时，这时设备要主动上报该DP点数据，面板收到解析。建议百分比有变化时，就上报更新\",\"extensions\":{\"iconName\":\"icon-dp_battery\"},\"name\":\"电池电量\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"%\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"work_state\",\"description\":\"空闲未插枪，空闲已插枪，空闲故障，充电等待，充电中，充电暂停，充电结束，充电发生故障\",\"extensions\":{\"iconName\":\"icon-zhuangtai\"},\"name\":\"充电桩状态\",\"typeSpec\":{\"range\":[\"charger_free\",\"charger_insert\",\"charger_free_fault\",\"charger_wait\",\"charger_charging\",\"charger_pause\",\"charger_end\",\"charger_fault\"],\"type\":\"enum\",\"typeDefaultValue\":\"charger_free\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"charge_cur_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-shezhi\"},\"name\":\"充电电流设定\",\"typeSpec\":{\"max\":80,\"min\":6,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":6,\"unit\":\"A\"}},
{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"phase_a\",\"description\":\"1、相电压，电流及功率\\n2，大端模式，HEX格式，共8个字节\\n3，单位精度：电压，2字节，单位0.1V。电流，3字节，单位 0.001A 。A相有功功率，3字节，单位0.001kW\\n4，报文格式\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"A相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":7,\"accessMode\":\"ro\",\"code\":\"phase_b\",\"description\":\"1、相电压，电流及功率\\n2，大端模式，HEX格式，共8个字节\\n3，单位精度：电压，2字节，单位0.1V。电流，3字节，单位 0.001A 。A相有功功率，3字节，单位0.001kW\\n4，报文格式\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"B相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"phase_c\",\"description\":\"1、相电压，电流及功率\\n2，大端模式，HEX格式，共8个字节\\n3，单位精度：电压，2字节，单位0.1V。电流，3字节，单位 0.001A 。A相有功功率，3字节，单位0.001kW\\n4，报文格式\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"C相电压，电流及功率\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"power_total\",\"description\":\"1，三相总有功功率\\n2，大端模式，HEX格式,4字节，\\n3,单位精度：单位0.001kW\\n4,报文格式\\n举例：0X00 00 27 10 表示总功率10.000KW\\n5，通信逻辑：\\n1）用户进面板，主动查询。用户进入面板，面板马上下发读取命令到电表，电表上报数据到云平台，面板拿到数据，然后展示。    \\n2）电表基于一定周期上报数据。建议：在WIFI模式时，15秒上报一次。NB模式时，1个小时上报一次。\",\"extensions\":{\"iconName\":\"icon-dp_lightning\"},\"name\":\"总功率\",\"typeSpec\":{\"max\":99999999,\"min\":0,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW\"}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"ov_cr\",\"ov2_cr_fault\",\"ov_vol\",\"undervoltage_alarm\",\"contactor_adhesion\",\"contactor_fault\",\"earth_fault\",\"meter_hardware_alarm\",\"scram_fault\",\"cp_fault\",\"meter_commu_fault\",\"card_reader_fault\",\"cir_short_fault\",\"adhesion_fault\",\"self_test_alarm\",\"leakagecurr_alarm\"],\"maxlen\":16,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"connection_state\",\"description\":\"CP12 未连接\\nCP9V 连接\\nCP6 充电\",\"extensions\":{\"iconName\":\"icon-zhuangtai\"},\"name\":\"CP状态\",\"typeSpec\":{\"range\":[\"controlpi_12v\",\"controlpi_12v_pwm\",\"controlpi_9v\",\"controlpi_9v_pwm\",\"controlpi_6v\",\"controlpi_6v_pwm\",\"controlpi_error\"],\"type\":\"enum\",\"typeDefaultValue\":\"controlpi_12v\"}},
{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"1，充电模式选择 \\n0X01 即时充电（选择即刻开启充电，界面回到主界面）充满停。\\n0X02 定电量（点击下发模式选择，界面跳转设置电量界面，一旦下发充电成功（dp17），即可启动充电，界面跳回主界面）  无云定时\\n0X03 定时充电（点击下发模式选择，界面跳转设置时间界面，设置好时间下发开启成功（dp19），即可充电，界面跳回主界面）。\\n即时充电 charge_now\\n//百分比充电charge_pct 本次不做\\n定电量charge_energy\\n定时充电charge_schedule\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"充电模式选择\",\"typeSpec\":{\"range\":[\"charge_now\",\"charge_energy\",\"charge_schedule\"],\"type\":\"enum\",\"typeDefaultValue\":\"charge_now\"}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"energy_charge\",\"description\":\"2，大端模式，HEX,三个字节，4位整数+两位小数\\n3，单位精度，0.01KWH\\n4，报文格式\\n   举例0X00 4E 20,充值200KWH 电量到MCU\\n5，通信逻辑\\n1）面板下发充值命令到电表，电表执行充值命令。\\n2）MCU充值成功，回复本次充值电量上报面板，面板更新界面显示：当前可用的剩余电量。\",\"extensions\":{\"iconName\":\"icon-dp_money\"},\"name\":\"单次充电电量上报——充电结束时上报\",\"typeSpec\":{\"max\":20000000,\"min\":1,\"scale\":3,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"kW·h\"}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"1，充电桩拉合闸\\n2，报文格式\\n 面板下发：0X01 合闸，0X00拉闸\\n MCU上报：0X01 合闸状态，0X00拉闸状态\\n3，通信逻辑\\n1）面板下发，MCU收到命令动作，再回发闸在当前的状态；\\n2）电表自动动作（漏电，短路），MCU上报电表状态\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"充电开启/关闭\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"charge_time\",\"description\":\"1，定时充电时间段设置\\n2，HEX格式，四个字节，大端模式\\n3，单位精度：分\\n4，报文格式\\n   第一个字节，表示开始充电时间小时，第二个字节，表开始充电时间分，第三个字节，表示结束时间小时，第四个字节，表示结束时间分\\n5，通信逻辑\\n   新配网，显示请输入；\\n   用户通过面板设置，MCU收到后解析及保存，并回复该值给云端，面板收到与下发值一致，就认为是成功，否则不会显示设置的值。\",\"extensions\":{\"iconName\":\"icon-dp_time3\"},\"name\":\"充电时间\",\"typeSpec\":{\"max\":1440,\"min\":1,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"min\"}},
{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"card_binding\",\"description\":\"第一个字节 0X01  绑定   0x00删除                                                           2，第二个字节卡号信息                                                                                  数据类型： string\\n功能属性：最大长度32字节\",\"extensions\":{\"iconName\":\"icon-dp_power2\"},\"name\":\"绑定卡\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"meter_id\",\"description\":\"1，设备号\\n2，大端模式，字符串型\\n3，单位精度\\n4，报文格式\\n5，通信逻辑\\nA，配网时上报三次，以确保上报成功。如果配对成功，面板有显示设备号。\\nB，如果配对成功，面板没有显示设备号，需要移除设备，再配置一遍。\\nC，每次电表上电，也上报一次。\",\"extensions\":{\"iconName\":\"icon-dp_0\"},\"name\":\"设备号\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"system_version\",\"description\":\"功能名称：充电桩软硬件版本号\\n数据传输类型：只上报\\n数据类型： string\\n功能属性： 最大长度128字节\\n备注：1，充电桩软硬件版本号\\n2，大端模式，HEX数据\\n3，数据定义：硬件版本号，2字节，倍数2。软件版本号，2字节，倍数2 。\\n4，报文格式\\n举例：00 64 00 65 表示硬件版本号：V1.00，软件版本号：V1.01 \\n3，通信逻辑 \\nA，配网时上报三次，以确保上报成功。如果配对成功，面板有显示软硬件版本。 \\nB，每次充电桩上电，上报一次。\",\"extensions\":{\"iconName\":\"icon-dp_mode\"},\"name\":\"系统版本\",\"typeSpec\":{\"maxlen\":255,\"type\":\"string\",\"typeDefaultValue\":\"\"}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"1，充电桩温度\\n2，大端模式，HEX格式，1个字节\\n3，单位精度：   1摄氏度\\n4，报文格式\\n例如，上报0X01,表示1度\\n5，通信逻辑：\\nA情形：配网成功时，MCU上报当前逆变器温度。\\nB情形：MCU周期定时上报逆变器温度。建议：在WIFI模式时，1分钟上报一次。NB模式时，1个小时上报一次\",\"extensions\":{\"iconName\":\"icon-dp_c\"},\"name\":\"充电桩温度\",\"typeSpec\":{\"max\":300,\"min\":-50,\"scale\":1,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-50,\"unit\":\"℃\"}},
{\"abilityId\":25,\"accessMode\":\"rw\",\"code\":\"charge_energy_once\",\"description\":\"1，单次充电量 \\n2，大端模式，HEX,4个字节，6个整数+2个小数\\n3，单位精度：0.01KWH\\n4，报文格式\\n   上报0X00 00 27 10,充值100.00 KWH\\n5，通信逻辑\\n1)召读逻辑\\n  用户进面板，下发查询。MCU上报回复剩余可用电量给面板。\\n2）电表基于一定周期上报数据。WIFI，60秒更新一次，NB建议1个小时更新一次。\\n3）充电结束/人为结束，上报单次充电量\",\"extensions\":{\"iconName\":\"icon-Ele\"},\"name\":\"单次充电量\",\"typeSpec\":{\"max\":200000,\"min\":0,\"scale\":2,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"kW·h\"}},
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"charge_time1\",\"description\":\"上报4个字节充电时间，单位以s。面板上显示时间相应转换时和分。\",\"name\":\"充电时间\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"name\":\"模式\",\"typeSpec\":{\"range\":[\"home\",\"mode\",\"recode\",\"setting\"],\"type\":\"enum\",\"typeDefaultValue\":\"home\"}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"current_limit\",\"description\":\"1、最小电流最大电流\\n2，大端模式，HEX格式，共4个字节\\n3，单位精度：最小电流，2字节，单位0.1A。最大电流，2字字节，单位0.1A。\",\"name\":\"额定电流\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}}]}]}"
  },
  "success": true,
  "t": 1705853202643,
  "tid": "11463ed4b87711eea050fecb253acbfb"
}
```

# Product ID

```
{
  "result": [
    {
      "active_time": 1705771424,
      "bind_space_id": "158757673",
      "category": "qccdz",
      "create_time": 1705745225,
      "custom_name": "HomerEVCharger",
      "icon": "smart/icon/bay1611120714513bC7N/d93c5f10b049818e507b7936101dfb17.png",
      "id": "bfeb221c33cd081e4dgn3c",
      "ip": "HIDDEN",
      "is_online": true,
      "lat": "HIDDEN",
      "local_key": "HIDDEN",
      "lon": "HIDDEN",
      "model": "",
      "name": "EV_Charger_14",
      "product_id": "jui3mys5c9rfdju2",
      "product_name": "EV_Charger_14",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1705774824,
      "uuid": "ce4eef43a499484d"
    }
  ],
  "success": true,
  "t": 1705853371024,
  "tid": "75a39190b87711eebe106ae4d2d5261a"
}
```

# Information about how the device functions

Almost no information about the seller, but the manual seems to be common to several EV Chargers (Here ECOPOINT)
https://m.media-amazon.com/images/I/91G215Hz0lL.pdf

Thanks a lot !!

**Comment by feeling001** [comment]
I Tried to write a yaml by myself  ( by adapting feyree_ev_charger.yaml into ecopoint_ev_charger.yaml)... 
The device is recognized but I have only one entity :-D ... I probably made something wrong.

```
name: Ecopoint EV charger
products:
  - id: jui3mys5c9rfdju2
    name: ECOPoint 32A EV charger
primary_entity:
  entity: sensor
  class: enum
  name: Status
  icon: "mdi:ev-station"
  dps:
    - id: 1
      type: integer
      optiona: true
      name: total_energy
    - id: 3
      type: string
      optional: true
      name: charger_status
    - id: 4
      type: integer
      name: charging_current
    - id: 10
      type: bitfield
      name: fault_code
    - id: 13
      type: string
      name: connection_state
    - id: 14
      type: string
      optional: true
      name: mode
      mapping:
        - dps_val: charge_now
        - dps_val: charge_pct
        - dps_val: charge_energy
        - dps_val: charge_schedule
    - id: 18
      type: boolean
      optional: true
      name: switch
    - id: 22
      type: string
      optional: true
      name: meter_id
    - id: 23
      type: string
      optional: true
      name: system_version
    - id: 24
      type: integer
      name: temp_current
    - id: 25
      type: integer
      optional: true
      name: charge_energy_once
      unit: kWh
    - id: 27
      type: string
      optional: true
      name: online_state
secondary_entities:
  - entity: button
    name: Clear energy
    class: restart
    category: config
    dps:
      - id: 16
        type: boolean
        name: button
        optional: true
  - entity: number
    name: Set charge current
    category: config
    icon: "mdi:ev-plug-type-2"
    dps:
      - id: 103
        type: boolean
        optional: true
        name: max_current
        mapping:
          - dps_val: false
            value: 16
          - value: 32
      - id: 111
        type: integer
        optional: true
        name: current_16_limit
        hidden: true
        range:
          min: 8
          max: 16
```

in the debug log I see
```
2024-01-22 17:45:58.615 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"1": 1340, "3": "charger_charging", "4": 6, "10": 0, "13": "controlpi_6v_pwm", "14": "charge_energy", "18": true, "22": "EV Charger 0001", "23": "2.0.0-512.220.01", "24": 19, "25": 193, "full_poll": true}
2024-01-22 17:46:15.705 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"6": "CQ4AFp4ABU8=", "full_poll": false}
2024-01-22 17:46:15.830 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"7": "AAAAAAAAAAA=", "full_poll": false}
2024-01-22 17:46:15.956 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"8": "AAAAAAAAAAA=", "full_poll": false}
2024-01-22 17:46:16.180 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"25": 198, "full_poll": false}
2024-01-22 17:46:16.293 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"1": 1343, "full_poll": false}
2024-01-22 17:46:18.076 DEBUG (MainThread) [custom_components.tuya_local.device] Ecopoint EV charger received {"101": "AAEUMg==", "full_poll": false}
```

But no sensors added :-(

**Comment by feeling001** [comment]
I propose the following Configuration : (working)
ecopoint_ev_charger.yaml

```
name: Ecopoint Charger EV
products:
  - id: bfeb221c33cd081e4dgn3c
    name: Ecopoint 32A EV charger
primary_entity:
  entity: sensor
  name: Charger State
  icon: "mdi:ev-station"
  class: enum
  dps:
    - id: 3 # work_state
      type: string
      name: sensor
      mapping:
        - dps_val: charger_charging
        - dps_val: charger_free
        - dps_val: charger_insert
        - dps_val: charger_free_fault
        - dps_val: charger_wait
        - dps_val: charger_pause
        - dps_val: charger_end
        - dps_val: charger_fault

secondary_entities:
  - entity: sensor
    name: Total energy
    dps:
      - id: 1 # forward_energy_total
        type: integer
        name: sensor
        class: energy
        unit: kWh
        mapping:
          - scale: 100
  - entity: number
    name: Set charge current
    category: config
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 4 # charge_cur_set
        type: integer
        name: value
        unit: A
        range:
          min: 6
          max: 32
        mapping:
          - constraint: max_current
            conditions:
              - dps_val: false
                value_redirect: current_16_limit
                range:
                  min: 8
                  max: 16
  - entity: sensor
    name: Fault
    icon: "mdi:alert-circle"
    class: enum
    category: diagnostic
    dps:
      - id: 10 # fault
        type: bitfield
        name: sensor
        class: enum
        mapping:
          - dps_val: 0
            value: no_fault
          - dps_val: ov2_cr_fault
          - dps_val: ov_vol
          - dps_val: undervoltage_alarm
          - dps_val: contactor_adhesion
          - dps_val: contactor_fault
          - dps_val: earth_fault
          - dps_val: meter_hardware_alarm
          - dps_val: scram_fault
          - dps_val: cp_fault
          - dps_val: meter_commu_fault
          - dps_val: card_reader_fault
          - dps_val: cir_short_fault
          - dps_val: adhesion_fault
          - dps_val: self_test_alarm
          - dps_val: leakagecurr_alarm
  - entity: sensor
    name: Connection Status
    icon: "mdi:connection"
    class: enum
    dps:
      - id: 13 # connection_state
        type: string
        name: sensor
        mapping:
          - dps_val: controlpi_12v
          - dps_val: controlpi_12v_pwm
          - dps_val: controlpi_9v
          - dps_val: controlpi_9v_pwm
          - dps_val: controlpi_6v
          - dps_val: controlpi_6v_pwm
          - dps_val: controlpi_error
  - entity: sensor
    name: Work Mode
    class: enum
    dps:
      - id: 14 # work_mode
        type: string
        optional: true
        name: sensor
        class: enum
        mapping:
          - dps_val: charge_now
          - dps_val: charge_energy
          - dps_val: charge_schedule
  - entity: sensor
    name: Meter id
    category: diagnostic
    dps:
      - id: 22 # meter_id
        type: string
        name: sensor
  - entity: sensor
    name: System Version
    category: diagnostic
    dps:
      - id: 23 # system_version
        type: string
        name: sensor
  - entity: sensor
    class: temperature
    name: Temperature
    category: diagnostic
    dps:
      - id: 24
        type: integer
        name: sensor
        unit: C
        class: measurement
  - entity: sensor
    name: Charge Energy Once
    dps:
      - id: 25 # charge_energy_once
        type: integer
        name: sensor
        optional: true
  - entity: switch
    name: Charger Switch
    icon: "mdi:electric-switch"
    category: config
    dps:
      - id: 18 # switch
        type: boolean
        name: switch
        mapping:
          - dps_val: false
          - dps_val: true
```
