### ISSUE TITLE
Request support for holman Helios Weather Station

### ISSUE THREAD

**Issue by Elliottmonaghan** [make-all/tuya-local#1617]
Only new to github and don't know all the ins and outs of posting request and such. I have added this device and have it running on my tuya-local with no errors currently. I will attach a copy of my yaml for it.

# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 1,
        "time": 1706499806021,
        "value": -200
      },
      {
        "code": "intemp",
        "custom_name": "",
        "dp_id": 101,
        "time": 1707178717554,
        "value": 254
      },
      {
        "code": "inhum",
        "custom_name": "",
        "dp_id": 102,
        "time": 1707178717571,
        "value": 500
      },
      {
        "code": "ch1temp",
        "custom_name": "",
        "dp_id": 103,
        "time": 1707178734636,
        "value": 331
      },
      {
        "code": "ch1hum",
        "custom_name": "",
        "dp_id": 104,
        "time": 1707178734656,
        "value": 530
      },
      {
        "code": "pressure",
        "custom_name": "",
        "dp_id": 109,
        "time": 1707178717685,
        "value": 10120
      },
      {
        "code": "windspeed",
        "custom_name": "",
        "dp_id": 110,
        "time": 1707178734707,
        "value": 70
      },
      {
        "code": "gustwind",
        "custom_name": "",
        "dp_id": 111,
        "time": 1707178667751,
        "value": 110
      },
      {
        "code": "wd",
        "custom_name": "",
        "dp_id": 112,
        "time": 1707178734803,
        "value": "SES"
      },
      {
        "code": "rain_1h",
        "custom_name": "",
        "dp_id": 113,
        "time": 1707127710378,
        "value": 0
      },
      {
        "code": "rain_24h",
        "custom_name": "",
        "dp_id": 114,
        "time": 1707125422255,
        "value": 0
      },
      {
        "code": "uvi",
        "custom_name": "",
        "dp_id": 115,
        "time": 1707178540084,
        "value": 70
      },
      {
        "code": "lux",
        "custom_name": "",
        "dp_id": 116,
        "time": 1707178469840,
        "value": 13107
      },
      {
        "code": "dewpoint",
        "custom_name": "",
        "dp_id": 117,
        "time": 1707178734894,
        "value": 222
      },
      {
        "code": "feellike",
        "custom_name": "",
        "dp_id": 123,
        "time": 1707178734669,
        "value": 311
      },
      {
        "code": "heat",
        "custom_name": "",
        "dp_id": 124,
        "time": 1707178734682,
        "value": 371
      },
      {
        "code": "windchill",
        "custom_name": "",
        "dp_id": 125,
        "time": 1707178734694,
        "value": 331
      },
      {
        "code": "com",
        "custom_name": "",
        "dp_id": 126,
        "time": 1707178717669,
        "value": "comfortable"
      },
      {
        "code": "alarm",
        "custom_name": "",
        "dp_id": 127,
        "time": 1707043433112,
        "value": "AX8AAAcAAn8AAAgA"
      },
      {
        "code": "alert",
        "custom_name": "",
        "dp_id": 128,
        "time": 1707043431967,
        "value": "ZQADAfT/nGcAAwK8/nA="
      },
      {
        "code": "unit",
        "custom_name": "",
        "dp_id": 129,
        "time": 1707043432821,
        "value": "AQACAAMABAA="
      },
      {
        "code": "battery",
        "custom_name": "",
        "dp_id": 130,
        "time": 1707178717781,
        "value": "AP8B/w=="
      },
      {
        "code": "basic",
        "custom_name": "",
        "dp_id": 131,
        "time": 1707043431683,
        "value": "fwIAAACAAmVngQ8="
      },
      {
        "code": "alertup",
        "custom_name": "",
        "dp_id": 132,
        "time": 1706499806021,
        "value": 0
      },
      {
        "code": "datadisplay",
        "custom_name": "",
        "dp_id": 133,
        "time": 1707178735007,
        "value": "ewB1AH0BfABnAGgAfgBuAG8AcAByAHEAdABzAA=="
      },
      {
        "code": "rain",
        "custom_name": "",
        "dp_id": 134,
        "time": 1707178734541,
        "value": 0
      },
      {
        "code": "inbat",
        "custom_name": "",
        "dp_id": 140,
        "time": 1707125418970,
        "value": "Good"
      },
      {
        "code": "ch1bat",
        "custom_name": "",
        "dp_id": 141,
        "time": 1707125418987,
        "value": "Good"
      },
      {
        "code": "UserVariable1",
        "custom_name": "",
        "dp_id": 150,
        "time": 1706499806021,
        "value": false
      },
      {
        "code": "UserVariable2",
        "custom_name": "",
        "dp_id": 151,
        "time": 1706499806021,
        "value": false
      },
      {
        "code": "UserVariable3",
        "custom_name": "",
        "dp_id": 153,
        "time": 1706499806021,
        "value": false
      },
      {
        "code": "UserVariable4",
        "custom_name": "",
        "dp_id": 154,
        "time": 1706499806021,
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1707178745925,
  "tid": "56a1cf6dc48511eeb4711ef527e2ea42"
}
```

# Product ID
```
{
  "result": [
    {
      "active_time": 1707043425,
      "bind_space_id": "49733084",
      "category": "wsdcg",
      "create_time": 1706499806,
      "custom_name": "",
      "icon": "smart/icon/ay1556838860681oKmdO/9b886c98ce149d23f01ea49bf18a9ecb.png",
      "id": "bf69e4a09c0c82e6d4efha",
      "ip": "",
      "is_online": true,
      "lat": "",
      "local_key": "",
      "lon": "",
      "model": "WS5095W2",
      "name": "Helios Weather Station",
      "product_id": "amluiug6se4zdz1t",
      "product_name": "Helios Weather Station",
      "sub": false,
      "time_zone": "",
      "update_time": 1707043425,
      "uuid": "6371ce6418dc5804"
    }
  ],
  "success": true,
  "t": 1707178783014,
  "tid": "6cc55eedc48511eea28be2dee5a60296"
}
```

# Information about how the device functions

https://www.holmanindustries.com.au/product/helios-wifi-weather-station/

```
# Helios Wi-Fi Weather Station
# https://www.holmanindustries.com.au/product/helios-wifi-weather-station/
name: Helios Weather Station
products:
  - id: amluiug6se4zdz1t
    model: WS5095W2
primary_entity:
  entity: sensor
  name: Indoor Temperature
  category: diagnostic
  dps:
    - id: 101
      name: sensor
      type: integer
      unit: C
      mapping:
        - scale: 10
      class: measurement
secondary_entities:
  - entity: sensor
    name: Indoor humidity
    class: humidity
    category: diagnostic
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: "%"
        mapping:
        - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: C
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Humidity
    class: humidity
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        unit: "%"
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Atmospheric Pressure
    class: atmospheric_pressure
    category: diagnostic
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: hPa
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Wind Speed
    class: wind_speed
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        unit: "km/h"
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Wind Gust
    class: wind_speed
    category: diagnostic
    dps:
      - id: 111
        type: integer
        name: sensor
        unit: km/h
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Wind Direction
    icon: mdi:compass-outline
    category: diagnostic
    dps:
      - id: 112
        type: string
        name: sensor
  - entity: sensor
    name: Rain 1 Hour
    class: precipitation
    category: diagnostic
    dps:
      - id: 113
        type: integer
        name: sensor
        unit: mm
        mapping:
          - scale: 0.01
        class: measurement
  - entity: sensor
    name: Rain Since 9am
    class: precipitation
    category: diagnostic
    dps:
      - id: 114
        type: integer
        name: sensor
        unit: mm
        mapping:
          - scale: 0.01
        class: measurement
  - entity: sensor
    name: UV Index
    category: diagnostic
    dps:
      - id: 115
        type: integer
        name: sensor
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Illuminance
    class: illuminance
    category: diagnostic
    dps:
      - id: 116
        type: integer
        name: sensor
        unit: lx
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Dewpoint
    class: temperature
    category: diagnostic
    dps:
      - id: 117
        type: integer
        name: sensor
        unit: C
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Feels Like
    class: temperature
    category: diagnostic
    dps:
      - id: 123
        type: integer
        name: sensor
        unit: C
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Heat Index
    class: temperature
    category: diagnostic
    dps:
      - id: 124
        type: integer
        name: sensor
        unit: C
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Windchill
    class: temperature
    category: diagnostic
    dps:
      - id: 125
        type: integer
        name: sensor
        unit: C
        mapping:
          - scale: 10
        class: measurement
  - entity: sensor
    name: Outdoor Temp Rating
    category: diagnostic
    dps:
      - id: 126
        type: string
        name: sensor
  - entity: sensor
    name: Outdoor Rain
    class: precipitation
    category: diagnostic
    dps:
      - id: 134
        type: integer
        name: sensor
        unit: mm
        mapping:
          - scale: 0.01
        class: measurement
  - entity: sensor
    name: Tablet Battery
    icon: mdi:battery
    category: diagnostic
    dps:
      - id: 140
        type: string
        name: sensor
  - entity: sensor
    name: Outdoor Battery
    icon: mdi:battery
    category: diagnostic
    dps:
      - id: 141
        type: string
        name: sensor
```
