### ISSUE TITLE
Proposed support for iLonda Smart Wifi Fish Feeder

### ISSUE THREAD

**Issue by Cadish** [make-all/tuya-local#1619]
# Log message
```
Device matches cct_v1_lightbulb with quality of 50%. DPS: {"updated_at": 1727087491.7632954, "1": false, "6": 0}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000004upd7\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"5\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"秒\"}}]}]}"
  },
  "success": true,
  "t": 1707298612070,
  "tid": "6c71687dc59c11eeae9c82e95b97004a"
}
```

# Product ID

```
{
  "result": {
    "active_time": 1707296408,
    "bind_space_id": "166111991",
    "category": "ygwsq",
    "create_time": 1707295737,
    "custom_name": "Name",
    "icon": "smart/icon/ay1513862246256UjYBd/eb04d1b5ed3a72f2429fd34c76e82a80.png",
    "id": "xxxxx",
    "ip": "xxxxxx",
    "is_online": true,
    "lat": "xxxxxxx",
    "local_key": "xxxxxx",
    "lon": "xxxxxxx",
    "model": "",
    "name": "鱼缸喂食器",
    "product_id": "3jskpz3pwqn9oojn",
    "product_name": "鱼缸喂食器",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1707296408,
    "uuid": "cde261566e028df9"
  },
  "success": true,
  "t": 1707298502117,
  "tid": "2ae6d182c59c11eea80ac21fcdf0c8ac"
}
```

# Information about how the device functions
https://fccid.io/2AQJW-L88/User-Manual/User-Manual-3956439

# Proposed YAML Configuration

```
name: Fish feeder
products:
  - id: xxxx
    name: iLonda Smart Wifi Fish Feeder
primary_entity:
  entity: switch
  class: switch
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: number
    name: Countdown
    icon: "mdi:timer"
    category: config
    dps:
      - id: 6
        type: integer
        name: value
        range:
        min: 0
        max: 86400
        mapping:
            scale: 1
            step: 0
            unit: s
```
