### ISSUE TITLE
Request support for Honey Guaridan S56 ped feeder

### ISSUE THREAD

**Issue by ciotorcristian** [make-all/tuya-local#1670]
# Log Message

```
2024-02-19 16:46:25.677 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches None with quality of 0%. DPS: {"updated_at": 1708353978.1345325, "3": 1, "6": false, "18": 3, "101": 2, "102": true, "103": "full"}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"000003ys3u\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"meal_plan\",\"description\":\"同步到设备端本地，即使设备离线，仍能正常喂食出粮，喂食计划支持6组，共30字节，不足位补零。\\nraw格式约定：按照“周期+时间+喂食份数+开关”来实现本地定时，具体如下\\n1，前7个比特位代表周一到周日，二进制转十六进制，占用一个字节，0代表未设置，1代表设置，如0000001，表示周日生效，转换为16进制就是01\\n2，时间按照小时分钟格式，占用2个字节，分钟和小时，十进制转16进制，如18：50，转为16进制为1232\\n3，喂食份数，范围1-48.占用1个字节，十进制转16进制，如12，转为16进制为0c\\n4，开关，占用1个字节，00表示关闭，01表示开启\\n上述举例，对于APP端时间下发的结果为0112320c01，表示周日，18：50，喂食12份，开启。\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"96\",\"trigger\":\"direct\"},\"name\":\"喂食计划\",\"typeSpec\":{\"maxlen\":128,\"type\":\"raw\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"manual_feed\",\"description\":\"手动喂食份数\",\"extensions\":{\"iconName\":\"icon-icon-test13\",\"trigger\":\"direct\"},\"name\":\"手动喂食\",\"typeSpec\":{\"max\":6,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"slow_feed\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_wash\",\"trigger\":\"direct\"},\"name\":\"慢放喂食\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_notice\",\"scope\":\"fault\",\"trigger\":\"direct\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"food_run_out\",\"ERR1\",\"ERR3\",\"ERR5\"],\"maxlen\":4,\"type\":\"bitmap\",\"typeDefaultValue\":0}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"voice_times\",\"description\":\"\",\"extensions\":{\"attribute\":\"224\"},\"name\":\"语音播放次数\",\"typeSpec\":{\"max\":10,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0}},
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"record\",\"description\":\"用于记录喂食份数。每次喂食成功后mcu需要上报喂食份数。面板显示在记录页面。\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"喂食记录\",\"typeSpec\":{\"max\":48,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"hour\",\"description\":\"false为12小时制（默认），true为24小时制\",\"name\":\"24小时制\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"battery\",\"description\":\"\",\"name\":\"备用电池\",\"typeSpec\":{\"range\":[\"empty\",\"low\",\"high\",\"full\"],\"type\":\"enum\",\"typeDefaultValue\":\"empty\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"style\",\"description\":\"\",\"name\":\"风格\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}}]}]}"
  },
  "success": true,
  "t": 1708356160679,
  "tid": "b8762881cf3a11eeb4228e673063ebcd"
}
```

# Product ID

```
{
  "result": [
    {
      "active_time": 1701101701,
      "bind_space_id": "173359167",
      "category": "cwwsq",
      "create_time": 1701101701,
      "custom_name": "",
      "icon": "smart/icon/ay1543989738995Ij0in/2a9874753784ef33241cdddffe5fc2c6.png",
      "id": "bf72ab964d3e21aa56fwe0",
      "ip": "82.79.xxx.xxx",
      "is_online": true,
      "lat": "44.4300",
      "local_key": "xxxxxxxxxxxxxxxxx",
      "lon": "26.0400",
      "model": "",
      "name": "Smart feeder",
      "product_id": "wa8pwmxwnhpujmdq",
      "product_name": "海龙喂食器S56",
      "sub": false,
      "time_zone": "+02:00",
      "update_time": 1702724885,
      "uuid": "21e485c3b6e9dc38"
    }
  ],
  "success": true,
  "t": 1708356223287,
  "tid": "ddd9cb6fcf3a11eea1957edaaa357452"
}
```
# Information about how the device functions

Manual found online: https://www.manualslib.com/manual/3187110/Honeyguaridan-S56.html
Official site: https://www.honeyguardian.com/collections/feeder/products/honeyguardian-6l-smart-cat-feeder?variant=46640566272293

There is already a repo with the yaml file with all the DPs and description translated to english (https://github.com/Bellavista/Tuya-Local-Honeygaridan-S56):

```
name: HONEYGUARIDAN S56
products:
  - id: wa8pwmxwnhpujmdq
    model: S56
    manufacturer: HONEYGUARIDAN
primary_entity:
  entity: number
  category: config
  icon: "mdi:food-drumstick"
  name: Manual Feeding
  default: 1
  dps:
    - id: 3
      type: integer
      name: value
      range:
        min: 1
        max: 6
      mapping:
        - step: 1
      optional: true
secondary_entities:
  - entity: sensor
    force: true
    name: Planning
    icon: "mdi:calendar-multiselect"
    category: diagnostic
    dps:
      - id: 1
        type: integer
        name: sensor
  - entity: switch
    category: config
    name: Slow Feeding
    dps:
      - id: 6
        type: boolean
        name: switch
        mapping:
          - dps_val: false
            value: false
            icon: "mdi:play"
          - dps_val: true
            value: true
            icon: "mdi:fast-forward"
        optional: true
  - entity: sensor
    default: "0"
    force: true
    category: diagnostic
    class: enum
    icon: "mdi:alert-circle-outline"
    name: Error code
    readonly: true
    dps:
      - id: 14
        type: string
        name: sensor
        mapping:
          - dps_val: 0
            value: "OK"
          - dps_val: "food_run_out"
            value: "food_run_out"
          - dps_val: "ERR1"
            value: "ERR1 - TO DEFINE"
          - dps_val: "ERR3"
            value: "ERR3 - TO DEFINE"
          - dps_val: "ERR5"
            value: "ERR5 - TO DEFINE"
        optional: true
  - entity: number
    category: config
    default: 0
    force: true
    icon: "mdi:account-voice"
    name: Vocal Message
    dps:
      - id: 18
        type: intger
        name: value
        range:
          min: 1
          max: 10
        optional: true
  - entity: number
    category: diagnostic
    icon: "mdi:record-rec"
    readonly: true
    name: Meal Log
    dps:
      - id: 101
        type: integer
        name: value
        range:
          min: 1
          max: 48
        optional: true
  - entity: switch
    category: config
    name: Hour 12/24
    dps:
      - id: 102
        type: boolean
        name: switch
        mapping:
          - dps_val: false
            value: false
            icon: "mdi:hours-12"
          - dps_val: true
            value: true
            icon: "mdi:hours-24"
        optional: true
  - entity: sensor
    category: diagnostic
    default: "empty"
    class: enum
    icon: "mdi:alert-circle-outline"
    readonly: true
    name: Battery Level
    dps:
      - id: 103
        type: string
        name: sensor
        mapping:
          - dps_val: "empty"
            value: "EMPTY !!!"
            icon: "mdi:battery-alert-variant-outline"
          - dps_val: "low"
            value: "LOW !"
            icon: "mdi:battery-low"
          - dps_val: "High"
            value: "HIGH"
            icon: "mdi:battery-medium"
          - dps_val: "full"
            value: "FULL"
            icon: "mdi:battery-high"
        optional: true
  - entity: select
    category: config
    default: "1"
    icon: "mdi:palette-swatch-outline"
    name: App Style
    dps:
      - id: 104
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: "Dark"
          - dps_val: "2"
            value: "White"
          - dps_val: "3"
            value: "Ciano"
          - dps_val: "4"
            value: "Violet"
          - dps_val: "5"
            value: "Ciano-Violet"
        optional: true
```

**Comment by ciotorcristian** [comment]
Hello @make-all. Thank you for adding support for this pet feeder. I have manually downloaded the yaml file and added in the devices directory. I also restarted HA, but it still fails with the same error as if I did not add it at all. The log after I try to configure the device is still the same as the one provided earlier. I do not really know why it still fails as the yaml seems fine.

**Comment by make-all** [comment]
Using the dps from the log message above, I get the following result:
```
honeyguardian_s56_petfeeder matched 100%
  number_manual_feed:
   value: 1
   plan: None
  switch_slow_feeding:
    switch: False
  binary_sensor_problem:
    sensor: False
    fault_code: None
  number_voice_activations:
    value: 3
  sensor_meal_log:
    sensor: 2
  select_clock:
    option: 24 hour
  sensor_battery:
    sensor: 100
```

Maybe you did not install the file correctly, or the message is not exactly the same.
