### ISSUE TITLE
Request support for LEHMANN-LHOHC-2013C Radiator

### ISSUE THREAD

**Issue by ItsMe00007** [make-all/tuya-local#1737]
# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:97
Integration: Tuya Local (documentation, issues)
First occurred: 14:19:02 (1 occurrences)
Last logged: 14:19:02

Device matches LEHMANN-LHOHC-2013C Radiator with quality of 75%. DPS: {"updated_at": 1708175940.7645316, "1": false, "2": 25, "3": 15, "4": "standby", "5": "4", "9": false, "11": "0", "12": 0}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"ea8x7k\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"name\":\"目标温度\",\"typeSpec\":{\"max\":45,\"min\":5,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":5,\"unit\":\"°C\"}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"name\":\"当前温度\",\"typeSpec\":{\"max\":50,\"min\":-20,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":-20,\"unit\":\"°C\"}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"name\":\"工作模式\",\"typeSpec\":{\"range\":[\"smart\",\"auto\",\"standby\"],\"type\":\"enum\",\"typeDefaultValue\":\"smart\"}},
{\"abilityId\":5,\"accessMode\":\"rw\",\"code\":\"level\",\"description\":\"\",\"name\":\"档位\",\"typeSpec\":{\"range\":[\"1\",\"2\",\"3\",\"4\"],\"type\":\"enum\",\"typeDefaultValue\":\"1\"}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"anion\",\"description\":\"\",\"name\":\"风机\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"countdown\",\"description\":\"0：取消，1,2，....h计时\",\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\"],\"type\":\"enum\",\"typeDefaultValue\":\"0\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"\",\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},
{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"label\":[\"fault1\",\"fault2\",\"fault3\"],\"maxlen\":3,\"type\":\"bitmap\",\"typeDefaultValue\":0}}]}]}"
  },
  "success": true,
  "t": 1710183489700,
  "tid": "4d75653cdfd911ee91c03221dd841d9c"
}
```

# Product ID

"product_id": "wcpmk08nnnynbhy7",

# Information about how the device functions

https://www.amazon.de/gp/product/B0CJ5C3WV8/

The attached  LEHMANN-LHOHC-2013C Radiator.yaml works perfect for me except from this error in the System Log:

Entity None (<class 'custom_components.tuya_local.climate.TuyaLocalClimate'>) implements HVACMode(s): off, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/make-all/tuya-local/issues

```
name: LEHMANN Radiator
products:
  - id: bf5a1180dd10da416fdehu
    name: LEHMANN LHOHC-2013C
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:radiator-disabled"
        - dps_val: true
          value: heat
          icon: "mdi:radiator"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 5
        max: 37
      unit: C
    - id: 3
      type: integer
      name: current_temperature
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: auto
          value: "auto"
        - dps_val: smart
          value: "anti-frost"
        - dps_val: standby
          value: "Stop-Heat"
secondary_entities:
  - entity: select
    name: Power-Setting
    icon: "mdi:radiator"
    category: config
    dps:
      - id: 5
        type: string
        name: option
        mapping:
          - dps_val: 1
            value: "750W"
          - dps_val: 2
            value: "1250W"
          - dps_val: 3
            value: "2000W"
          - dps_val: 4
            value: "0W"
  - entity: switch
    name: Fan
    category: config
    icon: "mdi:fan"
    dps:
      - id: 9
        name: switch
        type: boolean
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 11
        type: string
        name: option
        mapping:
          - dps_val: 0
            value: "Off"
          - dps_val: 1
            value: 1 hour
          - dps_val: 2
            value: 2 hours
          - dps_val: 3
            value: 3 hours
          - dps_val: 4
            value: 4 hours
          - dps_val: 5
            value: 5 hours
          - dps_val: 6
            value: 6 hours
          - dps_val: 7
            value: 7 hours
          - dps_val: 8
            value: 8 hours
          - dps_val: 9
            value: 9 hours
          - dps_val: 10
            value: 10 hours
          - dps_val: 11
            value: 11 hours
          - dps_val: 12
            value: 12 hours
          - dps_val: 13
            value: 13 hours
          - dps_val: 14
            value: 14 hours
          - dps_val: 15
            value: 15 hours
          - dps_val: 16
            value: 16 hours
          - dps_val: 17
            value: 17 hours
          - dps_val: 18
            value: 18 hours
          - dps_val: 19
            value: 19 hours
          - dps_val: 20
            value: 20 hours
          - dps_val: 21
            value: 21 hours
          - dps_val: 22
            value: 22 hours
          - dps_val: 23
            value: 23 hours
          - dps_val: 24
            value: 24 hours
  - entity: sensor
    name: Timer remain
    icon: "mdi:timer"
    class: duration
    category: diagnostic
    dps:
      - id: 12
        type: integer
        name: sensor
        unit: min
```
