### ISSUE TITLE
Sensor name at device details

### ISSUE THREAD

**Issue by myhomeiot** [make-all/tuya-local#177]
Very strange happens with sensor name at device details screen, with this configuration sensor name shows ok:
```
name: Bresser ClimateConnect
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 55
      type: integer
      name: switch
secondary_entities:
  - entity: sensor
    name: Current Humidity
    class: humidity
    dps:
      - id: 2
        type: integer
        name: sensor
        class: measurement
        unit: "%"
        readonly: true
```
![capture](https://user-images.githubusercontent.com/70070601/172846272-3e533e0c-3acf-43b0-92b7-ae3ffa99589e.jpg)
If I change name from **Current Humidity** to **Current2 Humidity** (or anything else) then this shows:
![capture2](https://user-images.githubusercontent.com/70070601/172846320-8b56dc94-8eb8-4280-855b-b37d08b12fa6.jpg)
