### ISSUE TITLE
Request support for eMylo WiFi&RF 2 Gang

### ISSUE THREAD

**Issue by luis-guilherme** [make-all/tuya-local#1773]
# Config

filename: `emylo_wifi_and_rf_2gang.yaml`

```
name: eMylo 2 gang switch
products:
  - id: jupECyrdMrUifHd8
    name: eMylo WiFi&RF 2 Gang
primary_entity:
  entity: switch
  name: Switch 1
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: switch
    name: Switch 2
    dps:
      - id: 2
        name: switch
        type: boolean
```
