### ISSUE TITLE
New dehumidifier DYD-S20A432 (Eesee Adam)

### ISSUE THREAD

**Issue by yurgh** [make-all/tuya-local#180]
Hi, I picked up a dehumidifier to help drying the laundry; and would love to have it properly integrated into Home Assistant. I got it in Norway; but it's probably sold under various other names elsewhere.  Can it be done with the following info, or should I try to dig up something else?

Tuya product: DYD-S20A432 除湿机
OEM-name: Eesee Adam 
URL: https://eeese-aircare.com/adam/?lang=en

Installation log:
```
2022-06-11 13:47:25 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches mirabella_genio_usb with quality of 22%. DPS: {'1': True, '2': 50, '4': 'manual', '5': 'low', '14': False, '16': 56, '17': 'cancel', '18': 0, '19': 0, 'updated_at': 1654948043.8171365}
2022-06-11 13:47:25 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
2022-06-11 13:48:59 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches mirabella_genio_usb with quality of 22%. DPS: {'1': True, '2': 50, '4': 'manual', '5': 'low', '14': False, '16': 58, '17': 'cancel', '18': 0, '19': 0, 'updated_at': 1654948137.5356426}
2022-06-11 13:48:59 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

Tuya API Explorer Device Specificatin Attribute
```
{
  "result": {
    "category": "cs",
    "functions": [
      {
        "code": "fan_speed_enum",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"high\"]}"
      },
      {
        "code": "dehumidify_set_value",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":\"25\",\"max\":\"80\",\"scale\":\"0\",\"step\":\"5\"}"
      },
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "fan_speed_enum",
        "dp_id": 5,
        "type": "Enum",
        "values": "{\"range\":[\"low\",\"high\"]}"
      },
      {
        "code": "dehumidify_set_value",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":\"25\",\"max\":\"80\",\"scale\":\"0\",\"step\":\"5\"}"
      },
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "humidity_indoor",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":\"0\",\"max\":\"100\",\"scale\":\"0\",\"step\":\"1\"}"
      }
    ]
  },
  "success": true,
  "t": 1655032016318,
  "tid": "c5b4dfb9ea3f11eca25982f07e008233"
}
```

**Comment by make-all** [comment]
Thanks, this should be sufficient.

**Comment by yurgh** [comment]
I've been creating a definition for the device by shamelessly copy/pasting and tweaking from the other device definitions: thanks to the respective authors.

Also; added child lock, timer, and tank-full/missing, which was not in the description.

Two thing I wasn't able to fix was
1) that the device has two modes
DP 4: manual or laundry
DP 5: Fan speed low or high
I was only able to get fan speed showing. However, not a big deal as the laundry mode is just 25% target, fan high and a 6h timer... On my end I'll just remove the definition for DP 4 but maybe there is a way to have both show up on the control in Home Assistant? When laundry mode is active its not possible to set timer and fan speed.  (I'm always keeping this in manual mode for that reason)

2) the options in the timer list is not sorted so looks kind of messy.

Here goes the eesee_adam_dehumidifier.yaml:
```
name: Eesee Adam dehumidifier
primary_entity:
  entity: humidifier
  class: dehumidifier
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: false
          icon: "mdi:air-humidifier-off"
          icon_priority: 1
        - dps_val: true
          icon: "mdi:air-humidifier"
          icon_priority: 3
    - id: 4
      name: mode
      type: string
      mapping:
        - dps_val: "manual"
          value: "Manual"
        - dps_val: "laundry"
          value: "Dry clothes"
          icon: "mdi:tshirt-crew-outline"
          icon_priority: 5
    - id: 5
      name: mode
      type: string
      mapping:
        - dps_val: "low"
          value: "Low"
          icon: "mdi:fan-speed-1"
        - dps_val: "high"
          value: "High"
          icon: "mdi:fan-speed-3"
    - id: 2
      type: integer
      name: humidity
      range:
        min: 25
        max: 80
      mapping:
        - step: 5
    - id: 16
      name: current_humidity
      type: integer
secondary_entities:
  - entity: sensor
    name: Current Humidity
    class: humidity
    dps:
      - id: 16
        type: integer
        name: sensor
        unit: "%"
        class: measurement   
  - entity: binary_sensor
    name: Tank
    class: problem
    category: diagnostic
    dps:
      - id: 19
        type: integer
        name: sensor
        mapping:
          - dps_val: 0
            value: false
            icon: "mdi:cup-outline"
            icon_priority: 1
          - dps_val: 1
            value: true
            icon: "mdi:cup-water"
            icon_priority: 1
  - entity: lock
    name: Child Lock
    category: config
    dps:
      - id: 14
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 17
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "Off"
          - dps_val: "1h"
            value: "1 hour"
          - dps_val: "2h"
            value: "2 hours"
          - dps_val: "3h"
            value: "3 hours"
          - dps_val: "4h"
            value: "4 hours"
          - dps_val: "5h"
            value: "5 hours"
          - dps_val: "6h"
            value: "6 hours"
          - dps_val: "7h"
            value: "7 hours"
          - dps_val: "8h"
            value: "8 hours"
          - dps_val: "9h"
            value: "9 hours"
          - dps_val: "10h"
            value: "10 hours"
          - dps_val: "11h"
            value: "11 hours"
          - dps_val: "12h"
            value: "12 hours"
          - dps_val: "13h"
            value: "13 hours"
          - dps_val: "14h"
            value: "14 hours"
          - dps_val: "15h"
            value: "15 hours"
          - dps_val: "16h"
            value: "16 hours"
          - dps_val: "17h"
            value: "17 hours"
          - dps_val: "18h"
            value: "18 hours"
          - dps_val: "19h"
            value: "19 hours"
          - dps_val: "20h"
            value: "20 hours"
          - dps_val: "21h"
            value: "21 hours"
          - dps_val: "22h"
            value: "22 hours"
          - dps_val: "23h"
            value: "23 hours"
          - dps_val: "24h"
            value: "24 hours"
```
