### ISSUE TITLE
Request support for TD8 Doorbell with Camera and Siren

### ISSUE THREAD

**Issue by OsaedYahya** [make-all/tuya-local#1812]
Thank you for this amazing product, I've tried to implement this item but it has some issues or missing configurations

# Information about DPS mappings

 {
        "name": "Doorbell",
        "id": "xxxxxxxxxx",
        "key": "xxxxxxxxxx",
        "mac": "xxxxxxxxxx",
        "uuid": "xxxxxxxxxx",
        "category": "sp",
        "product_name": "Security Camera ",
        "product_id": "wih9ybttb42lxb1q",
        "biz_type": 18,
        "model": "TD8",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1514518688842pfRoq/82e25092f20b785f1cdc4556f488f1be.png",
        "mapping": {
            "101": {
                "code": "basic_indicator",
                "type": "Boolean",
                "values": {}
            },
            "103": {
                "code": "basic_flip",
                "type": "Boolean",
                "values": {}
            },
            "109": {
                "code": "sd_storge",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "110": {
                "code": "sd_status",
                "type": "Integer",
                "values": {
                    "min": 1,
                    "max": 5,
                    "scale": 0,
                    "step": 1
                }
            },
            "111": {
                "code": "sd_format",
                "type": "Boolean",
                "values": {}
            },
            "115": {
                "code": "movement_detect_pic",
                "type": "Raw",
                "values": {}
            },
            "117": {
                "code": "sd_format_state",
                "type": "Integer",
                "values": {
                    "min": -20000,
                    "max": 200000,
                    "scale": 0,
                    "step": 1
                }
            },
            "126": {
                "code": "battery_report_cap",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 15,
                    "scale": 0,
                    "step": 1
                }
            },
            "136": {
                "code": "doorbell_active",
                "type": "String",
                "values": "{\"maxlen\":255}"
            },
            "145": {
                "code": "wireless_electricity",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "146": {
                "code": "wireless_powermode",
                "type": "Enum",
                "values": {
                    "range": [
                        "0",
                        "1"
                    ]
                }
            },
            "147": {
                "code": "wireless_lowpower",
                "type": "Integer",
                "values": {
                    "min": 10,
                    "max": 50,
                    "scale": 0,
                    "step": 1
                }
            },
            "149": {
                "code": "wireless_awake",
                "type": "Boolean",
                "values": {}
            },
            "152": {
                "code": "pir_switch",
                "type": "Enum",
                "values": {
                    "range": [
                        "0",
                        "1",
                        "2",
                        "3"
                    ]
                }
            },
            "154": {
                "code": "doorbell_pic",
                "type": "Raw",
                "values": {}
            },
            "159": {
                "code": "siren_switch",
                "type": "Boolean",
                "values": {}
            },
            "160": {
                "code": "basic_device_volume",
                "type": "Integer",
                "values": {
                    "min": 1,
                    "max": 10,
                    "scale": 0,
                    "step": 1
                }
            },
            "170": {
                "code": "humanoid_filter",
                "type": "Boolean",
                "values": {}
            },
            "185": {
                "code": "alarm_message",
                "type": "String",
                "values": "{}"
            }
        }
    }

# Product ID

wih9ybttb42lxb1q

This is what I currently have as a new device
```
name: TD8 Doorbell
products:
  - id: wih9ybttb42lxb1q
    name: Security Camera
primary_entity:
  entity: camera
  dps:
    - id: 115
      name: snapshot
      type: base64
      optional: true
    - id: 134
      name: motion_enable
      type: boolean
    - id: 150
      name: record
      type: boolean
    - id: 101
      type: boolean
      name: basic_indicator
      optional: true
    - id: 159
      type: boolean
      name: siren_switch
      optional: true
secondary_entities:
  - entity: light
    name: Indicator
    category: config
    icon: "mdi:led-on"
    dps:
      - id: 101
        type: boolean
        name: basic_indicator
        optional: true
  - entity: switch
    name: Flip image
    icon: "mdi:flip-horizontal"
    category: config
    dps:
      - id: 103
        type: boolean
        name: basic_flip
        optional: true
  - entity: sensor
    name: SD capacity
    category: diagnostic
    dps:
      - id: 109
        type: string
        name: sd_storge
        optional: true
  - entity: sensor
    name: SD status
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sd_status
        optional: true
  - entity: button
    name: SD format
    category: config
    icon: "mdi:micro-sd"
    dps:
      - id: 111
        type: boolean
        name: sd_format
        optional: true
  - entity: sensor
    name: SD format state
    category: diagnostic
    dps:
      - id: 117
        type: integer
        name: sd_format_state
        optional: true
  - entity: button
    category: config
    dps:
      - id: 159
        type: boolean
        name: siren_switch
        optional: true
```
it's showing the camera and the siren switch works but is there no way to detect ringing? (it's supported in the app)
