### ISSUE TITLE
Request support for Bluetooth Door Lock

### ISSUE THREAD

**Issue by OsaedYahya** [make-all/tuya-local#1813]
# Information about DPS mappings

{
        "name": "Door",
        "id": "xxxxxxx",
        "key": "xxxxxxxxx",
        "mac": "xxxxxxxx",
        "uuid": "xxxxxxxx",
        "category": "jtmspro",
        "product_name": "Smart Lock",
        "product_id": "xicdxood",
        "biz_type": 18,
        "model": "C502",
        "sub": true,
        "icon": "https://images.tuyaeu.com/smart/program_category_icon/jtmspro.png",
        "node_id": "39d4c4d15050b51a",
        "mapping": {
            "1": {
                "code": "unlock_method_create",
                "type": "Raw",
                "values": {}
            },
            "2": {
                "code": "unlock_method_delete",
                "type": "Raw",
                "values": {}
            },
            "3": {
                "code": "unlock_method_modify",
                "type": "Raw",
                "values": {}
            },
            "8": {
                "code": "residual_electricity",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 100,
                    "scale": 0,
                    "step": 1
                }
            },
            "12": {
                "code": "unlock_fingerprint",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "13": {
                "code": "unlock_password",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "14": {
                "code": "unlock_dynamic",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "15": {
                "code": "unlock_card",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "19": {
                "code": "unlock_ble",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 999,
                    "scale": 0,
                    "step": 1
                }
            },
            "21": {
                "code": "alarm_lock",
                "type": "Enum",
                "values": {
                    "range": [
                        "wrong_finger",
                        "wrong_password",
                        "wrong_card",
                        "wrong_face",
                        "tongue_bad",
                        "too_hot",
                        "unclosed_time",
                        "tongue_not_out",
                        "pry",
                        "key_in",
                        "low_battery",
                        "power_off",
                        "shock",
                        "defense"
                    ]
                }
            },
            "24": {
                "code": "doorbell",
                "type": "Boolean",
                "values": {}
            },
            "28": {
                "code": "language",
                "type": "Enum",
                "values": {
                    "range": [
                        "chinese_simplified",
                        "english"
                    ]
                }
            },
            "31": {
                "code": "beep_volume",
                "type": "Enum",
                "values": {
                    "range": [
                        "mute",
                        "low",
                        "normal",
                        "high"
                    ]
                }
            },
            "44": {
                "code": "rtc_lock",
                "type": "Boolean",
                "values": {}
            },
            "54": {
                "code": "synch_method",
                "type": "Raw",
                "values": {}
            },
            "70": {
                "code": "check_code_set",
                "type": "Raw",
                "values": {}
            },
            "71": {
                "code": "ble_unlock_check",
                "type": "Raw",
                "values": {}
            }
        },
        "parent": ""
    }

# Product ID

xicdxood

# Information about how the device functions

This is a bluetooth door lock, I've tried to create the config file for it (was able to add it but it doesn't open or do anything just shows the battery)

```
name: Smart lock
products:
  - id: xicdxood
    name: Smart Lock
primary_entity:
  entity: lock
  dps:
    - id: 13
      name: unlock_password
      type: integer
      optional: true
      persist: false
    - id: 16
      name: unlock_key
      type: integer
      optional: true
      persist: false
    - id: 19
      name: unlock_ble
      type: integer
      optional: true
      persist: false
    - id: 21
      name: jammed
      type: string
      optional: true
      persist: false
      mapping:
        - dps_val: tongue_bad
          value: true
        - value: false
    - id: 43
      name: unlock_fingerprint
      type: integer
      optional: true
      persist: false
    - id: 47
      name: lock
      type: boolean
      readonly: true
    - id: 62
      name: unlock_app
      type: integer
      optional: true
      persist: false
    - id: 63
      name: unlock_voice
      type: integer
      optional: true
      persist: false
    - id: 105
      name: lock_record
      type: string
      optional: true
secondary_entities:
  - entity: sensor
    class: battery
    category: diagnostic
    dps:
      - id: 8
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: binary_sensor
    name: Wrong password
    class: problem
    category: diagnostic
    dps:
      - id: 21
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: wrong_password
            value: true
          - dps_val: "1"
            value: true
          - value: false
  - entity: binary_sensor
    class: tamper
    category: diagnostic
    dps:
      - id: 21
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: pry
            value: true
          - dps_val: "8"
            value: true
          - value: false
  - entity: binary_sensor
    class: battery
    category: diagnostic
    dps:
      - id: 21
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: low_battery
            value: true
          - dps_val: "10"
            value: true
          - dps_val: low_battery_keypad
          - value: false
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 21
        type: string
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: defense
            value: true
          - dps_val: "13"
            value: true
          - value: false
  - entity: binary_sensor
    name: Duress
    class: safety
    category: diagnostic
    dps:
      - id: 22
        type: boolean
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
  - entity: event
    class: doorbell
    category: diagnostic
    dps:
      - id: 24
        type: boolean
        name: event
        optional: true
        mapping:
          - dps_val: true
            value: ring
          - dps_val: false
            value: null
  - entity: binary_sensor
    name: Doorbell
    deprecated: event_doorbell
    class: sound
    category: diagnostic
    dps:
      - id: 24
        type: boolean
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
  - entity: number
    name: Doorbell volume
    category: config
    dps:
      - id: 27
        type: string
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
        mapping:
          - dps_val: mute
            value: 0
            icon: "mdi:volume-mute"
          - dps_val: voice
            value: 100
            icon: "mdi:volume-high"
  - entity: switch
    name: Auto lock
    category: config
    icon: "mdi:lock-reset"
    dps:
      - id: 33
        type: boolean
        name: switch
  - entity: number
    name: Auto lock delay
    category: config
    icon: "mdi:lock-clock"
    dps:
      - id: 36
        name: value
        type: integer
        range:
          min: 10
          max: 180
        mapping:
          - step: 10
        unit: s
  - entity: binary_sensor
    class: door
    category: diagnostic
    dps:
      - id: 40
        type: string
        name: sensor
        mapping:
          - dps_val: unknown
            value: null
          - dps_val: open
            value: true
          - dps_val: closed
            value: false
  - entity: binary_sensor
    name: Keypad reset
    class: running
    category: diagnostic
    dps:
      - id: 102
        type: boolean
        name: sensor
  - entity: sensor
    name: Keypad battery
    class: battery
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: binary_sensor
    class: connectivity
    category: diagnostic
    dps:
      - id: 107
        type: boolean
        name: sensor
```
