### ISSUE TITLE
Please help to add new device (check new device file)

### ISSUE THREAD

**Issue by Der-Nax** [make-all/tuya-local#192]
I have a new device power meter for 3 fases.
I try to make the new device file, but I did error. COuld you please check and show error.
```yaml
name: Power Clamp
primary_entity:
  entity: sensor
  class: energy
  dps:
    - id: 131
      type: energy
      name: total energy
      mapping:
        - scale: 100
      unit: kWh
      class: total_increasing
    - id: 132
      type: current
      name: total current
      mapping:
        - scale: 1000
      unit: A
    - id: 133
      type: power
      name: active power
      unit: W
    - id: 135
      type: frequency
      name: frequency
    - id: 136
      type: temperature
      name: temperature
      mapping:
        - scale: 10
secondary_entities:
  - entity: sensor
    category: diagnostic
    name: Voltage A
    dps:
      - id: 101
        name: sensor
        type: voltage
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    name: Current A
    dps:
      - id: 102
        name: sensor
        type: current
        unit: A
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: power
    name: Power A
    dps:
      - id: 103
        name: sensor
        type: power
        unit: W
  - entity: sensor
    category: diagnostic
    class: power_factor
    name: Power factor A
    dps:
      - id: 104
        name: sensor
        type: power_factor
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    class: energy
    name: Energy A
    dps:
      - id: 106
        name: sensor
        type: energy
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    name: Voltage B
    dps:
      - id: 111
        name: sensor
        type: voltage
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    name: Current B
    dps:
      - id: 112
        name: sensor
        type: current
        unit: A
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: power
    name: Power B
    dps:
      - id: 113
        name: sensor
        type: power
        unit: W
  - entity: sensor
    category: diagnostic
    class: power_factor
    name: Power factor B
    dps:
      - id: 114
        name: sensor
        type: power_factor
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    class: energy
    name: Energy B
    dps:
      - id: 116
        name: sensor
        type: energy
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    name: Voltage C
    dps:
      - id: 121
        name: sensor
        type: voltage
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    name: Current C
    dps:
      - id: 122
        name: sensor
        type: current
        unit: A
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: power
    name: Power C
    dps:
      - id: 123
        name: sensor
        type: power
        unit: W
  - entity: sensor
    category: diagnostic
    class: power_factor
    name: Power factor C
    dps:
      - id: 124
        name: sensor
        type: power_factor
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    class: energy
    name: Energy C
    dps:
      - id: 126
        name: sensor
        type: energy
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 100
```
About device:
I check it on localtuya and mapping all dps:
"model": "Power Clamp",
                            "dps_strings": [
                                "101 (value: 2284)",
                                "102 (value: 1073)",
                                "103 (value: 191)",
                                "104 (value: 78)",
                                "106 (value: 251)",
                                "111 (value: 2354)",
                                "112 (value: 748)",
                                "113 (value: 47)",
                                "114 (value: 100)",
                                "116 (value: 267)",
                                "121 (value: 2350)",
                                "122 (value: 753)",
                                "123 (value: 149)",
                                "124 (value: 84)",
                                "126 (value: 517)",
                                "131 (value: 1036)",
                                "132 (value: 2574)",
                                "133 (value: 188)",
                                "135 (value: 50)",
                                "136 (value: 390)"
                            ],
                            "entities": [
                                {
                                    "id": 101,
                                    "friendly_name": "F1_Voltage",
                                    "unit_of_measurement": "V",
                                    "device_class": "voltage",
                                    "scaling": 0.1,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 102,
                                    "friendly_name": "Current",
                                    "unit_of_measurement": "A",
                                    "device_class": "current",
                                    "scaling": 0.1,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 111,
                                    "friendly_name": "F2_Voltage",
                                    "unit_of_measurement": "V",
                                    "device_class": "voltage",
                                    "scaling": 0.1,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 121,
                                    "friendly_name": "F3_Voltage",
                                    "unit_of_measurement": "V",
                                    "device_class": "voltage",
                                    "scaling": 0.1,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 102,
                                    "friendly_name": "F1_Current",
                                    "unit_of_measurement": "A",
                                    "device_class": "current",
                                    "scaling": 0.001,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 112,
                                    "friendly_name": "F2_Current",
                                    "unit_of_measurement": "A",
                                    "device_class": "current",
                                    "scaling": 0.001,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 122,
                                    "friendly_name": "F3_Current",
                                    "unit_of_measurement": "A",
                                    "device_class": "current",
                                    "scaling": 0.001,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 103,
                                    "friendly_name": "F1_Power",
                                    "unit_of_measurement": "W",
                                    "device_class": "power",
                                    "platform": "sensor"
                                },
                                {
                                    "id": 104,
                                    "friendly_name": "F1_PowerFactor",
                                    "device_class": "power_factor",
                                    "scaling": 0.01,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 106,
                                    "friendly_name": "F1_Energy",
                                    "unit_of_measurement": "kWh",
                                    "device_class": "energy",
                                    "scaling": 0.01,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 113,
                                    "friendly_name": "F2_Power",
                                    "unit_of_measurement": "W",
                                    "device_class": "power",
                                    "platform": "sensor"
                                },
                                {
                                    "id": 114,
                                    "friendly_name": "F2_PowerFactor",
                                    "device_class": "power_factor",
                                    "scaling": 0.01,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 116,
                                    "friendly_name": "F2_Energy",
                                    "unit_of_measurement": "kWh",
                                    "device_class": "energy",
                                    "scaling": 0.01,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 123,
                                    "friendly_name": "F3_Power",
                                    "unit_of_measurement": "W",
                                    "device_class": "power",
                                    "platform": "sensor"
                                },
                                {
                                    "id": 124,
                                    "friendly_name": "F3_PowerFactor",
                                    "device_class": "power_factor",
                                    "scaling": 0.01,
                                    "platform": "sensor"
                                },
                                {
                                    "id": 126,
                                    "friendly_name": "F3_Energy",
                                    "unit_of_measurement": "kWh",
                                    "device_class": "energy",
                                    "scaling": 0.01,
                                    "platform": "sensor"
                                },
                              
                                }
                            ],
                            "product_key": "r64livttuufctble"
