### ISSUE TITLE
Request support for nybro_heater

### ISSUE THREAD

**Issue by Zylazy** [make-all/tuya-local#1978]
```
name: NYBRO heater
products:
  - id: ahzyjjcfbe1ehrbt
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          value: "heat"
    - id: 2
      name: temperature
      type: integer
      range:
        min: 5
        max: 35
    - id: 3
      name: current_temperature
      type: integer
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: low
          value: eco
        - dps_val: high
          value: boost
        - dps_val: af
          value: away
    - id: 12
      type: bitfield
      name: error
      mapping:
        - dps_val: 0
          value: "OK"
secondary_entities:
  - entity: binary_sensor
    name: Heating
    category: diagnostic
    dps:
      - id: 101
        type: boolean
        name: sensor
        mapping:
          - dps_val: on
            value: true
            icon: "mdi:radiator"
          - dps_val: off
            value: false
            icon: "mdi:radiator-disabled"
```
