### ISSUE TITLE
Request support for Embrighten Curtain Lights

### ISSUE THREAD

**Issue by cabmoomoo** [make-all/tuya-local#1989]
Below is my yaml file for controlling the Enbrighten Smart LED Wi-Fi Curtain Lights (Model 69278). DPs not covered include:
- "27": "Music Sync"
- "28": "Real-Time Adjustment"
- "58": "led number set"

This file was based on smart_led_strip.yaml, but modifications were required. The curtain lights lack temperature-based color control and they seem to use a proprietary (or at least non-standard) scene control method.
I attempted to decipher how their scenes are coded, but when I realized the color portion of the code can include a plus sign and some other symbols, I figured it was better for my sanity to assume it's encrypted or something goofy like that and leave it be. Instead, I simply recorded the scene DP values for all the included scenes in the app. 
The product id is not included as my tuya cloud trial has unfortunately expired.
```
name: Smart Curtain Lights
primary_entity:
  entity: light
  dps:
    - id: 20
      type: boolean
      name: switch
    - id: 21
      type: string
      name: color_mode
      mapping:
        - dps_val: colour
          value: hs
        - dps_val: scene
          value: Scene
    - id: 24
      name: rgbhsv
      type: hex
      optional: true
      format:
        - name: h
          bytes: 2
          range:
            min: 0
            max: 360
        - name: s
          bytes: 2
          range:
            min: 0
            max: 1000
        - name: v
          bytes: 2
          range:
            min: 0
            max: 1000
secondary_entities:
  - entity: number
    translation_key: timer
    category: config
    dps:
      - id: 26
        name: value
        type: integer
        unit: min
        optional: true
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
          - dps_val: null
  - entity: select
    name: Scene
    icon: "mdi:palette"
    category: config
    dps:
      - id: 56
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "AQAKMjIAAABkAABkAAAAAGQAeGQAAAAAZAA5BwAAAAA="
            value: "Holiday"
          - dps_val: "AQEKMjIAAABkAABkAAAAAGQAOQcAAAAAZAEsZAAAAAA="
            value: "Valentine's Day"
          - dps_val: "AQIKMjIAAABkAAhkAAAAAGIBGFgAAAAAZAAPZAAAAAA="
            value: "Halloween"
          - dps_val: "AQMKMjIAAABkAHhkAAAAAGQAOQcAAAAAXwCIYwAAAAA="
            value: "St. Patrick's Day"
          - dps_val: "AQQKMjIAAABkAABkAAAAAGQAOQcAAAAAZADwZAAAAAA="
            value: "July 4th"
          - dps_val: "AQUKMjIAAABkAHhkAAAAAGEAO2MAAAAAYgEYWAAAAAA="
            value: "Mardi Gras"
          - dps_val: "AQYKMjIAAABkAHhkAAAAAF8AiGMAAAAAXQC+ZAAAAABiARJVAAAAAGQBH0UAAAAAZAEsZAAAAAA="
            value: "Spring"
          - dps_val: "AQcKMjIAAABkAA9kAAAAAF0AvmQAAAAAYgAuZAAAAABSAL5kAAAAAGEAO2MAAAAAXwDYYQAAAAA="
            value: "Summer"
          - dps_val: "AQgKMjIAAABkAABkAAAAAGQACGQAAAAAYgAuZAAAAABhADtjAAAAAGQAD2QAAAAAZAEsZAAAAAA="
            value: "Autumn"
          - dps_val: "AQkKMjIAAABdAL5kAAAAAFIAvmQAAAAAZADwZAAAAABiARJVAAAAAF8A2GEAAAAAZAA5BwAAAAA="
            value: "Winter"
          - dps_val: "AQoKMjIAAABkAABkAAAAAGQACGQAAAAAZAAPZAAAAAA="
            value: "Fire"
          - dps_val: "AQsKMjIAAABiARJVAAAAAGQA8GQAAAAAYgAuZAAAAABhADtjAAAAAFIAvmQAAAAAXwDYYQAAAAA="
            value: "Storm"
          - dps_val: "AQwKMjIAAABkAA9kAAAAAFIAvmQAAAAAYgAuZAAAAABiARhYAAAAAF0AvmQAAAAAZAEfRQAAAAA="
            value: "Gaming"
          - dps_val: "AQ0KMjIAAABkAPBkAAAAAGIBElUAAAAAYgEYWAAAAAA="
            value: "Space"
          - dps_val: "AQ4KMjIAAABkAABkAAAAAGIBGFgAAAAAZADwZAAAAAA="
            value: "Dark"
          - dps_val: "AQ8KMjIAAABkAHhkAAAAAGIBElUAAAAAXwCIYwAAAABSAL5kAAAAAF0AvmQAAAAAXwDYYQAAAAA="
            value: "Aquatic"
          - dps_val: "ARAKMjIAAABkAABkAAAAAGEAO2MAAAAAZAB4ZAAAAABfANhhAAAAAGQA8GQAAAAAZAEsZAAAAAA="
            value: "Party"
          - dps_val: "AREKMjIAAABkAABkAAAAAGQAD2QAAAAAYQA7YwAAAABkAHhkAAAAAGQA8GQAAAAAYgESVQAAAABkAR9FAAAAAA=="
            value: "Rainbows"
```
