### ISSUE TITLE
Request support for [Hydrate Ultra Petoneer | Fresco | Pettadore EU pet fountain ]

### ISSUE THREAD

**Issue by malosaa** [make-all/tuya-local#2000]
This is the working config of the Ultra version of  Petoneer | Fresco | Pettadore EU pet fountain.
* Fixed Detected during adding

```
name: Hydrate Ultra
products:
  - id: cuw2k3ho3e25fade
    name: Hydrate Ultra

primary_entity:
  entity: switch
  icon: "mdi:water-pump"
  dps:
    - id: 101
      type: boolean
      name: switch

secondary_entities:
  - entity: light
    name: Led light
    icon: "mdi:brightness-6"
    category: config
    dps:
      - id: 102
        name: Led brightness
        type: integer
        unit: "%"
        range:
          min: 1
          max: 10
  - entity: button
    name: Reset Filter Alarm
    icon: "mdi:air-filter"
    category: config
    dps:
      - id: 104
        type: integer  # Assuming the reset value might be an integer operation
        name: button
  - entity: sensor
    name: Filter life
    icon: "mdi:air-filter"
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        precision: 0
        range:
          min: 0
          max: 43200
        mapping:
          - scale: 1440  # minutes => days
            invert: true
        unit: d
  - entity: button
    name: Reset Pump Alarm
    icon: "mdi:pump"
    category: config
    dps:
      - id: 105
        type: integer  # Assuming the reset value might be an integer operation
        name: button
  - entity: sensor
    name: Pump maintenance
    icon: "mdi:pump"
    category: diagnostic
    dps:
      - id: 105
        type: integer
        name: sensor
        precision: 0
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 1440
            invert: true
        unit: d
  - entity: sensor
    name: Water quality
    icon: "mdi:water"
    category: diagnostic
    dps:
      - id: 106
        type: integer
        name: sensor
        unit: TDS
  - entity: switch
    name: UV sterilization
    icon: "mdi:flash"
    category: config
    dps:
      - id: 107
        type: boolean
        name: switch
  - entity: sensor
    name: Water level
    icon: "mdi:water"
    category: diagnostic
    dps:
      - id: 108
        type: integer
        name: sensor
        mapping:
          - dps_val: 1
            value: 1
          - dps_val: 2
            value: 2
          - dps_val: 3
            value: 3
          - dps_val: 4
            value: 4
  - entity: sensor
    name: UV runtime
    icon: "mdi:timer-outline"
    category: diagnostic
    dps:
      - id: 109
        type: integer
        name: sensor
        unit: s

```

Everything works as expected, i did test it.
except the mapping part has issue's when changing value to text, it does return unknown.
so i kept it as a number, maybe someone can look at it.

Regards

![image](https://github.com/make-all/tuya-local/assets/13116501/9658a16a-2d45-4e08-843f-987863e30652)
The main device has also a brightness option, to control the brightness of the led.
The Fountain has no boolean for control the light so i added it to the power switch
![image](https://github.com/make-all/tuya-local/assets/13116501/a22d69a5-81b5-4de6-9ce5-4b16f1cb8e27)

Here the device details:

```
{
  "result": {
    "active_time": 1718020689,
    "bind_space_id": "21563324",
    "category": "cwysj",
    "create_time": 1619021013,
    "custom_name": "Hydrate Ultra",
    "icon": "smart/icon/1553052329qmoijlx7rqq_0.png",
    "id": "REDACTED",
    "ip": "REDACTED",
    "is_online": true,
    "lat": "REDACTED",
    "local_key": "REDACTED",
    "lon": "REDACTED",
    "model": "",
    "name": "Fresco Ultra",
    "product_id": "cuw2k3ho3e25fade",
    "product_name": "110002-宠物饮水机UV版(公共面板)",
    "sub": false,
    "time_zone": "+01:00",
    "update_time": 1718021124,
    "uuid": "REDACTED"
  },
  "success": true,
  "t": 1718129648886,
  "tid": "65757e17281e11ef90fe3eec9450b138"
}
```

I fixed the code now, it will be available during selection while adding the device
