### ISSUE TITLE
Request support for: [Minoston Wi-Fi 4 Hour Countdown Timer Switch]

### ISSUE THREAD

**Issue by tk627** [make-all/tuya-local#2013]
# Log Message

```
Device matches minoston_countdown_timer_switch with quality of 100%. DPS: {"updated_at": 1718392042.2216961, "1": false, "7": 0, "101": 300, "102": 600, "103": 1800, "104": 3600, "105": 7200, "106": 14400, "107": 100, "108": 1, "109": "on", "110": "on", "111": false}
```

# Information about DPS mappings

```
model: 
{
  modelId:00000490i1,
  services:
  [{
    actions:[],
    code:,
    description:,
    events:[],
    name:默认服务,
    properties: [
    {abilityId:1,accessMode:rw,code:switch_1,description:,extensions:{iconName:icon-power,attribute:1152},name:开关 1,typeSpec:{type:bool}},
    {abilityId:7,accessMode:rw,code:countdown_1,description:,extensions:{iconName:icon-dp_time2,attribute:1248},name:开关1倒计时,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:101,accessMode:rw,code:key_1,description:该值表示延迟关的时间， APP 会修改该值，所以固件应该订阅该值,name:按键1,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:102,accessMode:rw,code:key_2,description:,name:按键2,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:103,accessMode:rw,code:key_3,description:,name:按键3,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:104,accessMode:rw,code:key_4,description:,name:按键4,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:105,accessMode:rw,code:key_5,description:,name:按键5,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:106,accessMode:rw,code:key_6,description:,name:按键6,typeSpec:{type:value,max:86400,min:0,scale:0,step:1,unit:s}},
    {abilityId:107,accessMode:rw,code:led_brightness,description:按键，开关指示亮度,name:指示灯亮度,typeSpec:{type:value,max:100,min:0,scale:0,step:1,unit:}},
    {abilityId:108,accessMode:rw,code:active_key,description:指定当前生效的按键，用于 app 界面显示\\n 0 --- 表示当前没有按键事件\\n 1 --- 表示当前执行按键1 的倒计时,name:当前生效的按键,typeSpec:{type:value,max:6,min:0,scale:0,step:1,unit:}},
    {abilityId:109,accessMode:rw,code:power_status,description:标识开关状态：\\non --- 指示灯常亮\\nflicker --- 指示灯闪烁,name:开关状态指示灯,typeSpec:{type:enum,range:[on, flicker]}},
    {abilityId:110,accessMode:rw,code:countdown_status,description:标识倒计时按键状态：\\non --- 指示灯常亮\\nflicker --- 指示灯闪烁,name:倒计时按键状态指示灯,typeSpec:{type:enum,range:[on, flicker]}},
    {abilityId:111,accessMode:rw,code:alway_on,description:,name:常开,typeSpec:{type:bool}}]
  }]
}

```
Here is my minoston_countdown_timer_switch.yaml I wrote for it. Unfortunately, it doesn't use the push buttons, or show which button was pushed to start the timer, but it gives the switch on/off and the countdown timer.

minoston_countdown_timer_switch.yaml
```
name: Minoston Wi-Fi 4 Hour Countdown Timer Switch
products:
  - id: ae0y7quogjcnzery
    #   model: NHT06-WIFI
    name: Countdown Switch
#   DPS:
#     ID:1   false code:switch_1 type:bool
#     ID:7   0     code:countdown_1 type:value (max:86400,min:0,scale:0,step:1,unit:s)
#     ID:101 300   code:key_1 type:value
#     ID:102 600   code:key_2 type:value
#     ID:103 1800  code:key_3 type:value
#     ID:104 3600  code:key_4 type:value
#     ID:105 7200  code:key_5 type:value
#     ID:106 14400 code:key_6 type:value
#     ID:107 100   code:led_brightness type:value (max:100,min:0,scale:0,step:1)
#     ID:108 1     code:active_key type:value (max:6,min:0,scale:0,step:1)
#     ID:109 on    code:power_status type:enum (range:[on, flicker])
#     ID:110 on    code:countdown_status type:enum (range:[on, flicker])
#     ID:111 false code:alway_on type:bool
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 1
      name: switch
      type: boolean
    - id: 101
      name: 5 Min Button
      type: integer
    - id: 102
      name: 10 Min Button
      type: integer
    - id: 103
      name: 30 Min Button
      type: integer
    - id: 104
      name: 1 Hour Button
      type: integer
    - id: 105
      name: 2 Hour Button
      type: integer
    - id: 106
      name: 4 Hour Button
      type: integer
    - id: 107
      name: Brightness
      type: integer
      range:
        min: 0
        max: 100
    - id: 108
      name: option
      type: integer
      range:
        min: 0
        max: 6
    - id: 109
      name: option
      type: string
      mapping:
        - dps_val: "on"
          value: "On"
        - dps_val: "flicker"
          value: "Flicker"
    - id: 110
      name: option
      type: string
      mapping:
        - dps_val: "on"
          value: "On"
        - dps_val: "flicker"
          value: "Flicker"
    - id: 111
      name: Always On
      type: boolean
secondary_entities:
  - entity: number
    translation_key: timer
    category: config
    dps:
      - id: 7
        type: integer
        name: value
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 1
            step: 1

```

# Product ID

ae0y7quogjcnzery

# Information about how the device functions

[https://minoston.com/products/minoston-wifi-timer-switch-smart-countdown-timer-switch-5-15-30-minutes-1-2-4-hour-on-off-timer-switch-mt10w](url)
