### ISSUE TITLE
New device - Compteur Digital Electric (power meter 1 phase)

### ISSUE THREAD

**Issue by Der-Nax** [make-all/tuya-local#202]
I added new device. Please add in a new release.
```yaml
name: Compteur Digital Electric
primary_entity:
  entity: sensor
  class: energy
  dps:
    - id: 17
      type: integer
      name: sensor
      mapping:
        - scale: 100
      unit: kWh
      class: total_increasing
secondary_entities:
  - entity: sensor
    category: diagnostic
    name: Voltage
    class: voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    name: Current
    dps:
      - id: 18
        name: sensor
        type: integer
        unit: A
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    class: power
    name: Power
    dps:
      - id: 19
        name: sensor
        type: integer
        unit: W
```

I have unknow dps:

```
  - entity: sensor
    category: diagnostic
    name: unknown_21
    dps:
      - id: 21
        name: sensor
        type: integer
  - entity: sensor
    category: diagnostic
    name: unknown_22
    dps:
      - id: 22
        name: sensor
        type: integer
  - entity: sensor
    category: diagnostic
    name: unknown_23
    dps:
      - id: 23
        name: sensor
        type: integer
  - entity: sensor
    category: diagnostic
    name: unknown_24
    dps:
      - id: 24
        name: sensor
        type: integer
  - entity: sensor
    category: diagnostic
    name: unknown_25
    dps:
      - id: 25
        name: sensor
        type: integer
  - entity: sensor
    category: diagnostic
    name: unknown_26
    dps:
      - id: 26
        name: sensor
        type: integer
```

 but it is static and it don't exist in tuya iot portal.

Additional about device - "product_id": "1whdy4a8ypamjloi". I don't add this parameter into my config. You are owner of final product and I think that I should provide maximum information about it for you.
Thank you for you time and work!
