### ISSUE TITLE
localtuya.set_dp equivalent?

### ISSUE THREAD

**Issue by pergolafabio** [make-all/tuya-local#2025]
Hi, didnt use the template, since its more a question...

I am converting all my devices from localtuya, to tuya-local
For one device, i need to manually set the DP , it isnt auto discovered , its a petfeeder, if i want to give my cat 5 portions i did in localtuya  below, how can i do this in tuya-local?

```
      - service: localtuya.set_dp
        data:
          device_id: !secret tuya_petfeeder_id
          dp: 201
          value: 5
```
