### ISSUE TITLE
Add support for Zedar R600

### ISSUE THREAD

**Issue by lankhaar** [make-all/tuya-local#2072]
**Describe the bug**
After a clean install of tuya-local (and a fairly clean install of HA), I can't find the device I expected to find. I fill in all data (ip, protocol 3.3, local key) for my device (a robot vacuum cleaner) and the dps that are logged are in fact the dps I would expect from my robot vacuum so no issues there it seems, yet it will always suggest the same 6 devices (see screenshot) with none of them being a robot vacuum.

![image](https://github.com/make-all/tuya-local/assets/107768491/2a08b4f2-1a08-493b-a9e1-d8807c3774c7)

I have also added my own yaml file with my device id and configured all dps (it's almost identical to the device ID `kljjvealoaepeysi`, device "Kabum Smart 700 Rev 2023").

All the dps I find in the log match the one from the yaml file, yet it's not suggested as a device type.

**Additional context**
Logs:
![image](https://github.com/make-all/tuya-local/assets/107768491/929dd458-b169-4d9f-b91e-f6b84d063dd0)
```log
Device matches asc_wifi_circuit_breaker with quality of 19%. DPS: {"updated_at": 1719961775.8133426, "1": false, "2": false, "4": "smart", "5": "sleep", "6": 0, "7": 0, "8": 83, "9": "strong", "17": 7408, "19": 12808, "21": 7408, "23": 13678, "26": 4, "27": true, "28": 0, "45": true, "102": false, "105": false, "106": false, "107": false, "108": false}
```
```log
Detected blocking call to open inside the event loop by custom integration 'tuya_local' at custom_components/tuya_local/helpers/device_config.py, line 101: self._config = load_yaml(filename) (offender: /usr/src/homeassistant/homeassistant/util/yaml/loader.py, line 226: with open(fname, encoding="utf-8") as conf_file:), please create a bug report at https://github.com/make-all/tuya-local/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/tuya_local/config_flow.py", line 436, in async_step_local return await self.async_step_select_type() File "/config/custom_components/tuya_local/config_flow.py", line 474, in async_step_select_type async for type in self.device.async_possible_types(): File "/config/custom_components/tuya_local/device.py", line 360, in async_possible_types for match in possible_matches(cached_state): File "/config/custom_components/tuya_local/helpers/device_config.py", line 982, in possible_matches parsed = TuyaDeviceConfig(cfg) File "/config/custom_components/tuya_local/helpers/device_config.py", line 101, in __init__ self._config = load_yaml(filename)
```

**Comment by lankhaar** [comment]
@make-all , judging on the tags you've added/removed I don't think I made myself 100% clear.

The id that I mentioned (for Kabum Smart 700 Rev 2023) was just an example, but for me the search seems broken entierly, I can't seem to find ANY product. The search result will always be the same (19% match on `asc_wifi_circuit_breaker`).

I hope that clears some things up now :-)

**Comment by make-all** [comment]
You are correct that you are not making yourself clear.
You say "I can't seem to find ANY product", but your screenshot shows six possible matches found.
And now your complaint seems to be that you are not able to enter the else clause, which is the "can't find ANY product" case.

**Comment by lankhaar** [comment]
That was really helpfull, thanks @make-all !

This helped me doing some debugging and I managed to add the device now. I'm only left with a few more issues. Perhaps you could guide me into the right direction?

The vacuum is in an idle state, but here there's some sort of state which says error, however I'm not even sure what that card entry is;
![image](https://github.com/make-all/tuya-local/assets/107768491/346c2ba4-441b-4396-94bb-9fd472158fb7)

Also none of the commands work yet. I'll continue my troubleshooting, but I'd love to hear if you've got an idea :-D

**Comment by lankhaar** [comment]
I'm almost there, but I'm gonna need help with the final part. I think I've mapped all data, everything is showing correctly (except for that error from previous comment, but I'm not sure what you'd need for that). 
From what I can see my issues are only in the action (sending it out to clean, sending it to it's dock, etc.). On every action change, Tuya seems to be doing 3 things.. Changing the status (DP ID 5), changing the mode (DP ID 4), changing the power_go (DP ID 1)

![image](https://github.com/make-all/tuya-local/assets/107768491/247f5bd8-75bc-439f-907e-2a4ed942b8b8)

Hope you can help!

# Device ID
yiarxtixzkmnegxk

# YAML

```yaml
name: Robot vacuum
products:
  - id: yiarxtixzkmnegxk
    name: Zedar R600
primary_entity:
  entity: vacuum
  dps:
    - id: 1
      type: boolean
      optional: true
      name: activate
      mapping:
        - dps_val: false
          constraint: pause
          conditions:
            - dps_val: true
              value: false
            - dps_val: false
              value: false
              hidden: true
            - dps_val: null
              value: false
              hidden: true
        - dps_val: true
          constraint: pause
          conditions:
            - dps_val: false
              value: true
            - dps_val: true
              value: true
              hidden: true
            - dps_val: null
              value: true
              hidden: true
        - dps_val: null
          value: false
          hidden: true
    - id: 2
      type: boolean
      optional: true
      name: pause
    - id: 4
      type: string
      name: command
      mapping:
        - dps_val: smart
          value: smart
        - dps_val: chargego
          value: return_to_base
        - dps_val: zone
          value: zone
        - dps_val: pose
          value: go_to_position
        - dps_val: part
          value: room
    - id: 5
      type: string
      name: status
      mapping:
        - dps_val: standby
          value: standby
        - dps_val: smart
          value: cleaning
        - dps_val: smart_clean
          value: cleaning
        - dps_val: zone_clean
          value: cleaning
        - dps_val: part_clean
          value: cleaning
        - dps_val: cleaning
          value: cleaning
        - dps_val: paused
          value: paused
        - dps_val: goto_pos
          value: going_to_location
        - dps_val: pos_arrived
          value: on_location
        - dps_val: pos_unarrive
          value: cannot_find_location
        - dps_val: goto_charge
          value: returning
        - dps_val: charging
          value: charging
        - dps_val: charge_done
          value: charged
        - dps_val: sleep
          value: sleep
        - dps_val: select_room
          value: select_room
        - dps_val: wall_follow
          value: wall_follow
        - dps_val: direction_control
          value: direction_control
    - id: 9
      type: string
      name: fan_speed
      mapping:
        - dps_val: turnoff
          value: "Off"
        - dps_val: gentle
          value: Low
        - dps_val: normal
          value: Medium
        - dps_val: strong
          value: High
    - id: 11
      type: boolean
      optional: true
      name: locate
    - id: 12
      type: string
      optional: true
      name: direction_control
      mapping:
        - dps_val: forward
          value: forward
        - dps_val: backward
          value: reverse
        - dps_val: turn_left
          value: left
        - dps_val: turn_right
          value: right
        - dps_val: stop
          value: stop
    - id: 14
      type: string
      optional: true
      name: path_data
    - id: 15
      type: string
      optional: true
      name: complex_command
    - id: 16
      type: string
      optional: true
      name: request
      mapping:
        - dps_val: get_map
          value: Get map
        - dps_val: get_path
          value: Get path
        - dps_val: get_both
          value: Get both
    - id: 28
      type: bitfield
      name: error
      mapping:
        - dps_val: 0
          value: none
        - dps_val: 2
          value: left_wheel_hang
        - dps_val: 4
          value: main_brush_stuck
        - dps_val: 8
          value: right_wheel_hang
        - dps_val: 16
          value: left_wheel_stuck
        - dps_val: 32
          value: right_wheel_stuck
        - dps_val: 64
          value: cliff
        - dps_val: 128
          value: side_brush_stuck
        - dps_val: 512
          value: collision
        - dps_val: 1024
          value: dust_box_stuck
        - dps_val: 4096
          value: ground_check_failure
        - dps_val: 32768
          value: vacuum_motor_stuck
        - dps_val: 65536
          value: high_current
        - dps_val: 131072
          value: charge_port_closed
    # - id: 32
    #   type: string
    #   optional: true
    #   name: device_timer
    - id: 33
      type: string
      optional: true
      name: disturb_time_set
    # - id: 34
    #   type: string
    #   optional: true
    #   name: device_info
    - id: 35
      type: string
      optional: true
      name: voice_data
secondary_entities:
  - entity: button
    name: Start
    icon: "mdi:play"
    category: config
    dps:
      - id: 1
        type: boolean
        name: button
        optional: true
  - entity: button
    name: Pause
    category: config
    icon: "mdi:pause"
    dps:
      - id: 2
        type: boolean
        name: button
        optional: true
  - entity: button
    name: Dock
    category: config
    icon: "mdi:lightning-bolt"
    dps:
      - id: 3
        type: boolean
        name: button
        optional: true
  - entity: sensor
    name: Cleaning time
    class: duration
    category: diagnostic
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: min
        class: measurement
  - entity: sensor
    name: Cleaned area
    category: diagnostic
    icon: "mdi:floor-plan"
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: m2
  - entity: sensor
    class: battery
    dps:
      - id: 8
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: select
    name: Mopping
    icon: "mdi:cup-water"
    category: config
    dps:
      - id: 10
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: closed
            value: "Off"
          - dps_val: low
            value: Low
          - dps_val: middle
            value: Medium
          - dps_val: high
            value: High
          - dps_val: null
            value: "Off"
            hidden: true
  - entity: button
    name: Reset map
    category: config
    dps:
      - id: 13
        type: boolean
        name: button
        optional: true
  - entity: sensor
    name: Edge brush life
    class: duration
    category: diagnostic
    dps:
      - id: 17
        type: integer
        name: sensor
        unit: min
  - entity: button
    name: Edge brush reset
    class: restart
    category: config
    dps:
      - id: 18
        type: boolean
        name: button
        optional: true
  - entity: sensor
    name: Roll brush life
    class: duration
    category: diagnostic
    dps:
      - id: 19
        type: integer
        name: sensor
        unit: min
  - entity: button
    name: Roll brush reset
    class: restart
    category: config
    dps:
      - id: 20
        type: boolean
        name: button
        optional: true
  - entity: sensor
    name: Filter life
    class: duration
    category: diagnostic
    dps:
      - id: 21
        type: integer
        name: sensor
        unit: min
  - entity: button
    name: Filter reset
    class: restart
    category: config
    dps:
      - id: 22
        type: boolean
        name: button
        optional: true
  - entity: sensor
    name: Mop life
    class: duration
    category: diagnostic
    dps:
      - id: 23
        type: integer
        name: sensor
        unit: min
  - entity: button
    name: Mop reset
    class: restart
    category: config
    dps:
      - id: 24
        type: boolean
        name: button
        optional: true
  - entity: switch
    name: Do not disturb
    category: config
    dps:
      - id: 25
        type: boolean
        name: switch
        optional: true
        mapping:
          - dps_val: null
            value: false
            hidden: true
  - entity: number
    name: Volume
    category: config
    icon: "mdi:volume-high"
    dps:
      - id: 26
        type: integer
        name: value
        range:
          min: 0
          max: 10
        unit: "%"
        mapping:
          - scale: 0.1
```

**Comment by lankhaar** [comment]
@make-all , I can tell by the amount of "new device requests" that you're a busy man, so I'm happy to add support for this myself. It would be amazing if you could push me into the direction on how to debug though, because it could take me days finding it out on my own lol.

If I can get the commands to work, that would be amazing already. I already shared what's needed for that in my last comment.

Currently I have to get 2 things done I guess. When play button is hit, I should update the `command` to "smart" and switch `power_go` (aka `activate`) to true. I assume this is done through the mapping on the command? Would that look something like the following snippet? Or should this be configured on it's primary entity instead of on the command?

```yaml
  - entity: button
    name: Start
    icon: "mdi:play"
    category: config
    dps:
      - id: 1
        type: boolean
        name: button
        optional: true
        mapping:
          - dps_val: true
            constraint: command
            value: smart
```

Also I see one weird thing in the `activate` command. If I click the play button, you'll see that it will turn itself off again, I assume because it updates data from the device which never turned on. Not sure whether that is or is not intended. Could be intended because it technically never turns on (it never starts executing any kind of command).

https://github.com/make-all/tuya-local/assets/107768491/f9471125-ffae-47da-861b-81de68def70e

I do not see any messages in the log either, is there some kind of way to debug this? Maybe a way to see a response from the device after sending it a command?
