### ISSUE TITLE
Request support for LORATAP WiFi Smart Curtain

### ISSUE THREAD

**Issue by bergyb** [make-all/tuya-local#2077]
Please add LORATAP WiFi Smart Curtain . Thanks

```
name: Smart Curtain
products:
  - id: v7ooovn9oamttmre
    name: Smart Curtain
primary_entity:
  entity: cover
  class: shutter
  dps:
    - id: 1
      name: control
      type: string
      mapping:
        - dps_val: "open"
          value: open
        - dps_val: "close"
          value: close
        - dps_val: "stop"
          value: stop
    - id: 2
      name: position
      type: integer
      unit: "%"
      range:
        min: 0
        max: 100
      mapping:
        - scale: 0
        - step: 10
secondary_entities:
  - entity: switch
    category: config
    name: Reverse Motor Direction
    icon: "mdi:arrow-u-down-left"
    dps:
      - id: 8
        type: string
        name: switch
        mapping:
          - dps_val: "forward"
            value: false
          - dps_val: "back"
            value: true
  - entity: select
    name: Calibration
    category: config
    icon: "mdi:toggle-switch"
    dps:
      - id: 3
        name: option
        type: string
        mapping:
          - dps_val: "start"
            value: "On"
          - dps_val: "end"
            value: "Off"
```
