### ISSUE TITLE
New Device - Help with YAML -  Kogan Tower Heater KASTHFP2KWA

### ISSUE THREAD

**Issue by illuzn** [make-all/tuya-local#209]
This is for [Kogan SmarterHome™ 2000W Tower Heater Fireplace Effect KASTHFP2KWA](https://www.kogan.com/au/buy/kogan-smarterhome-2000w-tower-heater-fireplace-effect/)

The DPS schema is as follows:
```yaml
- dps: 1
  - type: boolean
  - description: Controls main power. true=on, false=off
- dps: 2
  - type: integer (10-35)
  - description: Thermostat. For heating functions, controls when the heating element is turned on/ off. 
- dps: 3
  - type: integer. read_only
  - description: Current Temperature
- dps: 4
  - type: string
  - description: Mode (only works if main power is on). FAN= fan_only, LOW=low_power_heat, HIGH= high_power_heat. N.B. Heat modes will be overridden by the thermostat automatically i.e. if the thermostat temperature is 24C and the current temperature is 22C the device will switch to low power automatically.
- dps: 8
  - type: boolean
  - description: Oscillation. true=on, false = off
- dps: 10
  - type: boolean
  - description: Configuration Setting. Turns on/ off the flame effect.
- dps: 19
  - type: string
  - description: Timer. cancel=off, otherwise accepts settings of "$h" where $ is an integer between 1 to 12.
- dps: 21
  - type integer
  - description: Unknown. Possibly error code or diagnostic.
```

I've given it my best go to create a yaml for this. However, need help with the following:
1. Is there a way to link DPS 1 and 4 so they are controlled by hvac_mode? Ideally would use the following table.

| hvac_mode | DPS1 | DPS4 |
|--------------|-------|-------|
| off | false | (ignored) |
| fan_only | true | FAN |
| heat | true | HIGH |
| dry | true | LOW |

The dry mode isn't strictly necessary here - but I assume there will be errors if LOW isn't assigned to anything.

2. I can't think of a way to get the timer working (not an essential function though).
3. The current temperature currently keeps on reporting even if the heater is off. This temperature is only updated if the heater/ fan is on. Is there a way to hide it if the main power is off?

[kogan_kasthfp2kwa_towerheater.zip](https://github.com/make-all/tuya-local/files/9173155/kogan_kasthfp2kwa_towerheater.zip)

**Comment by make-all** [comment]
1. That should work.  There are many devices using this pattern already to turn a boolean on/off and mode selection into a single hvac_mode on the Home Assistant side (most of the air conditioners/heatpumps work this way and could be used as an example).  I wouldn't use fan_mode for the name of the first dps though, that is reserved for fan high/low etc control, use something like "power", and set it to hidden.
2. This type of timer should work as a select entity. (for an example, see arlec_fan.yaml)
3. I think the following should work:
```
   mapping:
     - constraint: power
       conditions:
         - dps_val: off
           invalid: true
```

I guess it is a matter of preference, but the flame effect could be a light entity rather than a switch.
