### ISSUE TITLE
Request support for EV charger [AFYEEV 32A 22kw]

### ISSUE THREAD

**Issue by jmcollin78** [make-all/tuya-local#2108]
Hello, here is new device file for adding a AFYEEV 32A 22kw EV charger.
It could be great to integrate it directly into your devices directory.

```
name: EV charger
products:
  - id: aaaealnecwgwerjl
    name: AFYEEV 32A EV charger
primary_entity:
  entity: sensor
  class: enum
  name: Status
  icon: "mdi:ev-station"
  dps:
    - id: 3
      type: string
      name: sensor
      mapping:
        - dps_val: charger_free
          value: Disconnected
        - dps_val: charger_insert
          value: Connected
        - dps_val: charger_free_fault
          value: Fault (disconnected)
        - dps_val: charger_charging
          value: Charging
        - dps_val: charger_wait
          value: Waiting
        - dps_val: charger_end
          value: Charged
        - dps_val: charger_fault
          value: Fault
        - dps_val: charger_pause
          value: Pause
secondary_entities:
  - entity: number
    name: Set current
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 4
        type: integer
        name: value
        unit: A
        range:
          min: 6
          max: 16
  - entity: sensor
    icon: "mdi:flash"
    name: Single phase power
    class: power
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: W
        class: measurement
        precision: 1
        mapping:
          - scale: 3
  - entity: sensor
    icon: "mdi:flash"
    name: Total power
    class: power
    dps:
      - id: 9
        type: integer
        name: sensor
        unit: W
        class: measurement
        precision: 1
        mapping:
          - scale: 1
  - entity: sensor
    name: Fault reason
    icon: 'mdi:alert-outline'
    class: enum
    dps:
      - id: 10
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: "Ready"
          - dps_val: 1
            value: "Ov2 Cr Fault"
          - dps_val: 2
            value: "OV Vol"
          - dps_val: 4
            value: "Undervoltage alarm"
          - dps_val: 8
            value: "Contactor adhesion"
          - dps_val: 16
            value: "Contactor fault"
          - dps_val: 32
            value: "Earth fault"
          - dps_val: 64
            value: "Meter Hardware alarm"
          - dps_val: 128
            value: "Scram fault"
          - dps_val: 256
            value: "CP fault"
          - dps_val: 512
            value: "Meter Commu fault"
          - dps_val: 1024
            value: "Card reader fault"
          - dps_val: 2048
            value: "Cir short fault"
          - dps_val: 4096
            value: "Adhesion fault"
          - dps_val: 8192
            value: "Self test alarm"
          - dps_val: 16384
            value: "Leakage current fault"
  - entity: select
    name: Working mode
    icon: "mdi:list-box-outline"
    dps:
      - id: 14
        type: string
        name: option
        mapping:
          - dps_val: charge_now
            value: Charge now
          - dps_val: charge_pct
            value: Charge PCT
          - dps_val: charge_energy
            value: Charge energy
          - dps_val: charge_schedule
            value: Charge schedule
          - dps_val: charge_delay
            value: Charge delay
  - entity: switch
    name: Power switch
    icon: "mdi:power"
    dps:
      - id: 18
        type: boolean
        optional: true
        force: true
        name: switch
  - entity: sensor
    class: temperature
    name: Temperature
    # category: diagnostic
    dps:
      - id: 24
        type: integer
        name: sensor
        unit: °C
        class: measurement
        mapping:
          - scale: 1
  - entity: sensor
    name: Charge energy once
    class: energy
    dps:
      - id: 25
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        optional: true
        mapping:
          - scale: 2
  - entity: sensor
    class: enum
    name: Online state
    icon: "mdi:wifi"
    dps:
      - id: 27
        optional: true
        type: string
        name: sensor
        mapping:
          - dps_val: offline
            value: Offline
          - dps_val: online
            value: Online
  - entity: number
    name: Timer
    # category: config
    icon: "mdi:car-clock"
    dps:
      - id: 28
        type: integer
        name: value
        unit: h
        optional: true
        range:
          min: 0
          max: 15
```
