### ISSUE TITLE
Silvercrest kettle: Mapping mistakes

### ISSUE THREAD

**Issue by s-hutter** [make-all/tuya-local#2120]
Hey there, thanks for the great integration!
I recently bought a Silvercrest kettle and successfully integrated it using this repo. However, i noticed a few issues:

**Describe the bug**
- The kettle can be set to boil the water and then keep it warm, these values are mapped in reverse. The integration shows "Keep warm" while boiling up the water and switches to "Boil" as soon as the temperature is reached and the keep warm function activates.
- This integration restricts the temperature and keep warm times to steps of 5 °C and 30 min. Using the Tuya app, both settings have a step size of 1.

**To Reproduce**
Change temperature / set keep warm time, run and monitor device state.

**Expected behavior**
- Device state ("Keep warm"/"Boil") should be switched to match what the device is actually doing.
- Temperature and keep warm time settings should not be artificially restricted but allow using a step size of 1. I understand that such a granular control might not be necessary, but bigger custom step sizes can be achieved in different ways if the user wants to change the values manually in the UI. Especially the keep warm time step size of 30 min is quite high in the current version.

**Additional context**
I have adapted the device yaml as follows and it now works as expected:
```yaml
name: Silvercrest kettle
products:
  - id: il4ofqon04yai1xe
    name: WK0828RT
primary_entity:
  entity: water_heater
  icon: "mdi:kettle"
  dps:
    - id: 1
      type: boolean
      name: operation_mode
      mapping:
        - dps_val: false
          value: "Off"
        - dps_val: true
          constraint: warm
          conditions:
            - dps_val: false
              value: Boil
              # was: Keep warm
            - dps_val: true
              value: Keep warm
              # was: Boil
    - id: 2
      type: integer
      name: current_temperature
    - id: 8
      type: integer
      name: temperature
      unit: C
      range:
        min: 40
        max: 100
      mapping:
        - step: 1
          # was: 5
    - id: 13
      type: boolean
      name: warm
      optional: true
      hidden: true
      # One of these unknowns should be the "16 preset programs".
      # Both are numeric strings (so probably enums)
    - id: 15
      type: string
      name: unknown_15
    - id: 16
      type: string
      name: unknown_16
    - id: 103
      type: boolean
      name: unknown_103
    - id: 104
      type: integer
      name: unknown_104
secondary_entities:
  # Portal docs say there is a number to set, and also a countdown remaining.
  # This might be the remaining (log was 5, which is not a 30 minute step)
  # with the other unknown string above a 0/30/60/90/120 selection
  - entity: number
    name: Warm time
    category: config
    icon: "mdi:timer"
    dps:
      - id: 14
        type: integer
        name: value
        unit: min
        optional: true
        range:
          min: 0
          max: 120
        mapping:
          - step: 1
            # was: 30
  - entity: sensor
    translation_key: time_remaining
    class: duration
    category: diagnostic
    dps:
      - id: 18
        type: integer
        name: sensor
        unit: min
        optional: true

```
