### ISSUE TITLE
Request support for Noeifevo Q21W EV charger

### ISSUE THREAD

**Issue by sragas** [make-all/tuya-local#2130]
Hi,

attached a working config for Noeifevo Q21W EV charger.

https://www.noeifevo.de/products/noeifevo-q21w-mobile-wallbox-11kw-mit-app-fernsteuerung-5m-10m-typ2-cee16a-3phase-ladekabel-elektroauto

```
name: EV charger
products:
  - id: "bktb3jskdic1ar2t"
    name: "Noeifevo Q21W EV charger"
primary_entity:
  entity: sensor
  name: Charger State
  icon: "mdi:ev-station"
  class: enum
  dps:
    - id: 3 
      type: string
      name: sensor
      mapping:
        - dps_val: charger_charging
          value: Charging
        - dps_val: charger_free
          value: Available
        - dps_val: charger_insert
          value: Plugged in
        - dps_val: charger_free_fault
          value: Fault
        - dps_val: charger_wait
          value: Delaying
        - dps_val: charger_pause
          value: Paused
        - dps_val: charger_end
          value: Charged
        - dps_val: charger_fault
          value: Fault (plugged in)
    - id: 23  
      type: string
      name: system_version
secondary_entities:
  - entity: number
    name: Charging current
    category: config
    class: current
    icon: "mdi:ev-plug-type2"
    dps:
      - id: 4 
        type: integer
        name: value
        unit: A
        range:
          min: 6
          max: 16
  - entity: sensor
    class: power
    category: diagnostic
    dps:
      - id: 9
        type: integer
        name: sensor
        unit: kW
        class: measurement
        mapping:
          - scale: 1000
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 10  
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 10
        type: bitfield
        name: fault_code  
  - entity: select
    name: Charging mode
    icon: "mdi:ev-station"
    category: config
    dps:
      - id: 14 
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: charge_now
            value: Immediate
          - dps_val: charge_schedule
            value: Scheduled charge
  - entity: sensor
    name: Voltage A
    class: voltage
    dps:
      - id: 6  
        type: base64
        name: sensor
        optional: true
        unit: V
        mapping:
          - mask: "FFFF0000000000"
            scale: 10
  - entity: sensor
    name: Current A
    class: current
    dps:
      - id: 6  
        type: base64
        name: sensor
        optional: true
        unit: A
        mapping:
          - mask: "000000FFFF0000"
            scale: 1000
  - entity: sensor
    name: Power A
    class: power
    dps:
      - id: 6 
        type: base64
        name: sensor
        optional: true
        unit: kW
        mapping:
          - mask: "0000000000FFFF"
            scale: 1000
  - entity: sensor
    name: Voltage B
    class: voltage
    dps:
      - id: 7  
        type: base64
        name: sensor
        optional: true
        unit: V
        mapping:
          - mask: "FFFF0000000000"
            scale: 10
  - entity: sensor
    name: Current B
    class: current
    dps:
      - id: 7  
        type: base64
        name: sensor
        optional: true
        unit: A
        mapping:
          - mask: "000000FFFF0000"
            scale: 1000
  - entity: sensor
    name: Power B
    class: power
    dps:
      - id: 7  
        type: base64
        name: sensor
        optional: true
        unit: kW
        mapping:
          - mask: "0000000000FFFF"
            scale: 1000
  - entity: sensor
    name: Voltage C
    class: voltage
    dps:
      - id: 8  
        type: base64
        name: sensor
        optional: true
        unit: V
        mapping:
          - mask: "FFFF0000000000"
            scale: 10
  - entity: sensor
    name: Current C
    class: current
    dps:
      - id: 8 
        type: base64
        name: sensor
        optional: true
        unit: A
        mapping:
          - mask: "000000FFFF0000"
            scale: 1000
  - entity: sensor
    name: Power C
    class: power
    dps:
      - id: 8 
        type: base64
        name: sensor
        optional: true
        unit: kW
        mapping:
          - mask: "0000000000FFFF"
            scale: 1000
  - entity: sensor
    name: Schedule start
    icon: "mdi:battery-clock"
    dps:
      - id: 19
        type: base64
        name: sensor
        optional: true
        mapping:
          - mask: "FF00"
  - entity: sensor
    name: Schedule stop
    icon: "mdi:battery-clock-outline"
    dps:
      - id: 19
        type: base64
        name: sensor
        optional: true
        mapping:
          - mask: "00FF"
  - entity: switch
    icon: "mdi:ev-station"
    dps:
      - id: 18  
        type: boolean
        name: switch
```
