### ISSUE TITLE
anko kmart fan

### ISSUE THREAD

**Issue by hazell20** [make-all/tuya-local#22]
hey mate 
love your work wanted to know how I could go about adding a device I have Anko Kmart fan.
I have queried to dp ids have worked a couple out just wanted to find out how I can go about adding it

regards
rhys

**Comment by make-all** [comment]
Take a look at the custom_components/tuya_local/devices directory.  It will need a yaml file similar to the ones in there now - probably closest to the goldair_fan.yaml. Minimal would be a primary_entity of entity:fan, and each dps specified with its id, type, and name which should match the names for specific functions in custom_components/tuya_local/generic/fan.py.
It is best if you can specify all DPS in the yaml file, even if you don't know what the functions are for some of them, as it will help with device detection. With just 1 - 6, I think there might be a heater or two that clash.

**Comment by make-all** [comment]
Generally I would write a test for it as well, to make sure everything works as expected, the tests are in tests/devices, but to get it going quickly, it can be done later. Also, if it cannot be auto-detected due to DPS clashing with another device, I think it will need some work in the config related files, as currently they have a fixed list of options, and haven't yet been modified to take that list from the config files.

**Comment by hazell20** [comment]
Thank for the quick reply I had stated to look if I could edit the golder fan file. I will have a bit off a play with it post back if I have success so it can be added.

**Comment by make-all** [comment]
Based on the information you provided so far, and the manual here: https://www.kmart.com.au/wcsstore/Kmart/pdfs/42779896_Manual.pdf

I think the following should work (filename anko_fan.yaml)

```yaml
name: Anko Fan
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: normal
          value: normal
        - dps_val: nature
          value: nature
        - dps_val: sleep
          value: sleep
    - id: 3
      type: integer
      name: speed
      range:
        min: 1
        max: 8
      mapping:
        - scale: 0.08
    - id: 4
      type: string
      name: oscillate
      mapping:
        - dps_val: "auto"
          value: true
        - dps_val: "off"
          value: false
    - id: 6
      type: integer
      name: timer
```
