### ISSUE TITLE
Request support for Duux Bright Air Cleaner

### ISSUE THREAD

**Issue by bramhoosemans** [make-all/tuya-local#2269]
### Log message

```text
Device matches feit_dimmer with quality of 38%. DPS: {"updated_at": 1725448136.298892, "1": false, "2": 1, "4": "auto", "5": 100, "6": true, "11": false, "18": "cancel", "21": "great"}
```

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"000002q19i\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"pm25\",\"description\":\"\",\"name\":\"PM2.5\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"fan_speed_enum\",\"description\":\"自动，1,2,3,睡眠 \",\"name\":\"风速\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"auto\",\"1\",\"2\",\"3\",\"sleep\"]}},
{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"filter\",\"description\":\"\",\"name\":\"滤芯使用率\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"anion\",\"description\":\"\",\"name\":\"负离子\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"filter_reset\",\"description\":\"\",\"name\":\"滤芯复位\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"name\":\"倒计时\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cancel\",\"2h\",\"4h\",\"6h\",\"8h\"]}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"air_quality\",\"description\":\"优良差\",\"name\":\"空气质量\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"great\",\"good\",\"poor\"]}}]}]}"
  },
  "success": true,
  "t": 1723728662858,
  "tid": "9dcf40995b0a11ef95a3c283ae9aa908"
}
```

### Product ID

go2ndjijilncwuf7

### Product Name

Duux Bright

### Information about how the device functions

I have already written an integration for the Duux Bright myself. It matches 100% with the DPS and works fine, but I'm not a developer, so feedback is more than welcome!

```
name: Duux air cleaner
products:
  - id: go2ndjijilncwuf7
    name: Duux Bright
primary_entity:
  entity: switch
  icon: "mdi:air-purifier"
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: select
    name: Fan Speed
    class: enum
    icon: "mdi:auto-mode"
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: auto
            value: auto
          - dps_val: "1"
            value: "1"
          - dps_val: "2"
            value: "2"
          - dps_val: "3"
            value: "3"
          - dps_val: sleep
            value: sleep
  - entity: number
    name: PM2.5
    icon: "mdi:bacteria-outline"
    category: diagnostic
    dps:
      - id: 2
        type: integer
        name: value
        unit: "μg/m3"
        range:
          min: 0
          max: 999
  - entity: number
    name: Filter Usage
    icon: "mdi:air-filter"
    category: diagnostic
    dps:
      - id: 5
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
  - entity: switch
    name: Ionizer
    icon: "mdi:magnet-on"
    category: config
    dps:
      - id: 6
        type: boolean
        name: switch
  - entity: switch
    name: Replace Filter
    icon: "mdi:ticket-percent-outline"
    category: config
    dps:
      - id: 11
        type: boolean
        name: switch
  - entity: select
    name: Countdown
    icon: "mdi:timer-outline"
    class: enum
    category: config
    dps:
      - id: 18
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "Cancel"
          - dps_val: "2h"
            value: "2 hours"
          - dps_val: "4h"
            value: "4 hours"
          - dps_val: "6h"
            value: "6 hours"
          - dps_val: "8h"
            value: "8 hours"
  - entity: sensor
    name: Air Quality
    icon: "mdi:air-filter"
    class: enum
    category: diagnostic
    dps:
      - id: 21
        type: string
        name: sensor
        mapping:
          - dps_val: "great"
            value: "Great"
          - dps_val: "good"
            value: "Good"
          - dps_val: "poor"
            value: "Poor"
```
