### ISSUE TITLE
Request support for Klarstein Kraftwerk Smart

### ISSUE THREAD

**Issue by fmauNeko** [make-all/tuya-local#2312]
### Log message

```text
Device matches smartplug_usb with quality of 31%. DPS: {"updated_at": 1726579719.4110582, "1": false, "2": "fan", "3": "high", "4": 0, "6": false, "7": false, "8": 22, "9": 0, "11": 72, "12": true, "13": false, "14": false, "15": 0}
```

### DPS information

```text
{
  "modelId": "000004ki0y",
  "services": [
    {
      "actions": [],
      "code": "",
      "description": "",
      "events": [],
      "name": "默认服务",
      "properties": [
        {
          "abilityId": 1,
          "accessMode": "rw",
          "code": "power",
          "description": "机器开关功能",
          "extensions": { "attribute": "1" },
          "name": "开关",
          "typeSpec": { "type": "bool" }
        },
        {
          "abilityId": 2,
          "accessMode": "rw",
          "code": "mode",
          "description": "工作模式分为：自动、制冷、送风、除湿、制热",
          "name": "工作模式",
          "typeSpec": {
            "type": "enum",
            "range": ["auto", "cool", "fan", "dry", "heat"]
          }
        },
        {
          "abilityId": 3,
          "accessMode": "rw",
          "code": "speed",
          "description": "风速档位：低档、中档、高档",
          "name": "档位",
          "typeSpec": { "type": "enum", "range": ["low", "mid", "high"] }
        },
        {
          "abilityId": 4,
          "accessMode": "rw",
          "code": "timer",
          "description": "定时功能：可设定1-24小时开/关机及不定时",
          "name": "定时",
          "typeSpec": {
            "type": "value",
            "max": 24,
            "min": 0,
            "scale": 0,
            "step": 1,
            "unit": "h"
          }
        },
        {
          "abilityId": 5,
          "accessMode": "rw",
          "code": "temp_c_set",
          "description": "",
          "name": "温度",
          "typeSpec": {
            "type": "value",
            "max": 32,
            "min": 18,
            "scale": 0,
            "step": 1,
            "unit": "℃"
          }
        },
        {
          "abilityId": 6,
          "accessMode": "rw",
          "code": "sleep",
          "description": "",
          "name": "睡眠",
          "typeSpec": { "type": "bool" }
        },
        {
          "abilityId": 7,
          "accessMode": "rw",
          "code": "ion",
          "description": "负离子（光触媒）：开/关功能",
          "name": "负离子/光触媒功能",
          "typeSpec": { "type": "bool" }
        },
        {
          "abilityId": 8,
          "accessMode": "ro",
          "code": "temp_c_disp",
          "description": "",
          "name": "室内温度",
          "typeSpec": {
            "type": "value",
            "max": 50,
            "min": 0,
            "scale": 0,
            "step": 1,
            "unit": "℃"
          }
        },
        {
          "abilityId": 9,
          "accessMode": "ro",
          "code": "fault",
          "description": "full_water：满水报警；E1：室内温度传感器故障；E2：室内盘管传感器故障",
          "extensions": { "scope": "fault" },
          "name": "故障告警",
          "typeSpec": {
            "type": "bitmap",
            "label": ["full_water", "E1", "E2"],
            "maxlen": 3
          }
        },
        {
          "abilityId": 10,
          "accessMode": "rw",
          "code": "temp_f_set",
          "description": "",
          "name": "华氏温度设置",
          "typeSpec": {
            "type": "value",
            "max": 90,
            "min": 64,
            "scale": 0,
            "step": 1,
            "unit": "℉"
          }
        },
        {
          "abilityId": 11,
          "accessMode": "ro",
          "code": "temp_f_disp",
          "description": "",
          "name": "华氏温度显示",
          "typeSpec": {
            "type": "value",
            "max": 122,
            "min": 32,
            "scale": 0,
            "step": 1,
            "unit": "℉"
          }
        },
        {
          "abilityId": 12,
          "accessMode": "ro",
          "code": "ion_show",
          "description": "",
          "name": "是否显示负离子／光触媒",
          "typeSpec": { "type": "bool" }
        },
        {
          "abilityId": 13,
          "accessMode": "ro",
          "code": "mode_hot_show",
          "description": "",
          "name": "是否显示制热模式",
          "typeSpec": { "type": "bool" }
        },
        {
          "abilityId": 14,
          "accessMode": "rw",
          "code": "c_f_change",
          "description": "",
          "name": "华氏度摄氏度切换",
          "typeSpec": { "type": "bool" }
        },
        {
          "abilityId": 15,
          "accessMode": "ro",
          "code": "count_down",
          "description": "",
          "name": "倒计时剩余时间",
          "typeSpec": {
            "type": "value",
            "max": 1440,
            "min": 0,
            "scale": 0,
            "step": 1,
            "unit": ""
          }
        }
      ]
    }
  ]
}
```

### Product ID

1wfuo7w1yoejmgbn

### Product Name

Kraftwerk Smart

### Information about how the device functions

Mobile AC Unit

**Comment by fmauNeko** [comment]
Here's a YAML config for this device. It looks pretty similar to `duux_blizzard_portable_aircon` but with some small variations.

```yaml
name: Air conditioner
products:
  - id: 1wfuo7w1yoejmgbn
    name: Klarstein Kraftwerk Smart
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          constraint: mode
          conditions:
            - dps_val: auto
              value: heat_cool
            - dps_val: cool
              value: cool
            - dps_val: fan
              value: fan_only
            - dps_val: dry
              value: dry
    - id: 2
      type: string
      name: mode
      hidden: true
    - id: 3
      type: string
      name: fan_mode
      mapping:
        - dps_val: low
          constraint: hvac_mode
          conditions:
            - dps_val: false
              value: "off"
            - dps_val: true
              value: low
        - dps_val: mid
          constraint: hvac_mode
          conditions:
            - dps_val: false
              value: "off"
            - dps_val: true
              value: medium
        - dps_val: high
          constraint: hvac_mode
          conditions:
            - dps_val: false
              value: "off"
            - dps_val: true
              value: high
    - id: 5
      type: integer
      name: temperature
      optional: true
      range:
        min: 18
        max: 32
      mapping:
        - constraint: temperature_unit
          conditions:
            - dps_val: true
              value_redirect: temp_set_f
              range:
                min: 64
                max: 90
    - id: 6
      type: boolean
      name: preset_mode
      mapping:
        - dps_val: false
          value: none
        - dps_val: true
          value: sleep
    - id: 8
      type: integer
      name: current_temperature
      mapping:
        - constraint: temperature_unit
          conditions:
            - dps_val: true
              value_redirect: temp_current_f
    - id: 10
      type: integer
      name: temp_set_f
      optional: true
      range:
        min: 64
        max: 90
      hidden: true
    - id: 11
      type: integer
      name: temp_current_f
      hidden: true
    - id: 14
      type: boolean
      name: temperature_unit
      mapping:
        - dps_val: false
          value: C
        - dps_val: true
          value: F
secondary_entities:
  - entity: number
    translation_key: timer
    category: config
    dps:
      - id: 4
        type: integer
        name: value
        unit: h
        range:
          min: 0
          max: 24
  - entity: binary_sensor
    translation_key: tank_full
    category: diagnostic
    dps:
      - id: 9
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 1
            value: true
          - value: false
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 9
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - dps_val: 1
            value: false
          - value: true
  - entity: select
    translation_key: temperature_unit
    category: config
    dps:
      - id: 14
        type: boolean
        name: option
        mapping:
          - dps_val: false
            value: celsius
          - dps_val: true
            value: fahrenheit
  - entity: sensor
    translation_key: time_remaining
    class: duration
    category: diagnostic
    dps:
      - id: 15
        type: integer
        name: sensor
        unit: min
```
