### ISSUE TITLE
Siren WiFi STL ESP_65B419

### ISSUE THREAD

**Issue by VladimirTuzovGitHub** [make-all/tuya-local#2350]
### Log message

```text
Device matches zigbee_mir_te100ty_climate_sensor with quality of 100%. DPS: {"updated_at": 1727594590.9474046, "101": "4", "102": "3", "103": 15}

```

### DPS information

```
{"modelId":"0000000dn6","services":[{"actions":[],"code":"","description":"","events":[],"name":"默认服务","properties":[
{"abilityId":101,"accessMode":"ro","code":"BatteryStatus","description":"0：满电\n1：高\n2：中\n3：低\n4：外电","name":"电量状态","typeSpec":{"type":"enum","range":["0","1","2","3","4"]}},
{"abilityId":102,"accessMode":"rw","code":"Alarmtype","description":"每一种代表一种声音","name":"声音类型","typeSpec":{"type":"enum","range":["1","2","3","4","5","6","7","8","9","10"]}},
{"abilityId":103,"accessMode":"rw","code":"AlarmPeriod","description":"","name":"报警时长","typeSpec":{"type":"value","max":60,"min":0,"scale":0,"step":1,"unit":"秒"}},
{"abilityId":104,"accessMode":"rw","code":"AlarmSwitch","description":"","name":"报警开关","typeSpec":{"type":"bool"}}]}]}
```

<details>

```text
{
  "result": [
    {
      "active_time": 1702320185,
      "bind_space_id": "52420419",
      "category": "sgbj",
      "create_time": 1702283264,
      "custom_name": "",
      "icon": "smart/icon/1528364694thahb9sok2l_0.png",
      "id": "4825104784f3eb65b419",
      "ip": "188.124.246.***",
      "is_online": true,
      "lat": "49.8200",
      "local_key": "Zr;E3a_h=`OJ479***",
      "lon": "73.1200",
      "model": "",
      "name": "Siren",
      "product_id": "DYgId0sz6zWlmmYu",
      "product_name": "声光报警器",
      "sub": false,
      "time_zone": "+06:00",
      "update_time": 1712131102,
      "uuid": "4825104784f3eb65b419"
    }
  ],
  "success": true,
  "t": 1727548017173,
  "tid": "3e70a8377dc711efb77736033862a1ba"
}

{
  "result": [
    {
      "id": "4825104784f3eb65b419",
      "status": [
        {
          "code": "BatteryStatus",
          "value": "4"
        },
        {
          "code": "Alarmtype",
          "value": "10"
        },
        {
          "code": "AlarmPeriod",
          "value": 15
        },
        {
          "code": "AlarmSwitch",
          "value": false
        }
      ]
    }
  ],
  "success": true,
  "t": 1727548358325,
  "tid": "09c5a8a27dc811efbc016e7818a0f8a2"
}

{
  "result": {
    "category": "sgbj",
    "functions": [
      {
        "code": "Alarmtype",
        "desc": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}",
        "name": "声音类型",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "AlarmPeriod",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}",
        "name": "报警时长",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "AlarmSwitch",
        "desc": "{}",
        "name": "报警开关",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "Alarmtype",
        "name": "声音类型",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "BatteryStatus",
        "name": "电量状态",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}"
      },
      {
        "code": "AlarmSwitch",
        "name": "报警开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "AlarmPeriod",
        "name": "报警时长",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1727547969801,
  "tid": "223113707dc711ef88b02ac421ecbce6"
}

{
  "result": {
    "category": "sgbj",
    "functions": [
      {
        "code": "Alarmtype",
        "desc": "Alarmtype",
        "name": "Alarmtype",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}"
      },
      {
        "code": "AlarmPeriod",
        "desc": "AlarmPeriod",
        "name": "AlarmPeriod",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "AlarmSwitch",
        "desc": "AlarmSwitch",
        "name": "AlarmSwitch",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1727548275744,
  "tid": "d88eb64e7dc711efb77736033862a1ba"
}
```

</details>

### Product ID

DYgId0sz6zWlmmYu

### Product Name

STL Siren Alarm WiFi

### Information about how the device functions

My siren is very similar to this siren: https://sl.aliexpress.ru/p?key=3KRbrM9

**Comment by make-all** [comment]
You need to solve the communication issues before we can consider adding a new device

Possibly having it added to localtuya is what is preventing any other connections.

**Comment by VladimirTuzovGitHub** [comment]
@make-all Ok, I'll be happy to remove it from localtuya.

**Comment by VladimirTuzovGitHub** [comment]
@make-all I deleted the device from localtuya and now I can't add it to Tuya Local and also to localtuya. I tried to delete and add from the Tuya application, all without result. I remember earlier last year when I added it to localtuya there were also problems the first time adding this device with protocol 3.1, but now I've been trying for more than an hour and without results. Maybe you can tell me how else I can add to Tuya Local?

**Comment by make-all** [comment]
If it is battery powered, and connects to WiFi without a hub, then local use is futile (the cloud is the hub in that case). This may be why it isn't working well in localtuya and difficult to connect to both localtuya and tuya-local.

Otherwise, make sure that you force quit the app during device set up, after you have got the information from cloud, but before submitting that form with all the connection details, where it will test the device connection. If the device is one of these that will only accept one local connection, then the app may be blocking it.

**Comment by VladimirTuzovGitHub** [comment]
@make-all Managed to connect. Offers to select two types of device, ir_remote_sensors and zigbee_mir_te100ty_climate_sensor.
Log message:
Device matches zigbee_mir_te100ty_climate_sensor with quality of 100%. DPS: {"updated_at": 1727594590.9474046, "101": "4", "102": "3", "103": 15}

**Comment by make-all** [comment]
It looks like the info above came from iot.tuya.com, so if you have access, the QueryThingsDataModel API call results for the device would help a lot. The above data is missing the link between numeric indices in the log and the "code" in the cloud API, also that function may provide more details on how the "1", "2", "3"... values map to actual meanings.

**Comment by VladimirTuzovGitHub** [comment]
@make-all 
{
  "result": {
    "model": "{\"modelId\":\"0000000dn6\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"BatteryStatus\",\"description\":\"0：满电\\n1：高\\n2：中\\n3：低\\n4：外电\",\"name\":\"电量状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\"]}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"Alarmtype\",\"description\":\"每一种代表一种声音\",\"name\":\"声音类型\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\"]}},{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"AlarmPeriod\",\"description\":\"\",\"name\":\"报警时长\",\"typeSpec\":{\"type\":\"value\",\"max\":60,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"秒\"}},{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"AlarmSwitch\",\"description\":\"\",\"name\":\"报警开关\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1727600232783,
  "tid": "d1582a347e4011efbc016e7818a0f8a2"
}

**Comment by VladimirTuzovGitHub** [comment]
@make-all Hello! Judging by the status Done, as I understand it, the integration has apparently been implemented. Please tell me if I can check it somehow?

**Comment by VladimirTuzovGitHub** [comment]
@make-all Yes, I have already added it to custom_components/tuya_local/devices/stl_siren.yaml, but when adding a device it does not define the STL siren alarm configuration.
![image](https://github.com/user-attachments/assets/4ea0d196-39f8-4df1-95bf-c35c76f06416)

**Comment by make-all** [comment]
Apologies, I skipped testing the config against the log message at the top. I will debug it now.

**Comment by make-all** [comment]
Please try the latest version (or add `optional: true` by hand to stl_siren.yaml under `-id: 104`)

**Comment by VladimirTuzovGitHub** [comment]
@make-all Managed to add configuration. But, there is no setting for choosing alarm sound and sound time settings. Also, there is no information about battery charge, although tuya iot has this information.
![image](https://github.com/user-attachments/assets/3a23353d-375f-43b2-9ada-137ade2ce357)

 {
  "result": {
    "properties": [
      {
        "code": "BatteryStatus",
        "custom_name": "",
        "dp_id": 101,
        "time": 1728388865119,
        "type": "enum",
        "value": "4"
      },
      {
        "code": "Alarmtype",
        "custom_name": "",
        "dp_id": 102,
        "time": 1728388868399,
        "type": "enum",
        "value": "3"
      },
      {
        "code": "AlarmPeriod",
        "custom_name": "",
        "dp_id": 103,
        "time": 1728388873352,
        "type": "value",
        "value": 15
      },
      {
        "code": "AlarmSwitch",
        "custom_name": "",
        "dp_id": 104,
        "time": 1728388903851,
        "type": "bool",
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1728388932374,
  "tid": "26f32d37856d11efbc016e7818a0f8a2"
}

**Comment by make-all** [comment]
The battery status is split between two sensors: battery and plug (which you seem to have reassigned as connection). When the device is plugged in, it does not report anything about the battery.

The siren entity does not have a good UI in Home Assistant. But you can change the tone and duration by adding parameters to the siren.turn_on service.

**Comment by VladimirTuzovGitHub** [comment]
@make-all I think you could add the ability to change the tone and duration as a "select" setting. At least I did it before via localtuya integration.

**Comment by VladimirTuzovGitHub** [comment]
@make-all I took the liberty of correcting your configuration. I added two settings, checked and made sure that everything works. I think you can take it for the final configuration of this device.

```
name: Siren
products:
  - id: DYgId0sz6zWlmmYu
    name: STL siren Type
primary_entity:
  entity: siren
  dps:
    - id: 102
      type: string
      name: tone
      mapping:
        - dps_val: "1"
          value: "Type 1"
        - dps_val: "2"
          value: "Type 2"
        - dps_val: "3"
          value: "Type 3"
        - dps_val: "4"
          value: "Type 4"
        - dps_val: "5"
          value: "Type 5"
        - dps_val: "6"
          value: "Type 6"
        - dps_val: "7"
          value: "Type 7"
        - dps_val: "8"
          value: "Type 8"
        - dps_val: "9"
          value: "Type 9"
        - dps_val: "10"
          value: "Type 10"
    - id: 103
      type: integer
      name: duration
      range:
        min: 0
        max: 60
    - id: 104
      type: boolean
      optional: true
      name: switch
secondary_entities:
  - entity: sensor
    class: battery
    category: diagnostic
    dps:
      - id: 101
        type: string
        name: sensor
        unit: "%"
        mapping:
          - dps_val: "0"
            value: 100
          - dps_val: "1"
            value: 75
          - dps_val: "2"
            value: 50
          - dps_val: "3"
            value: 25
          - dps_val: "4"
            value: null
  - entity: select
    name: Alarmtype
    icon: "mdi:music"
    category: config
    dps:
      - id: 102
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: "Type 1"
          - dps_val: "2"
            value: "Type 2"
          - dps_val: "3"
            value: "Type 3"
          - dps_val: "4"
            value: "Type 4"
          - dps_val: "5"
            value: "Type 5"
          - dps_val: "6"
            value: "Type 6"
          - dps_val: "7"
            value: "Type 7"
          - dps_val: "8"
            value: "Type 8"
          - dps_val: "9"
            value: "Type 9"
          - dps_val: "10"
            value: "Type 10"
  - entity: number
    name: AlarmPeriod
    icon: "mdi:timer-music-outline"
    category: config
    dps:
      - id: 103
        type: integer
        name: value
        unit: sec
        range:
          min: 0
          max: 60
  - entity: binary_sensor
    class: plug
    category: diagnostic
    dps:
      - id: 101
        type: string
        name: sensor
        mapping:
          - dps_val: "4"
            value: true
          - value: false
```
   
   
![image](https://github.com/user-attachments/assets/44b25843-98b0-4d70-acf1-eb23b0b70aaf)

**Comment by VladimirTuzovGitHub** [comment]
@make-all Hello! The final integration is fully tested. Please update this code in custom_components/tuya_local/devices/stl_siren.yaml. Thank you very much for your support! As a token of my gratitude, I bought you a smartplug.
```
name: Siren
products:
  - id: DYgId0sz6zWlmmYu
    name: STL siren Type
primary_entity:
  entity: siren
  dps:
    - id: 102
      type: string
      name: tone
      mapping:
        - dps_val: "1"
          value: "Type 1"
        - dps_val: "2"
          value: "Type 2"
        - dps_val: "3"
          value: "Type 3"
        - dps_val: "4"
          value: "Type 4"
        - dps_val: "5"
          value: "Type 5"
        - dps_val: "6"
          value: "Type 6"
        - dps_val: "7"
          value: "Type 7"
        - dps_val: "8"
          value: "Type 8"
        - dps_val: "9"
          value: "Type 9"
        - dps_val: "10"
          value: "Type 10"
    - id: 103
      type: integer
      name: duration
      range:
        min: 0
        max: 60
    - id: 104
      type: boolean
      optional: true
      name: switch
secondary_entities:
  - entity: sensor
    class: battery
    category: diagnostic
    dps:
      - id: 101
        type: string
        name: sensor
        unit: "%"
        mapping:
          - dps_val: "0"
            value: 100
          - dps_val: "1"
            value: 75
          - dps_val: "2"
            value: 50
          - dps_val: "3"
            value: 25
          - dps_val: "4"
            value: null
  - entity: select
    name: Alarmtype
    icon: "mdi:music"
    category: config
    dps:
      - id: 102
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: "Type 1"
          - dps_val: "2"
            value: "Type 2"
          - dps_val: "3"
            value: "Type 3"
          - dps_val: "4"
            value: "Type 4"
          - dps_val: "5"
            value: "Type 5"
          - dps_val: "6"
            value: "Type 6"
          - dps_val: "7"
            value: "Type 7"
          - dps_val: "8"
            value: "Type 8"
          - dps_val: "9"
            value: "Type 9"
          - dps_val: "10"
            value: "Type 10"
  - entity: number
    name: AlarmPeriod
    icon: "mdi:timer-music-outline"
    category: config
    dps:
      - id: 103
        type: integer
        name: value
        unit: sec
        range:
          min: 0
          max: 60
  - entity: binary_sensor
    class: plug
    category: diagnostic
    dps:
      - id: 101
        type: string
        name: sensor
        mapping:
          - dps_val: "4"
            value: true
          - value: false
```
