### ISSUE TITLE
Request support for PoolEx Jetline Selection FI

### ISSUE THREAD

**Issue by develtop** [make-all/tuya-local#2401]
Hi,

i have created a custom configuration for this model. It is based on poolex_silverline_heatpump.yaml.
Works for more than a year now without any issue.

Would be great if it can be included in an upcoming release.

poolex_jetline_selection_fi.yaml

```
name: Poolex JetLine Selection FI heatpump
primary_entity:
  entity: climate
  translation_key: pool_heatpump
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
          icon_priority: 1
        - dps_val: true
          value: "heat"
          icon: "mdi:hot-tub"
          icon_priority: 3
    - id: 2
      name: temperature
      type: integer
      range:
        min: 8
        max: 40
    - id: 3
      name: current_temperature
      type: integer
    - id: 4
      name: preset_mode
      type: string
      mapping:
        - dps_val: Auto
          value: auto
        - dps_val: Cool
          value: smart_cool
        - dps_val: Heat
          value: smart_heat
        - dps_val: BoostHeat
          value: quick_heat
        - dps_val: BoostCool
          value: quick_cool
        - dps_val: SilentHeat
          value: quiet_heat
        - dps_val: SilentCool
          value: quiet_cool
    - id: 13
      type: integer
      name: error
      mapping:
        - dps_val: 0
          value: "OK"
        - dps_val: 256
          value: "Water Flow Protection"
          icon: "mdi:water-pump-off"
          icon_priority: 2
secondary_entities:
  - entity: binary_sensor
    name: Water flow
    class: problem
    category: diagnostic
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true

```

```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.10.2",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Atlantic/Canary",
    "os_name": "Linux",
    "os_version": "6.6.54-haos",
    "supervisor": "2024.10.2",
    "host_os": "Home Assistant OS 13.2",
    "docker_version": "27.2.0",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2024.10.0",
      "requirements": [
        "tinytuya==1.15.1",
        "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
      ]
    },
    "frigate": {
      "documentation": "https://github.com/blakeblackshear/frigate",
      "version": "5.4.0",
      "requirements": [
        "pytz"
      ]
    },
    "hpprinter": {
      "documentation": "https://github.com/elad-bar/ha-hpprinter",
      "version": "2.0.4",
      "requirements": [
        "xmltodict~=0.13.0",
        "flatten_json",
        "defusedxml"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "2.0.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "requirements": [
      "tinytuya==1.15.1",
      "tuya-device-sharing-sdk>=0.1.9,<=0.2.99"
    ],
    "version": "2024.10.0",
    "is_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 2.195799970650114e-05
    },
    "bd4924c5bd562c22cd98f079ae651db0": {
      "config_entry_setup": 1.5923282710000422
    }
  },
  "data": {
    "name": "Poolex Heatpump",
    "type": "poolex_jetline_selection_fi",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.3,
    "tinytuya_version": "1.15.1",
    "api_version_set": 3.3,
    "api_version_used": 3.3,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1729065822.279077,
      "1": false,
      "2": 24,
      "3": 25,
      "4": "Heat",
      "13": 0
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [],
    "home_assistant": {
      "name": "Poolex Heatpump",
      "name_by_user": "Poolw\u00e4rmepumpe",
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.poolwarmepumpe_water_flow",
            "state": "off",
            "attributes": {
              "device_class": "problem",
              "friendly_name": "Poolw\u00e4rmepumpe Water flow"
            },
            "last_changed": "2024-10-16T07:35:49.832920+00:00",
            "last_reported": "2024-10-16T07:35:49.832920+00:00",
            "last_updated": "2024-10-16T07:35:49.832920+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.poolwarmepumpe_none",
            "state": "off",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat"
              ],
              "min_temp": 8,
              "max_temp": 40,
              "target_temp_step": 1.0,
              "preset_modes": [
                "auto",
                "smart_cool",
                "smart_heat",
                "quick_heat",
                "quick_cool",
                "quiet_heat",
                "quiet_cool"
              ],
              "current_temperature": 25,
              "temperature": 24,
              "preset_mode": "smart_heat",
              "error": "OK",
              "icon": "mdi:hvac-off",
              "friendly_name": "Poolw\u00e4rmepumpe",
              "supported_features": 401
            },
            "last_changed": "2024-10-16T07:35:49.834407+00:00",
            "last_reported": "2024-10-16T07:35:49.834407+00:00",
            "last_updated": "2024-10-16T07:35:49.834407+00:00"
          }
        }
      ]
    }
  }
}
```
