### ISSUE TITLE
Request support for Poolex Jetline Selection FI heatpump

### ISSUE THREAD

**Issue by develtop** [make-all/tuya-local#2402]
### Log message

```text
-
```

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1728551017032,
        "type": "bool",
        "value": false
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 2,
        "time": 1728551017032,
        "type": "value",
        "value": 24
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 3,
        "time": 1729084101022,
        "type": "value",
        "value": 25
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 4,
        "time": 1728551017032,
        "type": "enum",
        "value": "Heat"
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 13,
        "time": 1728551017032,
        "type": "bitmap",
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1729084109800,
  "tid": "bcfe02818bbf11efb996167c3ccc11fc"
}
```

### Product ID

3bhylhz5zhogklel

### Product Name

Pool Heat Pump

### Information about how the device functions

Working configuration yaml for this device (working for one year now). Just wanted to share an include in upcoming release:

```
name: Poolex JetLine Selection FI heatpump
primary_entity:
  entity: climate
  translation_key: pool_heatpump
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
          icon: "mdi:hvac-off"
          icon_priority: 1
        - dps_val: true
          value: "heat"
          icon: "mdi:hot-tub"
          icon_priority: 3
    - id: 2
      name: temperature
      type: integer
      range:
        min: 8
        max: 40
    - id: 3
      name: current_temperature
      type: integer
    - id: 4
      name: preset_mode
      type: string
      mapping:
        - dps_val: Auto
          value: auto
        - dps_val: Cool
          value: smart_cool
        - dps_val: Heat
          value: smart_heat
        - dps_val: BoostHeat
          value: quick_heat
        - dps_val: BoostCool
          value: quick_cool
        - dps_val: SilentHeat
          value: quiet_heat
        - dps_val: SilentCool
          value: quiet_cool
    - id: 13
      type: integer
      name: error
      mapping:
        - dps_val: 0
          value: "OK"
        - dps_val: 256
          value: "Water Flow Protection"
          icon: "mdi:water-pump-off"
          icon_priority: 2
secondary_entities:
  - entity: binary_sensor
    name: Water flow
    class: problem
    category: diagnostic
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true

```
