### ISSUE TITLE
Change sunbeam_dual_bedwarmer.yaml for compatibility for new device version

### ISSUE THREAD

**Issue by backcountrymountains** [make-all/tuya-local#2451]
### Description

Newly purchased device wouldn't be discovered by tuya-local. New device doesn't expose DPiD: 8 locally. Change DPiD: 8 to ```optional: true``` gets tuya-local to recognize the device.
Change
```sunbeam_dual_bedwarmer.yaml``` from:
```
- entity: switch
    name: Combined preheat
    icon: "mdi:heatwave"
    category: config
    dps:
      - id: 8
        type: boolean
        name: switch
```
to:
```
- entity: switch
    name: Combined preheat
    icon: "mdi:heatwave"
    category: config
    dps:
      - id: 8
        type: boolean
        name: switch
        optional: true
```

### Steps to reproduce

try to link device to tuya-local

### Expected behaviour

link to tuya-local

### Additional context

Dunno if this is considered a bug or a new device because it's just a modification of an existing device. I had an electric blanket ```Sunbeam Bedding Dual - S1``` that worked fine with ```sunbeam_dual_bedwarmer.yaml``` but then I bought a ```Sunbeam Bedding Dual - S2``` that didn't link with tuya-local. 

Side note: the new blanket doesn't show all the DPiDs locally unless every feature of the blanket is turned on, so in addition to changing DPiD: 8 to optional, I also had to turn on all functions of the blanket so it responded with all of the other DPiDs. Maybe it's a pairing device "Pro Tip" to turn on all functions of a device to get it to link with tuya-local.

Thanks, this integration continues to be amazing!

tinytuya dp list for new version of blanket: 
(only DPiD 8 prevents linking with tuya-local, in my (limited) testing.)
```
"dps": {
                "dps": {
                    "4": "level_1",
                    "14": true,
                    "15": true,
                    "20": "level_1",
                    "21": "level_1",
                    "24": true,
                    "25": true,
                    "26": "10h",
                    "27": "10h",
                    "28": 35700,
                    "29": 35580,
                    "105": "ZONE_A"
                }
            },
```
tinytuya dp list for old version of blanket:
```
"dps": {
                "dps": {
                    "1": false,
                    "4": "level_4",
                    "8": false,
                    "13": 0,
                    "14": false,
                    "15": false,
                    "20": "level_4",
                    "21": "level_4",
                    "24": false,
                    "25": false,
                    "26": "10h",
                    "27": "10h",
                    "28": 36000,
                    "29": 36000,
                    "102": 0,
                    "103": 0,
                    "104": "User_Confirmation",
                    "105": "ZONE_A"
                }
            },
```

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.
