### ISSUE TITLE
Request support for Smart Drawer Lock

### ISSUE THREAD

**Issue by phid78** [make-all/tuya-local#2537]
### Log message

```text
2024-11-24 13:28:27.208 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches drawer_ble_lock with quality of 100%. DPS: {"updated_at": 1732451295.8184233, "8": 100, "33": true, "62": 256}
```

### Product ID

gumrixyt

### Product Name

Smart Drawer Lock HDY

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"e6gk9c\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"unlock_method_create\",\"description\":\"【必选】App蓝牙近距离连接门锁后，进行开门方式的创建操作，支持指纹、密码、卡等方式的创建\",\"name\":\"添加开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"unlock_method_delete\",\"description\":\"【必选】App蓝牙近距离连接门锁后，进行开门方式的删除操作，支持指纹、密码、卡等方式的删除\",\"name\":\"删除开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"unlock_method_modify\",\"description\":\"【必选】App蓝牙近距离连接门锁后，进行开门方式的修改操作，支持指纹、密码、卡等方式的修改\",\"name\":\"修改开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"bluetooth_unlock\",\"description\":\"【手机蓝牙解锁必选之一】\\n【支持蓝牙配件不能选择该dp，需选择dp71，与70&71互斥，2选1】\",\"extensions\":{\"attribute\":\"512\"},\"name\":\"蓝牙解锁\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":8,\"accessMode\":\"ro\",\"code\":\"residual_electricity\",\"description\":\"【可选，但必须二选一】门锁上报电量百分比。剩余电量与电量状态，必须二选一   默认值为-1时不显示电量\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"剩余电量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":-1,\"scale\":0,\"step\":1}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"unlock_ble\",\"description\":\"【必须】请用记录型上报成功上报：成员+蓝牙开门+时间（开门记录）\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"蓝牙解锁记录\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"alarm_lock\",\"description\":\"【必选】0=指纹试错报警、1=密码试错报警、2=卡试错报警、3=人脸试错报警、4=假锁（锁舌卡住）、5=高温报警、6=超时未关门、7=电子锁舌未弹出、8=防撬报警 、9=钥匙插入、10=低电报警、11=电量耗尽报警、12=震动报警、13=布防报警。低电暂时保留使用单独的dp点的设计，如果使用了本dp点中的低电报警值，就不要使用11dp点\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"门锁告警\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"low_battery\"]}},
{\"abilityId\":33,\"accessMode\":\"rw\",\"code\":\"automatic_lock\",\"description\":\"【可选】自动落锁/不自动落锁，仅使用本dp点，可以实现自动落锁与不自动落锁（即常开模式）的切换。\\n可选配合下一个dp自动落锁延时，组合实现以下功能：\\n1、默认时长自动落锁\\n2、指定时长自动落锁\\n3、常开\\n自动落锁最小延时1，最大1800，单位秒\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"自动落锁\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":35,\"accessMode\":\"rw\",\"code\":\"synch_member\",\"description\":\"下发同步指令：差量同步开门方式（即只同步指令中包含序号的开门方式）。注意：一条指令同步不能超过50字节，即同步硬件个数在50个以下\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"同步成员开门方式\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":60,\"accessMode\":\"rw\",\"code\":\"remote_no_pd_setkey\",\"description\":\"【不支持配件，支持音箱开门选该dp，与70&73互斥】\\n配置远程网络加密解锁是否开启，包含密钥（次数、时效、内容）\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1152\"},\"name\":\"配置新免密远程解锁\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":61,\"accessMode\":\"rw\",\"code\":\"remote_no_dp_key\",\"description\":\"远程网络解锁动作触发，下发和上报\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1152\"},\"name\":\"新免密远程开门-带密钥\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":62,\"accessMode\":\"ro\",\"code\":\"unlock_phone_remote\",\"description\":\"上报远程手机解锁的开门记录\",\"extensions\":{\"iconName\":\"icon-shouji\",\"attribute\":\"1152\",\"trigger\":\"direct\"},\"name\":\"远程解锁\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":0,\"step\":1}}]}]}"
  },
  "success": true,
  "t": 1732451019025,
  "tid": "ef4570cbaa5e11ef9fed422f202c76b8"
}
```

<details>

```text
{
  "result": {
    "properties": [
      {
        "code": "unlock_method_create",
        "custom_name": "",
        "dp_id": 1,
        "time": 1731093815694,
        "type": "raw"
      },
      {
        "code": "unlock_method_delete",
        "custom_name": "",
        "dp_id": 2,
        "time": 1731093815694,
        "type": "raw"
      },
      {
        "code": "unlock_method_modify",
        "custom_name": "",
        "dp_id": 3,
        "time": 1731094897000,
        "type": "raw",
        "value": "AAAAAv84/w=="
      },
      {
        "code": "bluetooth_unlock",
        "custom_name": "",
        "dp_id": 6,
        "time": 1732278217000,
        "type": "raw",
        "value": "AAE="
      },
      {
        "code": "residual_electricity",
        "custom_name": "",
        "dp_id": 8,
        "time": 1732290880156,
        "type": "value",
        "value": 100
      },
      {
        "code": "unlock_ble",
        "custom_name": "",
        "dp_id": 19,
        "time": 1732278216000,
        "type": "value",
        "value": 1
      },
      {
        "code": "alarm_lock",
        "custom_name": "",
        "dp_id": 21,
        "time": 1731093815694,
        "type": "enum",
        "value": "low_battery"
      },
      {
        "code": "automatic_lock",
        "custom_name": "",
        "dp_id": 33,
        "time": 1732290886422,
        "type": "bool",
        "value": false
      },
      {
        "code": "synch_member",
        "custom_name": "",
        "dp_id": 35,
        "time": 1731093815694,
        "type": "raw"
      },
      {
        "code": "remote_no_pd_setkey",
        "custom_name": "",
        "dp_id": 60,
        "time": 1732034631902,
        "type": "raw",
        "value": "AAAB"
      },
      {
        "code": "remote_no_dp_key",
        "custom_name": "",
        "dp_id": 61,
        "time": 1732269379737,
        "type": "raw",
        "value": "AAAB"
      },
      {
        "code": "unlock_phone_remote",
        "custom_name": "",
        "dp_id": 62,
        "time": 1732269378000,
        "type": "value",
        "value": 256
      }
    ]
  },

}
```

</details>

### Information about how the device functions

By adding it to tuya local, it is recognized as: 
gainsboroughliberty_entrance_lock or ble_orion_lock
But the unlocking does not work, however the battery charge seems ok

```
{
  "result": {
    "active_time": 1731093815,
    "bind_space_id": "165229675",
    "category": "ms",
    "create_time": 1731093815,
    "custom_name": "drawer",
    "icon": "smart/icon/ay15724370520156puq6/07f985f74744123b20bda1328920a217.jpg",
    "id": "bf99080zi7t6mgcr",
    "ip": "",
    "is_online": true,
    "lat": "xxxx",
    "local_key": "xxxx",
    "lon": "xxx",
    "model": "HDY",
    "name": "蓝牙柜锁",
    "product_id": "gumrixyt",
    "product_name": "蓝牙柜锁",
    "sub": true,
    "time_zone": "+01:00",
    "update_time": 1732034631,
    "uuid": "a5d6742addfb66ae"
  }
```

https://fr.aliexpress.com/item/1005006168688454.html

when i open or close trough tuya app, iot give this informations : 

```
2024-11-22 17:38:57 | Report | Code-free remote unlock | AAAB | device itself |  
2024-11-22 17:38:56 | Publish | Code-free remote unlock | AQABMDkzNDAxMDEAAQ== | unknown |  
2024-11-22 17:38:55 | Report | Remote unlock | 256 | device itself
```

**Comment by phid78** [comment]
I try to add it by myself : 

Device matches drawer_ble_lock with quality of 100%. DPS: {"updated_at": 1732369913.6094286, "8": 100, "33": true, "62": 256}

yaml : 
```
`name: Drawer BLE lock
products:
  - id: gumrixyt
    name: Drawer BLE lock
primary_entity:
  entity: lock
  dps:
    - id: 1
      type: string
      name: unlock_method_register
      optional: true
      sensitive: true
    - id: 2
      type: string
      name: unlock_method_delete
      optional: true
    - id: 19
      type: integer
      name: unlock_ble
      persist: false
      optional: true
    - id: 6
      type: string
      name: bluetooth_unlock
      optional: true
      sensitive: true
    - id: 60
      type: string
      name: remote_no_pd_setkey
      optional: true
      sensitive: true
    - id: 61
      type: string
      name: remote_no_dp_key
      optional: true
      sensitive: true
    - id: 62
      type: integer
      name: unlock_phone_remote
      persist: false
      optional: true
    - id: 33
      type: boolean
      name: lock
    - id: 54
      type: string
      name: sync_method
      optional: true
      sensitive: true
secondary_entities:
  - entity: sensor
    class: battery
    category: diagnostic
    dps:
      - id: 8
        type: integer
        name: sensor
        unit: "%"`
```

Battery ok, but unlock not : when i switch via HA, i ear a sound in the device but no unlock.
It seems tuya offer possibility to control lock now : 
![image](https://github.com/user-attachments/assets/007e0b16-4acb-4b14-bdd7-deaa40005238)

![image](https://github.com/user-attachments/assets/03bb3d99-bb30-48e3-b00e-9a55ad31903e)

![image](https://github.com/user-attachments/assets/04b1fb49-96cc-46ce-86c1-9c74d44aad00)

Tell me what can i do to help you more
