### ISSUE TITLE
Request support for SP-TVCM-510 Motorized TV mount

### ISSUE THREAD

**Issue by fantnhu** [make-all/tuya-local#2568]
### Log message

```text
Device matches None with quality of 0%. DPS: {"updated_at": 1732777923.6423845, "101": "cancel", "103": "cancel", "105": 0}
```

### Product ID

etspz6new8zb1vdy

### Product Name

SP-TVCM-510

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"000004blnw\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"move\",\"description\":\"五个控制按键，控制方式：举例如枚举值move_up（按键按下下发move_up指令，按键弹起下发cancel指令），另外4个按键同样按下下发功能指令，弹起下发cancel指令\",\"name\":\"运行控制\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"move_up\",\"move_down\",\"move_left\",\"move_right\",\"move_default\",\"cancel\"]}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"model_no\",\"description\":\"字符透传上报\",\"name\":\"型号\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"memory\",\"description\":\"三个记忆按键，三个调取按键，默认为cancel状态\",\"name\":\"位置记忆\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"mem1\",\"mem2\",\"mem3\",\"recall1\",\"recall2\",\"recall3\",\"cancel\"]}},
{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"fault_code_report\",\"description\":\"故障码上报后，APP界面进行弹窗提醒, fault_code1对应弹窗内容：An error occured. Please reset the system.     fault_code2对应弹窗内容：An error occured. Please contact your place of purchase for service or replacement. \",\"extensions\":{\"scope\":\"fault\"},\"name\":\"故障码上报\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"fault_code_1\",\"fault_code_2\"],\"maxlen\":2}}]}]}"
  },
  "success": true,
  "t": 1732778167513,
  "tid": "a2f1fd1aad5811efb8d3d602bee329f0"
}
```

<details>

```
{
    "startRowId": "",
    "pageNo": 1,
    "pageSize": 10,
    "code": "101",
    "startTime": 1732614423210,
    "endTime": 1732787223210,
    "projectCode": "p1634711730005vwqjqv",
    "sourceId": "eu1634579748440cAiog",
    "sourceType": "4",
    "deviceId": "xxx",
    "pageStartRow": "",
    "region": "EU"
}
{
    "startRowId": "",
    "pageNo": 1,
    "pageSize": 10,
    "code": "102",
    "startTime": 1732614532871,
    "endTime": 1732787332871,
    "projectCode": "p1634711730005vwqjqv",
    "sourceId": "eu1634579748440cAiog",
    "sourceType": "4",
    "deviceId": "xxx",
    "pageStartRow": "",
    "region": "EU"
}
{
    "startRowId": "",
    "pageNo": 1,
    "pageSize": 10,
    "code": "103",
    "startTime": 1732614552577,
    "endTime": 1732787352577,
    "projectCode": "p1634711730005vwqjqv",
    "sourceId": "eu1634579748440cAiog",
    "sourceType": "4",
    "deviceId": "xxx",
    "pageStartRow": "",
    "region": "EU"
}
{
    "startRowId": "",
    "pageNo": 1,
    "pageSize": 10,
    "code": "105",
    "startTime": 1732614570949,
    "endTime": 1732787370950,
    "projectCode": "p1634711730005vwqjqv",
    "sourceId": "eu1634579748440cAiog",
    "sourceType": "4",
    "deviceId": "xxx",
    "pageStartRow": "",
    "region": "EU"
}
```

</details>

### Information about how the device functions

This is a motorized ceiling TV mount. 
Brand: Speaka
Wifi (Tuya) + RF remote.
The app has right and left buttons, they don't work on this device (doesn't turn sideways). 

![image](https://github.com/user-attachments/assets/7773a1a7-363a-425b-ba46-2997aa1d8361)
![image](https://github.com/user-attachments/assets/67a53beb-b137-4ee3-9113-6bc2db24137e)

**Comment by fantnhu** [comment]
Hi! The product was new and the description in the webshop was incorrect. 
The device (unfortunately) uses Bluetooth. Is it possible to support it via the HUB? 
(Tuya BLE integration displays the device name but does not create an entity.)

**Comment by fantnhu** [comment]
Hi! I would like to help you integrate the devices. I created the .yaml for this tool based on "devices/README.md". I set the device category to "cover" (curtain, blind, motorized screen...).
I put the file in the devices directory, but even after restart I get the message "This device is not supported".
Any other dependencies to watch out for? Or should I fork the repo and install it?
I have a lot of Tuya tools, I'm happy to help with DP, but I can also make .yaml files.

Hi, Istvan

```
name: TV Console Mount
products:
  - id: etspz6new8zb1vdy
    name: SP-TVCM-510

primary_entity:
  entity: cover
  name: TV Mount
  dps: 
    - id: 101
      type: string 
      name: control
      mapping:
        - dps_val: move_up
          value: open
        - dps_val: move_down
          value: close
        - dps_val: cancel
          value: stop

secondary_entities:
  - entity: select
    name: Memory Position
    category: config
    dps:
      - id: 103
        type: string
        name: option
        mapping:
          - dps_val: mem1
            value: Save Position 1
          - dps_val: mem2
            value: Save Position 2
          - dps_val: mem3
            value: Save Position 3
          - dps_val: recall1
            value: Recall Position 1
          - dps_val: recall2
            value: Recall Position 2
          - dps_val: recall3
            value: Recall Position 3
          - dps_val: cancel
            value: Cancel

  - entity: sensor
    name: Model Number
    category: diagnostic
    dps:
      - id: 102
        type: string
        name: sensor

  - entity: binary_sensor
    name: Error Status
    class: problem
    category: diagnostic
    dps:
      - id: 105
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 105
        type: bitfield
        name: fault_code
```

**Comment by make-all** [comment]
You have dp 102 in your config, but it is not reported in the log.  Either remove it, or mark it as optional.
Personally I wouldn't implement a model number as an entity, as it will never change. Making it an attribute of the cover seems a better option.

**Comment by fantnhu** [comment]
> You have dp 102 in your config, but it is not reported in the log. Either remove it, or mark it as optional. Personally I wouldn't implement a model number as an entity, as it will never change. Making it an attribute of the cover seems a better option.

Thank you for your quick reply. I removed 102, so it works.
Moving up and down, moving to memory position, and saving position works. I have added icons and made the save to memory buttons

![image](https://github.com/user-attachments/assets/abc1b338-74c1-42c2-85ba-8d6e57516e87)

```
name: TV Console Mount
products:
  - id: etspz6new8zb1vdy
    name: SP-TVCM-510

primary_entity:
  entity: cover
  name: TV Mount
  icon: "mdi:television"
  dps:
    - id: 101
      type: string 
      name: control
      mapping:
        - dps_val: move_up
          value: open
        - dps_val: move_down
          value: close
        - dps_val: cancel
          value: stop
        - dps_val: move_left
          value: left
        - dps_val: move_right
          value: right
        - dps_val: move_default
          value: default
    - id: 102
      type: string
      name: model
      optional: true

secondary_entities:
  - entity: button
    name: Save Position 1
    category: config
    icon: "mdi:content-save"
    dps:
      - id: 103
        type: string
        name: button
        mapping:
          - dps_val: mem1
            value: true

  - entity: button
    name: Save Position 2
    category: config
    icon: "mdi:content-save"
    dps:
      - id: 103
        type: string
        name: button
        mapping:
          - dps_val: mem2
            value: true

  - entity: button
    name: Save Position 3
    category: config
    icon: "mdi:content-save"
    dps:
      - id: 103
        type: string
        name: button
        mapping:
          - dps_val: mem3
            value: true

  - entity: select
    name: Recall Position
    category: config
    icon: "mdi:restore"
    dps:
      - id: 103
        type: string
        name: option
        mapping:
          - dps_val: recall1
            value: Position 1
          - dps_val: recall2
            value: Position 2
          - dps_val: recall3
            value: Position 3
          - dps_val: cancel
            value: Cancel

  - entity: binary_sensor
    name: Error Status
    class: problem
    category: diagnostic
    dps:
      - id: 105
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 105
        type: bitfield
        name: fault_code
```
