### ISSUE TITLE
 PlantsIO Ivy Smart Planter display won't toggle off

### ISSUE THREAD

**Issue by thewade** [make-all/tuya-local#2589]
### Description

Continued from the conversation at https://github.com/make-all/tuya-local/discussions/2168.

When I try to toggle the display off, it briefly toggles off but then toggles back on.

The datapoint is correctly updated and the screen turns off. However in Home Assistant it shows as on with a brightness of 1%.

### Steps to reproduce

From the device config I press the slider to turn the device off.

### Expected behaviour

The device state should be 'off' and the toggle should be in the off state.

### Additional context

The entity:
```
  - entity: light
    translation_key: display
    category: config
    dps:
      - id: 101
        type: integer
        name: brightness
        range:
          min: 0
          max: 100
      - id: 135
        type: boolean
        name: available
        mapping:
          - dps_val: false
            value: true
          - dps_val: true
            value: false
```

A value of 0 is off, with 1-100 being brightness values.

When toggled off, in the device diagnostics with see the dps value is 0 which is correct.

```
  "data": {
    "name": "Smart Planter",
    "type": "plantsio_ivy_smart_planter",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.4,
    "tinytuya_version": "1.15.1",
    "api_version_set": 3.4,
    "api_version_used": 3.4,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1733082474.188266,
      "101": 0,
```
However under entities we see the state is 'on' and the brightness is 3.

```
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "light.smart_planter_display",
            "state": "on",
            "attributes": {
              "supported_color_modes": [
                "brightness"
              ],
              "color_mode": "brightness"
              "brightness": 3,
              "available": true,
              "friendly_name": "Smart Planter Display",
              "supported_features": 0
            },
            "last_changed": "2024-12-01T19:47:31.928245+00:00",
            "last_reported": "2024-12-01T19:47:54.194543+00:00",
            "last_updated": "2024-12-01T19:47:52.130242+00:00"
          }
```
Files:
- [tuya_local-01J34JHQWR7H35HR2C9ZYGECC3-Smart Planter-12e9e268e2429eb0c67e582320e15a81(14).json](https://github.com/user-attachments/files/17970225/tuya_local-01J34JHQWR7H35HR2C9ZYGECC3-Smart.Planter-12e9e268e2429eb0c67e582320e15a81.14.json)
- [home-assistant_tuya_local_2024-12-01T20-12-18.380Z.log](https://github.com/user-attachments/files/17970224/home-assistant_tuya_local_2024-12-01T20-12-18.380Z.log)

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [X] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [X] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.
