### ISSUE TITLE
Request support for EARU ELECTRONIC K6H-3A-W

### ISSUE THREAD

**Issue by Rain-ZG** [make-all/tuya-local#2602]
### Log message

```text
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:393
integration: Tuya Local (documentation, issues)
First occurred: 16:45:47 (1 occurrences)
Last logged: 16:45:47

Device matches avatto_me81_thermostat with quality of 93%. DPS: {"updated_at": 1733240742.625431, "1": true, "2": "manual", "10": true, "16": 230, "19": 300, "24": 245, "26": 160, "27": -4, "31": "5_2", "36": "close", "40": false, "43": "in", "44": 15, "45": 0}
```

### Product ID

v6foggibzyjlvwdx

### Product Name

EARU ELECTRONIC K6H-3A-W

### DPS information

```text
QueryThingsDataModel

{
  "result": {
    "model": "{\"modelId\":\"eyfl44\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power3\",\"attribute\":\"1024\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"manual\",\"auto\",\"eco\"]}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"frost\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-chushuang\",\"attribute\":\"1024\"},\"name\":\"防霜冻功能\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"scope\":\"\",\"attribute\":\"1024\"},\"name\":\"目标温度\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":0,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"upper_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"scope\":\"\",\"attribute\":\"1024\"},\"name\":\"设置温度上限\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":200,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu\",\"attribute\":\"1024\"},\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":990,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"lower_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1024\"},\"name\":\"设置温度下限\",\"typeSpec\":{\"type\":\"value\",\"max\":200,\"min\":0,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},
{\"abilityId\":27,\"accessMode\":\"rw\",\"code\":\"temp_correction\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu1\",\"attribute\":\"1024\"},\"name\":\"温度校准\",\"typeSpec\":{\"type\":\"value\",\"max\":9,\"min\":-9,\"scale\":0,\"step\":1}},
{\"abilityId\":30,\"accessMode\":\"rw\",\"code\":\"week_program3\",\"description\":\"每段定时可以设置第1，2字节时间，第3字节温度；6段定时；默认时间06:00 20°C ；08:00 15°C；11:30 15°C；13:30 15°C；17:00 22°C；22:00 15°C；每段占3个字节,工作日6时段，休息日2时段，总共8各时段，24字节\",\"extensions\":{\"iconName\":\"icon-zhouchengxu\",\"attribute\":\"1024\"},\"name\":\"周程序（工作日）\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":31,\"accessMode\":\"rw\",\"code\":\"work_days\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhouchengxu\",\"attribute\":\"1024\"},\"name\":\"工作日设置\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"off\",\"5_2\",\"6_1\",\"7\"]}},
{\"abilityId\":36,\"accessMode\":\"ro\",\"code\":\"valve_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tcl_function_vs2\",\"attribute\":\"1024\"},\"name\":\"加热状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"open\",\"close\"]}},
{\"abilityId\":39,\"accessMode\":\"rw\",\"code\":\"factory_reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-icon-test12\",\"attribute\":\"1024\"},\"name\":\"恢复出厂设置\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1024\"},\"name\":\"童锁\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":43,\"accessMode\":\"rw\",\"code\":\"sensor_choose\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-gongneng\",\"attribute\":\"1024\"},\"name\":\"传感器选择\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"in\",\"out\",\"ALL\"]}},
{\"abilityId\":44,\"accessMode\":\"rw\",\"code\":\"backlight\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-liangdu\",\"attribute\":\"1024\"},\"name\":\"背光亮度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":45,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_notice\",\"scope\":\"fault\",\"attribute\":\"1024\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"e1\",\"e2\",\"e3\",\"e4\"],\"maxlen\":4}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"outerlimit\",\"description\":\"\",\"name\":\"传感器限温值\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":20,\"scale\":0,\"step\":1,\"unit\":\"℃\"}}]}]}"
  },
  "success": true,
  "t": 1733236649601,
  "tid": "1f90a808b18411efabb796545b6d7eea"
}

```

Corrected YAML without TPD ID 30 and 101
```
name: Thermostat
products:
  - id: v6foggibzyjlvwdx
    name: EARU ELECTRONIC K6H-3A-W
primary_entity:
  entity: climate
  translation_key: thermostat
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: true
          value: heat
        - dps_val: false
          value: "off"
          icon: "mdi:radiator-disabled"
          icon_priority: 1
    - id: 2
      name: preset_mode
      type: string
      mapping:
        - dps_val: auto
          value: program
        - dps_val: manual
          value: manual
    - id: 16
      type: value
      name: temperature
      unit: C
      range:
        min: 0
        max: 900
      mapping:
        - scale: 10
          step: 5
    - id: 19
      type: integer
      name: max_temperature
      range:
        min: 200
        max: 900
      mapping:
        - scale: 10
    - id: 24
      type: integer
      name: current_temperature
      range:
        min: 0
        max: 990
      mapping:
        - scale: 10
    - id: 26
      optional: true
      type: integer
      name: min_temperature
      range:
        min: 0
        max: 200
      mapping:
        - scale: 10
    - id: 36
      type: string
      name: hvac_action
      mapping:
        - dps_val: close
          icon: "mdi:radiator-disabled"
          icon_priority: 2
          value: idle
        - dps_val: open
          icon: "mdi:radiator"
          icon_priority: 2
          value: heating
secondary_entities:
  - entity: number
    name: Calibration offset
    category: config
    icon: "mdi:thermometer"
    dps:
      - id: 27
        type: integer
        name: value
        unit: C
        range:
          min: -9
          max: 9
  - entity: switch
    translation_key: anti_frost
    category: config
    dps:
      - id: 10
        type: boolean
        name: switch
  - entity: lock
    translation_key: child_lock
    category: config
    dps:
      - id: 40
        optional: true
        type: boolean
        name: lock
  - entity: select
    name: Sensor selection
    category: config
    dps:
      - id: 43
        type: string
        name: option
        mapping:
          - dps_val: in
            icon: "mdi:gauge"
            value: Internal
          - dps_val: out
            icon: "mdi:thermometer-chevron-down"
            value: External
          - dps_val: all
            icon: "mdi:thermometer"
            value: Both
  - entity: binary_sensor
    category: diagnostic
    class: problem
    dps:
      - id: 45
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 45
        name: fault_code
        type: bitfield
  - entity: number
    name: Maximum temperature
    category: config
    class: temperature
    icon: "mdi:thermometer-chevron-up"
    dps:
      - id: 19
        type: integer
        name: value
        unit: C
        range:
          min: 200
          max: 900
        mapping:
          - scale: 10
            step: 10
  - entity: number
    name: Minimum temperature
    category: config
    class: temperature
    icon: "mdi:thermometer-chevron-down"
    dps:
      - id: 26
        optional: true
        name: value
        type: integer
        unit: C
        range:
          min: 0
          max: 200
        mapping:
          - scale: 10
            step: 10
  - entity: button
    name: Reset
    category: config
    class: restart
    dps:
      - id: 39
        name: button
        type: boolean
        optional: true
  - entity: select
    name: Working week
    icon: "mdi:calendar-clock"
    category: config
    dps:
      - id: 31
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "00"
            value: "Off"
          - dps_val: "5_2"
            value: "5 days"
          - dps_val: "6_1"
            value: "6 days"
          - dps_val: "70"
            value: "7 days"
  - entity: light
    name: Backlight
    category: config
    dps:
      - id: 44
        type: integer
        name: brightness
        optional: true
        range:
          min: 0
          max: 100
```

### Information about how the device functions

This is standard thermostat. I got it to work with multi_leaf_dy_107_thermostat.yaml but values for temperatures were wrong. Everything else looks good. In DPS information I have included edited yaml file which I am using for this device and where values for temperatures are corrected.
Two DPS IDs are missing from config, ID 30 and id 101. For that reasons I am also including data from QueryThingsDataModel
