### ISSUE TITLE
Request support for brizlabs string lights

### ISSUE THREAD

**Issue by TimPasquini** [make-all/tuya-local#2609]
### Log message

```text
2024-12-04 11:19:34.738 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding Brizlabs M5 RGB String Lights device with product id dakqi22zvrfeomry
2024-12-04 11:19:34.738 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches enbrighten_curtainlights with quality of 100%. DPS: {"updated_at": 1733329170.375351, "20": true, "21": "colour", "24": "016403e803e8"}
2024-12-04 11:19:34.738 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
```

### Product ID

dakqi22zvrfeomry

### Product Name

Brizlabs M5 RGB String Lights

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"ep70i8\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_led\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"1029\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1024\"},\"name\":\"模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}},{\"abilityId\":24,\"accessMode\":\"rw\",\"code\":\"colour_data\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-yanse\",\"attribute\":\"1152\"},\"name\":\"彩光\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":27,\"accessMode\":\"wr\",\"code\":\"music_data\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mic\",\"attribute\":\"1024\"},\"name\":\"音乐律动\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":28,\"accessMode\":\"wr\",\"code\":\"control_data\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_box2\",\"attribute\":\"1024\"},\"name\":\"调节\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"m0\",\"description\":\"\",\"name\":\"M0\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},{\"abilityId\":121,\"accessMode\":\"rw\",\"code\":\"lightmic_music_data\",\"description\":\"\",\"name\":\"麦克风音乐律动\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}}]}]}"
  },
  "success": true,
  "t": 1733327979535,
  "tid": "c4775cf0b25811efa2cae6bb15587f28"
}
```

### Information about how the device functions

```{
  "result": {
    "properties": [
      {
        "code": "switch_led",
        "custom_name": "",
        "dp_id": 20,
        "time": 1733328548056,
        "type": "bool",
        "value": true
      },
      {
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 21,
        "time": 1733329436075,
        "type": "enum",
        "value": "scene"
      },
      {
        "code": "colour_data",
        "custom_name": "",
        "dp_id": 24,
        "time": 1733329415085,
        "type": "string",
        "value": "0030001403e8"
      },
      {
        "code": "music_data",
        "custom_name": "",
        "dp_id": 27,
        "time": 1733323906401,
        "type": "string",
        "value": ""
      },
      {
        "code": "control_data",
        "custom_name": "",
        "dp_id": 28,
        "time": 1733323906401,
        "type": "string",
        "value": ""
      },
      {
        "code": "m0",
        "custom_name": "",
        "dp_id": 101,
        "time": 1733324273780,
        "type": "string",
        "value": "00000301ff06ff0000ffff0000ff0000ffff0000ffff00ff"
      },
      {
        "code": "lightmic_music_data",
        "custom_name": "",
        "dp_id": 121,
        "time": 1733328179287,
        "type": "raw",
        "value": "AQAAAzIyAQAAZAAAZA=="
      }
    ]
  },
  "success": true,
  "t": 1733330164556,
  "tid": "dad7756bb25d11efbd404216baaa6809"
}
```

The device a string of christmas tree lights and a controller device. It doesn't appear to use the common 3-wire arrangement for most addressable LED strips. It appears to have 2 wires that go out to the string from a controller box labeled "CZJUTAI LED CONTROLLER". Model JT-EL/FC300V0300-H10. In the Tuya app the lights can be set to various color patterns and animations, as well as just direct color control.

The device can be added currently, as it seems to find a "match" which is semi-functional. Control is limited to On/Off and changing the color/brightness of all lights. There is an "effect" selection box with "Off" and "Scene" for choices. There is also an entity for "Scene," however none of these seem to work.

There also appear to be several mismatches in DPs between the config file and the properties of the light switch.

From fiddling around a bit on my own, I think dp id 21 should be something like:
```
    - id: 21
      type: string
      name: effect
        - dps_val: colour
          value: color
        - dps_val: scene
          value: scene
        - dps_val: music
          value: music
```

I don't personally need the music stuff to work, which it looks like several of the other DPs are used for that. I have confirmed that the colors appear to work correctly in home assistant when in the color mode. This light has no "white" mode since it doesn't have DP26 for brightness.

When you set the device to "Scene" using the debug device tool on the developer portal, it immediately jumps to whatever the last scene set by the smart life app was. 

The scene parameters appear to be set using DP id 101. The config for the enbrighten_curtainlight appears to use DP id 56. I think these must work on similar principles though. DP id 101 sets a value to a hex string, but the convention appears different from the existing config's. I copied over the curtainlight's implementation, and adjusted it to use id 101.

For decoding the hex strings, there are 22 "modes" in the smart life app and they inconsistently have subsets of color options or speeds. The parent modes seem to be indicated in the first byte of the string as hex values `00` through `15`. The second byte appears to control a switch interval and the third byte controls a transition time. The fourth byte can only be `00`, '01', or '02' which are associated to "static", "jumping", or "gradient" lighting modes. The next 6 bytes appear to be HSV values. From that point on it appears you can append additional HSV values for additional colors if the modes support them. 

There are several of these strings in the sample config below. It would be a pretty big time-sync to try and get every possible mode set up in the way I have it implemented. This is the first device I have that doesn't have a pre-made config so I'm pretty new and there are big gaps in my understanding here. I'm not sure if there is a way to break up the duties of forming these strings so that every possible mode and color combo doesn't need to be pre-defined. I know there is a DP 28 which looks like it can be used to send adjustments on the fly but I don't really know how to implement it. 

Here is a preliminary config that give some pre-set scenes, mono-color control using the color picker, and on/off control:

```
name: brizlabs string lights
primary_entity:
  entity: light
  dps:
    - id: 20
      type: boolean
      name: switch
    - id: 21
      type: string
      name: effect
      mapping:
        - dps_val: colour
          value: color
        - dps_val: scene
          value: scene
    - id: 24
      name: rgbhsv
      type: hex
      format:
        - name: h
          bytes: 2
          range:
            min: 0
            max: 360
        - name: s
          bytes: 2
          range:
            min: 0
            max: 1000
        - name: v
          bytes: 2
          range:
            min: 0
            max: 1000
secondary_entities:
  - entity: select
    name: Scene
    icon: "mdi:palette"
    category: config
    dps:
      - id: 101
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "00000301ff06ff0000ffff0000ff0000ffff0000ffff00ff"
            value: "Solid Multicolor"
          - dps_val: "00000301ff01ffffff"
            value: "Solid White"
          - dps_val: "00000301ff0200ff00ff0000"
            value: "Solid Red-Green"
          - dps_val: "03000301ff07ff0000ffff0000ff0000ffff0000ffff00ffffffff"
          - dps_val: "09000101ff02ff000000ff00"
            value: "Slow Red-Green Swap"
          - dps_val: "09000301ff02ff000000ff00"
            value: "Fast Red-Green Swap"
            value: "Multicolor Chase"
          - dps_val: "11000301ff02ff000000ff00"
          - dps_val: "0c000101ff06ff000000ff000000ffffff0000ffffff00ff"
            value: "Multicolor Transition"
            value: "Color cycling pulse"
          - dps_val: "13000301ff070000ff00ffff00ff00ff00ffff0000ffffffffff00"
            value: "Fast color cycle"
          - dps_val: "15000301ff01ff0000"
            value: "Rotating Color Cycle"
          - dps_val: "09000301ff01ffffff"
            value: "White-White Swap"
          - dps_val: "0c000101ff01ffffff"
            value: "White-Off Swap"
```

Hopefully this is enough that people can have some basic control. I'll submit a pull request to get this basic yaml set up. Thanks for building and maintaining the integration!
