### ISSUE TITLE
No Brightness-DPS on create_fan_light.yaml

### ISSUE THREAD

**Issue by ulliohura** [make-all/tuya-local#2624]
### Description

Hello,

in the cfg-file for my Create Fan-Light there is no Datapoint for Brightness.
I added manually to create_fan_light.yaml following code to get it working:

Line 32:
```      
      - id: 22
        name: brightness
        type: integer
        range:
          min: 10
          max: 1000
```

On the next update the changes will be lost, so perhaps s.o. can help me to get it integrated officialy into tuyalocal. Unfortunately i dont know how to do a pull request.

Thanks

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [ ] This is not requesting addition of a new device.
