### ISSUE TITLE
New device request 'Screen sync smart light 2.0'

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#264]
Here are the available data points:

- switch 20
- mode 21
- setup side 101
- brightness 22
- light type 102
- 安装位置设置交互 (Install Location Settings Interactive) 103
- color 24
- 情景 (Scene) 104
- scene 25
- timer 26
- music 27
- adjust 28

Please also see https://github.com/rospogrigio/localtuya/issues/1111
It contains additional details.

Scene history:
`{"result":{"devId":"bfd191771ccdf4c81el3nc","datas":[{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667658861540,"eventName":"Scene","eventTimeStr":"2022-11-05 14:34:21:540","eventDetail":"82000000000000000000000000000000","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667658861280,"eventName":"Scene","eventTimeStr":"2022-11-05 14:34:21:280","eventDetail":"82000000000000000000000000000000","requestFrom":"cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667658860295,"eventName":"Scene","eventTimeStr":"2022-11-05 14:34:20:295","eventDetail":"81000000000000000000000000000000","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667658860084,"eventName":"Scene","eventTimeStr":"2022-11-05 14:34:20:084","eventDetail":"81000000000000000000000000000000","requestFrom":"cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667658030759,"eventName":"Scene","eventTimeStr":"2022-11-05 14:20:30:759","eventDetail":"84000000000000000000000000000000","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"appName:智能生活,ios-packageName:com.tuya.smartlife,android-packageName:com.tuya.smartlife,model:VOG-L29,os_system:10,app_version:4.4.2","eventTime":1667658030583,"eventName":"Scene","eventTimeStr":"2022-11-05 14:20:30:583","eventDetail":"84000000000000000000000000000000","requestFrom":"app client"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667658028333,"eventName":"Scene","eventTimeStr":"2022-11-05 14:20:28:333","eventDetail":"83000000000000000000000000000000","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"appName:智能生活,ios-packageName:com.tuya.smartlife,android-packageName:com.tuya.smartlife,model:VOG-L29,os_system:10,app_version:4.4.2","eventTime":1667658028058,"eventName":"Scene","eventTimeStr":"2022-11-05 14:20:28:058","eventDetail":"83000000000000000000000000000000","requestFrom":"app client"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667658001244,"eventName":"Scene","eventTimeStr":"2022-11-05 14:20:01:244","eventDetail":"9300000000000000000000000000","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667658000947,"eventName":"Scene","eventTimeStr":"2022-11-05 14:20:00:947","eventDetail":"9300000000000000000000000000","requestFrom":"cloud2cloud"}],"docType":1,"hasNext":true,"totalCount":0,"currentPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkxOTU5MTQyNjdfN18yNQ==","nextPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkxOTY3ODQwNDdfN18yNQ=="},"t":1667660445493,"success":true,"status":"ok"}`

Mode history:
`{"result":{"devId":"bfd191771ccdf4c81el3nc","datas":[{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667658000947,"eventName":"Mode","eventTimeStr":"2022-11-05 14:20:00:947","eventDetail":"Color","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667657991816,"eventName":"Mode","eventTimeStr":"2022-11-05 14:19:51:816","eventDetail":"Color","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667657991429,"eventName":"Mode","eventTimeStr":"2022-11-05 14:19:51:429","eventDetail":"Color","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584898642,"eventName":"Mode","eventTimeStr":"2022-11-04 18:01:38:642","eventDetail":"White","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584598144,"eventName":"Mode","eventTimeStr":"2022-11-04 17:56:38:144","eventDetail":"Color","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584586060,"eventName":"Mode","eventTimeStr":"2022-11-04 17:56:26:060","eventDetail":"Scene","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584582572,"eventName":"Mode","eventTimeStr":"2022-11-04 17:56:22:572","eventDetail":"Music","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584574664,"eventName":"Mode","eventTimeStr":"2022-11-04 17:56:14:664","eventDetail":"Scene","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584138519,"eventName":"Mode","eventTimeStr":"2022-11-04 17:48:58:519","eventDetail":"White","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583292890,"eventName":"Mode","eventTimeStr":"2022-11-04 17:34:52:890","eventDetail":"Color","requestFrom":"cloud2cloud"}],"docType":1,"hasNext":true,"totalCount":0,"currentPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkxOTY3NzQ4NjBfNV8yMQ==","nextPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkyNzE1Nzg2MTFfNV8yMQ=="},"t":1667660559179,"success":true,"status":"ok"}`

Color history:
`{"result":{"devId":"bfd191771ccdf4c81el3nc","datas":[{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667658000947,"eventName":"Color ","eventTimeStr":"2022-11-05 14:20:00:947","eventDetail":"012103b70233","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667657991429,"eventName":"Color ","eventTimeStr":"2022-11-05 14:19:51:429","eventDetail":"012103b70233","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667587121093,"eventName":"Color ","eventTimeStr":"2022-11-04 18:38:41:093","eventDetail":"012103b70233","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667587119201,"eventName":"Color ","eventTimeStr":"2022-11-04 18:38:39:201","eventDetail":"006103680233","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667587115531,"eventName":"Color ","eventTimeStr":"2022-11-04 18:38:35:531","eventDetail":"007802190233","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584598124,"eventName":"Color ","eventTimeStr":"2022-11-04 17:56:38:124","eventDetail":"014502a000c1","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583292890,"eventName":"Color ","eventTimeStr":"2022-11-04 17:34:52:890","eventDetail":"001e03e800c1","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583197196,"eventName":"Color ","eventTimeStr":"2022-11-04 17:33:17:196","eventDetail":"001e03e800c1","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583192434,"eventName":"Color ","eventTimeStr":"2022-11-04 17:33:12:434","eventDetail":"001e03e800c1","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667582806299,"eventName":"Color ","eventTimeStr":"2022-11-04 17:26:46:299","eventDetail":"001e03e800c1","requestFrom":"device itself"}],"docType":1,"hasNext":true,"totalCount":0,"currentPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkxOTY3NzQ4NjBfNV8yNA==","nextPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkyNzE5NzM5OTlfN18yNA=="},"t":1667660597682,"success":true,"status":"ok"}`

Brightness history:
`{"result":{"devId":"bfd191771ccdf4c81el3nc","datas":[{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667658000947,"eventName":"Brightness","eventTimeStr":"2022-11-05 14:20:00:947","eventDetail":"563","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667657991429,"eventName":"Brightness","eventTimeStr":"2022-11-05 14:19:51:429","eventDetail":"563","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667587095027,"eventName":"Brightness","eventTimeStr":"2022-11-04 18:38:15:027","eventDetail":"563","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584149162,"eventName":"Brightness","eventTimeStr":"2022-11-04 17:49:09:162","eventDetail":"110","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584145164,"eventName":"Brightness","eventTimeStr":"2022-11-04 17:49:05:164","eventDetail":"767","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667584014781,"eventName":"Brightness","eventTimeStr":"2022-11-04 17:46:54:781","eventDetail":"226","requestFrom":"device itself"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583292890,"eventName":"Brightness","eventTimeStr":"2022-11-04 17:34:52:890","eventDetail":"227","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583197196,"eventName":"Brightness","eventTimeStr":"2022-11-04 17:33:17:196","eventDetail":"227","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"","eventTime":1667583192434,"eventName":"Brightness","eventTimeStr":"2022-11-04 17:33:12:434","eventDetail":"227","requestFrom":"cloud2cloud"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Report","sourceDetail":"","eventTime":1667567606114,"eventName":"Brightness","eventTimeStr":"2022-11-04 13:13:26:114","eventDetail":"227","requestFrom":"device itself"}],"docType":1,"hasNext":true,"totalCount":0,"currentPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkxOTY3NzQ4NjBfNV8yMg==","nextPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkyODcxNjk4NjZfNV8yMg=="},"t":1667660655187,"success":true,"status":"ok"}`

**Comment by and7ey** [comment]
Could you please clarify what `awaiting confirmation` status means? Do I need to install some beta version and verify how it works?

**Comment by make-all** [comment]
If you want to do the confirmation before the release, you can install "main" by selecting "Redownload" from the menu inside the HACS description for this integration, and select "main" as the version to install.  Otherwise I will release the current state untested (maybe later tonight or during the week) and you can feedback after release.  If you can figure out the functionality and possible values for the dps above 100, it may also be possible to expand the functionality beyond basic RGB light functions (for example, it isn't clear how to put it into HDMI sync mode).

**Comment by and7ey** [comment]
Thanks. I will be testing it now. 

Here are some of my findings:
```
Mobile application menu Scene / Rainbow:
- Scene 86000000000000000000000000000000

Scene / Fire:
- Scene 87000000000000000000000000000000

Scene / Read:
- Scene 88000000000000000000000000000000

(more scenes are supported, just skipped them)


Video / Screen / Movie (this is actually HDMI sync mode):
- Scene 80000000000000000000000000000000

Video / Screen / Video:
- Scene 81000000000000000000000000000000

Video / Screen / Game:
- Scene 82000000000000000000000000000000


Video / Music / Spectrum (this is Microphone mode):
- Scene 83000000000000000000000000000000

Video / Music / Electronic:
- Scene 84000000000000000000000000000000

Video / Music / Listen:
- Scene 85000000000000000000000000000000


Color:
- not supported ("The currently selected Mode does not allow to change colors. Please select the available part in the Taste Mode"), I didn't get what is meant by Taste mode. But there are some events with Color DP in tuya device log.

Brightness 100%:
- Brightness    1000

Brightness 50%:
- Brightness    495

Brightness 1%:
- Brightness    10

Settings / Lamp type / Light Post:
- (DP 102) Light Type  0.10

Settings / Lamp type / Light Strip:
- (DP 102) Light Type  0.00 (my case)

Settings / Installation Side / Left Side (not available for Light Post, used with Light Strip only):
- (DP 101) Setup Side   0.00 (my case)

Settings / Installation Side / Right Side (not available for Light Post, used with Light Strip only):
- (DP 101) Setup Side   0.10
```

And I didn't get what is the purpose of DP 103. Here is the sample payload:
`{"startRowId":"","pageNo":1,"pageSize":10,"code":"103","startTime":1667576881721,"endTime":1667749681723,"projectCode":"1234567890","sourceId":"eu159664875936960LBV","sourceType":"4","deviceId":"bfd191771ccdf4c81el3nc","pageStartRow":"","region":"EU"}`
and here is the response (looks like some analytics):
`{"result":{"devId":"bfd191771ccdf4c81el3nc","datas":[{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"appName:智能生活,ios-packageName:com.tuya.smartlife,android-packageName:com.tuya.smartlife,model:VOG-L29,os_system:10,app_version:4.4.2","eventTime":1667749231387,"eventName":"安装位置设置交互","eventTimeStr":"2022-11-06 15:40:31:387","eventDetail":"0.10","requestFrom":"app client"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"appName:智能生活,ios-packageName:com.tuya.smartlife,android-packageName:com.tuya.smartlife,model:VOG-L29,os_system:10,app_version:4.4.2","eventTime":1667749217824,"eventName":"安装位置设置交互","eventTimeStr":"2022-11-06 15:40:17:824","eventDetail":"0.00","requestFrom":"app client"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"appName:智能生活,ios-packageName:com.tuya.smartlife,android-packageName:com.tuya.smartlife,model:VOG-L29,os_system:10,app_version:4.4.2","eventTime":1667749176537,"eventName":"安装位置设置交互","eventTimeStr":"2022-11-06 15:39:36:537","eventDetail":"0.10","requestFrom":"app client"},{"devId":"bfd191771ccdf4c81el3nc","eventType":"Publish","sourceDetail":"appName:智能生活,ios-packageName:com.tuya.smartlife,android-packageName:com.tuya.smartlife,model:VOG-L29,os_system:10,app_version:4.4.2","eventTime":1667749162653,"eventName":"安装位置设置交互","eventTimeStr":"2022-11-06 15:39:22:653","eventDetail":"0.00","requestFrom":"app client"}],"docType":1,"hasNext":false,"totalCount":0,"currentPageStartRowKey":"MDJhNTg0MTRjbjNsZTE4YzRmZGNjMTc3MTkxZGZiXzkyMjMzNzAzNjkxMDU1NDQ0MjBfNV8xMDM="},"t":1667749683194,"success":true,"status":"ok"}`

There are no events with DP 104 (情景), 27 (music), 28 (adjust).

**Comment by and7ey** [comment]
Upd. I didn't get how to test it properly.
When I add the device, it suggest to choose from two device types:
- ir_remote_sensors
- rgbcw_lightbulb
If I choose `rgbcw_lightbulb`, then just switch on/off works.

**Comment by make-all** [comment]
Did you first Redownload the tuya-local integration, chosing "main" as the version to install?

Can you look in the Home Assistant log after adding it for a log message listing the dps that came back from the device?  Or if you already added it, go into Settings / Devices and Download the Diagnostics for the device?

**Comment by and7ey** [comment]
Yes, I've chosen `main` as the version and verified that file `screen sync.yaml` (or something like that) appeared in my custom_components/toya_local/devices folder.

Ok, I'll add the log later.

**Comment by and7ey** [comment]
Here is the log (please note that I've chosen `rgbcw_lightbulb` when adding the device) 
[tuya_local-6a5ccd8b671980e875485a0e07b3cdbc-RGBCW Lightbulb-bb1ea4383ac9e15b156d0f8f2d7e3c0f.json.txt](https://github.com/make-all/tuya-local/files/9952078/tuya_local-6a5ccd8b671980e875485a0e07b3cdbc-RGBCW.Lightbulb-bb1ea4383ac9e15b156d0f8f2d7e3c0f.json.txt)

**Comment by and7ey** [comment]
@make-all how do you identify the device? based on DPS available?

**Comment by make-all** [comment]
Yes, it is based on DPS available and their types.

**Comment by make-all** [comment]
I have added another commit to change some of the dp types based on the log message above.  There are still some not showing (they are marked as optional in the config, so missing is OK, but if they are there in other modes, it may lead to misdetection again if they do not match).

**Comment by and7ey** [comment]
I've modified the yaml file to make more dps optional, in result the device has been identified as screen sync. But now when I switch it on, the following error is shown

  File "/config/custom_components/tuya_local/helpers/device_config.py", line 330, in decoded_value
    return bytes.fromhex(v)
ValueError: non-hexadecimal number found in fromhex() arg at position 3

**Comment by make-all** [comment]
Could you download the diagnostics again when it is (vaguely at least) working?

The one above has a protocol version of 3.2 and no dps listed.  I think it is taken too early when the protocol is still being figured out.  But I also suspect that it is one of the newer protocol versions (3.2 or 3.4) which may have additional requirements for fetching all the dps, otherwise it is randomly returning a partial snapshot of the most recently changed or something.

Also, that color value is not hex, as it has 'N' in it.  This probably has special meaning, is it like this when in hdmi sync mode perhaps?

**Comment by and7ey** [comment]
please see attached two versions (hdmi and standard scene modes)

[tuya_local-1594ae9ce9a815914055f331fb284090-Ambilight-bb1ea4383ac9e15b156d0f8f2d7e3c0f.json (1).txt](https://github.com/make-all/tuya-local/files/9967867/tuya_local-1594ae9ce9a815914055f331fb284090-Ambilight-bb1ea4383ac9e15b156d0f8f2d7e3c0f.json.1.txt)
[tuya_local-1594ae9ce9a815914055f331fb284090-Ambilight-bb1ea4383ac9e15b156d0f8f2d7e3c0f.json.txt](https://github.com/make-all/tuya-local/files/9967868/tuya_local-1594ae9ce9a815914055f331fb284090-Ambilight-bb1ea4383ac9e15b156d0f8f2d7e3c0f.json.txt)

**Comment by and7ey** [comment]
<img width="1204" alt="Снимок экрана 2022-11-09 в 9 14 15" src="https://user-images.githubusercontent.com/900474/200753606-fc7012e1-49f1-4e50-97f6-a415c69a6344.png">
Looks like we can just replace N with 0

**Comment by and7ey** [comment]
@make-all could you please help me with the questions above?

**Comment by make-all** [comment]
Do you still have it added as rgbcw_lightbulb?  Can you remove the device and try adding it again as screensync_light?

Currently there is still no handling of the N in hex values, I am not sure if it is a replacement for 0 or a negative sign indicator.

There should be many more effects available than just the two standard Home Assistant ones (which were mapped to random and music as per the rgbcw lightbulb).

**Comment by and7ey** [comment]
>> I've modified the yaml file to make more dps optional, in result the device has been identified as screen sync.

So, it is added as `screensync_light`. The names of the effects are given there - https://github.com/make-all/tuya-local/issues/264#issuecomment-1304831558. There are no are no events with DP 104 (情景), so believe we may ignore it.

**Comment by make-all** [comment]
Sorry, I meant 25, not 104.  I was confused by the same naming (though 104 is in Chinese, which probably means it is intended for factory/diagnostic use rather than general operation).

**Comment by and7ey** [comment]
Can we test 2 scenes (dp 25 86000000000000000000000000000000 and 84000000000000000000000000000000): 
1) mode 21 equal to 'white',
2) mode 21 equal to 'color',
3) without mode 21? 
How to reflect that in yaml?

**Comment by make-all** [comment]
Sorry, I think we are not ready to implement scenes until we get the mode working correctly.

**Comment by and7ey** [comment]
Ok. I was playing with the app, there is no single Mode event received.

Some scenes support Color mode:
```
Scene / Firework:
- Scene 89000000000000000000000000000000

Scene / Star:
- Scene 90000000000000000000000000000000
  supports Color

Scene / Drip:
- Scene 91000000000000000000000000000000
  supports Color

Scene / Particle:
- Scene 92000000000000000000000000000000
  supports Color

Scene / Flow:
- Scene 93000000000000000000000000000000
  supports Color

Scene / Ball:
- Scene 94000000000000000000000000000000
  supports Color

Scene / Swing:
- Scene 95000000000000000000000000000000
  supports Color

Scene / Breath:
- Scene 96000000000000000000000000000000
  supports Color

Scene / Pure:
- Scene 97000000000000000000000000000000
  supports Color
```
but when I change the color, new scene is received: `01000000000000000000000000000000`.

And here are some sample colors:
```
Color Red:    015c03e803e8 (not sure if this is ff0000 - can not choose pure red color)
Color Blue:   00cd03d703e8 
Color Yellow: 003803e803e8
Color Green:  006703e803e8
Color White:  0067000003e8
```

**Comment by make-all** [comment]
The colors are in HSV (4 hex characters per component), not in RGB, so that Red is 348, 1000, 1000 (converts to FF0033 in RGB).
I suspect "Scene" 01000000..." is plain colour mode.  But more interesting that that big hex number that is going to be impossible to fully support without more understanding, is the Mode.

**Comment by and7ey** [comment]
I've experimented more - the main color is changed, but the scene remains unchanged, when I choose the color (i.e. Scene Star supports the color change).  Not sure in which case Scene 01000... appears.

Should I verify something else on my side?

**Comment by and7ey** [comment]
Could you please give me one-two examples how to add the scene to yaml file? I'll add them to test how it works.

**Comment by and7ey** [comment]
@make-all do I understand it correctly - I can try to add 
```
    // mode
    - id: 21
      type: string
      name: color_mode
      mapping:
        - dps_val: White
          value: color_temp
        - dps_val: Color
          value: rgbw
        - dps_val: Scene
          value: colorloop
        - dps_val: Music
          value: random

    // scene
    - id: 25
	type: bitfield
	name: scene
	mappings:
	  - dps_val: 80000000000000000000000000000000
	    value: Video - Screen - Movie
	  - dpv_val: 87000000000000000000000000000000
	    value: Scene - Fire
```
to yaml file and test it?

**Comment by make-all** [comment]
I think if you rename scene to effect it may work.  If not, make that a separate select entity.

**Comment by and7ey** [comment]
Now switch on/off doesn't work - 
> Failed to call service light/turn_on. non-hexadecimal number found in fromhex() arg at position 3

I also had to make some dps optional: 20, 21, 25, 26

**Comment by make-all** [comment]
This device does not seem to be workable, sorry.  It is too inconsistent with which dps are returned, at least we need the on/off and color_mode to be consistently there.

**Comment by and7ey** [comment]
I hope still there is a chance, just more experiments are needed. 
On/off is there. Color_mode is under question.

Is there any way to apply yaml changes without HA restart?

**Comment by and7ey** [comment]
The following config works almost perfectly:
```
name: Screen sync smart light 2.0
primary_entity:
  entity: light
  dps:
    # on/off
    - id: 20
      type: boolean
      name: switch
      optional: true
    # mode
    - id: 21
      type: string
      name: color_mode
      mapping:
        - dps_val: colour
          value: rgbw
    # scene      
    - id: 25
      type: hex
      name: effect
      mapping:
        - dps_val: 80000000000000000000000000000000
          value: Video / Screen / Movie

        - dps_val: 81000000000000000000000000000000
          value: Video / Screen / Video

        - dps_val: 82000000000000000000000000000000
          value: Video / Screen / Game


        - dps_val: 83000000000000000000000000000000
          value: Video / Music / Spectrum

        - dps_val: 84000000000000000000000000000000
          value: Video / Music / Electronic

        - dps_val: 85000000000000000000000000000000
          value: Video / Music / Listen

        - dps_val: 86000000000000000000000000000000
          value: Scene / Rainbow

        - dps_val: 87000000000000000000000000000000
          value: Scene / Fire

        - dps_val: 88000000000000000000000000000000
          value: Scene / Read

        - dps_val: 89000000000000000000000000000000
          value: Scene / Firework

        - dps_val: 90000000000000000000000000000000
          value: Scene / Star (color)

        - dps_val: 91000000000000000000000000000000
          value: Scene / Drip (color)

        - dps_val: 92000000000000000000000000000000
          value: Scene / Particle (color)

        - dps_val: 93000000000000000000000000000000
          value: Scene / Flow (color)

        - dps_val: 94000000000000000000000000000000
          value: Scene / Ball (color)

        - dps_val: 95000000000000000000000000000000
          value: Scene / Swing (color)

        - dps_val: 96000000000000000000000000000000
          value: Scene / Breath (color)

        - dps_val: 97000000000000000000000000000000
          value: Scene / Pure (color)

      optional: true

   # brightness
    - id: 22
      name: brightness
      type: integer
      range:
        min: 10
        max: 1000
      mapping:
        - scale: 3.92
        
    # color    
    - id: 24
      name: rgbhsv
      type: hex
      format:
        - name: h
          bytes: 2
          range:
            min: 0
            max: 360
        - name: s
          bytes: 2
          range:
            min: 0
            max: 1000
        - name: v
          bytes: 2
          range:
            min: 0
            max: 1000
      optional: false
    
    # music
    - id: 27
      type: hex
      name: music_data
      optional: true
      
    # adjust
    - id: 28
      type: hex
      name: control_data
      optional: true
      
    # setup side  
    - id: 101
      type: integer
      name: setup_side
      optional: true
      
    # light type  
    - id: 102
      type: integer
      name: light_type
      optional: true
      
    # install location settings interactive 
    - id: 103
      type: string
      name: install_location
      optional: true
      
    # 情景 (scene)  
    - id: 104
      type: string
      name: scene
      optional: true
      
secondary_entities:
  - entity: number
    name: Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 26
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        unit: min
        mapping:
          - scale: 60
            step: 60
        optional: true

```

The effects are changed well, the color is changed (for the effects, where it is supported), switch on and off is supported.

Just the following minor questions are left open:
1) brightness is not changed (believe, it worked before with some other config) - I see no event in Tuya Console. Is it because I left just one mode - `colour`?
2) is there any way to hide color palette for modes, where it is not supported?
