### ISSUE TITLE
Request support for EARU 2P 63A

### ISSUE THREAD

**Issue by requireyan** [make-all/tuya-local#2662]
### Log message

```text
Adding Breaker device with product id z3jngbyubvwgfrcv
Device matches None with quality of 0%. DPS: {"updated_at": 1734466761.6156194, "17": "BAEAMgUBAFA="}
```

### Product ID

z3jngbyubvwgfrcv

### Product Name

EARU 2P V3 63A

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "total_forward_energy",
        "custom_name": "",
        "dp_id": 1,
        "time": 1734466861045,
        "type": "value",
        "value": 77547
      },
      {
        "code": "phase_a",
        "custom_name": "",
        "dp_id": 6,
        "time": 1734467073658,
        "type": "raw",
        "value": "CQsABOcAAQQ="
      },
      {
        "code": "phase_b",
        "custom_name": "",
        "dp_id": 7,
        "time": 1723627197308,
        "type": "raw"
      },
      {
        "code": "phase_c",
        "custom_name": "",
        "dp_id": 8,
        "time": 1723627197308,
        "type": "raw"
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 9,
        "time": 1732174575266,
        "type": "bitmap",
        "value": 0
      },
      {
        "code": "switch_prepayment",
        "custom_name": "",
        "dp_id": 11,
        "time": 1732174575266,
        "type": "bool",
        "value": false
      },
      {
        "code": "clear_energy",
        "custom_name": "",
        "dp_id": 12,
        "time": 1732174575266,
        "type": "bool",
        "value": false
      },
      {
        "code": "balance_energy",
        "custom_name": "",
        "dp_id": 13,
        "time": 1732174575266,
        "type": "value",
        "value": 0
      },
      {
        "code": "charge_energy",
        "custom_name": "",
        "dp_id": 14,
        "time": 1723627197308,
        "type": "value",
        "value": 0
      },
      {
        "code": "leakage_current",
        "custom_name": "",
        "dp_id": 15,
        "time": 1734467068591,
        "type": "value",
        "value": 6
      },
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 16,
        "time": 1732174575266,
        "type": "bool",
        "value": true
      },
      {
        "code": "alarm_set_1",
        "custom_name": "",
        "dp_id": 17,
        "time": 1734467067491,
        "type": "raw",
        "value": "BAEAMgUBAFA="
      },
      {
        "code": "alarm_set_2",
        "custom_name": "",
        "dp_id": 18,
        "time": 1734467067570,
        "type": "raw",
        "value": "AQEAlgMBARMEAQCv"
      },
      {
        "code": "recover_sec",
        "custom_name": "",
        "dp_id": 101,
        "time": 1723627197308,
        "type": "value",
        "value": 1
      },
      {
        "code": "recover_cnt",
        "custom_name": "",
        "dp_id": 102,
        "time": 1732174575266,
        "type": "value",
        "value": 5
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 103,
        "time": 1734466961121,
        "type": "value",
        "value": 24
      },
      {
        "code": "recover_enable",
        "custom_name": "",
        "dp_id": 104,
        "time": 1732174575266,
        "type": "bool",
        "value": true
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 105,
        "time": 1732174575266,
        "type": "value",
        "value": 0
      },
      {
        "code": "cycle_time",
        "custom_name": "",
        "dp_id": 106,
        "time": 1732174575266,
        "type": "string",
        "value": "EwAAAAAAAAAAAA=="
      },
      {
        "code": "leak_delay",
        "custom_name": "",
        "dp_id": 107,
        "time": 1732174575266,
        "type": "value",
        "value": 30
      },
      {
        "code": "random_time",
        "custom_name": "",
        "dp_id": 108,
        "time": 1723627197308,
        "type": "string",
        "value": ""
      },
      {
        "code": "switch_inching",
        "custom_name": "",
        "dp_id": 109,
        "time": 1732174575266,
        "type": "string",
        "value": "AAAA"
      },
      {
        "code": "alarm_set3",
        "custom_name": "",
        "dp_id": 126,
        "time": 1723627197308,
        "type": "raw"
      },
      {
        "code": "status",
        "custom_name": "",
        "dp_id": 127,
        "time": 1723627197308,
        "type": "enum",
        "value": "0"
      },
      {
        "code": "status_b",
        "custom_name": "",
        "dp_id": 128,
        "time": 1723627197308,
        "type": "enum",
        "value": "0"
      },
      {
        "code": "status_c",
        "custom_name": "",
        "dp_id": 129,
        "time": 1723627197308,
        "type": "enum",
        "value": "0"
      },
      {
        "code": "swithc_power_save",
        "custom_name": "",
        "dp_id": 134,
        "time": 1732174615272,
        "type": "enum",
        "value": "2"
      }
    ]
  },
  "success": true,
  "t": 1734467095247,
  "tid": "fa4c0f70bcb411efaf84fe4c51833753"
}
```

### Information about how the device functions

Device details:
model: One-way normal_63A
product name: Single-phase reclosing_2P_V3_63

**Comment by make-all** [comment]
Have you tried with the protocol version set to 3.2?

**Comment by requireyan** [comment]
Yes they all fail with 904/914 unless version 3.4 is used.

**Comment by DimVKir** [comment]
I wrote a configuration for this device. Anyone can test it.
Place this code in the file /custom_components/tuya_local/devices/earu_2p_63a.yaml, reload the integration and add the device.

```
name: Circuit breaker
products:
  - id: z3jngbyubvwgfrcv
    manufacturer: EARU
    model: EARU_2P_V3_63
entities:
  - entity: switch
    icon: "mdi:fuse"
    name: Breaker
    dps:
      - id: 16
        name: switch
        type: boolean
  - entity: sensor
    name: Total energy
    class: energy
    dps:
      - id: 1
        type: integer
        unit: kWh
        class: total_increasing
        name: sensor
        mapping:
          - scale: 100
  - entity: sensor
    class: voltage
    icon: "mdi:sine-wave"
    category: diagnostic
    dps:
      - id: 6
        optional: true
        force: true
        type: base64
        unit: V
        class: measurement
        name: sensor
        mask: "FFFF000000000000"
        mapping:
          - scale: 10
  - entity: sensor
    class: current
    icon: "mdi:current-ac"
    category: sensors
    dps:
      - id: 6
        optional: true
        force: true
        type: base64
        unit: A
        name: sensor
        mask: "0000FFFFFF000000"
        mapping:
          - scale: 1000
  - entity: sensor
    class: power
    icon: "mdi:flash"
    category: diagnostic
    dps:
      - id: 6
        optional: true
        force: true
        type: base64
        unit: kW
        name: sensor
        mask: "0000000000FFFFFF"
        mapping:
          - scale: 1000
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 9
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 9
        type: bitfield
        name: fault_code
      - id: 9
        type: bitfield
        name: description
        mapping:
          - dps_val: 0
            value: OK
          - dps_val: 1
            value: Short circuit
          - dps_val: 2
            value: Surge
          - dps_val: 4
            value: Overload
          - dps_val: 8
            value: Leakage current
          - dps_val: 16
            value: High temperature
          - dps_val: 32
            value: Fire
          - dps_val: 64
            value: High power
          - dps_val: 128
            value: Self test
          - dps_val: 256
            value: Over current
          - dps_val: 512
            value: Unbalanced
          - dps_val: 1024
            value: Over voltage
          - dps_val: 2048
            value: Under voltage
          - dps_val: 4096
            value: Phase fault
          - dps_val: 8192
            value: Outage
          - dps_val: 16384
            value: Magnetism
          - dps_val: 32768
            value: Low credit
          - dps_val: 65536
            value: No balance
          - dps_val: 131072
            value: Phase Seq Error
          - dps_val: 262144
            value: Voltage Unbalance
          - dps_val: 524288
            value: Low current
  - entity: switch
    name: Prepay
    category: config
    icon: "mdi:hand-coin"
    dps:
      - id: 11
        type: boolean
        name: switch
  - entity: button
    name: Energy reset
    category: config
    class: restart
    dps:
      - id: 12
        type: boolean
        name: button
  - entity: sensor
    name: Balance energy
    category: diagnostic
    icon: "mdi:home-lightning-bolt"
    dps:
      - id: 13
        optional: true
        type: integer
        name: sensor
        unit: kWh
        mapping:
          - scale: 100
  - entity: sensor
    name: Actual leakage current
    icon: "mdi:wave-undercurrent"
    category: diagnostic
    dps:
      - id: 15
        optional: true
        type: integer
        name: sensor
        unit: mA
  - entity: switch
    name: Leakage current
    category: config
    hidden: unavailable
    dps:
      - id: 17
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 17
        optional: true
        force: true
        type: base64
        name: switch
        mask: "00FF000000000000"
  - entity: number
    name: Leakage current
    category: config
    hidden: unavailable
    mode: box
    dps:
      - id: 17
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 17
        optional: true
        force: true
        type: base64
        unit: mA
        name: value
        mask: "0000FFFF00000000"
        range:
          min: 10
          max: 99
  - entity: switch
    name: High temperature
    category: config
    hidden: unavailable
    dps:
      - id: 17
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 17
        optional: true
        force: true
        type: base64
        name: switch
        mask: "0000000000FF0000"
  - entity: number
    name: High temperature
    category: config
    hidden: unavailable
    mode: box
    dps:
      - id: 17
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 17
        optional: true
        force: true
        type: base64
        unit: C
        name: value
        mask: "000000000000FFFF"
        range:
          min: 10
          max: 85
  - entity: switch
    name: Over current
    category: config
    hidden: unavailable
    dps:
      - id: 18
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 18
        optional: true
        force: true
        type: base64
        name: switch
        mask: "00FF00000000000000000000"
  - entity: number
    name: Over current
    category: config
    hidden: unavailable
    mode: box
    dps:
      - id: 18
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 18
        optional: true
        force: true
        type: base64
        unit: A
        name: value
        mask: "0000FFFF0000000000000000"
        mapping:
          - scale: 10
        range:
          min: 10
          max: 630
  - entity: switch
    name: Over voltage
    category: config
    hidden: unavailable
    dps:
      - id: 18
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 18
        optional: true
        force: true
        type: base64
        name: switch
        mask: "0000000000FF000000000000"
  - entity: number
    name: Over voltage
    category: config
    hidden: unavailable
    mode: box
    dps:
      - id: 18
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 18
        optional: true
        force: true
        type: base64
        unit: V
        name: value
        mask: "000000000000FFFF00000000"
        range:
          min: 120
          max: 300
  - entity: switch
    name: Under voltage
    category: config
    hidden: unavailable
    dps:
      - id: 18
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 18
        optional: true
        force: true
        type: base64
        name: switch
        mask: "000000000000000000FF0000"
  - entity: number
    name: Under voltage
    category: config
    hidden: unavailable
    mode: box
    dps:
      - id: 18
        type: boolean
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 18
        optional: true
        force: true
        type: base64
        unit: V
        name: value
        mask: "00000000000000000000FFFF"
        range:
          min: 80
          max: 210
  - entity: sensor
    name: Temperature
    icon: "mdi:thermometer-lines"
    category: diagnostic
    dps:
      - id: 103
        optional: true
        force: true
        type: integer
        name: sensor
        unit: C
#  - entity: sensor
#    name: countdown_1
#    category: diagnostic
#    hidden: true
#    dps:
#      - id: 105
#        optional: true
#        type: integer
#        name: sensor
#        unit: s
#  - entity: sensor
#    name: cycle_time
#    category: diagnostic
#    hidden: true
#    dps:
#      - id: 106
#        type: string
#        optional: true
#        hidden: true
#        name: sensor
#  - entity: sensor
#    name: random_time
#    category: diagnostic
#    dps:
#      - id: 108
#        type: string
#        optional: true
#        name: sensor
  - entity: switch
    name: Reclosing enabling
    category: config
    dps:
      - id: 104
        type: boolean
        name: switch
#  - entity: number
#    name: Reclose recovery seconds
#    category: config
#    dps:
#      - id: 101
#        type: integer
#        name: value
#        unit: s
#        range:
#          min: 1
#          max: 99
  - entity: number
    name: Reclosing allowed times
    category: config
    dps:
      - id: 102
        type: integer
        name: value
        unit: times
        range:
          min: 1
          max: 30

```
