### ISSUE TITLE
Kolanky Charging Time unit should be h and not min

### ISSUE THREAD

**Issue by layanto** [make-all/tuya-local#2675]
### Description

kolanky_evcharger.yml unit for Charging Time should be h and not min

Current:
```
  - entity: sensor
    name: Charging time
    class: duration
    dps:
      - id: 120
        type: integer
        optional: true
        name: sensor
        unit: min
        mapping:
          - scale: 10
```
New:
```
  - entity: sensor
    name: Charging time
    class: duration
    dps:
      - id: 120
        type: integer
        optional: true
        name: sensor
        unit: h
        mapping:
          - scale: 10
```

### Steps to reproduce

Either start charging and watch Charging Time count up or set Delay Start (in hours) and watch Charging Time count down. Either way, display on Home Assistant is incorrect where h is shown as min and min is shown as sec.

### Confirmation

- [X] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [X] This is not requesting addition of a new device.
