### ISSUE TITLE
 New device request "ETOP-HT thermostat"

### ISSUE THREAD

**Issue by mojiro** [make-all/tuya-local#272]
Hello,

I have created a Yaml for a new device. Would you like to add it in your project?

It is tested and it works with heaters that are controlled by "ETOP-HT" thermostats, like EcoVolt  EVRAD.

Thanks.

**Filename:** `etop_ht_thermostat.yaml`

**Code:**
```
name: ETOP-HT thermostat
products:
  - id: viav1onpzcozfneb

primary_entity:
  entity: climate
  name: Thermostat
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
          icon_priority: 1
        - dps_val: true
          value: heat
          icon_priority: 1
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: manual
          value: none
          icon: "mdi:cursor-pointer"
        - dps_val: eco
          value: eco
          icon: "mdi:sprout"
        - dps_val: auto
          value: activity
          icon: "mdi:thermostat-auto"
    - id: 3
      type: string
      name: hvac_action
      mapping:
        - dps_val: no_heating
          value: "off"
        - dps_val: heating
          value: heating
    - id: 24
      type: integer
      name: current_temperature
      range:
        min: 0
        max: 1000
      mapping:
        - scale: 10
          step: 5
    - id: 16
      type: integer
      name: temperature
      range:
        min: 0
        max: 1000
      mapping:
        - scale: 10
          step: 5
    - id: 26
      type: integer
      name: min_temperature
      range:
        min: 0
        max: 1000
      mapping:
        - scale: 10
          step: 5
    - id: 19
      type: integer
      name: max_temperature
      range:
        min: 50
        max: 1000
      mapping:
        - scale: 10
          step: 5

secondary_entities:
  - entity: switch
    name: "Anti-frost"
    icon: "mdi:snowflake-melt"
    category: config
    dps:
      - id: 10
        type: boolean
        name: switch
  - entity: lock
    name: "Child lock"
    category: config
    dps:
      - id: 40
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"
  - entity: number
    name: "Setpoint min."
    category: config
    mode: slider
    dps:
      - id: 26
        name: value
        type: integer
        unit: C
        range:
          min: 0
          max: 1000
        mapping:
          - scale: 10
            step: 5
            icon: "mdi:thermometer-low"
  - entity: number
    name: "Setpoint max."
    category: config
    mode: slider
    dps:
      - id: 19
        type: integer
        name: value
        unit: C
        range:
          min: 50
          max: 1000
        mapping:
          - scale: 10
            step: 5
            icon: "mdi:thermometer-high"
  - entity: number
    name: Temperature correction
    category: config
    mode: slider
    dps:
      - id: 27
        name: value
        type: integer
        unit: C
        range:
          min: -100
          max: 100
        mapping:
          - scale: 10
            step: 5
            icon: "mdi:wrench-clock"
  - entity: number
    name: Error
    category: diagnostic
    class: problem
    dps:
      - id: 45
        type: bitfield
        name: value
        readonly: true
        mapping:
          - icon: "mdi:alert"
```
