### ISSUE TITLE
Request support for Rohnson Soft Cooking R-2858 SmartChef XL

### ISSUE THREAD

**Issue by dimis7** [make-all/tuya-local#2746]
### Log message

```text
Device matches simple_dual_switch_timer_v2 with quality of 33%. DPS: {"updated_at": 1736236868.967799, "1": false, "2": false, "3": "custom", "4": 0, "6": 185, "9": 15, "10": 15, "12": 0, "101": false, "103": true, "108": "wait_mode", "110": false}
```

### Product ID

dsyz4tnrkwgo2fma

### Product Name

Rohnson Soft Cooking R-2858 SmartChef XL

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"f0bso4\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"0：处于冷却关机\\n1：正常开机，可操作\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"start\",\"description\":\"0：烹饪状态\\n1：暂停状态\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"启动/停止\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"1：鸡腿\\n2：牛排\\n3：烤鱼\\n4：蛋糕\\n5：披萨\\n6：香肠\\n7：薯条\\n8：干果\\n9：自定义\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"烹饪模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"drumsticks\",\"steak\",\"fish\",\"cake\",\"pizza\",\"sausage\",\"chips\",\"dryfruit\",\"custom\"]}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"cloud_recipe_number\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"云菜谱清单\",\"typeSpec\":{\"type\":\"value\",\"max\":999999999,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"cook_temperature\",\"description\":\"由MCU端上报  华氏度版本：180-440   摄氏度版本：80-220\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"烹饪温度\",\"typeSpec\":{\"type\":\"value\",\"max\":220,\"min\":30,\"scale\":0,\"step\":5,\"unit\":\"℃\"}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"cook_time\",\"description\":\"所有菜单：1-60min\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"烹饪时间\",\"typeSpec\":{\"type\":\"value\",\"max\":1440,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"min\"}},
{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"remain_time\",\"description\":\"\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"剩余时间\",\"typeSpec\":{\"type\":\"value\",\"max\":1440,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"min\"}},
{\"abilityId\":12,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"E1:温控探头断路\\nE2:温控探头短路\",\"extensions\":{\"scope\":\"fault\",\"attribute\":\"128\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"e1\",\"e2\"],\"maxlen\":2}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"lamp\",\"description\":\"烤箱灯状态\",\"name\":\"烤箱灯\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"temp_uint\",\"description\":\"APP端只显示其单位    由MCU端控制显示为℉或者℃\\ntrue-1-摄氏度  false-0华氏度\",\"name\":\"温度单位\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"cool_time\",\"description\":\"进入关机冷却状态后，开始计时，冷却时间由MCU上报，在冷却状态下，APP端不可操作，计时至20S后产品返回待机，之后恢复正常操作\",\"name\":\"关机冷却时间\",\"typeSpec\":{\"type\":\"value\",\"max\":20,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"S\"}},
{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"status_mode\",\"description\":\"wait=待机/set=设置/run=烹饪/stop=冷却关机\\n(pause=暂停，暂停这个状态暂时先保留）\",\"name\":\"工作状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"wait_mode\",\"set_mode\",\"run_mode\",\"stop_mode\",\"pause_mode\",\"time_out\"]}},
{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"send_message\",\"description\":\"noting：无消息\\nalarm：翻锅提醒\\nfinish_cooking：完成烹饪\",\"name\":\"消息推送\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"nothing\",\"alarm\",\"finish_cooking\"]}},
{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"tender_roast\",\"description\":\"0：关闭嫩烤\\n1：开启嫩烤\",\"name\":\"嫩烤功能\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1736237045413,
  "tid": "f6cdaa4fcccd11ef9e5f9e9247cde4aa"
}
```

### Information about how the device functions

Air fryer (kitchen appliance)
[Manual](https://eshop.rohnson.cz/wp-content/uploads/2024/11/R-2858-SmartChef-XL-2-Wi-Fi-EN-MANUAL.pdf)

![image](https://github.com/user-attachments/assets/c65c4ec3-919a-44a6-82a2-caf3aee1b838)

Short description of control panel:

Top row
From left to right:
1st button switch on/off the light in the basket
2nd button: press one time to set the time with + - buttons, press second time to set the temperature with the + - buttons
3rd button is to configure the wifi

The display in the middle showing the remaining time and temperature while the device is working. 
There is also a "shake" indicator. The shake indicator will illuminate when the cooking cycle
has reached its halfway point. This halfway time gives you the opportunity to shake or
flip your food in appliance, which helps ensure even cooking. The "shake" indicator will also trigger a notification in the mobile app.

4th and 5th buttons (+ -) is to adjust the time / temperature in combination with 2nd button (see above).

2nd row
There are 8 pre-made recipes. just select the recipe you want and press the play/pause button to start cooking.

3rd row
1st button starts the cooking process or pause the currently running process 
2nd button power on/off the device
3rd button is the Soft cooking function. Soft cooking function will spray water drop onto the food during cooking, to reserve
juicy and keep the food moist.

**Comment by dimis7** [comment]
Hi. I create my own config for this air fryer.
Feel free to use it / modify as you wish.

```
name: Rohnson Soft Cooking R-2858 SmartChef XL
products:
  - id: dsyz4tnrkwgo2fma
    manufacturer: Rohnson
    model: Soft Cooking R-2858 SmartChef XL

entities:
  - entity: switch
    icon: "mdi:toaster-oven"
    dps:
      - id: 1
        name: switch
        type: boolean

  - entity: switch
    name: Start / Pause
    icon: "mdi:play-pause"
    dps:
      - id: 2
        name: switch
        type: boolean

      - id: 1
        name: available
        type: boolean
        hidden: true
        
  - entity: select
    name: Recipe
    translation_key: recipe
    dps:
        
      - id: 3
        type: string
        name: option
        mapping:
          - dps_val: "drumsticks"
            value: Drumsticks
          - dps_val: "steak"
            value: Steak
          - dps_val: "fish"
            value: Fish
          
          - dps_val: "cake"
            constraint: water_spray
            conditions:
                - dps_val: false
                  value: Cake

          - dps_val: "pizza"
            constraint: water_spray
            conditions:
                - dps_val: false
                  value: Pizza
                  
          - dps_val: "sausage"
            value: Sausage
          - dps_val: "chips"
            value: Chips
         
          - dps_val: "dryfruit"
            constraint: water_spray
            conditions:
                - dps_val: false
                  value: Dryfruit
                  
          - dps_val: "custom"
            value: Custom
  
      - id: 110
        type: boolean
        name: water_spray
        hidden: true
        
      - id: 1
        name: available
        type: boolean
        hidden: true
    
  - entity: number
    name: Cloud recipe
    category: config
    icon: "mdi:cloud-print"
    dps:
      - id: 4
        type: integer
        name: value
        range:
          min: 0
          max: 999999
          
      - id: 1
        name: available
        type: boolean
        hidden: true
        
  - entity: number
    class: temperature
    dps:
      - id: 3
        name: recipe
        type: string
        hidden: true
      - id: 6
        type: integer
        name: value
        unit: C
        range:
          min: 80
          max: 220
        mapping:
          - step: 5
            constraint: recipe
            conditions:
                - dps_val: "dryfruit"
                  range :
                    min: 30
                    max: 80
                    
      - id: 1
        name: available
        type: boolean
        hidden: true
          
  - entity: number
    name: Cooking time
    class: duration
    translation_key: timer
    dps:
      - id: 3
        name: recipe
        type: string
        hidden: true
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 1
          max: 60
        mapping:
          - step: 1
            constraint: recipe
            conditions:
                - dps_val: "dryfruit"
                  step: 60
                  range :
                    min: 120
                    max: 1440
                    
      - id: 1
        name: available
        type: boolean
        hidden: true
        
  - entity: sensor
    translation_key: time_remaining
    class: duration
    dps:
      - id: 10
        type: integer
        name: sensor
        unit: min
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 12
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 12
        type: bitfield
        name: fault_code
  
  - entity: switch
    name: Lamp
    icon: "mdi:lightbulb"
    dps:
      - id: 101
        type: boolean
        name: switch
    
  - entity: sensor
    translation_key: status
    class: enum
    dps:
      - id: 108
        type: string
        name: sensor
        mapping:
          - dps_val: wait_mode
            value: Powered off
          - dps_val: set_mode
            value: Powered on, idle
          - dps_val: run_mode
            value: Cooking
          - dps_val: stop_mode
            value: Cooling off
          - dps_val: time_out
            value: Cooking, Paused
          - dps_val: pause_mode
            value: The pot basket has been drawn out
            

  - entity: sensor
    name: Reminder
    class: enum
    dps:
      - id: 109
        type: string
        name: sensor
        mapping:
          - dps_val: "nothing"
            value: No reminder
          - dps_val: "alarm"
            value: Shake
          - dps_val: "finish_cooking"
            value: Done cooking

  - entity: switch
    name: Water spray
    icon: "mdi:water"
    dps:
      - id: 110
        type: boolean
        name: switch
          
      - id: 1
        name: available
        type: boolean
        hidden: true
        mapping:
          - constraint: recipe
            conditions:
              - dps_val: "cake"
                value: false
              - dps_val: "pizza"
                value: false
              - dps_val: "dryfruit"
                value: false
                        
      - id: 3
        name: recipe
        type: string
        hidden: true
        
  - entity: select
    translation_key: temperature_unit
    readonly: true
    category: config
    dps:
      - id: 103
        type: boolean
        optional: true
        name: option
        mapping:
          - dps_val: true
            value: celsius
          - dps_val: false
            value: fahrenheit
            hidden: true
```
