### ISSUE TITLE
New Device LEDVANCE Sun@Home Wifi

### ISSUE THREAD

**Issue by jwacalex** [make-all/tuya-local#2764]
### Log message

```text
WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches calex_s45cleare27_light with quality of 100%. DPS: {"updated_at": 1736622654.5093665, "20": true, "21": "white", "22": 1000, "23": 1000, "25": "000e0d0000000000000000c80000", "26": 0}
```

### Product Name

LEDVANCE Sun@Home Wifi

### DPS information

```text
Switch: 20 
Mode: 21 (white)
Brightness: 22
Temperature: 23
min color temp: 2200
max color temp: 5000
```

### Information about how the device functions

- Device cannot be integrated into the Smart Life Tuya App
- Ledvance app is necessary for inital setup and key-extraction
- Keys can be extracted with the following tool: https://github.com/FlagX/ha-ledvance-tuya-resync-localkey
- data sources
  -  https://knx-user-forum.de/forum/%C3%B6ffentlicher-bereich/geb%C3%A4udetechnik-ohne-knx-eib/1898515-guide-ledvance-sun-home-in-homeassistant-mittels-localtuya
  - https://developer.tuya.com/en/docs/iot/lamp-classic-template?id=Kab3qvhxz72mw

**Comment by make-all** [comment]
It seems to be a 100% match for an already existing device, and there is no detailed information on dps or product id supplied, so I don't see anything that can be done here.

**Comment by jwacalex** [comment]
``calex_s45cleare27_light`` provides the wrong color temperatures. I've attached a rough but functional prototype



```
name: Ledvance Sun@Home
products:
  - manufacturer: Ledvance
    model: Wifi SUN@HOME
entities:
  - entity: light
    dps:
      - id: 20
        type: boolean
        name: switch
      - id: 21
        type: string
        name: work_mode
        mapping:
          - dps_val: color_temp
            value: color_temp
      - id: 22
        name: brightness
        type: integer
        range:
          min: 10
          max: 1000
      - id: 23
        name: color_temp
        type: integer
        range:
          min: 0
          max: 1000
        mapping:
          - target_range:
              min: 2200
              max: 5000
```
