### ISSUE TITLE
New device request: AVATTO Smart Wifi Thermostat WT100

### ISSUE THREAD

**Issue by Tommy032017** [make-all/tuya-local#279]
Would be great, if you could add this device. Thank you in advance.

**Brand name, model:**
‎Avatto Smart Wifi Thermostat
WT100-EH (most identical device WT100-BH)

**Home Assistant Log:**
```
2022-11-18 10:06:18.595 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches hydrotherm_dynamic_x8_water_heater with quality of 28%. DPS: {'1': True, '2': 215, '3': 213, '4': 'hot', '5': '1', '8': True, '13': True, '16': 0, '20': -18, '21': 25, '25': '1', '26': False, '31': False, '41': '3', '42': '3', '101': False, '105': 5, '107': 35, 'updated_at': 1668762377.2266963}
```
**Tuya IoT,
"Get Device Specification Attribute:"**
```
{
  "result": {
    "category": "wk",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":700,\"scale\":1,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\",\"wind\",\"comfortable\",\"energy\",\"auto\",\"holiday\",\"eco\",\"manual\",\"sleep\",\"dry\",\"program\",\"floor_heat\",\"auxiliary_heat\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":700,\"scale\":1,\"step\":1}"
      },
      {
        "code": "temp_current",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":999,\"scale\":1,\"step\":1}"
      },
      {
        "code": "mode",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"cold\",\"hot\",\"wind\",\"comfortable\",\"energy\",\"auto\",\"holiday\",\"eco\",\"manual\",\"sleep\",\"dry\",\"program\",\"floor_heat\",\"auxiliary_heat\"]}"
      },
      {
        "code": "child_lock",
        "dp_id": 8,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1668762659114,
  "tid": "ea940bcb672011ed8c7e06bdf2add754"
```

Thank you. Pls. let me know, if you need further details.

____________________________
![WT100_EH-wifi_2](https://user-images.githubusercontent.com/26543724/202668956-7f6f1443-7c4d-4642-94b0-dcd5b4c1e3f8.jpg)
![WT100-EH-wifi](https://user-images.githubusercontent.com/26543724/202668964-8c65518d-f6ae-4f03-a674-add012c857a7.jpg)

**Comment by Tommy032017** [comment]
For all who are interested in this device:
I still tested some similar thermostats, which all did not function as expected: Wrong and incomplete manual, not all functions could be set directly on the device (only with tuya app), switching manual, auto, home and away also not selectable directly at the device (only app).
I bought this one (16A, WT100-EH) for my water floor heating, controlled by a 230V valve, NC, not heating valve is closed.
Pos:
- all settings could also be done and programmed directly at the device, without app
- manual is complete and all settings and parameters are described correctly
- settings and programming of schedule times and temperatures could be done directly at the device, without app!
- delay of relay could be programmed (minutes delay), ideal for valves
- temperature hysteresis for switching 230V out could be programmed 0,1 - 0,5 - 1 - .... °C 
- output is 16A, 230V as NC = 230V out for heating, could also be programmed vice versa for NO, means 230V out for not heating.
- display backlight could be adjusted in high, middle, low and off.
Neg:
- front display panel is a little mirrored coated 

Bought it from Amazon for a special discount price of €33

**Comment by Tommy032017** [comment]
Thank you very much for your very fast integration. I am just testing everything and there are several problems. I will come back in a short time. I will collect all problems. In basic it is working well and temperature settings and values are correct.

**Comment by Tommy032017** [comment]
What I found:
![Bildschirmfoto vom 2022-11-20 17-59-29](https://user-images.githubusercontent.com/26543724/202916719-9d7045c2-959c-439b-bf89-d6d78584b536.png)

(in the screenshot the selected mode is "Temporary program mode")

But there are several problems, because "dp_id": 4 only has 3 values and this 3 modes could be selected by the following programmed values in the "avatto_wt100_thermostat.yaml":

Program mode is equivalent to
- dps_val: hot
  value: heat

Temporary program mode is equivalent to
- dps_val: wind
  value: fan_only

Manual mode is equivalent to
- dps_val: cold
  value: Cool


Only this 3 modes "Program mode, Temporary program mode and Program mode" are available in the mode settings of the WT100

All 3 modes could be selected by the created climate card by pressing and selcting "Heat", "Cool" and "Fan only"
The other modes are useless.

Child mode is working as well.

Some more information about the not unknown dp_id's:

DPS: {'1': True, '2': 215, '3': 213, '4': 'hot', '5': '1', '8': True, '13': True, '16': 0, '20': -18, '21': 25, '25': '1', '26': False, '31': False, '41': '3', '42': '3', '101': False, '105': 5, '107': 35,

id20:  -18 , is Temperature calibration (offset), but is in real -1.8 °C
id21:   25 , is "Max setting of temperature"
id107:  35 , is "Max temperature limit of external temperature sensor"
id105:   5 , is "Relay delay when changing temperature"


I've tried to change the yaml by my own, but I do not understand, what dps_val and value exactly do, especially which is the one for the symbol and the sending value.
Seams to be dps_val is the command and value the symbol on the card?

Thank you again.

**Comment by Tommy032017** [comment]
![img4](https://user-images.githubusercontent.com/26543724/202918123-8e659ca8-4c54-47a9-9100-f4111a40e9b8.jpg)
![img3](https://user-images.githubusercontent.com/26543724/202918124-1d576bdc-5bc4-4fff-a44e-21910f712c89.jpg)
![img2](https://user-images.githubusercontent.com/26543724/202918125-ab2a042a-e019-41ff-ac32-a99153741dcd.jpg)
![img1](https://user-images.githubusercontent.com/26543724/202918126-7c7a8060-19b3-409e-8465-a3d61f1d07c3.jpg)

**Comment by Tommy032017** [comment]
So I tried some programming and the device is now nearly perfect working.

**Working perfect:**
- all "secondary_entities"
- climate gauge with actual current temperature and temperature settings

**Not included id's, and not important in my opinion:**
- parameter of weekly schedule (time and temperature settings)
- Sound on/off
- Frost protection settings
- Switching relay between NC and NO
- reset

**Still needs improvement:**
- 3 icons or symbols in the climate gauge to select the 3 modes: Manual mode, Program mode and Temporary Program mode (Override mode)

I didn't know how to implement these icons and functions for 3 modes.
For now, switching between the modes works well under the 3 dots on the top right.
I also do not know, how to eliminate the field "action" under the 3 dots. I think there is no need for this function. Only selecting between the 3 modes will be enough.

avatto_wt100_thermostat.yaml
[avatto_wt100_thermostat.yaml.zip](https://github.com/make-all/tuya-local/files/10057383/avatto_wt100_thermostat.yaml.zip)

```
name: Avatto WT100-EH thermostat
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: hvac_mode
      type: boolean
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          constraint: preset_mode
          conditions:
            - dps_val: cold
              value: "Manual"
            - dps_val: hot
              value: "Program"
            - dps_val: wind
              value: "Program Override"
    - id: 2
      name: temperature
      type: integer
      range:
        min: 0
        max: 700
      mapping:
        - scale: 10
    - id: 3
      name: current_temperature
      type: integer
      readonly: true
      mapping:
        - scale: 10
    - id: 4
      name: preset_mode
      type: string
      mapping:
        - dps_val: cold
          value: "Manual"
        - dps_val: hot
          value: "Program"
        - dps_val: wind
          value: "Program Override"
    - id: 5
      name: unknown_5
      type: string
    - id: 13
      name: unknown_13
      type: boolean
    - id: 26
      name: unknown_26
      type: boolean
    - id: 31
      name: unknown_31
      type: boolean
    - id: 101
      name: unknown_101
      type: boolean
secondary_entities:
  - entity: lock
    name: Child lock
    category: config
    dps:
      - id: 8
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"
  - entity: select
    name: Temperature sensor
    icon: "mdi:thermometer"
    category: config
    dps:
      - id: 25
        type: integer
        name: option
        mapping:
          - dps_val: 1
            value: Internal
          - dps_val: 2
            value: External
          - dps_val: 3
            value: Both
  - entity: number
    name: Temperature calibration offset
    category: config
    icon: "mdi:arrow-expand-horizontal"
    dps:
      - id: 20
        type: integer
        name: value
        mapping:
        - scale: 10
        range:
          min: -99
          max: 99
  - entity: select
    name: Display backlight
    icon: "mdi:lightbulb"
    category: config
    dps:
      - id: 41
        type: integer
        name: option
        mapping:
          - dps_val: 0
            value: "off"
          - dps_val: 1
            value: low
          - dps_val: 2
            value: middle
          - dps_val: 3
            value: high
  - entity: select
    name: Working day settings
    icon: "mdi:calendar"
    category: config
    dps:
      - id: 42
        type: integer
        name: option
        mapping:
          - dps_val: 1
            value: 5+2
          - dps_val: 2
            value: 6+1
          - dps_val: 3
            value: "7.0"
  - entity: number
    name: Max settings temperature
    category: config
    icon: "mdi:arrow-expand-horizontal"
    dps:
      - id: 21
        type: integer
        name: value
        unit: C
        range:
          min: 15
          max: 95
  - entity: number
    name: External sensor temperature limit
    category: config
    icon: "mdi:arrow-expand-horizontal"
    dps:
      - id: 107
        type: integer
        name: value
        unit: C
        range:
          min: 5
          max: 60
  - entity: number
    name: Temperature hysteresis switch difference
    category: config
    icon: "mdi:arrow-expand-horizontal"
    dps:
      - id: 105
        type: integer
        name: value
        mapping:
        - scale: 10
        range:
          min: 5
          max: 95
```
![Bildschirmfoto vom 2022-11-21 13-27-18](https://user-images.githubusercontent.com/26543724/203077285-eccfb4e6-4a5d-4fed-ab54-de225186c0cc.png)
![Bildschirmfoto vom 2022-11-21 13-28-50](https://user-images.githubusercontent.com/26543724/203077338-24dd231e-091f-4e7a-b5dd-0ac1e1db2cd6.png)
![Bildschirmfoto vom 2022-11-21 13-28-36](https://user-images.githubusercontent.com/26543724/203077343-2e0427e5-5ad4-4039-a0f7-9eb0f070b2fb.png)
![Bildschirmfoto vom 2022-11-21 13-28-25](https://user-images.githubusercontent.com/26543724/203077344-128d67f4-0184-4549-808b-a593debcaa1c.png)
![Bildschirmfoto vom 2022-11-21 13-28-02](https://user-images.githubusercontent.com/26543724/203077347-eefbbe13-8262-4962-a5a8-16ed85793829.png)
![Bildschirmfoto vom 2022-11-21 13-27-48](https://user-images.githubusercontent.com/26543724/203077350-5eef768b-3971-4e84-b54d-eb3062406473.png)
