### ISSUE TITLE
Invalid temperature units in climate entity

### ISSUE THREAD

**Issue by vvv2542** [make-all/tuya-local#2802]
### Description

I'm trying to create configuration for Atorch S1TW thermostat. There are the following DPs:
102 - integer temperature in C
124 - integer temperature in F
118 - string temperature unit, possible values 'c' and 'f'
Minimal configuration:
```
name: Temperature controller
products:
  - id: rj84vmyhm0dh0jwy
    name: Atorch S1TW
entities:
 - entity: climate
    dps:
      - id: 102
        type: integer
        name: current_temperature
        mapping:
          - constraint: temperature_unit
            conditions:
              - dps_val: f
                value_redirect: current_temperature_f
      - id: 124
        type: integer
        name: current_temperature_f
      - id: 118
        name: temperature_unit
        type: string
        mapping:
          - dps_val: c
            value: C
          - dps_val: f
            value: F
```
It shows correct value and unit when 118 is set to 'c'. But shows incorrect value and unit when 118 is set to 'f'.

### Steps to reproduce

1. Create configuration shown above.
2. Upload configuration to custom_components/tuya_local/devices.
3. Reload configuration of the device.
4. Change temperature unit to 'f'.

### Expected behaviour

The entity should show '454 °F' (dp124=454, dp118=f), but it shows '234 °C'.

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [ ] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [ ] This is not requesting addition of a new device.
