### ISSUE TITLE
Request support for Video Doorbell TMEZON (MZ-IP-V718TW+MZ-VDP-PW201)

### ISSUE THREAD

**Issue by hajar97** [make-all/tuya-local#2835]
### Log message

```text
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:421
integration: Tuya Local (documentation, issues)
First occurred: 17:08:23 (6 occurrences)
Last logged: 17:22:20

Device matches v330l_petfeeder with quality of 100%. DPS: {"updated_at": 1737562938.1852624, "101": true}
```

### Product ID

h3bhzu9m0ig80rdu

### Product Name

BCom Majic IPBox

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"00000041xe\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"basic_indicator\",\"description\":\"设备设置页面-基本功能设置\\n设备指示灯是否打开，true打开，false关闭\",\"name\":\"指示灯\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"basic_flip\",\"description\":\"设备设置页面-基本功能设置\\n使直播画面垂直翻转，true打开翻转，false关闭翻转\",\"name\":\"画面翻转\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"basic_osd\",\"description\":\"设备设置页面-基本功能设置\\n时间水印功能开关，true打开水印，false关闭水印\",\"name\":\"时间水印\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"motion_sensitivity\",\"description\":\"0-2，灵敏度依次增加；仅为灵敏度，0并不是关闭移动侦测报警；规定0为低灵敏度，1为中灵敏度，2为高灵敏度。\",\"name\":\"移动侦测灵敏度\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\"]}},
{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"basic_nightvision\",\"description\":\"0:自动\\n1:关\\n2:开\",\"name\":\"红外夜视\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\"]}},
{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"sd_storge\",\"description\":\"示例：\\n---2017.07.08更新---\\n单位改为kb\\n---\\n3503775744|778977280|2718158848\\n其中第一字符串是总容量，第二个字符串是已使用的容量，第三个是剩余容量\",\"name\":\"获取存储卡容量\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":110,\"accessMode\":\"ro\",\"code\":\"sd_status\",\"description\":\"status：sd卡状态，1-正常，2-异常，3-空间不足，4-正在格式化，5-无SD卡；\",\"name\":\"存储卡状态\",\"typeSpec\":{\"type\":\"value\",\"max\":5,\"min\":1,\"scale\":1,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"sd_format\",\"description\":\"无参数\",\"name\":\"存储卡格式化\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":115,\"accessMode\":\"ro\",\"code\":\"movement_detect_pic\",\"description\":\"该功能实现请参考SDK\\n---------------\\n{\\\"dp_id\\\",\\\"bucket;object;key\\\"}/{\\\"dp_id\\\",\\\"bucket;object;\\\"}\\n\\nbucket:根文件夹；objcet:文件路径；key:加密\",\"name\":\"检测到移动\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":117,\"accessMode\":\"ro\",\"code\":\"sd_format_state\",\"description\":\"返回错误码：\\n-2000：SD卡正在格式化\\n-2001：SD卡格式化异常\\n-2002：无SD卡\\n-2003：SD卡错误\\n\\n//正数为格式化进度\",\"name\":\"格式化状态\",\"typeSpec\":{\"type\":\"value\",\"max\":20000,\"min\":-20000,\"scale\":1,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":136,\"accessMode\":\"ro\",\"code\":\"doorbell_active\",\"description\":\"\",\"name\":\"门铃-呼叫\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":148,\"accessMode\":\"rw\",\"code\":\"accessory_lock\",\"description\":\"\",\"name\":\"锁1\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":150,\"accessMode\":\"rw\",\"code\":\"record_switch\",\"description\":\"设备设置页面-存储卡设置\\nSD卡录像开关，true为打开，false为关闭\\n功能关闭时，不录像到SD卡\",\"name\":\"SD卡录像-开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":151,\"accessMode\":\"rw\",\"code\":\"record_mode\",\"description\":\"设备设置页面-存储卡设置\\nSD卡录像模式选择，1为事件录像（检测到移动再录像到SD卡），2为连续录像\",\"name\":\"SD卡录像-模式选择\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"1\",\"2\"]}},
{\"abilityId\":154,\"accessMode\":\"ro\",\"code\":\"doorbell_pic\",\"description\":\"用户按下门铃，抓拍图片并上传\",\"name\":\"门铃-抓拍图片\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":162,\"accessMode\":\"rw\",\"code\":\"device_restart\",\"description\":\"无参数，页面操作为按钮类型，用户点击远程重启，直接发送ture的命令。\",\"name\":\"设备远程重启\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":231,\"accessMode\":\"rw\",\"code\":\"ipc_c_switch_channel\",\"description\":\"博科切换通道\",\"name\":\"切换通道\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":232,\"accessMode\":\"rw\",\"code\":\"ipc_c_lock\",\"description\":\"博科锁2    数据类型:bool    数据传输类型:rw\",\"name\":\"锁2\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1731661939765,
  "tid": "b75ea1e7a33111ef9520ae18e4d9fbe2"
}
```

### Information about how the device functions

Hopefully, I filled out all the fields correctly this time. If not, please let me know what additional information may be needed. Thanks.

**Comment by hajar97** [comment]
Thank you @make-all. Somehow github didn't notify me there was a commit on this issue, so I only saw the status update today.

I downloaded the yaml file and tested it on my setup. It works really well. There are a couple of improvements I can suggest, but they are minor. Like the second door lock with DSP 148 hasn't been added. 

The main issues remaining unresolved though are:
1. No camera view available through this integration. It remains empty when I press on camera. 
2. Many of these switches are only becoming active and functioning if I open camera view in HA Tuya integration or Tuya app directly. As soon as I close the camera view all of the switches in Tuya Local stop having any impact. Main example is the door lock (DSP 148) which only works this way. The other door lock with DSP 232 works always, without this trick. But its the other lock that I need more than this one. 

I'll keep digging to try to understand why I cannot get camera view locally, but since you have so much experience with Tuya devices may be something rings your bell? Any idea or any closely related another Tuya device yaml file that I could check out for inspiration?

**Comment by make-all** [comment]
Tuya devices do not deliver the camera feed through the tuya protocol. Some cameras have local streaming support through standard protocols, but you will need to find the port, username and password your camera uses. Others are cloud only.

The documentation for Tuya's camera streaming is here:
https://developer.tuya.com/en/docs/iot/iot-video-live-stream?id=Kaiuyzn1xn2aa

**Comment by hajar97** [comment]
Got it, thank you. Will revert as soon as I get a chance to test every feature thoroughly.

**Comment by hajar97** [comment]
Ok, I made yaml configuration more aligned with the features of the device. Everything seems to work well, except for the camera, which sadly I was unable to connect to locally. Tried every trick, port scanning, wireshark, nothing yielded any results. 

Since other local features are working well this is a nice integration. But... While testing I discovered a strange blocking issue. The moment I add this device to my Tuya Local it starts unlocking and then locking my Accessory lock every 35s. My guess is that Tuya Local is probably polling the device with this frequency and each time it does a poll it somehow causes the Accessory lock to unlock and after a few seconds it automatically locks again. If I delete tuya local integration this behaviour stops.

I tried minimising yaml to have only Accessory lock and none of the other features. The issue remains. 

I then tried only removing the Accessory lock but keeping other features. Same issue. My door keeps unlocking every 35s. 

The moment I delete this device from Tuya Local this behaviour stops.

Do you think my guess about device polling could be right or is it something else? Any idea what could it be and how to stop this weird behaviour?

Here is my latest yaml version just in case:
```
name: Smart Intercom
products:
  - id: h3bhzu9m0ig80rdu
    manufacturer: Bcom
    model: Majic IPBox
entities:
  - entity: camera
    dps:
      - id: 154
        name: snapshot
        type: base64
        optional: true
        persist: false
        sensitive: true
        readonly: true
        mapping:
          - dps_val: null
            value_redirect: movement_pic
  - entity: lock
    name: Accessory lock
    dps:
      - id: 148
        type: boolean
        optional: true
        name: lock
        mapping:
          - dps_val: true # Unlocked
            value: false
          - dps_val: false # Locked
            value: true
  - entity: light
    name: Indicator light
    category: config
    dps:
      - id: 101
        type: boolean
        name: switch
  - entity: switch
    name: Flip
    icon: "mdi:flip-horizontal"
    category: config
    dps:
      - id: 103
        type: boolean
        optional: true
        name: switch
        mapping:
          - dps_val: null
            value: false
            hidden: true
  - entity: switch
    name: Time watermark
    category: config
    icon: "mdi:watermark"
    dps:
      - id: 104
        type: boolean
        optional: true
        name: switch
        mapping:
          - dps_val: null
            value: false
            hidden: true
  - entity: select
    name: Motion detection sensitivity
    icon: "mdi:motion-sensor"
    category: config
    dps:
      - id: 106
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "0"
            value: Low
          - dps_val: "1"
            value: Medium
          - dps_val: "2"
            value: High
          - dps_val: null
            value: Low
            hidden: true
  - entity: select
    name: Night vision
    icon: "mdi:theme-light-dark"
    category: config
    dps:
      - id: 108
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "0"
            value: Auto
          - dps_val: "1"
            value: "Off"
          - dps_val: "2"
            value: "On"
          - dps_val: null
            value: Auto
            hidden: true
  #- entity: sensor
  #  name: SD capacity
  #  category: diagnostic
  #  dps:
  #    - id: 109
  #      type: string
  #      optional: true
  #      name: sensor
  #      readonly: true
  - entity: sensor
    name: SD status
    class: enum
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        optional: true
        mapping:
          - dps_val: 1
            value: normal
          - dps_val: 2
            value: error
          - dps_val: 3
            value: full
          - dps_val: 4
            value: formatting
          - dps_val: 5
            value: missing
          - dps_val: null
            value: normal
            hidden: true
        readonly: true
      - id: 109
        type: string
        optional: true
        name: memory_card_capacity
        readonly: true
  - entity: button
    name: Format SD card
    category: config
    dps:
      - id: 111
        type: boolean
        optional: true
        name: button
      - id: 117
        type: integer
        optional: true
        readonly: true
        name: sd_format_status
        mapping:
          - dps_val: 2000
            value: Formatting
          - dps_val: 2001
            value: Format error
          - dps_val: 2002
            value: "No SD card"
          - dps_val: 2003
            value: Card error
  - entity: event
    class: doorbell
    dps:
      - id: 136
        type: string
        name: event
        optional: true
        mapping:
          - dps_val: ""
            value: null
          - dps_val: null
            value: null
          - value: ring
      - id: 136
        type: string
        optional: true
        name: raw_event
  - entity: switch
    name: Video recording
    category: config
    icon: "mdi:record-rec"
    dps:
      - id: 150
        type: boolean
        optional: true
        name: switch
        mapping:
          - dps_val: null
            value: false
            hidden: true
  - entity: select
    name: Recording mode
    icon: "mdi:file-video"
    category: config
    dps:
      - id: 151
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "1"
            value: Event
          - dps_val: "2"
            value: Continuous
          - dps_val: null
            value: Event
            hidden: true
  - entity: button
    category: config
    class: restart
    dps:
      - id: 162
        type: boolean
        optional: true
        name: button
  - entity: sensor
    name: IPC channel
    icon: "mdi:ab-testing"
    category: diagnostic
    dps:
      - id: 231
        type: string
        optional: true
        name: sensor
  - entity: lock
    name: IPC lock
    dps:
      - id: 232
        type: boolean
        optional: true
        name: lock
        mapping:
          - dps_val: true # Unlocked
            value: false
          - dps_val: false # Locked
            value: true
  - entity: event
    class: motion
    category: diagnostic
    dps:
      - id: 115
        type: string
        name: event
        optional: true
        mapping:
          - dps_val: null
            value: clear
          - value: detected
      - id: 115
        type: base64
        name: movement_pic
        sensitive: true
        optional: true
```

**Comment by make-all** [comment]
It sounds like your device may be rebooting or toggling that lock for some other reason when we do a request for full status.

If polling is not ticked in the config, we should not be doing any polling, but there is a persistent connection with a heartbeat sent every 5s, and status request every 30s (if the test for that uses `>`, it would explain why exactly 35s since the next heartbeat due after 30s will be at 35s). If the device does not like the way status is being requested, it could be a sign that the wrong protocol version is being used.  Version 3.2 and 3.3 are very close, except for the commands used to request status and setting dps. Version 3.22 uses the same command as 3.2 for requesting status, but uses the command from 3.3 for setting dps.

**Comment by hajar97** [comment]
Hi Jason. I have done endless testing and sadly my conclusion is that this device isn't adding much value with local only connection. 

I managed to make it work more or less stably with protocol v3.2. 

The main drawback is that everything that has to do with camera is not working locally: 
- There is no access to camera stream.
- There is no access to camera snapshots, whether during doorbell ring or motion detection
- There is no triggering of doorbell ring locally, dps 136 is never provided

And with that there is very limited use. Main functionality is reduced to:
- Access to lock, of which IP camera lock works 100% stably locally
- Accessory lock sometimes work and sometimes doesn't, its performance somehow tightly connected with the use of camera for some reason
- Whenever camera is activated (through viewing the camera view or through doorbell press) a dps 231 is triggered, which I connected to doorbell binary sensor. And that would be a nice doorbell sensor if it was only triggered when someone pressed the doorbell. But unfortunately it gets triggered on any camera livestream activation. And it only works if there is internet connection to tuya servers. If those are disabled, then this function stops working too. 

Below is the final, polished and commented version of the yaml config that in my opinion makes most sense for this device given very little info that it provides. In case you have any other ideas of what else I could try I am happy to test it. Otherwise will leave it with this config for now until there is some big breakthrough in future on how to make it provide more of the local information.

```
name: Smart Intercom
products:
  - id: h3bhzu9m0ig80rdu
    manufacturer: Bcom
    model: Majic IPBox
entities:
  # Unfortunately camera entity and everything related to it is not accessible locally at this point
  #- entity: camera
  #  dps:
  #    - id: 154
  #      name: snapshot
  #      type: text # base64
  #      optional: true
  #      persist: false
  #      sensitive: true
  #      readonly: true
  #      mapping:
  #        - dps_val: null
  #          value_redirect: movement_pic
  #    - id: 115
  #      type: text # base64
  #      name: movement_pic
  #      sensitive: true
  #      optional: true

  # Unfortunately camera entity and everything related to it is not accessible locally at this point
  #- entity: event
  #  class: motion
  #  category: diagnostic
  #  dps:
  #    - id: 115
  #      type: string
  #      name: event
  #      optional: true
  #      mapping:
  #        - dps_val: null
  #          value: clear
  #        - value: detected

  # Unfortunately no doorbell event is ever triggered locally even though this dps is officially supported
  #- entity: event
  #  class: doorbell
  #  dps:
  #    - id: 136
  #      type: string
  #      name: event
  #      optional: true
  #      mapping:
  #        - dps_val: ""
  #          value: null
  #        - dps_val: null
  #          value: null
  #        - value: ring
  #    - id: 136
  #      type: string
  #      optional: true
  #      name: raw_event
  - entity: lock
    name: Accessory lock
    dps:
      - id: 148
        type: boolean
        optional: true
        name: lock
        mapping:
          - dps_val: true # Unlocked
            value: false
          - dps_val: false # Locked
            value: true
          - dps_val: null
            value: true
            hidden: true
  - entity: lock
    name: IP camera lock
    dps:
      - id: 232
        type: boolean
        optional: true
        name: lock
        mapping:
          - dps_val: true # Unlocked
            value: false
          - dps_val: false # Locked
            value: true
          - dps_val: null
            value: true
            hidden: true
  # this only activates if there is connection to Tuya Cloud, otherwise it does not trigger
  - entity: binary_sensor
    name: Doorbell
    icon: "mdi:doorbell"
    dps:
      - id: 231
        type: boolean
        optional: true
        persist: false
        readonly: true
        name: sensor
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 231
        type: string
        optional: true
        name: ipc_c_switch_channel
  - entity: light
    name: Indicator light
    category: config
    dps:
      - id: 101
        type: boolean
        name: switch
  - entity: switch
    name: Flip
    icon: "mdi:flip-vertical"
    category: config
    dps:
      - id: 103
        type: boolean
        optional: true
        name: switch
        mapping:
          - dps_val: null
            value: false
            hidden: true
  - entity: switch
    name: Time watermark
    category: config
    icon: "mdi:watermark"
    dps:
      - id: 104
        type: boolean
        optional: true
        name: switch
        mapping:
          - dps_val: null
            value: true
            hidden: true
  - entity: select
    name: Motion detection sensitivity
    icon: "mdi:motion-sensor"
    category: config
    dps:
      - id: 106
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "0"
            value: "Low sensitivity"
          - dps_val: "1"
            value: "Medium sensitivity"
          - dps_val: "2"
            value: "High sensitivity"
          - dps_val: null
            value: "Low sensitivity"
            hidden: true
  - entity: select
    name: Night vision
    icon: "mdi:theme-light-dark"
    category: config
    dps:
      - id: 108
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "0"
            value: Automatic
          - dps_val: "1"
            value: "Off"
          - dps_val: "2"
            value: "On"
          - dps_val: null
            value: Automatic
            hidden: true
  - entity: switch
    name: Video recording
    category: config
    icon: "mdi:record-rec"
    dps:
      - id: 150
        type: boolean
        optional: true
        name: switch
        mapping:
          - dps_val: null
            value: true
            hidden: true
  - entity: select
    name: Record mode
    icon: "mdi:file-video"
    category: config
    dps:
      - id: 151
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: "1"
            value: "Record events only"
          - dps_val: "2"
            value: "Continuous recording"
          - dps_val: null
            value: "Record events only"
            hidden: true
  - entity: button
    category: diagnostic
    class: restart
    dps:
      - id: 162
        type: boolean
        optional: true
        name: button
  - entity: button
    name: SD card - format
    category: diagnostic
    dps:
      - id: 111
        type: boolean
        optional: true
        name: button
      - id: 117
        type: integer
        optional: true
        readonly: true
        name: sd_format_status
        mapping:
          - dps_val: 2000
            value: Formatting
          - dps_val: 2001
            value: Format error
          - dps_val: 2002
            value: "No SD card"
          - dps_val: 2003
            value: Card error
  - entity: sensor
    name: SD card - status
    class: enum
    icon: mdi:sd
    category: diagnostic
    dps:
      - id: 110
        type: integer
        name: sensor
        optional: true
        mapping:
          - dps_val: 1
            value: normal
          - dps_val: 2
            value: error
          - dps_val: 3
            value: full
          - dps_val: 4
            value: formatting
          - dps_val: 5
            value: missing
          - dps_val: null
            value: normal
            hidden: true
        readonly: true
      - id: 109
        type: string
        optional: true
        name: memory_card_capacity
        readonly: true
```
