### ISSUE TITLE
New Device: Hosome Air Purifier (KJ210F-142-01-C)

### ISSUE THREAD

**Issue by Kulturnilpferd** [make-all/tuya-local#284]
Hey there, I LOVE your project!!! Its really easy to understand what and how to do for me so I want to give a little bit back to the community... More is comming =)
(Hint: If i installed yesterday this beautiful project I had a conflict between [beok_tol47_thermostat.yaml](https://github.com/make-all/tuya-local/blob/main/custom_components/tuya_local/devices/beok_tol47_thermostat.yaml) don't know if its fixed (was edited yesterday)... Because i doesn't have such a smart thing I just deleted the yaml to proceed, just let you know :D
```
name: Hosome Air Purifier
products:
  - id: sferhht3hjkc942e
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch        
    - id: 3
      name: preset_mode
      type: string
      mapping:
        - dps_val: "Auto"
          value: "auto"
        - dps_val: "Manual"
          value: "manual"
        - dps_val: "Sleep"
          value: "sleep"
    - id: 4
      type: integer
      name: speed
      range:
        min: 1
        max: 3
      mapping:
        - scale: 1
secondary_entities:
  - entity: sensor
    name: PM2.5
    class: pm25
    dps:
      - id: 2
        type: integer
        name: sensor
        class: measurement
        unit: ugm3
  - entity: sensor
    name: Filter
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: "%"
        readonly: true
```
