### ISSUE TITLE
Request support for Tuya TH05Z Zigbee Temperature and humidity sensor

### ISSUE THREAD

**Issue by istenik** [make-all/tuya-local#2885]
### Log message

```text
2025-01-28 18:18:16.751 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches ble_pt216_temp_humidity with quality of 50%. DPS: {"updated_at": 1738084679.5771556, "1": 208, "2": 47, "4": 100, "9": "c", "10": 390, "11": 0, "12": 60, "13": 20, "17": 120, "18": 120, "19": 6, "20": 6}
```

### Product ID

vvmbj46n

### Product Name

Tuya TH05Z

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"e0s45g\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1666\",\"trigger\":\"direct\"},\"name\":\"温度\",\"typeSpec\":{\"type\":\"value\",\"max\":600,\"min\":-200,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"humidity_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-shidu\",\"attribute\":\"1666\",\"trigger\":\"direct\"},\"name\":\"湿度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":4,\"accessMode\":\"ro\",\"code\":\"battery_percentage\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_battery\",\"attribute\":\"1154\",\"trigger\":\"direct\"},\"name\":\"电池电量\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"temp_unit_convert\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"温标\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"c\",\"f\"]}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"maxtemp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1152\"},\"name\":\"温度上限\",\"typeSpec\":{\"type\":\"value\",\"max\":600,\"min\":-200,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"minitemp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu1\",\"attribute\":\"1152\"},\"name\":\"温度下限\",\"typeSpec\":{\"type\":\"value\",\"max\":600,\"min\":-200,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"maxhum_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1152\"},\"name\":\"湿度上限\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":13,\"accessMode\":\"rw\",\"code\":\"minihum_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"1152\"},\"name\":\"湿度下限\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"%\"}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"temp_alarm\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"attribute\":\"1152\"},\"name\":\"温度报警\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"hum_alarm\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"attribute\":\"1152\"},\"name\":\"湿度报警\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"temp_periodic_report\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"1152\"},\"name\":\"温度上报\",\"typeSpec\":{\"type\":\"value\",\"max\":120,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"min\"}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"hum_periodic_report\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"1152\"},\"name\":\"湿度上报\",\"typeSpec\":{\"type\":\"value\",\"max\":120,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"min\"}},
{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"temp_sensitivity\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu2\",\"attribute\":\"1152\"},\"name\":\"温度灵敏度\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":3,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"hum_sensitivity\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_wet2\",\"attribute\":\"1152\"},\"name\":\"湿度灵敏度\",\"typeSpec\":{\"type\":\"value\",\"max\":10,\"min\":3,\"scale\":0,\"step\":1,\"unit\":\"%\"}}]}]}"
  },
  "success": true,
  "t": 1738078507491,
  "tid": "73c854b0dd8d11ef9e609e9247cde4aa"
}
```

### Information about how the device functions

I developed configuration file.
Please check it and add it to the distribution.
Thanks.

```
name: Temperature and humidity sensor
products:
  - id: vvmbj46n
    model: TH05Z
entities:
  - entity: sensor
    class: temperature
    dps:
      - id: 1
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    class: humidity
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: sensor
    category: diagnostic
    class: battery
    dps:
      - id: 4
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: select
    translation_key: temperature_unit
    category: config
    hidden: true
    dps:
      - id: 9
        type: string
        name: option
        mapping:
          - dps_val: c
            value: celsius
          - dps_val: f
            value: fahrenheit
  - entity: number
    name: High temperature limit
    category: config
    class: temperature
    icon: "mdi:thermometer-chevron-up"
    hidden: true
    dps:
      - id: 10
        type: integer
        name: value
        unit: C
        range:
          min: -200
          max: 600
        mapping:
          - scale: 10
  - entity: number
    name: Low temperature limit
    category: config
    class: temperature
    icon: "mdi:thermometer-chevron-down"
    hidden: true
    dps:
      - id: 11
        type: integer
        name: value
        unit: C
        range:
          min: -200
          max: 600
        mapping:
          - scale: 10
  - entity: number
    name: High humidity limit
    category: config
    class: humidity
    hidden: true
    dps:
      - id: 12
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
  - entity: number
    name: Low humidity limit
    category: config
    class: humidity
    hidden: true
    dps:
      - id: 13
        type: integer
        name: value
        unit: "%"
        range:
          min: 0
          max: 100
  - entity: sensor
    name: Temperature alarm
    category: diagnostic
    class: enum
    icon: "mdi:thermometer-alert"
    hidden: true
    dps:
      - id: 14
        type: string
        name: sensor
        optional: true
        mapping:
          - dps_val: upperalarm
            value: "High temperature"
          - dps_val: loweralarm
            value: "Low temperature"
          - dps_val: cancel
            value: "No alarm"
  - entity: sensor
    name: Humidity alarm
    category: diagnostic
    class: enum
    icon: "mdi:water-percent-alert"
    hidden: true
    dps:
      - id: 15
        type: string
        name: sensor
        optional: true
        mapping:
          - dps_val: upperalarm
            value: "High humidity"
          - dps_val: loweralarm
            value: "Low humidity"
          - dps_val: cancel
            value: "No alarm"
  - entity: number
    name: Temperature report interval
    category: config
    icon: "mdi:clock"
    hidden: true
    dps:
      - id: 17
        type: integer
        name: value
        unit: min
        range:
          min: 1
          max: 120
  - entity: number
    name: Humidity report interval
    category: config
    icon: "mdi:clock"
    hidden: true
    dps:
      - id: 18
        type: integer
        name: value
        unit: min
        range:
          min: 1
          max: 120
  - entity: number
    name: Temperature calibration
    category: config
    class: temperature
    icon: "mdi:thermometer-check"
    hidden: true
    dps:
      - id: 19
        type: integer
        name: value
        unit: C
        range:
          min: 3
          max: 10
        mapping:
          - scale: 10
  - entity: number
    name: Humidity calibration
    category: config
    class: humidity
    icon: "mdi:water-percent"
    hidden: true
    dps:
      - id: 20
        type: integer
        name: value
        unit: "%"
        range:
          min: 3
          max: 10

```
