### ISSUE TITLE
Request support for <Single-phase reclosing V3_2P_63_bidirect>

### ISSUE THREAD

**Issue by abdul-karim-mia** [make-all/tuya-local#2910]
### Log message

```text
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:421
integration: Tuya Local (documentation, issues)
First occurred: 6:22:20 PM (1 occurrences)
Last logged: 6:22:20 PM

Device matches taxnele_energy_meter with quality of 50%. DPS: {"updated_at": 1738673497.4494379, "1": 219102, "9": 0, "11": false, "12": true, "13": 0, "15": 0, "16": true, "102": 5, "103": 23, "104": true, "105": 0, "106": "EwAAAAAAAAAAAA==", "107": 5, "109": "AAAA", "110": 0, "134": "2"}
```

### Product ID

d7f0f5753b81eecb52rcws

### Product Name

单相重合闸V3_2P_63_bidirect. En: Single-phase reclosing V3_2P_63_bidirect

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"f62900\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"total_forward_energy\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lightning\",\"attribute\":\"1152\"},\"name\":\"正向总有功电量\",\"typeSpec\":{\"type\":\"value\",\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"unit\":\"kW·h\"}},
{\"abilityId\":6,\"accessMode\":\"ro\",\"code\":\"phase_a\",\"description\":\"1，A相电压，电流及功率\\n2，大端模式，HEX格式，共8个字节\\n3，单位精度：电压，2字节，单位0.1V。电流，3字节，单位 0.001A 。A相有功功率，3字节，单位0.0001kW\\n4，报文格式\\n举例：08 80 00 03 E8 00 27 10 表示A相217.6V，A相电流1.000A，A相功率10.000KW\\n5，通信逻辑：\\n1）用户进面板，主动查询。用户进入面板，面板马上下发0x08到电表，电表上报数据到云平台，面板拿到数据，然后展示。 注：最新WIFI支持。   \\n2）电表基于一定周期上报数据。建议：在WIFI模式时，15秒上报一次。NB模式时，1个小时上报一次。\",\"extensions\":{\"iconName\":\"icon-dp_lightning\",\"attribute\":\"1152\"},\"name\":\"A相电压，电流及功率\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":9,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"1，告警\\n2，大端模式，HEX,4字节\\n3，报文格式\\n按照完整4个字节,对应的告警位上报告警；bit位，1表示有告警，0表示无告警；如果没用的告警位，补0。高位无定义，也补0；\\n举例：0X00 00 00 09,表示当前发生了漏电自检不正常告警和短路告警,无其它告警。\\n4，通信逻辑\\n只要有1个告警发生，就完整4个字节上报给面板；只要有1个告警关闭，就完整4个字节上报给面板，更新面板显示。\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"short_circuit_alarm\",\"surge_alarm\",\"overload_alarm\",\"leakagecurr_alarm\",\"temp_dif_fault\",\"fire_alarm\",\"high_power_alarm\",\"self_test_alarm\",\"ov_cr\",\"unbalance_alarm\",\"ov_vol\",\"undervoltage_alarm\",\"miss_phase_alarm\",\"outage_alarm\",\"magnetism_alarm\",\"credit_alarm\",\"no_balance_alarm\",\"phase_seq_err_alarm\",\"vol_unbalance_alarm\",\"low_current_alarm\"],\"maxlen\":20}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"switch_prepayment\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_money\",\"attribute\":\"1152\"},\"name\":\"预付费功能开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"clear_energy\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lightning\",\"attribute\":\"1152\"},\"name\":\"剩余可用电量清零\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":13,\"accessMode\":\"ro\",\"code\":\"balance_energy\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lightning\",\"attribute\":\"1152\"},\"name\":\"剩余可用电量显示 (kWh)\",\"typeSpec\":{\"type\":\"value\",\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"unit\":\"kW·h\"}},
{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"charge_energy\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_money\",\"attribute\":\"1152\"},\"name\":\"电量充值\",\"typeSpec\":{\"type\":\"value\",\"max\":999999,\"min\":0,\"scale\":2,\"step\":1,\"unit\":\"kW·h\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"leakage_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power1\",\"attribute\":\"1152\"},\"name\":\"剩余电流显示\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"mA\"}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1153\"},\"name\":\"断路器开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"alarm_set_1\",\"description\":\"1，告警阈值使能控制及设置2  \\n2，HEX格式，大端模式, 总告警的数量*4字节= 设置告警总长度。\\n3，报文格式\\n每个告警由4个字节组成，第1个字节（表示该告警存在）；第2个字节（发生此告警时，断路器控制模式（0X01拉闸，0X00不动作只告警）；第3、4字节：设置告警阈值\\n举例：0X01 01 00 00 03 01 00 14,表示该断路器支持短路告警，发生该告警时，自动跳闸，阀值补0。支持过载告警，发生该告警时，拉闸动作，动作阀值20KW。无其它告警。\\n4，通信逻辑\\nA，配网成功后，按照上面的格式，主动上报给云平台，面板知道哪些告警是断路器当前支持的。设置不成功，重新配网再上报。\\nB，断路器上电时，也上报一次。\\nC，面板根据协议下发告警设置。\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"attribute\":\"1152\"},\"name\":\"告警设置1\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"alarm_set_2\",\"description\":\"1，告警阈值使能控制及设置2  \\n2，HEX格式，大端模式\\n3，报文格式\\n每个告警由4个字节组成，第1个字节（表示该告警存在）；第2个字节（发生此告警时，断路器控制模式（0X01拉闸，0X00不动作只告警）；第3、4字节：设置告警阈值\\n举例：0X01 01 00 3C 03 01 00 F5,表示该断路器支持过流告警，发生该告警时，拉闸动作，动作阀值60A。支持过压告警，发生该告警时，拉闸动作，动作阀值245V\\n4，通信逻辑\\nA，配网成功后，按照上面的格式，主动上报给云平台，面板知道哪些告警是断路器当前支持的。设置不成功，重新配网再上报。\\nB，断路器上电时，也上报一次。\\nC，面板根据协议下发告警设置。\",\"extensions\":{\"iconName\":\"icon-dp_warming\",\"attribute\":\"1152\"},\"name\":\"告警设置2\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"recover_sec\",\"description\":\"\",\"name\":\"合闸恢复时间（弃用）\",\"typeSpec\":{\"type\":\"value\",\"max\":99,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"秒\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"recover_cnt\",\"description\":\"\",\"name\":\"重合闸允许次数\",\"typeSpec\":{\"type\":\"value\",\"max\":30,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"次\"}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"4096\"},\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":200,\"min\":-20,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"recover_enable\",\"description\":\"\",\"name\":\"重合闸允许使能\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"4096\"},\"name\":\"倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"cycle_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"4096\"},\"name\":\"循环定时\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"leak_delay\",\"description\":\"\",\"name\":\"合闸恢复时间\",\"typeSpec\":{\"type\":\"value\",\"max\":99,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"s\"}},
{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"random_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"4096\"},\"name\":\"随机定时\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"switch_inching\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"4096\"},\"name\":\"点动开关（延时关）\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":110,\"accessMode\":\"ro\",\"code\":\"reverse_energy_total\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lightning\",\"attribute\":\"4096\"},\"name\":\"反向总有功电量\",\"typeSpec\":{\"type\":\"value\",\"max\":99999999,\"min\":0,\"scale\":2,\"step\":1,\"unit\":\"kW·h\"}},
{\"abilityId\":111,\"accessMode\":\"ro\",\"code\":\"power_total\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lightning\",\"attribute\":\"4096\"},\"name\":\"总功率\",\"typeSpec\":{\"type\":\"value\",\"max\":900000,\"min\":0,\"scale\":3,\"step\":1,\"unit\":\"kW\"}},
{\"abilityId\":126,\"accessMode\":\"rw\",\"code\":\"alarm_set3\",\"description\":\"同告警设置1\",\"name\":\"告警设置3\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":127,\"accessMode\":\"ro\",\"code\":\"status\",\"description\":\"0.\\t不显示  1. 用电 。2 发电\",\"name\":\"状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\"]}},
{\"abilityId\":128,\"accessMode\":\"ro\",\"code\":\"status_b\",\"description\":\"0.\\t不显示  1. 用电 。2 发电\",\"name\":\"状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\"]}},
{\"abilityId\":129,\"accessMode\":\"ro\",\"code\":\"status_c\",\"description\":\"0.\\t不显示  1. 用电 。2 发电\",\"name\":\"状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\"]}},
{\"abilityId\":134,\"accessMode\":\"rw\",\"code\":\"swithc_power_save\",\"description\":\"0- OFF； 1-ON; 2-断电记忆\",\"name\":\"继电器上电状态设置\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\"]}}]}]}"
  },
  "success": true,
  "t": 1738673831094,
  "tid": "8c499540e2f711ef8c8d6ace3d884ac3"
}
```

### Information about how the device functions

```
name: Energy meter
products:
  - id: d7f0f5753b81eecb52rcws
    manufacturer: Yueqing Taixin Electric Co., Ltd.
    model: 63ACB
entities:
  - entity: switch
    icon: "mdi:fuse"
    name: Breaker
    dps:
      - id: 16
        type: boolean
        name: switch
      - id: 19
        type: string
        name: breaker_number
        optional: true
  - entity: sensor
    class: energy
    name: Total forward energy
    dps:
      - id: 1
        type: integer
        name: sensor
        class: total_increasing
        unit: kWh
        mapping:
          - scale: 100
  - entity: sensor
    class: energy
    name: Total Reverse Energy 
    dps:
      - id: 110
        type: integer
        name: sensor
        class: total_increasing
        unit: kWh
        mapping:
          - scale: 100
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 9
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 9
        type: bitfield
        name: fault_code
      - id: 9
        type: bitfield
        name: description
        mapping:
          - dps_val: 0
            value: OK
          - dps_val: 1
            value: Short circuit
          - dps_val: 2
            value: Surge
          - dps_val: 4
            value: Overload
          - dps_val: 8
            value: Earth leak
          - dps_val: 16
            value: High temperature
          - dps_val: 32
            value: Fire
          - dps_val: 64
            value: High power
          - dps_val: 128
            value: Self test
          - dps_val: 256
            value: Over current
          - dps_val: 512
            value: Unbalanced
          - dps_val: 1024
            value: Over voltage
          - dps_val: 2048
            value: Under voltage
          - dps_val: 4096
            value: Phase fault
          - dps_val: 8192
            value: Outage
          - dps_val: 16384
            value: Magnetism
          - dps_val: 32768
            value: Low credit
          - dps_val: 65536
            value: Credit expired
  - entity: switch
    name: Prepay
    category: config
    icon: "mdi:hand-coin"
    dps:
      - id: 11
        type: boolean
        name: switch
  - entity: switch
    name: Reclosing
    category: config
    icon: "mdi:restart"
    dps:
      - id: 104
        type: boolean
        name: switch
  - entity: select
    name: Power lost recovery 
    category: config
    icon: "mdi:clock-check"
    dps:
      - id: 134
        type: string
        name: option
        mapping:
          - dps_val: "0"
            value: "Off"
          - dps_val: "1"
            value: "On"
          - dps_val: "2"
            value: Last
  - entity: number
    category: config
    name: Reclosing Count
    dps:
      - id: 102
        type: integer
        name: value
        range:
          min: 1
          max: 30
        mapping:
          - scale: 1
            step: 1
  - entity: number
    category: config
    name: Reclosing Recover Time
    dps:
      - id: 107
        type: integer
        name: value
        unit: s
        range:
          min: 1
          max: 99
        mapping:
          - scale: 1
            step: 1
  - entity: button
    name: Energy reset
    category: config
    class: restart
    dps:
      - id: 12
        type: boolean
        name: button
  - entity: sensor
    name: Balance energy
    category: diagnostic
    class: energy_storage
    icon: "mdi:home-lightning-bolt"
    dps:
      - id: 13
        type: integer
        name: sensor
        unit: kWh
        mapping:
          - scale: 100
  - entity: sensor
    class: voltage
    category: diagnostic
    dps:
      - id: 6
        type: base64
        name: sensor
        optional: true
        unit: V
        mask: "FFFF000000000000"
        mapping:
          - scale: 10
  - entity: sensor
    class: current
    category: diagnostic
    dps:
      - id: 6
        type: base64
        name: sensor
        optional: true
        unit: A
        mask: "0000FFFFFF000000"
        mapping:
          - scale: 1000
  - entity: sensor
    class: power
    category: diagnostic
    dps:
      - id: 6
        type: base64
        name: sensor
        optional: true
        unit: kW
        mask: "0000000000FFFFFF"
        mapping:
          - scale: 1000
  - entity: sensor
    class: temperature
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: C
        class: measurement
  - entity: sensor
    name: Leakage current
    class: current
    category: diagnostic
    dps:
      - id: 15
        type: integer
        name: sensor
        unit: mA
        class: measurement
        optional: true
  - entity: number
    name: Charge energy
    category: config
    class: energy_storage
    icon: "mdi:cash"
    dps:
      - id: 14
        type: integer
        name: value
        unit: kWh
        optional: true
        range:
          min: 0
          max: 999999
        mapping:
          - scale: 100

```

This is what i made and it worked
please try to include alarm Controls they are in dps 17 (Alarm set1 | BAEAFAUBADI=) there is Leakage Threshold and switch and also High Temperature threshold and switch
and dps 18 have (Alarm set2 | AQAB9AMBAQQEAQBQ) Over Current, Over/Under Voltage Threshold and Switch for all three 

I have another one device but it just not bidirectional 
so it will just dont have dps 110
- entity: sensor
    class: energy
    name: Total Reverse Energy 
    dps:
      - id: 110
        type: integer
        name: sensor
        class: total_increasing
        unit: kWh
        mapping:
          - scale: 100
else everything is same
Device id is d72c50d5b3839b6a39swa8
