### ISSUE TITLE
Request support for CCST6001 thermostat

### ISSUE THREAD

**Issue by shyfxshadow** [make-all/tuya-local#2914]
### Log message

```text
2025-01-27 20:27:16.258 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding ZK0153智炫空调温控器 device with product id 9z20prc4jq1jb4im
2025-01-27 20:27:16.263 WARNING (MainThread) [custom_components.tuya_local.config_flow] Unable to fetch data model from cloud: 'str' object has no attribute 'keys'
2025-01-27 20:27:16.264 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches CCST6001_test_v2 with quality of 44%. DPS: {"updated_at": 1738006014.8269098, "1": true, "2": "HEAT", "3": "stop", "16": 220, "24": 220, "28": "high", "45": 0, "101": "manual", "102": "cool_heat"}
2025-01-27 20:27:16.264 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
```

### Product ID

9z20prc4jq1jb4im

### Product Name

CCST6001

### DPS information

```text
{
   "result": {
     "model": "{\"modelId\":\"ff7oc4\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power3\",\"attribute\":\"1\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"制冷，制热，送风\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"COOL\",\"HEAT\",\"FAN\"]}},
{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"制冷中，制热中，送风中，停止\",\"extensions\":{\"attribute\":\"128\"},\"name\":\"工作状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cooling\",\"heating\",\"blowing\",\"stop\"]}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\"},\"name\":\"设置温度\",\"typeSpec\":{\"type\":\"value\",\"max\":350,\"min\":50,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu\"},\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":-1000,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},
{\"abilityId\":28,\"accessMode\":\"rw\",\"code\":\"level\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_direction\"},\"name\":\"档位\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"low\",\"middle\",\"high\",\"auto\"]}},
{\"abilityId\":45,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"内置传感器故障，外置传感器故障\",\"extensions\":{\"iconName\":\"icon-dp_notice\",\"scope\":\"fault\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"e1\",\"e2\"],\"maxlen\":2}},
{\"abilityId\":48,\"accessMode\":\"rw\",\"code\":\"week_program4\",\"description\":\"每段定时可以设置第1，2字节时间，第3,4字节温度；6段定时；默认时间06:00 20°C ；08:00 15°C；11:30 15°C；13:30 15°C；17:00 22°C；22:00 15°C；每段占4个字节，如果温度带小数数据要扩大10倍传，如果不带小数正常传，06:00 35.0 则传06 00 01 5e；6*4*3=72字节\",\"name\":\"周程序（5+1+1）\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"manual_programmable_ECO\",\"description\":\"手动模式，编程模式，ECO\",\"name\":\"手动/周编程/ECO模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"manual\",\"programmable\",\"jieneng\"]}},
{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"sys_type\",\"description\":\"单冷，冷暖\",\"name\":\"机型选择\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cool\",\"cool_heat\"]}}]}]}"
   },
   "success": true,
   "t": 1738004******,
   "tid": "46a74911dce011efa*********"
 }
```

### Information about how the device functions

I could write a config file up to the yaml code below, however, as soon as I try to outcomment the other ids, i get a parse error

```
name: CCST6001
entities:
  - entity: climate
    dps:
      - id: 1
        name: hvac_mode
        type: boolean
        mapping:
          - dps_val: true
            value: "heat"
          - dps_val: false
            value: "off"
      # - id: 2
      #   name: mode
      #   type: enum
      #   mapping:
      #     - dps_val: "HEAT"
      #       value: "heat"
      #     - dps_val: "COOL"
      #       value: "cool"
      #     - dps_val: "FAN"
      #       value: "fan"
      # - id: 3
      #   name: work_state
      #   type: enum
      #   mapping:
      #     - dps_val: "cooling"
      #       value: "cooling"
      #     - dps_val: "heating"
      #       value: "heating"
      #     - dps_val: "blowing"
      #       value: "blowing"
      #     - dps_val: "stop"
      #       value: "stop"
      - id: 16
        name: target_temperature
        type: integer
        unit: C
        range:
          min: 50
          max: 350
      - id: 24
        name: current_temperature
        type: integer
        unit: C
        range:
          min: -1000
          max: 1000
      # - id: 28
      #   name: level
      #   type: enum
      #   mapping:
      #     - dps_val: "low"
      #       value: "low"
      #     - dps_val: "middle"
      #       value: "medium"
      #     - dps_val: "high"
      #       value: "high"
      #     - dps_val: "auto"
      #       value: "auto"
      - id: 45
        name: fault_status
        type: integer
        mapping:
          - dps_val: 0
            value: "no_fault"
          - dps_val: 1
            value: "fault_detected"
      # - id: 48
      #   name: weekly_schedule
      #   type: raw
      # - id: 101
      #   name: control_mode
      #   type: enum
      #   mapping:
      #     - dps_val: "manual"
      #       value: "manual"
      #     - dps_val: "programmable"
      #       value: "program"
      #     - dps_val: "jieneng"
      #       value: "eco"
      # - id: 102
      #   name: sys_type
      #   type: enum
      #   mapping:
      #     - dps_val: "cool_heat"
      #       value: "dual"
      #     - dps_val: "cool"
      #       value: "cool_only"

```

Parse error:

file "/usr/local/lib/python3.13/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
            "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "/config/custom_components/tuya_local/devices/CCST6001_test.yaml", line 46, column 9
expected <block end>, but found '-'
  in "/config/custom_components/tuya_local/devices/CCST6001_test.yaml", line 56, column 9

But the yaml file seems to be valid.

Any help is highly appreciated. Many thanks :-)
