### ISSUE TITLE
Device stopped working on January update

### ISSUE THREAD

**Issue by kap-Gun** [make-all/tuya-local#2922]
### Description

I have an ATORCH Smart Energy Meter (GR2PW).
It was working fine until January update.
Tuya plugs are still working, only this device has stopped.

### Steps to reproduce

I used the add new device via the smartlife app.
Upon choosing the device in the drop down, I get a new screen asking for the IP address to be inserted manually.
Doing so will bring up a new window on the type of device.
The device type is not present.

![Image](https://github.com/user-attachments/assets/7b4973e0-e46b-430d-916e-bcf25bf563a4)

![Image](https://github.com/user-attachments/assets/2beb4ba7-9d97-463e-b8b4-3dbe11a895b7)

### Expected behaviour

The device to continue working as before the update or the ability to recognise device type to be added after a reset.

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.

**Comment by make-all** [comment]
It is likely that your device is a "device22" device, and needs to use the newly added "3.22" protocol version instead of "3.3". Other users have also seen this problem when "3.4" devices are misdetected as "3.3".

**Comment by kap-Gun** [comment]
Choosing '3.22' protocol, or any '3.2' , '3.3' or even auto gives the same result.

**Comment by rhys-e2** [comment]
I've experienced the same behaviour when testing a new device config in my local environment. I get presented with the same 4 options as above when trying to add a new device.

Here is the device from the tinytuya scan:
```
{
        "name": "test light",
        "id": "",
        "key": "",
        "mac": "",
        "uuid": "",
        "category": "dj",
        "product_name": "",
        "product_id": "2un1bvpd3fqwq1w6",
        "biz_type": 0,
        "model": "GLD312HA Twinsel (2)",
        "sub": false,
        "icon": "https://images.tuyaeu.com/smart/icon/ay1536534747810ekKBj/08d8603d4cf59885e04e9825055e026c.png",
        "mapping": {
            "20": {
                "code": "switch_led",
                "type": "Boolean",
                "values": {}
            },
            "21": {
                "code": "work_mode",
                "type": "Enum",
                "values": {
                    "range": [
                        "white",
                        "colour",
                        "scene",
                        "music"
                    ]
                }
            },
            "22": {
                "code": "bright_value_v2",
                "type": "Integer",
                "values": {
                    "min": 10,
                    "max": 1000,
                    "scale": 0,
                    "step": 1
                }
            },
            "23": {
                "code": "temp_value_v2",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 1000,
                    "scale": 0,
                    "step": 1
                }
            },
            "25": {
                "code": "scene_data_v2",
                "type": "Json",
                "raw_values": "{\"scene_num\":{\"min\":1,\"scale\":0,\"max\":8,\"step\":1},\"scene_units\": {\"unit_change_mode\":{\"range\":[\"static\",\"jump\",\"gradient\"]},\"unit_switch_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"unit_gradient_duration\":{\"min\":0,\"scale\":0,\"max\":100,\"step\":1},\"bright\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"temperature\":{\"min\":0,\"scale\":0,\"max\":1000,\"step\":1},\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}}",
                "values": {
                    "scene_num": {
                        "min": 1,
                        "scale": 0,
                        "max": 8,
                        "step": 1
                    },
                    "scene_units": {
                        "unit_change_mode": {
                            "range": [
                                "static",
                                "jump",
                                "gradient"
                            ]
                        },
                        "unit_switch_duration": {
                            "min": 0,
                            "scale": 0,
                            "max": 100,
                            "step": 1
                        },
                        "unit_gradient_duration": {
                            "min": 0,
                            "scale": 0,
                            "max": 100,
                            "step": 1
                        },
                        "bright": {
                            "min": 0,
                            "scale": 0,
                            "max": 1000,
                            "step": 1
                        },
                        "temperature": {
                            "min": 0,
                            "scale": 0,
                            "max": 1000,
                            "step": 1
                        },
                        "h": {
                            "min": 0,
                            "scale": 0,
                            "unit": "",
                            "max": 360,
                            "step": 1
                        },
                        "s": {
                            "min": 0,
                            "scale": 0,
                            "unit": "",
                            "max": 1000,
                            "step": 1
                        },
                        "v": {
                            "min": 0,
                            "scale": 0,
                            "unit": "",
                            "max": 1000,
                            "step": 1
                        }
                    }
                }
            },
            "26": {
                "code": "countdown_1",
                "type": "Integer",
                "values": {
                    "min": 0,
                    "max": 86400,
                    "scale": 0,
                    "step": 1
                }
            },
            "28": {
                "code": "control_data",
                "type": "Json",
                "raw_values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}",
                "values": {
                    "change_mode": {
                        "range": [
                            "direct",
                            "gradient"
                        ]
                    },
                    "bright": {
                        "min": 0,
                        "scale": 0,
                        "unit": "",
                        "max": 1000,
                        "step": 1
                    },
                    "temperature": {
                        "min": 0,
                        "scale": 0,
                        "unit": "",
                        "max": 1000,
                        "step": 1
                    },
                    "h": {
                        "min": 0,
                        "scale": 0,
                        "unit": "",
                        "max": 360,
                        "step": 1
                    },
                    "s": {
                        "min": 0,
                        "scale": 0,
                        "unit": "",
                        "max": 255,
                        "step": 1
                    },
                    "v": {
                        "min": 0,
                        "scale": 0,
                        "unit": "",
                        "max": 255,
                        "step": 1
                    }
                }
            },
            "30": {
                "code": "rhythm_mode",
                "type": "Raw",
                "values": {
                    "maxlen": "255"
                }
            },
            "31": {
                "code": "sleep_mode",
                "type": "Raw",
                "values": {
                    "maxlen": "255"
                }
            },
            "32": {
                "code": "wakeup_mode",
                "type": "Raw",
                "values": {
                    "maxlen": "255"
                }
            },
            "33": {
                "code": "power_memory",
                "type": "Raw",
                "values": {}
            },
            "34": {
                "code": "do_not_disturb",
                "type": "Boolean",
                "values": {}
            },
            "209": {
                "code": "cycle_timing",
                "type": "Raw",
                "values": {}
            },
            "210": {
                "code": "random_timing",
                "type": "Raw",
                "values": {}
            }
        },
        "ip": "192.168.1.92",
        "version": "3.3"
    },
```

This is the config I have created:

```
name: Arlec LED Light
products:
  - id: 2un1bvpd3fqwq1w6
    manufacturer: Arlec
    model: GLD312HA Twinsel (2)
    model_id: GLD312HA
entities:
  - entity: light
    dps:
      - id: 20
        type: boolean
        name: switch
      - id: 21
        type: string
        name: color_mode
        mapping:
          - dps_val: white
            value: white
          - dps_val: colour
            value: hs
          - dps_val: scene
            value: Scene
          - dps_val: music
            value: Music
      - id: 22
        type: integer
        name: brightness
        range:
          min: 10
          max: 1000
      - id: 23
        type: integer
        name: color_temp
        range:
          min: 0
          max: 1000
      - id: 25
        type: json
        name: scene_data
      - id: 28
        type: json
        name: control_data
  - entity: number
    name: timer
    class: duration
    category: config
    dps:
      - id: 26
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
          - step: 60
  - entity: switch
    name: do_not_disturb
    category: config
    dps:
      - id: 34
        type: boolean
        name: switch
  - entity: select
    name: rhythm_mode
    category: config
    dps:
      - id: 30
        type: string
        name: option
  - entity: select
    name: sleep_mode
    category: config
    dps:
      - id: 31
        type: string
        name: option
  - entity: select
    name: wakeup_mode
    category: config
    dps:
      - id: 32
        type: string
        name: option
  - entity: switch
    name: power_memory
    category: config
    dps:
      - id: 33
        type: boolean
        name: switch
  - entity: select
    name: cycle_timing
    category: config
    dps:
      - id: 209
        type: string
        name: option
  - entity: select
    name: random_timing
    category: config
    dps:
      - id: 210
        type: string
        name: option
```
