### ISSUE TITLE
Wilfa Haze HU400BC Fan Speed Mapping Incorrect

### ISSUE THREAD

**Issue by Balneo** [make-all/tuya-local#2953]
### Description

The current dps mapping for fan speed in tuya-local does not correctly reflect the five speed levels of the Wilfa Haze HU400BC humidifier. Setting the speed to 100% in Home Assistant only triggers level_4, while level_5 (the actual max speed) is missing.

Current Behavior:

- level_0 is set to 20%.
- level_4 is set to 100%, making it impossible to select level_5.

I have checked it and it seems to work locally for me. I have double checked with the SmartLife App to see that it shows level 5 on the fan speed after the update with shifting the fan speed so level_0 is 0 and adding the level_5 to 100.

### Steps to reproduce

Steps to Reproduce:

- Set the fan speed to 100% in Home Assistant.
- Observe that level_4 is activated instead of level_5.

### Expected behaviour

Expected Behavior:

- level_0 should be 0%.
- level_1 should be 20%.
- level_2 should be 40%.
- level_3 should be 60%.
- level_4 should be 80%.
- level_5 should be 100%.

### Additional context

Proposed Fix:

Update the mapping in the device configuration to:

File: wilfa_haze_hu400bc_humidifier.yaml row 44 and more.

```
- entity: fan
  dps:
    - id: 1
      name: switch
      type: boolean
    - id: 23
      type: string
      name: speed
      mapping:
        - dps_val: level_0
          value: 0
        - dps_val: level_1
          value: 20
        - dps_val: level_2
          value: 40
        - dps_val: level_3
          value: 60
        - dps_val: level_4
          value: 80
        - dps_val: level_5
          value: 100
```

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.
