### ISSUE TITLE
Request support for Avatto WT200 thermostat

### ISSUE THREAD

**Issue by JabeBRD** [make-all/tuya-local#2989]
### Log message

```text
2025-02-17 22:31:06.247 WARNING (MainThread) [custom_components.tuya_local.device] Thermostat receive loop has terminated
2025-02-17 22:31:40.804 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding Temp-3 device with product id m3j5wouhgsvjlma9
2025-02-17 22:31:41.006 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device specification:
[{"id": 1, "name": "switch", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 2, "name": "temp_set", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":50,\"max\":950,\"scale\":1,\"step\":5}", "enumMap": {}}, {"id": 3, "name": "temp_current", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":999,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 4, "name": "mode", "type": "Enum", "format": "{\"range\":[\"auto\"]}", "enumMap": {}}, {"id": 9, "name": "child_lock", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 11, "name": "fault", "type": "Bitmap", "format": "{\"label\":[\"fault\"]}", "enumMap": {}}, {"id": 15, "name": "upper_temp", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":15,\"max\":95,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 19, "name": "temp_correction", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":-99,\"max\":99,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 103, "name": "frost", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 109, "name": "sound", "type": "Boolean", "format": "{}", "enumMap": {}}]
2025-02-17 22:31:41.006 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches avatto_wt200_thermostat with quality of 101%. DPS: {"updated_at": 1739824299.1431942, "1": true, "2": 150, "3": 140, "4": "home", "5": "1", "9": false, "11": 0, "15": 40, "19": -20, "101": 20, "102": 60, "103": true, "104": false, "106": "3", "107": "3", "108": false, "109": false, "110": "1"}
2025-02-17 22:31:41.006 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
```

### Product ID

m3j5wouhgsvjlma9

### Product Name

Avatto WT200-16A-W

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"eo0r20\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
*	{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1157\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
*   {\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-set\",\"attribute\":\"1152\"},\"name\":\"目标温度\",\"typeSpec\":{\"type\":\"value\",\"max\":950,\"min\":50,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},
*	{\"abilityId\":3,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1152\"},\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":999,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
*	{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"home\",\"auto\",\"temporary\",\"leave\"]}},
*	{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"work_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"工作状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\"]}},
*   {\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1152\"},\"name\":\"童锁\",\"typeSpec\":{\"type\":\"bool\"}},
*	{\"abilityId\":11,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"scope\":\"fault\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"fault\"],\"maxlen\":1}},
*	{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"upper_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"attribute\":\"1152\"},\"name\":\"设置温度上限\",\"typeSpec\":{\"type\":\"value\",\"max\":95,\"min\":15,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},
*	{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"temp_correction\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1152\"},\"name\":\"温度校准\",\"typeSpec\":{\"type\":\"value\",\"max\":99,\"min\":-99,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
*	{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"qidongwencha\",\"description\":\"\",\"name\":\"输出启动温差\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":5,\"scale\":1,\"step\":5,\"unit\":\"\"}},
*	{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"xianwen\",\"description\":\"\",\"name\":\"传感器限温值\",\"typeSpec\":{\"type\":\"value\",\"max\":60,\"min\":35,\"scale\":0,\"step\":1,\"unit\":\"\"}},
*	{\"abilityId\":103,\"accessMode\":\"rw\",\"code\":\"frost\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"4096\"},\"name\":\"防霜冻功能\",\"typeSpec\":{\"type\":\"bool\"}},
*	{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"reset\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"4096\"},\"name\":\"恢复出厂设置\",\"typeSpec\":{\"type\":\"bool\"}},
	{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"week_program3\",\"description\":\"\",\"name\":\"周程序（工作日）\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},
*	{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"backlight\",\"description\":\"\",\"name\":\"背光亮度\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\",\"3\"]}},
*	{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"work_days\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"4096\"},\"name\":\"工作日设置\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"0\",\"1\",\"2\",\"3\"]}},
*	{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"zhufan\",\"description\":\"\",\"name\":\"输出主反\",\"typeSpec\":{\"type\":\"bool\"}},
*	{\"abilityId\":109,\"accessMode\":\"rw\",\"code\":\"sound\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-sound\",\"attribute\":\"4096\"},\"name\":\"声音\",\"typeSpec\":{\"type\":\"bool\"}},
*	{\"abilityId\":110,\"accessMode\":\"rw\",\"code\":\"sensor_choose\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"4096\"},\"name\":\"传感器选择\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"1\",\"2\",\"3\"]}}]}]}"
  },
  "success": true,
  "t": 1739736499015,
  "tid": "c3bea2c1eca111efa76bb217c6c149bc"
```

### Information about how the device functions

I have added Avatto WT200 thermostat for my devices.
Here is yaml file, I have basicly copied another device that has same functions, just adjusted values so that it matches information from Tuya Api Explorer.
```
name: Thermostat
products:
  - id: m3j5wouhgsvjlma9
    manufacturer: Avatto
    model: WT200-16A-W
entities:
  - entity: climate
    translation_only_key: thermostat
    dps:
      - id: 1
        name: hvac_mode
        type: boolean
        mapping:
          - dps_val: true
            constraint: preset_mode
            conditions:
              - dps_val: auto
                value: auto
              - dps_val: temporary
                value: auto
#                hidden: true
              - dps_val: home
                value: heat
              - dps_val: leave
                value: heat
#                hidden: true
          - dps_val: false
            value: "off"
      - id: 2
        name: temperature
        type: integer
        unit: C
        range:
          min: 50
          max: 950
        mapping:
          - scale: 10
            step: 5
      - id: 3
        type: integer
        name: current_temperature
        mapping:
          - scale: 10
      - id: 4
        type: string
        name: preset_mode
        mapping:
          - dps_val: leave
            value: away
          - dps_val: home
            value: manual
          - dps_val: auto
            value: program
          - dps_val: temporary
            value: temp_override
      - id: 5
        type: string
        name: hvac_action
        mapping:
          - dps_val: "0"
            value: idle
          - dps_val: "1"
            value: heating
      - id: 15
        name: max_temperature
        type: integer
  - entity: lock
    translation_key: child_lock
    category: config
    dps:
      - id: 9
        type: boolean
        name: lock
  - entity: binary_sensor
    category: diagnostic
    class: problem
    dps:
      - id: 11
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
      - id: 11
        name: fault_code
        type: bitfield
  - entity: number
    name: Temperature hysteresis
    category: config
    icon: "mdi:thermometer-plus"
    dps:
      - id: 101
        type: integer
        name: value
        unit: °C
        range:
          min: 5
          max: 95
        mapping:
          - scale: 10
            step: 5
  - entity: number
    name: Maximum temperature
    category: config
    class: temperature
    icon: "mdi:thermometer-chevron-up"
    dps:
      - id: 15
        type: integer
        name: value
        unit: °C
        range:
          min: 15
          max: 95
  - entity: number
    name: Calibration offset
    category: config
    icon: "mdi:arrow-collapse-up"
    dps:
      - id: 19
        type: integer
        name: value
        unit: °C
        range:
          min: -99
          max: 99
        mapping:
          - scale: 10
  - entity: number
    name: External temperature limit
    category: config
    class: temperature
    icon: "mdi:arrow-collapse-up"
    dps:
      - id: 102
        type: integer
        name: value
        unit: °C
        range:
          min: 35
          max: 60
  - entity: switch
    translation_key: anti_frost
    category: config
    dps:
      - id: 103
        type: boolean
        name: switch
  - entity: button
    translation_key: factory_reset
    category: config
    dps:
      - id: 104
        name: button
        type: boolean
  - entity: light
    translation_key: backlight
    category: config
    dps:
      - id: 106
        type: string
        name: brightness
        mapping:
          - dps_val: "0"
            value: 0
          - dps_val: "1"
            value: 100
          - dps_val: "2"
            value: 180
          - dps_val: "3"
            value: 255
  - entity: select
    name: Schedule
    category: config
    icon: "mdi:calendar-clock"
    dps:
      - id: 107
        type: string
        name: option
        mapping:
          - dps_val: "0"
            value: "Off"
          - dps_val: "1"
            value: "Weekday+Weekend"
          - dps_val: "2"
            value: "Mon-Sat+Sun"
          - dps_val: "3"
            value: "Daily"
  - entity: switch
    name: Invert output
    category: config
    icon: "mdi:swap-horizontal"
    dps:
      - id: 108
        type: boolean
        name: switch
  - entity: select
    name: Sensor selection
    category: config
    icon: "mdi:home-thermometer"
    dps:
      - id: 110
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "1"
            value: Internal
          - dps_val: "2"
            value: External
          - dps_val: "3"
            value: Both
  - entity: switch
    name: Sound
    category: config
    icon: "mdi:music-note"
    dps:
      - id: 109
        type: boolean
        name: switch
```

It is missing `ID 105` `week_program3`
