### ISSUE TITLE
Bug with nested mapping in mrc_magnum_floorheater

### ISSUE THREAD

**Issue by MatsNl** [make-all/tuya-local#3008]
### Description

The Temperature hysteresis in the MRC Magnum floorheater does not work. I get an error saying ```
ERROR (MainThread) [custom_components.tuya_local.helpers.config] Error adding select_temperature_hysteresis for mrc_magnum_floorheater.yaml: select_temperature_hysteresis does not have a mapping to a list of options```

### Steps to reproduce

Add the MRC device as you would add any other device. Confirm the error in the log and observe the Temperature Hysteresis entity is 'unknown'

### Expected behaviour

The temperature hysteresis entity should load normally when the device is added/loaded.

### Additional context

I have resolved this locally by simply removing the nested mapping, but clearly that is not the desired solution as it basically hardcodes the option to False: 
```
  - entity: select
    name: Temperature hysteresis
    icon: "mdi:arrow-collapse-horizontal"
    category: config
    dps:
      - id: 114
        type: string
        name: option
        # mapping:
        #   - constraint: unit
        #     conditions:
        #       - dps_val: false
        mapping:
          - dps_val: "0_5"
            value: "0.5"
          - dps_val: "1"
            value: "1.0"
          - dps_val: "2"
            value: "1.5"
          - dps_val: "3"
            value: "2.0"
              # - dps_val: true
              #   mapping:
              #     - dps_val: "0_5"
              #       value: "1.0"
              #     - dps_val: "1"
              #       value: "2.0"
              #     - dps_val: "2"
              #       value: "3.0"
              #     - dps_val: "3"
              #       value: "4.0"
```

I'm not sure how this should be implemented, happy to make a PR if someone can explain the correct syntax.

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [x] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.
