### ISSUE TITLE
Request support for Luminance Motion sensor

### ISSUE THREAD

**Issue by kymap010** [make-all/tuya-local#3019]
### Log message

```text
2025-02-28 12:09:14.007 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches luminance_motion_sensor with quality of 83%. DPS: {"updated_at": 1740719347.9199598, "1": "none", "4": 100, "9": "high", "10": "60S", "12": 3179, "102": 60}
```

### Product ID

3towulqd

### Product Name

Luminance Motion sensor

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "pir_state",
        "custom_name": "",
        "dp_id": 1,
        "time": 1740717549009,
        "type": "enum",
        "value": "none"
      },
      {
        "code": "battery_percentage",
        "custom_name": "",
        "dp_id": 4,
        "time": 1740715884310,
        "type": "value",
        "value": 100
      },
      {
        "code": "pir_sensitivity",
        "custom_name": "",
        "dp_id": 9,
        "time": 1740715856813,
        "type": "enum",
        "value": "high"
      },
      {
        "code": "pir_time",
        "custom_name": "",
        "dp_id": 10,
        "time": 1740717433450,
        "type": "enum",
        "value": "60S"
      },
      {
        "code": "illuminance_value",
        "custom_name": "",
        "dp_id": 12,
        "time": 1740717549853,
        "type": "value",
        "value": 3179
      },
      {
        "code": "interval_time",
        "custom_name": "",
        "dp_id": 102,
        "time": 1740715856054,
        "type": "value",
        "value": 60
      }
    ]
  },
  "success": true,
  "t": 1740719047870,
  "tid": "7080629ef59111efbb1e5e27f1fe0fe0"
}
```

### Information about how the device functions

"product_id": "3towulqd",
"product_name": "Luminance Motion sensor",
"category": "pir",
"category_name": "Motion Detector",
"model": "ZG-204L",
"brand" : none

https://aliexpress.ru/item/1005004095233195.html?sku_id=12000028017055693

![Image](https://github.com/user-attachments/assets/6b2242bf-d79e-42f1-ac21-0b8d272457c5)

Works correctly after adding new yaml configuration file based on moes_motionsensor_light.yaml

```
name: Luminance Motion sensor
products:
  - id: 3towulqd
    manufacturer: none
    model: ZG-204L
entities:
  - entity: binary_sensor
    name: Motion detected
    class: motion
    dps:
      - id: 1
        type: string
        name: sensor
        mapping:
          - dps_val: none
            value: false
          - dps_val: pir
            value: true
  - entity: sensor
    name: Current luminance
    class: illuminance
    dps:
      - id: 12
        type: integer
        name: sensor
        unit: lx
        class: measurement
  - entity: sensor
    name: Battery Level
    class: battery
    dps:
      - id: 4
        type: integer
        name: sensor
        unit: "%"
  - entity: select
    name: Sensitivity
    icon: "mdi:human-greeting-proximity"
    category: config
    dps:
      - id: 9
        name: option
        type: string
        mapping:
          - dps_val: "low"
            value: "Low"
          - dps_val: "middle"
            value: "Medium"
          - dps_val: "high"
            value: "High"
  - entity: select
    name: Keep time
    icon: "mdi:camera-timer"
    category: config
    dps:
      - id: 10
        name: option
        type: string
        mapping:
          - dps_val: "10S"
            value: "10"
          - dps_val: "30S"
            value: "30"
          - dps_val: "60S"
            value: "60"
          - dps_val: "120S"
            value: "120"
```
