### ISSUE TITLE
Request support for Timberk T-EK21S104WF

### ISSUE THREAD

**Issue by kymap010** [make-all/tuya-local#3039]
### Log message

```text
2025-03-07 22:24:20.077 DEBUG (MainThread) [custom_components.tuya_local.device] tuya_local_timberk received {"1": false, "2": 47, "4": 100, "7": 0, "8": "standby", "9": "heating_quick", "10": 0, "11": "diy", "12": 0, "13": 0, "14": false, "15": 40, "17": 0, "full_poll": true}
```

### Product ID

ouqouaxvzftvpybr

### Product Name

Timberk T-EK21S104WF

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "start",
        "custom_name": "",
        "dp_id": 1,
        "time": 1741343227428,
        "type": "bool",
        "value": false
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 2,
        "time": 1741343255832,
        "type": "value",
        "value": 62
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 4,
        "time": 1741343215336,
        "type": "value",
        "value": 100
      },
      {
        "code": "warm_time",
        "custom_name": "",
        "dp_id": 7,
        "time": 1741343227519,
        "type": "value",
        "value": 0
      },
      {
        "code": "status",
        "custom_name": "",
        "dp_id": 8,
        "time": 1741343227610,
        "type": "enum",
        "value": "standby"
      },
      {
        "code": "work_type",
        "custom_name": "",
        "dp_id": 9,
        "time": 1741343227692,
        "type": "enum",
        "value": "heating_quick"
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 10,
        "time": 1741337846342,
        "type": "bitmap",
        "value": 0
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 11,
        "time": 1741343227785,
        "type": "enum",
        "value": "diy"
      },
      {
        "code": "countdown",
        "custom_name": "",
        "dp_id": 12,
        "time": 1741337845980,
        "type": "value",
        "value": 0
      },
      {
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 13,
        "time": 1741337845894,
        "type": "value",
        "value": 0
      },
      {
        "code": "warm",
        "custom_name": "",
        "dp_id": 14,
        "time": 1741343215440,
        "type": "bool",
        "value": false
      },
      {
        "code": "temp_set_1",
        "custom_name": "",
        "dp_id": 15,
        "time": 1741343215633,
        "type": "value",
        "value": 90
      },
      {
        "code": "warm_left",
        "custom_name": "",
        "dp_id": 17,
        "time": 1741343227872,
        "type": "value",
        "value": 0
      }
    ]
  },
  "success": true,
  "t": 1741343271143,
  "tid": "d292ffd9fb3e11efbdf7c612b69bb704"
}


{
  "result": {
    "category": "bh",
    "functions": [
      {
        "code": "start",
        "desc": "{}",
        "name": "启动",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_set",
        "desc": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}",
        "name": "温度设置-℃",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "warm_time",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}",
        "name": "保温时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_type",
        "desc": "{\"range\":[\"boiling_quick\"]}",
        "name": "工作类型",
        "type": "Enum",
        "values": "{\"range\":[\"boiling_quick\"]}"
      },
      {
        "code": "countdown",
        "desc": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}",
        "name": "倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}"
      },
      {
        "code": "warm",
        "desc": "{}",
        "name": "保温",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "start",
        "name": "启动",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "temp_current",
        "name": "当前温度-℃",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp_set",
        "name": "温度设置-℃",
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "warm_time",
        "name": "保温时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}"
      },
      {
        "code": "status",
        "name": "设备状态",
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"heating\",\"cooling\",\"warm\"]}"
      },
      {
        "code": "work_type",
        "name": "工作类型",
        "type": "Enum",
        "values": "{\"range\":[\"boiling_quick\"]}"
      },
      {
        "code": "countdown",
        "name": "倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_left",
        "name": "倒计时剩余时间",
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":720,\"scale\":0,\"step\":1}"
      },
      {
        "code": "warm",
        "name": "保温",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1741361716557,
  "tid": "c4d12870fb6911efbdf7c612b69bb704"
}
```

### Information about how the device functions

This yaml configuration work correctly
```
name: Timberk
products:
  - id: ouqouaxvzftvpybr
    manufacturer: Timberk
    model: T-EK21S104WF
entities:
  - entity: water_heater
    icon: "mdi:kettle-steam"
    dps:
      - id: 1
        type: boolean
        name: operation_mode
        mapping:
          - dps_val: false
            value: "Off"
            icon: "mdi:kettle-off-outline"
          - dps_val: true
            constraint: work_type
            conditions:
               - dps_val: black_tea
                 value: "Black tea"
                 icon: "mdi:tea"
               - dps_val: dechlorination
                 value: "Dechlorination"
                 icon: "mdi:kettle-steam"
               - dps_val: coffee
                 value: "Coffee"
                 icon: "mdi:coffee"
               - dps_val: green_tea
                 value: "Green tea"
                 icon: "mdi:tea"
               - dps_val: honey_water
                 value: "Honey water"
                 icon: "mdi:coffee"
               - dps_val: milk_powder
                 value: "Milk powder"
                 icon: "mdi:teddy-bear"                 
               - dps_val: boiled_water
                 value: "Boiled water"
                 icon: "mdi:kettle-steam"                 
               - dps_val: diy
                 value: "Default mode"
                 icon: "mdi:kettle-steam"                 
      - id: 11
        type: string
        name: work_type
        hidden: true
      - id: 2
        type: integer
        name: current_temperature
        unit: C
      - id: 4
        type: integer
        name: temperature
        unit: C        
        range:
          min: 0
          max: 100
        mapping:
          - step: 1
  - entity: switch
    name: "Start"
    icon: "mdi:kettle-outline"
    dps:
      - id: 1
        type: boolean
        name: switch
  - entity: switch
    name: "Warm"
    icon: "mdi:heat-wave"
    dps:
      - id: 14
        type: boolean
        name: switch        
  - entity: number
    name: "Warm time"
    category: config
    class: duration
    icon: "mdi:timer"
    dps:
      - id: 7
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 720
        mapping:
          - step: 1
  - entity: sensor
    icon: "mdi:thermometer"
    name: "Current temperature"
    category: diagnostic
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: C          
  - entity: sensor
    name: "Status"  
    translation_key: status
    class: enum
    icon: "mdi:kettle"
    category: diagnostic
    dps:
      - id: 8
        type: string
        name: sensor
        mapping:
          - dps_val: standby
            value: standby
          - dps_val: heating
            value: heating
          - dps_val: cooling
            value: cooling
          - dps_val: warm
            value: keeping_warm          
  - entity: sensor
    name: "Mode"  
    class: enum
    icon: "mdi:kettle"
    category: diagnostic
    dps:
      - id: 11
        type: string
        name: sensor
        mapping:
		  - dps_val: black_tea
			value: "Black tea"
			icon: "mdi:tea"
		  - dps_val: dechlorination
			value: "Dechlorination"
			icon: "mdi:kettle-steam"
		  - dps_val: coffee
			value: "Coffee"
			icon: "mdi:coffee"
		  - dps_val: green_tea
			value: "Green tea"
			icon: "mdi:tea"
		  - dps_val: honey_water
			value: "Honey water"
			icon: "mdi:coffee"
		  - dps_val: milk_powder
			value: "Milk powder"
			icon: "mdi:teddy-bear"                 
		  - dps_val: boiled_water
			value: "Boiled water"
			icon: "mdi:kettle-steam"                 
		  - dps_val: diy
			value: "Default mode"
			icon: "mdi:kettle-steam"           
            
```
