### ISSUE TITLE
Turning on Sky Lite Evolve cloud light toggles the light

### ISSUE THREAD

**Issue by NewsGuyTor** [make-all/tuya-local#3086]
### Description

The Sky Lite Evolve device has two lights, a cloud light entity and a laser light entity. The integration has an issue where the cloud light toggles despite that not being requested. That makes scenes not work properly, when you activate a scene when the cloud light is on it turns off and when it is off it turns on, despite "on" being requested every time.

Take this simple scene, it's just the cloud light and laser light entities. When you apply this scene the laser stays on like it should, but the cloud light (light.stjernelys) toggles on and off, depending on its state before. 

```
id: "1742867770060"
name: Chill starlight preset
entities:
  light.stjernelys:
    effect_list:
      - "off"
    supported_color_modes:
      - hs
      - white
    effect: "off"
    color_mode: hs
    brightness: 255
    hs_color:
      - 0
      - 100
    rgb_color:
      - 255
      - 0
      - 0
    xy_color:
      - 0.701
      - 0.299
    friendly_name: Stjernelys
    supported_features: 4
    state: "on"
  light.stjernelys_laser:
    effect_list:
      - Scene
      - Manual
      - Music
    supported_color_modes:
      - brightness
    effect: laser
    color_mode: brightness
    brightness: 180
    friendly_name: Stjernelys Laser
    supported_features: 4
    state: "on"
metadata:
  light.stjernelys:
    entity_only: true
  light.stjernelys_laser:
    entity_only: true

```

### Steps to reproduce

1. Add Sky Lite Evolve to TuyaLocal
2. Save a scene
3. Activate that scene two (or more) times

### Expected behaviour

The scene shouldn't change the cloud light between each activation of the scene, on should be on regardless of its state before.

### Additional context

Here's me triggering the scene mentioned above twice. First trigger (with the cloud light off) at around 03:20:02, second around 03:20:10 I think.

[home-assistant_2025-03-25T02-20-20.792Z.log](https://github.com/user-attachments/files/19440764/home-assistant_2025-03-25T02-20-20.792Z.log)

[config_entry-tuya_local-01JPZ8A6GZJDJFPM2K0Q8J0W78.json](https://github.com/user-attachments/files/19441189/config_entry-tuya_local-01JPZ8A6GZJDJFPM2K0Q8J0W78.json)

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [x] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.
