### ISSUE TITLE
New device request 'Fairy lights'

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#309]
The device: [https://aliexpress.ru/item/1005001662351478.html?sku_id=12000017036117115](https://aliexpress.ru/item/1005001662351478.html?sku_id=12000017036117115)

The internal name: 双模幻彩铜线灯串控制器 10米 100*IC 通用 24*KEY
(google-translated: Dual-mode magic color copper wire light string controller 10 meters 100*IC universal 24*KEY)

The log output for discovery:
`Device matches None with quality of 0%. DPS: {'20': True, '21': 'scene', '24': '0000000003e8', '25': '010192', '26': 0, '101': '26401bb1006e03e801f4', 'updated_at': 1670787682.4822989}`

I've drafted the yaml.
But I don't know how to combine multiple values into one value sent. 
```
name: Fairy lights
primary_entity:
  entity: light
  dps:
    # on/off
    - id: 20
      type: boolean
      name: switch

    # mode (supported values: Scene, Music, Color)
    - id: 21
      type: string
      name: color_mode
      mapping:
        - dps_val: colour
          value: rgbw      

    # 本地音乐模式 / local music mode
    # the value combines music mode, sensitivity, brightness and color
    # for ex., 46403e81006e03e801f4 - 100% brightness + 100% sensitivity 
    #          46403e8000ed036b01f4 - 100% brightness + blue color
    #          46403e8100ed036b01f4 - 100% brightness + autocolor
    #          42103e8100ed036b01f4 - less sensitivity
    - id: 101
      type: hex
      name: music_mode
      mapping:
        - dps_val: 16401bb1006e03e801f4
          value: Energy
        - dps_val: 26401bb1006e03e801f4
          value: Rhythm
        - dps_val: 36401bb1006e03e801f4
          value: Spectrum
        - dps_val: 46401bb1006e03e801f4
          value: Rolling

    # colorful
    # 0163026203e8 - red color + 100% brightness
    # 0163026201f3 - red color + 50% brightness
    # 00d6029803e8 - blue color + 100% brightness
    # 00d6029801f0 - blue color + 50% brightness
    - id: 24

    # scene
    # 0103e8 - Palm + 100% brightness
    # 0101f1 - Palm + 50% brightness
    # not sure how it works - the app contains multiple scenes: Palm, Christmas Tree, Fence, Rainbow, Photos, Fairy lights, Wreath
    # but I don't see the values at https://eu.iot.tuya.com/cloud/device/detail
    - id: 25
      type: hex
      name: effect
      mapping:
        - dps_val: 0103e8
          value: Palm

secondary_entities:
  - entity: number
    name: Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 26
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        unit: min
        mapping:
          - scale: 60
            step: 60
        optional: true
```

**Comment by make-all** [comment]
Basically you can't combine multiple values into one field except for hsv colour, which there is special handling for since it maps nicely into HA rgb handling.  This should work for your dp 24 - it looks like 4 hex digits each for h, s and v, with ranges 0-360, 0-1000 and 0-1000 respectively, which I think makes it identical to rgbcw_lightbulb, so you can copy from there.  The only solution for music_mode and effect for now is to select a few as preset effects. Lights only support one dp for "effect", so music_mode will either need to be split out into a separate select entity, or a more advanced way that might work if they are mutually exclusive would be to conditionally redirect from effect when color_mode is "Scene".

**Comment by make-all** [comment]
Your scene encoding should be 2 hex digits for the scene id, and 4 hex digits for the brightness.  Although the format is not complex, it is not easy to support splitting these back out again, and does not seem to be a common format that would be worth adding special handling for.  So I suggest identifying the mapping of scene names to the first two hex digits, then adding a couple of versions of each scene (100% and 50%).  The brightness should be the same for all (03e8 for 100%, 01f4 for 50%).

**Comment by and7ey** [comment]
Thanks! I don't see the list of effects available:
<img width="568" alt="Снимок экрана 2022-12-18 в 12 25 48" src="https://user-images.githubusercontent.com/900474/208298069-9a25a731-a51c-4694-8cb0-5e7407581411.png">
<img width="567" alt="Снимок экрана 2022-12-18 в 12 25 38" src="https://user-images.githubusercontent.com/900474/208298070-f36292fe-a3fd-4075-a6a9-3f63b06f79c3.png">
<img width="589" alt="Снимок экрана 2022-12-18 в 12 25 22" src="https://user-images.githubusercontent.com/900474/208298071-1262e2df-db12-4c11-857e-cd7eaaa329db.png">

**Comment by make-all** [comment]
That's strange, but you also have separate white brightness and color brightness controls in that screenshot, which is also unexpected.

**Comment by make-all** [comment]
Effects should appear between "White brightness" and "Attributes".
I'm also not expecting to see Music Mode under Attributes, so did you update to the config from git, or make manual changes to your own config?

**Comment by and7ey** [comment]
Initially I made modifications to my own yaml, but finally I've deleted all my own files and re-installed your addon.
In result I can not add this device(

Similar to another device I tried to add, there are just the following records in the log:

```
2022-12-23 19:22:50.840 DEBUG (SyncWorker_4) [custom_components.tuya_local.device] Retrying after exception 'dps'
2022-12-23 19:22:50.841 INFO (SyncWorker_4) [custom_components.tuya_local.device] Setting protocol version for Test to 2022-12-23 19:23:26.169 DEBUG (SyncWorker_4) [custom_components.tuya_local.device] Retrying after exception 'dps'
2022-12-23 19:23:26.170 INFO (SyncWorker_4) [custom_components.tuya_local.device] Setting protocol version for Test to 3.2.
```

`Configure your Tuya Local device` and the loading there is shown for ~10 minutes (!) and then shows `Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.`

**Comment by and7ey** [comment]
I tried to move effect to separate entity, but in result the entity is not created:

```
2023-01-04 22:32:21.099 ERROR (MainThread) [homeassistant.components.select] Error while setting up tuya_local platform for select
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tuya_local/select.py", line 10, in async_setup_entry
await async_tuya_setup_platform(
File "/config/custom_components/tuya_local/helpers/config.py", line 38, in async_tuya_setup_platform
data[ecfg.config_id] = entity_class(device, ecfg)
File "/config/custom_components/tuya_local/generic/select.py", line 26, in __init__
raise AttributeError(
AttributeError: <bound method TuyaEntityConfig.name of <custom_components.tuya_local.helpers.device_config.TuyaEntityConfig object at 0x7f59c46770>> does not have a mapping to a list of options
```

**Comment by and7ey** [comment]
Thanks. It works now.

Now the effects list contains values `colorloop` and `random` (suggest to remove them).

And please correct the typo:         

```
- dps_val: "0103e8"
   name: Palm
```

it should be `value`, not `name` (should be corrected for all values).

**Comment by and7ey** [comment]
I was suggesting to fully remove Scene and Music effects. They don't work. Moreover, it works better without them, don't know why (when Scene and Music effects are there, the color couldn't be changed; but it changed well without these effects added).

Here is the result yaml for dps 21:
```
    - id: 21
      name: color_mode
      type: string
      mapping:
        - dps_val: colour
          value: rgbw
```
