### ISSUE TITLE
Request support for SR208C (Solar collector pump relay with temperature sensors)

### ISSUE THREAD

**Issue by BeriBGood** [make-all/tuya-local#3102]
### Log messages

```text
Adding SR208C device with product id hyrswocbx6i1rveo

Device specification: [{"id": 1, "name": "switch", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 2, "name": "mode", "type": "Enum", "format": "{\"range\":[\"cold\",\"heating\",\"auto\"]}", "enumMap": {}}, {"id": 4, "name": "temp_set", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 6, "name": "temp_unit_convert", "type": "Enum", "format": "{\"range\":[\"c\",\"f\"]}", "enumMap": {}}, {"id": 8, "name": "instant_heating", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 14, "name": "countdown_left", "type": "Integer", "format": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 21, "name": "temp_top", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":4000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 22, "name": "temp_bottom", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":4000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 30, "name": "pump_state", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 32, "name": "ele_heating_state", "type": "Boolean", "format": "{}", "enumMap": {}}]

Device matches zigbee_smart_bulb with quality of 40%. DPS: {"updated_at": 1743313612.7234359, "1": false, "2": "heating", "4": 60, "6": "c", "8": false, "21": 1090, "22": 419, "26": 155, "30": false, "32": false}
###
```

### Product ID

 hyrswocbx6i1rveo

### Product Name

SR208C

### DPS information

```text
QueryThingsDataModel:

{
  "result": {
    "model": "{\"modelId\":\"000003kw5f\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"T3启用开关\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"1152\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cold\",\"heating\",\"auto\"]}},
{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-set\",\"attribute\":\"1664\"},\"name\":\"手动加热温度设置\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":6,\"accessMode\":\"rw\",\"code\":\"temp_unit_convert\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"温标切换\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"c\",\"f\"]}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"instant_heating\",\"description\":\"手动加热开关\",\"extensions\":{\"iconName\":\"icon-jiare1\",\"attribute\":\"1152\"},\"name\":\"手动加热开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":14,\"accessMode\":\"ro\",\"code\":\"countdown_left\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"1152\"},\"name\":\"倒计时剩余时间\",\"typeSpec\":{\"type\":\"value\",\"max\":1440,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"min\"}},
{\"abilityId\":15,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-baojing\",\"attribute\":\"1152\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"sys_high_fault\",\"sys_low_fault\",\"flow_fault\",\"power_fault\",\"cooling_fault\",\"heating_fault\",\"temp_dif_fault\",\"in_temp_fault\",\"eff_temp_fault\",\"coil_temp_fault\",\"ret_temp_fault\",\"news_fault\",\"amb_temp_fault\"],\"maxlen\":13}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"temp_top\",\"description\":\"上水箱温度\\n3888是短路\\n3999是开路\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"T3\",\"typeSpec\":{\"type\":\"value\",\"max\":4000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"temp_bottom\",\"description\":\"下水箱温度\\n3888是短路\\n3999是开路\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"T2\",\"typeSpec\":{\"type\":\"value\",\"max\":4000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":26,\"accessMode\":\"ro\",\"code\":\"around_temp\",\"description\":\"3888是短路\\n3999是开路\",\"extensions\":{\"iconName\":\"icon-wendu2\"},\"name\":\"T1温度\",\"typeSpec\":{\"type\":\"value\",\"max\":4000,\"min\":-300,\"scale\":1,\"step\":1,\"unit\":\"℃\"}},
{\"abilityId\":30,\"accessMode\":\"ro\",\"code\":\"pump_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"水泵状态\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":32,\"accessMode\":\"ro\",\"code\":\"ele_heating_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"1152\"},\"name\":\"电热状态\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"signal_strength\",\"description\":\"WiFi信号的强度值（绝对值）\",\"extensions\":{\"iconName\":\"icon-fengli\",\"attribute\":\"4096\"},\"name\":\"信号强度\",\"typeSpec\":{\"type\":\"value\",\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"scene_data_raw\",\"description\":\"控制器参数表。\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"4096\"},\"name\":\"控制器参数\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}}]}]}"
  },
  "success": true,
  "t": 1743279048783,
  "tid": "e7e861ae0cd911f0905d5e1a959ba61d"
}
```

<details>

```
Query properties

{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1743082326783,
        "type": "bool",
        "value": false
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1743081237080,
        "type": "enum",
        "value": "heating"
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 4,
        "time": 1743082509571,
        "type": "value",
        "value": 60
      },
      {
        "code": "temp_unit_convert",
        "custom_name": "",
        "dp_id": 6,
        "time": 1743081239029,
        "type": "enum",
        "value": "c"
      },
      {
        "code": "instant_heating",
        "custom_name": "",
        "dp_id": 8,
        "time": 1743082511310,
        "type": "bool",
        "value": false
      },
      {
        "code": "countdown_left",
        "custom_name": "",
        "dp_id": 14,
        "time": 1743080406369,
        "type": "value",
        "value": 0
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 15,
        "time": 1743080406369,
        "type": "bitmap",
        "value": 0
      },
      {
        "code": "temp_top",
        "custom_name": "",
        "dp_id": 21,
        "time": 1743081237120,
        "type": "value",
        "value": 1090
      },
      {
        "code": "temp_bottom",
        "custom_name": "",
        "dp_id": 22,
        "time": 1743278720649,
        "type": "value",
        "value": 457
      },
      {
        "code": "around_temp",
        "custom_name": "",
        "dp_id": 26,
        "time": 1743279190491,
        "type": "value",
        "value": 112
      },
      {
        "code": "pump_state",
        "custom_name": "",
        "dp_id": 30,
        "time": 1743278822609,
        "type": "bool",
        "value": false
      },
      {
        "code": "ele_heating_state",
        "custom_name": "",
        "dp_id": 32,
        "time": 1743246089496,
        "type": "bool",
        "value": false
      },
      {
        "code": "signal_strength",
        "custom_name": "",
        "dp_id": 101,
        "time": 1743080406369,
        "type": "value",
        "value": 0
      },
      {
        "code": "scene_data_raw",
        "custom_name": "",
        "dp_id": 102,
        "time": 1743080406369,
        "type": "raw"
      }
    ]
  },
  "success": true,
  "t": 1743279193356,
  "tid": "3e21e1930cda11f0905d5e1a959ba61d"
}
```

</details>

### Information about how the device functions

I found this [old config file](https://www.boards.ie/api/v2/media/download-by-url?url=https%3A%2F%2Fus.v-cdn.net%2F6034073%2Fuploads%2F6CGIGLLW94OF%2Fsr208c.txt) on a [forum](https://www.boards.ie/discussion/2058312831/solar-thermal-servicing-upgrades-cork-metropolitan-area)

[This is the manual for the SR208C](https://2-improve.com/wp-content/uploads/2018/10/Sr208C-met-pwm.pdf)

Important are
T1 (temperature at solar collector)
T2 (temperature at bottom of water collector)
T3 (temperature at top of water collector)
R1 (Pump running or not)
I'm not using it, but also external heater state
There are maybe other queries possible (state, settings etc.) they are secondary to me.

Thank you so much for helping me out. Even the official tuya (cloud) integration in HA could not manage this device...

**Comment by make-all** [comment]
Please separate the log for this device from any others. There are 5 log messages in there for at least 3 different devices.

**Comment by BeriBGood** [comment]
Sorry for doing it wrong. I refreshed the logs just before adding the SR208C and just after and copied everything that was shown.
I now freshly restarted the raspberry pi running HA and tried to connect the SR208C first thing after loading the interface. I hope the logs are clearer now.

Here is the logs. I also edited in the main post for clarity.

###
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:397
integration: Tuya Local (documentation, issues)
First occurred: 07:46:55 (1 occurrences)
Last logged: 07:46:55

Adding SR208C device with product id hyrswocbx6i1rveo

###

This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:415
integration: Tuya Local (documentation, issues)
First occurred: 07:46:55 (1 occurrences)
Last logged: 07:46:55

Device specification: [{"id": 1, "name": "switch", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 2, "name": "mode", "type": "Enum", "format": "{\"range\":[\"cold\",\"heating\",\"auto\"]}", "enumMap": {}}, {"id": 4, "name": "temp_set", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 6, "name": "temp_unit_convert", "type": "Enum", "format": "{\"range\":[\"c\",\"f\"]}", "enumMap": {}}, {"id": 8, "name": "instant_heating", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 14, "name": "countdown_left", "type": "Integer", "format": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 21, "name": "temp_top", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":4000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 22, "name": "temp_bottom", "type": "Integer", "format": "{\"unit\":\"\u2103\",\"min\":0,\"max\":4000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 30, "name": "pump_state", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 32, "name": "ele_heating_state", "type": "Boolean", "format": "{}", "enumMap": {}}]

###
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:421
integration: Tuya Local (documentation, issues)
First occurred: 07:46:55 (1 occurrences)
Last logged: 07:46:55

Device matches zigbee_smart_bulb with quality of 40%. DPS: {"updated_at": 1743313612.7234359, "1": false, "2": "heating", "4": 60, "6": "c", "8": false, "21": 1090, "22": 419, "26": 155, "30": false, "32": false}

**Comment by make-all** [comment]
> What I am not sure about, the product ID in the log and in the Tuya Core are different:
> log: hyrswocbx6i1rveo
> Tuya: bf545f96eb7eff2012viu6

The one from the log is the product id. The other is the device id, if you check the info in the tuya cloud API, you will see both listed there under those names. Device id is unique to your single device, so it is not useful for the config.

**Comment by BeriBGood** [comment]
I am a bloody noob in this topic and struggled a lot with the logic and the yaml syntax to just get some values out of the products.
I started working on it and learnt by trial and error and getting inspiration from other products.
It is not finished, surely not perfect, but for my use case and my needs it works. I do not need more than that.
Other better developers may work on this in the future (or not), in the meantime enjoy this simple limited config that works for me:

```
name: Solar water heater controller
products:
  - id: hyrswocbx6i1rveo
    manufacturer: Solar Electronics
    model: SR208C
entities:
  - entity: sensor
    name: Collector temperature (T1)
    icon: "mdi:sun-thermometer-outline"
    class: temperature
    dps:
      - id: 26
        type: integer
        name: sensor
        mapping:
          - scale: 10
        range:
          min: -300
          max: 4000
        unit: C
        class: measurement
  - entity: sensor
    name: Tank temperature bottom (T2)
    icon: "mdi:thermometer-chevron-down"
    class: temperature
    dps:
      - id: 22
        type: integer
        name: sensor
        mapping:
          - scale: 10
        range:
          min: 0
          max: 4000
        unit: C
        class: measurement
  - entity: sensor
    name: Tank temperature top (T3)
    icon: "mdi:thermometer-chevron-up"
    class: temperature
    dps:
      - id: 21
        type: integer
        name: sensor
        mapping:
          - scale: 10
        range:
          min: 0
          max: 4000
        unit: C
        class: measurement
  - entity: binary_sensor
    name: Circulation pump
    icon: "mdi:pump"
    category: diagnostic
    dps:
      - id: 30
        type: boolean
        name: sensor
```

**Comment by BeriBGood** [comment]
I adapted the file to be able to access the lower tank temperature in graphs and cards.
I do not know how to make a merge request, sorry for that.
```
name: Solar water heater
products:
  - id: hyrswocbx6i1rveo
    manufacturer: Lohxa
    model: SR208C
entities:
  - entity: water_heater
    dps:
      - id: 1
        type: boolean
        name: operation_mode
        mapping:
          - dps_val: false
            value: "off"
          - dps_val: true
            constraint: mode
            conditions:
              - dps_val: auto
                value: eco
                default: true
              - dps_val: heating
                value: electric
              - dps_val: cold
                value: away
      - id: 2
        type: string
        name: mode
        hidden: true
      - id: 4
        type: integer
        name: temperature
        unit: C
        range:
          min: 0
          max: 100
      - id: 22
        type: integer
        name: current_temperature
        mapping:
          - scale: 10
          - dps_val: 3888
            value: null
          - dps_val: 3999
            value: null
  - entity: select
    translation_key: temperature_unit
    category: config
    dps:
      - id: 6
        type: string
        name: option
        mapping:
          - dps_val: c
            value: celsius
          - dps_val: f
            value: fahrenheit
  - entity: switch
    name: Instant heating
    icon: "mdi:heating-coil"
    category: config
    dps:
      - id: 8
        type: boolean
        name: switch
  - entity: sensor
    translation_key: time_remaining
    class: duration
    category: diagnostic
    dps:
      - id: 14
        type: integer
        optional: true
        name: sensor
        unit: min
        class: measurement
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 15
        type: bitfield
        optional: true
        name: sensor
        mapping:
          - dps_val: null
            value: false
          - dps_val: 0
            value: false
          - value: true
      - id: 15
        type: bitfield
        optional: true
        name: fault_code
  - entity: sensor
    name: Upper tank temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 21
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
          - dps_val: 3888
            value: null
          - dps_val: 3999
            value: null
  - entity: sensor
    name: Lower tank temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 22
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
          - dps_val: 3888
            value: null
          - dps_val: 3999
            value: null
  - entity: sensor
    name: Solar collector temperature
    class: temperature
    category: diagnostic
    dps:
      - id: 26
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
          - dps_val: 3888
            value: null
          - dps_val: 3999
            value: null
  - entity: binary_sensor
    name: Solar
    icon: "mdi:solar-power-variant"
    class: running
    category: diagnostic
    dps:
      - id: 30
        type: boolean
        name: sensor
  - entity: binary_sensor
    name: Electric element
    class: running
    icon: "mdi:heating-coil"
    category: diagnostic
    dps:
      - id: 32
        type: boolean
        name: sensor
  - entity: sensor
    class: signal_strength
    category: diagnostic
    hidden: true
    dps:
      - id: 101
        type: integer
        optional: true
        name: sensor
        unit: dBm
        class: measurement
        range:
          min: 0
          max: 100
        mapping:
          - target_range:
              min: -90
              max: -20
  - entity: text
    name: Configuration
    category: config
    icon: "mdi:cogs"
    hidden: true
    dps:
      - id: 102
        type: base64
        optional: true
        name: value
```
