### ISSUE TITLE
T34 smart plug: no "initial_state" entity

### ISSUE THREAD

**Issue by voed** [make-all/tuya-local#3112]
### Description

The device detected as aubess_1gang_switch, everything else works fine, but there's no initial_state entity. I know some plugs does not have it, but it's not the case, i see it in the tuya app. Added diagnostics, let me know if you need any extra info.

![Image](https://github.com/user-attachments/assets/ade37ee9-28ca-4c94-b197-48046c609698)

### Additional context

<details>
  <summary>Diagnostic info</summary>
  

  
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2025.3.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.13.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Kyiv",
    "os_name": "Linux",
    "os_version": "6.12.18-haos",
    "supervisor": "2025.03.4",
    "host_os": "Home Assistant OS 15.0",
    "docker_version": "28.0.1",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "documentation": "https://hacs.xyz/docs/use/",
      "version": "2.0.5",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "solarman": {
      "documentation": "https://github.com/davidrapan/ha-solarman",
      "version": "25.03.18",
      "requirements": [
        "propcache",
        "aiofiles",
        "pyyaml",
        "pymodbus>=3.8.3"
      ]
    },
    "moonraker": {
      "documentation": "https://moonraker-home-assistant.readthedocs.io/en/latest/",
      "version": "1.7.0",
      "requirements": [
        "moonraker-api==2.0.6"
      ]
    },
    "smartir": {
      "documentation": "https://github.com/smartHomeHub/SmartIR",
      "version": "1.18.0",
      "requirements": [
        "aiofiles>=0.6.0"
      ]
    },
    "reolink_dev": {
      "documentation": "https://github.com/fwestenberg/reolink_dev",
      "version": "0.64",
      "requirements": [
        "reolink==0.0.64",
        "aiosmtpd>=1.4.2"
      ]
    },
    "prana": {
      "documentation": null,
      "version": "0.0.1",
      "requirements": [
        "bleak-retry-connector>=1.17.1",
        "bleak>=0.17.0"
      ]
    },
    "adaptive_cover": {
      "documentation": "https://github.com/basbruss/adaptive-cover",
      "version": "1.4.5",
      "requirements": [
        "astral",
        "pandas"
      ]
    },
    "tuya_local": {
      "documentation": "https://github.com/make-all/tuya-local",
      "version": "2025.3.0",
      "requirements": [
        "tinytuya==1.16.1",
        "tuya-device-sharing-sdk~=0.2.1"
      ]
    },
    "sonoff": {
      "documentation": "https://github.com/AlexxIT/SonoffLAN",
      "version": "3.8.2",
      "requirements": [
        "pycryptodome>=3.6.6"
      ]
    },
    "lywsd02": {
      "documentation": "https://github.com/ashald/home-assistant-lywsd02",
      "version": "0.2.0",
      "requirements": [
        "bluetooth_adapters"
      ]
    },
    "weatherdotcom": {
      "documentation": "https://github.com/jaydeethree/Home-Assistant-weatherdotcom",
      "version": "1.2.0",
      "requirements": []
    },
    "ble_monitor": {
      "documentation": "https://github.com/custom-components/ble_monitor",
      "version": "13.0.3",
      "requirements": [
        "pycryptodomex>=3.21.0",
        "janus>=2.0.0",
        "aioblescan>=0.2.14",
        "btsocket>=0.3.0",
        "pyric>=0.1.6.3"
      ]
    },
    "tuya_ble": {
      "documentation": "https://www.home-assistant.io/integrations/tuya_ble",
      "version": "0.1.8",
      "requirements": [
        "tuya-iot-py-sdk==0.6.6",
        "pycountry>23.0.0"
      ]
    },
    "battery_notes": {
      "documentation": "https://andrew-codechimp.github.io/HA-Battery-Notes/",
      "version": "2.9.5",
      "requirements": []
    },
    "netdaemon": {
      "documentation": "https://github.com/net-daemon/integration",
      "version": "24.50.0",
      "requirements": [
        "awesomeversion>=21.1.0"
      ]
    },
    "webrtc": {
      "documentation": "https://github.com/AlexxIT/WebRTC",
      "version": "v3.6.0",
      "requirements": []
    },
    "pandora_cas": {
      "documentation": "https://github.com/alryaz/pandora-cas",
      "version": "2.0.1",
      "requirements": []
    },
    "mikrotik_router": {
      "documentation": "https://github.com/tomaae/homeassistant-mikrotik_router",
      "version": "0.0.0",
      "requirements": [
        "librouteros>=3.2.0",
        "mac-vendor-lookup>=0.1.12"
      ]
    },
    "better_thermostat": {
      "documentation": "https://github.com/KartoffelToby/better_thermostat",
      "version": "1.7.0-beta3",
      "requirements": []
    },
    "nova_poshta": {
      "documentation": "https://github.com/krasnoukhov/homeassistant-nova-poshta",
      "version": "1.2.1",
      "requirements": [
        "stringcase>=1.2.0",
        "translitua==1.3.2",
        "novaposhta-python-client==0.1.3"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tuya_local",
    "name": "Tuya Local",
    "codeowners": [
      "make-all"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/make-all/tuya-local",
    "integration_type": "device",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/make-all/tuya-local/issues",
    "loggers": [
      "tuya_local",
      "tinytuya",
      "tuya_sharing"
    ],
    "requirements": [
      "tinytuya==1.16.1",
      "tuya-device-sharing-sdk~=0.2.1"
    ],
    "version": "2025.3.0",
    "is_built_in": false,
    "overwrites_built_in": false
  },
  "setup_times": {
    "null": {
      "setup": 2.9266986530274153e-05
    },
    "ac3d303d567bf40e5ab1252b53ca53c7": {
      "wait_import_platforms": -1.8756673309835605,
      "wait_base_component": -0.0006555599975399673,
      "config_entry_setup": 1.978342735033948
    },
    "75719e30870c5056e49f68e9b71bbcbb": {
      "wait_import_platforms": -1.8728908930206671,
      "config_entry_setup": 1.9850435970001854
    },
    "01JPWX0QQFMV2S5KKVQHEGJ3Q4": {
      "wait_import_platforms": -1.890846813970711,
      "config_entry_setup": 1.9778543889988214
    }
  },
  "data": {
    "name": "T34 plug",
    "type": "aubess_1gang_switch",
    "device_id": "**REDACTED**",
    "device_cid": "",
    "local_key": "**REDACTED**",
    "host": "**REDACTED**",
    "protocol_version": 3.4,
    "tinytuya_version": "1.16.1",
    "api_version_set": 3.4,
    "api_version_used": 3.4,
    "api_working": true,
    "status": {},
    "cached_state": {
      "updated_at": 1743538627.1779776,
      "1": false,
      "9": 0,
      "21": 0,
      "22": 0,
      "23": 2157,
      "24": 1,
      "29": 0,
      "38": "memory",
      "42": "",
      "43": "",
      "44": "AAAC"
    },
    "pending_state": {},
    "connected": true,
    "force_dps": [
      21,
      22,
      23
    ],
    "home_assistant": {
      "name": "T34 plug",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "problem",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "binary_sensor.t34_plug_problema",
            "state": "off",
            "attributes": {
              "fault_code": 0,
              "device_class": "problem",
              "friendly_name": "T34 plug \u041f\u0440\u043e\u0431\u043b\u0435\u043c\u0430"
            },
            "last_changed": "2025-04-01T20:17:07.180409+00:00",
            "last_reported": "2025-04-01T20:17:07.180409+00:00",
            "last_updated": "2025-04-01T20:17:07.180409+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "switch.t34_plug",
            "state": "off",
            "attributes": {
              "test_bit": 1,
              "random_time": "",
              "cycle_time": "",
              "switch_inching": "AAAC",
              "friendly_name": "T34 plug"
            },
            "last_changed": "2025-04-01T20:17:07.181717+00:00",
            "last_reported": "2025-04-01T20:17:07.181717+00:00",
            "last_updated": "2025-04-01T20:17:07.181717+00:00"
          }
        },
        {
          "disabled": true,
          "disabled_by": "integration",
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "unit_of_measurement": "Wh",
          "state": null
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "current",
          "icon": null,
          "unit_of_measurement": "mA",
          "state": {
            "entity_id": "sensor.t34_plug_strum",
            "state": "0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "mA",
              "device_class": "current",
              "friendly_name": "T34 plug \u0421\u0442\u0440\u0443\u043c"
            },
            "last_changed": "2025-04-01T20:17:07.178635+00:00",
            "last_reported": "2025-04-01T20:17:07.178635+00:00",
            "last_updated": "2025-04-01T20:17:07.178635+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "power",
          "icon": null,
          "unit_of_measurement": "W",
          "state": {
            "entity_id": "sensor.t34_plug_zhivlennia",
            "state": "0.0",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "W",
              "device_class": "power",
              "friendly_name": "T34 plug \u0416\u0438\u0432\u043b\u0435\u043d\u043d\u044f"
            },
            "last_changed": "2025-04-01T20:17:07.179331+00:00",
            "last_reported": "2025-04-01T20:17:07.179331+00:00",
            "last_updated": "2025-04-01T20:17:07.179331+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "diagnostic",
          "device_class": null,
          "original_device_class": "voltage",
          "icon": null,
          "unit_of_measurement": "V",
          "state": {
            "entity_id": "sensor.t34_plug_napruga",
            "state": "215.7",
            "attributes": {
              "state_class": "measurement",
              "unit_of_measurement": "V",
              "device_class": "voltage",
              "friendly_name": "T34 plug \u041d\u0430\u043f\u0440\u0443\u0433\u0430"
            },
            "last_changed": "2025-04-01T20:17:07.179894+00:00",
            "last_reported": "2025-04-01T20:17:07.179894+00:00",
            "last_updated": "2025-04-01T20:17:07.179894+00:00"
          }
        },
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": "config",
          "device_class": null,
          "original_device_class": "duration",
          "icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "number.t34_plug_taimer",
            "state": "0.0",
            "attributes": {
              "min": 0.0,
              "max": 1440.0,
              "step": 1.0,
              "mode": "auto",
              "device_class": "duration",
              "friendly_name": "T34 plug \u0422\u0430\u0439\u043c\u0435\u0440"
            },
            "last_changed": "2025-04-01T20:17:07.181047+00:00",
            "last_reported": "2025-04-01T20:17:07.181047+00:00",
            "last_updated": "2025-04-01T20:17:07.181047+00:00"
          }
        }
      ]
    }
  }
}
```
  
</details>

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.

**Comment by make-all** [comment]
Akthough there are no logs attached, I think I can see what might be happening. At startup, the initial state has no options, so I think HA is skipping creating it (even though it will have options later once the data is received from the device).

**Comment by blavak68** [comment]
in folder devices you find file 
aubess_1gang_switch.yaml
in this file you find section

```
  dps:
      - id: 38
        type: string
        name: option
        mapping:
          - dps_val: "0"
            value: "off"
            available: numeric_values
          - dps_val: "1"
            value: "on"
            available: numeric_values
          - dps_val: "2"
            value: memory
            available: numeric_values

          - dps_val: "off"
            value: "off"
            available: word_values
          - dps_val: "on"
            value: "on"
            available: word_values
          - dps_val: "memory"
            value: memory
            available: word_values
            
      - id: 38
        type: string
        name: numeric_values
        mapping:
          - dps_val: "0"
            value: true
          - dps_val: "1"
            value: true
          - dps_val: "2"
            value: true
          - value: false
          
      - id: 38
        type: string
        name: word_values
        mapping:
          - dps_val: "on"
            value: true
          - dps_val: "off"
            value: true
          - dps_val: memory
            value: true
          - value: false
```

and change it with this code

```
    dps:
      - id: 38
        type: string
        name: option
        mapping:
          - dps_val: "0"
            value: "off"
          - dps_val: "1"
            value: "on"
          - dps_val: "2"
            value: "memory"
          - dps_val: "off"
            value: "off"
          - dps_val: "on"
            value: "on"
          - dps_val: "memory"
            value: "memory"
```
