### ISSUE TITLE
Improvement for Fairy Lights

### ISSUE THREAD

**Issue by PaPa1ya** [make-all/tuya-local#3144]
### Description

This is an improvement to the config for this device:
https://github.com/make-all/tuya-local/issues/2724
https://github.com/make-all/tuya-local/blob/3b705bae6c4e45f4c748e8e91560ffe9947a771b/custom_components/tuya_local/devices/rgbled_garland.yaml

It will make the following changes:
- Adds a list of specific scenes supported by this product;
- Will set the specific correct Color order for that product;
- Adds support and a list of music scenes, of this product;

```yaml
name: Fairy lights
products:
  - id: dpfvez4c2ui18yef
entities:
  - entity: light
    icon: "mdi:led-strip"
    dps:
      - id: 20
        type: boolean
        name: switch
      - id: 21
        name: effect
        type: string
        mapping:
          - dps_val: colour
            value: RGB
          - dps_val: scene
            value: Scene
          - dps_val: music
            value: Music
        optional: true
      - id: 24
        name: rgbhsv
        type: hex
        format:
          - name: h
            bytes: 2
            range:
              min: 0
              max: 360
          - name: s
            bytes: 2
            range:
              min: 0
              max: 1000
          - name: v
            bytes: 2
            range:
              min: 0
              max: 1000
      - id: 51
        type: string
        optional: true
        name: dreamlight_scene_mode
      - id: 52
        type: string
        optional: true
        name: dreamlightmic_music_data
      - id: 61
        type: string
        optional: true
        name: paint_color_data
  - entity: number
    translation_key: timer
    class: duration
    category: config
    dps:
      - id: 26
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        precision: 0
        mapping:
          - scale: 60
            step: 60
  - entity: number
    name: LED count
    category: config
    icon: "mdi:led-strip-variant"
    dps:
      - id: 53
        type: integer
        name: value
        range:
          min: 1
          max: 1000
      - id: 47
        type: integer
        name: from_device
  - entity: select
    name: Scene
    icon: "mdi:palette"
    category: config
    dps:
      - id: 51
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "ARUKUlLgAABkAMFhALQwALVSAMRj"
            value: "Iceland Blue"
          - dps_val: "ARYKZGRgAABkAJJfAMZg"
            value: "Glacier express"
          - dps_val: "ARcDXl5gAABkADgvAB5cANVFARpk"
            value: "Sea of clouds"
          - dps_val: "ARgCZGTgAABkALI5AQpkAS1kAT9k"
            value: "Fireworks at sea"
          - dps_val: "ARkKVFRgAABkALEsAMBk"
            value: "Hut in the snow"
          - dps_val: "ARoDS0vgAABkAOA5AQlT"
            value: "Firefly night"
          - dps_val: "ARsDX19gAABkAK45AMRdAPlk"
            value: "Northland"
          - dps_val: "ARwKWlrgAABSAJ1kAI5k"
            value: "Grassland"
          - dps_val: "AR0DUlLgAABkAK5kAKZkAMFkAMxk"
            value: "Northern lights"
          - dps_val: "AR4KUlLgAABkABlkACJeACxbABRkAAxk"
            value: "Late autumn"
          - dps_val: "AUcFTU0AAABkAQNFAMFD"
            value: "Dream meteor"
          - dps_val: "AUgGMjIAAABkAU5BAB9J"
            value: "Early spring"
          - dps_val: "AUkHDg4AAABkANo3AVJBAFw3"
            value: "Spring outing"
          - dps_val: "AUoIMjIAAABkAPdQAClPAQ04AKMn"
            value: "Night service"
          - dps_val: "AUsJMjIAAABkAQNFAEE6ACVLAF5C"
            value: "Wind chime"
          - dps_val: "AUwMMjIAAABkANhNAMFDAQNFAFw3"
            value: "City lights"
          - dps_val: "AU0NMjIAAABkAChkAF5CAMFkAP9Q"
            value: "Color marbles"
          - dps_val: "AU4OMjIAAABkAD5fAL5c"
            value: "Summer train"
          - dps_val: "AU8PGRkAAABkALxkAC1OAABkAGQ8"
            value: "Christmas Eve"
          - dps_val: "AVAQMjIAAABkAOZHAGQ8ARlNALg5"
            value: "Dream Sea"
          - dps_val: "AR8CX19gAABkARBkANJkAK1kAItk"
            value: "Gamne"
          - dps_val: "ASAKVVVgAABkAMJYAT4zAP9GAR1k"
            value: "Holiday"
          - dps_val: "ASEDPDxgAABkAL8YAQQX"
            value: "Work"
          - dps_val: "ASIEZGRgAABkANdcALxTADceACw/AWE/"
            value: "Party"
          - dps_val: "ASMCZGRgAABkAQhLALEvAM1X"
            value: "Trend"
          - dps_val: "ASQKS0tgAABkALwmANZVARhkAPlN"
            value: "Sports"
          - dps_val: "ASUDQ0NgAABkALc1AJtUAM1h"
            value: "Meditation"
          - dps_val: "ASYBWVngAABkARlHAUk9AM1hACZk"
            value: "Dating"
          - dps_val: "ASkCYWHgAABkAAtkANlkACtkAJFkALlk"
            value: "Christmas"
          - dps_val: "ASoBZGRgAABkARVkAQVkAUVkAS9k"
            value: "Valentine's Day"
          - dps_val: "ASsDWlrgAABkAABXARZkANpkALNkAJVk"
            value: "Halloween"
          - dps_val: "ASwKSEhgAABkAD1kAQxbALpJABdh"
            value: "Thanksgiving Day"
          - dps_val: "AS0CWVlgAABkAJxjALxiAHtg"
            value: "Forest Day"
          - dps_val: "AS4DWlpgAABkAT42AQxWAR8j"
            value: "Mother's Day"
          - dps_val: "AS8CZGTgAABkANxCALZKAOFN"
            value: "Father's Day"
          - dps_val: "ATACXl5gAABkAABkAHhkALtk"
            value: "Football Day"
          - dps_val: "ATMDUlJgAABkAIhQANI5APsn"
            value: "Summer idyll"
          - dps_val: "ATQDXV1gAABkAPc2ATUrAMY0AJEp"
            value: "Dream of the sea"
          - dps_val: "ATUDUlJgAABNARJiATBd"
            value: "Love and dream"
          - dps_val: "ATYCSUlgAABkAGY8ADxJAB5k"
            value: "Spring fishing"
          - dps_val: "ATcKWlpgAABkADNYABhkAQBFAONeAKww"
            value: "Neon world"
          - dps_val: "ATgCV1fgAABkAQxkARpBAUdZABVkADw4"
            value: "Dreamland"
          - dps_val: "ATkDSEjgAABkAFlkALNH"
            value: "Summer wind"
          - dps_val: "AToCXV3gAABNALReARxkAOhJAMZf"
            value: "Planet journey"
  - entity: select
    name: Music
    icon: "mdi:music"
    category: config
    dps:
      - id: 52
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "AQEAA2QyAAAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA=="
            value: "Rock"
          - dps_val: "AQEAAmQyAAAAZAAAUAB4UADwUAA8UAC0UAEsUAAAAA=="
            value: "Jazz"
          - dps_val: "AQEAEmQyAAAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA=="
            value: "Classic"
          - dps_val: "AQEBAmQyAQAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA=="
            value: "Scroll"
          - dps_val: "AQECAGQyAQAAZAAAZAB4ZADwZAA8ZAC0ZAEsZA=="
            value: "Energy"
          - dps_val: "AQEDEGQyAQAAZAAAZAB4ZADwZAA8ZAC0ZAEsZAAAAA=="
            value: "Spectrum"
```

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.
