### ISSUE TITLE
Request support for Tuya Smart Life WiFi Energy Meter V-WIFI-DL01-ES

### ISSUE THREAD

**Issue by sidkipper1** [make-all/tuya-local#3161]
### Log message

```text
Device matches None with quality of 0%. DPS: {"updated_at": 1744977888.8379893, "103": "monitor", "105": 0, "106": 0, "107": 2462, "110": "normal", "111": 500, "113": "cloud_net"}
```

### Product ID

dyazpvq8orn3psn1

### Product Name

Tuya Smart Life WiFi Energy Meter (1 channel)

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"emsvi4\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"sync_request\",\"description\":\"\",\"extensions\":{\"cloudless\":1,\"trigger\":\"direct\"},\"name\":\"请求实时更新\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"idle\",\"request\"]}},
{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"sync_response\",\"description\":\"\",\"extensions\":{\"cloudless\":1,\"trigger\":\"direct\"},\"name\":\"回复实时更新\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"idle\",\"ok\"]}},
{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"device_state1\",\"description\":\"\",\"name\":\"设备状态1\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"close\",\"monitor\",\"working\",\"warning\"]}},
{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"add_ele1\",\"description\":\"\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"电量统计\",\"typeSpec\":{\"type\":\"value\",\"max\":500000,\"min\":0,\"scale\":2,\"step\":1,\"unit\":\"kWh\"}},
{\"abilityId\":105,\"accessMode\":\"ro\",\"code\":\"cur_power1\",\"description\":\"\",\"name\":\"当前功率\",\"typeSpec\":{\"type\":\"value\",\"max\":2000000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"W\"}},
{\"abilityId\":106,\"accessMode\":\"ro\",\"code\":\"cur_current1\",\"description\":\"\",\"name\":\"当前电流\",\"typeSpec\":{\"type\":\"value\",\"max\":800000,\"min\":0,\"scale\":3,\"step\":1,\"unit\":\"A\"}},
{\"abilityId\":107,\"accessMode\":\"ro\",\"code\":\"cur_voltage1\",\"description\":\"\",\"name\":\"当前电压\",\"typeSpec\":{\"type\":\"value\",\"max\":5000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"V\"}},
{\"abilityId\":108,\"accessMode\":\"ro\",\"code\":\"total_energy1\",\"description\":\"\",\"name\":\"总电量\",\"typeSpec\":{\"type\":\"value\",\"max\":2147483647,\"min\":0,\"scale\":3,\"step\":1,\"unit\":\"kwh\"}},
{\"abilityId\":109,\"accessMode\":\"ro\",\"code\":\"today_acc_energy1\",\"description\":\"\",\"name\":\"今日用电量\",\"typeSpec\":{\"type\":\"value\",\"max\":2147483647,\"min\":0,\"scale\":3,\"step\":1,\"unit\":\"kwh\"}},
{\"abilityId\":110,\"accessMode\":\"ro\",\"code\":\"power_type1\",\"description\":\"\",\"name\":\"第1路功率类型\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"normal\",\"warn\"]}},
{\"abilityId\":111,\"accessMode\":\"rw\",\"code\":\"warn_power1\",\"description\":\"\",\"name\":\"第1路告警功率设置\",\"typeSpec\":{\"type\":\"value\",\"max\":50000,\"min\":200,\"scale\":0,\"step\":100,\"unit\":\"W\"}},
{\"abilityId\":112,\"accessMode\":\"ro\",\"code\":\"today_energy_add1\",\"description\":\"\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"第1路用电量增加\",\"typeSpec\":{\"type\":\"value\",\"max\":500000,\"min\":0,\"scale\":2,\"step\":1,\"unit\":\"kWh\"}},
{\"abilityId\":113,\"accessMode\":\"ro\",\"code\":\"net_state\",\"description\":\"\",\"extensions\":{\"trigger\":\"direct\"},\"name\":\"网络状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"cloud_net\",\"local_net\",\"no_net\"]}}]}]}"
  },
  "success": true,
  "t": 1744979956836,
  "tid": "241cab161c5211f0942fe62c0c16c951"
}
```

### Information about how the device functions

Single channel version of the V-WIFI-DL02-ES that you already have a config for (tuya-energy-meter.yaml).  Attempted to create a version for this device, which gets detected by the device add wizard, but no device or entities get added (expect my attempt has errors in it).

https://www.aliexpress.com/i/1005005849090155.html (has both the single and dual channel devices)

My config file attempt (tuya-v-wifi-dl01-es-clamp-meter.yaml)

```
name: Single energy meter
products:
  - id: dyazpvq8orn3psn1
    model: V-WIFI-DL01-ES
entities:
  - entity: sensor
    category: diagnostic
    name: Device state
    dps:
      - id: 103
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: close
            value: close
            default: true
          - dps_val: monitor
            value: monitor
          - dps_val: working
            value: working
          - dps_val: warning
            value: warning
  - entity: sensor
    category: diagnostic
    name: Total Energy
    class: energy
    dps:
      - id: 104
        name: sensor
        type: integer
        unit: kWh
        force: true
        class: total_increasing
        mapping:
          - scale: 2
  - entity: sensor
    category: diagnostic
    #name: Current Power
    translation_key: power_x
    translation_placeholders:
      x: 1
    class: power
    dps:
      - id: 105
        name: sensor
        type: integer
        unti: W
        force: true
        class: measurement
  - entity: sensor
    category: diagnostic
    #name: Current
    translation_key: current_x
    translation_placeholders:
      x: "1"
    class: current
    dps:
      - id: 106
        name: sensor
        type: integer
        unti: A
        force: true
        class: measurement
        mapping:
          - scale: 3
  - entity: sensor
    category: diagnostic
    #name: Voltage
    translation_key: voltage_x
    translation_placeholders:
      x: "1"
    class: voltage
    dps:
      - id: 107
        name: sensor
        type: integer
        unti: A
        force: true
        class: measurement
  - entity: sensor
    category: diagnostic
    name: Total Energy
    class: energy
    dps:
      - id: 108
        name: sensor
        type: integer
        unti: kWh
        force: true
        class: total_increasing
        mapping:
          - scale: 3
  - entity: sensor
    category: diagnostic
    name: Today Energy
    class: energy
    dps:
      - id: 109
        name: sensor
        type: integer
        unti: kWh
        force: true
        class: total_increasing
        mapping:
          - scale: 3
  - entity: sensor
    category: diagnostic
    name: Power Type
    dps:
      - id: 110
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: normal
            value: normal
            default: true
          - dps_val: warn
            value: mwarn
  - entity: sensor
    category: diagnostic
    name: Network Status
    dps:
      - id: 113
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: cloud_net
            value: Cloud
            default: true
          - dps_val: local_net
            value: Local
          - dps_val: no_net
            value: None
```

Error when adding...

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:382
integration: Sensor (documentation, issues)
First occurred: 18:47:46 (1 occurrences)
Last logged: 18:47:46

Error while setting up tuya_local platform for sensor: decoding to str: need a bytes-like object, int found
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/helpers/config.py", line 31, in async_tuya_setup_platform
    data[ecfg.config_id] = entity_class(device, ecfg)
         ^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 309, in config_id
    slug = slug.replace(key, slugify(value))
                             ~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 45, in slugify
    slug = unicode_slug.slugify(text, separator=separator)
  File "/usr/local/lib/python3.13/site-packages/slugify/slugify.py", line 115, in slugify
    text = str(text, 'utf-8', 'ignore')
TypeError: decoding to str: need a bytes-like object, int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/tuya_local/sensor.py", line 23, in async_setup_entry
    await async_tuya_setup_platform(
    ...<5 lines>...
    )
  File "/config/custom_components/tuya_local/helpers/config.py", line 39, in async_tuya_setup_platform
    ecfg.config_id,
    ^^^^^^^^^^^^^^
  File "/config/custom_components/tuya_local/helpers/device_config.py", line 309, in config_id
    slug = slug.replace(key, slugify(value))
                             ~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 45, in slugify
    slug = unicode_slug.slugify(text, separator=separator)
  File "/usr/local/lib/python3.13/site-packages/slugify/slugify.py", line 115, in slugify
    text = str(text, 'utf-8', 'ignore')
TypeError: decoding to str: need a bytes-like object, int found
```

**Comment by sidkipper1** [comment]
Found an error in my config, can now add the device.  The string based entities are not working yet, and need to validate the scaling of the metrics.  Should get a chance to look further after the weekend.

```
name: Single energy meter
products:
  - id: dyazpvq8orn3psn1
    model: V-WIFI-DL01-ES
entities:
  - entity: sensor
    category: diagnostic
    name: Device state
    dps:
      - id: 103
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: close
            value: close
            default: true
          - dps_val: monitor
            value: monitor
          - dps_val: working
            value: working
          - dps_val: warning
            value: warning
  - entity: sensor
    category: diagnostic
    name: Total Energy
    class: energy
    dps:
      - id: 104
        name: sensor
        type: integer
        unit: kWh
        force: true
        class: total_increasing
        #mapping:
        #  - scale: 2
  - entity: sensor
    category: diagnostic
    #name: Current Power
    translation_key: power_x
    translation_placeholders:
      x: "1"
    class: power
    dps:
      - id: 105
        name: sensor
        type: integer
        unti: W
        force: true
        class: measurement
  - entity: sensor
    category: diagnostic
    #name: Current
    translation_key: current_x
    translation_placeholders:
      x: "1"
    class: current
    dps:
      - id: 106
        name: sensor
        type: integer
        unti: A
        force: true
        class: measurement
        #mapping:
        #  - scale: 3
  - entity: sensor
    category: diagnostic
    #name: Voltage
    translation_key: voltage_x
    translation_placeholders:
      x: "1"
    class: voltage
    dps:
      - id: 107
        name: sensor
        type: integer
        unti: A
        force: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    name: Total Energy
    class: energy
    dps:
      - id: 108
        name: sensor
        type: integer
        unti: kWh
        force: true
        class: total_increasing
        #mapping:
        #  - scale: 3
  - entity: sensor
    category: diagnostic
    name: Today Energy
    class: energy
    dps:
      - id: 109
        name: sensor
        type: integer
        unti: kWh
        force: true
        class: total_increasing
        #mapping:
        #  - scale: 3
  - entity: sensor
    category: diagnostic
    name: Power Type
    dps:
      - id: 110
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: normal
            value: normal
            default: true
          - dps_val: warn
            value: warn
  - entity: sensor
    category: diagnostic
    name: Network Status
    dps:
      - id: 113
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: cloud_net
            value: Cloud
            default: true
          - dps_val: local_net
            value: Local
          - dps_val: no_net
            value: None
```

**Comment by sidkipper1** [comment]
Updated config, all entities update with correct scaling and power monitoring alarm threshold updates in Smart Life app when changed through HA.

tuya-v-wifi-dl01-es-clamp-meter.yaml

```
name: Single energy meter
products:
  - id: dyazpvq8orn3psn1
    model: V-WIFI-DL01-ES
entities:
  - entity: sensor
    category: diagnostic
    name: Device State
    class: enum
    dps:
      - id: 103
        name: sensor
        type: string
        readonly: true
        #force: true
        mapping:
          - dps_val: close
            value: Close
            default: true
          - dps_val: monitor
            value: Monitor
          - dps_val: working
            value: Working
          - dps_val: warning
            value: Warning
  - entity: sensor
    category: diagnostic
    name: Power Statistics
    class: energy
    dps:
      - id: 104
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total_increasing
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    #name: Current Power
    translation_key: power_x
    translation_placeholders:
      x: "1"
    class: power
    dps:
      - id: 105
        name: sensor
        type: integer
        unit: W
        readonly: true
        force: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    #name: Current
    translation_key: current_x
    translation_placeholders:
      x: "1"
    class: current
    dps:
      - id: 106
        name: sensor
        type: integer
        unit: A
        readonly: true
        force: true
        class: measurement
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    #name: Voltage
    translation_key: voltage_x
    translation_placeholders:
      x: "1"
    class: voltage
    dps:
      - id: 107
        name: sensor
        type: integer
        unit: V
        readonly: true
        force: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    name: Total Energy
    class: energy
    dps:
      - id: 108
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total_increasing
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    name: Today Energy
    class: energy
    dps:
      - id: 109
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total_increasing
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    name: Power Type
    class: enum
    dps:
      - id: 110
        name: sensor
        type: string
        force: true
        readonly: true
        mapping:
          - dps_val: normal
            value: Normal
            default: true
          - dps_val: warn
            value: Warn
  - entity: number
    category: config
    name: Power 1 Alarm Setting
    class: power
    dps:
      - id: 111
        name: value
        type: integer
        unit: W
        range:
          min: 200
          max: 50000
        mapping:
          - step: 100
  - entity: sensor
    category: diagnostic
    name: Increased Energy
    class: energy
    dps:
      - id: 112
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    name: Network Status
    class: enum
    dps:
      - id: 113
        name: sensor
        type: string
        force: true
        mapping:
          - dps_val: cloud_net
            value: Cloud
            default: true
          - dps_val: local_net
            value: Local
          - dps_val: no_net
            value: None
```

**Comment by sidkipper1** [comment]
Think I may have pasted the wrong config before, this one works for all DPs except Device State, Network Status, Power Type.  None of which show anything particularly useful (except maybe Network Status which shows whether managed locally or via Tuya cloud).

```
name: Single energy meter
products:
  - id: dyazpvq8orn3psn1
    model: V-WIFI-DL01-ES
entities:
  - entity: sensor
    category: diagnostic
    name: Device state
    dps:
      - id: 103
        name: sensor
        type: string
        readonly: true
        mapping:
          - dps_val: close
            value: Close
            default: true
          - dps_val: monitor
            value: Monitor
          - dps_val: working
            value: Working
          - dps_val: warning
            value: Warning
  - entity: sensor
    category: diagnostic
    name: Power Statistics
    class: energy
    dps:
      - id: 104
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total_increasing
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    #name: Current Power
    translation_key: power_x
    translation_placeholders:
      x: "1"
    class: power
    dps:
      - id: 105
        name: sensor
        type: integer
        unit: W
        readonly: true
        force: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    #name: Current
    translation_key: current_x
    translation_placeholders:
      x: "1"
    class: current
    dps:
      - id: 106
        name: sensor
        type: integer
        unit: A
        readonly: true
        force: true
        class: measurement
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    #name: Voltage
    translation_key: voltage_x
    translation_placeholders:
      x: "1"
    class: voltage
    dps:
      - id: 107
        name: sensor
        type: integer
        unit: V
        readonly: true
        force: true
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    name: Total Energy
    class: energy
    dps:
      - id: 108
        name: sensor
        type: integer
        unti: kWh
        readonly: true
        force: true
        class: total_increasing
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    name: Today Energy
    class: energy
    dps:
      - id: 109
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total_increasing
        mapping:
          - scale: 1000
  - entity: sensor
    category: diagnostic
    name: Power Type
    dps:
      - id: 110
        name: sensor
        type: string
        readonly: true
        force: true
        mapping:
          - dps_val: normal
            value: Normal
            default: true
          - dps_val: warn
            value: Warn
  - entity: number
    category: config
    name: Power 1 Alarm Setting
    class: power
    dps:
      - id: 111
        name: value
        type: integer
        unit: W
        range:
          min: 200
          max: 50000
        mapping:
          - step: 100
  - entity: sensor
    category: diagnostic
    name: Increased Energy
    class: energy
    dps:
      - id: 112
        name: sensor
        type: integer
        unit: kWh
        readonly: true
        force: true
        class: total
        mapping:
          - scale: 100
  - entity: sensor
    category: diagnostic
    name: Network Status
    dps:
      - id: 113
        name: sensor
        type: string
        readonly: true
        force: true
        mapping:
          - dps_val: cloud_net
            value: Cloud
            default: true
          - dps_val: local_net
            value: Local
          - dps_val: no_net
            value: None
```
