### ISSUE TITLE
Set DP service to be added

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#318]
localtuya addon support sending DP values as a service, see for ex. the following code:
```
            - service: localtuya.set_dp
              data_template:
                device_id: bf711554ea4678bf7fccqq
                dp: 25
                value: >
                    {{states('input_select.da_fairy_lights_effects')}}
```

it would be great if the same functionality will be supported by your addon.
