### ISSUE TITLE
ElectriQ EcoSilent12HPW does not work correctly with electriq_ecosilent14hpw_aircon

### ISSUE THREAD

**Issue by XargsUK** [make-all/tuya-local#3210]
### Description

I'm experiencing an issue with the ElectriQ EcoSilent12HPW air conditioner configuration. When using the existing `electriq_ecosilent14hpw_aircon` configuration (which was [suggested](https://github.com/make-all/tuya-local/pull/3136) as compatible), there are problems with the HVAC mode mappings - specifically when setting to Auto mode and when the device is in smartcool mode. 

> [!NOTE]
> I'm raising this as an issue rather than requesting a new device because the PR for adding the ElectriQ EcoSilent12HPW (#3136) was closed with the comment that the "Device is the same as already supported 14HPW". However, in practice, the configurations have meaningful differences that affect functionality. This issue documents the specific behavioral differences to help improve compatibility.

### Steps to reproduce

1. Configure a new ElectriQ EcoSilent12HPW using the `electriq_ecosilent14hpw_aircon` configuration in Home Assistant
2. Try setting the HVAC mode to "Auto" in the Home Assistant UI
3. Observe that the physical device switches to "Cool" mode instead of "Auto/smartcool"
4. Set the device to "smartcool" mode using the physical controls
5. Observe that Home Assistant reports the state as "unknown"

### Expected behaviour

1. When setting to "Auto" mode in Home Assistant, the device should switch to "smartcool" mode
2. When the device is in "smartcool" mode, Home Assistant should correctly report the state as "Auto"

### Additional context

After analysing both configuration files, I've identified the key differences that explain why my PR configuration works correctly while the existing one doesn't:

1. **Fan mode mapping differences:**

   The 12HPW config in my PR has conditional mappings based on hvac_mode (whether the unit is on or off):

   ```yaml
   - id: 5
     name: fan_mode
     type: string
     mapping:
       - dps_val: "f1"
         constraint: hvac_mode
         conditions:
           - dps_val: false
             value: "off"
           - dps_val: true
             value: low
       # Similar pattern for other fan modes
   ```

While the 14HPW config uses direct mappings without these conditions:

   ```yaml
   - id: 5
     name: fan_mode
     type: string
     mapping:
       - dps_val: "f1"
         value: low
       - dps_val: "f2"
         value: diffuse
       # Direct mappings without constraints
   ```

2. **HVAC mode order differences:**
   - 12HPW: cool, fan, smartcool, dry, heat
   - 14HPW: cool, fan, heat, smartcool, dry

Despite being told that "Device is the same as already supported 14HPW" in the PR comments (https://github.com/make-all/tuya-local/pull/3136), the actual behaviour demonstrates that there are important differences in how the device handles state transitions or reports states.

I suggest either:

1. Merging my dedicated 12HPW configuration which correctly handles the mode mappings, or
2. Updating the 14HPW configuration to include the conditional fan mode mapping and correct mode order to support both device models properly

If you require anything else, feel free to give me a shout! 

### Confirmation

- [ ] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [ ] This is not requesting addition of a new device.
