### ISSUE TITLE
New gas sensor not deteced? (model exos58)

### ISSUE THREAD

**Issue by pergolafabio** [make-all/tuya-local#3259]
### Description

Hi, i bought some gas sensors from ali, while adding them to the integration, i was not able to select an appropriate device? can you help me how todo this?

Here is the image:

![Image](https://github.com/user-attachments/assets/eeed84ad-a85e-48bc-a6ad-a3ec3523aa03)

Here is the output from the API
is this already avaible? or should a new device type be created?
```
{
  "result": {
    "model": "{\"modelId\":\"exos58\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"ro\",\"code\":\"checking_result\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tcl_function_vs2\",\"trigger\":\"direct\"},\"name\":\"设备自检结果\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"checking\",\"check_success\",\"check_failure\",\"others\"]}},{\"abilityId\":2,\"accessMode\":\"ro\",\"code\":\"gas_sensor_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-huoyan\",\"trigger\":\"direct\"},\"name\":\"燃气检测状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"alarm\",\"normal\"]}},{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"alarm_time\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-timer1\"},\"name\":\"报警时长\",\"typeSpec\":{\"type\":\"value\",\"max\":180,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"s\"}},{\"abilityId\":5,\"accessMode\":\"ro\",\"code\":\"gas_sensor_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-jiare1\",\"trigger\":\"direct\"},\"name\":\"燃气检测值\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"LEL\"}},{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"alarm_ringtone\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-yinliang\"},\"name\":\"报警铃声\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\"]}},{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"self_checking\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-yunhang\"},\"name\":\"设备自检\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":10,\"accessMode\":\"ro\",\"code\":\"preheat\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_light2\"},\"name\":\"预热\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":12,\"accessMode\":\"rw\",\"code\":\"alarm_switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power\"},\"name\":\"报警开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":14,\"accessMode\":\"rw\",\"code\":\"muffling\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-Mute\"},\"name\":\"消音\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1747748083535,
  "tid": "30389e4b357f11f0b50a8ad9f66a9c16"
}
```

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [x] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.

**Comment by pergolafabio** [comment]
Here is the out from the log:

```
2025-05-20 15:47:35.950 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding Gas sensor device with product id stqmzk01tbm3qwhg
2025-05-20 15:47:36.123 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device specification:
[{"id": 1, "name": "checking_result", "type": "Enum", "format": "{\"range\":[\"checking\",\"check_success\",\"check_failure\",\"others\"]}", "enumMap": {}}, {"id": 2, "name": "gas_sensor_state", "type": "Enum", "format": "{\"range\":[\"alarm\",\"normal\"]}", "enumMap": {"1": {"code": "gas_sensor_status", "value": "alarm"}, "2": {"code": "gas_sensor_status", "value": "normal"}, "alarm": {"code": "gas_sensor_status", "value": "alarm"}, "normal": {"code": "gas_sensor_status", "value": "normal"}}}, {"id": 3, "name": "alarm_time", "type": "Integer", "format": "{\"unit\":\"s\",\"min\":1,\"max\":180,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 5, "name": "gas_sensor_value", "type": "Integer", "format": "{\"unit\":\"LEL\",\"min\":0,\"max\":1000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 9, "name": "self_checking", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 10, "name": "preheat", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 12, "name": "alarm_switch", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 14, "name": "muffling", "type": "Boolean", "format": "{}", "enumMap": {}}]
2025-05-20 15:47:36.123 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches loratap_curtain_switch_QCSC400ZB-V2 with quality of 22%. DPS: {"updated_at": 1747748851.7123375, "1": "check_success", "2": "normal", "3": 180, "5": 0, "8": "1", "9": false, "10": false, "12": true, "14": false}
2025-05-20 15:47:36.123 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
```

**Comment by pergolafabio** [comment]
ok , tried creating a new device

filename: rq400a_gasalarm.yaml with content below, then restarted HA, added device again, and it matched...
But after the device was added, it has no entities? what am i missing?

![Image](https://github.com/user-attachments/assets/f5a08a91-e00d-4514-8092-4b23673a30e6)



```
name: Gas leak detector
products:
  - id: stqmzk01tbm3qwhg
    model: RQ400A-Update CB2S
entities:
  - entity: binary_sensor
    class: gas
    dps:
      - id: 2
        type: string
        name: sensor
        mapping:
          - dps_val: normal
            value: false
          - dps_val: alarm
            value: true
  - entity: sensor
    name: Gas level
    dps:
      - id: 5
        type: integer
        name: sensor
        unit: "% LEL"
        range:
          min: 1
          max: 1000
        class: measurement
        mapping:
          - scale: 1
  - entity: select
    name: Alarm tone
    icon: "mdi:siren"
    category: config
    dps:
      - id: 8
        type: string
        name: option
        mapping:
          - dps_val: "1"
            value: Alarm 1
          - dps_val: "2"
            value: Alarm 2
          - dps_val: "3"
            value: Alarm 3
          - dps_val: "4"
            value: Alarm 4
          - dps_val: "5"
            value: Alarm 5
  - entity: number
    name: Alarm duration
    category: config
    icon: "mdi:camera-timer"
    dps:
      - id: 3
        type: integer
        name: value
        unit: s
        range:
          min: 1
          max: 180
  - entity: button
    name: Self check
    icon: "mdi:alert-circle-check"
    category: config
    dps:
      - id: 9
        type: boolean
        name: button
  - entity: sensor
    name: Self-check result
    class: enum
    category: diagnostic
    dps:
      - id: 1
        type: string
        name: sensor
        mapping:
          - dps_val: checking
            value: In progress
          - dps_val: check_success
            value: OK
          - dps_val: check_failure
            value: Fail!
          - dps_val: others
            value: Other
  - entity: binary_sensor
    name: Warm up
    class: cold
    category: diagnostic
    dps:
      - id: 10
        type: boolean
        name: sensor
  - entity: switch
    name: Alarm enable
    icon: "mdi:siren"
    category: config
    dps:
      - id: 12
        type: boolean
        name: switch
  - entity: switch
    name: Mute
    icon: "mdi:volume-mute"
    category: config
    dps:
      - id: 14
        type: boolean
        name: switch
```
