### ISSUE TITLE
PG107 Trigger and Message+Alarm Sensor

### ISSUE THREAD

**Issue by Daniel-Vitanza** [make-all/tuya-local#3272]
### Description

Hello,

I use your integration for 2 years for my home alarm PG107 (gautone or pgst brand).
At each update, I have to modify a couple of things in your code to have all functions working and last updade with depreciated code gave me even more pain. Not your fault ;) So many different devices to configure.

All in all, could we discuss how to implement my modifications to get the code working in the long-term for everyone with PG107 ?

Modifications:

**1. Add trigger button possibility to the alarm.**
 **Goal:** Configure an "SOS" button to trigger the alarm from homeassistant. Below you can see how it works in my dashboard with the yaml code.
![Image](https://github.com/user-attachments/assets/a5f3ba40-15f3-4cd7-9de1-778b30e38a8b)

![Image](https://github.com/user-attachments/assets/1b555c6d-ab71-4dcc-a64b-2690d18d15ce)

**How:** I added these lines into "alarm_control_panel.py".

```
if AlarmControlPanelState.TRIGGERED in alarm_states:
            self._attr_supported_features |= Feature.TRIGGER
```

**2. Add alarm message and alarm state with a sensor.**
**Goal:** Be able to check the actual states of the alarm: alarm, message and power

![Image](https://github.com/user-attachments/assets/15737cf9-ed6c-4605-9a68-104ff3f32fde)

**How:** Your last code provides an event for the alarm state. It does not work. And the alarm message is also not found. Here is the code that always works for me:

```
  - entity: sensor
    name: Alarm
    category: diagnostic
    dps:
      - id: 32
        type: string
        name: sensor
        optional: true
  - entity: sensor
    name: Alarm message
    category: diagnostic
    dps:
      - id: 26
        type: utf16b64
        name: sensor
        optional: true
  - entity: sensor
    name: Power
    category: diagnostic
    dps:
      - id: 101
        type: string
        name: sensor
        optional: true
```

### Steps to reproduce

__

### Expected behaviour

A long-term solution to avoid modifying your code after each update.
Maybe the easiest solution is to create a new device dedicated to PG107. I don't have PG103 to check if my modifications can be used with them too.

### Additional context

Gautone PG103 device for the configuration.

In reality, this is a Gautone/PGST PG107.

### Confirmation

- [x] I am sure this is a bug or improvement, that is well enough described that it can be implemented.
- [x] This report is for tuya-local, **not** for localtuya.
- [x] If this is for a specific device, the device config is mentioned above, or diagnostics are included.

- [ ] Log messages or diagnostics relevant to the issue are included.

- [x] This is not requesting addition of a new device.
