### ISSUE TITLE
Request support for LSC Power Strip

### ISSUE THREAD

**Issue by josvink66** [make-all/tuya-local#3291]
### Log message

```text
Device specification: [{"id": 1, "name": "switch_1", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 2, "name": "switch_2", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 3, "name": "switch_3", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 9, "name": "countdown_1", "type": "Integer", "format": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 10, "name": "countdown_2", "type": "Integer", "format": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 11, "name": "countdown_3", "type": "Integer", "format": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 17, "name": "add_ele", "type": "Integer", "format": "{\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}", "enumMap": {}}, {"id": 18, "name": "cur_current", "type": "Integer", "format": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 19, "name": "cur_power", "type": "Integer", "format": "{\"unit\":\"W\",\"min\":0,\"max\":80000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 20, "name": "cur_voltage", "type": "Integer", "format": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}", "enumMap": {}}, {"id": 38, "name": "relay_status", "type": "Enum", "format": "{\"range\":[\"power_off\",\"power_on\",\"last\"]}", "enumMap": {"0": {"code": "relay_status", "value": "power_off"}, "1": {"code": "relay_status", "value": "power_on"}, "2": {"code": "relay_status", "value": "last"}, "memory": {"code": "relay_status", "value": "last"}, "off": {"code": "relay_status", "value": "power_off"}, "on": {"code": "relay_status", "value": "power_on"}}}, {"id": 40, "name": "light_mode", "type": "Enum", "format": "{\"range\":[\"relay\",\"pos\",\"none\"]}", "enumMap": {}}, {"id": 41, "name": "child_lock", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 42, "name": "cycle_time", "type": "String", "format": "{}", "enumMap": {}}, {"id": 43, "name": "random_time", "type": "String", "format": "{}", "enumMap": {}}, {"id": 44, "name": "switch_inching", "type": "String", "format": "{}", "enumMap": {}}]
```

### Product ID

haay5f2zrjedat8z

### Product Name

LSC Power Strip

### DPS information

```text
{
  "result": {
    "model": "{\"modelId\":\"e1kirr2o\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"656\"},\"name\":\"开关1\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"switch_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"656\"},\"name\":\"开关2\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"switch_3\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"656\"},\"name\":\"开关3\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":9,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"736\"},\"name\":\"开关1倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},
{\"abilityId\":10,\"accessMode\":\"rw\",\"code\":\"countdown_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"736\"},\"name\":\"开关2倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},
{\"abilityId\":11,\"accessMode\":\"rw\",\"code\":\"countdown_3\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"736\"},\"name\":\"开关3倒计时\",\"typeSpec\":{\"type\":\"value\",\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"s\"}},
{\"abilityId\":17,\"accessMode\":\"ro\",\"code\":\"add_ele\",\"description\":\"\",\"extensions\":{\"attribute\":\"704\"},\"name\":\"增加电量\",\"typeSpec\":{\"type\":\"value\",\"max\":50000,\"min\":0,\"scale\":3,\"step\":100}},
{\"abilityId\":18,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"extensions\":{\"attribute\":\"704\"},\"name\":\"当前电流\",\"typeSpec\":{\"type\":\"value\",\"max\":30000,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"mA\"}},
{\"abilityId\":19,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"extensions\":{\"attribute\":\"704\"},\"name\":\"当前功率\",\"typeSpec\":{\"type\":\"value\",\"max\":80000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"W\"}},
{\"abilityId\":20,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"extensions\":{\"attribute\":\"704\"},\"name\":\"当前电压\",\"typeSpec\":{\"type\":\"value\",\"max\":5000,\"min\":0,\"scale\":1,\"step\":1,\"unit\":\"V\"}},
{\"abilityId\":21,\"accessMode\":\"ro\",\"code\":\"test_bit\",\"description\":\"\",\"extensions\":{\"attribute\":\"736\"},\"name\":\"产测结果位\",\"typeSpec\":{\"type\":\"value\",\"max\":5,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":22,\"accessMode\":\"ro\",\"code\":\"voltage_coe\",\"description\":\"\",\"extensions\":{\"attribute\":\"736\"},\"name\":\"电压校准系数\",\"typeSpec\":{\"type\":\"value\",\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":23,\"accessMode\":\"ro\",\"code\":\"electric_coe\",\"description\":\"\",\"extensions\":{\"attribute\":\"736\"},\"name\":\"电流校准系数\",\"typeSpec\":{\"type\":\"value\",\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"power_coe\",\"description\":\"\",\"extensions\":{\"attribute\":\"736\"},\"name\":\"功率校准系数\",\"typeSpec\":{\"type\":\"value\",\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":25,\"accessMode\":\"ro\",\"code\":\"electricity_coe\",\"description\":\"\",\"extensions\":{\"attribute\":\"736\"},\"name\":\"电量校准系数\",\"typeSpec\":{\"type\":\"value\",\"max\":1000000,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":26,\"accessMode\":\"ro\",\"code\":\"fault\",\"description\":\"\",\"extensions\":{\"attribute\":\"640\"},\"name\":\"故障告警\",\"typeSpec\":{\"type\":\"bitmap\",\"label\":[\"ov_cr\",\"ov_vol\",\"ov_pwr\",\"ls_cr\",\"ls_vol\",\"ls_pow\"],\"maxlen\":6}},
{\"abilityId\":38,\"accessMode\":\"rw\",\"code\":\"relay_status\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-zhuangtai\",\"attribute\":\"736\"},\"name\":\"上电状态设置\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"off\",\"on\",\"memory\"]}},
{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"light_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"tcl_function_light\",\"attribute\":\"224\"},\"name\":\"指示灯状态设置\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"relay\",\"pos\",\"none\",\"on\"]}},
{\"abilityId\":41,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"128\"},\"name\":\"童锁开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":42,\"accessMode\":\"rw\",\"code\":\"cycle_time\",\"description\":\"最大10个定时功能: 每10个字节代表；\\n/#1通道号（bit0--开关，bit7-bit1---通道号）；\\n/#2星期；\\n/#3#4起始时间(min)；\\n/#5#6结束时间(min)；\\n/#7#8开启时间(min)；\\n/#9#10关闭时间(min)；\",\"extensions\":{\"iconName\":\"icon-dp_time3\",\"attribute\":\"224\"},\"name\":\"循环定时\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":43,\"accessMode\":\"rw\",\"code\":\"random_time\",\"description\":\"最大16个定时功能：每6个字节代表；\\n/#1通道号（bit0--开关，bit7-bit1---通道号----排插位数0-6）；\\n/#2星期；\\n/#3#4起始时间(min)；\\n/#5#6结束时间(min)；\",\"extensions\":{\"iconName\":\"icon-dp_time2\",\"attribute\":\"224\"},\"name\":\"随机定时\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":44,\"accessMode\":\"rw\",\"code\":\"switch_inching\",\"description\":\"/#1控制（bit0--开关，bit7-bit1---通道号）；\\n/#2#3点动倒计时时间（s）；\",\"extensions\":{\"attribute\":\"240\"},\"name\":\"点动开关\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}}]}]}"
  },
  "success": true,
  "t": 1748536845997,
  "tid": "ab44eec33cab11f0b7363af2f1e8cfff"
}
```

### Information about how the device functions

It appears to be functionally identical to the dual_power_monitor_smartplugv2.yaml, but with support for three outlets instead of two. I've already created the YAML file, so it likely just needs to be reviewed before it can be added.

```
name: Triple smartplug
products:
  - id: haay5f2zrjedat8z
    manufacturer: LSC Power Strip
    model: e1kirr2o

entities:
  - entity: switch
    translation_key: outlet_x
    translation_placeholders:
      x: "1"
    class: outlet
    dps:
      - id: 1
        type: boolean
        name: switch
      - id: 17
        type: integer
        name: add_ele
        optional: true
      - id: 25
        type: integer
        name: ele_calibration
        optional: true
      - id: 42
        type: string
        name: schedule
        optional: true
      - id: 43
        type: string
        optional: true
        name: random_schedule
      - id: 44
        type: string
        optional: true
        name: inching

  - entity: switch
    translation_key: outlet_x
    translation_placeholders:
      x: "2"
    class: outlet
    dps:
      - id: 2
        type: boolean
        name: switch

  - entity: switch
    translation_key: outlet_x
    translation_placeholders:
      x: "3"
    class: outlet
    dps:
      - id: 3
        type: boolean
        name: switch

  - entity: number
    category: config
    translation_key: timer_x
    translation_placeholders:
      x: "1"
    class: duration
    dps:
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60

  - entity: number
    category: config
    translation_key: timer_x
    translation_placeholders:
      x: "2"
    class: duration
    dps:
      - id: 10
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60

  - entity: number
    category: config
    translation_key: timer_x
    translation_placeholders:
      x: "3"
    class: duration
    dps:
      - id: 11
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60

  - entity: sensor
    class: current
    category: diagnostic
    dps:
      - id: 18
        type: integer
        name: sensor
        unit: mA
        class: measurement

  - entity: sensor
    class: power
    category: diagnostic
    dps:
      - id: 19
        type: integer
        name: sensor
        unit: W
        class: measurement
        mapping:
          - scale: 10

  - entity: sensor
    class: voltage
    category: diagnostic
    dps:
      - id: 20
        type: integer
        name: sensor
        unit: V
        class: measurement
        mapping:
          - scale: 10

  - entity: sensor
    class: energy
    category: diagnostic
    dps:
      - id: 17
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 1000

  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 26
        type: bitfield
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
          - dps_val: 0
            value: false
          - value: true
      - id: 26
        type: bitfield
        name: fault_code
        optional: true

  - entity: select
    translation_key: initial_state
    category: config
    dps:
      - id: 38
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "on"
            value: "on"
          - dps_val: "off"
            value: "off"
          - dps_val: memory
            value: memory
          - dps_val: null
            invalid: true

  - entity: select
    name: Light mode
    icon: "mdi:circle-double"
    category: config
    hidden: unavailable
    dps:
      - id: 40
        type: string
        optional: true
        name: available
        mapping:
          - dps_val: null
            value: false
          - value: true
      - id: 40
        type: string
        optional: true
        name: option
        mapping:
          - dps_val: relay
            value: State
          - dps_val: pos
            value: Position
          - dps_val: none
            value: "Off"
          - dps_val: "on"
            value: "On"

  - entity: lock
    translation_key: child_lock
    category: config
    dps:
      - id: 41
        type: boolean
        name: lock
        optional: true
        mapping:
          - dps_val: null
            invalid: true
```
