### ISSUE TITLE
Float type doesn't work?

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#335]
I use the following config:
```yaml
  - entity: select
    name: Lamp Type
    dps:
      - id: 102
        type: float
        name: option
        optional: true
        mapping:
          - dps_val: 0.00
            value: Light Strip
          - dps_val: 0.10
            value: Light Post 
```
but with such config I am not able to add the device:
`DPS: {'updated_at': 1672857526.2358646, '20': False, '22': 1000, '24': '001900190100', '25': '82000000000000000000000000000000', '101': 0, '102': 0}`

I tried to replace `dps_val: 0.00` with `dps_val: 0.10`, but it doesn't help.

But if I replace the type with `integer`, it works (device is found, but the value is not sent, of course)
