### ISSUE TITLE
Add documentation about color modes

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#337]
Could you please create a document / wiki article about color modes? 

```
- id: 21
      type: string
      name: color_mode
      mapping:
        - dps_val: colour
          value: rgbw
```

How HA treats each value (white, rgbw, colorloop, random) added there?

If I add some color mode here, do I need to add something else to my yaml? For ex, dps with brightness?
