### ISSUE TITLE
Possibility to add user-configured devices

### ISSUE THREAD

**Issue by and7ey** [make-all/tuya-local#340]
It would be great to make it possible to define a folder, where configs for user-added devices will be stored.

For ex., you say there https://github.com/make-all/tuya-local/issues/264 that device works unstable and don't want it to add it to your repo. But I believe that it works perfectly. If I add the yaml to standard `custom_components/tuya-local/device` folder, then it will deleted with the addon redownload (and most probably - with addon update). 

If there will be an option to keep yaml files in some additional folder, then it will help a lot. 

(you may consider even `configuration.yaml`)

Just choose the simplest solution for conflicts resolution. For ex., if 2 files exist with the same name in 2 folders, then choose the addon original folder.

**Comment by make-all** [comment]
It isn't the aim of this project to provide a DIY platform for users to tinker with.  localtuya already fills that niche.

**Comment by and7ey** [comment]
Just in case somebody will be looking for the solution:

1. create folder `tuya_local_devices` inside your `config` folder
2. place your custom yaml files at this folder
3. add to your `configuration.yaml`:
```yaml
shell_command:
  copy_devices_to_tuya_local: 'cp -f /config/tuya_local_devices/*.* /config/custom_components/tuya_local/devices/'
```
4. add the following Automation:
```yaml
- id: copy_devices_to_tuya_local
  alias: Copy local device to Tuya Local at HA start
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.copy_devices_to_tuya_local
  mode: single
```
