### ISSUE TITLE
Request support for Zemismart 3 Phase Energy Meter SPM02_WiFi_V2

### ISSUE THREAD

**Issue by JuroZeStupavy** [make-all/tuya-local#3414]
### Log message

```text
2025-06-25 08:33:23.157 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding Metering_3PN_WiFi device with product id kxdr6su0c55p7bbo
2025-06-25 08:33:23.415 WARNING (MainThread) [custom_components.tuya_local.config_flow] Unable to fetch data model from cloud: network error:(-9999999) sign invalid
2025-06-25 08:33:23.416 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches inkbird_ipt2ch_thermostat with quality of 56%. DPS: {"updated_at": 1750833183.6561708, "1": 394438, "9": 0, "19": "SPM02_8445", "23": 0, "29": 208, "32": 4997, "50": 46, "102": 2361, "103": 632, "104": 66, "105": 2364, "106": 581, "107": 56, "108": 2357, "109": 710, "110": 86}
2025-06-25 08:33:23.417 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
```

### Product ID

kxdr6su0c55p7bbo

### Product Name

Zemismart SPM02_WiFi_V2

### DPS information

```text
{
  "result": {
    "properties": [
      {
        "code": "forward_energy_total",
        "custom_name": "",
        "dp_id": 1,
        "time": 1750833763793,
        "type": "value",
        "value": 394444
      },
      {
        "code": "phase_a",
        "custom_name": "",
        "dp_id": 6,
        "time": 1750833854472,
        "type": "raw",
        "value": "CT0AAoMAAEI="
      },
      {
        "code": "phase_b",
        "custom_name": "",
        "dp_id": 7,
        "time": 1750833854710,
        "type": "raw",
        "value": "CT4AAkcAADg="
      },
      {
        "code": "phase_c",
        "custom_name": "",
        "dp_id": 8,
        "time": 1750833854773,
        "type": "raw",
        "value": "CTkAA4kAAKE="
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 9,
        "time": 1748864290357,
        "type": "bitmap",
        "value": 0
      },
      {
        "code": "clear_energy",
        "custom_name": "",
        "dp_id": 12,
        "time": 1735215813765,
        "type": "bool",
        "value": false
      },
      {
        "code": "alarm_set_1",
        "custom_name": "",
        "dp_id": 17,
        "time": 1750694296760,
        "type": "raw",
        "value": "BwEADQ=="
      },
      {
        "code": "alarm_set_2",
        "custom_name": "",
        "dp_id": 18,
        "time": 1750694296957,
        "type": "raw",
        "value": "AQEAPAMBAP0EAAC0BQAAAAcBAAAIAQAeCQAAAA=="
      },
      {
        "code": "breaker_id",
        "custom_name": "",
        "dp_id": 19,
        "time": 1748864290357,
        "type": "string",
        "value": "SPM02_8445"
      },
      {
        "code": "reverse_energy_total",
        "custom_name": "",
        "dp_id": 23,
        "time": 1750833854461,
        "type": "value",
        "value": 0
      },
      {
        "code": "active_power",
        "custom_name": "",
        "dp_id": 29,
        "time": 1750833854925,
        "type": "value",
        "value": 284
      },
      {
        "code": "supply_frequency",
        "custom_name": "",
        "dp_id": 32,
        "time": 1750833854912,
        "type": "value",
        "value": 5001
      },
      {
        "code": "online_state",
        "custom_name": "",
        "dp_id": 35,
        "time": 1735636613728,
        "type": "enum",
        "value": "online"
      },
      {
        "code": "power_factor",
        "custom_name": "",
        "dp_id": 50,
        "time": 1750833854938,
        "type": "value",
        "value": 57
      },
      {
        "code": "cur_voltage_x",
        "custom_name": "",
        "dp_id": 102,
        "time": 1750833854951,
        "type": "value",
        "value": 2365
      },
      {
        "code": "cur_current_x",
        "custom_name": "",
        "dp_id": 103,
        "time": 1750833854963,
        "type": "value",
        "value": 631
      },
      {
        "code": "cur_power_x",
        "custom_name": "",
        "dp_id": 104,
        "time": 1750833854976,
        "type": "value",
        "value": 66
      },
      {
        "code": "cur_voltage_y",
        "custom_name": "",
        "dp_id": 105,
        "time": 1750833854986,
        "type": "value",
        "value": 2366
      },
      {
        "code": "cur_current_y",
        "custom_name": "",
        "dp_id": 106,
        "time": 1750833855015,
        "type": "value",
        "value": 583
      },
      {
        "code": "cur_power_y",
        "custom_name": "",
        "dp_id": 107,
        "time": 1750833857023,
        "type": "value",
        "value": 56
      },
      {
        "code": "cur_voltage_z",
        "custom_name": "",
        "dp_id": 108,
        "time": 1750833855050,
        "type": "value",
        "value": 2361
      },
      {
        "code": "cur_current_z",
        "custom_name": "",
        "dp_id": 109,
        "time": 1750833824779,
        "type": "value",
        "value": 905
      },
      {
        "code": "cur_power_z",
        "custom_name": "",
        "dp_id": 110,
        "time": 1750833855063,
        "type": "value",
        "value": 161
      }
    ]
  },
  "success": true,
  "t": 1750833882931,
  "tid": "dfffce6b518f11f0b492d6238a027bdd"
}

{
  "result": [
    {
      "active_time": 1735215813,
      "bind_space_id": "73234335",
      "category": "dlq",
      "create_time": 1735215813,
      "custom_name": "",
      "icon": "smart/icon/ay1553162414592ZG6Kk/b8b318e89a8c5c6267bd274678e09505.png",
      "id": "bf446af3b5f07c8b02ro2m",
      "ip": "",
      "is_online": true,
      "lat": "",
      "local_key": "",
      "lon": "",
      "model": "",
      "name": "Metering_3PN_WiFi",
      "product_id": "kxdr6su0c55p7bbo",
      "product_name": "SPM02_WiFi_V2",
      "sub": false,
      "time_zone": "+01:00",
      "update_time": 1745179009,
      "uuid": "7ed222c9ca0f73b8"
    }
  ],
  "success": true,
  "t": 1750833816761,
  "tid": "b88457b6518f11f0bc424a7a32184703"
}
```

### Information about how the device functions

3 Phase Electric Energy Meter

https://www.zemismart.com/products/spm02-d2tz?srsltid=AfmBOopjtOFt4Ou0GaodfDhFZlFDPeYx-TUvUJLnXt4P6oEBjR2J-Zkv

**Comment by Alaskamsk** [comment]
Same problem. I suspect it's a Chinese version of SPM02_WiFi with a different Product ID (kxdr6su0c55p7bbo). After updating to Version 2025.11.2, the problem persists, even though SPM02_WiFi support is advertised starting with that version. I've attached a screenshot.

![Image](https://github.com/user-attachments/assets/be6c8946-0f72-439b-9d27-5b770f1ec28b)

**Comment by make-all** [comment]
Unfortunately the dps info is not detailed enough to work with

**Comment by weinhaeupl1** [comment]
i do use the same device and i'm facing the same error..... what do we need to provide to get a proper support for this device.

i would like to help here

**Comment by make-all** [comment]
It needs results of the Query Things Data Model tuya cloud API call, which will show all the available info about all the dps. Currently available data is missing most importantly ranges for numeric and enum dps, but also more detailed descriptions (even if only in Chinese) that might give some hint about the format of the raw dps.

**Comment by dhiru1602** [comment]
I bought the same device from AliExpress, and unfortunately it looks like it’s a clone of the real SPM02. After logging the DPS and checking values in the Tuya app, I managed to put together a working YAML config for it. You can try the config below and see if it works for your device. I’m not sure what the project’s stance is on supporting clone hardware, so I’m unsure whether it makes sense to submit a PR for this.

<img width="1067" height="836" alt="Image" src="https://github.com/user-attachments/assets/ba0d2309-bd39-4f60-83b6-c770be807dee" />


```
name: SPM02 WiFi V2

products:
  - id: kxdr6su0c55p7bbo
    name: SPM02_WiFi_V2
    manufacturer: Zemismart
    model_id: SPM02-D2TW
    model: 3-Phase Energy Meter

entities:
  # --------------------
  # Total energy consumed
  # --------------------
  - entity: sensor
    translation_key: energy_consumed
    class: energy
    dps:
      - id: 1
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 100

  # --------------------
  # Total energy produced
  # --------------------
  - entity: sensor
    translation_key: energy_produced
    class: energy
    dps:
      - id: 23
        type: integer
        name: sensor
        unit: kWh
        class: total_increasing
        mapping:
          - scale: 100

  # --------------------
  # Total active power
  # --------------------
  - entity: sensor
    class: power
    dps:
      - id: 29
        name: sensor
        unit: W
        class: measurement
        type: integer

  # --------------------
  # Phase L1
  # --------------------
  - entity: sensor
    translation_key: voltage_x
    translation_placeholders:
      x: L1
    class: voltage
    dps:
      - id: 102
        name: sensor
        unit: V
        class: measurement
        type: integer
        mapping:
          - scale: 10

  - entity: sensor
    translation_key: current_x
    translation_placeholders:
      x: L1
    class: current
    dps:
      - id: 103
        name: sensor
        unit: A
        class: measurement
        type: integer
        mapping:
          - scale: 1000

  - entity: sensor
    translation_key: power_x
    translation_placeholders:
      x: L1
    class: power
    dps:
      - id: 104
        name: sensor
        unit: W
        class: measurement
        type: integer

  # --------------------
  # Phase L2
  # --------------------
  - entity: sensor
    translation_key: voltage_x
    translation_placeholders:
      x: L2
    class: voltage
    dps:
      - id: 105
        name: sensor
        unit: V
        class: measurement
        type: integer
        mapping:
          - scale: 10

  - entity: sensor
    translation_key: current_x
    translation_placeholders:
      x: L2
    class: current
    dps:
      - id: 106
        name: sensor
        unit: A
        class: measurement
        type: integer
        mapping:
          - scale: 1000

  - entity: sensor
    translation_key: power_x
    translation_placeholders:
      x: L2
    class: power
    dps:
      - id: 107
        name: sensor
        unit: W
        class: measurement
        type: integer

  # --------------------
  # Phase L3
  # --------------------
  - entity: sensor
    translation_key: voltage_x
    translation_placeholders:
      x: L3
    class: voltage
    dps:
      - id: 108
        name: sensor
        unit: V
        class: measurement
        type: integer
        mapping:
          - scale: 10

  - entity: sensor
    translation_key: current_x
    translation_placeholders:
      x: L3
    class: current
    dps:
      - id: 109
        name: sensor
        unit: A
        class: measurement
        type: integer
        mapping:
          - scale: 1000

  - entity: sensor
    translation_key: power_x
    translation_placeholders:
      x: L3
    class: power
    dps:
      - id: 110
        name: sensor
        unit: W
        class: measurement
        type: integer

  # --------------------
  # Power factor (unitless ratio 0–1)
  # --------------------
  - entity: sensor
    class: power_factor
    dps:
      - id: 50
        name: sensor
        type: integer
        class: measurement
        mapping:
          - scale: 100

  # --------------------
  # Frequency
  # --------------------
  - entity: sensor
    class: frequency
    dps:
      - id: 32
        name: sensor
        unit: Hz
        class: measurement
        type: integer
        mapping:
          - scale: 100

  # --------------------
  # Fault status
  # --------------------
  - entity: binary_sensor
    class: problem
    category: diagnostic
    dps:
      - id: 9
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true

  # --------------------
  # Breaker ID (diagnostic)
  # --------------------
  - entity: sensor
    name: Breaker ID
    category: diagnostic
    dps:
      - id: 19
        type: string
        name: sensor
```
