### ISSUE TITLE
Request support for Chanfok Ceiling Fan (mild difference to existing supported fan?)

### ISSUE THREAD

**Issue by vincedarley** [make-all/tuya-local#3417]
### Log message

```text
2025-06-26 14:10:44.733 WARNING (MainThread) [custom_components.tuya_local.config_flow] Adding Chanfok Ceiling Fan device with product id yos17rcreaqlpi5i
2025-06-26 14:10:44.795 WARNING (MainThread) [custom_components.tuya_local.config_flow] Cloud device spec:
[{"id": 20, "name": "switch_led", "type": "Boolean", "format": "{}", "enumMap": {}}, {"id": 21, "name": "work_mode", "type": "Enum", "format": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}", "enumMap": {}}, {"id": 22, "name": "bright_value", "type": "Integer", "format": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 23, "name": "temp_value", "type": "Integer", "format": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}", "enumMap": {}}, {"id": 53, "name": "switch_night_light", "type": "Boolean", "format": "{}", "enumMap": {}}]
2025-06-26 14:10:44.795 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches marpou_ceiling_lamp_ledlight with quality of 40%. DPS: {"updated_at": 1750943442.8344378, "20": true, "21": "white", "22": 495, "23": 1000, "53": false, "101": false, "104": "forward", "105": 1, "106": "fresh", "107": false}
2025-06-26 14:10:44.795 WARNING (MainThread) [custom_components.tuya_local.config_flow] Include the previous log messages with any new device request to https://github.com/make-all/tuya-local/issues/
```

### Product ID

yos17rcreaqlpi5i

### Product Name

Chanfok Ceiling Fan

### DPS information

```text
Here's the result from QueryThingsDataModel:

{
  "result": {
    "model": "{\"modelId\":\"e1koidqc\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"\",\"properties\":[
{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"switch_led\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power\",\"attribute\":\"1665\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":21,\"accessMode\":\"rw\",\"code\":\"work_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1664\"},\"name\":\"模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}},
{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"bright_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-liangdu1\",\"attribute\":\"1664\"},\"name\":\"亮度值\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":10,\"scale\":0,\"step\":1}},
{\"abilityId\":23,\"accessMode\":\"rw\",\"code\":\"temp_value\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_half\",\"attribute\":\"1664\"},\"name\":\"冷暖值\",\"typeSpec\":{\"type\":\"value\",\"max\":1000,\"min\":0,\"scale\":0,\"step\":1}},
{\"abilityId\":28,\"accessMode\":\"wr\",\"code\":\"control_data\",\"description\":\"用于实现调光调色的实时调节。\",\"extensions\":{\"iconName\":\"icon-dp_box2\",\"attribute\":\"1664\"},\"name\":\"调节\",\"typeSpec\":{\"type\":\"string\",\"maxlen\":255}},
{\"abilityId\":53,\"accessMode\":\"rw\",\"code\":\"switch_night_light\",\"description\":\"设置独立夜灯，亮度超低，满足用户夜晚使用，又不会干扰到其他人正常睡眠的需求\",\"extensions\":{\"iconName\":\"icon-a_power\",\"attribute\":\"1152\"},\"name\":\"夜灯开关\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"fan_beep\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_voice\",\"attribute\":\"4096\"},\"name\":\"声音\",\"typeSpec\":{\"type\":\"bool\"}},
{\"abilityId\":104,\"accessMode\":\"rw\",\"code\":\"fan_direction\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"4096\"},\"name\":\"风向\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"forward\",\"reverse\"]}},
{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-FanSpeed\",\"attribute\":\"4096\"},\"name\":\"风扇速度\",\"typeSpec\":{\"type\":\"value\",\"max\":6,\"min\":1,\"scale\":0,\"step\":1,\"unit\":\"\"}},
{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"fan_mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_mode_fan\",\"attribute\":\"4096\"},\"name\":\"风类\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"fresh\",\"nature\"]}},
{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"fan_switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power2\",\"attribute\":\"4096\"},\"name\":\"风扇开关\",\"typeSpec\":{\"type\":\"bool\"}}]}]}"
  },
  "success": true,
  "t": 1750946702413,
  "tid": "8d9e0626529611f0b492d6238a027bdd"
}
```

### Information about how the device functions

Note that there already seems to be a "Chanfok Smart Ceiling Fan" supported: https://github.com/make-all/tuya-local/issues/546

But mine is not recognised as that fan.  I notice that mine calls itself "Chanfok Ceiling Fan", so perhaps a subtle model change?

The UI in Tuya Smart for my fan is as follows:
Fan Switch: off/on
Speed: 1...6 (slider)
Once the fan is on, you have two toggles:
Direction: Forward vs Reverse
Mode: Fresh vs Nature

Lamp Switch: off/on
Brightness: 1...100% (slider)
Temperature 0...100% (0=very warm, 100=very cold white light)
Night Light ON/OFF (seems to turn the light on with a specific warmth and brightness, although the UI is a bit confused).

**Comment by vincedarley** [comment]
Here is the result of Query Properties:

```
{
  "result": {
    "properties": [
      {
        "code": "switch_led",
        "custom_name": "",
        "dp_id": 20,
        "time": 1750947307355,
        "type": "bool",
        "value": false
      },
      {
        "code": "work_mode",
        "custom_name": "",
        "dp_id": 21,
        "time": 1750946866351,
        "type": "enum",
        "value": "white"
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 22,
        "time": 1750946997822,
        "type": "value",
        "value": 303
      },
      {
        "code": "temp_value",
        "custom_name": "",
        "dp_id": 23,
        "time": 1750946943194,
        "type": "value",
        "value": 1000
      },
      {
        "code": "control_data",
        "custom_name": "",
        "dp_id": 28,
        "time": 1750942663551,
        "type": "string",
        "value": ""
      },
      {
        "code": "switch_night_light",
        "custom_name": "",
        "dp_id": 53,
        "time": 1750947307355,
        "type": "bool",
        "value": false
      },
      {
        "code": "fan_beep",
        "custom_name": "",
        "dp_id": 101,
        "time": 1750946974259,
        "type": "bool",
        "value": false
      },
      {
        "code": "fan_direction",
        "custom_name": "",
        "dp_id": 104,
        "time": 1750947071216,
        "type": "enum",
        "value": "reverse"
      },
      {
        "code": "fan_speed",
        "custom_name": "",
        "dp_id": 105,
        "time": 1750947071216,
        "type": "value",
        "value": 1
      },
      {
        "code": "fan_mode",
        "custom_name": "",
        "dp_id": 106,
        "time": 1750947079384,
        "type": "enum",
        "value": "fresh"
      },
      {
        "code": "fan_switch",
        "custom_name": "",
        "dp_id": 107,
        "time": 1750947300321,
        "type": "bool",
        "value": false
      }
    ]
  },
  "success": true,
  "t": 1750947334436,
  "tid": "065c0ac5529811f0884d66005ac75605"
}
```

**Comment by RJPottsUK** [comment]
Thank-you to the OP for this.  I found this thread soon after installing Tuya Local as the fan \ light only has the light entities in the Tuya (Cloud) integration. Being new to Tuya Local I was scratching my head trying to figure out why it gave me a list of unrelated device types to choose from when trying to add.

**Comment by RJPottsUK** [comment]
The following, placed in a file called "Ceiling_Fan.yaml", in custom_components\tuya_local\devices\ worked for me;

```
name: Ceiling fan
products:
  - id: tvtzgei8bgaezsvi
    manufacturer: Chanfok
    name: JST-DC-WYfen
entities:
  - entity: fan
    translation_only_key: fan_with_presets
    dps:
      - id: 107
        type: boolean
        name: switch
      - id: 106
        type: string
        name: preset_mode
        mapping:
          - dps_val: fresh
            value: fresh
          - dps_val: nature
            value: nature
      - id: 105
        type: integer
        name: speed
        range:
          min: 1
          max: 6
      - id: 104
        type: string
        name: direction
      - id: 101
        type: boolean
        name: unknown_101
        optional: true
  - entity: light
    dps:
      - id: 20
        type: boolean
        name: switch
      - id: 21
        name: work_mode
        type: string
        optional: true
      - id: 22
        name: brightness
        type: integer
        range:
          min: 10
          max: 1000
      - id: 23
        name: color_temp
        type: integer
        range:
          min: 0
          max: 1000
        mapping:
          - target_range:
              min: 2700
              max: 6500
      - id: 28
        name: control_data
        type: string
        optional: true
  - entity: switch
    name: Beep
    icon: "mdi:bell"
    category: config
    dps:
      - id: 101
        type: boolean
        name: switch
```
