### ISSUE TITLE
Request support for BHT-12 Smart Thermostat

### ISSUE THREAD

**Issue by happy-daisy** [make-all/tuya-local#3420]
### Log message

```text
Local Logs:
Device matches lucci_fan with quality of 19%. DPS: {"updated_at": 1750974394.812378, "1": false, "2": "manual", "4": false, "16": 190, "17": 41, "19": 350, "23": "c", "24": 165, "26": 50, "36": "close", "40": false, "101": 60, "102": true, "104": 0, "105": 200, "107": 260}
```

### Product ID

"productKey": "kw2kh2jfzxaej5tb"

### Product Name

BHT-12 Smart Thermostat

### DPS information

```text
"model": "{\"modelId\":\"000004mf2n\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power3\",\"attribute\":\"1024\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"工作模式\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"auto\",\"manual\",\"temphold\",\"holidays\"]}},{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"eco\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_function_eco\",\"attribute\":\"1024\"},\"name\":\"ECO模式\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"attribute\":\"1024\"},\"name\":\"目标温度\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":50,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"temp_set_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"目标温度_F\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":41,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"upper_temp_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"设置温度上限-℉\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":77,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"upper_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1024\"},\"name\":\"设置温度上限\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":250,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"lower_temp_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"设置温度下限-℉\",\"typeSpec\":{\"type\":\"value\",\"max\":77,\"min\":41,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":23,\"accessMode\":\"rw\",\"code\":\"temp_unit_convert\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1024\"},\"name\":\"温标切换\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"c\",\"f\"]}},{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu\",\"attribute\":\"1024\"},\"name\":\"当前温度\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":0,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"lower_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1024\"},\"name\":\"设置温度下限\",\"typeSpec\":{\"type\":\"value\",\"max\":250,\"min\":50,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":29,\"accessMode\":\"ro\",\"code\":\"temp_current_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"当前温度_F\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":32,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":36,\"accessMode\":\"ro\",\"code\":\"valve_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tcl_function_vs2\",\"attribute\":\"1024\"},\"name\":\"阀门状态\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"open\",\"close\"]}},{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1024\"},\"name\":\"童锁\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":71,\"accessMode\":\"rw\",\"code\":\"week_program_4\",\"description\":\"周程序4\",\"name\":\"周程序4\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"holiday_days_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"4096\"},\"name\":\"假日模式天数设置\",\"typeSpec\":{\"type\":\"value\",\"max\":99,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"day\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"cold_hot_set\",\"description\":\"\",\"name\":\"冷/热\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"floor_temp_f\",\"description\":\"\",\"name\":\"地板温度-°F\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":32,\"scale\":0,\"step\":1,\"unit\":\"°F\"}},{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"floor_temp\",\"description\":\"\",\"name\":\"地板温度\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":0,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"eco_heat_temp\",\"description\":\"\",\"name\":\"制热节能温度\",\"typeSpec\":{\"type\":\"value\",\"max\":500,\"min\":100,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"eco_heat_temp_f\",\"description\":\"\",\"name\":\"制热节能温度-℉\",\"typeSpec\":{\"type\":\"value\",\"max\":122,\"min\":50,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"eco_cold_temp\",\"description\":\"\",\"name\":\"制冷节能温度\",\"typeSpec\":{\"type\":\"value\",\"max\":500,\"min\":100,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"eco_cold_temp_f\",\"description\":\"\",\"name\":\"制冷节能温度-℉\",\"typeSpec\":{\"type\":\"value\",\"max\":122,\"min\":50,\"scale\":0,\"step\":1,\"unit\":\"℉\"}}]}]}"

Running through google translate gives the following:

 "model": "{\"modelId\":\"000004mf2n\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"default service\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_power3\",\"attribute\":\"1024\"},\"name\":\"switch\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_mode\",\"attribute\":\"1152\"},\"name\":\"operating mode\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"auto\",\"manual\",\"temphold\",\"holidays\"]}},{\"abilityId\":4,\"accessMode\":\"rw\",\"code\":\"eco\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-a_function_eco\",\"attribute\":\"1024\"},\"name\":\"ECO model\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"temp_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_temp\",\"attribute\":\"1024\"},\"name\":\"Target Temperature\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":50,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"temp_set_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"Target Temperature_F\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":41,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":18,\"accessMode\":\"rw\",\"code\":\"upper_temp_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"Set the Upper Temperature Limit ℉\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":77,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":19,\"accessMode\":\"rw\",\"code\":\"upper_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1024\"},\"name\":\"Set the Upper Temperature Limit\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":250,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":20,\"accessMode\":\"rw\",\"code\":\"lower_temp_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"Set the Lower Temperature Limit ℉\",\"typeSpec\":{\"type\":\"value\",\"max\":77,\"min\":41,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":23,\"accessMode\":\"rw\",\"code\":\"temp_unit_convert\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_loop\",\"attribute\":\"1024\"},\"name\":\"Temperature Scale Switch\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"c\",\"f\"]}},{\"abilityId\":24,\"accessMode\":\"ro\",\"code\":\"temp_current\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-wendu\",\"attribute\":\"1024\"},\"name\":\"Current Temperature\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":0,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":26,\"accessMode\":\"rw\",\"code\":\"lower_temp\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_c\",\"attribute\":\"1024\"},\"name\":\"Set the Lower Temperature Limit\",\"typeSpec\":{\"type\":\"value\",\"max\":250,\"min\":50,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":29,\"accessMode\":\"ro\",\"code\":\"temp_current_f\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_f\",\"attribute\":\"1024\"},\"name\":\"Current Temperature F\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":32,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":36,\"accessMode\":\"ro\",\"code\":\"valve_state\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-tcl_function_vs2\",\"attribute\":\"1024\"},\"name\":\"Valve Status\",\"typeSpec\":{\"type\":\"enum\",\"range\":[\"open\",\"close\"]}},{\"abilityId\":40,\"accessMode\":\"rw\",\"code\":\"child_lock\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_lock\",\"attribute\":\"1024\"},\"name\":\"Child Lock\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":71,\"accessMode\":\"rw\",\"code\":\"week_program_4\",\"description\":\"周程序4\",\"name\":\"周程序4\",\"typeSpec\":{\"type\":\"raw\",\"maxlen\":128}},{\"abilityId\":101,\"accessMode\":\"rw\",\"code\":\"holiday_days_set\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-setting\",\"attribute\":\"4096\"},\"name\":\"Holiday Mode Days Setting\",\"typeSpec\":{\"type\":\"value\",\"max\":99,\"min\":0,\"scale\":0,\"step\":1,\"unit\":\"day\"}},{\"abilityId\":102,\"accessMode\":\"rw\",\"code\":\"cold_hot_set\",\"description\":\"\",\"name\":\"Cold/Hot\",\"typeSpec\":{\"type\":\"bool\"}},{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"floor_temp_f\",\"description\":\"\",\"name\":\"Floor Temperature-°F\",\"typeSpec\":{\"type\":\"value\",\"max\":194,\"min\":32,\"scale\":0,\"step\":1,\"unit\":\"°F\"}},{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"floor_temp\",\"description\":\"\",\"name\":\"Floor Temperature\",\"typeSpec\":{\"type\":\"value\",\"max\":900,\"min\":0,\"scale\":1,\"step\":5,\"unit\":\"℃\"}},{\"abilityId\":105,\"accessMode\":\"rw\",\"code\":\"eco_heat_temp\",\"description\":\"\",\"name\":\"Heating energy-saving temperature",\"typeSpec\":{\"type\":\"value\",\"max\":500,\"min\":100,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":106,\"accessMode\":\"rw\",\"code\":\"eco_heat_temp_f\",\"description\":\"\",\"name\":\"Heating Enertgy Saving Temperature-℉\",\"typeSpec\":{\"type\":\"value\",\"max\":122,\"min\":50,\"scale\":0,\"step\":1,\"unit\":\"℉\"}},{\"abilityId\":107,\"accessMode\":\"rw\",\"code\":\"eco_cold_temp\",\"description\":\"\",\"name\":\"Refrigeration Energy Saving Temperature\",\"typeSpec\":{\"type\":\"value\",\"max\":500,\"min\":100,\"scale\":1,\"step\":10,\"unit\":\"℃\"}},{\"abilityId\":108,\"accessMode\":\"rw\",\"code\":\"eco_cold_temp_f\",\"description\":\"\",\"name\":\"Refrigeration Energy Saving Temperature-℉\",\"typeSpec\":{\"type\":\"value\",\"max\":122,\"min\":50,\"scale\":0,\"step\":1,\"unit\":\"℉\"}}]}]}"
```

### Information about how the device functions

It is a simple powerplug that can turn off/on when it reaches particular temperatures. It has a connection on the side to allow an external thermometer to be attached so the temperature sensor can be more appropriately placed.

It is used  to add smarts to portable heaters, infrared heaters and the like.

**Comment by happy-daisy** [comment]
The below gives me basic functionality. I plugged the id of the device from the tinytuya scan. I suspect the productID should have been used instead, but it worked for me.
Can turn on/off, set target temperature and view temperature.

Have not bothered with advanced features such as programming modes or tested child lock yet.

The basics of what I need is working, probably got some issues with the hvac_mode mapping based on the 'conditions' section. 

```
name: Thermostat
products:
  - id: <redacted>
    model: BHT-012
entities:
  - entity: climate
    dps:
      - id: 1
        name: hvac_mode
        type: boolean
        mapping:
          - dps_val: false
            value: "off"
          - dps_val: true
            #constraint: mode
            conditions:
              - dps_val: heat
                value: heat
              - dps_val: true
                value: heat
              - dps_val: true
                value: heat
      - id: 2
        name: mode
        type: string
        mapping:
        - dps_val: "heat"
          value: heat
        - dps_val: true
          value: heat
        - dps_val: "auto"
          value: auto
        - dps_val: "manual"
          value: manual
        - dps_val: "heat"
          value: temphold
        - dps_val: holidays
          value: holidays
      #      - id: 3
      #        name: hvac_action
      #        type: string
      #        optional: true
      #        mapping:
      #          - dps_val: Warming
      #            value: heating
      #          - dps_val: Heat
      #            value: heating
      #          - dps_val: "Off"
      #            value: idle
      #          - dps_val: Closed
      #            value: idle
      #          - dps_val: null
      #            value: idle
      - id: 16
        name: temperature
        type: integer
        unit: C
        range:
          min: 50
          max: 900
        mapping:
          - scale: 10
            step: 5
      - id: 19
        name: max_temperature
        type: integer
        range:
          min: 77
          max: 194
        mapping:
          - scale: 10
            step: 1
      - id: 24
        name: current_temperature
        type: integer
        range:
          min: 0
          max: 900
        mapping:
          - scale: 10
            step: 5
      - id: 26
        name: min_temperature
        type: integer
        range:
          min: 50
          max: 250
        mapping:
          - scale: 10
            step: 10
  - entity: lock
    translation_key: child_lock
    category: config
    dps:
      - id: 40
        type: boolean
        name: lock


```
