### ISSUE TITLE
Sensor entities for temp and humidity not added

### ISSUE THREAD

**Issue by jjlauer** [make-all/tuya-local#350]
I followed similar examples to add support for a temperature and humidity sensor.  While I can get an entity for the "Display Units" config to appear when adding a device, this integration seems to skip over the temperature and humidity sensors.  Those entities are also never displayed in the UI either.  Hoping for some help!  Here is the .yaml

```yaml
# Example DPS Status
# {'dps': {'1': 226, '2': 41, '9': 'f'}}
name: TH16 TH06WB3S Temperature and Humidity Sensor
products:
  - id: 7akwzwfwhukkdsib
primary_entity:
  entity: sensor
  name: Temperature
  class: temperature
  dps:
    - id: 1
      name: Temperature
      type: integer
      unit: C
      mapping:
        - scale: 10
      class: measurement
secondary_entities:
  - entity: sensor
    name: Humidity
    class: humidity
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: select
    name: Display Units
    category: config
    dps:
      - id: 9
        name: option
        type: string
        mapping:
          - dps_val: "f"
            value: Fahrenheit
          - dps_val: "c"
            value: Celcius

```
