### ISSUE TITLE
Netmostat N-1 wifi Thermostat (RTAFN1)

### ISSUE THREAD

**Issue by ppprpd** [make-all/tuya-local#353]
Hi!
Can you add this device?

```
name: Netmostat N-1 Smart Thermostat
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: true
          value: heat
        - dps_val: false
          value: "off"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 50
        max: 350
      mapping:
        - step: 5
          scale: 10
    - id: 3
      type: integer
      name: current_temperature
      mapping:
        - step: 5
          scale: 10
    - id: 4
      type: string
      name: preset_mode
      mapping:
        - dps_val: smart
          value: comfort
        - dps_val: antifreezing
          value: Anti-freeze
    - id: 19
      type: string
      name: timer
      optional: true
      mapping:
        - dps_val: "0h"
          value: "off"
        - dps_val: "1h"
          value: "1 hour"
        - dps_val: "2h"
          value: "2 hours"
secondary_entities:
  - entity: lock
    name: Child lock
    icon: "mdi:hand-back-right-off"
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
```
