### ISSUE TITLE
Aroma humidifier implemenation

### ISSUE THREAD

**Issue by spuljko** [make-all/tuya-local#355]
I am trying to write device support for generic aroma diffuser which is humidifier type in HA. It is working OK via Tuya integration.
Sample: https://expo.tuya.com/product/706007   https://expo.tuya.com/product/829078   
Product Category: jsq

Device doesn't have target humidity, and I am getting following error:

ERROR (MainThread) [custom_components.tuya_local.device] Aromatherapy Humidifier receive loop terminated by exception 
Traceback (most recent call last):
  File "/config/custom_components/tuya_local/device.py", line 158, in receive_loop
    entity.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 704, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 556, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 599, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 171, in state_attributes
    if self.target_humidity is not None:
  File "/config/custom_components/tuya_local/generic/humidifier.py", line 78, in target_humidity
    raise NotImplementedError()

Here is yaml:
```
name: Aromatherapy Humidifier YYM-805SW
products:
    - id: c0nh3LmEk0NDebrq
primary_entity:
  entity: humidifier
  class: humidifier
  dps:
    - id: 1
      name: switch_spray   
      type: boolean
      mapping:
        - dps_val: true
          value: true
        - dps_val: false
          value: false
    - id: 2
      name: mode      
      type: string
      category: config
      mapping:
        - dps_val: large
          value: Large
        - dps_val: small
          value: Small
    - id: 5
      name: switch_led
      type: boolean
      mapping:
        - dps_val: true
          value: true
        - dps_val: false
          value: false
```

**Comment by make-all** [comment]
If it doesn't have target humidity, then it isn't really a humidifier in HA, it is a fan, and the switch_led is a light.

```yaml
name: Aromatherapy Humidifier YYM-805SW
products:
    - id: c0nh3LmEk0NDebrq
primary_entity:
  entity: fan
  dps:
    - id: 1
      name: switch
      type: boolean
    - id: 2
      name: speed
      type: string
      mapping:
        - dps_val: large
          value: 100
        - dps_val: small
          value: 50
secondary_entities:
  - entity: light
    name: LED
    category: config
    dps:
      - id: 5
        name: switch
        type: boolean
```

**Comment by spuljko** [comment]
Thanks, that's working well. I have added rest of DPS, but light color can't be changed. I have tried various combinations. 
Light color received from device status on Tuya site looks like this:
```
    {
      "code": "colour_data_hsv",
      "value": "{\"h\":85.0,\"s\":253.0,\"v\":255.0}"
    }
```
This also applies for sending command to change color on Tuya site.
In settings dialog for the light I can see brightness slider although brightness dps does not exist.
Is the problem in that color mode hs is not implemented?

```
# DPS sample: {'updated_at': 1674433099.9169242, '1': True, '2': 'large', '3': '1', '5': True, '6': 'colourful1', '8': '001fff00e8ffff'} 
name:  YYM-805SW Aroma diffuser
products:
    - id: c0nh3LmEk0NDebrq
primary_entity:
  entity: fan
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: true
          icon: mdi:scent
          value: ON
        - dps_val: false
          icon: mdi:scent-off
          value: OFF      
    - id: 2
      name: speed
      type: string
      hidden: true
      mapping:
        - dps_val: large
          value: 100
          icon: "mdi:sprinkler-variant"
        - dps_val: small
          value: 50
          icon: "mdi:sprinkler"
    - id: 4          
      name: "Left time"
      readolny: true
      optional: true
      type: integer
      range:
        min: 0
        max: 360
secondary_entities:
  - entity: light
    name: Nightlight
    icon: "mdi:light-recessed"
    dps:
      - id: 5
        name: switch
        type: boolean
      - id: 6 
        name: color_mode  #effect
        type: string
        hidden: true
        mapping:
          - dps_val: colour
            value: rgbw 
      - id: 8   # not working
        name: rgbhsv  
        type: hex     
        format:
          - name: r
            bytes: 1
          - name: g
            bytes: 1
          - name: b
            bytes: 1
          - name: h
            bytes: 2
            range:
              min: 0
              max: 360
          - name: s
            bytes: 1
            range:
              min: 0
              max: 100
          - name: v
            bytes: 1
            range:
              min: 0
              max: 100
  - entity: select
    name: "Color mode"
    category: config
    icon: "mdi:palette"
    dps:
    - id: 6
      name: option
      type: string
      mapping:
        - dps_val: colour
          value: Color
        - dps_val: colourful1
          value: Colorful          
  - entity: select
    name: "Spray mode"
    category: config
    icon: "mdi:sprinkler-variant"
    dps:
    - id: 2
      name: option
      type: string
      mapping:
        - dps_val: large
          value: Large
          icon: "mdi:sprinkler-variant"
        - dps_val: small
          value: Small
          icon: "mdi:sprinkler"
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 3
        name: option  
        type: string
        mapping:
          - dps_val: "cancel"
            value: "Off"
          - dps_val: "1"
            value: "1 hour"
          - dps_val: "3"
            value: "3 hours"
          - dps_val: "6"
            value: "6 hours"
```
