### ISSUE TITLE
New device - RGB plug

### ISSUE THREAD

**Issue by MadDoct** [make-all/tuya-local#360]
this is the yaml I made
Tuya describes it as Scenario Light Socket

```
name: Scenario Light Socket
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 4
      type: integer
      name: current_a
      readonly: true
      mapping:
        - scale: 1000
    - id: 5
      type: integer
      name: voltage_v
      readonly: true
      mapping:
        - scale: 10
    - id: 6
      type: integer
      name: current_power_w
      readonly: true
      mapping:
        - scale: 10
    - id: 33
      type: integer
      name: timer

secondary_entities:
  - entity: light
    name: Night light
    dps:
      - id: 25
        name: scene_data
        type: hex
        optional: true
      - id: 27
        name: switch
        type: boolean
      - id: 28
        type: string
        name: color_mode
        mapping:
          - dps_val: colour
            value: rgbw
          - dps_val: scene
            value: colorloop
          - dps_val: music
            value: random
      - id: 31
        name: rgbhsv
        type: hex
        optional: true
        format:
          - name: h
            bytes: 2
            range:
              min: 0
              max: 360
          - name: s
            bytes: 2
            range:
              min: 0
              max: 1000
          - name: v
            bytes: 2
            range:
              min: 0
              max: 1000
  - entity: number
    category: config
    icon: "mdi:timer"
    name: Timer
    dps:
      - id: 33
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: sensor
    name: Current
    category: diagnostic
    class: current
    dps:
      - id: 4
        name: sensor
        type: integer
        class: measurement
        unit: mA
  - entity: sensor
    name: Voltage
    category: diagnostic
    class: voltage
    dps:
      - id: 5
        name: sensor
        type: integer
        class: measurement
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    name: Power
    category: diagnostic
    class: power
    dps:
      - id: 6
        name: sensor
        type: integer
        class: measurement
        unit: W
        mapping:
          - scale: 10
  - entity: select
    name: Scene
    icon: "mdi:palette"
    category: config
    dps:
      - id: 25
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: "000c0d0000000000000000c80000"
            # color: brown, static
            value: Night
          - dps_val: "010e0d0000840000000003e801f4"
            # color: white, static
            value: Read
          - dps_val: "020e0d0000e80383000003e803e8"
            # color: lt cyan, static
            value: Working
          - dps_val: "030e0d00001403e8000001f401f4"
            # color: grey, static
            value: Leisure
          - dps_val: "04464602007803e803e800000000464602007803e8000a00000000"
            # color: G+DkG, Breath, Mid speed
            value: Soft
          - dps_val: "05464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000464601003d03e803e80000000046460100ae03e803e800000000464601011303e803e800000000"
            # color* R+G+B+Y+C+V, Flash, Mid speed
            value: Colorful
          - dps_val: "06464601000003e803e800000000464601007803e803e80000000046460100f003e803e800000000"
            # color* R+G+B, Flash, Mid speed
            value: Dazzling
          - dps_val: "07464602000003e803e800000000464602007803e803e80000000046460200f003e803e800000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e800000000"
            # color* R+G+B+Y+C+V, Breath, Mid speed
            value: Gorgeous
```
