### ISSUE TITLE
Help with Gate Controller

### ISSUE THREAD

**Issue by illuzn** [make-all/tuya-local#365]
I'm trying to set up the following Gate Controller...
````yaml
#A generic Tuya Gate Controller
name: Gate Controller
primary_entity:
  entity: button
  name: Activate
  icon: "mdi:gesture-tap-button"
  dps:
    - id: 148
      type: boolean
      name: button
````
The issue I am having is the device shows as unavailable when first added (or when HA is rebooted). This is because my device doesn't report any status for this DPS (or seemingly any DPS at all - according to tuyadebug).

Setting this dps to true definitely triggers the gate opening though (tested via tuya-cli).

I've tried setting `optional: true` but that doesn't do anything. Any advice?
