### ISSUE TITLE
Unable to load integration - Missing tinytuya

### ISSUE THREAD

**Issue by Joery** [make-all/tuya-local#366]
When I try to setup tuya-local, it does not start the config-flow but gives the following error in the logs:

`Error occurred loading configuration flow for integration tuya_local: No module named 'tinytuya'`

I installed tuya-local by adding it as a custom repository to HACS.
Is there a way to get tinytuya to load? Using the [linuxserver/homeassistant](https://github.com/linuxserver/docker-homeassistant) container.

Thanks!

**Comment by make-all** [comment]
Sorry, I cannot offer support for exotic installation methods.  On HA OS, they have a wheels repository that takes care of dependencies, and since this dependency is declared in the manifest I'd expect that to work.  But I don't know how the various other alternate HA installation methods work with regards to dependency handling.

**Comment by Joery** [comment]
Thank you for your explanation, I'll inquire with the linuxserver-team.

**Comment by Joery** [comment]
I'll also put the solution here for future reference. Adding the following two lines to the environment variables in the docker-compose fixes it:

```
- DOCKER_MODS=linuxserver/mods:universal-package-install
- INSTALL_PIP_PACKAGES=tinytuya
```

**Comment by akrauze** [comment]
Thanks @Joery . I'm using the official HA image and had the same issue. With your answer it became obvious that "all" I had to do was to run ``pip install tinytuya`` at container startup (that can be done by overriding ``CMD``, ``ENTRYPOINT`` or ``ARGS``, or in my case using Kube's ``postStart``).

For anyone else in the business of using extreme exotic installation methods, here is how it can be done on Kube:
```yaml
        image: ghcr.io/home-assistant/home-assistant:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /usr/local/bin/pip
              - install
              - tinytuya
```
