### ISSUE TITLE
Adding device seems to timeout?

### ISSUE THREAD

**Issue by tricksel** [make-all/tuya-local#40]
Hi,

For some reason, adding the integration and adding my device seems to timeout. I fill in the IP-address, the local id and the local key (field labels are missing, so I hope I fill in the right data in the right fields). When saving, it's busy for some time, but doesn't save or whatsoever. I don't know where to find log files (if any), so don't know how to give any more info.
Is this a known problem? Or can I supply more info, and, if so, how?

**Comment by EKCJ** [comment]
I think I'm having the same problem - but with the advantage of a working frontend I can see the failure message, which is:
```
Unable to connect to your device with those details. It could be an intermittent issue, or they may be incorrect.
```

The log entry:
```
This error originated from a custom integration.

Logger: custom_components.tuya_local.device
Source: custom_components/tuya_local/device.py:236
Integration: Tuya Local (documentation, issues)
First occurred: 00:39:19 (1 occurrences)
Last logged: 00:39:19

Failed to refresh device state for Test.
```

I will try again tomorrow given the "intermittent" statement in the error, but I've been trying this for about half an hour with no success. I am able to ping the device from console so it doesn't appear to be a network issue. Would be grateful for any troubleshooting suggestions.

**Comment by make-all** [comment]
Double check the device ID and key are correct.  If possible, use tuya-cli or tinytuya to test the connection from the command line.

After getting the local key, you cannot re pair the device with another app, as that will cause the local key to change.

**Comment by EKCJ** [comment]
Thanks for this. You were clearly onto something when you wrote the error message, because doing the exact same thing 12 hours later worked. Hopefully OP had the same experience.

My device is not being detected as the correct type (it's a dehumidifier but only the simple_switch option is available) - but I will poke around and see if I can get it recognised correctly.

**Comment by make-all** [comment]
A climate device might be better if the heater can have the target temperature set.

**Comment by EKCJ** [comment]
Thankyou, this is useful. I've got a mostly working configuration file but am struggling with a couple of features. I'd be grateful for any suggestions you have.

Here's the config:
```
name: "ElectriQ Dehumidifier DESD9LW"
primary_entity:
  entity: climate
  dps:
    - id: 1
      name: power
      type: boolean
#      hidden: true
      mapping:
        - dps_val: false
          icon: "mdi:air-humidifier-off"
          icon_priority: 1
          value: "off"
        - dps_val: true
          icon: "mdi:air-humidifier"
          icon_priority: 3
    - id: 2
      type: integer
      name: humidity
      range:
        min: 35
        max: 80
      mapping:
        - step: 5
    - id: 4
      type: string
      name: fan_mode
      mapping:
        - dps_val: "Low"
          constraint: hvac_mode
          conditions:
            - dps_val: "Auto"
              invalid: true
          value: "Low"
        - dps_val: "Medium"
          constraint: hvac_mode
          conditions:
            - dps_val: "Auto"
              invalid: true
          value: "Medium"
        - dps_val: "High"
          constraint: hvac_mode
          conditions:
            - dps_val: "Auto"
              invalid: true
          value: "High"
        - dps_val: "auto"
          value: "Auto"
          invalid: true
    - id: 5
      name: hvac_mode
      type: string
      mapping:
        - value: "off"
        - dps_val: "Auto"
          value: "auto"
          constraint: power
          conditions:
          - dps_val: false
            value_redirect: power
        - dps_val: "Heater"
          value: "heat"
          constraint: power
          conditions:
          - dps_val: false
            value_redirect: power
        - dps_val: "Dehumidity"
          value: "dry"
          constraint: power
          conditions:
          - dps_val: false
            value_redirect: power
        - dps_val: "Fan"
          value: "fan_only"
          constraint: power
          conditions:
          - dps_val: false
            value_redirect: power
          icon: "mdi:air-purifier"
          icon_priority: 2
    - id: 6
      type: integer
      name: current_humidity
      readonly: true
    - id: 7
      type: integer
      name: current_temperature
      readonly: true
    - id: 10
      type: boolean
      name: swing_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          value: "vertical"
    - id: 101
      type: integer
      name: temperature
      range:
        min: 16
        max: 30
      mapping:
        - step: 1
secondary_entities:
  - entity: switch
    name: "UV sanitizer"
    icon: "mdi:solar-power"
    dps:
      - id: 15
        name: switch
        type: boolean
  - entity: switch
    name: "Ioniser"
    icon: "mdi:atom-variant"
    dps:
      - id: 12
        name: switch
        type: boolean
```
I'm struggling with 3 issues:
### Switches
The second switch for the ioniser isn't created in HA. I think I remember reading that multiple switches aren't supported yet, but can't find the thread any more. If that is the case then I'll set the UV light up as a light entity.

### Target Humidity
Setting the target humidity in HA throws an error:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: core.py:362
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:29:08 (1 occurrences)
Last logged: 13:29:08

[23126175886592] async_set_humidity() got an unexpected keyword argument 'humidity'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 856, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 689, in _handle_entity_call
    result = hass.async_run_job(partial(getattr(entity, func), **data))  # type: ignore
  File "/usr/src/homeassistant/homeassistant/core.py", line 451, in async_run_job
    return self.async_run_hass_job(HassJob(target), *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 435, in async_run_hass_job
    return self.async_add_hass_job(hassjob, *args)
  File "/usr/src/homeassistant/homeassistant/core.py", line 362, in async_add_hass_job
    task = self.loop.create_task(hassjob.target(*args))
TypeError: async_set_humidity() got an unexpected keyword argument 'humidity'
```
HA also displays the max and min humidity correctly in Developer Tools -> States, but doesn't seem to recognise the step value. Not sure what is happening here.

### Switching the device off
The device has a physical on/off power button, and a separate mode selection button with 4 options (heater, dehumidifier, air purifier and smart). Using the above config, HA correctly displays the hvac_mode as Off when the power is off, and selecting a different HVAC mode turns the power on, although it restores the previous hvac_mode instead of using the one selected (I don't know why this works).

Unfortunately I haven't been able to figure out a way to turn the power off from HA. I tried to do this using value_redirect but couldn't get a working config. The climate entity also doesn't support a power switch, and I don't think I can set up a separate switch entity as mentioned above.

I think I could work around this by creating a humidifier entity, but that would mean having to use the humidifier card to turn the device on even if the user isn't intending to use the dehumidifier features, which isn't ideal.



Thanks for reading this very long post - please let me know if it would be better to split this off into a new issue(s).
