### ISSUE TITLE
Support for the Breville Easy Air purifier

### ISSUE THREAD

**Issue by DataGeek-AU** [make-all/tuya-local#400]
### Breville Easy Air purifier 
![BrevilleAir](https://user-images.githubusercontent.com/47727356/218427436-76784bbf-d3d6-4239-b070-f37e2dfab964.jpg)

Sharing my .yaml file for anyone with a Breville Air purifier. The Home Assistant integration with tuya doesn't allow you to control the fan speed remotely. I have been able to successfully implement all the same controls as the tuya app including fan speed. See my screen shot below. I did not implement the filter reset as I would normally do that on the device at the time I cleaned or replaced the filter.

Only annoying thing is home assistant sorts the select list based on the _dps_val_. I ended up adding numbers to make it easier for me to select without thinking. 

note that the primary entity is switch. This is required so that the correct configuration is available to you at the setup stage. otherwise, all you will see is simple switch. This is due to the product settings in the tuya cloud.

hopefully this gets added to the device library. And if not all you should need to do save the .yaml below into your own file and enjoy the best home assistant integration for the Breville Easy Air purifier

### Home Assistant view of Entities
![brev](https://user-images.githubusercontent.com/47727356/218423418-c7c37bcd-76f2-4435-a8a9-c13490507d30.JPG)

### the_Breville_Easy_Air_purifier.yaml

[the_Breville_Easy_Air_purifier.txt](https://github.com/make-all/tuya-local/files/10720774/the_Breville_Easy_Air_purifier.txt)
`
```
name: the Breville Easy Air™
products:
  - id: k2mlahbu9v4xxdlb
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: true
          icon: "mdi:air-purifier"
        - dps_val: false
          icon: "mdi:air-purifier-off"
secondary_entities:
  - entity: switch
    name: Night Mode
    category: config
    icon: "mdi:lightbulb-night"
    dps:
      - id: 8
        name: switch
        type: boolean
  - entity: switch
    name: Micro Shield
    category: config
    icon: "mdi:shield-bug"
    dps:
      - id: 9
        name: switch
        type: boolean
  - entity: sensor
    name: Filter Days Left
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 16
        name: sensor
        type: integer
        unit: day
  - entity: select
    name: Timer
    category: config
    dps:
      - id: 19
        type: string
        name: option
        mapping:
          - dps_val: "cancle"
            value: "Cancel"
            icon: "mdi:timer"
          - dps_val: "2"
            value: "2 hour"
            icon: "mdi:fan-clock"
          - dps_val: "4"
            value: "4 hours" 
            icon: "mdi:fan-clock"
          - dps_val: "8"
            value: "8 hours" 
            icon: "mdi:fan-clock"
  - entity: select
    name: Fan Speed
    category: config
    dps:
      - id: 4
        type: string
        name: option
        mapping:
          - dps_val: "low"
            value: "1 - Low"
            icon: "mdi:fan-speed-1"
          - dps_val: "mid"
            value: "2 - Mid"
            icon: "mdi:fan-speed-2"
          - dps_val: "high"
            value: "3 - High"
            icon: "mdi:fan-speed-3"
          - dps_val: "turbo"
            value: "4 - Turbo"
            icon: "mdi:fan-plus"
  - entity: sensor
    name: Time Left
    category: diagnostic
    icon: "mdi:timer"
    dps:
      - id: 20
        name: sensor
        type: integer
        unit: min`
```
