### ISSUE TITLE
Request support for DETA LED Single Gang Touch Dimmer Switch 6910HA series2

### ISSUE THREAD

**Issue by dezinc57** [make-all/tuya-local#409]
Requesting device support for DETA (Grid Connect) Smart LED Single Gang Touch Dimmer Switch 6910HA series2

# Log Message

Device matches simple_switch with quality of 11%. DPS: {'updated_at': 1676177547.4074905, '1': False, '2': 'normal', '3': 2, '8': 'forward', '15': False, '16': 1000, '17': 220, '22': '0', '24': 0}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches mirabella_genio_usb with quality of 50%. DPS: {'updated_at': 1676177876.7114944, '1': False, '2': 400, '3': 190, '6': 0}

# Information about DPS mappings

{
  "result": {
    "category": "tgq",
    "functions": [
      {
        "code": "switch_led_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_min_1",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_led_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "bright_value_1",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "brightness_min_1",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_1",
        "dp_id": 6,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1676178207556,
  "tid": "95dede3baa9211eda120e66c285aff6b"
}

# Product ID

{
  "result": {
    "category": "tgq",
    "category_name": "Light Modulator",
    "model": "6910HA series2",
    "product_id": "zdbapiyvwyi4wtrr",
    "product_name": "6910HA series2",

  },

# Information about how the device functions

Device provides Touch ON/OFF and Touch (hold) dimming.
Simply touch and hold the switch to increase or decrease the desired brightness.
It comes with new features that allow you to adjust the minimum and maximum end of the dimming range in case of flickering.

Product page: https://detaelectrical.com.au/product/deta-grid-connect-smart-led-single-gang-touch-dimmer-switch/

**Comment by dezinc57** [comment]
Confirming device entities work are configured and work correctly.

Also works with earlier hardware device version 6910HA (non series2)

**Comment by Kaldek** [comment]
> Confirming device entities are configured and work correctly.
> 
> Also works with earlier hardware device version 6910HA (non series2)

Are you sure about this?  I had to hack the crap out mine using TuyaMCU Option66 to get it to work, along with some deep MQTT trickery in Home Assistant:

```yaml
mqtt:
  light:
  - unique_id: "Study Dimmer"
    name: "Study Dimmer"
    state_topic: "stat/tasmota_15EB46/POWER"
    command_topic: "cmnd/tasmota_15EB46/POWER"
    payload_on: 'ON'
    payload_off: 'OFF'
    brightness_command_topic: "cmnd/tasmota_15EB46/TuyaSend2"
    brightness_command_template: "{{ '2,' ~ ((value | int) * (1000 - 280) // 1000 + 280) }}"
    brightness_state_topic: "tele/tasmota_15EB46/RESULT"
    brightness_scale: 1000
    brightness_value_template: "{{ ((value_json.TuyaReceived['2'].DpIdData | int(base=16)) - 280) * 1000 // (1000 - 280) if '2' in value_json.TuyaReceived else None }}"

```
