### ISSUE TITLE
Vacuum seen as switch

### ISSUE THREAD

**Issue by Oglaf** [make-all/tuya-local#412]
**Describe the bug**
When I add my vacuum to Tuya Local it only suggests generic switches
![image](https://user-images.githubusercontent.com/31038423/218830601-a20724e0-59c8-40bd-8572-70287447dc0f.png)

**To Reproduce**
1. Click **Add integration** button;
2. Select **Tuya Local**;
3. Input uuid, ip address, local key;
4. Select protocol version 3.3;
5. Click **Submit**.

**Expected behavior**
Suggest my vacuum device at best, show other device or message error at worst.

**Additional context**
I'm migrating from localtuya to tuya-local and I'm trying support my vacuum using my localtuya's diagnostic file and other local-tuya's vacuum devices to create my own (which probably works on most vacuums since it works with localtuya's suggested DPs).

I have placed my file under /config/custom_components/tuya_local/devices and restarted HA.

My device.yaml file:
```
name: KaBuM!Robô aspirador de pó 
products:
  - id: wexaeucvbdawkkpo
primary_entity:
  entity: vacuum
  dps:
    - id: 1
      type: boolean
      name: power
    - id: 11
      type: bitfield
      name: error   
      mapping:
        - dps_val: 1
          value: edge_sweep
        - dps_val: 2
          value: middle_sweep
        - dps_val: 4
          value: left_wheel
        - dps_val: 8
          value: right_wheel
        - dps_val: 16
          value: garbage_box
        - dps_val: 32
          value: land_check
        - dps_val: 64
          value: collision
    - id: 14
      name: battery
      type: integer
      readonly: true
    - id: 25
      type: boolean
      name: activate
    - id: 26
      type: string
      name: direction_control
      optional: true
      mapping:
        - dps_val: forward
          value: forward
        - dps_val: backward
          value: reverse
        - dps_val: turn_left
          value: left
        - dps_val: turn_right
          value: right
        - dps_val: stop
          value: stop
    - id: 27
      type: string
      name: command
      mapping:
        - dps_val: standby
          value: standby
        - dps_val: smart
          value: auto_cleaning
        - dps_val: spiral
          value: stop_cleanning
        - dps_value: single
          value: room_cleaning
        - dps_val: wall_follow
          value: edge_cleaning
        - dps_val: chargego
          value: return_to_base
    - id: 28
      type: string
      name: status
      mapping:
        - dps_val: cleanning
          value: cleanning
        - dps_val: returning
          value: returning_to_dock
        - dps_val: charging
          value: charging
        - dps_val: standby
          value: standby
    - id: 29
      type: boolean
      name: locate
      optional: true
    - id: 30
      type: string
      name: fan_speed
      mapping:
        - dps_val: low
          value: Low
        - dps_val: normal
          value: Medium
        - dps_val: high
          value: High
secondary_entities:
  - entity: select
    name: Mute voice
    icon: "mdi:account-voice"
    dps:
      - id: 31
        type: boolean
        name: mute_voice
  - entity: sensor
    name: Clean area
    category: diagnostic
    icon: "mdi:floor-plan"
    dps:
      - id: 32
        type: integer
        name: sensor
        unit: m2
  - entity: sensor
    name: Clean time
    category: diagnostic
    icon: "mdi:clock-outline"
    dps:
      - id: 33
        type: integer
        name: sensor
        unit: min
```
