### ISSUE TITLE
Request support for Teckin SS42

### ISSUE THREAD

**Issue by drudgebg** [make-all/tuya-local#414]
Tested and working yaml code for Teckin SS42:

```
name: Smart Outdoor Double plug
primary_entity:
  entity: switch
  class: outlet
  name: Switch 1
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: switch
    class: outlet
    name: Switch 2
    dps:
      - id: 2
        type: boolean
        name: switch
  - entity: number
    category: config
    name: Timer 2
    icon: "mdi:timer"
    dps:
      - id: 101
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer 1
    icon: "mdi:timer"
    dps:
      - id: 102
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
```
