### ISSUE TITLE
New Device Support  BlitzWolf BW-SHP6 PRO

### ISSUE THREAD

**Issue by MarciPain** [make-all/tuya-local#421]
```yaml
name: BW-SHP6 PRO
primary_entity:
  entity: switch
  class: outlet
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 9
      type: integer
      name: timer
    - id: 17
      type: integer
      name: add_ele
      read_only: true
    - id: 18
      type: integer
      name: current_a
      read-only: true
      mapping:
        - scale: 1000
    - id: 19
      type: integer
      name: current_power_w
      read-only: true
      mapping:
        - scale: 10
    - id: 20
      type: integer
      name: voltage_v
      read-only: true
      mapping:
        - scale: 10
    - id: 21
      type: bitfield
      name: factory_test
      optional: true
    - id: 22
      type: integer
      name: voltage_calibration
      optional: true
    - id: 23
      type: integer
      name: current_calibration
      optional: true
    - id: 24
      type: integer
      name: power_calibration
      optional: true
    - id: 25
      type: integer
      name: energy_calibration
      optional: true
    - id: 41
      type: string
      name: cycle_time
      optional: true
    - id: 42
      type: string
      name: random_time
      optional: true
    - id: 43
      type: string
      name: switch_inching
      optional: true
secondary_entities:
  - entity: sensor
    category: diagnostic
    class: voltage
    name: Voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        class: measurement
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    name: Current
    dps:
      - id: 18
        name: sensor
        type: integer
        class: measurement
        unit: mA
  - entity: sensor
    category: diagnostic
    class: power
    name: Power
    dps:
      - id: 19
        name: sensor
        type: integer
        class: measurement
        unit: W
        mapping:
          - scale: 10
  - entity: number
    category: config
    name: Countdown Timer
    optional: true
    icon: "mdi:timer"
    dps:
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: select
    category: config
    name: Initial state
    icon: "mdi:toggle-switch"
    dps:
      - id: 38
        type: string
        name: option
        mapping:
          - dps_val: "on"
            value: "On"
          - dps_val: "off"
            value: "Off"
          - dps_val: memory
            value: "Last State"
  - entity: select
    category: config
    name: Light mode
    optional: true
    icon: "mdi:toggle-switch"
    dps:
      - id: 39
        type: string
        name: option
        mapping:
          - dps_val: "relay"
            value: "Relay"
          - dps_val: "pos"
            value: "Position"
          - dps_val: none
            value: "None"
  - entity: switch
    name: Child Lock
    optional: true
    category: config
    dps:
      - id: 40
        type: boolean
        name: switch
```
