### ISSUE TITLE
Support for [Orion Heater]

### ISSUE THREAD

**Issue by MarciPain** [make-all/tuya-local#423]
```yaml
name: Orion Heater
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: true
          value: "heat"
        - dps_val: false
          value: "off"
    - id: 2
      type: integer
      name: temperature
      range:
        min: 18
        max: 45
    - id: 3
      type: integer
      name: current_temperature
    - id: 5
      type: string
      name: preset_mode
      mapping:.
        - dps_val: "1"
          value: "1000 W"
        - dps_val: "2"
          value: "2000 W"
        - dps_val: "auto"
          value: "Auto"
        - dps_val: "off"
          value: "off"
secondary_entities:
   - entity: select
     name: Timer
     icon: "mdi:timer"
     category: config
     dps:
       - id: 19
         type: string
         name: option
         mapping:
           - dps_val: "cancel"
             value: "none"
           - dps_val: "1h"
             value: "1 Hour"
           - dps_val: "2h"
             value: "2 Hours"
           - dps_val: "3h"
             value: "3 Hours"
           - dps_val: "4h"
             value: "4 Hours"
           - dps_val: "5h"
             value: "5 Hours"
           - dps_val: "6h"
             value: "6 Hours"
           - dps_val: "7h"
             value: "7 Hours"
           - dps_val: "8h"
             value: "8 Hours"
   - entity: switch
     name: Window
     category: config
     dps:
       - id: 101
         type: boolean
         name: switch
   - entity: switch
     name: Swing
     category: config
     dps:
       - id: 101
         type: boolean
         name: switch
```
