### ISSUE TITLE
Support for [PGST PA-010 Tuya WiFi LCD Display Digital Indoor Temperature and Humidity Sensor]

### ISSUE THREAD

**Issue by MarciPain** [make-all/tuya-local#426]
# Log message

{'1': 22, '2': 57, '3': 'high', '9': 'c', '10': 39, '11': 0, '12': 97, '13': 1, '23': 0, '24': 0}

# Config
```yaml
name: PGST PA-010 Tuya WiFi LCD Display Digital Indoor Temperature and Humidity Sensor
primary_entity:
  entity: sensor
  name: Temperature
  class: temperature
  dps:
    - id: 1
      name: sensor
      type: integer
      unit: C
      class: measurement
secondary_entities:
  - entity: sensor
    name: Humidity
    class: humidity
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: select
    name: Battery
    read_only: true
    category: diagnostic
    dps:
      - id: 3
        type: string
        name: option
        mapping:
          - dps_val: "low"
            value: "LOW"
          - dps_val: "middle"
            value: "MIDDLE"
          - dps_val: "high"
            value: "HIGH"
  - entity: select
    name: Display Units
    category: config
    dps:
      - id: 9
        name: option
        type: string
        mapping:
          - dps_val: "f"
            value: Fahrenheit
          - dps_val: "c"
            value: Celsius
  - entity: number
    name: Maximum Temperature Set
    category: config
    dps:
      - id: 10
        name: value
        type: integer
        range:
          min: -20
          max: 70
  - entity: number
    name: Minimum Temperature Set
    category: config
    dps:
      - id: 11
        name: value
        type: integer
        range:
          min: -20
          max: 70
  - entity: number
    name: Maximum Humidity Set
    category: config
    dps:
      - id: 12
        name: value
        type: integer
        range:
          min: 0
          max: 100
  - entity: number
    name: Minimum Humidity Set
    category: config
    dps:
      - id: 13
        name: value
        type: integer
        range:
          min: 0
          max: 100
```
