### ISSUE TITLE
Request support for [cycle-multi-function-timer-air monitor]

### ISSUE THREAD

**Issue by p-owerscripter** [make-all/tuya-local#489]
**Tuya Wifi 7in1 Air Qualität Meter PM 2,5 CO2 TVOC HCHO AQI Temperatur**
[Product description](https://de.aliexpress.com/item/1005004886287408.html)

 "product_id": "ezovdhzaxsovyzf0",
 "product_name": "cycle-multi-function-timer-air monitor",
```
{
  "result": {
    "category": "kj",
    "functions": [],
    "status": [
      {
        "code": "pm25",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"ug/m3\",\"min\":0,\"max\":999,\"scale\":0,\"step\":1}"
      },
      {
        "code": "temp",
        "dp_id": 12,
        "type": "Integer",
        "values": "{\"unit\":\"℃\",\"min\":0,\"max\":600,\"scale\":1,\"step\":1}"
      },
      {
        "code": "humidity",
        "dp_id": 13,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "tvoc",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"ug/m3\",\"min\":0,\"max\":3000,\"scale\":3,\"step\":1}"
      },
      {
        "code": "eco2",
        "dp_id": 15,
        "type": "Integer",
        "values": "{\"unit\":\"ppm\",\"min\":400,\"max\":5000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "air_quality",
        "dp_id": 21,
        "type": "Enum",
        "values": "{\"range\":[\"great\",\"mild\",\"good\",\"medium\",\"severe\"]}"
      },
      {
        "code": "ch2o_value",
        "dp_id": 27,
        "type": "Integer",
        "values": "{\"unit\":\"ug/m3\",\"min\":0,\"max\":3000,\"scale\":3,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1677872843124,
  "tid": "376887bfb9fc11ed9f7936041e250963"
}
```
**My integration:**
```
name: cycle-multi-function-timer-air monitor
product:
  - id: ezovdhzaxsovyzf0
    name: cycle-multi-function-timer-air monitor
primary_entity:
  entity: sensor
  name: Air Quality
  class: aqi
  dps:
    - id: 21
      type: string
      name: sensor
      unit:
      class: measurement
secondary_entities:
  - entity: sensor
    name: Fine Particles (PM 2.5)
    class: pm25
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: µg/m³
        class: measurement
  - entity: sensor
    name: Formaldehyde
    class: volatile_organic_compounds
    dps:
      - id: 27
        type: integer
        name: sensor
        unit: mg/m³
        class: measurement
        mapping:
          - scale: 1000
  - entity: sensor
    name: Temperature
    class: temperature
    dps:
      - id: 12
        type: integer
        name: sensor
        unit: C
        class: measurement
        mapping:
          - scale: 10
  - entity: sensor
    name: Humidity
    class: humidity
    dps:
      - id: 13
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: sensor
    name: Volatile organic compound (TVOC)
    class: volatile_organic_compounds
    dps:
      - id: 14
        type: integer
        name: sensor
        unit: mg/m³
        class: measurement
        mapping:
          - scale: 1000
  - entity: sensor
    name: eCO2 (carbon dioxide calculated from TVOC)
    class: carbon_dioxide
    dps:
      - id: 15
        type: integer
        name: sensor
        unit: ppm
        class: measurement
```
