### ISSUE TITLE
Curtain Switch Same Brand Problem

### ISSUE THREAD

**Issue by cataseven** [make-all/tuya-local#494]
Hi, 

I have 11 curtain switches. For 10 of them Integration suggested model "qs_c01_curtain". Only for one it suggested  "loratap_curtain_switch". They are all same brand and model (Model Name: 108W&108WR New)

to solve this problem, I added it as Loratap, then I changed loratap_curtain_switch.yaml file as following. (I did not change first 3 lines). Then I restart HA. Remove entities coming from Lora integration and left only one coming from qs_c01 

Note: Lora integration see the switch "as button" (show the switch with 3 buttons (open, stop, close)
qs_c01 integration see it "as cover." (this is the correct mode)

```
name: LoraTap curtain switch
product:
  - id: tuh2eatk4hsq336s
primary_entity:
  entity: cover
  class: curtain
  dps:
    - id: 1
      name: control
      type: string
      mapping:
        - dps_val: open
          value: open
        - dps_val: close
          value: close
        - dps_val: stop
          value: stop
    - id: 2
      name: position
      type: integer
      unit: "%"
      range:
        min: 0
        max: 100
      mapping:
        - step: 10
secondary_entities:
  - entity: select
    name: Motor reverse mode
    category: config
    icon: "mdi:sign-direction"
    dps:
      - id: 8
        name: option
        type: string
        mapping:
          - dps_val: forward
            value: Forward
          - dps_val: back
            value: Back
  - entity: number
    name: Travel time
    category: config
    icon: "mdi:timer"
    dps:
      - id: 10
        name: value
        type: integer
        unit: s
        range:
          min: 1
          max: 60
```
