### ISSUE TITLE
Yaml file for Smart Sprinkler Controller

### ISSUE THREAD

**Issue by cataseven** [make-all/tuya-local#496]
for this product: https://www.aliexpress.com/item/1005003162848907.html?

```
name: Smart Sprinkler Controller
product:
  - id: e8fwsklivj87msao
    name: Smart Sprinkler Controller
primary_entity:
  entity: switch
  name: Switch 1
  dps:
    - id: 101
      name: switch
      type: boolean
secondary_entities:
  - entity: switch
    name: Switch 2
    dps:
      - id: 102
        name: switch
        type: boolean
  - entity: switch
    name: Switch 3
    dps:
      - id: 103
        name: switch
        type: boolean
  - entity: switch
    name: Switch 4
    dps:
      - id: 104
        name: switch
        type: boolean
  - entity: switch
    name: Switch 5
    dps:
      - id: 105
        name: switch
        type: boolean
  - entity: switch
    name: Switch 6
    dps:
      - id: 106
        name: switch
        type: boolean
  - entity: switch
    name: Switch 7
    dps:
      - id: 110
        name: switch
        type: boolean
  - entity: switch
    name: Switch 8
    dps:
      - id: 111
        name: switch
        type: boolean
```
