### ISSUE TITLE
Request support for Shinco 30D Dehumidifier

### ISSUE THREAD

**Issue by shiner66** [make-all/tuya-local#509]
### Log Message:
```
Device matches None with quality of 0%. DPS: {'updated_at': 1678219663.544819, '1': True, '2': '0', '3': 55, '4': 35, '5': False, '6': '0', '7': False, '8': True, '11': 0, '12': '0', '13': 0, '102': False}
```
### Get Device Specification Attribute returns:
```
{
  "result": {
    "category": "cs",
    "functions": [
      {
        "code": "anion",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "anion",
        "dp_id": 5,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fault",
        "dp_id": 11,
        "type": "Bitmap",
        "values": "{\"label\":[\"E1\",\"E2\"]}"
      },
      {
        "code": "countdown_left",
        "dp_id": 13,
        "type": "Integer",
        "values": "{\"unit\":\"min\",\"min\":0,\"max\":1440,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1678220631667,
  "tid": "f986ac8ebd2511ed98e69e0bfac44282"
}
```

### Datapoints info:
```
Power: 1
Mode: 2
Humidity (Enviroment report): 3
Set Humidity (Integer): 4
Anion (Even if it has no function it seems): 5
Inside Drying (Dries the unit after use to prevent mold): 101
Wind Speed (Fan Speed HIGH/LOW): 6
Water Pump (For devices with pump to sink capability): 102
Child Lock: 7
Swing: 8
Fault: 11
Countdown (1 Hours increment): 12
Remaining Time (Countdown, 1 minute increment): 13

From standard set, other instructions are deemed not standard by Tuya:

fault	Bitmap	
{
  "label": [
    "E1",
    "E2"
  ]
}
countdown_left	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 1440,
  "scale": 0,
  "step": 1
}
```

### Also, I tried to edit one of the already existant device files with the revelant DPIs, just to see if it get recognized that way, but no avail, still says that there are no compatible devices (disregard model info):

```
name: Eeese Adam dehumidifier
primary_entity:
  entity: humidifier
  class: dehumidifier
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
      - dps_val: false
        icon: "mdi:air-humidifier-off"
        icon_priority: 1
      - dps_val: true
        icon: "mdi:air-humidifier"
        icon_priority: 4
    - id: 4
      name: humidity
      type: integer
      range:
        min: 25
        max: 80
      mapping:
        - step: 5
    - id: 2
      name: mode
      type: string
      mapping:
        - dps_val: manual
          value: Manual
        - dps_val: laundry
          value: Dry clothes
          icon: "mdi:tshirt-crew-outline"
          icon_priority: 3
    - id: 11
      type: bitfield
      name: error
      mapping:
        - dps_val: 1
          icon: "mdi:cup-water"
          icon_priority: 2
      hidden: true
secondary_entities:
  - entity: fan
    dps:
      - id: 1
        type: boolean
        name: switch
      - id: 2
        type: string
        name: dehumidifier_mode
        hidden: true
      - id: 6
        type: string
        name: speed
        mapping:
          - dps_val: low
            value: 50
            constraint: dehumidifier_mode
            conditions:
              - dps_val: laundry
                invalid: true
          - dps_val: high
            value: 100
  - entity: sensor
    name: Current humidity
    class: humidity
    dps:
      - id: 3
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: binary_sensor
    name: Tank
    class: problem
    category: diagnostic
    dps:
      - id: 11
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: lock
    name: Child lock
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 12
        type: string
        name: option
        mapping:
          - dps_val: cancel
            value: "Off"
          - dps_val: 1h
            value: 1 hour
          - dps_val: 2h
            value: 2 hours
          - dps_val: 3h
            value: 3 hours
          - dps_val: 4h
            value: 4 hours
          - dps_val: 5h
            value: 5 hours
          - dps_val: 6h
            value: 6 hours
          - dps_val: 7h
            value: 7 hours
          - dps_val: 8h
            value: 8 hours
          - dps_val: 9h
            value: 9 hours
          - dps_val: 10h
            value: 10 hours
          - dps_val: 11h
            value: 11 hours
          - dps_val: 12h
            value: 12 hours
          - dps_val: 13h
            value: 13 hours
          - dps_val: 14h
            value: 14 hours
          - dps_val: 15h
            value: 15 hours
          - dps_val: 16h
            value: 16 hours
          - dps_val: 17h
            value: 17 hours
          - dps_val: 18h
            value: 18 hours
          - dps_val: 19h
            value: 19 hours
          - dps_val: 20h
            value: 20 hours
          - dps_val: 21h
            value: 21 hours
          - dps_val: 22h
            value: 22 hours
          - dps_val: 23h
            value: 23 hours
          - dps_val: 24h
            value: 24 hours
```

### Device manual (Different model, but operates in pretty much the same way): https://cdn.manomano.com/files/pdf/20084625.pdf
