### ISSUE TITLE
Request support for ceiling fan and light dimmer switch

### ISSUE THREAD

**Issue by endrumaj** [make-all/tuya-local#517]
# Log Message

-->
```
Device matches simple_switch with quality of 12%. DPS: {"updated_at": 1678394082.1054509, "1": false, "3": "3", "9": false, "10": 10, "101": 0, "103": 0, "105": 10, "106": "mode1"}
```

# Information about DPS mappings

```
Please paste the output here.
```

      {
        "code": "switch",
        "dp_id": 1 ,
        "value": false
      },
      {
        "code": "fan_speed",
        ""dp_id":  3 ,
        "value": "3"     (1,2,3,4)
      },
      {
        "code": "light",
        "dp_id":   9 ,
        "value": false
      },
      {
        "code": "bright_value",
         "dp_id":  10 ,
        "value": 1000   
      }
    ],

"dp_id":  105:  dimming range (10-1000)
"dp_id":  106: dimming mode (mode1,mode2,mode3)

  },
  "success": true,
  "t": 1678391935078,
  "tid": "d24ae073beb411ed8e091e9ebf08afbf"
}
-->

# Product ID

    "product_id": "ipyqwvhvzzjezv35",
    "product_name": "Ceiling Fan Dimmer Switch DS03",

# Information about how the device functions

**Comment by ChapayTv** [comment]
Please add this video intercom, if possible, it would be nice to see the object "pressing a button on the call panel" and "motion detector". in the cloud tuya there is no such possibility.



{
  "result": {
    "category": "sp",
    "functions": [
      {
        "code": "basic_indicator",
        "dp_id": 101,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "basic_flip",
        "dp_id": 103,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "basic_osd",
        "dp_id": 104,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "motion_sensitivity",
        "dp_id": 106,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "basic_nightvision",
        "dp_id": 108,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "sd_format",
        "dp_id": 111,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "record_switch",
        "dp_id": 150,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "record_mode",
        "dp_id": 151,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\"]}"
      },
      {
        "code": "device_restart",
        "dp_id": 162,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "basic_indicator",
        "dp_id": 101,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "basic_flip",
        "dp_id": 103,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "basic_osd",
        "dp_id": 104,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "motion_sensitivity",
        "dp_id": 106,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "basic_nightvision",
        "dp_id": 108,
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "sd_storge",
        "dp_id": 109,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "sd_status",
        "dp_id": 110,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":5,\"scale\":1,\"step\":1}"
      },
      {
        "code": "sd_format",
        "dp_id": 111,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "movement_detect_pic",
        "dp_id": 115,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "sd_format_state",
        "dp_id": 117,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":-20000,\"max\":20000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "doorbell_active",
        "dp_id": 136,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "record_switch",
        "dp_id": 150,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "record_mode",
        "dp_id": 151,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\"]}"
      },
      {
        "code": "doorbell_pic",
        "dp_id": 154,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "device_restart",
        "dp_id": 162,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1678434872883,
  "tid": "cb393012bf1811eda9e9d694da825c81"
}

**Comment by make-all** [comment]
@ChapayTv, this does not appear to be the same device, please file a separate issue for it.

@endrumaj, please provide more information on the device identification: brand / model etc.

**Comment by ChapayTv** [comment]
"product_id": "h3bhzu9m0ig80rdu",
"name": "SmartDoorBell-IPBox",

**Comment by ChapayTv** [comment]
This is what you need?

**Comment by make-all** [comment]
No, I need you to file your comments on an issue relating to your device.  
This issue was opened in relation to a ceiling fan.

**Comment by ChapayTv** [comment]
It's a video intercom device, it just won't connect to tuya local14:11, 10 марта 2023 г., Jason Rumney ***@***.***>:
No, I need you to file your comments on an issue relating to your device.
This issue was opened in relation to a ceiling fan.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by endrumaj** [comment]
TREATLIFE Smart Ceiling Fan Control and Dimmer Light Switch

**Comment by ThomasADavis** [comment]
I have a config for this..

```
name: DS03 Fan Controller
primary_entity:
  entity: fan
  dps:
    - id: 1
      name: Power
      type: boolean
    - id: 3
      name: Speed
      type: integer
      range:
        min: 1
        max: 4
      mapping:
        - scale: 0.04

secondary_entities:
  - entity: light
    dps:
      - id: 9
        type: boolean
        name: Switch
      - id: 10
        type: integer
        name: Brightness
        mapping:
          - scale: 4
      - id: 106
        name: Dimmer_mode
        type: string
      - id: 101
        name: Step
        type: integer
      - id: 103 
        name: Max
        type: integer
      - id: 105
        name: Min
        type: integer
```
