### ISSUE TITLE
Request support for CBI Astute Smart Controller (ASC)

### ISSUE THREAD

**Issue by Die-Meester** [make-all/tuya-local#563]
# Log Message

```
Please paste logs herename: ASC (Wi-Fi) ver 2
products:
  - id: xzgtyrqbab8lm2zo
    name: CBI ASC (Wifi) switch
primary_entity:
  entity: switch
  class: switch
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: number
    category: config
    name: Timer
    icon: "mdi:timer"
    dps:
      - id: 7
        type: integer
        name: value
        unit: sec
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 0
            step: 1
  - entity: select
    category: config
    name: Initial state
    icon: "mdi:toggle-switch"
    dps:
      - id: 14
        type: string
        name: option
        mapping:
          - dps_val: "power_on"
            value: "On"
          - dps_val: "power_off"
            value: "Off"
          - dps_val: last
            value: "Last State"
  - entity: sensor
    category: diagnostic
    name: Energy
    class: energy
    dps:
      - id: 20
        name: sensor
        type: integer
        unit: Wh
        class: measurement
        force: true
        readonly: true
  - entity: sensor
    category: diagnostic
    class: current
    name: Current
    dps:
      - id: 21
        name: sensor
        type: integer
        class: measurement
        force: true
        unit: mA
  - entity: sensor
    category: diagnostic
    class: power
    name: Power
    dps:
      - id: 23
        name: sensor
        type: integer
        class: measurement
        force: true
        unit: W
        range:
          min: 0
          max: 50000
        mapping:
          - scale: 10
            step: 1
  - entity: sensor
    category: diagnostic
    class: voltage
    name: Voltage
    dps:
      - id: 22
        name: sensor
        type: integer
        class: measurement
        force: true
        unit: V
        range:
          min: 0
          max: 5000
        mapping:
          - scale: 10
            step: 1

```

```
Please paste the output here.
```

# Product ID
xzgtyrqbab8lm2zo

# Information about how the device functions
![Alt text](https://cbi-lowvoltage.co.za/sites/default/files/styles/medium__300_wide_/public/gallery/ASC%20Open2.jpg?itok=xL6pLD2U "Product Image")

[Manual](https://cbi-lowvoltage.co.za/sites/default/files/downloads/CBI%20ASTUTE%20INSTRUCTION%20LEAFLET%203990A963%20REV%20B%2017032021.pdf)
