### ISSUE TITLE
Adding new Motion sensor config

### ISSUE THREAD

**Issue by tientmit88** [make-all/tuya-local#579]
```
name: Motion Sensor Light
products:
  - id: vwqnz1sn
    name: Motion Sensor
primary_entity:
  entity: binary_sensor
  name: Motion detected
  class: motion
  dps:
    - id: 1
      type: string
      name: sensor
      mapping:
        - dps_val: none
          value: OFF
          icon: "mdi:motion-sensor-off"
        - dps_val: pir
          value: ON
          icon: "mdi:motion-sensor"
secondary_entities:
  - entity: sensor
    name: Current Luminance
    class: illuminance
    dps:
      - id: 6
        type: integer
        name: sensor
        unit: lx
        class: measurement
        readonly: true
  - entity: sensor
    name: Battery Level
    class: battery
    dps:
      - id: 4
        type: integer
        name: sensor
        readonly: true
        unit: "%"
  - entity: select
    name: Sensitivity
    icon: "mdi:human-greeting-proximity"
    category: config
    dps:
      - id: 9
        name: option
        type: string
        mapping:
          - dps_val: "low"
            value: "Low"
          - dps_val: "middle"
            value: "Middle"
          - dps_val: "high"
            value: "High"
  - entity: select
    name: Keep time
    icon: "mdi:human-greeting-proximity"
    category: config
    dps:
      - id: 10
        name: option
        type: string
        mapping:
          - dps_val: "30s"
            value: "30"
          - dps_val: "60s"
            value: "60"
          - dps_val: "120s"
            value: "120"

```
