### ISSUE TITLE
Request support for Smart Curtain Motor

### ISSUE THREAD

**Issue by darki73** [make-all/tuya-local#583]
# Information about DPS mappings
```
Device matches whm04_doorbell with quality of 83%. DPS: {"updated_at": 1680350478.3538263, "1": "close", "2": 0, "3": 16, "6": true, "7": "closing", "101": true}
```

# DPS Mappings
## Derived Mappings

| Name | Pretty Name | Actions | DPS | States | Visibility |
| ---- | ----------- | ------- | --- | ------ | ---------- |
| control | Control | Send & Report | 1 |   open / close / stop / continue | exposed |
| percent_control | Curtain position setting | Send & Report | 2 |   0-100 | exposed |
| percent_state | Current curtain position | Report Only | 3 |   0-100 | exposed |
| auto_power | Auto Power | Send & Report | 6 |   true / false | exposed |
| work_state | Work State | Report Only | 7 |   opening / closing | exposed |
| situation_set | Situation Set | Report Only | 11 |   fully_open / fully_closed | exposed |
| fault | Fault | Report Only | 12 |   0 | exposed |
| motor_direction | Motor Direction | Send & Report | 101 |   true / false | hidden |
| limit_setting | Limit Setting | ??? | 102 |   ??? | hidden |

## Standard Instruction Set
| Code            | Type    | Values |
| --------------- | ------- | ------ |
| control         | Enum    | { "range": [    "open",    "stop",    "close",    "continue"  ] }" |
| percent_control | Integer | { "unit": "%",  "min": 0,  "max": 100,  "scale": 0,  "step": 1 }"  |
| auto_power      | Boolean | { true, false }                                                    |

## Standard Status Set
| Code            | Type    | Values |
| --------------- | ------- | ------ |
| control         | Enum    | { "range": [  "open",  "stop",  "close",  "continue"] }    |
| percent_control | Integer | { "unit": "%","min": 0,"max": 100,"scale": 0,"step": 1 }   |
| percent_state   | Integer | { "unit": "%","min": 0,"max": 100,"scale": 0,"step": 1 }   |
| auto_power      | Boolean | { true, false }                                            |
| work_state      | Enum    | { "range": [  "opening",  "closing"] }                     |
| situation_set   | Enum    | { "range": [  "fully_open",  "fully_close"] }              |
| fault           | Bitmap  | { "label": [  "motor_fault"] }                             |

# Product ID
```
h2wipnagcunsar5r
```

# Example Configuration
```yaml
name: Smart Curtain Motor
products:
  - id: h2wipnagcunsar5r
    name: 智能窗帘电机
primary_entity:
  entity: cover
  class: curtain
  category: config
  name: Smart Curtain Motor
  mode: auto
  dps:
    - id: 1
      type: string
      name: control
      persist: true
      mapping:
        - dps_val: open
          value: open
        - dps_val: close
          value: close
        - dps_val: stop
          value: stop
        - dps_val: continue
          value: continue
    - id: 2
      type: integer
      name: position
      unit: "%"
      persist: true
      range:
        min: 0
        max: 100
        step: 1
        scale: 0
    - id: 3
      type: integer
      name: current_position
      unit: "%"
      persist: false
      range:
        min: 0
        max: 100
        step: 1
        scale: 0
    - id: 7
      type: string
      name: action
      mapping:
        - dps_val: opening
          constraint: current_position
          conditions:
            - dps_val: 100
              value: opened
            - dps_val: null
              value: opened
            - value: opening
        - dps_val: closing
          constraint: current_position
          conditions:
            - dps_val: 0
              value: closed
            - dps_val: null
              value: closed
            - value: closing
secondary_entities:
  - entity: switch
    category: config
    name: Reverse Motor Direction
    dps:
      - id: 101
        type: boolean
        name: motor_direction
  - entity: switch
    category: config
    name: Auto Power
    dps:
      - id: 6
        type: boolean
        name: auto_power
```

# Information about how the device functions

The device itself is a motor, which can be installed onto the rails and the is able to move the curtains.

This device worked pretty well with the provided configuration, however, after a couple of days, curtains started to try and close themselves automatically with no reason whatsoever.
Even worse, even if they are closed, they will still try to close and while doing so, they were stressing out the motor which in turn was making awful sound.

After digging on the Tuya IoT website, i've noticed that motors (i have 3) stopped reporting their state back to the cloud (state changes are not reflected, however, whenever i execute commands through the IoT cloud, motors behave correctly and report an actual state).

I've been testing this configuration for quite some time before submitting a PR, however, turns out it is borderline unusable for some reason.

I've tried to provide as much details as possible, maybe "native" support from maintainer or someone who faced the similar issue will be much more stable.

Thank you!

**Comment by darki73** [comment]
This is the new configuration file for the device, some fields are marked as optional due to the fact that device might not initially report them, however, after opening/closing it a couple of times (or just after a period of time) those values become available, hence populated. Also, sometimes some of them are not reported unless they are explicitly set by the user (for example motor_direction, you need to toggle it for the device to report its status)

```yaml
name: Smart Curtain Motor
products:
  - id: h2wipnagcunsar5r
    name: 智能窗帘电机
primary_entity:
  entity: cover
  class: curtain
  category: config
  name: Smary Curtain Motor
  mode: auto
  dps:
    - id: 1 # control
      type: string
      name: control
      persist: true
      mapping:
        - dps_val: open
          value: open
        - dps_val: close
          value: close
        - dps_val: stop
          value: stop
        - dps_val: continue
          value: continue
    - id: 2 # percent_control
      type: integer
      name: position
      persist: true
      optional: true
      range:
        min: 0
        max: 100
        step: 1
        scale: 0
      unit: '%'
    - id: 3 # percent_state
      type: integer
      name: current_position
      readonly: true
      optional: true
      range:
        min: 0
        max: 100
        step: 1
        scale: 0
      unit: '%'
    - id: 7 # work_state (opening, closing)
      type: string
      name: action
      readonly: true
      optional: true
      mapping:
        - dps_val: opening
          constraint: current_position
          conditions:
            - dps_val: 100
              value: opened
            - dps_val: null
              value: opened
            - value: opening
        - dps_val: closing
          constraint: current_position
          conditions:
            - dps_val: 0
              value: closed
            - dps_val: null
              value: closed
            - value: closing
    - id: 11 # situation_set (fully_open, fully_close)
      type: boolean
      name: open
      readonly: true
      optional: true
      mapping:
        - dps_val: fully_open
          value: true
        - dps_val: fully_close
          value: false
secondary_entities:
  - entity: switch
    category: config
    name: Reverse Motor Direction
    dps:
      - id: 101 # motor_direction
        type: boolean
        name: switch
        optional: true
        mapping:
          - dps_val: true
            value: true
          - dps_val: false
            value: false
          - dps_val: null
            value: false
  - entity: switch
    category: config
    name: Auto Power
    dps:
      - id: 6 # auto_power
        type: boolean
        name: switch
        optional: true
  - entity: switch
    category: config
    name: Limit Setting
    dps:
      - id: 102 # limit_setting
        type: boolean
        name: switch
        optional: true
        mapping:
          - dps_val: true
            value: true
          - dps_val: false
            value: false
          - dps_val: null
            value: false
  - entity: binary_sensor
    name: Motor
    class: problem
    category: diagnostic
    dps:
      - id: 12 # motor_fault
        type: bitfield
        name: sensor
        mapping:
          - dps_val: -1
            value: false
          - dps_val: 0
            value: false
          - dps_val: null
            value: false
          - value: true
```

But the issue with device starting misbehave randomly still persists
