### ISSUE TITLE
Request support for ROJECO Pet Feeder

### ISSUE THREAD

**Issue by antonio1475** [make-all/tuya-local#585]
# Log Message

```
This error originated from a custom integration.

Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:46
Integration: Tuya Local (documentation, issues)
First occurred: 15:41:27 (2 occurrences)
Last logged: 15:41:27

Device matches None with quality of 0%. DPS: {"updated_at": 1680356485.1268923, "2": true, "3": 1, "4": "standby", "10": 100, "13": 0, "14": 1, "17": true, "23": true}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "category": "cwwsq",
    "functions": [
      {
        "code": "meal_plan",
        "dp_id": 1,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "quick_feed",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "manual_feed",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "light",
        "dp_id": 17,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "slow_feed",
        "dp_id": 23,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "factory_reset",
        "dp_id": 24,
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "meal_plan",
        "dp_id": 1,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "quick_feed",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "manual_feed",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "feed_state",
        "dp_id": 4,
        "type": "Enum",
        "values": "{\"range\":[\"standby\",\"feeding\",\"done\"]}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "charge_state",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "feed_report",
        "dp_id": 14,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "light",
        "dp_id": 17,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "slow_feed",
        "dp_id": 23,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "factory_reset",
        "dp_id": 24,
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1680356550607,
  "tid": "0c6cf525d09311ed8c18e22f7855219f"
}
```

# Product ID
    "product_id": "hbiwalfrzqfzv2cq",
    "product_name": "ROJECO Pet Feeder",

# Example configuration

```
name: ROJECO Pet Feeder
product:
  - id: hbiwalfrzqfzv2cq
primary_entity:
  entity: button
  class: restart
  icon: "mdi:food-drumstick"
  name: Quick feed
  dps:
    - id: 2
      type: boolean
      name: button
secondary_entities:
  - entity: sensor
    icon: "mdi:paw"
    name: Last amount
    category: diagnostic
    dps:
      - id: 14
        name: sensor
        type: integer
        unit: portions
  - entity: sensor
    category: diagnostic
    name: Feed state
    icon: "mdi:valve"
    class: enum
    dps:
      - id: 4
        name: sensor
        type: string
        mapping:
          - dps_val: standby
            value: Standby
          - dps_val: feeding
            value: Feeding
          - dps_val: done
            value: Done
  - entity: number
    name: Manual Feed
    category: config
    icon: "mdi:paw"
    dps:
      - id: 3
        type: integer
        name: value
        unit: portions
        range:
          min: 1
          max: 60
  - entity: switch
    name: Slow Feed
    category: config
    icon: "mdi:speedometer-slow"
    dps:
      - id: 23
        type: boolean
        name: switch
  - entity: switch
    icon: "mdi:alarm-light"
    name: Indicator
    category: config
    dps:
      - id: 17
        type: boolean
        name: switch
  - entity: binary_sensor
    name: Empty food
    icon: "mdi:seed-off-outline"
    class: problem
    category: diagnostic
    dps:
      - id: 13
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 2
            value: true
          - value: false
```

# Information about how the device functions

Scanned manual: [ROJECO Automatic Pet Feeder.pdf](https://github.com/make-all/tuya-local/files/11129694/ROJECO.Automatic.Pet.Feeder.pdf)
