### ISSUE TITLE
climate: _Unrecognised HVAC Action 1 ignored

### ISSUE THREAD

**Issue by martin3000** [make-all/tuya-local#616]
For my Owon PCT513 thermostat, I get the following warnings in the log:
>_Unrecognised HVAC Action 1 ignored

The warning appears in the early morning. There are around 7 warnings per minute!

The PCT513 has a feature to start heating before it is scheduled. For example if I want 21°C at 8:00 in the morning, the thermostat can already start at 6:00 so that the target temperature is reached at 8:00. I guess the hvac action 1 is that pre-heating phase.

But since I do not understand how the owon_pct513_thermostat.yaml works, I cannot change it.

Does it need an entry

```
        - dps_val: 1
          value: heating
```
?

**Comment by make-all** [comment]
Probably it needs that additional mapping. But it is a bit strange that it uses a numeric value only for that one state.  Are there other numeric states it uses?

**Comment by martin3000** [comment]
> Are there other numeric states it uses?

Where can I see that?

**Comment by craibo** [comment]
This has started occurring for me today on a device I have had no problem with previously.

This error originated from a custom integration.

Logger: custom_components.tuya_local.climate
Source: custom_components/tuya_local/climate.py:291
Integration: Tuya Local (documentation, issues)
First occurred: 15:47:45 (545 occurrences)
Last logged: 20:12:15

_Unrecognised HVAC Action None ignored
_Unrecognised HVAC Action True ignored
_Unrecognised HVAC Action False ignored

**Comment by martin3000** [comment]
I have done this locally:
```
        action = self._hvac_action_dps.get_value(self._device)
        if action is None:  #jms
            return None     #jms

```

**Comment by martin3000** [comment]
This fixed it for me (devices/owon_pct513_thermostat.yaml):
```
    - id: 129
      type: string
      name: hvac_action
      mapping:
        - dps_val: coolfanon
          value: cooling
        - dps_val: alloff
          value: idle
        - dps_val: fanon
          value: fan
        - dps_val: heatfanon
          value: heating
        - dps_val: "1"
          value: heating

```
