### ISSUE TITLE
Moes 3 Gang smart switch

### ISSUE THREAD

**Issue by tomassj9** [make-all/tuya-local#641]
# Log Message
```
2023-04-24 12:43:40.387 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches somgom_double_switch with quality of 71%. DPS: {"updated_at": 1682333020.061975, "1": false, "2": false, "3": false, "7": 0, "8": 0, "9": 0, "16": false}
2023-04-24 12:43:40.388 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings
```
  "result": {
    "category": "kg",
    "functions": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "switch_backlight",
        "type": "Boolean",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "switch_1",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_3",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_3",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "relay_status",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\"]}"
      },
      {
        "code": "switch_backlight",
        "type": "Boolean",
        "values": "{}"
      }
    ]
  },
```

# Product ID
m4viuhaiez8qjswh / Moes 3 Gang smart switch

# Information about how the device functions
It's a 3 gang switch. It has timers for every gang. It also has backlight, it can be toggled on / off. Also you can set the power on state (on/off/last)

# Working Configuration
```
name: Triple switch with timer and backlight
products:
  - id: m4viuhaiez8qjswh
    name: Moes 3 Gang smart switch
primary_entity:
  entity: light
  name: "Gang 1"
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: light
    name: "Gang 2"
    dps:
      - id: 2
        name: switch
        type: boolean
  - entity: light
    name: "Gang 3"
    dps:
      - id: 3
        name: switch
        type: boolean
  - entity: light
    name: Backlight
    category: config
    dps:
      - id: 16
        name: switch
        type: boolean
  - entity: number
    category: config
    name: "Timer Gang 1"
    icon: "mdi:timer"
    dps:
      - id: 7
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: "Timer Gang 2"
    icon: "mdi:timer"
    dps:
      - id: 8
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: "Timer Gang 3"
    icon: "mdi:timer"
    dps:
      - id: 9
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: select
    category: config
    name: "Initial state"
    icon: "mdi:toggle-switch"
    dps:
      - id: 14
        type: string
        name: option
        optional: true
        mapping:
          - dps_val: 0
            value: "On"
          - dps_val: 1
            value: "Off"
          - dps_val: 2
            value: "Last State"
```
