### ISSUE TITLE
Is current code able to support gateway?

### ISSUE THREAD

**Issue by darek-margas** [make-all/tuya-local#70]
I've got some unique gateway for irrigation but it works as zigbee (except it is not zigbee).
I've tested it with tuya-cli and it works perfectly if I specify cid for child device.
Thing is - would it be possible to pass cid over this code?

**Comment by make-all** [comment]
I'll need to look into what this entails further. Most likely it will need some upstream changes to the tinytuya library, as the current documentation does not mention gateways at all.

**Comment by darek-margas** [comment]
I think it is just payload. There is some clue in localtuya repo in "zigbee gateway" branch. 
What that would need is optional CID field added to initial config window and then it has to pass CID pretty much as they tried in localtuya. I've heard for set command to succeed ID must be from child device but that is all about initial fields.

Tuya API shows gateway as this:
 
[ { name: 'Tuya Alfresco',
    id: 'XXXX as ID for gateway',
    key: 'KEY' },
  { name: 'Hollman Wi Fi Hub',
    id: 'XXXX as id for child device',
    key: 'KEY',
    subDevices:
     [ { name: 'WX1 Tap', id: 'XXXX tap ID', cid: '131' },
       { name: 'Wi-Fi Socket',
         id: 'XXX another ID',
         cid: '13B' } ] },


tuya-cli get --ip 192.168.0.1 --id XXXX tap ID --key KEY --cid 131 --full --protocol-version 3.3
{ dps:
   { '101': 0,
     '102': 0,
     '103': 5,
     '105': '2',
     '106': '3',
     '107': 12,
     '108': true,
     '113': '72',
     '114': '24',
     '115': false,
     '116': false,
     '117': true,
     '119': '1',
     '120': 0,
     '125': false,
     '127': 'HOL9-018-023-000-000' },
  cid: '131' }

**Comment by darek-margas** [comment]
I managed to alter localtuya to get it working.

**Comment by darek-margas** [comment]
I looked today at tinytuya. It seems the same trick will work, section to change is in init, lines 350-400. Without changes there it won't work.

**Comment by LesTR** [comment]
Hi @make-all and @darek-margas , Just FYI:

I [added](https://github.com/jasonacox/tinytuya/pull/222) support for devices connected to zigbee gateway into tinytuya. I'm preparing PR which adds support for tuya-local, right now I made some changes in my fork and it looks good. I'll open PR when it is ready.

**Comment by make-all** [comment]
tinytuya library is now updated to 1.9.1, so the support for making changes to support hubs is available in the underlying library.

This will be useful also for #170

**Comment by illuzn** [comment]
@LesTR I'm putting up my hand if you need a beta tester. I've got some Tuya Zigbee irrigation valves that I would love to get working with this.

**Comment by LesTR** [comment]
Hi @illuzn,
my changes were broken after https://github.com/jasonacox/tinytuya/pull/226 and I still don't have time to fix it. Hopefully, I'll find some time next week.

**Comment by make-all** [comment]
Since I have made lots of conflicting changes over the past couple of releases, I took the opportunity to rebase your main branch in https://github.com/make-all/tuya-local/tree/LesTR/main

But I don't have any suitable devices for testing, so I can't judge whether it is actually working or not.  But I did fix the config and tests that you added so at least those pass now.

**Comment by CiaoBelli87** [comment]
Hi there, tried [LesTR integration ](https://github.com/make-all/tuya-local/tree/LesTR/main) with the Holman WX1 water valve without luck. Log list attached 
![image](https://user-images.githubusercontent.com/114127780/213854030-69e73ab0-e0fa-4df0-9521-6eb4b0bdb11f.png)

**Comment by make-all** [comment]
I just rebased that branch again, as there are a number of fixes in main over the past week, including I think a fix for the "Detected blocking call..."

**Comment by lovaselek** [comment]
Hi,
I failed to configure tuya local from the [LesTR integration](https://github.com/make-all/tuya-local/tree/LesTR/main).
I have a "Tuya ZigBee Gateway Bridge Wireless Smart Hub" with 10 "AUBESS Tuya ZigBee Temperature Humidity Sensor" paired with the Smart Life app.

I tested with tinytuya python package ver 1.10.1 and works the requests for temperature and humidity values.

I created a configuration file for the AUBESS temperature/humidity sensor:

```
name: Temperature Humidity Sensor
products:
  - id: xr3htd96
primary_entity:
  entity: sensor
  name: Current temperature
  class: temperature
  dps:
    - id: 1
      type: integer
      name: sensor
      unit: C
      class: measurement
      mapping:
        - scale: 10
secondary_entities:
  - entity: sensor
    name: Current humidity
    class: humidity
    dps:
      - id: 2
        type: integer
        name: sensor
        unit: "%"
        class: measurement
  - entity: sensor
    name: Battery
    class: battery
    category: diagnostic
    dps:
      - id: 4
        name: sensor
        type: integer
```


I replaced the contents in custom_components/tuya_local folder from this branch.
Log list:
![image](https://user-images.githubusercontent.com/98054658/216461929-e3e59f69-2f28-4f0e-a71d-facd3c54341d.png)
Detailed error:
![image](https://user-images.githubusercontent.com/98054658/216462337-955452ca-4409-4ad6-b7e4-803a80ee4b7e.png)

The id after the KeyError ist from Sub device ID from new integration page.
The tinytuya version used by Home Assistant: 1.9.1
The previously configured Wi-Fi device integrations only works after I delete them and re-integrate them.

I don't know if the gateway should be added separately as a device, or if only the devices should be added to the integrations, I couldn't find a description for this. However, I was not able to add the gateway separately.

Thank you for your time and consideration.

Best regards,
lovaselek
