### ISSUE TITLE
Request support for Goldair GPDH340

### ISSUE THREAD

**Issue by nicole-ashley** [make-all/tuya-local#727]
This is another dehumidifier from Goldair. It's quite different to the existing dehumidifier in this repo (and indeed in my old Goldair repo) which was model GPDH420. 

# Log Message

Sorry this isn't from HA logs as I don't have it configured there, but it's from Tuya CLI which retains property types:
```js
dps: {
  '1': true,
  '2': '4',
  '4': 55,
  '6': '1',
  '11': 0,
  '103': 20,
  '104': 73,
  '105': 24,
  '106': false,
  '107': false,
  '108': false,
  '109': false
}
```

# Information about DPS mappings

```json
{
  "result": {
    "category": "cs",
    "functions": [],
    "status": [
      {
        "code": "fault",
        "dp_id": 11,
        "type": "Bitmap",
        "values": "{\"label\":[\"E1\",\"E2\"]}"
      }
    ]
  },
  "success": true,
  "t": 1684440121016,
  "tid": "da152d5bf5b611ed9b28425442ef4a7b"
}
```

* Room Humidity: 104
* 机型位 ("Model position" / "Model bit"?): 105
* Child Lock: 106
* Fault: 11
* hide (this actually controls the front display and is a "show" state not a "hide" state): 107
* Clean Filter: 108
* 泵浦键 ("Pump key"?): 109
* 室内华氏温度 ("Indoor temperature in Fahrenheit" except it's a Boolean 🤷‍♀️): 112

# Product ID

According to the Tuya API:
* Product Name: GOLDAIR PLATINUM 40L DEHUMIDIFIER
* Product ID: `okwjubkm9ndbq3j` (versus the GPDH420 which is `gynthidZEhTUCoMN`)

# Information about how the device functions

This device is much simpler than the GPDH420 in that there are no cross-functional conditionals. Generally anything you set will just work. However there are some quirks:

* There is a mode (dps ID 2) with the value of `2`. This seems to be an "unknown" mode, as the device does not remember the last mode through power loss and when it turns back on none of the mode LEDs are lit. In the app this mode is called "Custom" but cannot be set. You could either A) include it in the mode list like it is in the app but the API will error if you try to set it, or B) don't include it in the mode list at all and have the mode dropdown in HA empty when this is set (this is my preference as as it's a more accurate reflection of the device's own control panel).
* Timer cannot be read or set from the API
* The device doesn't seem to have a defrosting status unlike the GPDH420
* After cleaning the filter you need to press the hardware button to reset the status. I'm unsure if this can be done via the API, I suspect not but will report back when we have our first filter clean event

# Proposed device file

Here's how I would configure the device based on my experimentation with the app and API. It's my first time using this format so I may have made some incorrect configuration assumptions. In this I have used labels from the device's own control panel (which don't necessarily line up with the app) as I feel it's much better to have them the same as the physical device you're looking at.

```yml
name: Goldair GPDH420 dehumidifier
legacy_type: dehumidifier
primary_entity:
  entity: humidifier
  class: dehumidifier
  dps:
    - id: 1
      name: switch
      type: boolean
      mapping:
        - dps_val: false
          icon: "mdi:air-humidifier-off"
          icon_priority: 3
        - dps_val: true
          icon: "mdi:air-humidifier"
          icon_priority: 6
    - id: 2
      name: mode
      type: string
      mapping:
        - dps_val: "4"
          value: "Sleeping space"
        - dps_val: "5"
          value: "Living space"
        - dps_val: "6"
          value: "Basement"
        - dps_val: "7"
          value: "Continuous"
      # Cannot be set, only happens after power outage
      # - dps_val: "2"
      #   value: "None"
    - id: 4
      type: integer
      name: humidity
      range:
        min: 35
        max: 80
      mapping:
        - step: 5
    - id: 11
      type: bitfield
      name: error
      mapping:
        - dps_val: 16
          value: "Tank full or missing"
          icon: "mdi:cup-water"
          icon_priority: 1
        - dps_val: 0
          value: "OK"
      readonly: true
    - id: 103
      type: integer
      name: current_temperature
      readonly: true
    - id: 104
      type: integer
      name: current_humidity
      readonly: true
    - id: 108
      type: boolean
      name: filter_clean_required
      mapping:
        - dps_val: true
          icon: "mdi:air-filter"
          icon_priority: 2
      readonly: true
secondary_entities:
  - entity: fan
    dps:
      - id: 1
        type: boolean
        name: switch
      - id: 6
        type: string
        name: speed
        mapping:
          - dps_val: "1"
            value: 30
          - dps_val: "2"
            value: 60        
          - dps_val: "3"
            value: 100
  - entity: light
    name: Front display
    category: config
    dps:
      - id: 107
        type: boolean
        name: switch
        mapping:
          - dps_val: true
            value: true
            icon: "mdi:numeric"
          - dps_val: true
            value: true
            icon: "mdi:numeric-off"
  - entity: lock
    name: Child lock
    category: config
    dps:
      - id: 106
        type: boolean
        name: lock
        mapping:
          - dps_val: true
            icon: "mdi:hand-back-right-off"
          - dps_val: false
            icon: "mdi:hand-back-right"
  - entity: sensor
    name: Current temperature
    class: temperature
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: C
        class: measurement
        readonly: true
  - entity: sensor
    name: Current humidity
    class: humidity
    dps:
      - id: 104
        type: integer
        name: sensor
        class: measurement
        unit: "%"
        readonly: true
  - entity: binary_sensor
    name: Tank
    class: problem
    category: diagnostic
    dps:
      - id: 11
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true
  - entity: binary_sensor
    name: Filter clean required
    class: problem
    category: diagnostic
    dps:
      - id: 108
        type: boolean
        name: sensor
```
