### ISSUE TITLE
Add johgee Water timer valve

### ISSUE THREAD

**Issue by fcrozat** [make-all/tuya-local#747]
I have a Bluetooth water timer, associated with a BT gateway which is pretty similar to HCT-611 Water timer, but the matching code is unable to recognize it properly:

From the log, I'm getting:

Device matches asc_wifi_circuit_breaker with quality of 22%. DPS: {"updated_at": 1685477584.949048, "1": true, "4": 0, "7": 32, "9": 21658, "10": "cancel", "11": 80, "12": "manual", "14": false, "15": 7201}

DPS dump:

attributes
{
  "result": {
    "category": "sfkzq",
    "functions": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "time_use",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":2592000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "weather_delay",
        "dp_id": 10,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}"
      },
      {
        "code": "countdown",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "smart_weather",
        "dp_id": 13,
        "type": "Enum",
        "values": "{\"range\":[\"sunny\",\"cloudy\",\"rainy\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 7,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "time_use",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":2592000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "weather_delay",
        "dp_id": 10,
        "type": "Enum",
        "values": "{\"range\":[\"cancel\",\"24h\",\"48h\",\"72h\"]}"
      },
      {
        "code": "countdown",
        "dp_id": 11,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "work_state",
        "dp_id": 12,
        "type": "Enum",
        "values": "{\"range\":[\"auto\",\"manual\",\"idle\"]}"
      },
      {
        "code": "smart_weather",
        "dp_id": 13,
        "type": "Enum",
        "values": "{\"range\":[\"sunny\",\"cloudy\",\"rainy\"]}"
      },
      {
        "code": "use_time_one",
        "dp_id": 15,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1685392502252,
  "tid": "4983f0c0fe6011edac8032ebdb7f4f6c"
}

I tried to create a modified version of HCT-611 yaml file but didn't change the matching code.

**Comment by make-all** [comment]
New devices are not bugs.  Similar functionality means nothing for compatibility in the Tuya ecosystem, so a similar device existing does not mean it will match..

**Comment by fcrozat** [comment]
Sorry about that. I might have a clue why the matching code failed, after running tinytuya:
bluetooth bridge used to connect to Water timer has product id "yrzel5nutomegk6z", which is matching "ASC (Wi-Fi)" yaml device. Only "ASC (Wi-Fi)", "Simple Switch", "Simple Switch Timer" and "Simple Switch timerv2" are available to select.

I've tried with the added file without any luck:

name: Water valve
product:
  - id: nxquc5lb
primary_entity:
  entity: switch
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 12
      type: string
      name: state
secondary_entities:
  - entity: sensor
    name: Battery
    class: battery
    category: diagnostic
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: "%"
        mapping:
          - scale: 1
  - entity: sensor
    name: time_use
    class: battery
    category: diagnostic
    dps:
      - id: 9
        type: integer
        name: sensor
        unit: "%"
        range:
          min: 0
          max: 2592000
        mapping:
          - scale: 0
            step: 1
  - entity: sensor
    name: time_use_one
    class: battery
    category: diagnostic
    dps:
      - id: 15
        type: integer
        name: sensor
        unit: "%"
        range:
          min: 0
          max: 2592000
        mapping:
          - scale: 0
            step: 1
  - entity: select
    name: Weather delay
    icon: "mdi:weather-cloudy-clock"
    category: config
    dps:
      - id: 10
        type: string
        name: option
        mapping:
          - dps_val: cancel
            value: "Off"
          - dps_val: "24h"
            value: "1 day"
          - dps_val: "48h"
            value: "2 days"
          - dps_val: "72h"
            value: "3 days"
  - entity: number
    name: Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 11
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: select
    name: Smart weather
    icon: "mdi:sun-wireless"
    category: config
    dps:
      - id: 13
        type: string
        name: option
        mapping:
          - dps_val: sunny
            value: Sunny
          - dps_val: clear
            value: Clear
          - dps_val: cloudy
            value: Cloudy
          - dps_val: rainy
            value: Rain

**Comment by make-all** [comment]
Your log has dps 1, 4, 7, 9, 10, 11, 12, 14, 15
Your config file has 1, 7, 9, 10, 11, 12, 13, 15

This is why they are not matching.

**Comment by fcrozat** [comment]
Thanks a lot, I adapted the file and it is now properly recognized. I haven't yet if communication is working well with the valve.

I still have some issues with id: 10 causing an exception for the "option" part.

```
name: Johgee Water Timer Valve
products:
  - id: c8800fd30884068f
primary_entity:
  entity: switch
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 12
      type: string
      name: state
secondary_entities:
  - entity: sensor
    name: Battery
    class: battery
    category: diagnostic
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: "%"
  - entity: sensor
    name: Fault reporting
    category: diagnostic
    dps:
      - id: 4
        type: integer
        name: sensor
  - entity: number
    name: time_use
    category: config
    dps:
      - id: 9
        type: integer
        name: value
        range:
          min: 0
          max: 2592000
        unit: min
        mapping:
          - scale: 60
            step: 60
  - entity: sensor
    name: use_time_one
    category: diagnostic
    dps:
      - id: 15
        type: integer
        name: sensor
        range:
          min: 0
          max: 2592000
        unit: min
        mapping:
          - scale: 60
            step: 60
  - entity: select
    name: Weather delay
    icon: "mdi:weather-cloudy-clock"
    category: config
    dps:
      - id: 10
        type: string
        name: option
        mapping:
          - dps_val: "cancel"
            value: "Off"
          - dps_val: "24h"
            value: "1 day"
          - dps_val: "48h"
            value: "2 days"
          - dps_val: "72h"
            value: "3 days"
  - entity: number
    name: Timer
    category: config
    icon: "mdi:timer"
    dps:
      - id: 11
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
#  - entity: select
#    name: Smart weather
#    icon: "mdi:sun-wireless"
#    category: config
#    dps:
#      - id: 13
#        type: string
#        name: option
#        mapping:
#          - dps_val: sunny
#            value: Sunny
#          - dps_val: clear
#            value: Clear
#          - dps_val: cloudy
#            value: Cloudy
#          - dps_val: rainy
#            value: Rain
  - entity: select
    name: Smart weather switch
    icon: "mdi:sun-wireless"
    category: config
    dps:
      - id: 14
        type: boolean
        name: switch
```

**Comment by fcrozat** [comment]
I did some tests:
- main switch entity is working
- Timer is working: initial value is properly set from HA and is decreasing when valve is opened
- use_time is just a counter, I've updated the file to move it from number to sensor entity.

I still need to test when use_time_one is changing and if should be a sensor or number entity. It might be linked to the physical button override on the device to manually open / close the valve. 

Reading id:10, it is probably only usable in sync with the Tuya IoT platform to store if a delay should be set or not depending on weather condition, since those conditions are not handled in the device itself but on Tuya cloud platform. But I still need to figure how to properly handle it in yaml file to not cause exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tuya_local/select.py", line 14, in async_setup_entry
    await async_tuya_setup_platform(
  File "/config/custom_components/tuya_local/helpers/config.py", line 38, in async_tuya_setup_platform
    data[ecfg.config_id] = entity_class(device, ecfg)
  File "/config/custom_components/tuya_local/select.py", line 34, in __init__
    self._option_dps = dps_map.pop("option")
KeyError: 'option'

**Comment by make-all** [comment]
The error is complaining that there is no "option" under a select entity.  It is actually complaining about dp 14, not 10, as you have labelled that as "switch".  And since it is boolean, it probably is a switch, and it is the entity type that is incorrect.

**Comment by fcrozat** [comment]
Thanks for your help, I've fix the file and added support for all the remaining DPs which could be found on Tuya IoT platform for this device.

The only challenging part are the automated schedule, which is somehow encoded (maybe base64). However it is probably not that useful when using home assistant. I found very interesting informations at https://github.com/Koenkk/zigbee2mqtt/issues/16671

Smart weather is also probably not very useful when used with home assistant.

final file attached:
```
name: Johgee Water Timer Valve
products:
  - id: c8800fd30884068f
primary_entity:
  entity: switch
  dps:
    - id: 1
      type: boolean
      name: switch 
secondary_entities:
  - entity: sensor
    name: Battery
    class: battery
    category: diagnostic
    dps:
      - id: 7
        type: integer
        name: sensor
        unit: "%"
  - entity: sensor
    name: Fault reporting
    category: diagnostic
    dps:
      - id: 4
        type: integer
        name: sensor
  - entity: sensor
    name: Operation
    category: diagnostic
    dps:
      - id: 12
        type: string
        name: sensor
  - entity: sensor
    name: Automated Irrigation Schedule
    category: config
    dps:
      - id: 17
        type: string
        name: sensor
        optional: true
  - entity: sensor
    name: Automated Cycle and Soak schedule
    category: config
    dps:
      - id: 16
        type: string
        name: sensor
        optional: true
  - entity: sensor
    name: Accumulated use time
    category: diagnostic
    dps:
      - id: 9
        type: integer
        name: sensor
        range:
          min: 0
          max: 2592000
        unit: min
        mapping:
          - scale: 60
            step: 60
  - entity: sensor
    name: Last use time
    category: diagnostic
    dps:
      - id: 15
        type: integer
        name: sensor
        range:
          min: 0
          max: 2592000
        unit: min
        mapping:
          - scale: 60
            step: 60
  - entity: select
    name: Weather delay
    icon: "mdi:weather-cloudy-clock"
    category: config
    dps:
      - id: 10
        type: string
        name: option
        mapping:
          - dps_val: cancel
            value: "Off"
          - dps_val: "24h"
            value: "1 day"
          - dps_val: "48h"
            value: "2 days"
          - dps_val: "72h"
            value: "3 days"
  - entity: number
    name: Irrigation time
    category: config
    icon: "mdi:timer"
    dps:
      - id: 11
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: select
    name: Smart weather
    icon: "mdi:sun-wireless"
    category: diagnostic
    dps:
      - id: 13
        type: string
        name: option
        optional: true
        readonly: true
        mapping:
          - dps_val: sunny
            value: Sunny
          - dps_val: clear
            value: Clear
          - dps_val: cloudy
            value: Cloudy
          - dps_val: rainy
            value: Rain
  - entity: switch
    name: Smart weather switch
    icon: "mdi:sun-wireless"
    category: config
    dps:
      - id: 14
        type: boolean
        name: switch
```
