### ISSUE TITLE
Request support for [Wi-Fi Alarm with Doorbell]

### ISSUE THREAD

**Issue by g470258** [make-all/tuya-local#763]
# Log Message

```
Please paste logs here
```

# Information about DPS mappings

```
{
  "result": {
    "category": "mal",
    "functions": [
      {
        "code": "master_mode",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}"
      },
      {
        "code": "delay_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_time",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"分钟\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_alarm_sound",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_light",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_ringtone",
        "dp_id": 8,
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\"]}"
      },
      {
        "code": "switch_mode_light",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_sound",
        "dp_id": 12,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_light",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_low_battery",
        "dp_id": 17,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "muffling",
        "dp_id": 25,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_propel",
        "dp_id": 27,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_delay_time",
        "dp_id": 28,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_mode_dl_sound",
        "dp_id": 29,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "doorbell_volume",
        "dp_id": 30,
        "type": "Enum",
        "values": "{\"range\":[\"high\",\"low\",\"mute\"]}"
      },
      {
        "code": "master_state",
        "dp_id": 32,
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "factory_reset",
        "dp_id": 34,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sub_admin",
        "dp_id": 38,
        "type": "Raw",
        "values": "{}"
      }
    ],
    "status": [
      {
        "code": "master_mode",
        "dp_id": 1,
        "type": "Enum",
        "values": "{\"range\":[\"disarmed\",\"arm\",\"home\",\"sos\"]}"
      },
      {
        "code": "delay_set",
        "dp_id": 2,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "alarm_time",
        "dp_id": 3,
        "type": "Integer",
        "values": "{\"unit\":\"分钟\",\"min\":1,\"max\":60,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_alarm_sound",
        "dp_id": 4,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_alarm_light",
        "dp_id": 6,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_mode_light",
        "dp_id": 11,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_sound",
        "dp_id": 12,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_kb_light",
        "dp_id": 13,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "charge_state",
        "dp_id": 15,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "battery_percentage",
        "dp_id": 16,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_low_battery",
        "dp_id": 17,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "muffling",
        "dp_id": 25,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_msg",
        "dp_id": 26,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "switch_alarm_propel",
        "dp_id": 27,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "alarm_delay_time",
        "dp_id": 28,
        "type": "Integer",
        "values": "{\"unit\":\"秒\",\"min\":0,\"max\":300,\"scale\":0,\"step\":1}"
      },
      {
        "code": "switch_mode_dl_sound",
        "dp_id": 29,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "doorbell_volume",
        "dp_id": 30,
        "type": "Enum",
        "values": "{\"range\":[\"high\",\"low\",\"mute\"]}"
      },
      {
        "code": "master_state",
        "dp_id": 32,
        "type": "Enum",
        "values": "{\"range\":[\"normal\",\"alarm\"]}"
      },
      {
        "code": "master_information",
        "dp_id": 33,
        "type": "String",
        "values": "{\"maxlen\":255}"
      },
      {
        "code": "factory_reset",
        "dp_id": 34,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "sub_admin",
        "dp_id": 38,
        "type": "Raw",
        "values": "{}"
      }
    ]
  },
  "success": true,
  "t": 1685949187135,
  "tid": "6b912503037011eea795ce4cada2c678"
}
```

# Product ID

{
  "result": {
    "active_time": 1626781458,
    "category": "mal",
    "category_name": "Multifunctional Alarm",
    "create_time": 1626781458,
    "gateway_id": "",
    "icon": "smart/icon/ay1544185183501IhqNw/cc23e2e9cb3748bd0d139f3b5c8e1482.png",
    "id": "bf01c4d756fa629039d6oy",
    "ip": "xxx.xxx.xxx.xxx",
    "lat": "58.5793",
    "local_key": "xxxxxxxxxxxx",
    "lon": "49.6892",
    "model": "",
    "name": "doorbell",
    "online": true,
    "owner_id": "33617471",
    "product_id": "oqn2dj8otuhqhulr",
    "product_name": "Wi-Fi Alarm with Doorbell",
    "sub": false,
    "time_zone": "+03:00",
    "update_time": 1667055003,
    "uuid": "cb39392af5ddfa17"
  },
  "success": true,
  "t": 1685949913023,
  "tid": "1c36ac09037211eeac8032ebdb7f4f6c"
}

**Comment by g470258** [comment]
https://expo.tuya.com/product/825015

**Comment by g470258** [comment]
Add device
```
{
 "updated_at": 1686208913.1697307, "1": "disarmed", "2": 0, "3": 1, "4": true,
 "6": true, "8": "7", "11": true,
 "12": false, "13": false, "15": true, "16": 100, "17":
 true, "24": "Normal", "27": true, "28": 0, "29": false, "30": "low",
 "31": "0", "32": "normal", "34": false, "35": false, "36": "1",
 "37": "0", "39": "0", "40": "3"}
 ```

config

```
name: Doorbell
products:
  - id: bf01c4d756fa629039d6oy
    name: Alarm Doorbell
primary_entity:
  entity: button
  name: Alarm Disarm
  icon: "mdi:shield-off"
  dps:
    - id: 1
      type: string
      name: button
      mapping:
        - dps_val: "disarmed"
          value: true
secondary_entities:
  - entity: button
    name: Alarm Away arm
    icon: "mdi:shield-lock"
    dps:
      - id: 1
        type: string
        name: button
        mapping:
          - dps_val: "arm"
            value: true
  - entity: button
    name: Alarm Home
    icon: "mdi:shield-home"
    dps:
      - id: 1
        type: string
        name: button
        mapping:
          - dps_val: "home"
            value: true    
  - entity: button
    name: Alarm SOS
    icon: "mdi:shield-link-variant"
    dps:
      - id: 1
        type: string
        name: button
        mapping:
          - dps_val: "sos"
            value: true              

  - entity: switch
    name: Сountdown with a tick tone
    category: config
    icon: "mdi:metronome-tick"
    dps:
      - id: 29
        type: boolean
        name: switch  
  - entity: switch
    name: Door open\close notification
    category: config
    dps:
      - id: 12
        type: boolean
        name: switch  
  - entity: switch
    name: Door\windows unclosed notification
    category: config
    dps:
      - id: 13
        type: boolean
        name: switch  
  - entity: switch
    name: Doorbel notify
    category: config
    dps:
      - id: 27
        type: boolean
        name: switch  
  - entity: switch
    name: Alarm notify
    category: config
    icon: "mdi:alarm-bell"
    dps:
      - id: 6
        name: switch
        type: boolean        
  - entity: number
    category: config
    name: Alarm duration
    icon: "mdi:alarm-note"
    dps:
      - id: 3
        name: value
        type: integer
        range:
          min: 1
          max: 60
        unit: min
  - entity: number
    category: config
    name: Alarm output delay
    icon: "mdi:lock-clock"
    dps:
      - id: 2
        name: value
        type: integer
        range:
          min: 0
          max: 300
        unit: sec        

  - entity: switch
    name: Alarm sound
    category: config
    icon: "mdi:alarm-light"
    dps:
      - id: 4
        type: boolean
        name: switch
        
  - entity: switch
    name: Status indicator
    category: config
    icon: "mdi:alarm-light"
    dps:
      - id: 11
        type: boolean
        name: switch
        
  - entity: sensor
    name: Button battery
    class: battery
    category: diagnostic
    dps:
      - id: 16
        type: integer
        name: sensor
        unit: "%"
  - entity: binary_sensor
    name: Low battery alarm
    class: battery
    category: diagnostic
    dps:
      - id: 17
        type: boolean
        name: sensor 
        mapping:
          - dps_val: true
            value: false
          - value: true       
  - entity: select
    name: Volume doorbell
    category: config
    icon: "mdi:volume-high"
    dps:
      - id: 30
        name: option
        type: string
        mapping:
          - dps_val: "high"
            value: "High"
          - dps_val: "low"
            value: "Low"
          - dps_val: "mute"
            value: "Mute"   
          - dps_val: "upper-middle"
            value: "Upper middle" 
          - dps_val: "lower_middle"
            value: "Lower middle"             
  - entity: sensor
    name: Alarm mode
    icon: "mdi:alarm-bell"
    category: config
    dps:
      - id: 1
        type: string
        name: sensor
      - id: 32
        type: string
        name: Mode state
      - id: 24
        type: string
        name: Mode state2
        hidden: true        
      - id: 31
        type: string
        name: Ring tone set
      - id: 39
        type: string
        name: test6
        hidden: true        
      - id: 40
        type: string
        name: test7
        hidden: true
      - id: 11
        type: boolean
        name: button
        hidden: true
      - id: 35
        type: boolean
        name: buttoone
        hidden: true
      - id: 28
        type: integer
        name: alarm delay time 
      - id: 36
        type: integer
        name: test4
        hidden: true        
      - id: 37
        type: integer
        name: test5
        hidden: true 
        
        

  - entity: binary_sensor
    name: Ringing
    class: sound
    dps:
      - id: 26
        type: base64
        name: sensor
        optional: true
        persist: false
        mapping:
          - dps_val: null
            value: false
          - value: true
          
  - entity: binary_sensor
    name: AC power
    class: power
    category: diagnostic
    dps:
      - id: 15
        type: boolean
        name: sensor  
       
  - entity: binary_sensor
    name: Factory reset read only
    icon: "mdi:close-octagon"
    category: diagnostic
    dps:
      - id: 34
        type: boolean
        name: sensor         
  - entity: select
    category: config
    name: Ring tone
    icon: "mdi:ear-hearing"
    dps:
      - id: 8
        name: option
        type: string
        mapping:
          - dps_val: 1
            value: Standart-slow
          - dps_val: 2
            value: Standart-fast
          - dps_val: 3
            value: Westminster Quarters
          - dps_val: 4
            value: For Elise  
          - dps_val: 5
            value: Bird   
          - dps_val: 6
            value: Cock  
          - dps_val: 7
            value: Ringtone   
          - dps_val: 8
            value: Wolf   
          - dps_val: 9
            value: Moonglow  
          - dps_val: 10
            value: Canon   
          - dps_val: 11
            value: Yesterday Once More   
          - dps_val: 12
            value: Clock Cucloo   
          - dps_val: 13
            value: Cucloo Waitz  
          - dps_val: 14
            value: Class Ringtone  
          - dps_val: 15
            value: Everything is Better  
          - dps_val: 16
            value: Dreamtable-The dawn  
          - dps_val: 17
            value: Turkish March   
          - dps_val: 18
            value: Alarm  
          - dps_val: 19
            value: The Great Mercy Mantra  
          - dps_val: 20
            value: Tchaikovsky Overtude 1812   
          - dps_val: 21
            value: The Moon Reflected In Er-quan  
          - dps_val: 22
            value: Little Star
          - dps_val: 23
            value: Waltz of the Flowers
          - dps_val: 24
            value: libiamo Ne Lieti Calici
          - dps_val: 25
            value: Die Forelle 
          - dps_val: 26
            value: Circus 
          - dps_val: 27
            value: Danse des petits cygnes 
          - dps_val: 28
            value: Fiddler on the Roof 
          - dps_val: 29
            value: Beautiful Dreamer 
          - dps_val: 30
            value: Carmen Overtude
          - dps_val: 31
            value: The Fishermen stig in the Evening
          - dps_val: 32
            value: Dog
          - dps_val: 33
            value: Pig Bajie
          - dps_val: 34
            value: Paris in Autumn
          - dps_val: 35
            value: Nutcracker Waltz
          - dps_val: 36
            value: Red River Valley
          - dps_val: 37
            value: The Four Seasones
          - dps_val: 38
            value: Schubert Serenade
          - dps_val: 39
            value: Merry Christmas
          - dps_val: 40
            value: Malta
          - dps_val: 41
            value: Toy solder
          - dps_val: 42
            value: Ode an die Freuge
          - dps_val: 43
            value: Eva's Polka
          - dps_val: 44
            value: Rondo a capriccio
          - dps_val: 45
            value: Hungarian Dance
          - dps_val: 46
            value: Minuet in G Major
          - dps_val: 47
            value: Auld Lang Syne
          - dps_val: 48
            value: The Nutcracker
          - dps_val: 49
            value: Pop Dance
          - dps_val: 50
            value: Toreador Song
          - dps_val: 51
            value: Lullaby
          - dps_val: 52
            value: Green sleeves
          - dps_val: 53
            value: Happy New Year
          - dps_val: 54
            value: The wandering Songstress
          - dps_val: 55
            value: Chopin Waltz
          - dps_val: 56
            value: Shepherd Song
          - dps_val: 57
            value: Happy Birthday
          - dps_val: 58
            value: A Hulusi fjute            
            ```
