### ISSUE TITLE
Request support for [device description]

### ISSUE THREAD

**Issue by cramer52** [make-all/tuya-local#770]
# Log Message

```
Device matches None with quality of 0%. DPS: {"updated_at": 1686053192.8093898, "20": false, "24": "00f00000000a", "26": 0, "51": "manual", "52": true, "53": false, "54": 10, "60": false, "62": 10}
```

# Information about DPS mappings

```
{
  "result": {
    "category": "xktyd",
    "functions": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "colour_data",
        "dp_id": 24,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mic_music_data",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":\"255\"}"
      },
      {
        "code": "star_work_mode",
        "dp_id": 51,
        "type": "Enum",
        "values": "{\"range\":[\"manual\",\"scene\",\"music\"]}"
      },
      {
        "code": "colour_switch",
        "dp_id": 52,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "laser_switch",
        "dp_id": 53,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "laser_bright",
        "dp_id": 54,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "star_control_data",
        "dp_id": 57,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "star_scene_data",
        "dp_id": 58,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "fan_switch",
        "dp_id": 60,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "dp_id": 62,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ],
    "lang_config": {},
    "status": [
      {
        "code": "switch_led",
        "dp_id": 20,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "colour_data",
        "dp_id": 24,
        "type": "Json",
        "values": "{}"
      },
      {
        "code": "countdown",
        "dp_id": 26,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "mic_music_data",
        "dp_id": 42,
        "type": "String",
        "values": "{\"maxlen\":\"255\"}"
      },
      {
        "code": "star_work_mode",
        "dp_id": 51,
        "type": "Enum",
        "values": "{\"range\":[\"manual\",\"scene\",\"music\"]}"
      },
      {
        "code": "colour_switch",
        "dp_id": 52,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "laser_switch",
        "dp_id": 53,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "laser_bright",
        "dp_id": 54,
        "type": "Integer",
        "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "star_scene_data",
        "dp_id": 58,
        "type": "Raw",
        "values": "{}"
      },
      {
        "code": "fan_switch",
        "dp_id": 60,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "dp_id": 62,
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1686053596558,
  "tid": "84696d52046311eebfbfa24bf1d21c99"
}
```

# Product ID

# Information about how the device functions
This is a Galaxy Light that also has a laser integrated (own light unit) and this can move with the help of a motor. The brightness entity of the main galaxy light does not appear to be exposed. The motor is recognized as a fan.

# First try implementation YAML Code, I'm not sure how to test it tough. I put the YAML in the devices subfolder but still get the message that the device is not supported.

```
name: Galaxy Light
products:
  - id: okyhahmixunjmbca
    name: Galaxy Light
primary_entity:
  entity: light
  dps:
    - id: 20
      type: boolean
      name: switch_led
    - id: 24
      name: color_data
      type: json
secondary_entities:
  - entity: switch
    name: Galaxy Light Colour
    dps:
      - id: 52
        type: boolean
        name: colour_switch
  - entity: number
    name: Timer
    dps:
      - id: 26
        type: integer
        range:
          min: 0
          max: 86400
  - entity: light
    name: Galaxy Light Laser
    dps:
      - id: 53
        type: laser_switch
        name: switch
      - id: 54
        name: laser_bright
        type: integer
        range:
          min: 10
          max: 1000
  - entity: fan
    dps:
      - id: 60
        type: boolean
        name: fan_switch
      - id: 62
        type: integer
        name: fan_speed
        range:
          min: 1
          max: 100
```
