### ISSUE TITLE
Request support for Proscenic A8 Air Purifier

### ISSUE THREAD

**Issue by kajapa** [make-all/tuya-local#776]
# Log Message

```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local (documentation, issues)
First occurred: 16:07:24 (2 occurrences)
Last logged: 16:07:24

Device matches ir_remote_sensors with quality of 17%. DPS: {"updated_at": 1686233241.8186786, "1": false, "2": 0, "4": "auto", "5": 96, "7": false, "8": false, "11": false, "16": 1939, "17": 0, "21": "great", "101": 0, "102": "003"}
Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
"status": [
      {
        "code": "switch",
        "value": false
		"dp_id": 1
      },
      {
        "code": "pm25",
        "value": 0
		"dp_id": 2
      },
      {
        "code": "fan_speed_enum",
        "value": {"sleep", "mid", "high", "auto"}
		"dp_id": 4
      },
      {
        "code": "filter",
        "value": 96
		"unit": "%"
		"dp_id": 5
      },
      {
        "code": "lock",
        "value": false
		"dp_id": 7 
      },
      {
        "code": "light",
        "value": false
		"dp_id": 8
      },
      {
        "code": "filter_reset",
        "value": false
		"dp_id": 11
      },
      {
        "code": "filter_days",
        "value": 1939
		"dp_id": 16
		"unit": d
      },
      {
        "code": "total_time",
        "value": 0
		"dp_id": 17
		"unit": min
      },
      {
        "code": "total_pm",
        "value": 0
		"dp_id": 20
      },
      {
        "code": "air_quality",
        "value": "great"
		"dp_id": 21 
      },
      {
        "code": "fault",
        "value": 0
		"dp_id": 22
      }
    ],
    "sub": false,
    "time_zone": "+01:00",
    "uid": "eu1627645011200BWh0n",
    "update_time": 1686231336,
    "uuid": "1615185624a160286666"
  },
  "success": true,
  "t": 1686231402067,
  "tid": "80c25f04060111eeac8032ebdb7f4f6c"
}
```
# Template made by me
```
name: A8
products:
  - id: jiiagi6aamtgbffk
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch
      type: boolean
      icon: "mdi:air-purifier"
    - id: 4
      name: preset_mode
      type: string
      mapping:
        - dps_val: "sleep"
          value: "Noc"
        - dps_val: "mid"
          value: "Medium"
        - dps_val: "high"
          value: "High"
        - dps_val: "auto"
          value: "Auto"
secondary_entities:
  - entity: sensor
    name: PM2.5
    icon: "mdi:air-filter"
    class: pm25
    dps:
      - id: 2
        name: sensor
        class: measurement
        type: integer
        unit: ugm3
  - entity: switch
    name: Light
    category: config
    icon: "mdi:lightbulb-night"
    dps:
      - id: 8
        name: switch
        type: boolean
  - entity: sensor
    name: Filter Usage
    category: diagnostic
    icon: "mdi:shield-bug"
    dps:
      - id: 5
        name: sensor
        type: integer
        unit: "%"
  - entity: switch
    name: Reset Filter
    category: config
    icon: "mdi:lightbulb-night"
    dps:
      - id: 11
        name: switch
        type: boolean
  - entity: sensor
    name: Filter days left
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 16
        name: sensor
        type: integer
        unit: d
  - entity: switch
    name: Child Lock
    category: config
    icon: "mdi:lock"
    dps:
      - id: 7
        name: switch
        type: boolean
  - entity: sensor
    name: Total Runtime
    category: diagnostic
    icon: "mdi:data-matrix"
    dps:
      - id: 17
        name: sensor
        type: integer
        unit: min
  - entity: sensor
    name: Total PM
    category: diagnostic
    icon: "mdi:data-matrix"
    dps:
      - id: 20
        name: sensor
        type: integer
        unit: ugm3
  - entity: sensor
    name: Air quality
    class: enum
    icon: "mdi:air-filter"
    dps:
      - id: 21
        name: sensor
        type: string
        mapping:
          - dps_val: "great"
            value: "Great"
          - dps_val: "good"
            value: "Good"
          - dps_val: "medium"
            value: "Mild pollution"
          - dps_val: "severe"
            value: "Severe"
```

# Product ID
```
"product_id": "jiiagi6aamtgbffk",
"product_name": "A8"
```

# Information about how the device functions
```
https://www.xiaomitoday.com/product/proscenic-a8/
Hi! I've tried adding new yaml file with configuration to my air purifier but it didn't show up during set up process. I also added my template to description of this ticket.
If there is any more information I can add than don't hesitate to ask.
```
