### ISSUE TITLE
Unable to use Orion Bluetooth Lock as a trigger

### ISSUE THREAD

**Issue by jaydisc** [make-all/tuya-local#798]
I have not been able to get the unlocking of the Orion Door Lock (support recently added) to be a trigger an automation as you suggested (https://github.com/make-all/tuya-local/issues/654#issuecomment-1562516676):

    If you update again, I have tried to fix the reporting.  Likely now the "changed_by" will only appear briefly after an unlock, but it might be in the LogBook, and automations triggered on it will work so you could use an automation to update a Helper entity if you want to track the last unlock long term.

I've tried using the 'unlocking' and 'unlocked' events to no avail (no log entries or traces are created either):

```
trigger:
  - platform: device
    device_id: 3edd6a86e47973b87580caf1d3284f95
    domain: lock
    entity_id: lock.office_lock_hallway_dysfunctional
    type: unlocking
```

```
trigger:
  - platform: device
    device_id: 3edd6a86e47973b87580caf1d3284f95
    domain: lock
    entity_id: lock.office_lock_hallway_dysfunctional
    type: unlocked
```

Thank you.

[tuya_local-baf7d32887458f9fd5db882b9b772986-Office Lock Hallway-3edd6a86e47973b87580caf1d3284f95.json.txt](https://github.com/make-all/tuya-local/files/11742306/tuya_local-baf7d32887458f9fd5db882b9b772986-Office.Lock.Hallway-3edd6a86e47973b87580caf1d3284f95.json.txt)
