### ISSUE TITLE
Cannot find Proscenic A8 in set up process

### ISSUE THREAD

**Issue by kajapa** [make-all/tuya-local#803]
**Describe the bug**
After updating to newest version of integration, I still cannot add my air purifier. Purifier's configuration does not appear in set up process of new device. Currently I am using Local Tuya integration to manage my air purifier. I am also adding config of this integration. Please let me know if I can add any more information.

**To Reproduce**

1. Fill out all necessary information in initial window of configuration process.
2. Click Confirm button.
3. Try to find your device on list of supported devices.

**Expected behavior**
Device appears on list of supported devices.

**Logs**
```
Logger: custom_components.tuya_local.config_flow
Source: custom_components/tuya_local/config_flow.py:49
Integration: Tuya Local (documentation, issues)
First occurred: 20:19:23 (8 occurrences)
Last logged: 20:42:28
Device matches feit_dimmer with quality of 25%. DPS: {"updated_at": 1686853160.9615319, "1": false, "2": 0, "4": "sleep", "5": 95, "7": false, "8": false, "11": false, "16": 1914, "17": 9, "21": "great", "101": 0, "102": "003"}
Report this to https://github.com/make-all/tuya-local/issues/
Device matches feit_dimmer with quality of 25%. DPS: {"updated_at": 1686853636.4097874, "1": false, "2": 0, "4": "sleep", "5": 95, "7": false, "8": false, "11": false, "16": 1914, "17": 9, "21": "great", "101": 0, "102": "003"}
Device matches feit_dimmer with quality of 25%. DPS: {"updated_at": 1686854435.549771, "1": false, "2": 0, "4": "mid", "5": 95, "7": false, "8": true, "11": false, "16": 1914, "17": 7, "21": "great", "101": 0, "102": "003"}
Device matches feit_dimmer with quality of 25%. DPS: {"updated_at": 1686854545.6667356, "1": false, "2": 0, "4": "mid", "5": 95, "7": false, "8": true, "11": false, "16": 1914, "17": 7, "21": "great", "101": 0, "102": "003"}
```

**Local Tuya config**
```
"data": {
    
      "protocol_version": "3.3",
      "enable_debug": false,
      "dps_strings": [
        "1 (value: True)",
        "2 (value: 14)",
        "4 (value: auto)",
        "5 (value: 100)",
        "7 (value: False)",
        "8 (value: False)",
        "11 (value: False)",
        "16 (value: 2000)",
        "17 (value: 17)",
        "21 (value: great)",
        "101 (value: 0)",
        "102 (value: 003)"
      ],
      "entities": [
        {
          "id": 1,
          "friendly_name": "Switch",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "platform": "switch"
        },
        {
          "id": 7,
          "friendly_name": "Child lock",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "platform": "switch"
        },
        {
          "id": 8,
          "friendly_name": "Light",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "platform": "switch"
        },
        {
          "id": 11,
          "friendly_name": "Reset filter",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "platform": "switch"
        },
        {
          "id": 4,
          "friendly_name": Mode
          "select_options": "sleep;mid;high;auto",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "select_options_friendly": "Sleep;Medium;High;Auto",
          "platform": "select"
        },
        {
          "id": 5,
          "friendly_name": "Filtr usage",
          "unit_of_measurement": "%",
          "platform": "sensor"
        },
        {
          "id": 16,
          "friendly_name": "Filter days left",
          "unit_of_measurement": "dni/dzie\u0144",
          "platform": "sensor"
        },
        {
          "id": 21,
          "friendly_name": "PM2.5",
          "platform": "sensor"
        },
        {
          "id": 2,
          "friendly_name": "Air quality",
          "device_class": "pm25",
          "unit_of_measurement": "pm2.5",
          "platform": "sensor"
        },
        {
          "id": 17,
          "friendly_name": "Total runtime",
          "unit_of_measurement": "min",
          "device_class": "duration",
          "platform": "sensor"
        },
        {
          "id": 102,
          "friendly_name": "Unknown102",
          "restore_on_reconnect": false,
          "is_passive_entity": false,
          "platform": "switch"
        }
      ],
      "product_key": "jiiagi6aamtgbffk"
```

**Comment by kajapa** [comment]
@make-all I removed dp 103 and left 101 and 102. I also changed type of 102 to string. It works NOW! It looks like this:
```- id: 101
      name: unknown_101
      type: integer
    - id: 102
      name: unknown_102
      type: string
```

**Comment by make-all** [comment]
Are you using a different source?  Your description of what you did does not match the state of this repository either before or after the change yesterday to rename 103 to 102 (it was a typo in the original commit, but it just needed renaming, and was already a string).

**Comment by kajapa** [comment]
If by source you mean different yaml file then no. I was trying to add device with default configuration (default yaml file after updating integration). Apologize if I made mistake in description :D. Just te be clear this is how proscenic_a8_airpurifier.yaml looks in my HA:
````
name: Air Purifier
products:
  - id: jiiagi6aamtgbffk
    name: Proscenic A8
primary_entity:
  entity: fan
  icon: "mdi:air-purifier"
  dps:
    - id: 1
      name: switch
      type: boolean
    - id: 4
      name: preset_mode
      type: string
      mapping:
        - dps_val: "sleep"
          value: "Sleep"
        - dps_val: "mid"
          value: "Medium"
        - dps_val: "high"
          value: "High"
        - dps_val: "auto"
          value: "Auto"
    - id: 101
      name: unknown_101
      type: integer
    - id: 102
      name: unknown_102
      type: string

secondary_entities:
  - entity: sensor
    name: PM2.5
    class: pm25
    dps:
      - id: 2
        name: sensor
        class: measurement
        type: integer
        unit: ugm3
  - entity: light
    category: config
    icon: "mdi:lightbulb-night"
    dps:
      - id: 8
        name: switch
        type: boolean
  - entity: sensor
    name: Filter usage
    category: diagnostic
    icon: "mdi:shield-bug"
    dps:
      - id: 5
        name: sensor
        type: integer
        unit: "%"
  - entity: switch
    name: Reset Filter
    category: config
    icon: "mdi:lightbulb-night"
    dps:
      - id: 11
        name: switch
        type: boolean
  - entity: sensor
    name: Filter days left
    category: diagnostic
    icon: "mdi:air-filter"
    dps:
      - id: 16
        name: sensor
        type: integer
        unit: d
  - entity: lock
    name: Child lock
    icon: "mdi:hand-back-right-off"
    category: config
    dps:
      - id: 7
        type: boolean
        name: lock
  - entity: sensor
    name: Total runtime
    category: diagnostic
    icon: "mdi:data-matrix"
    dps:
      - id: 17
        name: sensor
        type: integer
        unit: min
  - entity: sensor
    name: Total PM
    category: diagnostic
    icon: "mdi:data-matrix"
    dps:
      - id: 20
        name: sensor
        type: integer
        optional: true
        unit: ugm3
  - entity: sensor
    name: Air quality
    class: enum
    icon: "mdi:air-filter"
    dps:
      - id: 21
        name: sensor
        type: string
        mapping:
          - dps_val: "great"
            value: "Great"
          - dps_val: "good"
            value: "Good"
          - dps_val: "medium"
            value: "Mild pollution"
          - dps_val: "severe"
            value: "Severe"
````
