### ISSUE TITLE
Mini Smart Fan Speed Switch - Support request

### ISSUE THREAD

**Issue by vampywiz17** [make-all/tuya-local#82]
Hello there,

if possible please try to support this device:

my device info:

Device Link: https://www.aliexpress.com/item/1005002941694177.html

![140172508-24a028a0-db29-4352-9e7e-ad6c0532ea0f](https://user-images.githubusercontent.com/14281430/143506779-31a7ba5a-c20a-483d-a905-76c2890e9458.png)

```
switch_fan	Boolean	
"{true,false}"
countdown_fan	Integer	
{
  "unit": "s",
  "min": 0,
  "max": 86400,
  "scale": 0,
  "step": 1
}
fan_speed_enum	Enum	
{
  "range": [
    "level_1",
    "level_2",
    "level_3",
    "level_4",
    "level_5"
  ]
}
fan_speed	Integer	
{
  "unit": "%",
  "min": 1,
  "max": 100,
  "scale": 0,
  "step": 1
}

```

```
{
  "result": {
    "category": "fskg",
    "functions": [
      {
        "code": "switch_fan",
        "desc": "{}",
        "name": "风扇开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_fan",
        "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}",
        "name": "风扇倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_speed_enum",
        "desc": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\"]}",
        "name": "风速档位",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\"]}"
      },
      {
        "code": "fan_speed",
        "desc": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}",
        "name": "风速",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_fan",
        "name": "风扇开关",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_fan",
        "name": "风扇倒计时",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_speed_enum",
        "name": "风速档位",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\"]}"
      },
      {
        "code": "fan_speed",
        "name": "风速",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1636449731726
}
```

I know, that you need the dps info, but the device currently is not here and i can not connect it to my local network. I will extend this issue the dps information soon!

**Comment by make-all** [comment]
If you have access to your device details in iot.tuya.com, you can also get the details including dps ids from the API Explorer at Smart Home Management System / Device Control / Get Device Specification Attribute.

**Comment by vampywiz17** [comment]
@make-all 

here:

```
{
  "result": {
    "category": "fskg",
    "functions": [
      {
        "code": "switch_fan",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_fan",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_speed_enum",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\"]}"
      },
      {
        "code": "fan_speed",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ],
    "status": [
      {
        "code": "switch_fan",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_fan",
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "fan_speed_enum",
        "type": "Enum",
        "values": "{\"range\":[\"level_1\",\"level_2\",\"level_3\",\"level_4\",\"level_5\"]}"
      },
      {
        "code": "fan_speed",
        "type": "Integer",
        "values": "{\"unit\":\"%\",\"min\":1,\"max\":100,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1637910967313
}
```

**Comment by vampywiz17** [comment]
i try to make a yaml my own. 

What do you think? (i not tested it)

```
name: TMWF02 Wi-Fi Fan Module
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: integer
      name: countdown
	  unit: s
      range:
        min: 0
        max: 86400
      mapping:
        - scale: 0
    - id: 3
      type: integer
      name: speed
      range:
        min: 1
        max: 5
      mapping:
        - scale: 0.05
    - id: 4
      type: integer
      name: speed
	  unit: "%"
      range:
        min: 1
        max: 100
      mapping:
        - scale: 0
```

some questions:

1.
"scale 0" is need in this two case?

2. 
id3 and id4 seems set same thing with different method. Need to use both of them?

3.
countdown is neccesary? (i think it is exist lot of tuya devices, but i dont know that is any reason to use it with local integration...)

**Comment by vampywiz17** [comment]
@make-all 

i try this simple config:

```
name: TMWF02 Wi-Fi Fan Module
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 4
      type: integer
      name: speed
      unit: "%"
      range:
        min: 1
        max: 100
```

it read the config without any problem (if i set it via Tuya app) but if i try to set it, it not work. I try tuya cli, but get this error:

```
DEBUG=* tuya-cli set --id XXXXXXXX--key XXXXXXXX  --ip 192.168.31.208 --protocol-version 3.3 --dps 1 --set true
  TuyAPI IP and ID are already both resolved. +0ms
  TuyAPI Connecting to 192.168.31.208... +3ms
  TuyAPI Socket connected. +88ms
  TuyAPI SET Payload: +1ms
  TuyAPI { devId: 'XXXXXXX',
  TuyAPI   gwId: 'XXXXXXX',
  TuyAPI   uid: '',
  TuyAPI   t: 1637950462,
  TuyAPI   dps: { '1': true } } +0ms
  TuyAPI Received data: 000055aa00000001000000070000000c00000000a505a9140000aa55 +101ms
  TuyAPI Parsed: +1ms
  TuyAPI { payload: false, leftover: false, commandByte: 7, sequenceN: 1 } +0ms
  TuyAPI Got SET ack. +0ms
{ Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Timeout waiting for status response from device id: bf8bb0c814793d7206jwct')
    at TuyaDevice.emit (events.js:187:17)
    at pTimeout (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/tuyapi/index.js:369:12)
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/@tuyapi/cli/node_modules/p-timeout/index.js:25:13)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  context:
   'Timeout waiting for status response from device id: XXXXXXXXXXXXX' }
```

**Comment by vampywiz17** [comment]
Strange.... i install localtuya integration to test, that work or not. It auto discover the fan, BUT show totally different ID, than the tuya-cli wizard .... I change the ID to the initial config and now work like a charm!!

What do you think??! :)

**Comment by make-all** [comment]
The way I have defined scale is different to the way Tuya have defined it. scale: 0 will result in a divide by 0 error, just leave it out if there is no scaling needed.
You probably want just one of those speed settings. I don't know if the percentage one will need
```
mapping:
    - step: 20
```
to work properly, probably it is the same 5 steps, but expressed as a percentage.

Adding the other speed in under a different name and making it hidden will help filter out false matches with device detection.
And for completeness, I would add
```
secondary_entities:
  - entity: number
    category: config
    name: Timer
    dps:
      - id: 2
        name: value
        type: integer
        range:
          min: 0
          max: 86400
```
