### ISSUE TITLE
thermex lima 80v

### ISSUE THREAD

**Issue by rbalaev** [make-all/tuya-local#842]
# Log Message

```
name: thermex_lima_80v
product:
  - id: bff6c7d8b807ba447ermih
    name: thermex_lima_80v
primary_entity:
  entity: switch
  icon: "mdi:water-boiler"
  name: Water heater
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: sensor
    name: Mode
    category: config
    icon: "mdi:heat-wave"
    dps:
      - id: 13
        type: string
        name: sensor
      - id: 20
        type: integer
        name: attr1   
  - entity: sensor
    name: Current temperature
    category: config
    class: temperature
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: °C  
  - entity: sensor
    name: Target temperature
    category: config
    class: temperature
    dps:
      - id: 9
        type: integer
        name: sensor
        unit: °C          
  - entity: number
    category: config
    name: Set Target temperature
    icon: "mdi:coolant-temperature"
    dps:
      - id: 9
        name: value
        type: integer
        unit: °C
        range:
          min: 35
          max: 75                 
  - entity: sensor
    name: No frost
    icon: "mdi:snowflake-melt"
    category: diagnostic
    dps:
      - id: 101
        type: boolean
        name: sensor
```

```
Please paste the output here.
```

# Product ID

# Information about how the device functions
