### ISSUE TITLE
Request support for Goldair 101cm Electronic Tower Fan

### ISSUE THREAD

**Issue by BenJamesAndo** [make-all/tuya-local#853]
# Log Message

```
2023-06-28 20:25:26.760 WARNING (MainThread) [custom_components.tuya_local.config_flow] Device matches stirling_fs140dc_fan with quality of 83%. DPS: {"updated_at": 1687947926.1472604, "1": false, "2": "normal", "3": 1, "5": false, "21": 25, "22": "cancel"}
2023-06-28 20:25:26.761 WARNING (MainThread) [custom_components.tuya_local.config_flow] Report this to https://github.com/make-all/tuya-local/issues/
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1687989603980,
        "value": false
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1687949497925,
        "value": "normal"
      },
      {
        "code": "fan_speed",
        "custom_name": "",
        "dp_id": 3,
        "time": 1687953258907,
        "value": 1
      },
      {
        "code": "switch_horizontal",
        "custom_name": "",
        "dp_id": 5,
        "time": 1687952743989,
        "value": false
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 21,
        "time": 1687995470917,
        "value": 22
      },
      {
        "code": "countdown_set",
        "custom_name": "",
        "dp_id": 22,
        "time": 1687902360501,
        "value": "cancel"
      }
    ]
  },
  "success": true,
  "t": 1687996550927,
  "tid": "4f7d7370160f11ee871736843e81b476"
}
```

# Product ID

`xonvukal96pf99s6`

# Information about how the device functions
https://goldair.co.nz/products/gctf260
Press the POWER button and the fan will turn on automatically to MEDIUM 
SPEED
Press the SPEED button to select your desired speed level. Choose between 
LOW, MEDIUM and HIGH speed. 
Press the TIMER button to set the desired auto power off time. Choose 
between 1hr – 12hrs with 1hr intervals. 

There's a current pull request [#844](https://github.com/make-all/tuya-local/pull/844#issue-1775910911) for a similar fan, the Platinum model. I changed the code a bit and got it working somewhat for me. But Pressing off doesn't seem to work properly and I couldn't get the timer working correctly. Probably because my fan is in 1 hour increments. I did add temperature to my version of the yaml file which does work. Below is my attempt at the .yaml file for your reference.

```
name: Goldair 101cm Electronic Tower Fan
products:
  - id: xonvukal96pf99s6
    name: Goldair 101cm Electronic Tower Fan
primary_entity:
  entity: fan
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 2
      type: string
      name: preset_mode
      mapping:
        - dps_val: 1
          value: Normal
        - dps_val: 2
          value: Nature
        - dps_val: 3
          value: Sleep
    - id: 3
      type: integer
      name: speed
      range:
        min: 0
        max: 3
      mapping:
        - scale: 0.03
    - id: 5
      type: boolean
      name: oscillate
    - id: 21
      type: integer
      name: temperature
      unit: C
      range:
        min: 4
        max: 35
secondary_entities:
  - entity: select
    name: Timer
    icon: "mdi:timer"
    category: config
    dps:
      - id: 22
        name: option
        type: string
        mapping:
          - dps_val: cancel
            value: "Off"
          - dps_val: "0_5"
            value: "30 minutes"
          - dps_val: "1_0"
            value: "1 hour"
          - dps_val: "1_5"
            value: "1.5 hours"
          - dps_val: "2_0"
            value: "2 hours"
          - dps_val: "2_5"
            value: "2.5 hours"
          - dps_val: "3_0"
            value: "3 hours"
          - dps_val: "3_5"
            value: "3.5 hours"
          - dps_val: "4_0"
            value: "4 hours"
          - dps_val: "4_5"
            value: "4.5 hours"
          - dps_val: "5_0"
            value: "5 hours"
          - dps_val: "5_5"
            value: "5.5 hours"
          - dps_val: "6_0"
            value: "6 hours"
          - dps_val: "6_5"
            value: "6.5 hours"
          - dps_val: "7_0"
            value: "7 hours"
          - dps_val: "7_5"
            value: "7.5 hours"
          - dps_val: "8_0"
            value: "8 hours"
          - dps_val: "8_5"
            value: "8.5 hours"
          - dps_val: "9_0"
            value: "9 hours"
          - dps_val: "9_5"
            value: "9.5 hours"
          - dps_val: "10_0"
            value: "10 hours"        
```

Thanks so much!
