### ISSUE TITLE
New device(Wait to test): WOOX R4028 Smart Home 3 Plug+4 USB + DIGOO DG-PS01 Smart Power Strip

### ISSUE THREAD

**Issue by vampywiz17** [make-all/tuya-local#87]
Hello i work some new device. One of this (the two device config is same. i dont know that i make two yaml or it good this version?):

Please review it, if the syntax logic good, i will commit it. (today i will test it, of course )

ID1 - switch_1
ID2 - switch_2
ID3 - switch_3
ID7 - switch_usb1
ID101 - countdown_1
ID102 - countdown_2
ID103 - countdown_3
ID107 - countdown_usb1

![262297613_956981108356242_1235839470918588043_n](https://user-images.githubusercontent.com/14281430/143853067-27326da9-b563-4b75-b341-403a23c330c5.png)

![262506117_212583117688200_8620708702318107927_n](https://user-images.githubusercontent.com/14281430/143853192-c9d3a88f-075c-4764-8e96-86856bb946b0.png)

```
name: Woox R4028 + DIGOO DG-PS01
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch_1
      type: boolean
secondary_entities:
  - entity: switch
    dps:
    - id: 2
      name: switch_2
      type: boolean
  - entity: switch
    dps:
    - id: 3
      name: switch_3
      type: boolean
  - entity: switch
    dps:
    - id: 7
      name: switch_usb1
      type: boolean
  - entity: number
    category: config
    name: Timer_1
    dps:
      - id: 101
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer_2
    dps:
      - id: 102
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer_3
    dps:
      - id: 103
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer_usb1
    dps:
      - id: 105
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
```
