### ISSUE TITLE
Would like to add additional MoesGo PCT513-WB-TY Thermostat

### ISSUE THREAD

**Issue by EWRCnetadmin** [make-all/tuya-local#875]
Link to MoesGo PCT513-WB-TY Thermostat:
https://www.amazon.com/dp/B0B3X5DWK4

Below link (and in section at the end) is the YAML file for this thermostat.  New YAML file was based on the original file "owon_pct513_thermostat.yaml".  Please add this file to the repository.

[pct513-wb-ty.yaml.txt](https://github.com/make-all/tuya-local/files/11970268/pct513-wb-ty.yaml.txt)

# Log Message

```
N/A
```

# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1688621466623,
        "value": "cool"
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 16,
        "time": 1688644942267,
        "value": 2950
      },
      {
        "code": "temp_set_f",
        "custom_name": "",
        "dp_id": 17,
        "time": 1688644942268,
        "value": 85
      },
      {
        "code": "upper_temp_f",
        "custom_name": "",
        "dp_id": 18,
        "time": 1681334798003,
        "value": 70
      },
      {
        "code": "upper_temp",
        "custom_name": "",
        "dp_id": 19,
        "time": 1681334798003,
        "value": 20
      },
      {
        "code": "lower_temp_f",
        "custom_name": "",
        "dp_id": 20,
        "time": 1681334798003,
        "value": 32
      },
      {
        "code": "temp_unit_convert",
        "custom_name": "",
        "dp_id": 23,
        "time": 1688621466623,
        "value": "f"
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 24,
        "time": 1688652009961,
        "value": 2150
      },
      {
        "code": "lower_temp",
        "custom_name": "",
        "dp_id": 26,
        "time": 1681334798003,
        "value": 0
      },
      {
        "code": "temp_correction",
        "custom_name": "",
        "dp_id": 27,
        "time": 1681334798003,
        "value": -9
      },
      {
        "code": "temp_current_f",
        "custom_name": "",
        "dp_id": 29,
        "time": 1688652009981,
        "value": 71
      },
      {
        "code": "humidity",
        "custom_name": "",
        "dp_id": 34,
        "time": 1688655478434,
        "value": 69
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 45,
        "time": 1687544392433,
        "value": 0
      },
      {
        "code": "hvacsystemtype",
        "custom_name": "",
        "dp_id": 107,
        "time": 1688621466623,
        "value": "5"
      },
      {
        "code": "cool_set_temp",
        "custom_name": "",
        "dp_id": 108,
        "time": 1688644942188,
        "value": 2950
      },
      {
        "code": "heat_temp_set",
        "custom_name": "",
        "dp_id": 109,
        "time": 1688644942519,
        "value": 1650
      },
      {
        "code": "cool_set_temp_f",
        "custom_name": "",
        "dp_id": 110,
        "time": 1688644942195,
        "value": 85
      },
      {
        "code": "heat_temp_set_f",
        "custom_name": "",
        "dp_id": 111,
        "time": 1688644942551,
        "value": 62
      },
      {
        "code": "fanmode",
        "custom_name": "",
        "dp_id": 115,
        "time": 1687544392433,
        "value": "auto"
      },
      {
        "code": "homemode",
        "custom_name": "",
        "dp_id": 116,
        "time": 1687544392433,
        "value": "1"
      },
      {
        "code": "schedule",
        "custom_name": "",
        "dp_id": 118,
        "time": 1688613626644,
        "value": "AAFoCDQJ9gEB4AZyC4YCBDgINAn2AwUoBnIKvv///4AAgAAAAWgINAn2AQHgBnILhgIEOAg0CfYDBSgGcgq+////gACAAAABaAg0CfYBAeAGcguGAgQ4CDQJ9gMFKAZyCr7///+AAIAAAAFoCDQJ9gEB4AZyC4YCBDgINAn2AwUoBnIKvv///4AAgAAAAWgINAn2AQHgBnILhgIEOAg0CfYDBSgGcgq+////gACAAAABaAg0CfYBAeAGcguGAgQ4CDQJ9gMFKAZyCr7///+AAIAAAAFoCDQJ9gEB4AZyC4YCBDgINAn2AwUoBnIKvv///4AAgAA="
      },
      {
        "code": "schedule_enable",
        "custom_name": "",
        "dp_id": 119,
        "time": 1687544388706,
        "value": true
      },
      {
        "code": "setpointholdmode",
        "custom_name": "",
        "dp_id": 120,
        "time": 1688645128497,
        "value": "followschedule"
      },
      {
        "code": "vacationschedule",
        "custom_name": "",
        "dp_id": 121,
        "time": 1688613626829,
        "value": "AA=="
      },
      {
        "code": "sensorlist1",
        "custom_name": "",
        "dp_id": 122,
        "time": 1688655476220,
        "value": "AQAAOvZNeSBEZXZpY2UAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQhmAQ8AAQABCIYAAAAAAAA="
      },
      {
        "code": "fancylcetime",
        "custom_name": "",
        "dp_id": 123,
        "time": 1687544392433,
        "value": 25
      },
      {
        "code": "sensorlist2",
        "custom_name": "",
        "dp_id": 125,
        "time": 1688655476410,
        "value": "AQ=="
      },
      {
        "code": "sensorlist3",
        "custom_name": "",
        "dp_id": 126,
        "time": 1688655476627,
        "value": "AQ=="
      },
      {
        "code": "sensorlist4",
        "custom_name": "",
        "dp_id": 127,
        "time": 1688655476844,
        "value": "AQ=="
      },
      {
        "code": "sensorlist5",
        "custom_name": "",
        "dp_id": 128,
        "time": 1688655477123,
        "value": "AQ=="
      },
      {
        "code": "relaystatus",
        "custom_name": "",
        "dp_id": 129,
        "time": 1688619724743,
        "value": "alloff"
      },
      {
        "code": "weather",
        "custom_name": "",
        "dp_id": 130,
        "time": 1687544386377
      }
    ]
  },
  "success": true,
  "t": 1688655583154,
  "tid": "bd4e5b0e1c0d11ee9fecaa50f188a4b0"
}
```

# Product ID

```
{
  "result": {
    "active_time": 1687544386,
    "category": "wk",
    "create_time": 1672890217,
    "custom_name": "Test Thermostat",
    "icon": "smart/icon/ay1515026431018saCFs/bc88425bf219971170ee1483b1b3e41f.png",
    "id": "[REDACTED]",
    "ip": "[REDACTED]",
    "is_online": true,
    "lat": "[REDACTED]",
    "local_key": "[REDACTED]",
    "lon": "[REDACTED]",
    "model": "PCT513-WB",
    "name": "Thermostat  3",
    "product_id": "sqkxklkleeasfk8w",
    "product_name": "PCT513-WB-TY（PCT513-TY更换WBR3模组）",
    "sub": false,
    "time_zone": "-05:00",
    "update_time": 1687544490,
    "uuid": "767b394f07178d1b"
  },
  "success": true,
  "t": 1688659009289,
  "tid": "b76fa6441c1511ee804ade073cb82c5d"
}
```

# Example YAML File
```
name: PCT513-WB-TY Thermostat
products:
  - id: sqkxklkleeasfk8w
primary_entity:
  entity: climate
  translation_key: thermostat
  dps:
    - id: 2
      type: string
      name: hvac_mode
      mapping:
        - dps_val: "off"
          value: "off"
        - dps_val: cool
          value: cool
        - dps_val: heat
          value: heat
        - dps_val: auto
          value: heat_cool
        - dps_val: emergencyheat
          value: heat
    - id: 17
      type: integer
      name: temperature
      range:
        min: 41
        max: 90
    - id: 23
      type: string
      name: temperature_unit
      mapping:
        - dps_val: c
          value: C
        - dps_val: f
          value: F
    - id: 24
      type: integer
      name: current_temperature
      mapping:
        - scale: 100
          constraint: temperature_unit
          conditions:
            - dps_val: f
              scale: 1
              value_redirect: curtemp_f
    - id: 29
      type: integer
      name: curtemp_f
      hidden: true
    - id: 34
      type: integer
      name: current_humidity
    - id: 45
      type: integer
      name: unknown_45
    - id: 107
      type: string
      name: installation
    - id: 108
      type: integer
      name: temp_c
      mapping:
        - scale: 100
    - id: 109
      type: integer
      name: unknown_109
    - id: 110
      type: integer
      name: temp_f2
    - id: 111
      type: integer
      name: unknown_111
    - id: 115
      type: string
      name: fan_mode
      mapping:
        - dps_val: auto
          value: auto
        - dps_val: "on"
          value: "on"
        - dps_val: cycle
          value: cycle
    - id: 116
      type: string
      name: unknown_116
    - id: 119
      type: boolean
      name: scheduling
      hidden: true
      mapping:
        - dps_val: false
          value: Manual
    - id: 120
      type: string
      name: preset_mode
      mapping:
        - dps_val: followschedule
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
              value: Manual
            - dps_val: true
              value: Follow Schedule
        - dps_val: temphold
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
            - dps_val: true
              value: Temporary Hold
        - dps_val: permhold
          constraint: scheduling
          conditions:
            - dps_val: false
              value_redirect: scheduling
            - dps_val: true
              value: Permanent Hold
    - id: 129
      type: string
      name: hvac_action
      mapping:
        - dps_val: coolfanon
          value: cooling
        - dps_val: alloff
          value: idle
        - dps_val: fanon
          value: fan
        - dps_val: heatfanon
          value: heating
        - dps_val: "1"
          value: heating
secondary_entities:
  - entity: number
    name: Fan runtime
    category: config
    dps:
      - id: 123
        type: integer
        name: value
        unit: min
        range:
          min: 0
          max: 55
        mapping:
          - step: 5
  - entity: sensor
    name: Current temperature
    class: temperature
    dps:
      - id: 29
        type: integer
        name: sensor
        unit: F
        class: measurement
        mapping:
          - scale: 1
  - entity: select
    name: Current Mode
    category: config
    dps:
      - id: 129
        type: string
        name: option
        mapping:
          - dps_val: coolfanon
            value: cooling
          - dps_val: alloff
            value: idle
          - dps_val: fanon
            value: fan
          - dps_val: heatfanon
            value: heating
```
