### ISSUE TITLE
New device (Work in progress): DIGOO DG-SP01 Dual USB Interface EU Plug Smart WiFi Socket with LED Night Light

### ISSUE THREAD

**Issue by vampywiz17** [make-all/tuya-local#89]
Also new device. Work in progress to integrate it (possible to need some help from light/color entity)....

```
{
  "result": {
    "category": "cz",
    "functions": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_led",
        "dp_id": 27,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "work_mode",
        "dp_id": 28,
        "type": "Enum",
        "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"]}"
      },
      {
        "code": "bright_value",
        "dp_id": 29,
        "type": "Integer",
        "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}"
      },
      {
        "code": "colour_data",
        "dp_id": 31,
        "type": "Json",
        "values": "{}"
      }
    ],
```

```
name: DIGOO DG-SP01
primary_entity:
  entity: switch
  dps:
    - id: 1
      name: switch
      type: boolean
secondary_entities:
  - entity: switch
    dps:
    - id: 27
      name: switch_led
      type: boolean
  - entity: light
    category: config
    dps:
      - id: 29
        type: integer
        name: brightness
      range:
        min: 25
        max: 255
```
