### ISSUE TITLE
New device (Work in progress): DIGOO DG-SP202 Dual EU Plug Smart WIFI Socket

### ISSUE THREAD

**Issue by vampywiz17** [make-all/tuya-local#91]
Work in Progress

It need to add kWh measuring and test the metering scale.

```
    "status": [
      {
        "code": "switch_1",
        "dp_id": 1,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_2",
        "dp_id": 2,
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown_1",
        "dp_id": 9,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "countdown_2",
        "dp_id": 10,
        "type": "Integer",
        "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"
      },
      {
        "code": "add_ele",
        "dp_id": 17,
        "type": "Integer",
        "values": "{\"unit\":\"\",\"min\":0,\"max\":50000,\"scale\":3,\"step\":100}"
      },
      {
        "code": "cur_current",
        "dp_id": 18,
        "type": "Integer",
        "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}"
      },
      {
        "code": "cur_power",
        "dp_id": 19,
        "type": "Integer",
        "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":1,\"step\":1}"
      },
      {
        "code": "cur_voltage",
        "dp_id": 20,
        "type": "Integer",
        "values": "{\"unit\":\"V\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}"
      }
    ]
  },

```
```
name: DIGOO DG-SP202
primary_entity:
  entity: switch
  class: outlet 1
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 18
      type: integer
      name: current_a
      readonly: true
      mapping:
        - scale: 1000
    - id: 19
      type: integer
      name: current_power_w
      readonly: true
    - id: 20
      type: integer
      name: voltage_v
      readonly: true
secondary_entities:
  - entity: switch
    name: outlet 2
    class: switch
    dps:
      - id: 2
        type: boolean
        name: switch
  - entity: sensor
    category: diagnostic
    class: voltage
    name: Voltage
    dps:
      - id: 20
        name: sensor
        type: integer
        class: measurement
        unit: V
        mapping:
          - scale: 10
  - entity: sensor
    category: diagnostic
    class: current
    name: Current
    dps:
      - id: 18
        name: sensor
        type: integer
        class: measurement
        unit: mA
  - entity: sensor
    category: diagnostic
    class: power
    name: Power
    dps:
      - id: 19
        name: sensor
        type: integer
        class: measurement
        unit: W
        mapping:
          - scale: 10
  - entity: number
    category: config
    name: Timer 1
    icon: "mdi:timer"
    dps:
      - id: 9
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
  - entity: number
    category: config
    name: Timer 2
    icon: "mdi:timer"
    dps:
      - id: 10
        name: value
        type: integer
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
```
