### ISSUE TITLE
Request support for Lyfco air conditioner

### ISSUE THREAD

**Issue by davidsch1992** [make-all/tuya-local#946]
# Log Message

```
name: Air conditioner
products:
  - id: gwwxvfg8auctbnpr
    name: Lyfco Air Condition OL-A012
primary_entity:
  entity: climate
  dps:
    - id: 1
      type: boolean
      name: hvac_mode
      mapping:
        - dps_val: false
          value: "off"
        - dps_val: true
          constraint: mode
          conditions:
            - dps_val: Cool
              value: cool
            - dps_val: Dry
              value: dry
            - dps_val: Fan
              value: fan_only
            - dps_val: Heat
              value: heat
    - id: 2
      type: integer
      name: temperature
      range:
        min: 16
        max: 32
      unit: C
    - id: 3
      type: integer
      name: current_temperature
    - id: 4
      type: string
      name: mode
      hidden: true
    - id: 5
      type: string
      name: fan_mode
      mapping:
        - dps_val: Low
          value: low
        - dps_val: Mid
          value: middle
        - dps_val: Hig
          value: high
    - id: 15
      type: string
      name: swing_mode
      mapping:
        - dps_val: "OFF"
          value: "off"
        - dps_val: "ON"
          value: "on"
    - id: 22
      type: bitfield
      name: fault_code
    - id: 101
      type: boolean
      name: preset_mode
      mapping:
        - dps_val: true
          value: sleep
        - dps_val: false
          value: comfort
secondary_entities:
  - entity: binary_sensor
    name: Fault
    class: problem
    category: diagnostic
    dps:
      - id: 22
        type: bitfield
        name: sensor
        mapping:
          - dps_val: 0
            value: false
          - value: true

```
# Information about DPS mappings

```
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1690667560244,
        "value": false
      },
      {
        "code": "temp_set",
        "custom_name": "",
        "dp_id": 2,
        "time": 1690663405537,
        "value": 20
      },
      {
        "code": "temp_current",
        "custom_name": "",
        "dp_id": 3,
        "time": 1690667655507,
        "value": 23
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 4,
        "time": 1690666046269,
        "value": "Fan"
      },
      {
        "code": "fan_speed_enum",
        "custom_name": "",
        "dp_id": 5,
        "time": 1690667240010,
        "value": "Low"
      },
      {
        "code": "windshake",
        "custom_name": "",
        "dp_id": 15,
        "time": 1690667549127,
        "value": "OFF"
      },
      {
        "code": "fault",
        "custom_name": "",
        "dp_id": 22,
        "time": 1688675136616,
        "value": 0
      },
      {
        "code": "Sleep",
        "custom_name": "",
        "dp_id": 101,
        "time": 1690663419836,
        "value": false
      }
    ]
  }
```

# Product ID

```
gwwxvfg8auctbnpr
```

# Information about how the device functions

The device is a portable air-condition device with the possibility to use it for heating or cooling.

Manual in english here: https://www.netrauta.fi/attachments/products/outl1/ohje2-116-2-16.pdf

I have tried the yaml file and it works for me with my device.

One thing I didn´t manage to solve was that you need to toggle it to off before any mode toggling to turn it on. 
I made a workaround with an automation using service "Climate: Turn on" triggered by a change to any of the on modes e.g. "cool".
