### ISSUE TITLE
Request support for MakeGood/Witron 2 gang smart wall switch with power monitoring

### ISSUE THREAD

**Issue by jaymunro** [make-all/tuya-local#957]
# Log Message

```
Report this to https://github.com/make-all/tuya-local/issues/
Device matches simple_dual_switch_timer with quality of 50%. DPS: {"updated_at": 1690878119.2272758, "1": false, "2": true, "7": 0, "8": 0, "101": 0, "102": 93, "103": 213, "104": 2380}
Device matches None with quality of 0%. DPS: {"updated_at": 1690879302.549306, "104": 2380}
Device matches simple_dual_switch_timer with quality of 50%. DPS: {"updated_at": 1690879374.1637967, "1": false, "2": true, "7": 0, "8": 0, "101": 0, "102": 93, "103": 212, "104": 2380}
Device matches simple_dual_switch_timer with quality of 50%. DPS: {"updated_at": 1690879689.2542176, "1": false, "2": true, "7": 0, "8": 0, "101": 0, "102": 93, "103": 213, "104": 2360}
```

# Information about DPS mappings

```
{
  "result": {
    "model": "{\"modelId\":\"00000010dn\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power\",\"attribute\":\"20\"},\"name\":\"开关\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"switch_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-power\",\"attribute\":\"21\"},\"name\":\"开关 2\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},{\"abilityId\":7,\"accessMode\":\"rw\",\"code\":\"countdown_1\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"开关1倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"countdown_2\",\"description\":\"\",\"extensions\":{\"iconName\":\"icon-dp_time2\"},\"name\":\"开关2倒计时\",\"typeSpec\":{\"max\":86400,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"s\"}},{\"abilityId\":101,\"accessMode\":\"ro\",\"code\":\"add_ele\",\"description\":\"\",\"name\":\"增加电量\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":3,\"step\":100,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"度\"}},{\"abilityId\":102,\"accessMode\":\"ro\",\"code\":\"cur_current\",\"description\":\"\",\"name\":\"当前电流\",\"typeSpec\":{\"max\":30000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"mA\"}},{\"abilityId\":103,\"accessMode\":\"ro\",\"code\":\"cur_power\",\"description\":\"\",\"name\":\"当前功率\",\"typeSpec\":{\"max\":50000,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"W\"}},{\"abilityId\":104,\"accessMode\":\"ro\",\"code\":\"cur_voltage\",\"description\":\"\",\"name\":\"当前电压\",\"typeSpec\":{\"max\":2500,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"V\"}}]}]}"
  },
  "success": true,
  "t": 1690888215477,
  "tid": "fdd2da33305b11ee804ade073cb82c5d"
} 
```

“Query properties” gives:
```
{
  "result": {
    "properties": [
      {
        "code": "switch_1",
        "custom_name": "Garage",
        "dp_id": 1,
        "time": 1690886150913,
        "value": false
      },
      {
        "code": "switch_2",
        "custom_name": "Courtyard",
        "dp_id": 2,
        "time": 1690887270784,
        "value": true
      },
      {
        "code": "countdown_1",
        "custom_name": "",
        "dp_id": 7,
        "time": 1690886158732,
        "value": 0
      },
      {
        "code": "countdown_2",
        "custom_name": "",
        "dp_id": 8,
        "time": 1690876164082,
        "value": 0
      },
      {
        "code": "add_ele",
        "custom_name": "",
        "dp_id": 101,
        "time": 1690888409965,
        "value": 0
      },
      {
        "code": "cur_current",
        "custom_name": "",
        "dp_id": 102,
        "time": 1690888525973,
        "value": 93
      },
      {
        "code": "cur_power",
        "custom_name": "",
        "dp_id": 103,
        "time": 1690888530975,
        "value": 208
      },
      {
        "code": "cur_voltage",
        "custom_name": "",
        "dp_id": 104,
        "time": 1690888526181,
        "value": 2300
      }
    ]
  },
  "success": true,
  "t": 1690888533491,
  "tid": "bb6a8724305c11ee8c70fe98ebe72f12"
}
```

Countdown timer values are in whole seconds
cur_current is in mA
cur_power is in W x 10 (i.e. 208 is 20.8 W)
cur_voltage is in V x 10 (2300 is 230.0 V)

# Product ID

```
{
  "result": [
    {
      "active_time": 1690876155,
      "category": "kg",
      "create_time": 1690876155,
      "custom_name": "Garage lights",
      "icon": "smart/product_icon2/kg_1.png",
      "id": "64567173e868e768148a",
      "ip": "116.12.60.82",
      "is_online": true,
      "lat": "-43.5000",
      "local_key": "xxxxxxxxxxxxxxxxxx",
      "lon": "172.5700",
      "model": "",
      "name": "Two Switch",
      "product_id": "XdGCESvXTI5Mvfx2",
      "product_name": "2 Gang Switch",
      "sub": false,
      "time_zone": "+12:00",
      "update_time": 1690876189,
      "uuid": "64567173e868e768148a"
    }
  ],
  "success": true,
  "t": 1690888970174,
  "tid": "bfa02f87305d11ee8c70fe98ebe72f12"
}
```

# Information about how the device functions

[SSW-2G-BL01.pdf](https://github.com/make-all/tuya-local/files/12228675/SSW-2G-BL01.pdf)
https://www.witron.com.au/assets/brochures/SSW-2G-BL01.pdf

Perhaps this could be used to create a generic switch with power monitoring as the dps seem to match that of #956

**Comment by jaymunro** [comment]
I have it working locally now.

I added a file `generic_switch_dual_energy.yaml` to the devices folder with the contents:

```
name: Dual switch with timers and power monitoring
products:
  - id: XdGCESvXTI5Mvfx2
    name: 2 Gang Switch
primary_entity:
  entity: switch
  name: Switch 1
  dps:
    - id: 1
      type: boolean
      name: switch
secondary_entities:
  - entity: switch
    name: Switch 2
    dps:
      - id: 2
        type: boolean
        name: switch
  - entity: number
    name: Timer 1
    icon: "mdi:timer"
    category: config
    dps:
      - id: 7
        type: integer
        name: value
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
        unit: min
  - entity: number
    name: Timer 2
    icon: "mdi:timer"
    category: config
    dps:
      - id: 8
        type: integer
        name: value
        range:
          min: 0
          max: 86400
        mapping:
          - scale: 60
            step: 60
        unit: min
  - entity: sensor
    name: Current
    class: current
    category: diagnostic
    dps:
      - id: 102
        type: integer
        name: sensor
        unit: A
        class: measurement
        force: true
        mapping:
          - scale: 1000
  - entity: sensor
    name: Power
    class: power
    category: diagnostic
    dps:
      - id: 103
        type: integer
        name: sensor
        unit: W
        class: measurement
        force: true
        mapping:
          - scale: 10
  - entity: sensor
    name: Voltage
    class: voltage
    category: diagnostic
    dps:
      - id: 104
        type: integer
        name: sensor
        unit: V
        class: measurement
        force: true
        mapping:
          - scale: 10
```
