### ISSUE TITLE
Request support for Casafan_CeilingFan

### ISSUE THREAD

**Issue by k-welker** [make-all/tuya-local#999]
Here is my working .yml file for this ceiling fan w/o additional LED Module.
The color temperature of the LED is fixed (3.000K), so I marked it as hidden.
Maybe there will be other Modules in the future.
If you don't own the LED-Module, only primary_entity is needed.

### Links to vendor
[Motors](https://www.ventilator.de/deckenventilatoren/deckenventilatoren-wifi/eco-neo-iii-wifi)
[Lights](https://www.ventilator.de/deckenventilatoren/deckenventilatoren-wifi/eco-neo-iii-wifi/leuchten-eco-neo-iii-wifi)

### Data from iot.tuya.com
Product Name: Casafan_CeilingFan
Device ID: bf4871b1442cb066fahsm2
Product Category: fs
Protocol Version: 3.3

### YML-Content

```
name: Ceiling fan with LED Light
products:
  - id: qx9ovwpe9isccpb6
    name: Casafan ECO Neo III Wifi
primary_entity:
  entity: fan
  translation_key: fan_with_presets
  dps:
    - id: 1
      type: boolean
      name: switch
    - id: 3
      type: string
      name: oscillating
      mapping:
        - dps_val: nature_Off
          value: OFF
        - dps_val: nature_Low
          value: Low
        - dps_val: nature_Hi
          value: High
    - id: 3
      type: integer
      name: speed
      mode: slider
      range:
        min: 1
        max: 6
      mapping:
        - scale: 0.06
        - step: 1
    - id: 8
      type: string
      name: direction
      mapping:
        - dps_val: Forward
          value: Forward
        - dps_val: Reverse
          value: Reverse
    - id: 22
      type: string
      name: countdown
      mapping:
        - dps_val: Cancel
          value: OFF
        - dps_val: 1h
          value: 1h
        - dps_val: 2h
          value: 2h
        - dps_val: 3h
          value: 3h
        - dps_val: 4h
          value: 4h
        - dps_val: 5h
          value: 5h
        - dps_val: 6h
          value: 6h
secondary_entities:
  - entity: light
    dps:
      - id: 15
        type: boolean
        name: switch
      - id: 16
        type: integer
        name: brightness
        mode: slider
        range:
          min: 0
          max: 100
        mapping:
          - step: 10
      - id: 17
        type: integer
        name: colortemp
        hidden: true
        range:
          min: 0
          max: 100
```

#### Query Properties
```
{
  "result": {
    "properties": [
      {
        "code": "switch",
        "custom_name": "",
        "dp_id": 1,
        "time": 1692350544081,
        "value": true
      },
      {
        "code": "mode",
        "custom_name": "",
        "dp_id": 2,
        "time": 1692352091297,
        "value": "nature_off"
      },
      {
        "code": "fan_speed",
        "custom_name": "",
        "dp_id": 3,
        "time": 1692350387476,
        "value": 4
      },
      {
        "code": "fan_direction",
        "custom_name": "",
        "dp_id": 8,
        "time": 1692334991272,
        "value": "forward"
      },
      {
        "code": "light",
        "custom_name": "",
        "dp_id": 15,
        "time": 1692354997591,
        "value": false
      },
      {
        "code": "bright_value",
        "custom_name": "",
        "dp_id": 16,
        "time": 1692354994690,
        "value": 20
      },
      {
        "code": "temp_value",
        "custom_name": "",
        "dp_id": 17,
        "time": 1692352018852,
        "value": 0
      },
      {
        "code": "countdown_set",
        "custom_name": "",
        "dp_id": 22,
        "time": 1692351949882,
        "value": "6h"
      }
    ]
  },
  "success": true,
  "t": 1692360327003,
  "tid": "84b416933dbf11ee85b18e593a74ca03"
}
```

#### Query Things Data Model
```
{
  "result": {
    "model": "{\"modelId\":\"000003sm9a\",\"services\":[{\"actions\":[],\"code\":\"\",\"description\":\"\",\"events\":[],\"name\":\"默认服务\",\"properties\":[
{\"abilityId\":1,\"accessMode\":\"rw\",\"code\":\"switch\",\"description\":\"FAN OFF\",\"name\":\"OFF\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":2,\"accessMode\":\"rw\",\"code\":\"mode\",\"description\":\"韻律風 off (關閉韻律風)\\n韻律風 Low (1,2,3,4)\\n韻律風 Hi  ( 3,4,5,6)\\n\\n\",\"name\":\"韻律風\",\"typeSpec\":{\"range\":[\"nature_off\",\"nature_Low\",\"nature_Hi\"],\"type\":\"enum\",\"typeDefaultValue\":\"nature_off\"}},
{\"abilityId\":3,\"accessMode\":\"rw\",\"code\":\"fan_speed\",\"description\":\"1~6速\",\"name\":\"风速\",\"typeSpec\":{\"max\":6,\"min\":1,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":1,\"unit\":\"\"}},
{\"abilityId\":8,\"accessMode\":\"rw\",\"code\":\"fan_direction\",\"description\":\"FWD/REV\",\"name\":\"风向\",\"typeSpec\":{\"range\":[\"forward\",\"reverse\"],\"type\":\"enum\",\"typeDefaultValue\":\"forward\"}},
{\"abilityId\":15,\"accessMode\":\"rw\",\"code\":\"light\",\"description\":\"燈 ON/OFF\",\"name\":\"灯光\",\"typeSpec\":{\"type\":\"bool\",\"typeDefaultValue\":false}},
{\"abilityId\":16,\"accessMode\":\"rw\",\"code\":\"bright_value\",\"description\":\"\",\"name\":\"灯光亮度\",\"typeSpec\":{\"max\":100,\"min\":10,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":10,\"unit\":\"\"}},
{\"abilityId\":17,\"accessMode\":\"rw\",\"code\":\"temp_value\",\"description\":\"\",\"name\":\"灯光色温\",\"typeSpec\":{\"max\":100,\"min\":0,\"scale\":0,\"step\":1,\"type\":\"value\",\"typeDefaultValue\":0,\"unit\":\"\"}},
{\"abilityId\":22,\"accessMode\":\"rw\",\"code\":\"countdown_set\",\"description\":\"\",\"name\":\"倒计时\",\"typeSpec\":{\"range\":[\"cancel\",\"1h\",\"2h\",\"3h\",\"4h\",\"5h\",\"6h\"],\"type\":\"enum\",\"typeDefaultValue\":\"cancel\"}}]}]}"
  },
  "success": true,
  "t": 1692360158067,
  "tid": "1ff9af7a3dbf11ee9a70760d0d3c40d3"
}
```
